### ISSUE TITLE
[Suggestion] Change logo icon

### ISSUE THREAD

**Issue by itsjavi** [BoostIO/Boostnote#1006]
Hi this is more a visual suggestion than an issue, but for newcomers like me, by the icon It is sometimes hard to differentiate the app from a regular messaging app. If resembles too much the icon of other messaging apps like Telegram.

<img width="342" alt="screen shot 2017-10-23 at 3 04 21 pm" src="https://user-images.githubusercontent.com/122741/31890462-85095d9c-b803-11e7-9de5-bcfd30bacac6.png">

My suggestion is to find another logo that resembles more a "development" / "notes" / "recipes" / "snippets" app.
Thank you for this awesome tool.

**Comment by kazup01** [comment]
Hi @itsjavi , thanks for your suggestion!  But we have no plan that change icon.
