### ISSUE TITLE
Random words underlined

### ISSUE THREAD

**Issue by Parasrah** [BoostIO/Boostnote#1007]
## Problem
Words such as `feedbac` are underlined for no apparent reason.

## Example
![image](https://user-images.githubusercontent.com/14935550/31906409-45f9c7e6-b7ee-11e7-833d-8402812c0455.png)

**Comment by asmsuechan** [comment]
Hi, @Right2Drive. Thank you for reporting. I'll investigate it.

**Comment by Right2Drive** [comment]
Np, I'm on version 0.8.15 if that helps you out at all 😄

**Comment by asmsuechan** [comment]
This is the condition that this unexpected behavior happens: if the word is any of `{w| consisted of the combination of more than 7 letters from {a, b, c, d, e, f}}`

These words accept the condition: aaaaaaa, aabbccddee, aefffff
These words reject the condition: a, abcdefg

**Comment by xpac1985** [comment]
If that wasn't obvious - it seems to be some automatic underlining HEX values...

**Comment by Flexo013** [comment]
This issue no longer seems to exist on 0.15.3.
