### ISSUE TITLE
Losing focus means leaving editing mode

### ISSUE THREAD

**Issue by piefel** [BoostIO/Boostnote#1009]
When I change windows back and forth, Boostnote editor will change from editing mode to previewing mode. This requires another click into the window or always pressing Ctrl-E before I enter more text.

(Using Ubuntu Linux.)

**Comment by asmsuechan** [comment]
Hi, @piefel. Is your issue solved by https://github.com/BoostIO/Boostnote/pull/283? 
ref: https://github.com/BoostIO/Boostnote/issues/960#issuecomment-336595755

**Comment by piefel** [comment]
Indeed, #960 is the exact same issue. Thanks for pointing that out!

I might add that I did not expect that functionality behind a _lock_ icon with the tooltip text _Lock_. OK, whatever icon, but the tooltip text could really be a bit more descriptive.
