### ISSUE TITLE
Be able to change width of the tab.

### ISSUE THREAD

**Issue by memnoth** [BoostIO/Boostnote#101]
![2016-08-27 22-05-49](https://cloud.githubusercontent.com/assets/18240966/18027595/1e2787cc-6ca3-11e6-929b-a2025ee5b3ee.png)

탭 사이즈 조절이 가능했으면 좋겠습니다.
**semester 2nd of 3rd Year** 같이 긴 문장을 작성할 경우 짤리게 됩니다.

항상 잘 쓰고 있습니다, 고맙습니다!

**Comment by Rokt33r** [comment]
피드백 감사합니다! #68 에 추가해뒀습니다.
얼른 적용되도록 노력해 볼게요!

**Comment by Rokt33r** [comment]
![screen shot 2016-09-08 at 10 37 21 pm](https://cloud.githubusercontent.com/assets/5865853/18351366/d99b9e06-7614-11e6-9e8f-8ab39b1ab09b.png)

이번 주말 적용됩니다!

**Comment by Rokt33r** [comment]
늦어져서 죄송합니다 적용되었습니다!
