### ISSUE TITLE
[Feature Request] Add more support for 3rd party cloud integration for sync feature

### ISSUE THREAD

**Issue by miickiie** [BoostIO/Boostnote#1012]
Add more support for 3rd party cloud integration for sync feature apart from Dropbox
Box and Google Drive, for instance

**Comment by asmsuechan** [comment]
Hi, @miickiie. Do you mention about Boostnote mobile? If so, please open an issue on https://github.com/BoostIO/boostnote-mobile.
If you mentioned Boostnote, you can already share notes via file-based storages such as Google Drive. ref: https://github.com/BoostIO/Boostnote/wiki/Cloud-Syncing
