### ISSUE TITLE
Feature request: Add keystroke support

### ISSUE THREAD

**Issue by gustavoriveray** [BoostIO/Boostnote#1015]
Please add support for Markdown keystrokes.

when typing something like:

`<kbd>shift</kbd> + <kbd>command</kbd> + <kbd>3</kbd>`

we should get something like 

<kbd>shift</kbd> + <kbd>command</kbd> + <kbd>3</kbd>

**Comment by filoxo** [comment]
I'd like to take a stab at this.

**Comment by kazup01** [comment]
This feature is created by @filoxo !🎉 #1019

**Comment by kazup01** [comment]
Thanks for your waiting! Boostnote v0.8.16 is out. Enjoy!
#1027
