### ISSUE TITLE
Possible bug in update required pop-up

### ISSUE THREAD

**Issue by pesap** [BoostIO/Boostnote#1024]
Hello there,
I installed the Boostnote app for macOS via https://boostnote.io/#download. Once it finished installing and open a notification says: update found! preparing to update...

After a few seconds, a second notification inside Boostnote appears:

![image](https://user-images.githubusercontent.com/2238996/32083083-f9619308-ba74-11e7-9eff-4ed9ffa73fbd.png)

When I click restart & install, the app closes and then nothing happens. The app does not restart and when I try to open again it appears again the update found. If I click not now, the notification disappears but then appears again and if closed again, a small icon at the bottom right of the UI appears.

![image](https://user-images.githubusercontent.com/2238996/32083160-8d509f5a-ba75-11e7-9d0b-66894d551a35.png)

If I close and open the app this problem persists and it is annoying. Any suggestions? I am using a MacBook Pro with macOS High Sierra 10.13

Thank you!

**Comment by kazup01** [comment]
Sorry for inconvenience. I couldn't reproduce it.
Could you re install from website? The latest version(v0.8.16) is attached, so please try it.
https://boostnote.io/

**Comment by pesap** [comment]
Thank you! Now it works as expected!
