### ISSUE TITLE
Import notes by dragging files

### ISSUE THREAD

**Issue by tridc** [BoostIO/Boostnote#1028]
Currently, when creating new folder I cannot import notes (md files) by dragging into the empty pane. I can only do that after creating a new note

**Comment by CSJedi** [comment]
Let me try this

**Comment by petKitsune** [comment]
Boostnote 0.8.16
Win7 64x

same on [file>import>...]
I need to create a new note first before I can import md 
drag and drop does not work at all

**Comment by kazup01** [comment]
I reproduced it.

**Comment by tatoosh** [comment]
Same here: Windows 10 x64 with Boostnote v0.8.16.
I just have to create a first empty note.

**Comment by arthurlacoste** [comment]
I have the same issue on Windows 10 x64 with Boostnote v0.8.16.
