### ISSUE TITLE
Keyboard Markdown freeze

### ISSUE THREAD

**Issue by Hedronmx** [BoostIO/Boostnote#1029]
If I use the bracket way of inserting keyboard shortcuts twice, boost note freezes.
So if I add [[a]] and then when I do two brackets [[ it freezes. you have to be really quick to not freeze the software.

Running boost note on Elementary OS

![Imgur](https://i.imgur.com/GL4loC8.png)

**Comment by RyoYokoyama** [comment]
I reproduce this bug, too.

**Comment by yamash723** [comment]
This bug cause is the `markdown-it-kbd` plugin.

I fixed this and send Pull Request for `markdown-it-kbd` repo.
Please wait for PR to be merged.

**Comment by kazup01** [comment]
Cool!

**Comment by kazup01** [comment]
v0.8.17 is out! I wrote the release note. https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2

Thanks @Hedronmx and @yamash723 :)
