### ISSUE TITLE
Sort notes and folders

### ISSUE THREAD

**Issue by robertomarcal** [BoostIO/Boostnote#103]
Would be great if we could sort notes and folders alphabetically.

**Comment by Rokt33r** [comment]
Fine! Btw, How many folder you are using? If possible, could you show me a screenshot of your workspace? I just want to know how our users are using Boostnote.

**Comment by robertomarcal** [comment]
I don't have a lot of saved notes yet.

I have been looking for a way to organize my dev notes til I found Boostnote.
So far I was keeping in text files. I have 18 folders with about 200 notes to move to it.

**Comment by Rokt33r** [comment]
@robertomarcal Thanks for your answer. It is so helpful! 👍

**Comment by sami3d** [comment]
I would love the same features .... heres my screenshot  ... http://i.imgur.com/FnrWuBF.png ... also thanks for bringing back the dark ui :)

**Comment by robertomarcal** [comment]
@Rokt33r I saw the new sort option for the notes in the last update. Thanks.
The folders I managed by editing the JSON file. :)

**Comment by kazup01** [comment]
Finally, @sosukesuzuki added the feature that sort folders by drag & drop. We will add it at next update!
