### ISSUE TITLE
Strange spacing under CodeEditor

### ISSUE THREAD

**Issue by RedBug312** [BoostIO/Boostnote#1031]
I found a stange spacing under CodeEditor the component, which only showed up in Snippet note mode. The spacing will reveal the preview part under the editor part.

Then I found the css rule causing this:
```css
.CodeMirror {
  height: 96%;
}
```
And the corresponding stylus rule is at line 94 of `Boostnote/browser/main/global.styl`.

Although changing the value to `100%` would solve the problem, but why did the value left as `96%`?

**Screenshot**
![2017-10-30 13-22-21](https://user-images.githubusercontent.com/11537681/32155983-9ab1a786-bd75-11e7-914c-51bcdebd0bfb.png)

The environment is:
- OS: Ubuntu 17.04 x86_64
- node: v6.11.5

**Comment by asmsuechan** [comment]
ref: https://github.com/BoostIO/Boostnote/commit/4e90a93b30758af59243b9c1b93df4f564b67d16

Can you tell me why you think this is a problem? (It's just a question)

**Comment by RedBug312** [comment]
In the screenshot, there's a line of rendered Markdown preview component, showing up below editor component, as the area not highlighted by blue background in picture.
I thought it might disturb users editing snippet notes, so I think it better to completely hide preview component under edit mode.

**Comment by kazup01** [comment]
I will fix this by the next update. Thank you for your report!

**Comment by asmsuechan** [comment]
It seems the 96% is correct now (on the current master branch).
![image](https://user-images.githubusercontent.com/11307908/32492826-f4498e5a-c3fe-11e7-9214-7e28080959da.png)

**Comment by RedBug312** [comment]
The problem seemed related to window height, for it happens when I maximize the window as 1920*1080.

Tested on master branch 2 days ago, the problem happens in snippet note, under edit mode, preview content reaches the bottom of window, and the highlighted `<div>` element has height over than about 530px
