### ISSUE TITLE
Right-click context menu not showing up

### ISSUE THREAD

**Issue by Mindstormer619** [BoostIO/Boostnote#1034]
## Issue

Right-click context menu does not appear on right-clicking a note. That's about it.  
In fact I did not even know there was a right-click menu until I saw it in the feature set for latest version.

## Stats

+ **OS:** Windows 10
+ **Version:** 0.8.16

## Screenshot

![](https://i.imgur.com/F6I5Cya.jpg)

**Comment by kazup01** [comment]
I reproduced it. This bug is occur on list view.
