### ISSUE TITLE
Attaching existing storage in OneDrive not working

### ISSUE THREAD

**Issue by albertoarmida** [BoostIO/Boostnote#1035]
Installing Boostnote on my laptop and attaching existing storage (saved in OneDrive) not show folder and notes (see image below).

![image](https://user-images.githubusercontent.com/18306018/32172712-d4397b1c-bd7c-11e7-9818-cfd059c596e4.png)

Also adding storage from Preferences -> Storages etc will show same issue.

**Comment by kazup01** [comment]
Hi @albertoarmida, did you try this procedure? https://medium.com/boostnote/cloud-syncing-backups-5b138f30e1dc

**Comment by albertoarmida** [comment]
Yes, of course. In my desktop PC it works like a charm, but not on my laptop.

**Comment by kazup01** [comment]
@albertoarmida  Thanks for trying it. I will investigate this cause.

**Comment by teatwig** [comment]
Same problem, I can't even create a new storage in OneDrive.
If I copy the folder out of OneDrive it works without problems.

**Comment by MightyBright** [comment]
I had similar problem with my new PC. 
Disabling OneDrive's On-Demand Setting solved my problem.

Check your OneDrive setting by right-clicking OneDrive icon on your task bar.
Go to Settings tab and disable Files On-Demand Setting.

https://support.office.com/en-us/article/Learn-about-OneDrive-Files-On-Demand-0E6860D3-D9F3-4971-B321-7092438FB38E

Hope this helps... :)

**Comment by Flexo013** [comment]
Is this still an issue @albertoarmida ?

**Comment by albertoarmida** [comment]
Yes, I still have the problem.

**Comment by Flexo013** [comment]
Are you syncing just the the `notes` folder or the folder containing `notes/`, `attachtments/`, and `boostnote.json`?

**Comment by Flexo013** [comment]
@albertoarmida Can you answer the question I asked above?
