### ISSUE TITLE
archive notes

### ISSUE THREAD

**Issue by takumaniihara** [BoostIO/Boostnote#104]
First of all thanks for the great application. I use this application every day on my Windows desktop and Linux laptops.

Is it possible to add archive function to this application?(just like gmail and google keep)
When I am "done" with a note I put that note to folder named Archive.
But there are some problem with this.
After I put the notes in Archive folder, I do not want the notes in that folder shown in All Notes section.(but able to search the archived notes)
Also, when I use Archive folder, I can not un archive the notes when I forgot the original folder name.

**Comment by Rokt33r** [comment]
Thanks for your suggesting. It is a good idea.

But, before shipping, we have to discuss this issue a little more.

> Searching archived note

I think the archived notes should be searched when the user set some flags(including archived notes or filtering archived notes only).

And I have one more thing to discuss. **When original folder deleted, how to handle the archived note?**
Currently, I'm going to recreate the folder by the original key of note.(It might not be able to revive name and color of the deleted folder)

**Comment by takumaniihara** [comment]
Thanks for the reply.

> I think the archived notes should be searched when the user set some flags(including archived notes or filtering archived notes only).

I think using flags is a great idea and also default searching setting would be great (e.g. default search include archived note or not). 
I prefer default search include archived notes, because right now i have not many notes in archived folder. When I got many notes in archive folder, I would prefer default search not include archived notes.  

> When original folder deleted, how to handle the archived note?

This never crossed my mind. 

>I'm going to recreate the folder by the original key of note

I think this would be good way of handling archived notes which original folder has deleted.

**Comment by Rokt33r** [comment]
Great! We might be good to go.

**Comment by kazup01** [comment]
I close this because this issue has been left untouched.

**Comment by sferra** [comment]
I was just about to open a new ticket requesting this feature when I found this ticket. I hope that it will be reopened at some point if people show interest in the "archive note" functionality.

I also think that note archival could be implemented quite simply, by assigning a special "archived" tag to notes (similar to the "star" property) and enabling to toggle the appearance of notes tagged in such a way. That way it shouldn't be necessary to move notes around or replicate directory structures. It might be even possible to let the user decide if additional tags should behave the same as the "archived" tag.
