### ISSUE TITLE
"Boostnote v0.8.16 has been released" stuck in bottom right corner

### ISSUE THREAD

**Issue by KadeG** [BoostIO/Boostnote#1045]
The update notification for v0.8.16 seems to be stuck in the bottom right hand corner. This is on v0.8.16. 

![image](https://user-images.githubusercontent.com/7104361/32203584-28b2671e-bdb2-11e7-926f-e7d71fe9a87f.png)

**Comment by kazup01** [comment]
Hi @KadeG , this is a link to this blog.
https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-16-has-been-released-783afea95ca3

**Comment by KadeG** [comment]
Any change we can get an option to remove it in general or specifically after updating?
