### ISSUE TITLE
Inline math

### ISSUE THREAD

**Issue by notaduck** [BoostIO/Boostnote#1047]
Is it me there is doing something wrong while trying to do inline math?

If I include "$$ \therefore $$$ Sokrates er dødelig (konklusion)" in a note then I will get a 
```
KaTex parse error: Expected "EOF", got '$' at position 12: \therefore $$$ Sokrates er ....

```

**Comment by asmsuechan** [comment]
What you want is this.
```
$$\therefore$$ Sokrates er dødelig (konklusion)
```

![image](https://user-images.githubusercontent.com/11307908/32276828-c5912492-bf53-11e7-9609-4e843d54d298.png)

**Comment by ikelaiah** [comment]
I confirm that the inline math works
```
$$\therefore$$ Sokrates er dødelig (konklusion)
```
