### ISSUE TITLE
Save and Get data from api

### ISSUE THREAD

**Issue by absalan** [BoostIO/Boostnote#105]
Hi Guys,

I'm trying to create a server based API for this app and save and receive the data trough API and release it as free service for this app.
So I need to know where are the save and get methods or functions that I can change with API post and ... 

Thanks

**Comment by Rokt33r** [comment]
It will be renewed from the next release.Check this brach. 
https://github.com/BoostIO/Boostnote/tree/data-api-refactor/browser/main/lib/dataApi
