### ISSUE TITLE
Invalid font-family

### ISSUE THREAD

**Issue by reidstidolph** [BoostIO/Boostnote#1050]
After upgrading to boostnote_0.8.16_amd64.deb on my Ubuntu 17.10/Gnome3 system and setting a custom preview font-family, I'm seeing it unable to render preview fonts due to an invalid font-family property. It seems like the setting of `Microsoft YaHei` has 2 single quotes on either side of it, causing the font-family setting to be invalid. When I remove one of the sets of single quotes manually within the dev console, it reads/renders properly.

With the following configuration:
![image](https://user-images.githubusercontent.com/2548047/32283683-4a7225ca-bee2-11e7-9d9e-200ea169904f.png)
Font-family gets set to: `'Montserrat','meiryo',''Microsoft YaHei'','helvetica','arial','sans-serif'`
...which throws an "invalid property value" error for the font-family style of the body html tag:
![image](https://user-images.githubusercontent.com/2548047/32284181-a04e56f2-bee3-11e7-8bdf-5299d16ee5d3.png)

This change may have something to do with it perhaps? https://github.com/BoostIO/Boostnote/commit/7e2f0049b638930bd4c09c0b5b2edee46bffb82b#diff-a54dec67725b3e604a34d39a7fcb72f6

**Comment by yosmoc** [comment]
Hi @reidstidolph,

It seems it has already been fixed in this [commit](https://github.com/BoostIO/Boostnote/commit/bfa8db7b55d6b7549203be5010c7462adfc911d1).

**Comment by kazup01** [comment]
v0.8.17 is out! Thank you @reidstidolph and @yosmoc 👍

**Comment by reidstidolph** [comment]
Just updated, and it looks good! Thanks @kazup01 !!
