### ISSUE TITLE
Note Links Broken?

### ISSUE THREAD

**Issue by kenthannigan** [BoostIO/Boostnote#1051]
I noticed my links to notes weren't working, so i installed a fresh copy of Boostnote 0.8.16 on a VM and the links still don't work. Is anybody else having this issue? Did link syntax change but the info tab did not update the syntax?

![img-361](https://user-images.githubusercontent.com/16963630/32285422-93ee3bf8-bf00-11e7-9d09-9d06303cd856.png)
![img-362](https://user-images.githubusercontent.com/16963630/32285424-971e3ac6-bf00-11e7-8395-58919014b8cb.png)

The console log output shows `list:jump` and `list:moved` but nothing happens.
![img-368](https://user-images.githubusercontent.com/16963630/32285427-9a7a2ee6-bf00-11e7-9844-12d84c317656.gif)

**Comment by asmsuechan** [comment]
Hi, @kenthannigan. I confirm this bug. It occurs because the hash of storages sometimes changes. So I'll investigate the timing and solve it.

**Comment by NamedKitten** [comment]
Can reproduce, hasn't worked for a while for me.

**Comment by whizark** [comment]
Some actions change storage/note hash (<storage-hash>-<note-hash>), so it seems that note linking feature should also replace the hash links (or change hash to UUID would be better).

* move a note to a folder (changes note hash)
* move a note to a folder in storage (change storage and note hash)
* migration from V6 (changes storage and note hash)

**Comment by kazup01** [comment]
This bug was fixed and released at v0.8.20.
[Release Note](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd)

If there is still sone problems, feel free to reopen this issue. Thanks!
