### ISSUE TITLE
[Feature] An option to copy and paste link/images from html format into markdown automatically.

### ISSUE THREAD

**Issue by ikelaiah** [BoostIO/Boostnote#1053]
At the moment, when I copy and paste a link from Stackoverflow it appears as

```
How do you reindex an array in php
```
Boostnote *only* copies the text. Which is great in most cases. 👍 

Wouldn't it be more useful if you could grab the link and format it as the following?

```
[How do you reindex an array in php](https://stackoverflow.com/questions/591094/how-do-you-reindex-an-array-in-php)
```

For images, Boostnote could grab the link and paste as

```
![](https://blog.toggl.com/wp-content/uploads/2017/04/toggl-how-to-kill-the-dragon-with-9-programming-languages.jpg)
```

**Comment by ikelaiah** [comment]
Perhaps, a context right-click menu that give options;
>
> * paste as plain text (default)
> * paste special (or something...)
>

**Comment by kazup01** [comment]
Sounds good.

**Comment by jan-schulz-k24** [comment]
I would alos love to have "paste image" which would grab the image from the clipboard, save it somewhere and insert the md string (with a relative path!) to show it in the file

**Comment by j9ac9k** [comment]
In addition to +1'ing this feature request, I was hoping this feature could encompass text as well

There is a fantastic website: https://euangoddard.github.io/clipboard2markdown/

You paste markdown rendered html text/links and it will give the markdown text so you can preserve the markdown formatting

for example, if I copy this text
<img width="1093" alt="screen shot 2018-06-10 at 9 37 26 am" src="https://user-images.githubusercontent.com/646398/41203864-05457110-6c92-11e8-81fd-c7282179ef3e.png">

paste it into the website above, it will give me the following output:

```markdown
### Constant Rate Factor (CRF)[](https://trac.ffmpeg.org/wiki/Encode/H.265#ConstantRateFactorCRF "Link to this section")

Use this mode if you want to retain good visual quality and don't care about the exact bitrate or filesize of the encoded file. The mode works exactly the same as in x264, so please read the [H.264](https://trac.ffmpeg.org/wiki/Encode/H.264#crf) guide for more info.

As with x264, you need to make two choices:

-   Choose a CRF. The default is 28, and it should visually correspond to libx264 video at CRF 23, but result in about half the file size. Other than that, CRF works just like in x264.

-   Choose a preset. The default is `medium`. The preset determines how fast the encoding process will be -- at the expense of compression efficiency. Put differently, if you choose `ultrafast`, the encoding process is going to run fast, but the file size will be larger when compared to `medium`. The visual quality will be the same. Valid presets are `ultrafast`, `superfast`, `veryfast`, `faster`, `fast`, `medium`, `slow`, `slower`, `veryslow` and `placebo`.

-   Choose a tune. By default, this is disabled, and it is generally not required to set a tune option. x265 supports the following `-tune` options: `psnr`, `ssim`, `grain`, `zerolatency`, `fastdecode`. They are rexplained in the [H.264 guide](https://trac.ffmpeg.org/wiki/Encode/H.264#crf).

For example:

ffmpeg -i input -c:v libx265 -crf 28 -c:a aac -b:a 128k output.mp4

This example uses AAC audio at 128 kBit/s. This uses the ffmpeg-internal encoder, but under [AAC](https://trac.ffmpeg.org/wiki/Encode/AAC) you will find info about more options.
```

If boostnote couple copy markdown rendered HTML, and paste the RAW markdown text into boostnote, that would be an awesome feature!

**Comment by Flexo013** [comment]
The current version of Boostnote support pasting links and images from clipboard:

```md
[Paste to Markdown](https://euangoddard.github.io/clipboard2markdown/)

![86a00c73.png](:storage\fa37dce2-8783-4b66-b5ce-5d8f41ba4aec\86a00c73.png)
```
