### ISSUE TITLE
Crashed on start with blank UI

### ISSUE THREAD

**Issue by tridc** [BoostIO/Boostnote#1056]
Boostnote 0.8.16 on my macbook has this issue after a hanging. Reinstall does not resolve the problem. Please help me to check this.
<img width="1280" alt="screen shot 2017-11-03 at 9 41 36 pm" src="https://user-images.githubusercontent.com/3231854/32379492-3ee6954c-c0e0-11e7-9146-02f818670d8c.png">

**Comment by kazup01** [comment]
Hi @tridc , I do not know why it occurring.
Could you attach the image of console error?

**Comment by tridc** [comment]
Here is console output
<img width="1280" alt="screen shot 2017-11-04 at 9 12 15 am" src="https://user-images.githubusercontent.com/3231854/32401418-5491c2da-c140-11e7-93f6-2f6905737c21.png">

**Comment by kohei-takata** [comment]
@tridc Did you try `cmd + R` ?

**Comment by asmsuechan** [comment]
Probably one of Boostnote Helper process is dead.

**Comment by tridc** [comment]
> @tridc Did you try cmd + R ?
Yes, but it doesn't help
Open Console on MacOS, I reveal a crash file. Maybe it would help to debug

[Boostnote Helper_2017-11-04-130858_MacBot.crash.zip](https://github.com/BoostIO/Boostnote/files/1443056/Boostnote.Helper_2017-11-04-130858_MacBot.crash.zip)

**Comment by asmsuechan** [comment]
Thank you for the information. According to my search, there are some probabilities of the cause. So, please give us your machine(OS/CPU/RAM) information.

And, one of them is that Boostnote arises memory leak...
https://github.com/electron/electron/issues/5410#issuecomment-217351054
Did you see any symptoms of memory leak?

**Comment by incace** [comment]
I am experiencing this all of a sudden. 0.15.3 on macOS. Boostnote Helper crashing 3 times and eventually the window loads. Not sure why?

**Comment by Flexo013** [comment]
Does this also occur with older versions?

**Comment by arcturus140** [comment]
does it also crash after launching Boostnote with admin rights?
