### ISSUE TITLE
Cannot import into a specific folder

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#1057]
Video of problem (problem workflow first, then working workflow): http://www.youtube.com/watch?v=3kf_k5wTzNQ

Repro steps:

1. Select a folder (one of the storage options)
2. File > Import From > *select a file*
3. Nothing happens

**Here is a *working* workflow for import:**

1. Select the "All Notes" category
2. File > Import From > *select a file*
3. File successfully imports

------

System Info:

Windows 10.0.16299 (Windows 10 Pro Build 16299 x64)
Boostnote: 0.8.16? **(would be helpful to have an "About" under "Help" menu to see which version I'm using)**

**Comment by kazup01** [comment]
Hi @derekantrican , thank you for your reporting.
You can import files after make at least one note at the specific folder.
#1028

<img width="531" alt="screen shot 0029-11-04 at 4 18 54 am" src="https://user-images.githubusercontent.com/8602615/32392006-59bbe642-c117-11e7-8130-4aab2a30937f.png">

**Comment by derekantrican** [comment]
Ok, that's odd. Will this be changed in the future?

**Comment by kazup01** [comment]
Yes we will fix it.
