### ISSUE TITLE
Cannot Consistently Import Files

### ISSUE THREAD

**Issue by GaryFurash** [BoostIO/Boostnote#1059]
OS : Windows 7
Issue: If I delete all my %APPDATA% Boostnote Files, then reinstall boostnote, I can Import from Text once. Once I've done one import, I can no longer Import (It Opens the File Finder Window, and lets me select files, but nothing happens).

**Comment by GaryFurash** [comment]
Whoops, ignore that! It turns out there's a big time delay, then you see the files, so it's fine. Sorry.

**Comment by GaryFurash** [comment]
So what actually happened is after I uploaded a set, I uploaded a second set. After I reloaded / restarted, it had REMOVED all my prior imports and then imported the new stuff.

Also, is there any way to get them to import as gists?

**Comment by kazup01** [comment]
Hi @GaryFurash , there is none import files to gists (GitHub Gist?) now, but we will implement it later.

**Comment by GaryFurash** [comment]
Apologies. I'm just trying to import text/md files from the file system.

If, after importing a bunch of files into the file system, I try to AGAIN import some more files from the file system, I get weird behavior (like the first set of imported files disappearing

**Comment by benhourigan** [comment]
Hi there. I'm having a similar problem: trying to import about 2000 .txt and .md files from my nvalt folder. Got a long beachball (macOS 10.13) and then saw I had 500--600 files in Boostnote from the import. Deleted them and tried again, now none of the files appear after the import, even if I wait a long time. v0.8.16.

**Comment by Flexo013** [comment]
I can import notes fine using 0.12.1 on Windows 10.

@GaryFurash If you are still experiencing this issue then feel free to open a new issue for the problem.
