### ISSUE TITLE
Issues with select notebook dropdown (filter not working and no scrollbar)

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#106]
Hello. 
When viewing a note, in the dropbown to select the folder, the filter does not work. Also when I have too many folders, the list dont display all of them, and no scroll appears.

**Comment by Rokt33r** [comment]
I'll check it. Could you attach some screenshots?

**Comment by brpaz** [comment]
Sure.

Here it an example

![imgur](http://i.imgur.com/qCI9U5Z.jpg)

**Comment by Rokt33r** [comment]
@brpaz Oh... I'll fix it in this week. Sorry for the inconvenience.

**Comment by Rokt33r** [comment]
Fixed. It will be shipped on this Saturday
