### ISSUE TITLE
All fonts in dialog windows are blocks rather than characters (missing font?)

### ISSUE THREAD

**Issue by Hubro** [BoostIO/Boostnote#1063]
All fonts in system dialog windows have blocks rather than characters.

I just installed Boostnote version 0.8.16-1 (deb) from the website. When I click "..." to browse for a storage directory, this pops up:

![image](https://user-images.githubusercontent.com/597206/32408280-bfe1b4b4-c195-11e7-9eed-c00083514e86.png)

When I click "New note" without a storage set up (which obviously is an error) this shows up:

![image](https://user-images.githubusercontent.com/597206/32408284-dc2669d0-c195-11e7-91e6-5aad6d96055f.png)

So it's not just the browse dialog. No errors are displayed in the developer tools or the terminal.

I'm using Ubuntu 17.10 (Artful Aardvark).

<pre>
$ uname -a
Linux cross 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
</pre>

I'm guessing this is actually an issue with whichever library Boostnote/Electron uses for displaying dialogs rather than with Boostnote itself, but I have no idea where else to report this issue.

**Comment by asmsuechan** [comment]
Please refer this: https://github.com/BoostIO/Boostnote/issues/964
