### ISSUE TITLE
Single click edit mode is little aggressive

### ISSUE THREAD

**Issue by tekjar** [BoostIO/Boostnote#1066]
Hi. Thanks a lot for boostnote. 

Single click on content pane takes me to edit mode. People tend to single click after selection (or in general) which takes them to edit mode. This is very annoying during reading. What do you think of write locks by default (or) double click for going  to edit mode?

**Comment by asmsuechan** [comment]
You can change into right-click, and double-click will be implemented soon.
![image](https://user-images.githubusercontent.com/11307908/32413888-f0bbc5c0-c25d-11e7-8425-be954e5af32d.png)

**Comment by tekjar** [comment]
Awesome. Thanks :)
