### ISSUE TITLE
Suggestion: Confirmation before deleting snippet note file/lock note

### ISSUE THREAD

**Issue by pcampbell-software** [BoostIO/Boostnote#107]
When I create a snippet note; and add a new file, it is very easy to delete this note as there is no confirmation. I've found I've accidentally mis-clicked on occasion and lost a note (this is quite easy to do if you have many code files in your code snippet note).

A confirmation box or the ability to lock a note would be ideal.

**Comment by Rokt33r** [comment]
I agree. I'll update on this week.

**Comment by Rokt33r** [comment]
Shipped! Confirmation dialog will appear when deleting a snippet with content.
