### ISSUE TITLE
Preview font not reflecting on changing in 8.16

### ISSUE THREAD

**Issue by rahulpathakgit** [BoostIO/Boostnote#1073]
When I change the Preview mode font then its not getting reflected in preview window. Its working for edit mode though.

![font setting](https://user-images.githubusercontent.com/10892516/32424893-3bde3494-c2d5-11e7-8b84-2074271cab39.png)
![screenshot from 2017-11-06 09-30-44](https://user-images.githubusercontent.com/10892516/32424894-3c1710f2-c2d5-11e7-8c7e-259aa662c4dd.png)

**Comment by kazup01** [comment]
Duplicate #1048
