### ISSUE TITLE
Display release version inside Boostnote

### ISSUE THREAD

**Issue by wolfheart** [BoostIO/Boostnote#1074]
I couldn't find any possibility to see the actual installed version of Boostnote. Please add a small dialog with this information. Maybe check for new versions in there too?
Thx!

**Comment by kazup01** [comment]
Hi @wolfheart , thank you for opening an issue.
We will improve update process.

You can check Boostnote version at menu. The latest version is v0.8.16.
https://github.com/BoostIO/Boostnote/releases
<img width="396" alt="screen shot 0029-11-07 at 12 12 01 am" src="https://user-images.githubusercontent.com/8602615/32447859-99a0e920-c350-11e7-9474-c9f3891377f9.png">

**Comment by yosmoc** [comment]
Hi @kazup01,

I think this menu is only available in OSX. 
https://github.com/BoostIO/Boostnote/blob/master/lib/main-menu.js

**Comment by wolfheart** [comment]
@yosmoc is right! I **can't** find that entry on Windows 10!

**Comment by Nino9614** [comment]
I can confirm that on Windows 10 there is no menu options but you can still see the version of boostnote 
in the preferences: 

![image](https://user-images.githubusercontent.com/27356972/32487195-40d4eba8-c3a9-11e7-9118-87411cafb032.png)

**Comment by wolfheart** [comment]
Thank you! Althou I couldn't find the preferences at the first glance, the version is displayed there.

Please add the preferences to the "Boostnote"-menu too.

**Comment by kazup01** [comment]
memo #916

**Comment by kazup01** [comment]
Please wait for the next update. Thank you!
