### ISSUE TITLE
Problem with install 

### ISSUE THREAD

**Issue by BartoszCoyote** [BoostIO/Boostnote#1077]
`2017-10-19 15:41:22> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\kazup\src\Boostnote\resources\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\kazup\src\Boostnote\resources\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\kazup\src\Boostnote\resources\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)`

Try to run install app while i already have installed Boostnote.

**Comment by kazup01** [comment]
Hi @BartoszCoyote , thank you for your report. Are you using Windows?

**Comment by BartoszCoyote** [comment]
Yes, windows 7 (x64) . I forgot i have already install boostnote and try to install new and error occured.

**Comment by kazup01** [comment]
Hi @BartoszCoyote , sorry for the late replying. Could you remove the old Boostnote package and reinstall current version? Maybe installation bug will not occur. Thanks.
