### ISSUE TITLE
Closing the app in windows doesn't quit / No quit shortcut

### ISSUE THREAD

**Issue by LordFlashmeow** [BoostIO/Boostnote#1078]
I know you changed this for macs so that the program doesn't quit when you close it, but it's super counter-intuitive on windows. In addition, there is no shortcut to quit, so the only way to quit the app is to click the Boostnote menu and select exit.

Even `Alt + F4` just hides the app. 

Is there a solution?

EDIT: I see that there is a commit to fix this. Looking forwards to it being implemented.

**Comment by arthurlacoste** [comment]
I've tried to use `Alt + F4` too, and I think this is a default behavior for any Windows apps.
