### ISSUE TITLE
Search does not search in tags

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#108]
I am not sure if this is a bug or a missing feature, but it appears that the search is currently not searching the tags, but only titles and text:

![test1](https://cloud.githubusercontent.com/assets/11869704/18342959/94593bae-75b1-11e6-9a9d-26147d7fbc1d.png)
![test2](https://cloud.githubusercontent.com/assets/11869704/18342960/9459e4fa-75b1-11e6-89db-f88ec8a1ec09.png)
![test3](https://cloud.githubusercontent.com/assets/11869704/18342961/945df072-75b1-11e6-8475-452ee5bfa7c7.png)

Searching the tags would be great, and I hope it's not much trouble to implement. I currently have no time to look at the source myself, I kinda feel that it should be straightforward.

I could not find another issue addressing this directly, please remove this if I was mistaken.

PS: Gotta say it. Boostnote is fantastic, thanks a lot for making this.

**Comment by Rokt33r** [comment]
It is a piece of cake for me. I'll ship it on this week. :)

**Comment by huettenhain** [comment]
Thanks a lot man, that's awesome.

**Comment by Rokt33r** [comment]
Sorry, I realized it has been implemented already. You can search notes by tag with `#` just like hashtag of twitter!
Sorry for the lack of tutorial. 😢

**Comment by huettenhain** [comment]
Alright. I guess I would prefer if the hashtag was not *required*, since I am using them as keywords. 

Adding a hashtag could still limit the search to tags, while the search searches both note and tags. However, this certainly depends on how you (intend to) use tags.

**Comment by Rokt33r** [comment]
Hmm...In fact, I've rarely been using tags. And, I think it can be offered as an option.
Could you tell me the ideal searching behavior of yours?

**Comment by huettenhain** [comment]
Sure, thanks a lot for being so forthcoming! I would say the following suits me best:
* Typing any text searches tags and note contents
* Typing text preceeded by a hashtag `#` searches tags only

Optionally, you can offer a third search option:

* Typing anything by `!` negates the statement, i.e. it restricts the search to results that do not match the text that follows

For example:

1. `#bash xargs` finds my notes tagged as `bash` and containing `xargs` anywhere  
2. `bash xargs` finds my notes containing `bash` and `xargs` anywhere, the results of (1) are a subset of the results obtained this way

And if you implement the third option:

3. `!#xargs xargs` finds everything that contains `xargs` but has not been tagged as `xargs`
4. `#xargs !xargs` finds everything that has been tagged as `xargs` but does not contain `xargs`

**Comment by Rokt33r** [comment]
Great! Applying all options doesn't seem to be harm. I'll ship it the next update on this weekend.
Thank you so much! 👍

**Comment by huettenhain** [comment]
Well actually, thank **you** so much! =)

**Comment by Rokt33r** [comment]
Shipped!
