### ISSUE TITLE
[Suggestion] Nightly Builds

### ISSUE THREAD

**Issue by flashmeow** [BoostIO/Boostnote#1080]
Would it be possible to have a nightly build of the master branch available somewhere? I'd love to be able to try out new features without having to deal with Git all the time.

**Comment by kohei-takata** [comment]
Hi @LordFlashmeow !
I will try to improve works of release and CI.
And when do that, I will keep nightly build in mind.
Thanks.

**Comment by Flexo013** [comment]
Thanks for your suggestion!

We are currently looking at solidifying the release and pre-release process of Boostnote. I like your suggestion of having an easy accessible nightly build.

I'm not quite sure if Boostnote is big enough to warrant such a feature. But giving everybody access to a latest version, with features that will be part of the next release, is part of the plan.
