### ISSUE TITLE
When pasting an image from the clipboard, boostnote also copies some of the text that was just typed

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#1086]
See this screen recording: http://www.youtube.com/watch?v=Wr1BGEyeDZA

Simply put, I had copied an image to my clipboard, typed some text, then pressed "Ctrl+V" to paste the image. Boostnote pasted the markdown-formatted image (as expected) but preceeded the image with some text that I had just typed (in the screen recording, you can see that a couple lines above it replicated the entire line that I had just typed before inserting the markdown-formatted image)

**Comment by kohei-takata** [comment]
#1119 is merged, so I close this issue.
