### ISSUE TITLE
folder note count shows the total number of notes in Boostnote after adding new note

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#1089]
Hello.
I found a strange issue today.
When I create a new note, and put in a folder, sometimes the folder count will display the total number of stored notes in Boostnote and if I open that folder it will display all the notes of all folders.

If I restart application, everything goes back to normal. 

This doesn't happen always. I couldnt find a pattern yet.
No errors in devtools.

**Comment by kohei-takata** [comment]
Are there anyone can reproduce this bug?
Please comment here.

**Comment by jmhibben** [comment]
Unfortunately, I'm not sure that I can reproduce the bug, but I've had a similar issue. One of my storage folders stopped reporting the correct number of notes prior to a hard close (similar to what is described in #1299). Additionally, that folder also stopped loading any note list and instead would simply display the last-viewed list of notes.

As the issue does not seem to reoccur shortly after opening, I suspect that it may be something caused when BoostNote is left open for quite some time (measured in hours or days). I've only had this happen once so far that I'm aware of, but having a folder go from reporting 8 to 35 (of 55) notes is certainly bizarre enough to report. I'll comment again if and when I notice this issue return.

System Info:
- Linux Mint 18.1 64-bit
- Cinnamon 3.2.7
- Linux Kernel 4.4.0-104

**Comment by Flexo013** [comment]
I can't reproduce this.

@brpaz If you still experience this issue then feel te either reopen this issue or make anew one.
