### ISSUE TITLE
Side Scrollbar is still showing on full screen/Full width

### ISSUE THREAD

**Issue by himaanshu24** [BoostIO/Boostnote#1091]
When I am switching to the full-width mode in Boostnote it is still showing the scrollbar of the sidebar. Please refer the attached screenshot.

![image](https://user-images.githubusercontent.com/8476966/32594715-131fbc0a-c553-11e7-9d72-cb7c88ceb48d.png)

This is easily reproducible each and every time we switch to the full-width mode from sidebar mode.

**Comment by kazup01** [comment]
Hi @himaanshu24 , thank you for your info. What version of Boostntoe are you using?

**Comment by himaanshu24** [comment]
The version is 
![image](https://user-images.githubusercontent.com/8476966/32696345-d0264202-c79b-11e7-9141-37a808802122.png)

**Comment by kazup01** [comment]
Hi @himaanshu24 , sorry for long absence.
How about latest version, v0.8.17? This error is not occurring my environment - macOS and Windows.
If this bug still occurring, please feel free talk to me :)

**Comment by alkarn** [comment]
Hello @kazup01. Big fan of Boostnote myself I have the same problem. I am using Boostnote 0.8.18 on Ubuntu 16.04 and the scrollbar is still showing in full width, both on view and on edit mode.

![boostnote-bug-edit-mode](https://user-images.githubusercontent.com/14148361/33761108-abdbd05e-dc10-11e7-9a70-0e383da40ae7.png)
![boostnote-bug-view-mode](https://user-images.githubusercontent.com/14148361/33761109-ac031d08-dc10-11e7-8b47-41a83deb8a06.png)

Thanks!

**Comment by Flexo013** [comment]
This is no longer an issue in 0.12.1.
