### ISSUE TITLE
Boostnote still resides in taskbar after closing to tray.

### ISSUE THREAD

**Issue by AOne-T** [BoostIO/Boostnote#1095]
The default application behavior when closing via close button (Windows) minimizes it to tray, but the application is still in the taskbar. 
Suppose this should be configurable. Whether the app should minimize to tray or should it still be in taskbar.

**Comment by kazup01** [comment]
Hi @AOne-T , please wait for the next update. https://github.com/BoostIO/Boostnote/pull/1043

**Comment by kazup01** [comment]
v0.8.17 is out! I wrote the release note. https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2
Enjoy :)
