### ISSUE TITLE
Cannot edit synchronized notes

### ISSUE THREAD

**Issue by enriro** [BoostIO/Boostnote#1099]
Cannot edit notes on iPhone (iOS 10.3.3) created on Mac and synchronized via Dropbox.

**Comment by kazup01** [comment]
Enable you to edit the note even when dropbox sync at next update. https://github.com/BoostIO/boostnote-mobile/pull/75 Thank you for your waiting!

Please post mobile's issue here. https://github.com/BoostIO/Boostnote-mobile
