### ISSUE TITLE
Feature Request - Preview Enhancements

### ISSUE THREAD

**Issue by jordankaiser** [BoostIO/Boostnote#1103]
First, thanks for the great project! I've been looking for a markdown note taking app and this is really great! I'm enjoying it a lot so far. I thought of a couple enhancements that I think could be helpful.

# Keyboard shortcut for the Markdown Preview

When typing long notes it's often helpful to me to see the formatted markdown as it's easier to parse at a glance.

# Even better, simultaneous markdown writing and preview panes!

I enjoy being able to see the formatted markdown as I'm writing it and while being able to toggle quickly between the two views is helpful having them up at the same time is even better.

VS Code and Gitbooks have some good implementations of this feature.

Thanks for your great work on this project!

**Comment by kohei-takata** [comment]
Hi @jordankaiser !
Thanks for your opening an issue, and enjoying Boostnote!

Could you tell me a little more about `Keyboard shortcut for the Markdown Preview` or paste some screenshots?
I cannot imagine that feature.

The second feature is implemented to some markdown editor, isn't it?
I will talk about the feature and how to implement with core member.

**Comment by jordankaiser** [comment]
H @kohei-takata !

I'm happy to provide more details.

For ```Keyboard shortcut for the Markdown Preview``` see the screenshot below. What I suggest would be to add a keyboard shortcut to the button highlighted in red.

![boostnote-keyboard-shortcut](https://user-images.githubusercontent.com/15913688/32747371-2d1f2aa4-c87e-11e7-9f1f-cf9fa113a8dc.jpg)

For the second feature yes it's in VS Code. Attached is a screen for reference if needed.

![boostnote](https://user-images.githubusercontent.com/15913688/32747465-657d9552-c87e-11e7-8881-c32305311560.jpg)

Thanks!

**Comment by kohei-takata** [comment]
Hi @jordankaiser !
I understand. I will talk about this feature in core team.

**Comment by kazup01** [comment]
Hi @jordankaiser , this feature was released yet. Thanks for your suggestion :)

![screen shot 0030-01-15 at 7 35 27 am](https://user-images.githubusercontent.com/8602615/34942732-bbe02d50-f9c6-11e7-99b6-12fc8d9b8aa8.png)
