### ISSUE TITLE
Can not search for tags containing spaces

### ISSUE THREAD

**Issue by tbfisher** [BoostIO/Boostnote#111]
1. create a tag containing a space
2. search using "#" prefix

**Comment by Rokt33r** [comment]
Yes, It is weird a little... 

Currently, I have 2 options.
1. Forbid spaces
2. Provide an escape character like `\ `

And both of them doesn't seem to be attractive...
Is there some better way to tackle this problem?

**Comment by huettenhain** [comment]
Frankly, forbidding spaces is not the worst option. Usually, you can replace them by dots, dashes, underscores or solve the problem by camel casing.

**Comment by Rokt33r** [comment]
@huettenhain Thanks for the feedback. It seems to be clever choice. 👍

**Comment by tbfisher** [comment]
slack is a good model -- typing "#" spawns a pulldown with a list of possible choices

**Comment by Rokt33r** [comment]
@tbfisher That is also good for better UX. Thanks for your comment 👍

**Comment by Rokt33r** [comment]
Currently, the app will replace spaces with an underscore. I'll make the pulldown dialog like slack later. :)
