### ISSUE TITLE
[Feature Request] TImestamp in notes 

### ISSUE THREAD

**Issue by Anishcharith** [BoostIO/Boostnote#1110]
Is it possible to add a function that puts a timestamp in my notes
In vim editor, I can call the strftime function that does this
to achieve something like this
![boostnote](https://user-images.githubusercontent.com/17667272/32691120-293e0b9a-c729-11e7-88d8-469256c445a1.png)
I have mannually put that for now

**Comment by kazup01** [comment]
Hi @Anishcharith, thank you for your suggestion :)

**Comment by kazup01** [comment]
Hi @Anishcharith , what do you think about it? #1137

**Comment by Anishcharith** [comment]
That's pretty good !!

**Comment by Flexo013** [comment]
In the latest version of Boostnote you can add a timestamp by pressing <kbd>Ctrl</kbd>+<kbd>/</kbd> for just the date, and if you also hold <kbd>Shift</kbd> then it will add the time too.
