### ISSUE TITLE
[Feature-Request] Make links in notes able to link to other notes

### ISSUE THREAD

**Issue by pfftdammitchris** [BoostIO/Boostnote#1111]
For example in this screenshot below we should be able to go to "Note 1" by clicking on the link

![note-hotlinking](https://user-images.githubusercontent.com/20717348/32692739-71444686-c6d2-11e7-86fb-e844cca50c52.PNG)

Why we should have this:
Just like architecturing a module/library in javascript by encapsulating all separate modules into one file making it easier to reference from one file, we should have accessibility from multiple notes from within one note.

This makes it so we can have a master note or a table of contents that links to wherever else in the entire storage / notebook / whatever.

I see that clicking on the "I" icon to the right brings up this menu and provides a "Note Link" hash. Maybe we can start from there?

![i](https://user-images.githubusercontent.com/20717348/32692761-e28c8f1a-c6d2-11e7-8108-e259e263021c.png)

**Comment by 1l0** [comment]
Dupl: https://github.com/BoostIO/Boostnote/issues/1051
