### ISSUE TITLE
Remove mixpanel?

### ISSUE THREAD

**Issue by levrik** [BoostIO/Boostnote#1112]
Mixpanel is still included in the app (`MAIN_FOCUSED`) and doesn't get disabled when opt-out of analytics.
As #621 states Mixpanel have been replaced by AWS Mobile Analytics.

Is it intended that Mixpanel is still included in the application?
I can submit a PR which removes it.

**Comment by kazup01** [comment]
Hi @levrik , 
We are no longer using Mixpanel. Certainly I think that unnecessary part should be removed as you said.
Could you send us this pull request?
Thank you :)
