### ISSUE TITLE
Delete node files still exist?

### ISSUE THREAD

**Issue by aogooc** [BoostIO/Boostnote#1117]
The latest version windows.

I created a note and deleted it. Found that the file still exists ?

**Comment by PaulRosset** [comment]
Hi @aogooc :)

Once you delete the file, the file goes in the trash and then you can delete it forever.
Check your local storage of your computer to see that the file has been well deleted.

In [#1052](https://github.com/BoostIO/Boostnote/pull/1052) a counter will be added in the next release to tell you that there is file in the trash.
Tell me if Im wrong here.

**Comment by kazup01** [comment]
I will close this, but please reopen if there is a problem. Thank you.
