### ISSUE TITLE
Batch export to Markdown

### ISSUE THREAD

**Issue by lechip** [BoostIO/Boostnote#1122]
Would be awesome to be able to batch export notes in `.md` format (or other formats.

I know is possible with individual notes, but when you are like me with more than 200+ notes, is not so practial.

Cheers and thank you!

**Comment by kohei-takata** [comment]
Hi @lechip !
Thanks for your opinion!
I don't know how to implement the feature, so I will study.
Also, PRs are welcome!

**Comment by jasondavis** [comment]
I have requested this for a long time.  My idea was to batch export a folder of notes and create a ZIP file with the folder and all notes as MD files in the zipped folder/file

**Comment by jasondavis** [comment]
@kohei-takata "I don't know how to implement the feature, so I will study."...

Simply get a list of notes that exist in the selected Notebook/folder and then loop over each one and run the code from the current MD export on each file, then create a ZIP file with all the newly created MD files and save it to disk.

In my past feature requests here I have links to useful ZIP libraries that make the process really easy

**Comment by kazup01** [comment]
This feature was released at v0.8.20.
[Release Note](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd)
Thank you for you guys waiting!

**Comment by weaming** [comment]
write a script to convert cson files to markdown format

https://gist.github.com/weaming/32b7b62956b304ff66fbae396ca9c86b
