### ISSUE TITLE
Garbled texts in the UI of 'Select Directory' on Ubuntu 17.10

### ISSUE THREAD

**Issue by CicoZhang** [BoostIO/Boostnote#1124]
![image](https://user-images.githubusercontent.com/11710225/32786400-2136ffe2-c954-11e7-8cfe-e1bec1caf645.png)

I am using Ubuntu 17.10.

![image](https://user-images.githubusercontent.com/11710225/32786634-c6160206-c954-11e7-81aa-b5e489388481.png)

![image](https://user-images.githubusercontent.com/11710225/32786651-d34ee9c4-c954-11e7-9f77-197c6200a61c.png)

**Comment by yosmoc** [comment]
Hi @CicoZhang,

I have fixed this problem in #1105. This change will be included in the next release.

**Comment by kazup01** [comment]
v0.8.17 is out! Thank you @CicoZhang and @yosmoc :)
