### ISSUE TITLE
Tags button misaligns when zoom level is set less than 100%

### ISSUE THREAD

**Issue by shantanualsi** [BoostIO/Boostnote#1128]
1. Reduce the zoom level to 90% or 80% from the dropdown
2. Check the Tags button on the left SideNav

![zoom_error_boostnote_0 8 16](https://user-images.githubusercontent.com/660283/32822564-25563e10-ca14-11e7-8401-578f9b5e6abc.png)
![boostnote issue](https://user-images.githubusercontent.com/660283/32822579-34f888d2-ca14-11e7-849d-2bf47eeca9d3.png)

This issue is reproducible on Boostnote 0.8.16 on Ubuntu 16.04

**Comment by kazup01** [comment]
Hi @shantanualsi , thank you for your report.
This problem has fixed. #1096 Wait for next update :)

**Comment by kazup01** [comment]
v0.8.17 is out! I wrote the release note. https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2

**Comment by kazup01** [comment]
Thank you again @shantanualsi :)

**Comment by shantanualsi** [comment]
That's awesome @kazup01.. I already upgraded, looks amazing!
