### ISSUE TITLE
How to describe triple backquotes in code blocks

### ISSUE THREAD

**Issue by falsandtru** [BoostIO/Boostnote#1130]
About your wiki, you can describe triple backquotes without escaping as follows.

`````
````
```flowchart
```
````
`````

https://github.com/BoostIO/Boostnote/wiki/Diagram-support

**Comment by kazup01** [comment]
Cannot use triple backquotes in code blocks. This issue about markdown. Please check it. https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
