### ISSUE TITLE
Font ''Microsoft YaHei'' has extra quotes

### ISSUE THREAD

**Issue by amitauras** [BoostIO/Boostnote#1131]
For preview in **windows** Bootsnote when we assign any font it is not getting applied because some extra fonts are getting added one of which is _'Microsoft YaHei'_ and it has extra quotes like **''**Microsoft YaHei**''** due to which browser is not recognizing it as a valid _font-family_ value. 

![extra-fonts-issue](https://user-images.githubusercontent.com/7886615/32874055-cbbd6444-cab5-11e7-8b9d-fe359461fa51.png)

**Comment by yosmoc** [comment]
Hi @amitauras,

It seems it has already been fixed in this [commit](https://github.com/BoostIO/Boostnote/commit/bfa8db7b55d6b7549203be5010c7462adfc911d1) Please wait for the next release.

**Comment by kazup01** [comment]
v0.8.17 is out! I wrote the release note. https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2
Thank you @amitauras and @yosmoc :)
