### ISSUE TITLE
Custom Editor Themes

### ISSUE THREAD

**Issue by ITProKyle** [BoostIO/Boostnote#1134]
It would be great to have the ability to import and use our own CodeMirror themes.

**Comment by kazup01** [comment]
Hi @ITProKyle , how about these themes? 
[Editor themes](https://github.com/BoostIO/Boostnote/wiki/Editor-theme)
[Codeblock themes](https://github.com/BoostIO/Boostnote/wiki/Codeblock-theme)

**Comment by asmsuechan** [comment]
There's no official support, but you can do it by yourself.
https://github.com/BoostIO/Boostnote/issues/200#issuecomment-271854423

**Comment by ITProKyle** [comment]
The linked comment by @asmsuechan did the trick. Thank you.

Please consider adding this to the Wiki.

It could be beneficial to add the functionality into setting > UI with a button to drop a CSS file in the correct directory then, restart the application to have the new theme appear in the drop down. It would improve the UX of the process and remove requests for more themes to be added.

**Comment by kazup01** [comment]
memo: #591

**Comment by Flexo013** [comment]
I will close this issue for now as you can add your own custom css from the preferences.

@ITProKyle If you feel like something more has to happen with this issue, then feel free to reopen/recreate an issue.
