### ISSUE TITLE
Boostnote does not remember the star

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#114]
Not a major issue, but for the record: Version 0.6.4 does not remember the star on any note between complete restarts. To reproduce (I hope) just star any note and reload with Ctrl+R. The star is gone.

**Comment by Rokt33r** [comment]
You should wait more than 2.5 seconds before refreshing the app. Boostnote doesn't write down every changes to file system. 

As you see, it waits the end of editing.
Firstly, the detail component dispatches the change after a second from the last editing.
https://github.com/BoostIO/Boostnote/blob/v0.6.2/browser/main/Detail/SnippetNoteDetail.js#L101-L113
Then, dataApi queues saving the changes to File system and waits 1.5 seconds.
https://github.com/BoostIO/Boostnote/blob/v0.6.2/browser/main/lib/dataApi.js#L22-L32

Could you check it once again? If the waiting doesn't work, It must be a bug.

**Comment by huettenhain** [comment]
Hey, I tried two things:

* add a star, wait at least 10 seconds (just to be sure) and reload
* add a star, then edit the note, wait at least 10 seconds and reload

In neither case, the star was still there after reload. The edits to the note were remembered, though, so I do not think it's a timing issue.

**Comment by Rokt33r** [comment]
@huettenhain Okay, I'll check it again. Anyway, it works well on v0.6.5.

**Comment by Rokt33r** [comment]
It seems to be fixed now!
