### ISSUE TITLE
change background color

### ISSUE THREAD

**Issue by rifqempul** [BoostIO/Boostnote#1145]
please add change background option. i can't really focus my eyes on gray background. thanks.
![bg](https://user-images.githubusercontent.com/11476083/32992550-8d6c5e54-cd7e-11e7-9e6c-0514ef3d1a92.PNG)

**Comment by kazup01** [comment]
Hi @rifqempul , I think that we should make custom themes feature.
Please check it. #591

And new theme will available at next update. Wait a moment :)
![screen shot 0029-11-20 at 1 24 51 am](https://user-images.githubusercontent.com/8602615/32992740-ab49168e-cd91-11e7-8607-5f3b2f2b5314.png)

**Comment by rifqempul** [comment]
wow thanks! looking forward to it.
