### ISSUE TITLE
snippet copy from Finder window removes newlines 

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#1146]
On Windows 10, when using the Finder window to copy a snippet note content to the clipboard, the pasted text has all line breaks removed.

**Comment by kazup01** [comment]
Since we discard the Finder feature at v0.9.0 because this feature used very rarely, so I close this issue.
[v0.9.0 Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)

If you need, please feel free to talk to us. 
Thank you!
