### ISSUE TITLE
Default directory not created when first time and cannot edit location textfield

### ISSUE THREAD

**Issue by jamoore5** [BoostIO/Boostnote#1148]
Sorry I do not have any screenshots, but the first couple of times I opened Boostnote on my MacBook it gave me a screen asking where I would like to store my files. When I tried to type into the text field the location it would just open. However, when I tried to create a note it would error saying something about no storage. Next time I opened Boostnote I would get the same screen asking for the storage location. 

I worked around this issue by creating a directory and using the browse/search tool to set the location.

**Comment by dakira** [comment]
Same issue. The textfield is not editable. And when I click the three dots to the right of it, it shows me a screen like this:
![bildschirmfoto von 2017-11-22 13-27-11](https://user-images.githubusercontent.com/576555/33127551-2adfa02c-cf89-11e7-84b7-4a54c5d8ed6b.png)

**Comment by jamoore5** [comment]
In my case on mac, the browse/search tool (three dots) worked. I just had to create the folder first and not try to edit the location with the text field.

**Comment by dakira** [comment]
Another workaround for me seems to be to just accept the default and create a seperate storage from settings.

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.

**Comment by dakira** [comment]
@Flexo013 What activity do you expect? Two people reported a bug and never heard back from the developer. I even posted a screenshot. :)

**Comment by Flexo013** [comment]
Apologies for that. OSS sometimes has this problem were it is unclear who is responsible for what.

As for the issue you reported, I don't it occurs anymore as one default storage location is created upon installation and I couldn't find any issues with creating new storages elsewhere.

Is the issue still present for you? @dakira?

**Comment by dakira** [comment]
@Flexo013 Looks like it's fixed! I just tried with a blank install. :-)

**Comment by Flexo013** [comment]
Thanks for the update!
