### ISSUE TITLE
TouchBar support

### ISSUE THREAD

**Issue by romainwn** [BoostIO/Boostnote#1155]
As mentioned on the Slack general channel, it would be great to add support for 2016-17 MacBook Touch Bar.

This issue could be used to add suggestions on what could be interesting to add on this Touch Bar

**Comment by robbawebba** [comment]
I would love to see some basic markdown editor controls while in edit mode:
* create an ordered/unordered list
* start a todo list
* bold, underline, italics
* insert a markdown link
* insert a code block

All of these couldn't fit in the touch bar, so some of them might have to be left out or condensed.

**Comment by mikaoelitiana** [comment]
This is a great feature to have. A quick link to note category would be great also.
