### ISSUE TITLE
App crash when press toggle main hotkey on OS X

### ISSUE THREAD

**Issue by mas9612** [BoostIO/Boostnote#1158]
Hello,

I'm using Boostnote on Mac OS X 10.11.6.
When I press Toggle main hotkey (Cmd + Option + L) to change focus to Boostnote from other app, Boostnote will sometimes crash.
And I try to reopen Boostnote after crash, but it'll not be able to open.

I don't know this problem is from Boostnote or my environment, but I hope this issue will help you.

I'll attach crash report.
[Boostnote_2017-11-23-160946_Macbook-Pro-3.crash.txt](https://github.com/BoostIO/Boostnote/files/1498289/Boostnote_2017-11-23-160946_Macbook-Pro-3.crash.txt)
If you need any information, please notify me.

Thank you,

**Comment by kazup01** [comment]
Hi @mas9612 , thank you for your information! 
I never heard it. Is there someone occurred this problem?

**Comment by mas9612** [comment]
Hello @kazup01,

I think this issue seems to be only occurred on my Mac.
Other user (around me) haven't heard this issue too like you.

Thanks,

**Comment by kazup01** [comment]
Hi @mas9612 , 
Thank you for your reply and cooperation :)
I close this issue, but if you need to more information, please feel free to reopen it.
Thank you again!
