### ISSUE TITLE
Feature request: live Markdown preview pane

### ISSUE THREAD

**Issue by incredibleweirdo** [BoostIO/Boostnote#116]
Hello,
   First of all, I love this application. It's helping me store and organize many snippets of code (C#/linq, SQL, JS, etc), brainstorm notes, and useful links for references.
   One thing that I would like to see is the option to view a live preview pane for Markdown notes. Perhaps to the right of the editor, showing live what the Markdown will render as. I do like the preview when not in edit mode, but I find myself clicking outside of the editor window repeatedly to see what my editing has wrought.

thank you!

**Comment by huettenhain** [comment]
Just my 2 cents: I have nothing against it, but if implemented, it should be optional. I like that Boostnote is so lean, and live previews always slow things down.

Also, just a comment: There is an option in Boostnote to use right-click instead of focus to switch between editor and markdown view. It might be more up your alley.

**Comment by Rokt33r** [comment]
Actually, I have a plan to implement it. And, I agree with @huettenhain 's opinion, it should be optional.
Currently, I'm going to implement 3 buttons to the bottom of main window, just like Power Point.

1. Single view(current)
2. 2-pane view(@incredibleweirdo said)
3. Fullscreen preview

**Comment by incredibleweirdo** [comment]
@Rokt33r no apologies needed! I think your response was plenty quick :) Honestly I expected that you'd have your hands full with other earlier requests, etc. and this would be put onto a list for the future. 

And yes, @huettenhain - as noted in the request, having it be optional would be best. Some may not want it, and even those that do may not want it on all the time. 

thank you!

**Comment by baer** [comment]
A new Markdown note app came out recently that has a pretty cool take on "live preview." Rather than have multiple screens or have a read/write mode it just converts the text you're actively working on to MD.

https://www.typora.io/

**Comment by Rokt33r** [comment]
@baer It would be great. But, It will takes lots of time because each block should be rendered as a react component.

**Comment by baer** [comment]
I haven't looked into the code yet and obviously it depends a lot on how things are done but there are quite a few examples of live edit/render interactions with React. One I'm pretty familiar with is [Formidable's component playground](https://github.com/FormidableLabs/component-playground) but I know there are others as well. Is there something in particular that makes this particularly difficult?

**Comment by Rokt33r** [comment]
@baer Thanks for suggesting. I'll try it and inform you later. 👍

**Comment by kirtan403** [comment]
@Rokt33r Any updates on this?

**Comment by kirtan403** [comment]
@kazup01 Is this feature implemented?

**Comment by incredibleweirdo** [comment]
@kazup01 Is this closed for being rejected, or another reason?

**Comment by incredibleweirdo** [comment]
Hello @kazup01  - why was this feature request closed?

**Comment by kidapu** [comment]
why? closed?
