### ISSUE TITLE
New notes in Dropbox from mobile app

### ISSUE THREAD

**Issue by Tsproggy** [BoostIO/Boostnote#1162]
I'm enjoying the Dropbox sync support. While I can edit existing notes and sync changes, it appears I'm unable to create new notes from my mobile device and sync it to my Dropbox account. I would greatly appreciate if anyone could add this feature.

_Edit: Also perhaps the ability to move a note from the All Notes tab into Dropbox and sync #271 ._

_Android 7.0
Honor 6x_

**Comment by kazup01** [comment]
Hi @Tsproggy , thank you for enjoying Boostnote :)
This feature is in progress.
https://github.com/BoostIO/boostnote-mobile/pull/84
We will update it in sometime soon.
