### ISSUE TITLE
Lock Editor not working

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [BoostIO/Boostnote#1163]
Hello,

I have just downloaded boostnote and start using it, but the lock button does not seem to work at all. If I lock a note by clicking to the lock button (icon now looks as a closed lock) I'm still able to edit the note just as if the lock was open. There is no function at all for the lock. Why is that?

**Comment by kazup01** [comment]
Hi @AlexisEspinosaGayosso, could you tell your environment?

I think that this is not bug, but current UI is hard to understand.
We will update layout like below gif within a few days.
![nov-23-0029 19-44-39](https://user-images.githubusercontent.com/8602615/33193401-aa33ca00-d10b-11e7-9181-42875623956b.gif)

**Comment by AlexisEspinosaGayosso** [comment]
Maybe I'm not understanding, but I still think this is a bug.
I installed it from latest version available 2 hour ago to linux and to windows and this is happening in both operating systems.
My understanding is: if I lock the symbol, then I should not be able to edit if I click on the note. And, if trying to edit, then I will get a warning message. Then, in order to edit I would need to unlock the symbol and editing is available and note will be saved automatically after anychange. (Hahahaha, my understanding is that its like completely the opposite of the saving button. Now we need to protect ourselves against autosaving.) Anyways, with the button locked I'm still able to edit after clicking on the note, so the locked or unlocked button is meaningless (or the lock option is not working and then we have a bug.)

**Comment by JasonWeise** [comment]
I having this exact issue also, I have created some notes and don't want to go into edit mode when clicking on the note itself but even with lock in the "on" state edit mode still enables.

Downloaded latest version from BoostIO homepage today (MacOS)

**Comment by Flexo013** [comment]
Currently you can only lock the editor (so that it doesn't switch to the preview). If you would also like a lock button than makes it so the preview window doesn't turn into the editor, then check out this issue: #2955
