### ISSUE TITLE
bug: Mac: On Install, input not accepted oninitial storage prompt

### ISSUE THREAD

**Issue by Karrade7** [BoostIO/Boostnote#1171]
When loading Boostnote for first time, it prompts for storage location.
If you try to edit the path directly by typing text it closes the windows and moves into the main program with an error of no storage mount. Using the UI to select folder works fine.

Step 1: Open Boostnote with no storage mount
![image](https://user-images.githubusercontent.com/1933873/33218377-da27dc5e-d0f9-11e7-8317-263149a19056.png)

Step 2:
type in a letter into the "select a directory" text box. I have tried C and D.
Boostnotes assumes input is complete and moves to main screen with no mount

![image](https://user-images.githubusercontent.com/1933873/33218419-1183cc26-d0fa-11e7-8fae-a2d6d4405ca1.png)

**Comment by kazup01** [comment]
Hi @Karrade7, thank you for your report. Could you paste screenshots in console?

Btw, I never heard it. Is there someone occurred this problem?

**Comment by Karrade7** [comment]
Console screenshot attached.
I was able to replicate this by unlinking storage, closing the app, re-opening and then pressing any keyboard when my curoser was in the box for storage directory include left arrow.
I'm running MAC 10.13.1, on a MacBook. 

![image](https://user-images.githubusercontent.com/1933873/33224107-344416ca-d123-11e7-8ab5-e5a3ec378b03.png)

**Comment by kazup01** [comment]
Hi @Karrade7 , I could reproduce it. This bug is occur when press enter on initialize modal.
Could you click on 'Let's Go!' button on it? We should fix this bug. Thank you for your report!

**Comment by Karrade7** [comment]
No problem. From your response it was clear to me if you reproduced it only by pressing enter or if pressing any key besides enter. I was able to cause the bug by pressing any button. 

I've already used Let's Go to start using BoostNote. Love it so far!
Do you need a screen shot of pressing Let's Go?

**Comment by kazup01** [comment]
Hi @Karrade7 , screenshot is not necessary. Thank you :) Enjoy Boostnote!
