### ISSUE TITLE
Margins too wide for regular notes after 0.8.17 update

### ISSUE THREAD

**Issue by Trewlany01** [BoostIO/Boostnote#1173]
Hello All,

Just updated to the newest 0.8.17 update and I am thrown off with the margins assigned in the new update.
**_Is there a way to change these margins manually, and if not, revert back to previous boostnote version before 0.8.17?_**
See screenshot below. I think these margins are taking too much space when using both regular view and full screen view of boostnote.
![margins](https://user-images.githubusercontent.com/32272737/33228092-3201c586-d170-11e7-9f4a-66228ed76583.JPG)
![margins second](https://user-images.githubusercontent.com/32272737/33228094-39aa049c-d170-11e7-8bbc-b8d07fbdc587.JPG)

**Comment by Trewlany01** [comment]
Perhaps I just need time to adjust to new format. 
Margin options would be nice, however I understand there are many things to address presently
Thanks for all the work you do!

**Comment by IlyakorMostovoy** [comment]
Hello! 
In version 0.8.17 editing area really has become very narrow, this lost a lot of useful space. You may want to make the opportunity to regulate this area by the width. Or, it's possible to make the width the same as the "Snippet note".

Thanks to the team Boostnote for your work.

**Comment by kazup01** [comment]
I understand, we will improve this layout by next update. Thank you for your feedback :)

**Comment by kazup01** [comment]
cc @ytk141

**Comment by charlesmu2014** [comment]
now,you can mod the main.js to change it
open *\boost\app-0.8.17\resources\app\compiled\main.js
search ".MarkdownNoteDetail__body___browser-main-Detail-" or "max-width:600px;"
delete  "max-width:600px;"
then ,reload it

**Comment by kazup01** [comment]
Fixed. #1179
Wait for the next update!
![nov-26-0029 16-17-49](https://user-images.githubusercontent.com/8602615/33237953-ae229f4a-d2c5-11e7-8f2b-b90ce97648d7.gif)

**Comment by kazup01** [comment]
Hi guys, we will update to v0.8.18 at tomorrow. Thank you for waiting!

**Comment by kazup01** [comment]
v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778

**Comment by Trewlany01** [comment]
Thank you so much! Looks great!
You guys are great at this.
