### ISSUE TITLE
Visible scrollbars on preferences window

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#1174]
Open when the preferences window, can see all the scrollbars behind of Storage, NotesList etc.

[Screenshot](https://i.imgur.com/MuE72i1.png)

**Comment by Trewlany01** [comment]
I have seen this same issue also and am providing screenshots also for this.

Seems that the second non active scroll bar is popping up but is unable to be used.
See screenshot for non active scroll bar. Its getting confusing with these difference in scroll bars.

![scroll bar](https://user-images.githubusercontent.com/32272737/33231587-cd2e14a8-d1b4-11e7-9ca0-47851364a678.JPG)

![scroll bar in preferences](https://user-images.githubusercontent.com/32272737/33231589-d678f0a0-d1b4-11e7-945a-25b16450aa03.JPG)

**Comment by kazup01** [comment]
Thank you for your report! Could you tell me you guys environment?

**Comment by arcticicestudio** [comment]
I can confirm that this problem occurs for Arch Linux using GNOME, i3 and Sway based environments.

> Boostnote v0.8.17
NodeJS v8.8.1

![gh-1174-scrot-neofetch](https://user-images.githubusercontent.com/7836623/33325620-0d9b26ca-d453-11e7-89e6-d74482e41065.png)

**Comment by Trewlany01** [comment]
My environment is Windows 10  Boostnote v0.8.17

**Comment by brpaz** [comment]
Mine is Linux Mint 18.3 Cinnamon with Boostnote v0.8.17

**Comment by MakisH** [comment]
I have the same problem in Ubuntu Linux 16.04 with Boostnote v0.8.18.

**Comment by roby777** [comment]
I have same porblems too.
Windows 7 Professional SP1
Boostnote v0.8.18

**Comment by MakisH** [comment]
In v0.8.19:

- The scrollbars are ok when the editor and the live rendering are side-to-side,
- The problem persists (two scrollbars instead of one) when I am in the older "click to exit editor" mode.

After experimenting, I see that what the two scrollbars are the scrollbars of the two containers.

**Comment by Flexo013** [comment]
In the latest version the scrollbars are all fixed.
