### ISSUE TITLE
About updating v0.6.7

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#118]
OS X app would not quit after `Restart & Install` button clicked.

Please quit the app manually after clicking `Restart & Install` button. Then, the new version will be restarted automatically.

The next update, from v0.6.7 to v0.6.8(or v0.7.0), won't bother you anymore.(I confirmed it is fixed)

**Comment by jc21** [comment]
Tried that, still didn't update, stuck on 0.6.5. I had to go to the website last time to get the new version as well. I would really like to turn off auto updating considering it's broken. At the very least, only checking for an update once a day or similar.

**Comment by Rokt33r** [comment]
@jc21 I'm really sorry. I'll release a fixed version today.
> I confirmed it works well. https://github.com/BoostIO/test-releases

But, current version v0.6.6 also has a same problem. please download again after v0.6.7 released.
>In my case, My app has been updated to v0.6.6 since I restarted twice.

**Comment by jc21** [comment]
Don't be sorry chief, it's free software! I know how shitty it is to develop without reward.

**Comment by Rokt33r** [comment]
@jc21 Thank you for your understanding. Btw, It seems to be fixed completely now. 👍
