### ISSUE TITLE
List insertion is broken on ArchLinux

### ISSUE THREAD

**Issue by ryochack** [BoostIO/Boostnote#1181]
Boostnote v0.8.17 on ArchLinux.

Markdown's list insertion seems to be broken on ArchLinux.
This problem doesn't reproduce on macOS Sierra v10.12.6 + Boostnote v0.8.17.

## Steps to reproduce
1. Write the list items.
```
- item
- item
```
2. Press enter key at `*` positon.
```
- item*
- item
```
3. Always reproduce. Last `- ` is replaced with `NaNundefined`.
```
- item
- 
NaNundefineditem
```

![boostnote_issue](https://user-images.githubusercontent.com/356703/33240922-f0d0daf0-d301-11e7-9406-a327e45640e7.png)

**Comment by clone1612** [comment]
I've pushed an update to the Arch package that should fix the issue.

**Comment by ryochack** [comment]
Thank you for your great job!
I confirmed that the issue has been fixed on the boostnote 0.8.18-2 Arch package!
