### ISSUE TITLE
Content width on Windows

### ISSUE THREAD

**Issue by kparkov** [BoostIO/Boostnote#1185]
In version 0.8.17 on Windows, when adding a Markdown note, the content frame is very narrow inside the larger window. 

![udklip](https://user-images.githubusercontent.com/805549/33244485-432ffb78-d2f8-11e7-96fb-10310e599f53.PNG)

It would be very nice with an option to let the content fill the entire width, and let the window size define the content width.

**Comment by bobmk2** [comment]
v0.8.17 on macOS too 😢 
![boostnote_v8 17 0](https://user-images.githubusercontent.com/1858949/33245924-b56111f6-d351-11e7-8684-d1becd30a62a.gif)

**Comment by boak** [comment]
Same issue for me as well

Windows 10
BoostNote v0.8.17

I do like the idea of the content not necessarily stretching to fill the whole window (especially on widescreen devices) but the current size is a bit small. Would it be possible to have a configuration item to set max-width?

**Comment by kazup01** [comment]
Hi all, this issue is duplicated. #1173 
It has already been fixed, wait for the next release.
https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by kazup01** [comment]
v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
