### ISSUE TITLE
Content width problem on Windows

### ISSUE THREAD

**Issue by farzadmf** [BoostIO/Boostnote#1186]
https://github.com/BoostIO/Boostnote/blob/6bab108a35135b25751dd542fcf85cc2605e1d97/browser/main/Detail/MarkdownNoteDetail.styl#L33:7

I'm not sure about other platforms, but at least on Windows, the setting of `max-width` causes the content to not occupy the whole width

**Comment by kazup01** [comment]
Hi @farzadmf , I'm already fixed.Wait for the next release.
https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by farzadmf** [comment]
Great, thanks for the quick reply 💯

**Comment by kazup01** [comment]
Enjoy 💯

**Comment by kazup01** [comment]
Hi @farzadmf , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778

**Comment by farzadmf** [comment]
Hi @kazup01 , Thank you so much for taking the time to let me know
I downloaded the new version, and it looks very good :)

**Comment by kazup01** [comment]
@farzadmf  I'm so glad to hear that ;) Enjoy Boostnote!
