### ISSUE TITLE
markdown editor's width is narrow

### ISSUE THREAD

**Issue by euii** [BoostIO/Boostnote#1189]
![snip20171127_1](https://user-images.githubusercontent.com/701552/33254831-99a55ce0-d385-11e7-9122-c61247912ab3.jpg)
![snip20171127_2](https://user-images.githubusercontent.com/701552/33254833-99d81ed2-d385-11e7-9223-0f9042a1387c.jpg)
![snip20171127_4](https://user-images.githubusercontent.com/701552/33254834-9a078b5e-d385-11e7-87d0-67759a8eb6a8.jpg)

how to resize editor width ?

**Comment by kazup01** [comment]
Check https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by kazup01** [comment]
Hi @euii , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
