### ISSUE TITLE
About data analytics

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#119]
# From v0.6.5, we start gathering usage data of Boostnote by mixpanel.
## Why?

To maintain this service, we need some numbers, weekly active users, monthly active users and total users.(These numbers are important for us to fundraise.)

Also, we are going to analysis which features are using often. It will guide us which feature should be focused.
## Currently, we are gathering these data.
- App focusing count
- Storage/Note count
- App version
## Future plan
- We will provide an option to turn off data reporting.
- We WON'T gather any PRIVATE data.(ex: content of notes)
- Replace mixpanel with AWS mobile analytics

---

If you have any question about this issue, please feel free to comment here.

**Comment by osiyuk** [comment]
Private data in future plan — do you gather content of notes right now?

**Comment by Rokt33r** [comment]
@osiyuk No, we don't gather it now neither.

**Comment by alexanderadam** [comment]
Will you announce the opt-out option here in this ticket as well?

**Comment by mikeres0** [comment]
This project is currently in limbo, we will get back to you
