### ISSUE TITLE
New Close Behavior

### ISSUE THREAD

**Issue by Nino9614** [BoostIO/Boostnote#1192]
With the new update installed, closing the application using the windows window close button results in completely closing the application. The Tray menu also is closes, 
Is this something you wanted or is it a bug?

My OS:
Windows 10 64-Bit

**Comment by kazup01** [comment]
Hi @Nino9614 , this is the new feature from v0.8.17 #1043
Thank you

**Comment by towfiqi** [comment]
Is there anyway to revive the old behavior?

**Comment by Rokt33r** [comment]
@towfiqi 
We're going to do. Check https://github.com/BoostIO/Boostnote/pull/1536

**Comment by towfiqi** [comment]
Great :smile:
