### ISSUE TITLE
Performance issues with many notes

### ISSUE THREAD

**Issue by kun-zhou** [BoostIO/Boostnote#1195]
When the number of notes get large, clicking the folder becomes extremely slow. Maybe it is caused by a combination of executing too many `render()` and locating the notes belong to the folder? I suppose you can use some cache and something like `react-virtualized` to help in this regard.

**Comment by Flexo013** [comment]
@kun-zhou Are you still experiencing this issue?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
