### ISSUE TITLE
Width of the text editor and markdown viewer and sidebars

### ISSUE THREAD

**Issue by oicitrapdraz** [BoostIO/Boostnote#1196]
Hi, I don't know why, but recently the width of the text editor and the markdown viewer is quite narrow, and before it covered almost the entire box of the window, also there's another sidebar that shouldn't be seen (sometimes you can see it in the preferences or in other windows)

![sidebars_and_width](https://i.imgur.com/xAC5hmK.png)

* I also take the opportunity to say that if folders could be created within folders it would be great, since it's complicated to organize everything with only one level of folders when I take notes for each course I'm taking at the university and different programming languages, frameworks, etc. that I'm studying.

Regards!

**Comment by kazup01** [comment]
Hi @oicitrapdraz , thank you for your feedback!
Since we can't manage if we receive multiple opinions to one Issue, could you post them one by one?

Width of contentl is fixed at #1173 :) https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681
Thanks again!

**Comment by kazup01** [comment]
Hi @oicitrapdraz , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
