### ISSUE TITLE
wide border around text input field

### ISSUE THREAD

**Issue by renebefort** [BoostIO/Boostnote#1198]
Hi,
I love the new look and feel. But on my windows system I have a wide border around the text input field. Is there any config to decrease the border?

![2017-11-28 09_29_36-boostnote](https://user-images.githubusercontent.com/23495665/33309624-0014bc0c-d41f-11e7-811b-5ebf4a5d4a3c.png)

Thank you for the great work!!!
Rene

**Comment by kazup01** [comment]
Hi @renebefort , I already fixed it. Wait for next update. https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by renebefort** [comment]
Hi @kazup01, Thanks!!!!

**Comment by kazup01** [comment]
Hi @renebefort , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
