### ISSUE TITLE
ショートカットキーを変更したのに残ってしまう。

### ISSUE THREAD

**Issue by yukitoto** [BoostIO/Boostnote#12]
`Setting`からToggle `Finder(popup)`の変更を行いました。
はじめは、`cmd + T`で行い、それがPC全体に適用されるものだと知り、他のものに変更し、Saveしましたが、未だ`cmd + T`でboostnoteの検索が開かれてしまいます。
気に入っていたので、解決策 or 修正を行ってもらえると嬉しいです。

**Comment by Rokt33r** [comment]
たぶん、新しく設定した値に認識不可能な値が入っていると思います。
もし全角スペースが使われたり、キーの名前が間違ったようなんで、新しく設定したキーを教えてもらえますか？

**Comment by yukitoto** [comment]
なるほど！
`cmd + T + B`で設定して、そのコマンドでもうまく動くと勘違いしていた（正確には`cmd + T`だけで動いていた）ので、前の設定が残っていたのかと思いました！
素早い対応ありがとうございます！
不正なコマンドの場合はアラートが出るようになるといいですね！

**Comment by Rokt33r** [comment]
役に立ったらよかったんです！
次のアップデートでエラーがちゃんと出るようにします！
