### ISSUE TITLE
Error/bug: Error message when creating new notes 

### ISSUE THREAD

**Issue by loifarn** [BoostIO/Boostnote#1200]
System: Ubuntu17.10
Boostnote version: 0.8.17

_Please let me know if there is any other information I can provide to help_

Error occurs when program is newly opened and the user tries to create a new note. This seemingly happens due to no "group" being selected by default to place the new note in.

The dialog is also not displayed propperly in the same way as issue #1199
![error-new-note](https://user-images.githubusercontent.com/17389791/33313857-2c167504-d42c-11e7-9196-f15d9e5ae830.png)

**Comment by yosmoc** [comment]
@loifarn,
Thanks for reporting.
Would you please give me the info `process.versions.electron`? You can get this in Developer tools -> Console -> process.versions.electron.

**Comment by loifarn** [comment]
@yosmoc Sorry if I'm missing something obvious here, but where can I find the Developer tools ?

**Comment by yosmoc** [comment]
@loifarn No worries. If you press Alt-key, the menu bar will be showed up. You can find the `Toggle developer tools` in View menu.

**Comment by loifarn** [comment]
Due to a unrelated problem I ended up moving my workstation back to windows for the time being. Thus I can no longer replicate the error. This issue can therefore be closed. Apologies for the inconvinience.
