### ISSUE TITLE
LaTeX with inline: $ and block: $$

### ISSUE THREAD

**Issue by Paalon** [BoostIO/Boostnote#1201]
Many markdown editors support LaTeX with inline: `$` and block: `$$` but Boostnote seems to support inline: `$$` and block: `$$$` only. I think we need to support inline: `$` and block: `$$` support for LaTeX.

**Comment by Paalon** [comment]
I don't know which is preferred {inline: `$$`, block: `$$$`} or {inline: `$`, block: `$$`}, but anyway it seems both syntax is widely used. So we should add preferences to set LaTeX delimiters.

**Comment by Paalon** [comment]
[@rokt33r/markdown-it-math](https://www.npmjs.com/package/@rokt33r/markdown-it-math)'s default setting is
```js
var options = {
    inlineOpen: '$$',
    inlineClose: '$$',
    blockOpen: '$$$',
    blockClose: '$$$',
    renderingOptions: {},
    inlineRenderer: require('ascii2mathml')(this.rendererOptions),
    blockRenderer: require('ascii2mathml')(Object.assign({ display: 'block' },
                                                         this.renderingOptions))
}
```
so we can change them by only switching `'$$' <-> '$'` and `'$$$' <-> '$$'`,

**Comment by Paalon** [comment]
#1221 will solve this.

**Comment by kazup01** [comment]
Thanks @Paalon ;)

**Comment by RoyiAvital** [comment]
Does the current version supports Math using MathJax?
