### ISSUE TITLE
On Linux, when Boost is closed, its process still remais opened 

### ISSUE THREAD

**Issue by danielbruno301** [BoostIO/Boostnote#1205]
On Linux Ubuntu Server 17.04, when Boost is closed, its process still remais opened. Always I must to type kill -9 boostnote_PID to close it effectively. If I try to open Boost without this trick, the boost app open with freeze window, nothing else can be used in the app.

**Comment by ricardoper** [comment]
Same issue for me on a Linux Mint 18.2 since version 0.8.x.

**Comment by DocWinter** [comment]
I have the same problem using the last version of Antergos.

**Comment by MakisH** [comment]
I don't have this problem in Ubuntu 16.04. Does it always happen for you? Even if you just open and close Boostnote, or only if you do a specific task first?

**Comment by danielbruno301** [comment]
It always happens to me. Every time I open Boostnote for the second time. Boostnote 0.8.16. I will update may version and see if this behavior disappears.

**Comment by ricardoper** [comment]
This bug it's very annoying. It's the same error reported on issue #1299 but this issue still's in "Open" state.

**Comment by francescocadei** [comment]
me to

**Comment by SrdjanMilic** [comment]
Also on Ubuntu 16.04, with latest version 0.8.20.

**Comment by ZeroX-DG** [comment]
I believe it's has been fixed in the latest version 0.11.13
