### ISSUE TITLE
Add a LATEX Math Support?

### ISSUE THREAD

**Issue by adamisntdead** [BoostIO/Boostnote#121]

**Comment by Rokt33r** [comment]
Boostnote has supported LATEX block(inline: `$$`, block: `$$$`).

Try
```
$$\alpha$$ and $$\beta$$

$$$
\frac{\alpha}{\beta}
$$$
```

**Comment by huettenhain** [comment]
Oh wow, this was on my wishlist and I thought it might be a little out there. Man, you need to start *documenting* all your awesome features.

**Comment by dpo** [comment]
Awesome!

**Comment by dotcs** [comment]
Awesome. Thank you so much for supporting LATEX formula. You've done a great job!

**Comment by notd5a** [comment]
i cant seem to use it :(

**Comment by Flexo013** [comment]
@notd5a Please create a new issue with screenshots showing what's not working, and then we'll figure out what's going wrong.
