### ISSUE TITLE
Editor width is fixed at a small size

### ISSUE THREAD

**Issue by robbawebba** [BoostIO/Boostnote#1210]
This might be a subjective bug, but I noticed that the editor size has a fixed width, regardless of the size of the sidebars. I think that it would be best to fill expand the editor area as much as possible to improve the editor experience. 

<img width="1680" alt="screen shot 2017-11-30 at 10 32 13 am" src="https://user-images.githubusercontent.com/10067384/33448355-a805c1b2-d5ba-11e7-85a6-8384359f18bb.png">

If there's a reason why the editor is fixed at this width, I'd be very open to hearing about it! 😄 

Thank you for your help!

**Comment by jwrobb** [comment]
I can confirm I have the same issue after upgrading to Version 0.8.17. Running Mac OSX V 10.11.6. The fixed width editor is not a good experience IMO.

**Comment by pavel-kolyasnikov** [comment]
I have the same problem after updating to 0.8.17. I have Windows 10. In version  0.8.16 the experience was better. Please return unfixed width.

![boostnote](https://user-images.githubusercontent.com/6136300/33459733-345e9c20-d63c-11e7-9ab1-c402c4bf402c.jpg)

**Comment by kazup01** [comment]
Hi all, I already fixed it. Wait for the next update. https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by kazup01** [comment]
Hi guys, v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
