### ISSUE TITLE
Importing notes not working.

### ISSUE THREAD

**Issue by threkk** [BoostIO/Boostnote#1213]
![screen shot 2017-11-30 at 23 56 40](https://user-images.githubusercontent.com/518481/33459455-3dca53d8-d62a-11e7-8809-696fcd1caf59.png)

**Version**: 0.8.17 (0.8.17)   
**OS**: MacOSX 10.12.6   
**Description**: Quite straightforward. Neither drag and drop or the menu imports neither `txt` or `md` files.

**Comment by SCdF** [comment]
Actual line is here: https://github.com/BoostIO/Boostnote/blob/edfc8d95c80bd611c86dfb05b19cef63cfbc55d9/browser/main/NoteList/index.js#L591

**Comment by SCdF** [comment]
This commit was the problem: https://github.com/BoostIO/Boostnote/commit/f1a90f4a11c4485c35d0e672cef859b1d936f94a#diff-9f5682dd5df751e3be2bb1d16f40f84f

**Comment by kazup01** [comment]
Thanks @SCdF and @mslourens for your support! Wait for the update ;)
#1227 #1258

**Comment by kazup01** [comment]
Thanks for your report @threkk !
