### ISSUE TITLE
Bullet list extension - NaNUndefined error

### ISSUE THREAD

**Issue by tinmice** [BoostIO/Boostnote#1214]
Error when extending a bullet list within two existing points. e.g. entering a carriage return after point 1 (see screenshot) to insert point 2.  Edit adds 'NaNUndefined' before desired bullet point.

![boostnote-bug](https://user-images.githubusercontent.com/8878957/33477048-0d0a08d6-d67c-11e7-926b-4bb6234e502d.png)

**Comment by clone1612** [comment]
I've pushed an update to the Arch package that should fix the issue.

**Comment by tinmice** [comment]
Nice, seems to be sorted. Thanks!

**Comment by kazup01** [comment]
Thanks @clone1612 !
