### ISSUE TITLE
Notes have HUGE margins in v0.8.17

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#1219]
Just updated to the latest version. See this screenshot (all my notes are like this):

![screenshot](https://i.imgur.com/ohnj8dO.png)

**Comment by ikelaiah** [comment]
Same here...

**Comment by kazup01** [comment]
I already fixed it. Please check it. https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by kazup01** [comment]
Hi guys, v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting :)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
