### ISSUE TITLE
Can't update App

### ISSUE THREAD

**Issue by SatoshiKawabata** [BoostIO/Boostnote#1222]
Boostnote says `Update found!` and I push `Restart and Install` to restart again and again. But app is not updated. I use version `0.8.10`, Mac version `10.12.6` .

**Comment by kazup01** [comment]
Hi @SatoshiKawabata , I think that something bug has occurred, could you paste screenshot of console?
But if possible, download the latest version from [here](https://boostnote.io/#download) again is the earliest.
sorry for the inconvenience.

**Comment by SatoshiKawabata** [comment]
@kazup01 I downloaded the latest version so I could updated. Sorry to forget taking a screenshot of console. Thanks.
