### ISSUE TITLE
The note details view is small 

### ISSUE THREAD

**Issue by Sethuraman** [BoostIO/Boostnote#1224]
On a bigger screen, the note detail view should expand horizontally to fit the window. It stays fixed at the center.
<img width="1924" alt="menubar_and_boostio_boost-releases__ _boostnote_app_releases___changelog" src="https://user-images.githubusercontent.com/1607090/33512340-68c9f23e-d754-11e7-98e8-b1d5810003af.png">

**Comment by kazup01** [comment]
Hi @Sethuraman , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
