### ISSUE TITLE
Expand editor width

### ISSUE THREAD

**Issue by SatoshiKawabata** [BoostIO/Boostnote#1229]
This is my request.

I think this editor width looks narrow.
![2017-12-03 9 19 07](https://user-images.githubusercontent.com/1194571/33521097-7208cc78-d80b-11e7-89c1-62e77005ccd7.png)

I want to expand it like this.
![2017-12-03 9 19 55](https://user-images.githubusercontent.com/1194571/33521102-993b4618-d80b-11e7-8cf1-5a1f888eb6f6.png)

Thanks.

**Comment by kazup01** [comment]
Already fixed. https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by SatoshiKawabata** [comment]
OK. I'm waiting for next update.

**Comment by kazup01** [comment]
We will update to v0.8.18 today. Thank you for waiting :)

**Comment by kazup01** [comment]
Hi @SatoshiKawabata , v0.8.18 is out! Fixed the margin of editor. 
Thanks for your waiting ;)

Release Note
https://medium.com/boostnote/boostnote-v0-8-18-release-50e5c143778
