### ISSUE TITLE
Font family setting not working anymore

### ISSUE THREAD

**Issue by gustafekeberg** [BoostIO/Boostnote#1232]
Font family for both editor and preview can not be set in config anymore.

Both editor and preview window always uses the default font from version 0.8.18 or maybe the previous version.

**Comment by kazup01** [comment]
Hi @gustafekeberg, thanks for your report.
Could you tell us to your environment?

**Comment by Harchytekt** [comment]
Hi @kazup01,

I have the same issue on macOS Sierra 10.12.6.

I found this for the preview with the Dev Tools:
```css
font-family: 'Fira Code, Lato','helvetica','arial','sans-serif';
``` 
So, for now, I _"fixed"_ the issue for the preview by adding **'** before and after the comma in the preferences:
```css
font-family: 'Fira Code', 'Lato','helvetica','arial','sans-serif';
``` 

I hope it'll help you.

**Comment by gustafekeberg** [comment]
I'm on macOS High Sierra 10.13.1 and I've found out that the issue occurred for me when updating to 0.8.18

**Comment by foliva** [comment]
Hi! This is an issue also in linux [Arch] with the 0.8.18 version.

**Comment by gustafekeberg** [comment]
Yeah, I also tried it on Ubuntu 17.04. Custom fonts stop working when updating to 0.8.18

**Comment by Mindstormer619** [comment]
Same issue on both Ubuntu 16.04 and Windows 10.

**Comment by MrBMT** [comment]
This issue was introduced back in 0.8.16 #1048 but was never fixed.
