### ISSUE TITLE
Feature Request: Export note as html

### ISSUE THREAD

**Issue by jwmcglynn** [BoostIO/Boostnote#1233]
I've been using boostnote to write blog posts, and one thing that was difficult to get running was duplicating boostnote's markdown rendering to convert the markdown into html, due to the specific extensions that boostnotes uses.

For this purpose, it would be nice if boostnote could export a note to html.

I'd be happy with barebones functionality, and would classify the features like so:

**Minimum Viable**
* Save the html of a rendered markdown note to file.  Links and images may be broken.  For dependent libraries like katex, provide documentation on what should be present for the content to render.

**Nice to have**
* Export to a folder with all images alongside the html file.
* Add any dependent javascript libraries to the html (maybe using hosted js libraries from cdnjs?)

**Comment by jalalmostafa** [comment]
Exporting as PDF would be also nice.

**Comment by kazup01** [comment]
We were released the Minimum Viable at v0.8.20.
[Release Note](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd)
