### ISSUE TITLE
GitHub confused newb howto contribute |

### ISSUE THREAD

**Issue by nickclasener** [BoostIO/Boostnote#1235]
What are the steps to contribute on github?
This will be my first contributions and i'm confused of the mechanics.
Do i need to create a pull request or how does it work?
 
I want to add some vim defaults to the vim emulator.

Thanks in advance!

**Comment by kazup01** [comment]
Hi @nickclasener , I'm glad to hear that ;)
Please fork this repository, and make some pull requests.

This is not place that teach to how to use GitHub, so I close it. Cheers.
