### ISSUE TITLE
Cannot create new note

### ISSUE THREAD

**Issue by dawidry** [BoostIO/Boostnote#124]
Hi, I'm new here. I've just downloaded version from main website (0.6.8). Application is working generally. I can change settings etc. But I cannot create new note. Clicking on + cause nothing, same as pressing cmd+N. 
I'm using it on OSX El Capitan 10.11.6

**Comment by Rokt33r** [comment]
I need more information. You can open console by pressing `Cmd + Alt + I`. Send me the error message!

**Comment by dawidry** [comment]
Shame on me. "No folder to create note" :)
I've created database, even twice to be sure, but I didn't notice that I have to create folder.
I'm closing this thread.

**Comment by Rokt33r** [comment]
Haha, that's not your fault. I think I have to show some alert.  😁 
These feedbacks also help me to make Boostnote better. So, don't hesitate.
