### ISSUE TITLE
What a big demo!?

### ISSUE THREAD

**Issue by mrdulin** [BoostIO/Boostnote#1245]
Can't open demo.
When I take this screenshot, the `bundle.js`file is still downloading.

What a big demo? Can you optimize it ?

![image](https://user-images.githubusercontent.com/17866683/33606456-8814d838-d9f8-11e7-9c08-9e5b53f1b988.png)

**Comment by kazup01** [comment]
This demo is beta. Could you download app from official page? 
We will demo to open source, please wait a moment. Thank you

**Comment by sosukesuzuki** [comment]
Hi @mrdulin ! 
That demo is built by me. 
It was my simple mistake that it was extremely big.:bow:
I'll fix it soon!:+1:

**Comment by mrdulin** [comment]
@sosukesuzuki appreciate it.

**Comment by sosukesuzuki** [comment]
@mrdulin !
I fixed it! please check [demo](https://boostnote.io/demo/)!
