### ISSUE TITLE
Apostrophe ( ' ) displays with space

### ISSUE THREAD

**Issue by ILikeBananas** [BoostIO/Boostnote#1246]
Apostrophes in words are displayed with a big space after it.  I looked in the developper tools and there is no space after it.

The preview : 
![boostnote_error1](https://user-images.githubusercontent.com/18428945/33608424-c002f0e2-d9c4-11e7-88e7-c7ada718299e.png)

The markdown text :
![boostnote_error2](https://user-images.githubusercontent.com/18428945/33608425-c0237862-d9c4-11e7-843b-8003673c7c35.png)

**Comment by kazup01** [comment]
Hi @ILikeBananas , 
Try to change the font-family at Preference.
Thank you.

e.g. I using Avenir
<img width="66" alt="screen shot 0029-12-06 at 3 19 14 pm" src="https://user-images.githubusercontent.com/8602615/33647545-e7674ba4-da98-11e7-8b74-008fe1e8b13d.png">
