### ISSUE TITLE
Why Font is so blurry on windows than other software?

### ISSUE THREAD

**Issue by necan** [BoostIO/Boostnote#1247]
This is Boostnote:
font is so blurry even I changed the preview font
![1](https://user-images.githubusercontent.com/25315125/33614539-9407756e-da12-11e7-87e0-18560e33bb0d.png)

This is Typora:
font is normal and clear
![2](https://user-images.githubusercontent.com/25315125/33614559-a3519f54-da12-11e7-8205-c3d1fd8fb0c9.png)

**Comment by kazup01** [comment]
Are you talking about Chinese? The alphabet is not blurred.
Teach the font that Typora is using.

**Comment by necan** [comment]
@kazup01 In fact, the alphabet is not clear as it preview in browser too, just like not opening ClearType.

**Comment by kazup01** [comment]
Could you tell your environment ? @necan

**Comment by necan** [comment]
@kazup01 
OS: Windows 10 1709
Resolution: 1366*768
Problem: previewing font is not sharp
