### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by gino909** [BoostIO/Boostnote#1251]
How to translate the app UI in other languages?
If you want I can contribute for german and may also for italian UI language
Please let me know, thank you

**Comment by kazup01** [comment]
@gino909 Thank you for your kindly support!

There is no language switching feature. If possible, could you translate docs into German?
https://github.com/BoostIO/Boostnote/tree/master/docs

Thanks again!

**Comment by gino909** [comment]
If you tell me where to find the EN source files I can take a look on it.
From my point of view you should implement a multi-language functionality to get global interests...
Can you add this as feature request? thank you

**Comment by kazup01** [comment]
English docs are here.
https://github.com/BoostIO/Boostnote/blob/master/docs/debug.md
https://github.com/BoostIO/Boostnote/blob/master/docs/build.md

I understand your opinion. Could you post this feature request?
I also would like feedback from others.
Thank you ;)

**Comment by gino909** [comment]
Hi 
Attached the translated files
BR

[Boostnote_mdfiles_de.zip](https://github.com/BoostIO/Boostnote/files/1547499/Boostnote_mdfiles_de.zip)

**Comment by kazup01** [comment]
Hi @gino909 , thank you for your support! I will add these at tomorrow :)

**Comment by kazup01** [comment]
I added the German files. Thank you for your support @gino909 !
#1274
