### ISSUE TITLE
Feature request: Multilanguage user interface

### ISSUE THREAD

**Issue by gino909** [BoostIO/Boostnote#1252]
Hi
for internationalization it would be great if the UI could be available in multiple languages
thank you

**Comment by Nino9614** [comment]
I also think its a good addition to the overall application because as you state on your Website: 

> Trusted by programmers from over 200 countries and regions.

I think a multi language UI would be usefull

**Comment by ranaegis** [comment]
I agree with @Nino9614. Norwegian language support would be _amazing_!

**Comment by bimlas** [comment]
It seems implemented, issue may be closed (at least when https://github.com/BoostIO/Boostnote/issues/1727 is fixed).
