### ISSUE TITLE
📣 Improve the Dark Theme

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#1255]
We will improve the Dark Theme. Here are the 3 examples.
Which do you like among them? Tell us you guys feedback ;)

## A
<img width="1209" alt="ver-a" src="https://user-images.githubusercontent.com/8602615/33754968-fb28b0fc-dc31-11e7-8b2c-6b4974c537d9.png">

## B
<img width="1209" alt="ver-b" src="https://user-images.githubusercontent.com/8602615/33754971-fd6ee8b8-dc31-11e7-9f6d-dabe8503b6f1.png">

## C
<img width="1210" alt="ver-c" src="https://user-images.githubusercontent.com/8602615/33754974-ff5594e2-dc31-11e7-877e-f3cc730e8f2f.png">

**Comment by Nino9614** [comment]
@kazup01 Just to give some feedback and my option :) 
I like Option B the most because its the darkest one. Option A seems to bright and Option C is more like a very dark green Theme rather then black. So i would go for Option A

**Comment by Mindstormer619** [comment]
B seems great :)

@Nino9614 
> So i would go for Option A
Surely you mean B?

**Comment by AnastasiaDunbar** [comment]
**A** is good, I like medium because it's not too dark that it hurts my eyes.

**Comment by petKitsune** [comment]
yes i like A to

**Comment by AnastasiaDunbar** [comment]
![Nino9614 and petKitsune using "to"](https://user-images.githubusercontent.com/11806048/33771787-52d87428-dc6d-11e7-84e6-495c64555adc.png)
🤔

**Comment by Alaev** [comment]
A and B, C is too dark.
Hard to pick one. I think A will win in the long run

**Comment by karanrajpal14** [comment]
I'd pick A. B is too dark. The contrast does hurt the eyes in the long run. Not a huge fan of C either.

**Comment by jmoniatte** [comment]
A

**Comment by ultimatevegance** [comment]
i love B ,it looks cool and badass~,or maybe provide more options or more customizable

**Comment by kazup01** [comment]
Hey all, thank you for you guys feedback!
We added the theme that flavored of "A" at #1268 .

And also, we will add the "B" flavored theme as a another one :)
 Thanks again!

**Comment by Nino9614** [comment]
@Mindstormer619 

> Surely you mean B?

Yeah thank you for the hint :)

**Comment by AnastasiaDunbar** [comment]
Why are the colors so flat though?
The navigator, note list and note details have the same background color.

**Comment by kazup01** [comment]
cc @ytk141

**Comment by ItsPugle** [comment]
I much prefer option A, because of it's materialistic colour theme. I would suggest it be slightly darker, but the other two options are too colour toned - B is too dark blue, and and C seems slight green.

**Comment by kazup01** [comment]
Twitter questionnaire is here 😄 
https://twitter.com/boostnoteapp/status/939030381541470208

**Comment by kazup01** [comment]
v0.8.19 will released in this week. Looking forward it;)
