### ISSUE TITLE
Files left after uninstall

### ISSUE THREAD

**Issue by Kinmarui** [BoostIO/Boostnote#1260]
FYI after following https://github.com/BoostIO/Boostnote/issues/852 two files are left in `\AppData\Local\boost` 
- .dead 1KB
- Update.exe 1,5 MB

also where data where kept? Were they removed or are they stored in separate folder (same as [macOS](https://github.com/BoostIO/Boostnote/wiki/Uninstall-Boostnote))

**Comment by DevelopRx** [comment]
On uninstall, 08.18 leaves files in **AppData > Roaming > Boostnote** directory in WIN 7 too. 

**My Storage** files were not deleted (good) and in the directory that I put them in.

**Comment by josefaidt** [comment]
v0.9.0 - Still seeing this issue, only hinders attempts at fresh reinstallation
Also this prevents Boostnote from functioning after reinstallation attempt (i.e. does not generate startup 'welcome' files, unable to add storage, Boostnote displays what looks like a general 'no notes' splashscreen and a loading icon that does not appear to actually load anything).

After removing both directories noted above, I was able to use Boostnote again.

Windows 10 build 1709
