### ISSUE TITLE
Export as MarkDown (.md) Image Link Broken

### ISSUE THREAD

**Issue by DevelopRx** [BoostIO/Boostnote#1261]
**Export as MarkDown (.md)** only exports literal .md and there is no path to images in :storage.

It would be nice if associated images in the .md file could also be exported from :storage into a separate local folder (images) and the .md revised accordingly. 

Current image link export output in .md: `![MyImage.jpg](\:storage\pfvw27psq2cblnmi.jpg)`

**What I Suggest:**

1. **pfvw27psq2cblnmi.jpg** renamed **MyImage.jpg** and copied into local export **images** folder
2. Link to image is updated in .md: `![MyImage](images/MyImage.jpg)`

Thanks!

**Comment by nlopin** [comment]
I'll fix it this week.

**Comment by DevelopRx** [comment]
Thanks!

**Comment by nlopin** [comment]
@kazup01 this one is done

**Comment by kazup01** [comment]
Thank you guys :)
