### ISSUE TITLE
Suggestion: Few minor changes to the progress bar

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1266]
In Boostnote on macOS 10.13.1, the padding between 0% on the progress bar when using checkboxes is effectively nill, and seems very squished. I think this could be improved with some more padding. 

I also find the progress bar to be bland/disguised. Maybe adding some dark, neutral, earthy tone colour progressions as you go through to 100% would be nice?

![screenshot 2017-12-10 at 4 54 38 pm](https://user-images.githubusercontent.com/22669894/33805826-84f91b44-de0a-11e7-86ad-252a6647b3bf.png)

**Comment by kazup01** [comment]
Hi @ItsPugle , thanks for your suggestion! Fix at #1268. Wait for the next update :)

**Comment by kazup01** [comment]
v0.8.19 is out!
https://medium.com/boostnote/boostnote-v0-8-19-is-out-with-new-theme-markdown-live-preview-and-more-25f6caaad61e
