### ISSUE TITLE
UTF8 wrong character when using @startuml

### ISSUE THREAD

**Issue by gbonazzoli** [BoostIO/Boostnote#1270]
The followin "boostnote" text:

```
@startuml
start
repeat
:Get Username And Password;
note left
Where Presenta la schermata
di login all'utente
end note
if (Username == sAMAccountName) then (yes)
:Check Username And Password 
Against Active Directory;
note left
Il server di Active Directory
è parametrizzato da qualche 
parte su Where
end note
else (no)
:Check Username And Password 
Against Where User Database;
note right
Consueto flusso di 
autenticazione di Where
end note
endif
:Execute Check;
repeat while (Is Password Correct?)
stop
@enduml
```

it is rendered as the attached picture:
<img width="895" alt="screen shot 2017-12-11 at 14 07 50" src="https://user-images.githubusercontent.com/17742862/33832674-52b9bfee-de7d-11e7-9db4-1967ce85c1e4.png">

As you can see, the 'è' char is not interpreted as a valid char.

**Comment by kazup01** [comment]
v0.8.19 is out!
https://medium.com/boostnote/boostnote-v0-8-19-is-out-with-new-theme-markdown-live-preview-and-more-25f6caaad61e
