### ISSUE TITLE
No Pin Icon for pinned notes in Compact View

### ISSUE THREAD

**Issue by AlexEshoo** [BoostIO/Boostnote#1273]
When a note is pinned, there is a pin icon in card view which is nice.
![image](https://user-images.githubusercontent.com/8216513/33841022-87fa829c-de64-11e7-9696-7d3062ca6eed.png)

But when in compact view there is no indication that the note is pinned. Perhaps making the note icon red is sufficient in this view?
![image](https://user-images.githubusercontent.com/8216513/33841039-953419fa-de64-11e7-8e18-72713d8084ce.png)

**Comment by kazup01** [comment]
Hi @AlexEshoo , thanks for your suggestion! I will add it later :)

**Comment by kazup01** [comment]
Added at #1275.

**Comment by Nino9614** [comment]
@kazup01 are you considering to also show the star icon when in compact mode? Or is that to much inside the layout?

**Comment by kazup01** [comment]
v0.8.19 is out!
https://medium.com/boostnote/boostnote-v0-8-19-is-out-with-new-theme-markdown-live-preview-and-more-25f6caaad61e

**Comment by kazup01** [comment]
Hi @Nino9614 , Since Star can be used from SideNav, I think unnecessary to display it on Notelist. What do you think about it?
