### ISSUE TITLE
Export and Import BoostNote library (Backup and Restore)

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#1276]
I am a long time user and collaborator on the Boostnote project but I have been away for a couple months so I am excited to see the recent updates!

When I went to update the BoostNote app to the latest I was sad to see that my 2 years of notebooks data was gone!  The new update had over-written my folders, tags, and hundreds of notes =(

Luckily I had made a backup of the data files for thew folders and notes that is only about a month outdated so I didn't lose 2 years worth of work however if I had not done that myself then it would of been lost!

My proposal is to do something similar to the other ElectronJS app called Eagle app for image collection management.  What they do is allow you to create and load a **Library** which can then also be exported and loaded at anytime.  This allows a few things:

- Allows to create a backup package of your data (folder names, tags, and Note files)
- Allows to easily switch that data collection out and load in a different set of data
- Allows to easily store that data on a USB drive that can be loaded into BoostNote app on any or multiple computers!

If BoostNote built a similar functionality then people can easily backup there data collection and restore it if needed as well as mentioned use it on other computers and even share it with others is wanted!

Below is an image from Eagle App just showing there menu for loading different data collections/libraries...

![](https://www.apollowebstudio.com/screenshots/2017/12/Eagle_2017-12-11_13-07-32.png)

**Comment by Nino9614** [comment]
@jasondavis what you thing of the idea to export all items of the current storage as a .zip file?
I think it will improve the backup process because you can just export the snippets and also upload it to cloud storage if you want. It will also download and upload the files from the cloud storage faster this way.

**Comment by Flexo013** [comment]
In the latest version of Boostnote you can export entire storage or just folders. This way they can be imported at a later date.

Also you can using something like MEGA or Dropbox to put your storage directory in the cloud. Thus allowing for syncing and reducing the chances of data loss immensely.
