### ISSUE TITLE
Custom themes and theme settings

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#1277]
The new themes are great.  Still would like to see an option to load custom themes from a theme settings file so that people can create any number of themes and even share them with the BoostNote community.

Another idea is simply the GUI for selecting the active theme is the settings would be cool to do something similar to Eagle Apps theme setting shown below by showing a preview image of the themes...

![](https://www.apollowebstudio.com/screenshots/2017/12/Eagle_2017-12-11_13-49-41.png)

**Comment by Flexo013** [comment]
I will close this issue for now as you can add your own custom css from the preferences.

@jasondavis If you feel like something more has to happen with this issue, then feel free to reopen/recreate an issue.
