### ISSUE TITLE
Code Notes with too many sub-note files dissapear

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#1279]
When a code note has too many sub-notes/files or the names of those files are too wide it will block the view of all the notes and make it impossible to access some of them...

![](https://www.apollowebstudio.com/screenshots/2017/12/Boostnote_2017-12-11_15-03-09.png)

---

A possible solution would be to count the character length of each note name and when the total number of characters gets up to X number then any note name after that number would be shown in a dropdown list on the far right side of the note tabs.

So if there is 10 notes and the total character length of the names of those notes from the first 5 notes equals X number that we set as the max number then it would show the first 5 notes as tabs and then the last 5 notes would be shown in the dropdown menu that would be to the right of the 5th notes tab

**Comment by nlopin** [comment]
I'm working on this one. It will look like this:
![image](https://user-images.githubusercontent.com/1469636/36357413-c720a664-150e-11e8-855d-cc66a6b7236f.png)

Tab has minimum width and when there are too many tabs, the arrows appear to look through them.

**Comment by Flexo013** [comment]
The fix for this has been merged.
