### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#128]
# Mobile app
## Specs
- Use React Native
  - I think this is the most efficient way to make a prototype app. 
  - Xamarin is considered an alternative. I'm going to switch this after I confront the performance issue.
- Webview will be used to render Markdown preview and to implement codemirror
- User should have a their own cloud storage to sync between desktop and mobile.
  - We currently has no plan to provide cloud. (It should be a paid option, but we know there are many free cloud storage alternative).
  - But, I think we could provide syncing via Bluetooth somewhen.

**Comment by jkurei** [comment]
I'd love to have this app.

One of the most important advantages of Boostnote is, at least for me, that it uses plaintext files for storage. This could be kept if syncing via dropbox was an option. What are your thoughts on this?

**Comment by Rokt33r** [comment]
@jkurei 
I think your comment is irrelevant to this issue. If it is, please create a new issue of it.
Also, could you tell me more specifically why you need it?

**Comment by YaManicKill** [comment]
With this being closed, does that mean there are no current plans for a mobile app? For a note taking app, at least a way to view on mobile would be brilliant.

**Comment by asmsuechan** [comment]
Hi @YaManicKill,
> a way to view on mobile would be brilliant

Strongly true. However, it will not be developed for a while. Because there is no mobile app developer in BoostIO member **for now**.
