### ISSUE TITLE
Writing a word ending with "x" between brackets counts as a Checkbox 

### ISSUE THREAD

**Issue by Romsick** [BoostIO/Boostnote#1280]
# Bug
Whenever you write "**[max]**" or any word ending with the "**x**" character (without the quotes) followed by a whitespace and any word/character, Boostnote interprets it as a **checkbox**, also inside code blocks.

The checkbox counter and the completion bar show there are uncompleted checkboxes in the note. But these aren't checkboxes and at the same time, the box to mark it as complete never appears in this cases.

![boostnote_checkbox_issue](https://user-images.githubusercontent.com/34283607/33854953-bff0d426-dec3-11e7-8175-f3fa743210d6.gif)

## To reproduce

Paste or write the following in a _Markdown Note_:

> foo [max] bar <- IS CHECKBOX
> \```shell
>   foo [max] bar <- IS CHECKBOX
> \```
> foo[max] bar <- IS CHECKBOX
> foo[max]bar <- NOT CHECKBOX
> foo [max]bar <- NOT CHECKBOX```

> [min] bar <- NOT CHECKBOX
> [max] tree <- IS CHECKBOX
> foo [axe] tree <- NOT CHECKBOX
> foo [xxx] tree <- IS CHECKBOX
> foo [paranoiax] tree <- IS CHECKBOX
> foo [xav] tree <- NOT CHECKBOX
> foo [xxb] tree <- NOT CHECKBOX

**Comment by nebbers1111** [comment]
Presuming that a checkbox can only be written in two ways 
`- [ ] unmarked` 
and 
`- [x] marked`
then
https://github.com/BoostIO/Boostnote/blob/4c3e62efadffce2a1d7cf8bf496a522bd4379f5f/browser/lib/getTodoStatus.js#L8
Should be 
`if (trimmedLine.match(/^[\+\-\*] \[(\s|x)\] ./)) { `
adding the brackets around the \s|x to make sure the or statement is only for the character in the box
