### ISSUE TITLE
Having a sub-point without any content makes the higher point h1

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1282]
I just noticed this, but if you have a dot-point with a sub-dot-point below it, like so: 
```markdown
 - Higher Point
   - 
```
the higher point (One above the sub-dot point), becomes a h1 style/# style.

![boostnote headings](https://user-images.githubusercontent.com/22669894/33867390-2430fe5a-df48-11e7-9080-e2f8bffce8b0.gif)

This happens on both new and old notes in all folders

**Comment by kazup01** [comment]
Hi @ItsPugle , this is not Boostnote problem, specification of Markdown.
![dec-12-0029 16-59-42](https://user-images.githubusercontent.com/8602615/33873381-11223ed0-df5e-11e7-9be0-6b4bfea838df.gif)

**Comment by kazup01** [comment]
No problem, enjoy Boostnote ;)
