### ISSUE TITLE
[Feature Request] Notes archive

### ISSUE THREAD

**Issue by piefel** [BoostIO/Boostnote#1286]
Low-priority feature request: I have a couple of notes that I just don’t want to delete yet, but really don’t need to see normally. I created an ‘Archive’ folder, but on start, Boostnote shows all notes in all all folders, which is not quite what I desired.

**Comment by kazup01** [comment]
Hi @piefel , thank you for your feedback!
Actually, the delete feature is same as Archive. Deleting the note enters Trash folder, and delete again deleted permanently. 
How about it?

**Comment by piefel** [comment]
Yes, that is (almost) true. I guess I could change my ways to use that. (At the moment I tend to just blindly clean the Trash from time to time.)
