### ISSUE TITLE
Update console window

### ISSUE THREAD

**Issue by maxart2007** [BoostIO/Boostnote#1288]
Hi guys, update console window runs every hour or so, this is so annoying, I captured the moment for you.
https://dl.dropboxusercontent.com/s/8325omyck38h78t/2017-12-13_03-18-12.png

**Comment by kazup01** [comment]
#1239

**Comment by kazup01** [comment]
Hi @maxart2007 , this bug has already fixed. Please reload your Boostnote!
Thanks for your waiting!
