### ISSUE TITLE
Lacking HiDPI Support

### ISSUE THREAD

**Issue by AnthonyWharton** [BoostIO/Boostnote#1289]
![image_2017-12-13_00-42-10](https://user-images.githubusercontent.com/7091722/33916006-9acf741e-df9e-11e7-99c4-2d96666dc71c.png)

Boostnote does not seem to detect or observe System DPI settings as shown above. Although I am not familiar with how Electron works, I do know this _should_ be possible as Atom works perfectly with HiDPI support.

**Comment by gerd2002** [comment]
This only appears to be an issue on Linux though, as both macOS and Windows scale (tested on my macBook). An easy to hotfix this is to allow the user to zoom the browser window, afterwards maybe look at the dpi or window size to automatically zoom.

**Comment by HymanZHAN** [comment]
Having the same issue here on PopOS 18.04. Hope an in-app solution could be provided. I do not need the app to check and follow my system DPI everytime I open it. It would be sufficient if only the zoom level stays the same after I restart the app.

**Comment by HymanZHAN** [comment]
Ok, so one not so clumsy and effective workaround I found (based on my experience with Chrome browser on Linux quite a while ago) is to add the `--force-device-scale-factor=2.5` to the `Exec` line of `/usr/share/applications/boostnote.desktop`.

So basically the desktop file now becomes:
```
[Desktop Entry]
Name=Boostnote
Comment=Boostnote
GenericName=Boostnote
Exec=boostnote --force-device-scale-factor=2.5 %U
Icon=boostnote
Type=Application
StartupNotify=true
Categories=Development;Utility;
MimeType=text/plain;
```
And it works nicely on my 15.6-inch 4k display.

**Comment by Flexo013** [comment]
I can't easily reproduce this, so closing it for now.

If this is still an issue with the latest version of Boostnote, then please leave a comment here and I'll reopen this ticket.
