### ISSUE TITLE
HTML predefined characters are rendered to symbol on code block

### ISSUE THREAD

**Issue by kyet** [BoostIO/Boostnote#1290]
This issue is only found in the markdown note. The snippet note has no problem.

![2017-12-13_002](https://user-images.githubusercontent.com/5888638/33916864-6f1e720c-dfee-11e7-9a75-95e5d6236e85.png)
![2017-12-13_001](https://user-images.githubusercontent.com/5888638/33916862-6d836dee-dfee-11e7-9c45-649de3e9cce7.png)

I expect that code block (triple `) should escape every character.
Is this intended behavior?

The github's editor is okay to use predefined entitiy on code block.
&para
&para;
```
&para
&para;
```

## Reference
* html predefined symbol table
http://www.madore.org/~david/computers/unicode/htmlent.html

**Comment by ZeroX-DG** [comment]
I think it's fixed in the latest version. Please feel free to re-open this issue if it still exists.
