### ISSUE TITLE
Fail to open Finder on Ubuntu16.04

### ISSUE THREAD

**Issue by Sild** [BoostIO/Boostnote#1291]
Nothing happend on hotkey press (I set ctrl+shift+f to open finder)
It's the main note ability, isn't it?
The error in console appear before shortcut was pressed. Nothing happend at all.

![image](https://user-images.githubusercontent.com/1629069/33927243-8d233cac-dff2-11e7-9559-b3806199c582.png)

**Comment by kazup01** [comment]
Hi @Sild , thank you for your report. Are you using the latest version?

**Comment by Sild** [comment]
@kazup01 yep, I keep the app up to date from 0.8.15 and Finder always not working.
Also ToggleMain working correctly (it hide and open windows even when boostnote not in focus)
![image](https://user-images.githubusercontent.com/1629069/33927430-5e025c68-dff3-11e7-9c39-5b724d0d8d29.png)
![image](https://user-images.githubusercontent.com/1629069/33927440-66f71ab6-dff3-11e7-85af-fe15fc0deebb.png)

**Comment by Sild** [comment]
UP: Linux version:

`Linux some-domain 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by kazup01** [comment]
@Sild  Thanks your info! We will investigate this cause. Btw this bug is not occurring my computer. (Boostnote v0.8.18 / macOS Sierra 10.12.6)

**Comment by Sild** [comment]
I know this bug does not affect macOS users - They also report a little bugs with finder. It's funny, they even have finder =)

**Comment by whizark** [comment]
see also #1044
