### ISSUE TITLE
How to uninstall？

### ISSUE THREAD

**Issue by anquandiyi** [BoostIO/Boostnote#1297]
Can not find the place to uninstall?

**Comment by Rokt33r** [comment]
Which OS are you using?

**Comment by anquandiyi** [comment]
windows 10

**Comment by anquandiyi** [comment]
@Rokt33r windows 10

**Comment by Nino9614** [comment]
Does Squirell or the used packager even generate a uninstall.exe?

**Comment by kazup01** [comment]
Check it. https://github.com/BoostIO/Boostnote/issues/852#issuecomment-328093334
