### ISSUE TITLE
preview mode / edit mode switch button

### ISSUE THREAD

**Issue by lzjqsdd** [BoostIO/Boostnote#1298]
Is there any way to lock preview mode ? sometimes I just want to click or scroll the content ,but don't want to edit it.because it will change the format, I have to cilck otherplack to keep it back

So if it can add a switch button to change preivew mode / edit mode., like:

![2017-12-15 10-25-37](https://user-images.githubusercontent.com/5256218/34023924-69cd19c6-e182-11e7-9708-190b514942ee.png)

@kazup01

**Comment by kazup01** [comment]
Hi @lzjqsdd , how about current version?

<img width="91" alt="screen shot 0030-01-04 at 8 45 40 pm" src="https://user-images.githubusercontent.com/8602615/34562104-434a50de-f190-11e7-8fcd-639a90342c67.png">

**Comment by lzjqsdd** [comment]
seems great , but i'm using v0.8.19. How can i checkout this version?

**Comment by kazup01** [comment]
Here 😄

<img width="584" alt="screen shot 0030-01-05 at 11 15 24 am" src="https://user-images.githubusercontent.com/8602615/34592763-c5186730-f209-11e7-899f-4f67cdabd297.png">

**Comment by lzjqsdd** [comment]
Found it . It can only keep in edit mode, how about keep in preview mode? most time we just want to review notes, not edit it.

Now I just change `Switch to Preivew` to keep in preview mode. Use right click to edit it. This already meets my demand.

![image](https://user-images.githubusercontent.com/5256218/34593427-ba6c6b0a-f205-11e7-80d4-edc9b0c9f5b1.png)
