### ISSUE TITLE
Linux application doesn't correctly close when using x in top right corner.

### ISSUE THREAD

**Issue by dogfish182** [BoostIO/Boostnote#1299]
Hi, 

for the last 2 versions running Boostnote on linux mint 18.2 

start boostnote. use it as normal. Close it from top right. Process does not exit. Trying to start boostnote again will cause it to flash on screen briefly then disappear. 

My window manager is cinnamon

running 

```bash
pgrep Boostnote     
11105
11109
11127
11136
```
shows the processes never exit and I must kill them 

```bash
kill $(pgrep Boostnote)
```

killing the application with ctrl + Q DOES end the process correctly. 

Boostnote 0.8.18

I noticed this issue first in 
.16 (I think) fairly sure it wasn't present in .14. 

This is not possible to capture in the developer console I think, therefore no screenshot.

**Comment by DoctorChe** [comment]
Same problem
Boostnote 0.10.0
Linux Mint 18.3 x64

**Comment by ZeroX-DG** [comment]
I think it's fixed in the latest version. Feel free to re-open this issue if it still exists.
