### ISSUE TITLE
shared table has not border

### ISSUE THREAD

**Issue by Gaddict** [BoostIO/Boostnote#13]
```
|header1|header2|header3|
|:---:|:---:|:---:|
|cell1|cell2|cell3|
|1|2|3|
```

<img width="689" alt="table" src="https://cloud.githubusercontent.com/assets/5138563/14383788/42d13806-fdd2-11e5-87db-7de08aaeb092.png">

**Comment by pollseed** [comment]
I also came out the same collapse :smile:

**Comment by Rokt33r** [comment]
Oh.. I missed this issue. sorry for my late answering. I'll fix it soon.

**Comment by Rokt33r** [comment]
Sorry, sharing on Boostnote homepage has been discarded since v0.6.
But, I'll give you another option, sharing on Gist till the first week of August.
