### ISSUE TITLE
Link to images (not inline)

### ISSUE THREAD

**Issue by tewe** [BoostIO/Boostnote#1300]
Viewing large images in line with text is not very useful. I'd like thumbnails or at least links:

`![image.png](/:storage/je5b75bo1d6j38fr.png)` shows an image in the Markdown preview, but `[image.png](/:storage/je5b75bo1d6j38fr.png)` (without the exclamation mark) is a dead link.

**Comment by kazup01** [comment]
That is a specification of markdown.

**Comment by tewe** [comment]
Is it? Visual Studio Code renders `[import.png](file:///home/tobias/Boostnote/images/961xzvklmlnpcik9.png)` as a working link, Boostnote doesn't render it at all.

**Comment by nlopin** [comment]
@tewe http://spec.commonmark.org/0.28/#images

**Comment by tewe** [comment]
I am not talking about _displaying_ an image, hence the "not inline" in the title. I want a regular link that I have to click to see the image. According to http://spec.commonmark.org/0.28/#example-472 the syntax is correct, and it works in Visual Studio, but not in Boostnote. What am I doing wrong?
