### ISSUE TITLE
Update found but nothing happens

### ISSUE THREAD

**Issue by 6feferonka9** [BoostIO/Boostnote#1301]
Hello, 

I see this notification few times a day "Update found! preparing to update" but nothing happens. I have no update button/link inside Boostnote.

Windows 10
Version of Boostnote: 0.8.17

**Comment by kazup01** [comment]
Hi @6feferonka9 , please check  #1239.

**Comment by kazup01** [comment]
Hi @6feferonka9 , this bug has already fixed. Please reload your Boostnote!
Thanks for your waiting!
