### ISSUE TITLE
Windows 32bit built

### ISSUE THREAD

**Issue by croulibri** [BoostIO/Boostnote#1303]
Hello,

I am currently using Boostnote on my laptop, it's a great app !
I would be interested to use Boostnote on my Windows 32bit desktop.

Have you any plan to release Windows 32bit built ?

Crou²

**Comment by forestail** [comment]
I’m eager for this too.
I built a windows 32bit version on my fork. 
Please download from the following link, if you want.

https://github.com/forestail/Boostnote/releases

**Comment by Flexo013** [comment]
Does the `.exe` file from [here](https://github.com/BoostIO/boost-releases/releases/latest) not work on 32-bit Windows machines?

https://github.com/BoostIO/boost-releases/releases/latest

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
