### ISSUE TITLE
Bug  BoostNote hangs on startup when one storage is linked to a missing flash drive

### ISSUE THREAD

**Issue by kevinsh7** [BoostIO/Boostnote#1304]
I've mapped two storage locations - one on my local machine and one on a flash drive I carry between machines. The idea is that I can still access my local storage even if I forget my flash drive. Every so often I copy files between the two storage folders to sync my notes.

But when I don't have my flash drive and I try to start BoostNote the application permanently hangs - sort of. I can still open preferences and add a 3rd storage folder, since the app is stating that none are available, but none of the storage areas will open. When the flash drive is next inserted, all those storage area mappings I tried to create now all show up and some of them have been duplicates in cases where I tried to remap to the same local storage folder. Unlinking them does get rid of the extra entries.

I would like BoostNote to timeout and simply mark unreachable storage areas as unavailable.

**Comment by ZeroX-DG** [comment]
I think this has been fixed in https://github.com/BoostIO/Boostnote/pull/2801.
Can you check it in our latest release 0.11.13?
I'll close this issue, for now, please re-open this if the problem still exists.
