### ISSUE TITLE
Annoying update window

### ISSUE THREAD

**Issue by maxart2007** [BoostIO/Boostnote#1309]
I'm not sure if my previous issue got lost, but... Boostnote update opens console window regularly many times a day. It annoys and interrupts other users' tasks.
Screenshot: https://www.dropbox.com/s/8325omyck38h78t/2017-12-13_03-18-12.png?dl=0

**Comment by sosukesuzuki** [comment]
Thanks for telling it me.
Could you tell me your OS, its version, and Boostnote's version?

**Comment by kazup01** [comment]
Dup #1239

**Comment by Rokt33r** [comment]
This isn't a duplicated issue. We will discuss this.

**Comment by Rokt33r** [comment]
@maxart2007 Let's check it every day rather than every hour. How do you think?

**Comment by kazup01** [comment]
Hi @maxart2007 , I'm terribly sorry it was my misunderstanding.

**Comment by Rokt33r** [comment]
Fixed. Now we check the update everyday rather than every hour.
