### ISSUE TITLE
[Bug] Nested SQL Comments aren't highlighted correctly

### ISSUE THREAD

**Issue by charliedemsky** [BoostIO/Boostnote#1314]
Nested block comments in SQL code aren't being highlighted correctly - I'd imagine this is extremely low priority, just figured I would report it. Included are two screenshots from the app, as well as a screenshot from SQL Server Management Studio showing the commenting highlighted correctly.

I'm using the app for Mac, version 0.8.18. Running Mac osSierra 10.12.6.

![screen shot 2017-12-20 at 7 41 32 am](https://user-images.githubusercontent.com/16215563/34215131-576357fc-e559-11e7-9965-473e9eeb0c85.png)
![screen shot 2017-12-20 at 7 41 42 am](https://user-images.githubusercontent.com/16215563/34215135-58c6b742-e559-11e7-8bcb-cec88b639386.png)
![screen shot 2017-12-20 at 7 43 57 am](https://user-images.githubusercontent.com/16215563/34215322-cf7ab73a-e559-11e7-96e7-1721eb22864b.png)

**Comment by Flexo013** [comment]
This seems to be working fine in the latest version of Boostnote:

![image](https://user-images.githubusercontent.com/4507015/61995373-f5a7d000-b087-11e9-9e86-646bb05abecf.png)
