### ISSUE TITLE
Link to snippet note not working

### ISSUE THREAD

**Issue by zhuoweiz** [BoostIO/Boostnote#1315]
I linked snippet notes to the markdown note but they are not working

**Comment by robbawebba** [comment]
@kazup01 I would love to help with this issue if it's not currently in development!

**Comment by kazup01** [comment]
@robbawebba Cool! Waiting for your pull request. Thank you 😄

**Comment by kazup01** [comment]
Wait for the next update :)

**Comment by kazup01** [comment]
Wait for the next update. Thanks @robbawebba :)

**Comment by 1l0** [comment]
Is this related to https://github.com/BoostIO/Boostnote/issues/1051, https://github.com/BoostIO/Boostnote/issues/1082 and https://github.com/BoostIO/Boostnote/issues/1111?
