### ISSUE TITLE
Place "delete note" button away from the other buttons

### ISSUE THREAD

**Issue by sferra** [BoostIO/Boostnote#1317]
The "delete note" button is currently placed next to other buttons or - in the worst case - in-between other buttons. This may cause accidental note deletion.

![screenshot from 2017-12-21 10-04-48](https://user-images.githubusercontent.com/596554/34249227-4fd83db4-e639-11e7-9768-6a6fe1fc8f92.png)

I suggest moving the button further away from the other buttons to avoid this issue.
![suggestion](https://user-images.githubusercontent.com/596554/34249383-db247cde-e639-11e7-91df-3e3ddf6eb138.png)

**Comment by mslourens** [comment]
we could also show a confirmation dialog before deleting notes.

**Comment by sferra** [comment]
yes, that is a good idea. also a preference option sould probably be added for "confirm note deletion". but i see that as a separate issue, actually a feature.

what i propose is a usability improvement in the sense that it's probably a bad idea to have "delete" between several UI appearance controls.

**Comment by chiangs** [comment]
Is it really necessary to have a confirmation of the note just goes to a
trash can to be emptied later?

I'm not so sure, I kinda like it the way it is.

Best regards,

Stephen E.  Chiang

**Comment by mslourens** [comment]
You see the same behavior on every OS: they all remove the files to the trash, but also show a confirmation dialog.

**Comment by sferra** [comment]
@chiangs it is generally good to confirm deletions or any destructive changes. also having a preference option to enable/disable such prompts would allow you to keep the current behavior

anyways, this ticket was about a minor UI adjustment, not a "confirm deletion" feature. 
@mslourens please feel free to open a new ticket for the "confirm" feature.

**Comment by chiangs** [comment]
@sferra, true. .. You are right about that 😊
