### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#1318]
Can someone translate [official page](https://boostnote.io/) to some languages?
We are so glad that if contributed here :)
https://github.com/BoostIO/boostio.github.io

Thank you!

**Comment by chiangs** [comment]
I can do Danish.

Best regards,

Stephen E.  Chiang

**Comment by romainwn** [comment]
working on the french translation 👍

**Comment by kazup01** [comment]
Thank you for the tons of cooperations <3

<img width="383" alt="screen shot 0030-01-04 at 8 42 35 pm" src="https://user-images.githubusercontent.com/8602615/34562022-de517ee6-f18f-11e7-92d3-cced56fbdd22.png">

**Comment by aurelkurtula** [comment]
I can translate it in Albania. Is that required?

**Comment by kazup01** [comment]
Hi @aurelkurtula, could you translate here? https://github.com/BoostIO/boostio.github.io
Thanks for your help!

**Comment by aurelkurtula** [comment]
@kazup01 Yes, will do
