### ISSUE TITLE
Collecting embedded Videos?

### ISSUE THREAD

**Issue by lazytyper** [BoostIO/Boostnote#132]
It would be cool if you could embed videos like at slack.com .
So you can note interesting videos...
But `markdown` is not very suitable for that.

**Comment by Rokt33r** [comment]
@lazytyper 
How should we implement it?

I think the below way would be the best because it can be parsed anywhere.
(Of course, Boostnote will render it as an `iframe` tag instead of an anchor.)

```
[![IMAGE ALT TEXT](http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE "Video Title")
```
> http://stackoverflow.com/questions/11804820/embed-a-you-tube-video

**Comment by lazytyper** [comment]
Maybe this service can help you

**Comment by Rokt33r** [comment]
@lazytyper I can't see anything. Could you assign the link again?

**Comment by lazytyper** [comment]
https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCU3mc0yvRNk

**Comment by Rokt33r** [comment]
@lazytyper Great library!
Btw, it is written in PHP. I'm going to try this.
https://github.com/alanshaw/embed-video

**Comment by kazup01** [comment]
I close this because this issue has been left untouched.
