### ISSUE TITLE
hope to add tree mode

### ISSUE THREAD

**Issue by ddatsh** [BoostIO/Boostnote#1322]
like this
![1](https://user-images.githubusercontent.com/1809194/34259784-89f1b0ba-e69e-11e7-9ccf-d5156b5eda0d.png)
)

**Comment by AnastasiaDunbar** [comment]
Yes, I'd love that. To categorize within folders.

**Comment by fellahi-ali** [comment]
It would be a useful and nice feature.

**Comment by Flexo013** [comment]
This comes down to adding subfolders with notes in them, so let's continue this in #125
