### ISSUE TITLE
Starred item count includes notes in trash, but list does not

### ISSUE THREAD

**Issue by initializard** [BoostIO/Boostnote#1326]
To replicate: 

- Create 2 notes, star both
- The left nav will say "Starred 2" and the notes will be visible in the Starred section
- Delete one of the notes
- The left nav will *still* say "Starred 2", but only one note will be visible in the Starred section and the other will only be visible in Trash

Relatedly, when you go to the trash, the stars aren't shown so it makes it difficult to find the old starred ones and you can't unstar them without taking them out of the trash.

**Starred**
![screen shot 2017-12-22 at 11 30 42 am](https://user-images.githubusercontent.com/2012737/34307030-c96e9c40-e70b-11e7-8952-a712c86c0472.png)

**Trash**
![screen shot 2017-12-22 at 11 30 49 am](https://user-images.githubusercontent.com/2012737/34307035-ce676b96-e70b-11e7-8c7c-3cc8dd2c3988.png)

**Comment by robbawebba** [comment]
@kazup01 What's the expected behavior for this issue? Should the "starred" count only include non-trash notes? or should the list of starred notes include notes from the trash?

**Comment by kazup01** [comment]
We were released v0.8.20.
[Release Note](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd)
Enjoy Boostnote :)

**Comment by JohnMunsch** [comment]
Why is this closed? The problem is still there in 0.11.13 today. I had a starred item in my trash and the count shown for starred items was five but the list only showed four. Even once I guessed that the other starred item was in my trash it took guessing and deleting to actually find and get rid of it.

**Comment by ZeroX-DG** [comment]
@JohnMunsch our current latest version is 0.11.15, can you try the latest one?

**Comment by JohnMunsch** [comment]
@ZeroX-DG I don't know why I didn't get auto-updated to 0.11.15 (I usually get update notices), but after I manually updated I was able to create a new note, star it, and delete it and it was removed from the count of starred notes. Thanks.
