### ISSUE TITLE
Print/Export as PDF or HTML

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#133]
@lazytyper suggested. 

As the below link, It doesn't seem to be hard.
https://github.com/hokein/electron-sample-apps/tree/master/printing

So, this feature might be included v0.7.0.

**Comment by NonlinearFruit** [comment]
Exporting to Markdown (particularly Github flavored) could be useful as well.

**Comment by bkjohnson** [comment]
If it hasn't already been added and you're still interested you can check out [Dillinger](http://dillinger.io) for a live demo of this sort of thing.  The "Preview As" and "Export As" buttons both have the options.

**Comment by kazup01** [comment]
Dillinger is looks good!
I added this issue to new todo list. https://goo.gl/Mdu44q

**Comment by schaveyt** [comment]
Images and and printing (via Export to HTML) ...boom...you'll have a OneNote replacement for 80% of its users.

Recommend skipping the PDF, as once rendering into html in the broswer...it can take over the print handing.

**Comment by kostaldavid8** [comment]
Can soumebody please make it? I would do it, but I don't know React too well. It looks simple to me.

**Comment by asmsuechan** [comment]
@kostaldavid8 actually, it' not easy because of a few problems. No problem, you should try now!

**Comment by kazup01** [comment]
Great! I'm looking forward it!👏 @kostaldavid8

**Comment by iursevla** [comment]
Any ETA on pdf export?
I'd love to have this feature.
