### ISSUE TITLE
Can't delete Boostnote-win.exe (0.8.19) installer for it's open in System.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [BoostIO/Boostnote#1330]
It said in the SquirrelSetup.log that on `CheckForUpdateImpl` it failed to load local releases, starting from scratch because it couldn't find `%appdata%\Local\boost\packages\RELEASES`. And on `InstallHelperImpl` it couldn't write uninstall icon because it couldn't find `C:\Users\kazup\project\Boostnote\resources\app.ico`. And on `IEnableLogger` it said "Failed to remove existing directory on full install, is the app still running???" that the processor cannot access the file `%appdata%\Local\boost\packages\boost-0.8.19-full.nupkg` because it's used by another processor.
Also the Boostnote taskbar icon looks like this when opening a shortcut with `%appdata%\Local\boost\Update.exe --processStart Boostnote.exe`: ![icon](https://user-images.githubusercontent.com/11806048/34319828-5ac414ac-e826-11e7-8c21-6af91ab0bd76.png)
The Update.exe's icon cannot be changed.
Boostnote also gave me some messages in Windows 10 about its updates, when they're clicked then nothing will happen.
My Boostnote application has updated but these issues will remain.

**Comment by AnastasiaDunbar** [comment]
This happened because I forgot to close Boostnote before installing that the error appeared then had to close Boostnote and run the installer again, when it was finished without mention it opened Boostnote itself but the installer was running in the background without any CPU usage (and installer not visible in the taskbar) that I killed node.exe and the installer processor but I couldn't delete the installer file.

**Comment by Flexo013** [comment]
Installing a new version of Boostnote while Boostnote is running will now be properly handled.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
