### ISSUE TITLE
Problem with Bullet Points in Markdown

### ISSUE THREAD

**Issue by aadtyaraj** [BoostIO/Boostnote#1332]
![capture1](https://user-images.githubusercontent.com/21054576/34334622-f4e28ff6-e8fc-11e7-8521-04ed1a442100.PNG)
![capture](https://user-images.githubusercontent.com/21054576/34334623-f51d017c-e8fc-11e7-8940-914cdc351293.PNG)

Bullet Points Collapse into One Another.

**Comment by kazup01** [comment]
I could not reproduce it. Could you tell me your environment?

**Comment by ZeroX-DG** [comment]
I also can't reproduce this issue. Closed due to inactivity. Feel free to re-open this if you still have this problem.
