### ISSUE TITLE
Subscript in latex not showing properly

### ISSUE THREAD

**Issue by EnayatUllah** [BoostIO/Boostnote#1335]
![screen shot 2017-12-25 at 3 55 25 pm](https://user-images.githubusercontent.com/4705123/34342871-330d5f42-e98c-11e7-9439-96fae6744958.png)

![screen shot 2017-12-25 at 3 57 48 pm](https://user-images.githubusercontent.com/4705123/34342876-660a1d18-e98c-11e7-9986-b1efeb4855c8.png)

When writing subscripts in latex mode (either inline or block), the subscript tends to be a little higher vertically. In the above screenshots. X and Y are subscripts in one, and in the other, what I meant to write was e_i, however it looks like ei.

**Comment by Flexo013** [comment]
I think that this was fixed when we updated our version of KaTeX.

This looks good to me: 
![image](https://user-images.githubusercontent.com/4507015/61999796-45f35200-b0c9-11e9-87ab-812b28777127.png)
