### ISSUE TITLE
Editor Indent Style not working in Live Preview

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1338]
HI, I'm using version 0.8.19 for Win. Running WIndows10 64bit.

I set the indentation style to 2 spaces in Preferences. In normal edit mode, indent works well. But only in live preview mode, the setting is ignored and 4 spaces are inserted.

## Screenshot
Nothing shown.
![597bca8378d1f640f1a103a220bbf16c](https://user-images.githubusercontent.com/247498/34400087-4360197e-ebd1-11e7-83b5-6cf114dd15cc.png)

**Comment by sosukesuzuki** [comment]
I fixed this issue on #1349

**Comment by kazup01** [comment]
We were released v0.8.20.
[Release Note](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd)
Thanks for your report @cignoir !
