### ISSUE TITLE
Flow chart & Sequence diagram

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#134]
Quiver supports them, and the renderer and its syntax seem to be opensourced!
https://github.com/HappenApps/Quiver/wiki/Getting-Started#diagram-cell

Sequence diagram: http://bramp.github.io/js-sequence-diagrams/
Flowchart: http://flowchart.js.org/

They will be presented with code block.

Examples: 

<pre>
```sequence
Title: Here is a title
A->B: Normal line
B-->C: Dashed line
C->>D: Open arrow
D-->>A: Dashed open arrow
```
</pre>
<pre>
```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
```
</pre>

**Comment by Rokt33r** [comment]
Done. https://github.com/BoostIO/Boostnote/commit/f0d2fb53d4de95244834ffe5d444768db930f057 https://github.com/BoostIO/Boostnote/commit/b18a5be9402f59a3039a1f648196fe1dd4288775

**Comment by eleijonmarck** [comment]
Is it possible to add a preview of the sequence while editing?
