### ISSUE TITLE
CSS code syntax for comments in markdown

### ISSUE THREAD

**Issue by chiangs** [BoostIO/Boostnote#1348]
Mac OSX 10.13.2
Boostnote 0.8.19

When writing a CSS code block, a comment doesn't differ in syntax highlighting/styling. Comments should standout from normal code a grey or faded color for example.

<img width="1136" alt="screen shot 2017-12-29 at 14 31 10" src="https://user-images.githubusercontent.com/10984593/34445898-f2c4b090-eca4-11e7-8bdd-a359089a4fb4.png">

**Comment by ncaron** [comment]
@chiangs 
You are not using the correct syntax for CSS comments. It should be `/* comment here */`.

![comments](https://user-images.githubusercontent.com/13804601/34449703-a45744ae-ecd1-11e7-855d-697627218ba2.png)

I believe this issue can be closed.

**Comment by sosukesuzuki** [comment]
I think so too.
I'll close this issue.
