### ISSUE TITLE
No details about current version and upgrades

### ISSUE THREAD

**Issue by darahak** [BoostIO/Boostnote#135]
Hello,

I didn't find any opened issue about this so...

When I go in the _Help_ menu, there is no _About_ section to see what is the **current version of Boostnote**.

And if an **upgrade** is available, I see no details about the new version, so I cannot compare them and see what I get with the install.

**Comment by Rokt33r** [comment]
I agree with you. btw you can find it from here.

![screen shot 2016-09-30 at 10 00 15 pm](https://cloud.githubusercontent.com/assets/5865853/18992463/6c3aa5f4-8759-11e6-9211-56d940a2e57e.png)

**Comment by darahak** [comment]
Oh! I completely missed that.
Thanks for the tip.
