### ISSUE TITLE
google play version crash

### ISSUE THREAD

**Issue by msongz** [BoostIO/Boostnote#1350]
on Nexus 5x 
ver OPR6.170623.023

**Comment by Alaev** [comment]
same here Nexus 5x v.8.1.0

**Comment by Henry78** [comment]
Crashes after fresh, plain installation when pressing the press sign to create the first note.

**Comment by kazup01** [comment]
Hi guys, sorry for the inconvenience.
Could you post it [here](https://github.com/BoostIO/Boostnote-mobile) again?
Thanks!
