### ISSUE TITLE
Note being replace after delete a tag

### ISSUE THREAD

**Issue by mysafesky** [BoostIO/Boostnote#1352]
Having multiple notes on tag "a", if delete tag "a", the content of the note will be replaced by one of random notes. 

I found this by losing some of notes without deleting them, while I got some repeating note with exactly same content. Then from the dropbox version history, it showed that the content of cson file was completely replaced by one of my other note.

**Comment by l4u** [comment]
same here

To reproduce

1. create note1 and tag it as 'a'
2. create note2
3. remove the tag 'a' from note1

current result: there're two note2, but note1 is not found.
expected result: there should be note1 and note2

**Comment by alec-imperial-veeva** [comment]
This is a pretty big issue for local storage users.  Running into it as well, when the note is overwritten it's also impossible to undo or roll back the note.

**Comment by elazar** [comment]
#1363 addressed #1357; does it also address this issue?

**Comment by liujibin320** [comment]
I encountered this issue on 0.8.19 as well today. I was using the local storage, and lost my one hour work simply because I changed a tag..... :sob:

**Comment by kazup01** [comment]
Hi all, v0.8.20 is out! This bug was fixed. Thanks for you guys waiting.

**Comment by kazup01** [comment]
Release Note is [here](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd).
Enjoy Boostnote :)
