### ISSUE TITLE
Elixir is supported by codemirror but not listed in boostnote

### ISSUE THREAD

**Issue by trinode** [BoostIO/Boostnote#1353]
Hi there,

I saw on the wiki https://github.com/BoostIO/Boostnote/wiki/Syntax-Highlighting that Elixir is supported by the syntax highlighting library, but it's not in the list of languages in the snippet editor, does it need simply adding to a list in boostnote?

**Comment by kazup01** [comment]
Hi @trinode ,
Since I added Elixir on the [wiki](https://github.com/BoostIO/Boostnote/wiki/Syntax-Highlighting) by mistake so I deleted it.
Thanks for your report!

Happy new year from Japan ㊗️

**Comment by trinode** [comment]
@kazup01 since codemirror _does_ support elixir via https://github.com/optick/codemirror-mode-elixir , what would it take to add it to boostnote? 

Happy new year to you also :)

**Comment by kazup01** [comment]
Cool! Could you add it on Boostnote? Thanks ;)

**Comment by trinode** [comment]
I've started (partially working) in PR #1354 could you provide input on my questions?

**Comment by trinode** [comment]
@kazup01 I've started (partially working) in PR #1354 could you provide input on my questions?
