### ISSUE TITLE
[Feature] Scroll sync between markdown & preview pane

### ISSUE THREAD

**Issue by thejasonparker** [BoostIO/Boostnote#1355]
When I scroll up & down within the markdown pane the preview pane does not scroll so I have to move each window separately.

It would be great to be able to sync the scroll of these panes so they move at the same time.  

OS: macOS High Sierra v10.13.2 (17C88)
Bootsnote v0.8.19 (0.8.19)

**Comment by kazup01** [comment]
+!

**Comment by Redsandro** [comment]
A wild pull request appears.
