### ISSUE TITLE
Entire notes disappeared after adding/removing tags

### ISSUE THREAD

**Issue by p-shiyaam** [BoostIO/Boostnote#1357]
Created 2 notes under a folder. While adding/removing a tag to note it is replacing all the other notes in that folder. I lost all my notes because of this.

Content before adding tag:

![1](https://user-images.githubusercontent.com/34997855/34473858-d4c785da-ef9d-11e7-8d45-6726799639b3.PNG)
![2](https://user-images.githubusercontent.com/34997855/34473861-d9cdaa14-ef9d-11e7-9656-226cb4bc46d3.PNG)

After adding tag:

![3](https://user-images.githubusercontent.com/34997855/34473862-dce6e1de-ef9d-11e7-9d0e-1db8b2d63edc.PNG)
![4](https://user-images.githubusercontent.com/34997855/34473864-e02c7372-ef9d-11e7-8552-9b216c5a6da3.PNG)

Please see screenshot 3. Notes content and the selected note snippet is showing different content. Happens while adding/removing tags

Thanks for all your efforts. please fix this asap as i lost all my notes because of this. Thanks in advance.

**Comment by elazar** [comment]
I think I'm running into this as well. At the very least, I somehow end up with multiple notes that have the same content, but different tags.

**Comment by alec-imperial-veeva** [comment]
Looks like it's the same as #1352.

**Comment by mysafesky** [comment]
Thanks @alec-imperial-veeva , it's the same. @kazup01 I think this requires some attention. Before the fix, an alarm needs to be sent to user for not doing anything on tag function to prevent loss of notes.

**Comment by kazup01** [comment]
Hi guys, sorry for the inconvenience. @sosukesuzuki fixed this bug at #1363, we will update to v0.8.20 this weekend.
Thank you for waiting!

**Comment by jnschrag** [comment]
Is there a way to recover notes that were lost? I had this happen to me as well.

**Comment by alec-imperial-veeva** [comment]
I have seen that after deleting the message, sometimes they revert to their original state when using local storage.  The best solution is to use something like dropbox and revert to a previous version.

**Comment by chiangs** [comment]
@jnschrag You could make your storage folder a git repo and periodically push it.

**Comment by jnschrag** [comment]
Thanks for the suggestions! I store my notes in Google Drive and was able to revert to an older version of the files to get the originals.

**Comment by ww7** [comment]
Temporary [binary](https://www.dropbox.com/s/xear3utmzpxqxkd/Boostnote.zip?dl=0) for macOS without this issue

**Comment by kazup01** [comment]
Hi all, v0.8.20 is out! This bug was fixed. Thanks for you guys waiting!

**Comment by kazup01** [comment]
Release Note is [here](https://medium.com/boostnote/boostnote-v0-8-20-release-4e1c1b1e1dbd).
Enjoy Boostnote :)
