### ISSUE TITLE
No simple method for reviewing notes side by side.

### ISSUE THREAD

**Issue by lookbehindyoo** [BoostIO/Boostnote#1364]
It would be nice if we were able to open two notes side by side, so as one could reference a previous note whilst composing a new one. This could be achieved by allowing a split pane system like similar text editors.

This would not be such a problem if it were possible to open two instances of boostnote simultaneously, which does not appear to work (on my system at least - win10). Trying to invoke another instance will open a new one, but kill the previous one silently in the background. 

As an aside, I keep being told that there is an update available, and the notification implies that the software will handle its installation, but this does not appear to be the case. Is this the intended behaviour?

**Comment by Flexo013** [comment]
This idea is more fleshed out (and funded) over in this issue: #1572 

Let's continue this idea over there.
