### ISSUE TITLE
There is a error at Windows 10

### ISSUE THREAD

**Issue by shunchuan** [BoostIO/Boostnote#1365]
My boostnote is installed for the first time，When the installation is completed, it can be opened normally。But when I close the Software window to minimize it and then open,There is a mistake here that I can not enter。

![image](https://user-images.githubusercontent.com/28803269/34591915-a9270094-f1fb-11e7-8f5c-7cb8b77d6343.png)

When I open Task Manager, there are two identical processes here。Then I turn them all off and open the Boostnote.exe，that's ok.But when I close it,emm....I think you should know。
This version is 0.8.19.0.

**Comment by kazup01** [comment]
Hi @shunchuan , thanks for your report! We will investigate this cause.

**Comment by Rokt33r** [comment]
This happens when closing app. We'll fix this problem soon. See #1396 for more information.

**Comment by shunchuan** [comment]
ok, thank you. @Rokt33r @kazup01

**Comment by Rokt33r** [comment]
Fixed!
