### ISSUE TITLE
ページにタグを設定した際に、前回タグを付けたページの内容がコピーされてしまう

### ISSUE THREAD

**Issue by katsumata-ryo** [BoostIO/Boostnote#1366]
英語が不得手のため日本語で失礼します。

### 概要

表題の通り、連続してページにタグ付けをすると
新しくタグ付けをしたいページが、前回タグ付けしたページの内容に変わってしまう。

### キャプチャ

![2018-01-05](https://user-images.githubusercontent.com/6890824/34593615-5b3a7578-f20f-11e7-9e58-14b7a083981f.gif)

### 他

dropbox同期だったので、バックアップから戻せたのですが
ページの内容が失われかねないので対応していただけるとありがたいです。

### 参考情報
OS: MAC OS 10.12.6
バージョン:  0.8.19

**Comment by kazup01** [comment]
Hi @katsumata-ryo san, thank you for your report.
This bug has already been fixed at #1357.

**Comment by katsumata-ryo** [comment]
クローズドの方を確認できてませんでした！
ご対応ありがとうございます！
