### ISSUE TITLE
App crashes trying to create a note

### ISSUE THREAD

**Issue by domcorvasce** [BoostIO/Boostnote#1367]
**Device:** Xiaomi Redmi Note 4

**Android:** 7.0

**ROM:** MIUI 8.1.4

The app crashes when I try to create a note clicking on the float button.

Here's the report:

![Report](https://s18.postimg.org/vhv50vup5/Screenshot_2018-01-05-08-04-59-633_com.miui.bugreport.png)

**Comment by Nino9614** [comment]
Hi, i think you should create this issue in the repository of the mobile app here: https://github.com/BoostIO/boostnote-mobile

**Comment by domcorvasce** [comment]
I'm really sorry.
Thanks for the information.
