### ISSUE TITLE
could make  cloud-hosted platform like "github" or "gitee" integrated into Bootsnotes synchronization？

### ISSUE THREAD

**Issue by xuelingzhizun** [BoostIO/Boostnote#1370]
sorry，my English is bad, I try to say it clean.

of course,this is not bug

could make  cloud-hosted platform like "github" or "gitee" integrated into Bootsnotes synchronization？

because whether China regulatory reasons or Linux ,“ onedriver”, “Googl driver” not so good to use.

**Comment by kazup01** [comment]
Hi @xuelingzhizun , thank you for your opening an issue! Please check #571. Thanks!
