### ISSUE TITLE
Opening the app in Windows 10

### ISSUE THREAD

**Issue by Goraka** [BoostIO/Boostnote#1371]
I just installed version 0.8.19 on my laptop that runs Windows 10 on it.... after the quick installation, I tried opening the app but it doesn't open at all... I have tried this several times before checking my task manager and I see several boostnote process but still app hasn't opened. 

I cleared all the process and tried it again with the same results.

**Comment by yoshiroid** [comment]
I have the same problem. Opening the `boostnote.json` file has the following code in the note list, and even if you delete it, it will be regenerated when you read the notes.

```
{
  "folders": [

    ...

    {
      "color": "#E10051",
      "name": "Unknown 1"
    }
  ],
  "version": "1.0"
}
```

This problem does not occur in macOS.

**Comment by kazup01** [comment]
Hi @Goraka , thanks for your report! Could you paste some screenshots of error log?
Is this problem is same as #1371?

**Comment by Goraka** [comment]
@kazup01 Hey, sorry but I am not even getting an error message! But the problem described there seems similar...

**Comment by kazup01** [comment]
Hey all, please check #1397. Sorry for the inconvenience.
