### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by Frmns** [BoostIO/Boostnote#1372]
Hi, I cant move the scrollbar, until I manually move the document with down arrow.
its exist in live previw and in pref and in md.
I have this issue several releases.
![untitled project](https://user-images.githubusercontent.com/35198052/34651950-7c38808a-f3e0-11e7-8c30-15c794479061.gif)

**Comment by kazup01** [comment]
Hi @Frmns , could you teach me your environment?

**Comment by Frmns** [comment]
Hi @kazup01 , I'm not sure that I understood your question correctly, what environment did you mean?

**Comment by kazup01** [comment]
Hi @Frmns , are you using Windows, Mac or Linux? And also teach me the computer version.

**Comment by Frmns** [comment]
hi @kazup01 , windows 10 (64bit), Lenevo ThinkPad T430s (14.0-inch).

**Comment by Flexo013** [comment]
This bug is no longer present in the latest version of Boostnote.
