### ISSUE TITLE
Render diagrams support

### ISSUE THREAD

**Issue by seblw** [BoostIO/Boostnote#1373]
Hi, 

Would you consider to add support for graphs in Boostnote (something like sequence and flowchart from http://support.typora.io/Draw-Diagrams-With-Markdown/).

**Comment by mslourens** [comment]
this has already been implemented with issue #1062 in Boostnote 0.8.17 with [PlantUML](http://plantuml.com/)

**Comment by seblw** [comment]
Great, thank you!
