### ISSUE TITLE
[Suggestion] Virtual space at the bottom

### ISSUE THREAD

**Issue by patrick-iv** [BoostIO/Boostnote#1375]
Like in Intellij/Android Studio I would like to have virtual space at the bottom of a file. Basically I would like to be able to scroll the bottom content of a file to the top of the screen.

![screenshot from 2018-01-08 13-20-41](https://user-images.githubusercontent.com/1384547/34670503-dfdadde0-f476-11e7-8725-12f400ecda1f.png)

**Comment by kazup01** [comment]
Hi @patrick-iv , there is a good news that you can use this feature from v0.8.19.
Please set from Preferences -> UI. 

<img width="776" alt="screen shot 0030-01-09 at 12 38 56 am" src="https://user-images.githubusercontent.com/8602615/34678124-81599d88-f4d5-11e7-9def-25e1be3d4991.png">


Thanks!
