### ISSUE TITLE
Dropbox Connection

### ISSUE THREAD

**Issue by Len-B** [BoostIO/Boostnote#1376]
Trying to connect to Dropbox on my Asus tablet. All went well until I entered the code. I'm now at a point where the screen is unresponsive so I cannot try again and the suggested folder have not been created in my Dropbox drive. Also, the dreaded stop message occurs.

![boostnote - asus tablet](https://user-images.githubusercontent.com/35223209/34670564-d0f86624-f46e-11e7-86c8-abb70e383616.jpg)

**Comment by kazup01** [comment]
Hi @yosmoc , please post it here. https://github.com/BoostIO/Boostnote-mobile/issues
Thanks.
