### ISSUE TITLE
About inline codes and numeric character references

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1377]
HI, I'm running ver 0.8.19 on Win10.

In some cases, special characters in inline codes are converted to numeric character references.

![32cff6a89a96447677cdb4084e637c48](https://user-images.githubusercontent.com/247498/34705146-9cc8ab60-f541-11e7-83de-c735d172b85d.png)

Is this correct behavior?

**Comment by Flexo013** [comment]
All these scenarios seem to render properly if you add clear newlines indicating start and end of code blocks. Additionally you should keep in mind that the first group of characters after the start of a code block are not displayed as this is the language of the mode block. 

For this reason the `$` is not displayed in this screenshot.
![image](https://user-images.githubusercontent.com/4507015/62011267-4b5aa600-b176-11e9-8029-551da9732f93.png)
