### ISSUE TITLE
Storage no longer seen, all notes appear to be "missing" from application

### ISSUE THREAD

**Issue by johntdyer** [BoostIO/Boostnote#138]
I upgraded to Sierra and this morning opened Boostnote and three is no storage any more. I still see the ~/Boostnote directory with plenty of files on my Mac but the app does not see them.

**Comment by johntdyer** [comment]
Upgraded to 0.6.8 and the problem seems to have gone away...

**Comment by Rokt33r** [comment]
Oh.. I was about to write an answer. I'm glad to hear that! 😄
