### ISSUE TITLE
Feature request: add note source URL field

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [BoostIO/Boostnote#1381]
Hello!

It would be nice to add editable note source URL field somewhere here: https://s3.amazonaws.com/donnicky_screenshots/2018-01-11_12-02-00_be7446c3-8cfc-4a8d-8ca6-8b7534c6fdad.png

**Comment by Flexo013** [comment]
This feature is present in the current version of Boosnote. There is a link you can copy, so you can paste it in other notes to link between notes.
