### ISSUE TITLE
Overwrite notes with another after adding tags

### ISSUE THREAD

**Issue by ww7** [BoostIO/Boostnote#1382]
macOS, Boostnote 0.8.19

After adding tag, note will be overwrite with previously chosen note

**Comment by ww7** [comment]
same bug #168 #181

**Comment by sosukesuzuki** [comment]
Hi! @ww7 !
We knew the bug, and I fixed it on #1363 .
This PR will be include from next version. Please wait next version(0.8.20) :bow:

**Comment by ww7** [comment]
Same bug when build with node version 8+
I need to work and just build, this issue is gone
Binary for macOS [temporary](https://www.dropbox.com/s/xear3utmzpxqxkd/Boostnote.zip?dl=0)
