### ISSUE TITLE
Info for new Version can be misleading

### ISSUE THREAD

**Issue by mmokross** [BoostIO/Boostnote#1388]
When I open the preferences, a hint for "a new version" is displayed. This information is misleading, if I 
have already installed that version. Thus only show that information, if a really new version should be promoted.

Additionally the text of the information is only partially visible, due to the transparent background.

Running Windows 10.

# **Opening the preferences**
![image](https://user-images.githubusercontent.com/1681227/34866965-ab001896-f77e-11e7-8653-822b2cc3c0bd.png)

# **Checking for the actual installed version**
![image](https://user-images.githubusercontent.com/1681227/34866984-c528ffa8-f77e-11e7-87ab-da5416d1b4a5.png)

**Comment by mslourens** [comment]
@sosukesuzuki can we include an official version number in the [notifications.json](https://raw.githubusercontent.com/BoostIO/notification/master/notification.json), so the comparison will be much easier. Now it's just a random string which may or may not include the version number (in whatever form). I suggest to add a version property in the same format as [electron.remote.app.getVersion()](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetversion) (which you see in the InfoTab).

**Comment by Flexo013** [comment]
The green notification is no longer used for announcing new version, so adding logic to compare it to the current installed version isn't quite needed anymore.

If the notification will be used for this in the future then this will have to implemented before such notifications can be made.
