### ISSUE TITLE
Remove menu bar on windows

### ISSUE THREAD

**Issue by meradoou** [BoostIO/Boostnote#139]
Hello,
Is possible to remove suggestion with Ms Windows version? I build from source and it's better without the menu bar.

Thank you

**Comment by Rokt33r** [comment]
Sorry for late answer. I also agree with your proposition. It might be good to be by default.
Could you send the edited code as a PR?

**Comment by mikeres0** [comment]
@meradoou are you submitting a PR for this? I can if you can't.

**Comment by Rokt33r** [comment]
@mikeres0 Could you create a new PR anyway? It would be helpful for me to know how should I tackle.

**Comment by mikeres0** [comment]
@Rokt33r I'll get this done within a few hours 👍

**Comment by Rokt33r** [comment]
Thank you so much!

**Comment by mikeres0** [comment]
@Rokt33r may I have access to Slack?

**Comment by Rokt33r** [comment]
@mikeres0 Sure! Send me an e-mail and I'll invite you. fluke8259@gmail.com

**Comment by meradoou** [comment]
Thank you :+1:

**Comment by mikeres0** [comment]
Issue can be closed?

**Comment by Rokt33r** [comment]
@mikeres0 Thanks for pointing. This is my first open-sourced project. So, I didn't know when I should close the issue.
