### ISSUE TITLE
Code blocks do not have monospace fonts

### ISSUE THREAD

**Issue by SMUsamaShah** [BoostIO/Boostnote#1391]
![image](https://user-images.githubusercontent.com/385283/34892826-7ee6cd9e-f7fc-11e7-9d4b-c477d8bb367a.png)

Also I want to change font of code only to "Fira Code", how do I do that?

Also there is a weird gray box in upper left corner of text editor area. Its there in snippets also.

**Comment by kazup01** [comment]
Hi @SMUsamaShah , you can change the font family from Preferences.

<img width="995" alt="screen shot 0030-01-15 at 7 16 22 am" src="https://user-images.githubusercontent.com/8602615/34942030-1a1b8430-f9c4-11e7-85c7-fad1c6fa7aae.png">
<img width="1018" alt="screen shot 0030-01-15 at 7 16 32 am" src="https://user-images.githubusercontent.com/8602615/34942031-1a2dd356-f9c4-11e7-8957-45d2f6af5eb4.png">

The wired grey box is not reproduced for my environment(macOS / Boostnote v0.8.20). Could you tell me your one?

**Comment by SMUsamaShah** [comment]
@kazup01  If I change Preview Font Family to let say 'Fira Code' (a monospace font), it changes the whole preview to 'Fira Code' instead of only the code fences.

I am on Windows 10 / Boostnote v0.8.20.

I ended up modifying the theme css file like `.cm-s-dracula {font-family: 'Fira Code'; }` but this doesn't feel right.

**Comment by SMUsamaShah** [comment]
There should be an option to set the font of only code fences.

**Comment by pwsandoval** [comment]
I support this idea.

**Comment by tliss** [comment]
This is really a core feature that needs to exist in a _note-taking app for programmers_.

**Comment by ZeroX-DG** [comment]
You can change the style of the preview in the setting now. Goto setting -> interface -> scroll down at the bottom -> check `Allow custom css for preview` and enter your css like that bellow:

![image](https://user-images.githubusercontent.com/12984316/51813614-cb986f80-22e9-11e9-8971-591b320ad690.png)


Result:
![image](https://user-images.githubusercontent.com/12984316/51813590-b6bbdc00-22e9-11e9-8369-0c4e4dfdeb64.png)

**Comment by fareedfauzi** [comment]
For those who use new version of Boosts Note (0.1.4).

Change to `Fira Code !important` at line 212

![image](https://user-images.githubusercontent.com/56353946/74463923-95666780-4ecd-11ea-9642-0041f9d862f4.png)
