### ISSUE TITLE
Windows app isn't terminated properly

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#1396]
After quitting the app with Ctrl + Q, the tray app still alive. And, if I try to quite the tray app again, it will throw an javascript error.

The only solution is killing the app from task manager(Ctrl + Alt + Delete).

![Ctrl+Alt+Del](https://img.memecdn.com/ctrl-alt-del_o_801162.jpg)

**Comment by AnastasiaDunbar** [comment]
Or Ctrl+Shift+Escape.

**Comment by Nino9614** [comment]
Getting the same error when clicking on any option of the tray menu

![boostnotetrayerror](https://user-images.githubusercontent.com/27356972/34933629-db9f7ab8-f9d7-11e7-84f7-ad04619d49d7.PNG)

**Comment by glego** [comment]
Duplicate issue #1264

**Comment by Rokt33r** [comment]
Fixed!
