### ISSUE TITLE
Can you make a note's name be the imported file' name

### ISSUE THREAD

**Issue by Darin726** [BoostIO/Boostnote#1398]
After I imported a markdown file. This note named according to it's content.

 Can you make a note's name be the imported file' name

**Comment by Rokt33r** [comment]
Could you share the content that you've imported? As long as I know, the app should use the content for the title of note.

**Comment by Darin726** [comment]
For example.

I wrote a diary named 2018-01-14.md.

and its content is nothing about the date.

When I import 2018-01-14.md into Boostnote. I want this note be named as 2018-01-14 but not its content. So that I can easy konw when this diary created.

Thanks

**Comment by Flexo013** [comment]
This feature is present in the current version of Boostnote as #1418 was merged.
