### ISSUE TITLE
Text encoding in the exported HTML

### ISSUE THREAD

**Issue by jinwoo** [BoostIO/Boostnote#1399]
Thanks for releasing 0.8.20, especially the HTML export feature!

Everything seems perfect, except the character encoding issue in some browsers. The exported html doesn't seem to specify its character set, so when I open an exported html file in FireFox (57.0.4, Mac), it uses whatever encoding is configured as the default (Western in my case).

That makes some characters displayed incorrectly, such as smart quotes, LaTeX math equations, etc. If I force the encoding to Unicode, they are displayed correctly.

Chrome seems to use Unicode by default and is ok.

Please specify the character encoding in the header of the generated html. I think something like
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```
will work.

Thanks!

**Comment by Rokt33r** [comment]
Sorry for the missing stuff. We'll fix it within the next week! 😄  😄 

감사합니다!!

**Comment by jinwoo** [comment]
Thank you! 감사합니다!

**Comment by kazup01** [comment]
v0.9.0 is out! Thank you for your suggestion @jinwoo . 감사합니다 😄
[Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)

**Comment by jinwoo** [comment]
Verified. Thanks!
