### ISSUE TITLE
Cannot use checkboxes without editing markdown

### ISSUE THREAD

**Issue by Petroochio** [BoostIO/Boostnote#14]
Hello Boostnote people!

I discovered recently that when you go to click a checkbox it opens up markdown view instead of changing the checkbox.

Check box items
<img width="276" alt="screen shot 2016-04-08 at 6 43 35 pm" src="https://cloud.githubusercontent.com/assets/8846179/14399379/27fbec6e-fdba-11e5-996a-a870618c8dbb.png">

Immediately after attempting to click one
<img width="273" alt="screen shot 2016-04-08 at 6 43 43 pm" src="https://cloud.githubusercontent.com/assets/8846179/14399387/3a08c922-fdba-11e5-93dd-eb13c663d2f2.png">

Clicking the third box would normally result in
<img width="284" alt="screen shot 2016-04-08 at 6 47 57 pm" src="https://cloud.githubusercontent.com/assets/8846179/14399414/757af62e-fdba-11e5-9ba6-0ab26623978b.png">

And should alter markdown to be this automatically
<img width="276" alt="screen shot 2016-04-08 at 6 48 04 pm" src="https://cloud.githubusercontent.com/assets/8846179/14399419/83c8ad2a-fdba-11e5-9a22-248f2e28f21a.png">

This is just something I came across when checking off on a todo list. Obviously this isn't a general todo app, but it would be nice if this functionality could happen.

Thanks!
-Petroochio

**Comment by Rokt33r** [comment]
Sorry for my answering.

It sounds reasonable. I'll implement it on this week. :+1:

**Comment by Rokt33r** [comment]
Sorry, I'd forgotten this issue.
**CONFIRMED** : It will be shipped on the next update. #60

**Comment by Rokt33r** [comment]
Done.
