### ISSUE TITLE
Remove `oh-my-cdn` from dependencies

### ISSUE THREAD

**Issue by osiyuk** [BoostIO/Boostnote#140]
In project there already heavily used `npm`. Module `oh-my-cdn` does something similar to `npm`.

Another reason is old `node` versions. The `oh-my-cdn` is written in ES6 style. In `node v0.10.21` there error:

```
$ npm install

> boost@0.6.8 postinstall ~/Boostnote
> npm run vendor


> boost@0.6.8 vendor ~/Boostnote
> oh-my-cdn


~/Boostnote/node_modules/oh-my-cdn/index.js:34
  var promise = new Promise((resolve, reject) => {
                                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "run" "vendor"
npm ERR! node v0.10.21
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! boost@0.6.8 vendor: `oh-my-cdn`
npm ERR! Exit status 8
```

I`ve propose solution, that is not acceptable, due to strict on new node versions. 
https://github.com/Rokt33r/oh-my-cdn/pull/2/commits/325b2ad1061b6635fb25eefbbbabf1b8184d48bd

**Comment by osiyuk** [comment]
@Rokt33r can you label this with https://hacktoberfest.digitalocean.com/

**Comment by osiyuk** [comment]
In `node v0.10.21` webpack won`t support ES6 in config files using babel.

https://github.com/webpack/webpack/issues/1403

**Comment by osiyuk** [comment]
Using `babel-node` and [webpack-dev-server API](https://webpack.github.io/docs/webpack-dev-server.html#api) it's possible to use `node v0.10.21` for at least build codes

**Comment by osiyuk** [comment]
Automation script using webpack-dev-server api
http://stackoverflow.com/a/31952145

**Comment by osiyuk** [comment]
$ babel-node
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.

**Comment by Rokt33r** [comment]
I noticed it, and It is already fixed from the next version!
https://github.com/BoostIO/Boostnote/blob/v0.7.0/package.json#L66-L68

**Comment by osiyuk** [comment]
Already done it.
https://github.com/osiyuk/Boostnote/commit/4ef9c8e8bdacc54f0bf99e9dc23402af62951fdd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R71

**Comment by Rokt33r** [comment]
Fine, but I definitely told you we won't support legacy version of nodejs.
There is no reason to support it.

**Comment by osiyuk** [comment]
It`s actually not affects new versions, but allows me to develop app on v0.10, and maybe someone else in the future. 
I don`t want every day nervously update node.

**Comment by osiyuk** [comment]
Have made running `electron --hot` with HotModuleReplacement on node v0.10.21

![screenshot from 2016-10-11 15-02-44](https://cloud.githubusercontent.com/assets/4260407/19269618/39b8e30c-8fc4-11e6-945e-4c8f188e3bd5.png)

**Comment by osiyuk** [comment]
#143

**Comment by sota1235** [comment]
flowchart.js is still using oh-my-cdn.
So, I will fix it.
