### ISSUE TITLE
Markdown list

### ISSUE THREAD

**Issue by ww7** [BoostIO/Boostnote#1401]
Bug with list when item without spaces (links) not fit in one line
![](https://i.imgur.com/qKF2AZc.png)

**Comment by glego** [comment]
I seem to have the same issue. There seem to be 2 types of issues.

Version: Boostnote 0.8.20

Issues
- [ ] Bullet point formatting issue for long urls (Example List 2)
- [ ] Bullet point formatting issue for urls with dashes `-` (Example List 3)

Example 
```
# Long url test

## List 1
* http://www.google.com/
* http://www.google.com/

## List 2
* http://www.google.com/
* http://www.google.com/123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123


## List 3

* http://www.google.com/
* http://www.google.com/123412341234123412341234123412341234123412341234-123412341234123412341234123412341234-12341234123412341234123412341234123412341234-123412341234123412341234
```

Screenshot

![image](https://user-images.githubusercontent.com/13739461/34915254-2c5a3606-f923-11e7-8337-1c26a56e826b.png)

**Comment by kazup01** [comment]
v0.9.0 is out! [Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
