### ISSUE TITLE
[Feature Request]Keyboard Shortcuts for text formatting

### ISSUE THREAD

**Issue by chennakeshava1998** [BoostIO/Boostnote#1402]
1. Can we have keyboard shotcuts for formatting text quickly like in Evernote? Like Ctrl+b should change the editor space to - <b></b> - with the cursor in between the tags. We could probably do this for many of the features. It saves a lot of time from explicit typing.

2. When we copy a link and paste it into boostnote, can it automatically change it to the format of a hyperlink? For instance, when I paste a link, it must change to - (<pasted link>)[ <cursor must be placed for some text> ]

**Comment by ww7** [comment]
2. – No, without description in [ ] link will not be displayed, but raw link is ok. 
Better to have this via You `1.` suggestion   
(temporary solution to use 3rd shortcut manager software, ex. http://brettterpstra.com/projects/markdown-service-tools/ http://brettterpstra.com/projects/keybindings/ )

**Comment by psychesworld** [comment]
But why there is no 'services' listed in the native app menu? All hotkeys from services are unavailable.
![image](https://user-images.githubusercontent.com/7285276/36834510-11adb566-1d6e-11e8-91fd-c83c998f0439.png)
![image](https://user-images.githubusercontent.com/7285276/36834532-265f9862-1d6e-11e8-877a-1ae5f68c7021.png)

**Comment by Flexo013** [comment]
1. This feature request is continued in #3142 

2. The current version of Boostnote supports this.
