### ISSUE TITLE
Suggestion about the tooltip of new note button for Windows

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1407]
Hi, I'm running ver 0.8.20 on Windows 10.

Thanks for adding a tooltip to the new note button, but ```Make a note ^ + n``` is causing slight confusion for Windows users. According to the file menu, it would be nice to display ```New Note Ctrl + N``` on Windows.

![new_note_button](https://user-images.githubusercontent.com/247498/34924541-5c3cf4a2-f9e7-11e7-823f-4c9ee240008c.png)

![menu](https://user-images.githubusercontent.com/247498/34924544-6013c010-f9e7-11e7-9452-db3174bde8b4.png)

**Comment by kazup01** [comment]
v0.9.0 is out! Thank you for your suggestion @yosmoc :)
[Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
