### ISSUE TITLE
Solarized Dark Styling Problem

### ISSUE THREAD

**Issue by Nino9614** [BoostIO/Boostnote#1409]
I noticed the styling is not applied correctly when using the solarized dark theme: 
![unbenannt](https://user-images.githubusercontent.com/27356972/34934106-85d52bf8-f9d9-11e7-82cf-0fd0b73da397.PNG)

Also there is a black rectangle that appears as soon as i change a preference and save it. 
This rectangle "follows" me on every menu i open

**Comment by kazup01** [comment]
Please not only say but also contribution once in a while. Anyone can fix it easily. Btw thanks for your report :) 
#1412

**Comment by Nino9614** [comment]
@kazup01 you welcome. I would like to contribute but i don't have much experience with react etc. I will improve my skills and try to contribute in the future

**Comment by kazup01** [comment]
v0.9.0 is out! Thank you for your suggestion @Nino9614 . We are looking forward to your contribution :)
[Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
