### ISSUE TITLE
Accent Table Headers

### ISSUE THREAD

**Issue by NonlinearFruit** [BoostIO/Boostnote#141]
Here is a github table. I think accenting the header row in some way helps a lot.
![image](https://cloud.githubusercontent.com/assets/6962125/19252285/4c1bacc8-8f01-11e6-9778-45d2c005b573.png)

Here is a table from **0.6.8**:
![image](https://cloud.githubusercontent.com/assets/6962125/19252334/94184536-8f01-11e6-8b12-5aad3af6a2af.png)

**Comment by Rokt33r** [comment]
It looks much better! Thanks for your reporting! I'll apply it on the update of this week.

**Comment by Rokt33r** [comment]
Shipped!
