### ISSUE TITLE
Boostnote shows different quotation marks

### ISSUE THREAD

**Issue by Ferocit** [BoostIO/Boostnote#1410]
Today I had the problem, that I copy&pasted a note into the terminal and it wouldn't work. I noticed that Boostnote seems to display a different character for the double quotation marks.

This is how it is viewed (you can see that the opening quotation mark is slightly italic):

![boostnote_view_mode](https://user-images.githubusercontent.com/3397899/34938730-ab77cafe-f9e9-11e7-8aab-e6f2b40103eb.png)

While it looks fine in edit mode:

![boostnote_edit_mode](https://user-images.githubusercontent.com/3397899/34938729-ab5f7b98-f9e9-11e7-8bd5-90974a32f6b1.png)

Boostnote should display the correct character I think.

Boostnote: v0.8.16
System: Ubuntu 16.04

**Comment by kazup01** [comment]
Please change the font family from Preferences.

**Comment by sdvdxl** [comment]
not work with Mono type
