### ISSUE TITLE
With v0.8.20 doesn't work save storage

### ISSUE THREAD

**Issue by pilargmez** [BoostIO/Boostnote#1414]

**Comment by kazup01** [comment]
Anyone can not understand even if read this. Please write in detail as possible.

**Comment by pilargmez** [comment]
Hello,

the application gives me several problems, the first is that it does not load the storage, I try to create a new storage and I create it but when I close the preferences panel and I go to the dashboard I do not have it, besides if I reload the application, it disappears even from the preferences panel. Besides that, the date to fold and unfold the side panel does not work ...

I have deleted and reinstalled the application several times but I have not been able to solve the problems,

Do I have any way to go back to the previous version?

Thank you

Pilar.
