### ISSUE TITLE
Option for Minimal Note Listing

### ISSUE THREAD

**Issue by NonlinearFruit** [BoostIO/Boostnote#142]
I am a huge fan of negative space. Currently there is a lot of info being thrown around in the list of notes.
![image](https://cloud.githubusercontent.com/assets/6962125/19252383/d0b1fdb6-8f01-11e6-8c78-47f57c800f8e.png)

 It would be nice if we could optionally turn some of it off. Sorta like this (but with some additional resizing).
![screenshot from 2016-10-10 15-53-52 v2](https://cloud.githubusercontent.com/assets/6962125/19252474/496c2024-8f02-11e6-9c54-0e98801a5f69.png)

**Comment by Rokt33r** [comment]
We're currently working it now. Hang on a little! 👍

**Comment by Rokt33r** [comment]
![screen shot 2016-10-12 at 7 13 33 pm](https://cloud.githubusercontent.com/assets/5865853/19306334/1ff13054-90b0-11e6-8e32-9223bf57b3ff.png)

It will be like the above screenshot.

**Comment by Rokt33r** [comment]
Shipped!
