### ISSUE TITLE
[Feature request] Position:fixed Save button in Preferences panel

### ISSUE THREAD

**Issue by Bubka** [BoostIO/Boostnote#1421]
Hello,

Since the UI preferences panel becomes bigger, a 'position: fixed' save button would be very nice to prevent tedious scrollings.

**Comment by sosukesuzuki** [comment]
I think so too. I'll implement this feature request.

**Comment by Bubka** [comment]
That was quick ! ^_^

**Comment by kazup01** [comment]
v0.9.0 is out! Thank you for your suggestion @Bubka :)
[Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
