### ISSUE TITLE
With v0.8.20 doesn't work save storage

### ISSUE THREAD

**Issue by pilargmez** [BoostIO/Boostnote#1422]
Hello,
the application for mac gives me several problems, the first is that it does not load the storage, I try to create a new storage and I create it but when I close the preferences panel and I go to the dashboard I do not have it, besides if I reload the application, it disappears even from the preferences panel. Besides that, the date to fold and unfold the side panel does not work ...

I have deleted and reinstalled the application several times but I have not been able to solve the problems,

Do I have any way to go back to the previous version?

Thank you

Pilar.

**Comment by Rokt33r** [comment]
Seems your data is corrupted by some reasons. Could you open devtool and attach a screenshot of the error?

Btw, you can download the previous version from the below link.
https://github.com/BoostIO/boost-releases/releases/tag/v0.8.19
(Don't restart the app because it will be updated)

**Comment by pilargmez** [comment]
Thank you! 

This is the error in the devtool
![captura de pantalla 2018-01-17 a las 11 07 46 3](https://user-images.githubusercontent.com/15791289/35037145-e144ee4e-fb76-11e7-99f2-81a7359f2e11.png)

**Comment by pilargmez** [comment]
I just downloaded the previous version and without recharging the application, it directly gives me the same problem that I was saying ...

**Comment by mslourens** [comment]
Boostnote does not have access to your volume **design** so it cannot create the storage folder. Are your sure this volume is connected?

**Comment by pilargmez** [comment]
It is true that in this case I am not having access to the design folder, but when I try to add another storage that can be linked to a new folder, I create it but just after when I go to the dashboard to add a note to that storage, this is not, so, I can not create a new storage I pass a screenshot.
<img width="1280" alt="captura de pantalla 2018-01-17 a las 15 04 41" src="https://user-images.githubusercontent.com/15791289/35046803-5e591ef2-fb98-11e7-8d9b-af72c9d160fb.png">

**Comment by mslourens** [comment]
I would suggest trying to remove all Boostnote config files, because it appears that Boostnote is trying to store your storage config in a file which doesn't exist. When you remove all config files, Boostnote should still be able to startup and will create new files for you in the default directory.

**Comment by pilargmez** [comment]
Ok, thank you!

can you tell me where the configuration files on mac are usually?

**Comment by mslourens** [comment]
it's stored in your home folder (~/Boostnote), which contains a notes folder and a config file (boostnote.json). If it's not in that folder, you should search for boostnote.json.

**Comment by pilargmez** [comment]
I deleted all the boostnote.json files that I had on my computer and the same thing keeps happening to me, I told a co-worker that has the application, it will update to the latest version and it has given the same error ...
<img width="1280" alt="captura de pantalla 2018-01-17 a las 17 14 37" src="https://user-images.githubusercontent.com/15791289/35053362-2d4b0f2a-fbaa-11e7-9cae-f044d6d69b87.png">

**Comment by mslourens** [comment]
It still tries to write the config file to volumes/design. Try clearing the localStorage from the developer tools (under the Application tab).

**Comment by pilargmez** [comment]
Perfect now!! thank you! and congrats for this app, is amazing!

**Comment by mslourens** [comment]
You're welcome, please close the issue.
