### ISSUE TITLE
With v0.8.20 can not close with kill command

### ISSUE THREAD

**Issue by bendo** [BoostIO/Boostnote#1424]
I am using i3 at work and xmonad at home. In both cases I have shortcut 'win+q' to close any application which has focus. Using kill (default signal is 15) doesn't work with version 0.8.20. If I try to close it, it closes boostnote window but it runs in background. So if I try to open it again, I get an error.

**Comment by tock203** [comment]
same here with Arch Linux, i3wm 4.14.1

**Comment by kazup01** [comment]
Duplicate #1396
