### ISSUE TITLE
Comment function not work?

### ISSUE THREAD

**Issue by tianchenwang** [BoostIO/Boostnote#1427]
Mac: 10.13.2
Boostnote: 0.8.20
I love Boostnote, but is there anyway to do line/block comment for code snippet AND markdown? Both not work with cmd+'/'.  The only way I can think of to do block comment is switching to Vim and deal with visual block. 
Thank you.

**Comment by kazup01** [comment]
Hi @tianchenwang , thanks for using Boostnote!
I could not understand it. What is "cmd+'/'" ? Try put "/" inside the code block simply.
Thank you.

![screen shot 0030-01-16 at 11 27 36 pm](https://user-images.githubusercontent.com/8602615/35025745-41befca4-fb15-11e7-9b93-e62263d944bc.png)
![screen shot 0030-01-16 at 11 27 39 pm](https://user-images.githubusercontent.com/8602615/35025746-41d1f034-fb15-11e7-92e0-7b6517c9e8ca.png)
