### ISSUE TITLE
feature request: add hotkeys

### ISSUE THREAD

**Issue by Laggkind** [BoostIO/Boostnote#1430]
I looked through the feature request, but I haven't found this one, although I am confused whether this option might be already there and I am just missing it. I would like to request the possibility to add custom hotkeys for different actions in the hotkey section of my preferences: in the best case to assign a hotkey to every UI-button. 
As I said, my boostnote-version doesn't appear to have this feature, I am using boostnote v0.8.20 on Ubuntu 17.10. If I missed something, I would be happy to be corrected.

**Comment by sosukesuzuki** [comment]
You are not mistaken.:smile: We'll discuss about your feature request:+1:

**Comment by tatoosh** [comment]
What abput global hotkeys for example new boostnote ?

**Comment by Flexo013** [comment]
Duplicate of #2645
