### ISSUE TITLE
[Feature Request] - Multi Comment

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1432]
In notepad++ you can comment with CTRL+K and uncomment with CTRL+SHIFT+K like shown in my gif.
This feature would help us programmers to comment our/in code.

![comment](https://user-images.githubusercontent.com/3670907/35046508-7607cd60-fb97-11e7-837d-821b60603479.gif)

**Comment by kazup01** [comment]
Hi @tatoosh , thanks for your suggestion. Please check #1404.
