### ISSUE TITLE
[Feature Request] - Markdown header and brace folding

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1433]
It would be nice to fold down / unfold markdown topics.
Here a sample, not with markdown headers but with brace in a css file.
![folding](https://user-images.githubusercontent.com/3670907/35046656-ed7efa12-fb97-11e7-8848-68a87c65c263.gif)

**Comment by kazup01** [comment]
Try write markdown in Boostnote. Thanks!

```
<details>

<summary>
Boostnote is a notepad corresponding to markdown notation, which is a tool for organizing and sharing information.
</summary>

- Features

- Search function to find memos in one shot

- Supports markdown notation

-  Export and import to Plain text (.txt), Markdown (.md) format

- Supports PDF saving

</details>
```

**Comment by tatoosh** [comment]
Ok thx @kazup01 but that is not for source code and standard markdown headers.

**Comment by shelper** [comment]
agree, dont know why it is closed, but folding would be  a nice feature to have.
