### ISSUE TITLE
Refactor release notifications 

### ISSUE THREAD

**Issue by mslourens** [BoostIO/Boostnote#1435]
In order to fix issue #1388 (where we need to compare the current appVersion with the latest release) I suggest to change the notifications:

- get the latest release by fetching: [https://api.github.com/repos/BoostIO/Boostnote/releases/latest](https://api.github.com/repos/BoostIO/Boostnote/releases/latest)
- parse the response and retrieve these properties:
  -  tag_name - for the comparison with the app.getVersion() result (after stripping the leading 'v') 
  - body - for the info in the notification, which should be filled in when the release is created and should not contain too much info, otherwise the notification will get too long.
- only display the notification if there is a difference in the comparison between the tag_name and the current appVersion (which will fix #1388)
- remove the repo [BoostIO/notification](https://github.com/BoostIO/notification)

**Comment by Rokt33r** [comment]
> get the latest release by fetching: https://api.github.com/repos/BoostIO/Boostnote/releases/latest

We can do it from here. https://api.github.com/repos/BoostIO/boost-releases/releases/latest

But I'm afraid that its body has too much information.

**Comment by mslourens** [comment]
will it take so much more time to process? I think this way it more consistent with Github and you need more info in order to compare the current version of your app with the latest release.

**Comment by Rokt33r** [comment]
Fixing #1388 is quite simple. Showing the `body` of a release is not that simple. We have to decide where to show it.(Visual design issue)

**Comment by Flexo013** [comment]
The green notification is no longer used for announcing new version, so adding logic to compare it to the current installed version isn't quite needed anymore.

If the notification will be used for this in the future then this will have to implemented before such notifications can be made.
