### ISSUE TITLE
[Feature Request] Embed files

### ISSUE THREAD

**Issue by doiya** [BoostIO/Boostnote#1445]
I want to embed not only images but also other files such as PDF and movies.

```
![PDF](/:storage/hoge.pdf)
```

**Comment by tatoosh** [comment]
Good idea

**Comment by ikelaiah** [comment]
Happy to fund for this feature to be added.

**Comment by CraigDamlo** [comment]
This is the one feature that I'm missing to being able to switch over full time.

**Comment by djpouliot** [comment]
Please add this feature.    Then Boostnote would be ideal for tracking research papers as well as coding project.

**Comment by takacsot** [comment]
I think this is implemented already.

**Comment by luispedrofonseca** [comment]
@takacsot Just tested it and couldn't figure out how to do it. Where did you see that this was implemented already?

**Comment by takacsot** [comment]
I just drag and drop a pdf file to the page.

**Comment by modmod24** [comment]
you can also embed videos using html

**Comment by modmod24** [comment]
and you need to drop it in the editor, not preview (for clarification)

**Comment by djpouliot** [comment]
Dragging the pdf to the page doesn't work for me.     Maybe the newer versions fixed this?   What version do you have?    I have 0.11.2.

**Comment by modmod24** [comment]
maybe the "Welcome to Boostnote!" note that comes with installation can be extended highlighting this feature

**Comment by modmod24** [comment]
work's for me in 0.11.6 onwards. I don't know when it was introduced.

**Comment by modmod24** [comment]
note you have to drag it into the note EDITOR.

**Comment by modmod24** [comment]
!

**Comment by ZeroX-DG** [comment]
Closed as already implemented
