### ISSUE TITLE
Where should issues (such as typo's) be put for the website?

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1446]
Really just the title. Do you want them to be reported over [here](https://github.com/BoostIO/boostio.github.io/)?

**Comment by kazup01** [comment]
yeah please send us pull request there! Thanks :)

**Comment by ItsPugle** [comment]
Uh... only issue: the typo isn't actually covered in that repo's code:
This should say "Sponsors", not "Sponsours" 😃 

![screenshot 2018-01-21 at 8 46 40 pm](https://user-images.githubusercontent.com/22669894/35193393-84642de6-feed-11e7-9eb4-39fe1e835a22.png)

**Comment by kazup01** [comment]
Oops elementary mistake... I will fix it soon. Thank you for your report :) @ItsPugle

**Comment by ItsPugle** [comment]
No problem!

**Comment by kazup01** [comment]
Fixed! https://boostnote.io/
Thanks again @ItsPugle.
