### ISSUE TITLE
[Bug] Boostnote v0.8.20 Windows 10

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1455]
After installing current Boostnote on Windows 10 the App opens the first time.
But i have no chance to open a second time. I did some reinstalling but the same error occurs, see attached image.
Can you please help me?

![grafik](https://user-images.githubusercontent.com/3670907/35324089-f2d00972-00ef-11e8-9959-b4b10f34a43f.png)

**Comment by kazup01** [comment]
Hi @tatoosh , sorry for the inconvenience.
Is bug same as #1264?

**Comment by tatoosh** [comment]
Seems to be the same, THX for linking.
