### ISSUE TITLE
[Feature Request] Provide the ability to open the note in the Main window (so it can be editited)

### ISSUE THREAD

**Issue by webwake** [BoostIO/Boostnote#1456]
Would be extremely useful if you could open a note from the finder to the main window in case you need to make a quick edit

**Comment by kazup01** [comment]
Since we discard the Finder feature at v0.9.0 because this feature used very rarely, so I close this issue.
[v0.9.0 Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)

If you need, please feel free to talk to us. 
Thank you!
