### ISSUE TITLE
vim moving keymap in boostnote

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#146]
Hello,
I'm vimmer also boostnoter. So I'd like to use vim moving keymap in boostnote. Could you develop it?
Thank you!

**Comment by Rokt33r** [comment]
I'd like to do support Vim binging.

But, I am poor at using Vim. Could you help me a little? We have a slack. If you're okay, send a e-mail to me and I'll send an invitation. (fluke8259@gmail.com)

Btw, It doesn't seem to be hard by this. https://codemirror.net/doc/manual.html#vimapi

**Comment by asmsuechan** [comment]
I send you an email just now!
