### ISSUE TITLE
Add a new toggle mode

### ISSUE THREAD

**Issue by waghcwb** [BoostIO/Boostnote#1462]
We have two options on `toggle mode` area `preview` and `edit + preview`.
![deepinscreenshot_20180125152807](https://user-images.githubusercontent.com/6169950/35402780-bbcfd240-01e4-11e8-9640-15593e75aae1.png)

It wold be great if we have another option with only `edit` view.
![deepinscreenshot_20180125153020](https://user-images.githubusercontent.com/6169950/35402877-fd655536-01e4-11e8-9e57-e5ba68d9c5c9.png)
** Display **only** this view..

**Comment by tatoosh** [comment]
Switch to fullscreen, is that enough?

**Comment by waghcwb** [comment]
In fullscreen mode we still have the two view modes..

Take a look at `Intellij` markdown editing

* Editing and viewing result
![deepinscreenshot_20180125154746](https://user-images.githubusercontent.com/6169950/35403693-ae031a52-01e7-11e8-9278-868f9cbf4a66.png)

* View only result
![deepinscreenshot_20180125154752](https://user-images.githubusercontent.com/6169950/35403704-b86821cc-01e7-11e8-9822-012a67be536f.png)

* Only edit
![deepinscreenshot_20180125154758](https://user-images.githubusercontent.com/6169950/35403714-c4fb8f6e-01e7-11e8-99a6-30638a4b7253.png)

Sometimes the user don't want to get distracted with the result of the markdown, or in some cases its just a matter of "space"

**Comment by kazup01** [comment]
Hi @waghcwb , thank you for opening the issue. Actually, there is a feature that enable you to fix to markdown editing mode.

<img width="728" alt="screen shot 0030-01-25 at 1 12 09 pm" src="https://user-images.githubusercontent.com/8602615/35404555-612333ea-01d1-11e8-89b5-a20c7f7cc36f.png">

**Comment by waghcwb** [comment]
Hello @kazup01,

How can I enable this feature?
![deepinscreenshot_20180125161409](https://user-images.githubusercontent.com/6169950/35404667-ec1ba5d6-01ea-11e8-969a-a522e2674a61.png)

**Comment by kazup01** [comment]
Hi @waghcwb , you can use this feature only during Markdown editing.

![jan-25-0030 13-32-54](https://user-images.githubusercontent.com/8602615/35405515-62adca38-01d4-11e8-8de5-fe2b3f5447fc.gif)

**Comment by kazup01** [comment]
Btw, I fixed these buttons layout 😄 #1453

**Comment by jonblack** [comment]
In version 0.11.4 the hide preview (eye?) icon shown above isn't available (or I can't find it), so I'm not able to hide the preview.
