### ISSUE TITLE
Create a launcher

### ISSUE THREAD

**Issue by waghcwb** [BoostIO/Boostnote#1463]
I don't know if this is a issue with my OS (Deepin 15.5, based on Debian unstable), but the installer didn't create a desktop launcher.

![ezgif-4-0249fde67b](https://user-images.githubusercontent.com/6169950/35405256-b83bcbae-01ec-11e8-85bf-6a4f2ad98661.gif)

**Comment by frederik-elwert** [comment]
I can confirm this. The .deb does actually ship a desktop file, installed as /usr/share/applications/boostnote.desktop, but on Ubuntu 16.04, the launcher does not appear in the applications menu/Dash. From looking at the desktop file, I could not find a reason why it would not appear.

**Comment by Flexo013** [comment]
Closing this as the issue no longer seems to occur on the latest versions of the installer.

@waghcwb If this issue does pop up again for you, then feel free to reopen this issue.
