### ISSUE TITLE
PHP code block - Markdown note

### ISSUE THREAD

**Issue by bbsnly** [BoostIO/Boostnote#1467]
OS: MacOS
Version: 0.8.20

PHP language code block is not supported in the Markdown note.

Markdown:
![screen shot 2018-01-26 at 08 59 14](https://user-images.githubusercontent.com/8020430/35430171-6dbc735e-0277-11e8-975a-c7498067294a.png)

Result:
![screen shot 2018-01-26 at 08 59 06](https://user-images.githubusercontent.com/8020430/35430184-74e59908-0277-11e8-9bb7-25f2978cd5a8.png)

**Comment by kazup01** [comment]
Hi @bbsnly , thank you for opening the issue! Is this same as #781 ?

**Comment by bbsnly** [comment]
@kazup01 Yes, it is the same (didn't see it) 👍

**Comment by kazup01** [comment]
No problem 😄

**Comment by albaad** [comment]
I don't know about MacOS, but it works OK for Windows for v0.11.5. You just need to treat it as an actual PHP file (you'ill need the **<?php** at the start);

Markdown
![github_1](https://user-images.githubusercontent.com/16304161/41300947-40f59344-6e67-11e8-8eb1-32031585303f.PNG)

Result
![github_2](https://user-images.githubusercontent.com/16304161/41300993-5fa36942-6e67-11e8-85bf-b1c301798b49.PNG)

**Comment by BruceBenjaminThomas** [comment]
> I don't know about MacOS, but it works OK for Windows for v0.11.5. You just need to treat it as an actual PHP file (you'ill need the **<?php** at the start);
> 
> Markdown
> ![github_1](https://user-images.githubusercontent.com/16304161/41300947-40f59344-6e67-11e8-8eb1-32031585303f.PNG)
> 
> Result
> ![github_2](https://user-images.githubusercontent.com/16304161/41300993-5fa36942-6e67-11e8-85bf-b1c301798b49.PNG)

Doesn't work for me on Mac or IOS even if I start with <?php or <?

**Comment by Flexo013** [comment]
@BruceBenjaminThomas Please create a new issue with screenshots and version number. then we take a further look into the issue.
