### ISSUE TITLE
[Feature Request] Note to Note Link Off / Backlink

### ISSUE THREAD

**Issue by projectrk** [BoostIO/Boostnote#1468]
Hi,

Good day. I would like to ask for a feature request:

Just like in Tomboy Notes, you can link a note to another note. when a note link clicked, it will redirect you to another note that you have set a back link. In Tomboy Notes, you can link a note by its Note Title. Even you rename the title, the linked Title will automatically or a prompt will ask you if you want to rename all linked Title.

Thank you

**Comment by kazup01** [comment]
Hi @projectrk , thank you for opening issue! Please check #1082.
