### ISSUE TITLE
Scroll Past End for Preview as well

### ISSUE THREAD

**Issue by allejo** [BoostIO/Boostnote#1471]
#1267 added the ability for scrolling past the end in the editor but could this also be added to the preview? It's strange to see my typing at the top of the screen on the left side but having to look down to the bottom on the right once my notes get long enough.

**Comment by kazup01** [comment]
v0.9.0 is out! Thank you for your contribution @allejo !
[Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
