### ISSUE TITLE
Suggestion: Use MathJax instead of KaTeX

### ISSUE THREAD

**Issue by gramster** [BoostIO/Boostnote#1473]
I'm not sure why the dev team went with KaTeX when most other Markdown editors seem to use MathJax. KaTeX is inferior in its support. For example, you can't seem to use bold font properly (which is needed for vector variables). Something like:

    $E(\bf{x})$

renders fine with MathJax but in Boost you get:

    KaTeX parse error: Expected 'EOF', got '\bf' at position 3: E(\̲b̲f̲{x})

**Comment by Paalon** [comment]
KaTeX is much [faster](https://www.intmath.com/cg5/katex-mathjax-comparison.php) than MathJax and easier to implement. I think that's why the dev team adopted it.

**Comment by Flexo013** [comment]
@gramster Are there at this point, a year-and-a-half later, still problems with KaTeX; making it inferior to MathJax?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
