### ISSUE TITLE
There's a pane divider missing in the Trash view when you have no trashed notes

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1477]
When you have no notes that are in the Trash - be it they they've been deleted etc, there's a missing pane divider line between the note list and the note content pane:

![screenshot 2018-01-29 at 12 09 14 pm](https://user-images.githubusercontent.com/22669894/35490739-75fe4aba-04ed-11e8-9280-82c108357a51.png)

**Comment by kazup01** [comment]
v0.9.0 is out! [Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)
