### ISSUE TITLE
[Feature Request] Bring in web page title when pasting URL on editor

### ISSUE THREAD

**Issue by avence12** [BoostIO/Boostnote#1482]
I would like to translate plain URL into markdown link with web page title.

Example:
1. Pasting https://github.com/BoostIO/Boostnote/issues on editor
2. Automatically transform `https://github.com/BoostIO/Boostnote/issues` into `[Issues · BoostIO/Boostnote](https://github.com/BoostIO/Boostnote/issues)` by extracting the title tag from HTML

![image](https://user-images.githubusercontent.com/4282367/35544656-8706da02-05a6-11e8-99d0-0cb2517b570d.png)

**Comment by glego** [comment]
You should have the ability to disable it and take into consideration when pasting between braces it doesn't nest.

like
```
([Issues · BoostIO/Boostnote](https://github.com/BoostIO/Boostnote/issues))
```
