### ISSUE TITLE
Missing notes after updating

### ISSUE THREAD

**Issue by hmojicag** [BoostIO/Boostnote#1485]
Not sure how it happened but some of my notes are unlinked.

Here's a screenshot of my boostnote, as you can see boostnote only "opens" 3 notes for the folder "haza"
![image](https://user-images.githubusercontent.com/6140325/35585010-5975706a-05bc-11e8-8a57-4900c447bc39.png)

Here's the hashcode of the folder "haza":
![image](https://user-images.githubusercontent.com/6140325/35585047-765bd3d6-05bc-11e8-8cc5-751cb53f0b9f.png)

But when I search the notes folder looking for my missing notes using the hashcode/key of the folder as search parameter I can see all my notes which must be 6 for this folder, other folders suffer the same issue:
![image](https://user-images.githubusercontent.com/6140325/35585125-a871a9fe-05bc-11e8-967d-af98b71f5066.png)

Why Boostnote is not loading those notes?
What can I do to fix that?

**Comment by anhhuyalex** [comment]
Hello,

I also experience a similar issue. After an update, some notes seem to have disappear from Boostnote. I can't see them, nor can I search them. Nevertheless, everything is linked (all the folders are visible). Furthermore, the .cson files still exist in the linked folder. Most notes remain, but some notes have mysterious disappeared.

**Comment by ithinuel** [comment]
Hi, I had a similar issue solved by Ctrl+R.

**Comment by Flexo013** [comment]
@hmojicag Have you experienced this issue with any of the latest builds of Boosnote?

**Comment by hmojicag** [comment]
Noup, sorry guys after that bug/thing/feature deleted my notes I got to move to a note keeper app that let handle and backup my notes in a simpler way, something that is not tightly coupled with the app itself and more like a simple text/markdown editor.
Thanks anyway.
