### ISSUE TITLE
Search function not refreshing searching list

### ISSUE THREAD

**Issue by dreadful44** [BoostIO/Boostnote#1486]
When i edit an snippet description, after than i search updated snippet with added text but not found. if i change the folder or tag navigation menu search again it's work.

**Comment by bimlas** [comment]
Translating to English:

The note's title in the notes list does not updated when the list is narrowed by search text.

![image](https://i.imgur.com/SaqKXnd.gif)

**Comment by dreadful44** [comment]
"Translating to English" is very nice word bro ! Didn't you find any other title for describe to my message ?

**Comment by stenalpjolly** [comment]
@dreadful44 @bimlas Is this issue still valid? I was just checking this. It seems working for me.

**Comment by bimlas** [comment]
Issue seems to be solved on 0.11.4.
