### ISSUE TITLE
Titlebar icon for Boostnote is pixelated

### ISSUE THREAD

**Issue by Timber232** [BoostIO/Boostnote#1488]
Titlebar icon for Boostnote is pixelated:

![image](https://user-images.githubusercontent.com/627637/35626163-dd5a0b6a-0662-11e8-8ed4-621b154c2ed4.png)

**Update:**

Current environment: 
OS: Windows 10 1709
Boostnote Version: v0.8.20

**Comment by kazup01** [comment]
Could you tell us your environment?

**Comment by MaiTestarossa** [comment]
same problem in windows 10 1703,include taskbar's icon.

**Comment by Timber232** [comment]
@kazup01 I've updated my post with my environment information :)

**Comment by kazup01** [comment]
Thank you guys :)

**Comment by Redsandro** [comment]
In Cinnamon (Linux Mint) the icon is micro-sized. (4k laptop)

![image](https://user-images.githubusercontent.com/1702193/35777682-75f38eee-09b2-11e8-964a-3b773c049af6.png)

Can you see it?

**Comment by Redsandro** [comment]
Alt + Tab icon in Cinnamon is also low quality:

![image](https://user-images.githubusercontent.com/1702193/36047835-8964b0b4-0ddd-11e8-8809-77b651311c03.png)

**Comment by teatwig** [comment]
Seems to be a duplicate of #1046
