### ISSUE TITLE
Add option for MD preview centering.

### ISSUE THREAD

**Issue by A-Lamia** [BoostIO/Boostnote#1496]
If possible it would be really nice to add an option that centers the content of the markdown preview instead of it floating to the left.

**Comment by ItsPugle** [comment]
You should be able to write `<center>` HTML tags around content to centre it 🙂

**Comment by islanddog** [comment]
@A-Lamia - I always use [https://gist.github.com/jonschlinkert/5854601](url) for all my Markdown questions 😄.

**Comment by A-Lamia** [comment]
Tried it out and it just stretches everything to to 100%, i just used some css to fix to ce

**Comment by A-Lamia** [comment]
Tried it out and it just stretches everything 100%, I'm using some simple CSS atm to center it. 

##### <center> tag
![img](https://ss.lamia.io/i/Boostnote_wQa3RBBmf.png)

##### Custom CSS.
![img](https://ss.lamia.io/i/Boostnote_puq2olpbX.png)

**Comment by Flexo013** [comment]
I'm unsure about the `<center>` tags working in the preview. 

@A-Lamia Have you found out how to get this to work or would you still like this new feature?

**Comment by A-Lamia** [comment]
With the new custom CSS support i don't think it's really needed.

**Comment by Flexo013** [comment]
Alright, thanks for the info!
