### ISSUE TITLE
[Bug] Clicking on a link doesn't open the page

### ISSUE THREAD

**Issue by jinwoo** [BoostIO/Boostnote#1500]
With the new release (v0.9.0), there are two related issues.

* When clicking on a link from the markdown preview, it opens the browser but its page is opened empty, without going to the linked address.
* And it always creates a new browser window even when there's already a browser window open. It used to open the page in a new tab, not in a new window. I *strongly* prefer the former.

I'm seeing these on my MacBook Air (macOS 10.13.3).

**Comment by kazup01** [comment]
Hi @jinwoo , thank you for your trying and reporting!

> When clicking on a link from the markdown preview, it opens the browser but its page is opened empty, without going to the linked address.
I can not reproduce this bug. Is there anyone occurring?

macOS Sierra 10.12.6

**Comment by Paalon** [comment]
I cannot reproduce the bugs but I have met them before on boostnote and other electron-based apps. I don't know that's why but I restarted them then the behavior have not occurred.

**Comment by jinwoo** [comment]
I can't reproduce anymore either. I didn't restart boostnote or reboot my machine, but it now just works. Closing.

**Comment by jinwoo** [comment]
For posterity:

I think I know how this can happen. This seems to be a Chrome bug. This happens when Chrome is the OS's default browser and when Chrome has been updated in the background but hasn't been restarted yet. The problem resolves once Chrome is restarted.

**Comment by raffienficiaud** [comment]
I do not know how is this related to #821 , but on my machine I never installed chrome (nor chromium).
