### ISSUE TITLE
[Feature Request] Don't change install folder on new update

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1505]
In my filesystem in windows 10 every update generates a new folder.
Can't you install in a boostnote folder without app version?

![grafik](https://user-images.githubusercontent.com/3670907/35782951-63d29bda-0a00-11e8-8ed1-c1ce2d806daf.png)

**Comment by islanddog** [comment]
This is done as the current update method is a pull from the 'Releases' category via GitHub using Squirrel Updater. I can see this being a good method to handle updates as if there is an issue with an update they can rollback or have all changes in an individual container. I am sure the update policy will involve an outdated folder removal in the future.

If they were to put all updates in the same folder they would have to pull a secondary branch or global file set which could provide a lot of unneeded issues.

**Comment by Flexo013** [comment]
@tatoosh Is this still a problem in the latest versions of Boostnote?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
