### ISSUE TITLE
[Bug] New notes and the all of the top notes aren't shaded

### ISSUE THREAD

**Issue by Paalon** [BoostIO/Boostnote#1507]
When I started boostnote, the folder's top note "test" was selected and should be shaded but not.
![2018-02-05 13 14 40](https://user-images.githubusercontent.com/11065457/35788468-7d3d8ee0-0a78-11e8-8b2b-9160494d4157.png)

I selected the note "test" and it was shaded.
![2018-02-05 13 15 05](https://user-images.githubusercontent.com/11065457/35788464-77e1ddb6-0a78-11e8-85ae-d7d9b4b647f4.png)

Then I created new note but the new "Empty" note was not shaded. The previous selected note "test" is shaded.
![2018-02-05 13 14 53](https://user-images.githubusercontent.com/11065457/35788461-72104616-0a78-11e8-802f-eb8e6bac91fe.png)

**Comment by nlopin** [comment]
I've noticed that too. I'll fix it

**Comment by Redsandro** [comment]
Both issues are fixed in #1528.
