### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#151]
Hi,
I'd like to use boostnote as a presentaton tool.

So I want 3 function below
- fullscreen mode
- pagination
- pasting images

Perhaps, are there in it already?
Thanks!

**Comment by Rokt33r** [comment]
Pasting images and Fullscreen mode is currently developing.

But, I can not understand *pagination* function.
Could you explain more about this? Did you mean [Marp](https://yhatt.github.io/marp/)?

**Comment by mikeres0** [comment]
I believe he means pagination within the notes, sections as such.

**Comment by Rokt33r** [comment]
I need more explanation how should it be realized.
Does it mean we should make a new format of note, like Wiki or Gitbook?

**Comment by asmsuechan** [comment]
Sorry for my absent.
I mean it's pagination like Marp, not Wiki or Gitbook.
Perhaps, it's nice to implement a function which exports to Marp.

May I ask if you understand what I mean?

**Comment by Rokt33r** [comment]
@mikeres0
I and @asmsuechan talked at slack. He want pagination function only for presentation mode. 
We might be able to use [gnab/remark](https://github.com/gnab/remark). But, I think we should mimic this library because it uses another markdown renderer.

**Comment by Flexo013** [comment]
@asmsuechan Is this feature still desired by you?

**Comment by arcturus140** [comment]
2 out of 3 functions are already supported

**Comment by Flexo013** [comment]
As @arcturus140 pointed, the only thing that isn't present currently is pagination.

@asmsuechan If you would really like this feature then feel free to open up a new issue with the feature request (preferably mentioning this issues number 151).
