### ISSUE TITLE
[Feature request] Export HTML including all files | pandoc?

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1510]
I tried the export from Boostnote, nice to have but all references in the HTML are linked to the local installation like this part of an export:

```html
</style>
      <link rel="stylesheet" href="file://C:\Users\tatoosh\AppData\Local\boost\app-0.9.0\resources\app/node_modules/katex/dist/katex.min.css">
      <link rel="stylesheet" href="file://C:\Users\tatoosh\AppData\Local\boost\app-0.9.0\resources\app/node_modules/codemirror/lib/codemirror.css">
      <link rel="stylesheet" id="codeTheme" href="file://C:\Users\tatoosh\AppData\Local\boost\app-0.9.0\resources\app/node_modules/codemirror/theme/seti.css">
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head><body data-theme="dark"><h1 data-line="0" id="atTemplate">Test</h1>
<p data-line="2"><img src="file:///Z:\owncloud\Boostnote\images\0.ashi0q6vv7.png" alt="0.ashi0q6vv7"></p>
```

Please include all files like **CSS** and **IMAGES** directly in the html.
For Visual Studio Code (https://github.com/dfinke/vscode-pandoc) or Atom there a plugins who are calling pandoc.

On my windows system i am using a batch file to convert markdown to html or pdf.
```
pandoc %1 --toc -c D:\pandoc\tatoosh.css --self-contained --toc -t html5 -o %1.html
````

So please change the export or give us an option for custom export with args, so i can call my batch file.

**Comment by islanddog** [comment]
I agree with you; I believe right now the export functionality for HTML is still in its infant stages. An option should be available to each do (Documents - Current) or All (which should include all project files). I think the only way to achieve this would be to have a 'Project Folder' of sorts to handle the export. For this type of functionality I still utilize Sublime Text but I do hope Boostnote has it in the future.

**Comment by nlopin** [comment]
It is fixed at #1306. This pull request is currently on review.

**Comment by nlopin** [comment]
@kazup01 @Rokt33r  we can close the task. #1306 is merged

**Comment by kazup01** [comment]
Thank you guys :)
