### ISSUE TITLE
Note link generate different hash on different machine

### ISSUE THREAD

**Issue by tonyjiangh** [BoostIO/Boostnote#1512]
I'm using dropbox to sync my notes on different machine.
The problem here is that the note-link is different on different machine. 

For example on of my note gives different link on:
OS X: `[Practice test](64f35425d24add73cb26-c695935f9ed00978b6ee)`
Ubuntu: `[Practice test](4d3ab8df951b220b623f-c695935f9ed00978b6ee)`

Why not just get rid of the first part and only leave the note hash?

* OS: OS X, Ubuntu
* Version: v0.9.0 on both system
* Storage: Dropbox

**Comment by mirsch** [comment]
Same Problem here.
First Part of the hash is the storage which is different on every client.
Maybe one could use an UUID if the hash of the note is not unique across storages but It makes no sense to me to have a client specific part in the link.

**Comment by Rokt33r** [comment]
Let's discuss this on #1623.
