### ISSUE TITLE
[Bug] Broken syntax highlighting when adding a plantuml sequence diagram

### ISSUE THREAD

**Issue by chbndrhnns** [BoostIO/Boostnote#1513]
When writing a Plantuml diagram, the syntax highlighter gets confused by an opening bracket when doing something like

```
@startuml
participant "RADIUS" as  r
[->r: Access Request
@enduml
```
![unbenannt](https://user-images.githubusercontent.com/7534547/35863099-e6563960-0b4d-11e8-9e98-5f93ec33fc33.PNG)

**Comment by billmetangmo** [comment]
The bracket here is one of your actor ?

**Comment by chbndrhnns** [comment]
The bracket is for indicating an actor that is not part of the diagram (in the plantuml manual this is under the incoming/outgoing messages section.

**Comment by billmetangmo** [comment]
Oki. I did not know this plantuml special character. Thanks :) !

**Comment by Flexo013** [comment]
This bug is no longer present in the latest version of Boostnote:

![image](https://user-images.githubusercontent.com/4507015/62012000-a7c2c300-b180-11e9-8104-86b268342ba3.png)
