### ISSUE TITLE
Problem with mac dmg file. Zip works

### ISSUE THREAD

**Issue by azri92** [BoostIO/Boostnote#1517]
I downloaded the dmg file from boostnote.io & the [release page](https://github.com/BoostIO/boost-releases/releases/tag/v0.9.0). The title of the expanded drive was "Android Studio 3.0.1.0". At first the screen window will be empty. After closing and reopening, I will see this:
![screen shot 2018-02-07 at 2 55 15 pm](https://user-images.githubusercontent.com/2047666/35905097-c584acde-0c20-11e8-85a6-1142248bb112.png)
When I try to drag the Boostnote app to Applications, I get this error:
<img width="577" alt="screen shot 2018-02-07 at 2 58 56 pm" src="https://user-images.githubusercontent.com/2047666/35905119-d504adee-0c20-11e8-9336-e85ae99c2edc.png">

**Workaround**: The zip file from the release page works.

**Comment by Rokt33r** [comment]
Which version did you download?

**Comment by Rokt33r** [comment]
Please re-open this if the problem happens again after downloading v0.9.x(or later).

**Comment by azri92** [comment]
I tested it just now with the latest version (0.9.0) & it's working fine. :)
