### ISSUE TITLE
[Feature Request] add Nested sub folder support

### ISSUE THREAD

**Issue by mehrdad-shokri** [BoostIO/Boostnote#1518]
I'm coming from [this](https://github.com/BoostIO/Boostnote/issues/125) feature request,  
as it states there is a WIP for adding sub categorical authoring just like a book support.  
One of the main maintainers (@Rokt33r) stated was working on this feature but there wasn't something announced since then.  
Any updates on this?

**Comment by Flexo013** [comment]
This feature will be continued on #125.
