### ISSUE TITLE
Search bar as filter instead of dropdown with results?

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#152]
This is somewhat of a feature request/enhancement: Whenever I use the search bar in the main application window, I wish that it would filter the list of notes below instead of showing a popup with results. I think this would be more useful in many ways, one being that you could easily search in one folder only.

**Comment by mikeres0** [comment]
I don't mind taking this on @Rokt33r

**Comment by tejado** [comment]
To be honest, I like the extra popup. So maybe do this additional (and maybe the default option)?

**Comment by mikeres0** [comment]
Yeah I agree, guess we could put it as a setting

@tejado you too dude :)

**Comment by Rokt33r** [comment]
Yes, we can provide it as an option.

@tejado Btw, Is there a way to make powerful the extra popup?

@mikeres0 It would be so thankful. Ask me anything whenever you stuck.

**Comment by tejado** [comment]
@Rokt33r sorry but can you please explain your question? :)

**Comment by mikeres0** [comment]
@tejado get on the slack channel mate

**Comment by Rokt33r** [comment]
@tejado Sorry for my bad English. 
The current popup should be more polished. I just thought you might have some idea to improve it because you seem to like the popup.

Btw, as @mikeres0 , we have a slack. If you want to join us, please send me an e-mail to me! fluke8259@gmail.com

**Comment by pba1** [comment]
@Rokt33r Popup polish ideas: I think it should show show the taglines for each found note as well. Also I would like options to search in "All" or "current storage" or "current folder".

**Comment by mikeres0** [comment]
@pba1 I'm not sure if this project is being maintained anymore.

**Comment by huettenhain** [comment]
There has been some activity recently, and I still think that the feature would greatly improve boostnote.

**Comment by larsborn** [comment]
+1 agree with @huettenhain. Is here someone, that would still take this on?

**Comment by kazup01** [comment]
Sorry to late supporting.
Thank you for feedback and discussion!
This improvement is not progressing.
We want to polish it but we would deal with it to later(because we update other features).
If someone sends us a pull request we will check it, can somebody help us?

**Comment by kazup01** [comment]
I agree with @huettenhain san's "filter the list of notes below instead of showing a popup with results"👍

**Comment by huettenhain** [comment]
Could this be added to the [list of requested features](https://github.com/BoostIO/Boostnote/wiki/List-of-the-requested-features)? This is definitely my most wanted feature for boostnote.

**Comment by kazup01** [comment]
I added it to list of requested features. What do you think about this? @asmsuechan

**Comment by kazup01** [comment]
Hi guys, sorry for late support. @sosukesuzuki is trying this feature!

**Comment by kazup01** [comment]
Merged! #600
Great work by @sosukesuzuki 🎉
We will update it at next week!

**Comment by huettenhain** [comment]
This makes me very, very happy.

**Comment by kazup01** [comment]
Released on v0.8.10.
@sosukesuzuki worked hard! Enjoy!
