### ISSUE TITLE
Font is blurry. Please use subpixel anti-aliasing.

### ISSUE THREAD

**Issue by necan** [BoostIO/Boostnote#1522]
OS: Windows 10 1709
Resolution: 1366*768 14 inches

All fonts except Menu bar are blurry. I find boostnote is using  grayscale anti-aliased.

![tim 20180209164228](https://user-images.githubusercontent.com/25315125/36019169-59753b86-0db9-11e8-8de2-c5e9c8f52036.png)
![tim 20180209164257](https://user-images.githubusercontent.com/25315125/36019173-5cf19156-0db9-11e8-99cb-c1e277516e35.png)
![tim 20180209164521](https://user-images.githubusercontent.com/25315125/36019179-61969828-0db9-11e8-95fe-f2dee4e49c87.png)

Only fonts in Menu bar are using subpixel anti-aliasing.

![tim 20180209164318](https://user-images.githubusercontent.com/25315125/36019069-0c97a916-0db9-11e8-9ea9-0e53b742e3d3.png)
![tim 20180209164434](https://user-images.githubusercontent.com/25315125/36019079-13b4a578-0db9-11e8-93ed-01cf3cb428a5.png)

but when I open the html exported by Boostnote in chrome, font is normal.

![tim 20180209165423](https://user-images.githubusercontent.com/25315125/36019379-0ee06ac2-0dba-11e8-8e1b-ff750cfef544.png)
![tim 20180209165521](https://user-images.githubusercontent.com/25315125/36019388-161d0ad4-0dba-11e8-8b05-9f8db462bed1.png)

Maybe it's electron's issue, but I found it seems fixed in [#6344](https://github.com/electron/electron/issues/6344). 

So how to turn on subpixel anti-aliasing on Boostnote?

**Comment by csadam** [comment]
To solve the problem,
**add** the `  backgroundColor: '#fff',`  parameter 
to the `const mainWindow = new BrowserWindow({` declaration
in the _%APPDATA%\..\Local\boost\app-0.11.12\resources\app\lib\main-window.js_ file.

for example:
```javascript
const mainWindow = new BrowserWindow({
  backgroundColor: '#fff',  //<-- add this
  x: windowSize.x,
  y: windowSize.y,
  width: windowSize.width,
  height: windowSize.height,
  useContentSize: true,
  minWidth: 500,
  minHeight: 320,  
  autoHideMenuBar: showMenu,
  webPreferences: {
    zoomFactor: 1.0,
    enableBlinkFeatures: 'OverlayScrollbars'
  },
  icon: path.resolve(__dirname, '../resources/app.png')
})
```

Reference: [link](https://github.com/electron/electron/issues/6344#issuecomment-420371918)
