### ISSUE TITLE
[Feature Request] Edit on double-click in stead of single-click

### ISSUE THREAD

**Issue by Redsandro** [BoostIO/Boostnote#1523]
I find myself constantly toggling the edit mode (preview -> editor) when I don't want to.

A solution would be to (have the option to) only switch to the editor when double-clicking on the preview, in stead of single-clicking.

**Comment by kazup01** [comment]
Hi @Redsandro , thank you for your suggestion. Btw you can use the option that right click in Preferences.

<img width="1150" alt="screen shot 0030-02-10 at 4 16 53 pm" src="https://user-images.githubusercontent.com/8602615/36059568-f1ef3d8e-0e7d-11e8-92da-6fc2b0ab386e.png">
