### ISSUE TITLE
I want to remove unlink.

### ISSUE THREAD

**Issue by sosukesuzuki** [BoostIO/Boostnote#1529]
Boostnote has a function which unlink a storage.
It is so buggy. Often, I listen report of bug that all of the storages have gone unlinked by Boostnote.
I think that function is unnecessary. 
Because, There is no problem if Boostnote can detect deleted folder which was used for Boostnote and unlink the storage automatically.
(However, I don't know whether that bug was caused by the function.:bow:)

**Comment by nlopin** [comment]
Do you mean, that if user wants to detach a storage, they need to remove (or move) storage folder from the filesystem?

**Comment by sosukesuzuki** [comment]
Yes, I want such.

**Comment by nlopin** [comment]
Sorry, but It doesn't sound good. Why user should bother deleting anything manually?

**Comment by sosukesuzuki** [comment]
Because, a folder which was used by Boostnote cannot be basically used on other software.
If user unlink storage in Boostnote, actually, that folder is left there. To delete it perfectly, after all, we must delete it manually.
So, I think function which unlink a storage on Boostnote is unnecessary.

**Comment by nlopin** [comment]
I am still not getting the idea. Can you provide an example of other software sharing with Boostnote storage folder? For me It looks like very rare scenario of usage and most users don't mix their storages with other apps.

**Comment by Flexo013** [comment]
I'm closing this for now as it is unclear what the reporter's motivations are for this 'feature request'.

@sosukesuzuki Feel free to reopen the issue with more information on why you would like to see this feature remove.
