### ISSUE TITLE
Pasting plain text code triggers KaTeX and html

### ISSUE THREAD

**Issue by Redsandro** [BoostIO/Boostnote#1532]
Sometimes you just have a text which mentions non-formatted code, like in old-school books where text is just text. You might want to keep it that way because of reasons.

Now different parsers are triggered on this.

Simplified example: 
#1502 
![image](https://user-images.githubusercontent.com/1702193/36063316-9e475704-0e7b-11e8-82d6-d862ba4ba496.png)

You need to manually look through the text and escape everything that triggers a parser. 

Although this is unexpected behavior, it makes sense from a technical point of view. Human expectations versus computational logic. Therefor this is not a bug but I'm inviting discussion to figure out if something can or should be done about it.

For example:

* Options for pasting text:
  * Do nothing
  * Auto-escape
  * Ask (when parsable text is detected)
* Options for KaTeX:
  * On parse error, return original text in stead of error message.

Simplified example code:

> # testnote
>
> ###### Two jquery actions multiline
> 
> $('a').each(() => {
>	var h=$(this)
> })
>
> ###### Two jquery actions in one line
>
> if ((/\.(gif|jpg|jpeg|png)$/i).test(h)) {$('body').append('\<img src="'+h+'">')}
>
> ###### Regex ending in $
>
> if ((/\.keyword$/i).test(h))$('body').emit(e);

**Comment by islanddog** [comment]
I would simply just bind the text into ```jscript tags before switching to the normal view or utilizing the snippet note function for these notes. If they are just meant to be 'old school books with text' this could handle it fine. If not I think this leads back to your other question and the official support of the Jquery library.

**Comment by Paalon** [comment]
You can edit KaTeX delimiters to others (like $ -> $$, $$ -> $$$) in preferences (need restart). It will prevent the behavior. This is not useful for those who don't use LaTeX but some people would use delimiters (inline for $ and display for $$). If we could prevent this ambiguous parsing behavior, it would be the best.
