### ISSUE TITLE
Is there a way to like to a snippet (note)?

### ISSUE THREAD

**Issue by aurelkurtula** [BoostIO/Boostnote#1534]
I know that we can link to different notes, but is there a way to link to a specific snipet

**Comment by ItsPugle** [comment]
I was [literally about to suggest this](https://user-images.githubusercontent.com/22669894/36081952-80ad3170-0ff0-11e8-83c6-d666d41885b9.png). I'm wholeheartedly +1 for this!

**Comment by islanddog** [comment]
Unless they change how snippets function, no. It currently pulls the ID attached to the .CSON file. As snippet notes are all bundled in a singular file you would need to be able to pull the URL via the name.

**Comment by Flexo013** [comment]
I'm closing this issue as the question was answered.

If you would like this to become a feature then feel free to create a separate feature request for that. Ideally also mentioning this issue number #1534
