### ISSUE TITLE
[Feature Request] Add a progress bar to Markdown snippets with checklist items

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1537]
If you use a normal Markdown Note, you have a little progress bar at the top of the note that progresses based off the checklist items. It'd be quite handy if Markdown snippet notes have this same functionality 😄

**Comment by islanddog** [comment]
I think the current premise is Markdown Notes are meant for Checklists and intensive documentation well Snippet Notes are just meant for multiple snippets with simple syntax formatting. I think giving Markdown Notes the ability to have tabs would help a lot of these requests.

**Comment by ItsPugle** [comment]
Maybe, Maybe not. I don't know!

I think that it might just be best to give Markdown Snippet notes everything that normal Markdown notes have.

**Comment by takacsot** [comment]
I think this could be closed as it is already implemented.

**Comment by modmod24** [comment]
yes, it is already implemented
