### ISSUE TITLE
Cannot close application; scroll bar and icon bugs in Windows

### ISSUE THREAD

**Issue by aurenen** [BoostIO/Boostnote#154]
I haven't tested this on my Mac, but on Windows, after the update to v0.7.2, I can no longer close Boostnote. It does not appear in the task tray, and the only way to close is to force end process.

Additionally, the scroll bar seems to be stuck over the menu. 
![scroll bar](http://i.imgur.com/rp6yFsi.png)

For the past 2-3 versions, the application icon has disappeared on me. 
![missing icon](http://i.imgur.com/RRtIhdl.png).

**Comment by Rokt33r** [comment]
You can quit the app by `Menu > Boostnote > Quit Boostnote`.

About the tray icon, could you tell me it is still hidden after restarting the app?
If it is, please tell me any hint how to reproduce the problem.

> Additionally, the scroll bar seems to be stuck over the menu. 

It will be fixed the update of the next week!

> For the past 2-3 versions, the application icon has disappeared on me. 

Okay, I'm currently investigating it. I'll tell you after I find something.

**Comment by aurenen** [comment]
Thank you, after restarting, the tray icon appears. I know in previous versions, when you close with the window "x" button, Boostnote is no longer on the task bar, but can be relaunched with the task tray icon, I just want to check that minimizing is the new behavior for the "x" button.

For the missing icon:
![missing icon](http://i.imgur.com/N437klH.png)
It looks like it might be an issue with a cached older version of the app? I double checked and it appears Boostnote was installed in AppData?

**Comment by Rokt33r** [comment]
Yes, It is a new behavior, just like Skype, to restore app much faster.
I'll add a jump list task to close the app from context menu of status bar.

> It looks like it might be an issue with a cached older version of the app?
Yes, It is a behavior of https://github.com/Squirrel/Squirrel.Windows
Thanks for reporting. I'll try to fix it.

**Comment by citycide** [comment]
Being able to close to tray would be nice to avoid having the app stick in the taskbar, ie. setting the window to hide on close or minimize but stay in the tray.

**Comment by flyball** [comment]
Closing an application via the "X" in the top right corner is such a default behavior for so many programs, what are your design thoughts on making that just minimize Boostnote? I came here thinking it was a bug, and still kind of think it is.
