### ISSUE TITLE
Mark notes by storage/folder color in "All notes" and "Notes in storage" views 

### ISSUE THREAD

**Issue by nlopin** [BoostIO/Boostnote#1545]
Now we set colors to folders, which affects only the title of preview. 
![image](https://user-images.githubusercontent.com/1469636/36226964-85caba3c-11e0-11e8-9a37-77125f524bf5.png)

But it's much more important to understand the folder of note in the storage view and the storage of note in "All notes" view. 

It would be great if we mark notes with corresponding color. We can color title icon or add thin colored vertical line at the beginning of the block. On screenshot below I colored title icons of the notelist: 
![image](https://user-images.githubusercontent.com/1469636/36227334-d6f04110-11e1-11e8-97e7-81ba3f5099f6.png)

**Comment by nlopin** [comment]
We need to find more elegant solution. The one with icons is too aggressive

**Comment by pfftdammitchris** [comment]
I'm working on this now.

**Comment by pfftdammitchris** [comment]
Sorry I think I misunderstood the post a little bit, but I think I know what you are trying to tell now.
I have a solution and idea for this, i'll proceed it to #1556 if you want me to. I think coloring the icon is a better elegant approach in the storage view.

Coloring the title of the note could be good too but I think if we do that then the icon next to it becomes redundant. What do you think?

**Comment by Flexo013** [comment]
It the latest version of Boostnote the notes in the sidebar have their folder listed like so:
![image](https://user-images.githubusercontent.com/4507015/62027143-3b29e180-b1dd-11e9-8442-185aa6d9fa72.png)
