### ISSUE TITLE
[Bug] Horrendous Apostrophe

### ISSUE THREAD

**Issue by Kyle-Helmick** [BoostIO/Boostnote#1546]
![image](https://user-images.githubusercontent.com/18430725/36235683-50743c0e-11af-11e8-8413-42f905e5026e.png)

Hey all, I was just taking notes in my class and noticed that spacing around apostrophes goes AWOL...

**Comment by pfftdammitchris** [comment]
I cant reproduce this issue

**Comment by oliver-daniel** [comment]
Are you in Canada and on Windows, by any chance? Sometimes it's possible to accidentally enter Canadian French mode, which can causes apostrophes to look weird.

**Comment by thejayhaykid** [comment]
I am in the U.S. on Windows 10 and version 0.11.13 and have this same issue after every apostrophe.

**Comment by AWolf81** [comment]
@thejayhaykid I'm using version 0.11.15 on Windows 10 and I'm not getting that issue - can you please check it with that version?

I've used the following text to test it:
```
## If you can't
## If you can/'t
## If you cant\'t
```

If it still happens can you please send me a screenshot of your settings dialog tab interface to see if you're using a different setting.
Also a screenshot of the rendered preview with dev tools would help - my output to the above snippet looks like this:
![image](https://user-images.githubusercontent.com/3046542/57044492-01435080-6c6b-11e9-97aa-a8d2a9220a21.png)

How can I change the background color of the preview window to a different theme? It's dark in the screenshot from @Kyle-Helmick - not sure if this is related to the issue but I'd like to check. Is this only possible with custom css for the preview? Please share your custom css setting if you're using it.

**Comment by thejayhaykid** [comment]
I just updated to 0.11.15 and I am still having the same issue.
![image](https://user-images.githubusercontent.com/9452325/57074932-45f2da00-6cb3-11e9-802a-2d35edc1bb88.png)

---

You can change the colors in Preferences > Interface but I tried a couple and it is still the same thing for me.

**Comment by AWolf81** [comment]
OK, can you please send me the text you used (enclosed in a tripple backticks \`\`\` code block so I can copy & paste your text)? Just to double check that I'm using the same characters.

A screenshot of the rendered html would be also great so I can see if there is something in the rendered html. (Dev. tools can be opened with Ctrl+shift+i and Ctrl+Shit+C to select the preview text with the weird space.)

**Comment by arcturus140** [comment]
please also mention Preview Font Family from the Interface section of your Boostnote preferences.

**Comment by thejayhaykid** [comment]
The preview font family field is blank, it always has been for me so I'm assuming that the default font is selected.

![image](https://user-images.githubusercontent.com/9452325/57138293-49a06280-6d80-11e9-805f-a915cd81373f.png)

---

#### Text used:
```
# Can't
# Can\'t
# Can/'t

Can't
Can\'t
Can/'t
```

![image](https://user-images.githubusercontent.com/9452325/57138222-21186880-6d80-11e9-96c9-ad6d5902b821.png)

**Comment by Flexo013** [comment]
Feel free to comment here or reopen this issue if this is still occurring with the latest version of Boostnote.
