### ISSUE TITLE
Nextcloud- or WebDAV-Syncing?

### ISSUE THREAD

**Issue by jcgerhard** [BoostIO/Boostnote#1547]
Hey guys! Boostnote is a really handy tool that I line to use a lot BUT: are there any plans to integrate Nextcloud or WebDaV syncing in the near future? Would be a killer feature!

**Comment by Rokt33r** [comment]
I would like to learn the new thing. But, I've never heard about it.

Could you describe more about it?

**Comment by SiSchae** [comment]
I sync my notes with my Nextcloud server. My storage points to a directory that synchronizes via nextcloudclient on my desktop and laptop.

**Comment by Trollwut** [comment]
@SiSchae does this also work with mobile, especially Android?

**Comment by SiSchae** [comment]
@Trollwut no unfortunately it doesn't work on android. Maybe if we can choose the storage location on the phone.

**Comment by Trollwut** [comment]
Then I still pledge for WebDAV (or Nextcloud) support :p

**Comment by Rokt33r** [comment]
Hmm, there are still no answer. I'll investigate this by myself.

**Comment by andreasjacobsen93** [comment]
Any news about Nextcloud support?

**Comment by benyanke** [comment]
It's a hack to be sure, but on Android, you can use an app called 'FolderSync' to sync a local phone directory with a remote NC or webdav instance.

**Comment by janLo** [comment]
There is already an issue for the mobile version: https://github.com/BoostIO/boostnote-mobile/issues/93

**Comment by Flexo013** [comment]
Let's continue this discussion in #1250.
