### ISSUE TITLE
Failed to extract installer on Windows 10 Pro

### ISSUE THREAD

**Issue by lepinekong** [BoostIO/Boostnote#1552]
Could not install, generated log below

[SquirrelSetup.log](https://github.com/BoostIO/Boostnote/files/1734293/SquirrelSetup.log)

**Comment by pfftdammitchris** [comment]
Read https://github.com/Squirrel/Squirrel.Windows/issues/698

Maybe you are being blocked from some write access issue?

* CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\moi\AppData\Local\atom\packages\.betaId
* CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\moi\AppData\Local\atom\packages\RELEASES'
* ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
* Program: About to install to: C:\Users\moi\AppData\Local\brave
* CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\moi\AppData\Local\brave\packages\.betaId

For example from here

* CheckForUpdateImpl: Reading RELEASES file from C:\Users\moi\AppData\Local\SquirrelTemp
* CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
* 2017-12-13 23:35:57> ApplyReleasesImpl: Writing files to app directory: C:\Users\moi\AppData\Local\brave\app-0.19.105
* 2017-12-13 23:35:57> LogHost: Rigging execution stub for lib/net45/Brave_ExecutionStub.exe to C:\Users\moi\AppData\Local\brave\Brave.exe
* 2017-12-13 23:35:58> LogHost: Rigging execution stub for lib/net45/resources/BraveDefaults_ExecutionStub.exe to C:\Users\moi\AppData\Local\brave\app-0.19.105\BraveDefaults.exe
* 2017-12-13 23:36:05> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\moi\AppData\Local\brave\app-0.19.105\Brave.exe]

Seems like your installation is being intercepted by some windows 10 protection feature

**Comment by Rokt33r** [comment]
@lepinekong Could you try again after deleting `C:\Users\moi\AppData\Local\boost` directory and any files in it?

**Comment by lepinekong** [comment]
Sorry I forgot : I deleted and reinstalled again it works 👍

**Comment by Rokt33r** [comment]
@lepinekong Glad to hear that! 😂 😂
