### ISSUE TITLE
[Feature Request] 'Empty trash' button when right clicking the trash can

### ISSUE THREAD

**Issue by patrick-iv** [BoostIO/Boostnote#1555]
Did a quick scan at the Issues page but couldn't find this (if there already is a feature request for this, please close this and link the other).

Like the title say, I'd like a "Delete all" or "Empty trash" button when right clicking the Trash tab. I know that it's possible to select all items in the category and right click, delete them but by default I always try to right click the Trash tab first (like you do when emptying the trash can in Windows).

**Comment by pfftdammitchris** [comment]
If no one works on this i'd like to implement this one soon

**Comment by Rokt33r** [comment]
Fixed by #1558.
