### ISSUE TITLE
Split and refactor SnippetNoteDetail component 

### ISSUE THREAD

**Issue by nlopin** [BoostIO/Boostnote#1557]
@kazup01 can you assign this on me?

SnippetNoteDetail.js is almost 800 LoC and has a lot of sophisticated logic inside. We need to split it in two parts:
* tab bar and its' logic
* snippet view

**Comment by Rokt33r** [comment]
Yea, we should do it definitely.
The codebase is too old because I've just started using React and Node.js at that time.

**Comment by nlopin** [comment]
@Rokt33r I can't start with this until PR #1566 isn't merged. Can you look at it?

**Comment by Rokt33r** [comment]
I'll do it now. Sorry for making you wait.

**Comment by Flexo013** [comment]
@nlopin Is this still an issue that is waiting for somebody to submit a PR?

**Comment by nlopin** [comment]
I don't think it is valid anymore
