### ISSUE TITLE
Snippet NoteでMarkdownのプレビューが表示できない

### ISSUE THREAD

**Issue by muro-bb** [BoostIO/Boostnote#156]
v0.7.1からSnippet NoteにMarkdownを追加してもプレビューを表示できません。
過去のデータはプレビュー表示できたため、csonファイルを比較したところ`mode`の値が`Markdown`となっていました( __M__ が大文字)
以前のファイルは`mode: "markdown"`となっており、テキストエディターで直接小文字に変更して `View > Reload` を行ったところ、プレビューが可能となりました。

#### 新旧csonファイルの比較

```diff
type: "SNIPPET_NOTE
folder: "..."
title: "..."
description: "..."
snippets: [
    {
        name: "..."
-        mode: "markdown"
+        mode: "Markdown"
        content: ```
...
```

---

OS: Windows 10 Pro 1067
Boostnote: 0.7.2 
で確認しました。

---

宜しくお願い致します。

**Comment by Rokt33r** [comment]
報告ありがとうございます！来週に直したものが反映されると思います。

**Comment by muro-bb** [comment]
ありがとうございます。
修正お待ちしております。

**Comment by Rokt33r** [comment]
すみません、くだらないバグでした。 https://github.com/BoostIO/Boostnote/commit/b906db3b24648f7c20fa7a863c3c11b6dddada48

反映されるのは今週末頃になると思います！
