### ISSUE TITLE
Boostlog?

### ISSUE THREAD

**Issue by ItsPugle** [BoostIO/Boostnote#1560]
I'm sure that this isn't the right place to report issues for Boostlog, but on [the homepage of Boostlog](https://boostlog.io/), the slogan/motto says "A Blogging Platform for Programmer." This should instead  say "A Blogging Platform for Programmers." 😄 

![screenshot 2018-02-20 at 2 01 05 pm](https://user-images.githubusercontent.com/22669894/36406996-b0349120-1646-11e8-9255-33dc7919685b.png)

**Comment by Rokt33r** [comment]
Definitely!! Thanks for reporting. 😂  I'm gonna fix it now!
Boostlog is our new prototype app. It will be open-sourced too somewhen. :)
