### ISSUE TITLE
[Bug] Weird CSS Issue

### ISSUE THREAD

**Issue by oliver-daniel** [BoostIO/Boostnote#1564]
![](https://media.giphy.com/media/m8iZfZExCN1IN7hiRd/giphy.gif)

When resizing the window, the toggle button does not seem to stop like the other top-bar buttons do.

I did not include a devtools screenshot because the devtools appear completely normal during resizing.

**Comment by pfftdammitchris** [comment]
Found the problem. WIl submit a pull request of a solution in a bit

**Comment by pfftdammitchris** [comment]
I found that adding an overflow: hidden would help the overlapping of the note list part.

However there is still left with the problem of the toggle mode button overlapping the "folder select" button in the markdown detail view as also shown in the screenshot, as well as being a mindless responsive element.

It seems that the positioning of the togglemode button being an absolute position is breaking the flex responsive flex container mechanisms if I am understanding correctly

The answer might be found at: https://www.w3.org/TR/css-flexbox-1/#abspos-items

Should the top bar be rewritten?

**Comment by pfftdammitchris** [comment]
Actually I figured a solution. Will submit a pull request
