### ISSUE TITLE
Questions for this project

### ISSUE THREAD

**Issue by pfftdammitchris** [BoostIO/Boostnote#1565]
Hello everyone,

I am a brand new open source contributor in general and this is my first serious open source project that I am growing my career in and to put on my resumes, as I am actively looking for a developer job in my area.  I have submitted my first couple pull requests here and there the past week and gradually planning to submit larger and more important ones (finding solutions to bugs for example) but I feel a little worried about my collaborations. Here are my main concerns:

1. As I was self-volunteering to contribute to this project I stumbled upon #1557 and realized that there is an "assignment" to contributers going on around here.  Would it be a lot more respectful and recommended for me to ask a Boostnote maintainer to _assign me_ to an issue/feature request? Lately I've sort of been barging into issues and trying to take over the tasks of solving/implementing them myself. I'm not getting any replies on my pull request and I tend to overthink things so I am worrying that I am missing some steps before contributing.
2. I noticed that React is v15.5.4. Why is it not at least v16? If there were any problems in the past that is preventing us from upgrading, how can I help make the change to get us updated? As this is my first serious week of contributions and currently Boostnote is my only open source I am contributing to at the moment, I would like to take advantage of my time at the moment to help the project proceed to latest updates
3. I noticed the files have mixed component rendering callback functions (ex: some use this.someMethod.bind(this) and some use {() => this.someMethod(someParameter)} in the render blocks. Should we submit pull requests to fix these inconsistencies? Do we have a code guideline to only prefer inline functions {() => this.someMethod()} or are contributors the ones to decide this?

**Comment by pfftdammitchris** [comment]
Great,  thanks for the answers!

**Comment by Rokt33r** [comment]
@pfftdammitchris I'm appreciating your contributions too. Let me know whenever you have something to ask! 😄 😄 😄
