### ISSUE TITLE
Can't see title in the title bar or the site icon

### ISSUE THREAD

**Issue by skywalker212** [BoostIO/Boostnote#1568]
![screenshot 4](https://user-images.githubusercontent.com/16351685/36492131-62f6a2b0-1752-11e8-95b7-21a27d552a3c.png)

**Comment by Rokt33r** [comment]
Haha..! our page has been completely renewed. Thanks for your reporting!

If you want give more feedback to us, visit here!
https://github.com/BoostIO/Boostlog-feedback/issues
