### ISSUE TITLE
[Feature Request] Move folder order by dragging

### ISSUE THREAD

**Issue by wonderlives** [BoostIO/Boostnote#1569]
![image](https://user-images.githubusercontent.com/25517207/36510176-3019f602-1730-11e8-9352-7a452039bf01.png)
Is there anyway to move the folder order by dragging?

**Comment by pfftdammitchris** [comment]
Probably not but I would like to implement this and submit a pull request--it is similar to a feature I am working on in my personal project and Boostnote uses the same packages so I'd like to figure the solution for Boostnote and hopefully it will get integrated!

**Comment by ghazal** [comment]
+1
