### ISSUE TITLE
[Feature Request] Publishing note to wordpress (and other blog systems)

### ISSUE THREAD

**Issue by lijinglue** [BoostIO/Boostnote#1571]
It would be great if BoostNote can publish NoteItem to wordpress. Is anyone working on it or is it in the roadmap?

**Comment by Memphizzz** [comment]
It would be awesome to have Ghost blogs supported too.

**Comment by rhbvkleef** [comment]
I would be immensely happy with the option of committing notes to Git (ofc. with a predefined repository and path). It would also be great fun if you could have different blog configurations per storage location.

**Comment by rhbvkleef** [comment]
Or even better: publish HTML documents to a path on the filesystem.
