### ISSUE TITLE
[Feature Request]  HotKey for Switch back to Application like Tilda terminal

### ISSUE THREAD

**Issue by penolove** [BoostIO/Boostnote#1573]
for Tilda Terminal, that can quickly switch to termainl with f12, when I open lots of windows.
if it's possible add to boostnote or there are some other solutions?

**Comment by Rokt33r** [comment]
We've already had! 
<img width="1192" alt="screen shot 2018-02-25 at 4 32 26 pm" src="https://user-images.githubusercontent.com/5865853/36639152-802b58e0-1a49-11e8-924d-d0f77f788015.png">
