### ISSUE TITLE
Pictures can't move automatically when changing the folder a note belongs to

### ISSUE THREAD

**Issue by kikyoulin** [BoostIO/Boostnote#1578]
This situation only occurs at moving a note to a folder that is in a different Storage Location.

![problem](https://user-images.githubusercontent.com/30592039/36626181-d83ce72e-1968-11e8-8121-017e8edf9d99.png)

If the two folders are in the same storage location, it shows images normally. If the two folders are not in the same storage location, I need to move these corresponding pictures manually.

**Comment by Flexo013** [comment]
This issue has been fixed. Thanks for reporting it!
