### ISSUE TITLE
New Scroll Sync feature not working properly

### ISSUE THREAD

**Issue by gramster** [BoostIO/Boostnote#1586]
I have the latest release 0.10.0 with the new scroll sync feature (yeah!)

However, it isn't working properly. If I scroll my preview then the raw markdown does sync, but if I scroll the markdown the preview does not sync.

**Comment by Redsandro** [comment]
Looks like it was broken when another feature was merged in. @Rokt33r could you merge https://github.com/BoostIO/Boostnote/pull/1591 for a quick fix?

**Comment by Rokt33r** [comment]
Absolutely. 😄

**Comment by Redsandro** [comment]
@gramster The fix is slated for 0.11.0. Sorry for that!

**Comment by Rokt33r** [comment]
I'm going to publish v0.11.0 on this weekend. Sorry for making you wait. 😢

**Comment by gramster** [comment]
Thanks for the quick fix!
