### ISSUE TITLE
No longer shows check list progress bar

### ISSUE THREAD

**Issue by tewe** [BoostIO/Boostnote#1589]
In v0.10.0 I can no longer see in the note list how many `- [ ]` I checked off. Downgrading to v0.9.0 helps.

**Comment by RomanKlopsch** [comment]
Which operating system are you using?
And which way did you install the new version?
I can't reproduce the bug on Ubuntu / 17.10 (installed due the deb package)

**Comment by tewe** [comment]
Sorry, macOS 10.13.3, both auto-update and the DMG.

**Comment by pfftdammitchris** [comment]
Working on windows for me. Seems like a macOS issue. Hmm

**Comment by Rokt33r** [comment]
Hmm... that's weird. It works fine for me too. I'm using macOS 10.13.3 too.

**Comment by tewe** [comment]
It does not work fine for you. Here is how 0.9.0 looks, not the progress bar:

<img width="1401" alt="boostnote" src="https://user-images.githubusercontent.com/645412/36740168-ef79deb2-1be1-11e8-8117-f835b3fedab7.png">

**Comment by RomanKlopsch** [comment]
Well, seems like we misunderstood you.
I have to correct myself: It does **not** work for me

**Comment by RomanKlopsch** [comment]
I managed to get the progress-bar back by changing the display type of
>.NoteItem__item-bottom___browser-components-

from *flex* to *block*.
I don't know, whether this tweak breaks something else but it seems to solve the issue.

**Comment by Rokt33r** [comment]
@RomanKlopsch If you don't mind, you can submit a PR with your solution! So, we can review and merge it. How about it? 😄

**Comment by RomanKlopsch** [comment]
I am looking forward to fix this in the afternoon

**Comment by Rokt33r** [comment]
I'll gladly wait for it! ❤️ ❤️

**Comment by RomanKlopsch** [comment]
#1614 here we go...

**Comment by yosmoc** [comment]
@Rokt33r please close this issue.
