### ISSUE TITLE
Allow custom plantuml server

### ISSUE THREAD

**Issue by chbndrhnns** [BoostIO/Boostnote#1592]
For a corporate environment, it is essential not to leak information to the outside. Thus, I would like to suggest making the rendering server for the PlantUML diagrams configurable.

According to the developers, this should be possible like this:

```
function customSrcGenerator (umlCode) { 
    return `https://your.server/plant-uml/${yourEncodeFunction(umlCode)}`; 
}

var md = require('markdown-it')()
    .use(require('markdown-it-plantuml'), { generateSource: customSrcGenerator });
```

[markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml/issues/5#issuecomment-368255217)

**Comment by yosmoc** [comment]
![image](https://user-images.githubusercontent.com/9694/46515496-74671e80-c864-11e8-87c3-d7ecec93f129.png)

You can specify the custom server in preference. 
Closed.
