### ISSUE TITLE
Add automatic screen scrolling support

### ISSUE THREAD

**Issue by blessingsi** [BoostIO/Boostnote#1599]
I would like to have smarter screen scrolling when I'm editing. That is to say, at minimum, X lines below.
<img width="1440" alt="2018-02-27 4 14 59" src="https://user-images.githubusercontent.com/16718759/36717588-9f5cbcfe-1bd9-11e8-9d0e-83b2cc12eaa5.png">

**Comment by RomanKlopsch** [comment]
I agree this would be a nice feature.
We should keep the cursor at the beginning of the last third of the editor to match the golden cut.

**Comment by jannik-kramer** [comment]
The is no offset but already a "Allow editor to scroll past the last line" in the settings. This might help for now.

**Comment by blessingsi** [comment]
Thank @jannik-kramer so much.That just what I need.
