### ISSUE TITLE
System Requirement

### ISSUE THREAD

**Issue by ishu3101** [BoostIO/Boostnote#16]
What are the System Requirement for using Boostnote?

**Comment by Rokt33r** [comment]
http://electron.atom.io/docs/v0.37.5/tutorial/supported-platforms/

**Comment by ishu3101** [comment]
You mean OS X 10.11.*

**Comment by Rokt33r** [comment]
@ishu3101 You're right. 👍

**Comment by Rokt33r** [comment]
Closed it. I added it also to readme.md!
