### ISSUE TITLE
Align image in center and provide caption

### ISSUE THREAD

**Issue by rahulpathakgit** [BoostIO/Boostnote#1600]
Hi,

How can i align an image in center and also provide a caption aligned with the image.
I am using the latest 0.10 image

Rahul

**Comment by Rokt33r** [comment]
It is not a spec of Markdown. But, you can still use HTML.

caption:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

align center:
https://developer.mozilla.org/ko/docs/Web/HTML/Element/center

**Comment by rahulpathakgit** [comment]
I referred the links and used in boostnote. Image is still not in the middle unlike caption. Is this the normal behavior of align="middle" in img tag?

![screenshot from 2018-02-27 18-04-16](https://user-images.githubusercontent.com/10892516/36729002-bba8d456-1be8-11e8-9301-ee3ad8788cac.png)

**Comment by rahulpathakgit** [comment]
I got it. I google it and found <center>. Its working like I need.

**Comment by kyet** [comment]
> I referred the links and used in boostnote. Image is still not in the middle unlike caption. Is this the normal behavior of align="middle" in img tag?
> 
> ![screenshot from 2018-02-27 18-04-16](https://user-images.githubusercontent.com/10892516/36729002-bba8d456-1be8-11e8-9301-ee3ad8788cac.png)

`<figcaption style="text-align:center">text</figcaption>` is working.

**Comment by zhongsheng-chen** [comment]
I have an alternative. 
```
<p align="center">
 <img src="src/assets/training_performance.jpg" alt="train_perf_fig" height="640" width="960"/>
    <br>
    <em>Figure 1 training process of NN.</em>
</p>

```
More details, please see [here](https://github.com/zhongsheng-chen/Back-Propagation-Neural-Network).
