### ISSUE TITLE
Travis CI uses old version of node & npm

### ISSUE THREAD

**Issue by rayou** [BoostIO/Boostnote#1602]
```bash
$ node --version
v6.13.0
$ npm --version
3.10.10
$ nvm --version
0.33.8
$ yarn --version
1.3.2
```

Noticed that Travis is using node 6 and npm 3.10.10, which is insufficient for build requirement.

Should be a easy fix by updating node version in [.travis.yml](https://github.com/BoostIO/Boostnote/blob/master/.travis.yml#L3)

**Comment by serima** [comment]
A pull request to solve this issue have already been merged, so is it better to close?
