### ISSUE TITLE
Automatic lists no longer work

### ISSUE THREAD

**Issue by ccurtin** [BoostIO/Boostnote#1605]
I'm on Windows 8 updated to the latest version a day or two ago and automatic lists no longer work.
When I type `- list item one` and hit return it used to automatically begin a new list item, like:
```
- list item one
- 
```

But now it doesn't create that next list item when pressing enter. Was this done on purpose?

**Comment by Rokt33r** [comment]
Duplicated!
https://github.com/BoostIO/Boostnote/issues/1588
