### ISSUE TITLE
Google Drive file delete issuess

### ISSUE THREAD

**Issue by vkjha542** [BoostIO/Boostnote#1606]
Hello Github Team,

This my first time to write my query on GitHub.
I have small issues on google drive, first I explain the scenario.
1. I am creating google drive folder and share publically, whose know the link, they have accessed and edit anything.
2. User login to drive using own google id and the file will upload/download in the folder.
3. I need to delete file also.

but I it shows the message about "Not has enough Permission to delete this file".

I need help to resolved this issues.

**Comment by Rokt33r** [comment]
I couldn't understand what the problem is. Why do you need delete the file?

**Comment by vkjha542** [comment]
It is a feature of our application.

I have delete file when documents process is complete then need to delete file from google drive.

If not delete then file automatically sync with phone local folder.

Thanks
Vivek Jha

**Comment by Rokt33r** [comment]
What's the meaning of `documents process is complete`?

**Comment by vkjha542** [comment]
Example: I have upload lot of file in Google drive folder and share folder link for different people's and people need to download images.

After I need to delete images on Google drive.

Because user have already the images I his phone and the doesn't need to download same image again.

**Comment by Rokt33r** [comment]
Sounds like it is not a problem of Boostnote. 🤔 🤔

**Comment by vkjha542** [comment]
Yes,
I need solution to delete Google drive file on public url.

Or move file one folder to another folder.
