### ISSUE TITLE
Notes mysteriously disappear after updates + closing Boostnote, but storage still linked

### ISSUE THREAD

**Issue by anhhuyalex** [BoostIO/Boostnote#1610]
Hello, so I've experienced an issue throughout boostnote's many updates. Some notes mysteriously disappear from boostnote even though I do nothing. Even though I followed the instructions and ensured that the storage is linked via Preferences -> Storages -> Add Storage.

<img width="1280" alt="screen shot 2018-02-28 at 3 51 30 pm" src="https://user-images.githubusercontent.com/17817335/36782539-46df0f3e-1c9f-11e8-8532-6ca744dbc8ff.png">

So I have my note Google's PageRank as you see here
<img width="1280" alt="screen shot 2018-02-28 at 3 48 05 pm" src="https://user-images.githubusercontent.com/17817335/36782573-5d070a28-1c9f-11e8-99b5-1cbf3dfb19a0.png">

After I close Boostnote and re-open you see that the note has disappeared. 
<img width="1280" alt="screen shot 2018-02-28 at 3 52 55 pm" src="https://user-images.githubusercontent.com/17817335/36782631-86c16976-1c9f-11e8-988c-38937cad438d.png">

The .cson file still remains within ~/Users/alng/Boostnote/notes so it's very frustrating because I have to copy all of the notes onto a new note in Boostnote and there's no easy way to import an existing .cson note into Boostnote.

I'd greatly appreciate advice. Thank you.

**Comment by Rokt33r** [comment]
I assume there is some error. Could you share the error message? You can see it from devtool.(You can open it with `Cmd + Alt + I`.

**Comment by anhhuyalex** [comment]
Hello,

Is this what you'd like to see? It seems only a few .png resources are missing and everything else looks OK. 
<img width="550" alt="screen shot 2018-02-28 at 4 03 48 pm" src="https://user-images.githubusercontent.com/17817335/36783113-12daf282-1ca1-11e8-9f32-b47e205cf8b7.png">

**Comment by Rokt33r** [comment]
Could you click the error with `7d78~~.cson` file and take a screenshot again?

**Comment by anhhuyalex** [comment]
Here you go.
<img width="555" alt="screen shot 2018-02-28 at 5 31 59 pm" src="https://user-images.githubusercontent.com/17817335/36786699-5c03171c-1cad-11e8-8423-96789a1aea36.png">

**Comment by Rokt33r** [comment]
It seems your note is including weird character which our cson parser can not parse. If you don't mind, could you send me the file so I can fix? rokt33r@boostio.co

**Comment by anhhuyalex** [comment]
Actually 7d78---.cson is a blank file as you can see. 
<img width="797" alt="screen shot 2018-02-28 at 6 03 24 pm" src="https://user-images.githubusercontent.com/17817335/36787968-28fce6a4-1cb2-11e8-9179-26ece3ba547f.png">

**Comment by Rokt33r** [comment]
Hmm.. we need more clue. Which version did you use before updating? And, do you know what kind of notes disappeared?

**Comment by anhhuyalex** [comment]
I used Boostnote 0.9.1 before updating to 0.10.0 but this issue has happened before, when updating from 0.8 to 0.9 some notes also disappeared. It seems that the most recent notes disappeared and the less recent ones stayed. Or it's possible they disappeared and I don't notice them before I don't remember, but all the less recent ones look like they're still there.

**Comment by Rokt33r** [comment]
And, could you delete the empty file? It might the error causes to stop loading all notes.

**Comment by Rokt33r** [comment]
I assume that is the problem. Let me know if you can not still find the notes.

**Comment by anhhuyalex** [comment]
Wow. All of my notes came back and multiple copies of them too since I made so many copies. Thank you!

**Comment by Rokt33r** [comment]
Glad to hear that!! 😄
