### ISSUE TITLE
Export folder to md - doesn't export all notes

### ISSUE THREAD

**Issue by clouddiver** [BoostIO/Boostnote#1613]
selecting the folder on the left, right-click, Export Folder->export as md, then select a folder and export. Boostnote exports only 5 out of 27 notes. In another folder it is only 1 out of 5. 
The same happens by exporting as text. 
Can someone please help me how to export all my hundreds notes that I have happily created with Boostnote?

**Comment by clouddiver** [comment]
Ok - understood by myself. 
The export functionality doesn't like backslash "/" within the note title as it will then try to store it in a folder that doesn't exist on the mac. 
Further it doesn't handle two notes with the same name, just exports one of them.

**Comment by pfftdammitchris** [comment]
That is good information! Definitely can be solved with a better way.
I'm at work right now and will provide a solution/fix within the next 2 days if there isn't a pull request yet

**Comment by Rokt33r** [comment]
Hmm.. I assume we have to use something like https://github.com/sindresorhus/filenamify to generate file name.
