### ISSUE TITLE
Search hotkey is missing after update on fresh 0.10.0 release

### ISSUE THREAD

**Issue by lulunevermind** [BoostIO/Boostnote#1615]
Hello!
It seems that after update search functionality doesn't work.
https://github.com/BoostIO/boost-releases/releases/download/v0.10.0/Boostnote-mac.dmg
Before:
![image](https://user-images.githubusercontent.com/14962379/36810151-f5e5ef3a-1cda-11e8-8323-6c6f072595aa.png)
Install:
![image](https://user-images.githubusercontent.com/14962379/36810214-1dd3f820-1cdb-11e8-87b0-cc228d802217.png)
After:
![image](https://user-images.githubusercontent.com/14962379/36809895-5eb96b3c-1cda-11e8-9867-ccbbcb2ce691.png)
Platform: OS X 10.13.1

**Comment by rayou** [comment]
this was removed by #1497

**Comment by Rokt33r** [comment]
We're gonna revive it. Check #1503
