### ISSUE TITLE
Using '*' to emphasize Chinese words can't show normally

### ISSUE THREAD

**Issue by WeijianXu** [BoostIO/Boostnote#1619]
When I use boostnote to write my notes in Chinese, I find that using '*' to emphasize Chinese words can't show normally. Some words are oblique, but someone not.
The source code are that:
`
*single asterisks*  *为啥在boostnote中文强调有问题* *abced*
`
`
_single underscores_  _中文强调不正常_
`
but the result likes that:

![_boostnote](https://user-images.githubusercontent.com/18255852/36832204-881bb382-1d65-11e8-921c-a43d530b6d2e.png)

Maybe there is a problem here.

**Comment by Rokt33r** [comment]
@WeijianXu It seems the fonts doesn't support italic. How about to change font?

**Comment by Rokt33r** [comment]
I'm going to close this issue. If you still have the problem after changing the font, let me know to fix it.
