### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by bkjohnson** [BoostIO/Boostnote#162]
I'm trying to build Boostnote on Linux Mint 18 and I get this error when running `npm run hot`:

```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! boost@0.7.2 start: `electron ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boost@0.7.2 start script 'electron ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.
```
However, if I run `npm run webpack` in one terminal and then run `electron ./index.js --hot` in another then Boostnote runs successfully.  Is there some build step that I'm missing?

**Comment by Rokt33r** [comment]
Could you install `electron-prebuilt` again?

`electron ./index.js --hot ` of `npm run hot` uses `./node_modules/.bin/electron`.
If it called directly, it will use global installation.

I'm not sure, but I think the local `electron-prebuilt` isn't installed properly.

**Comment by bkjohnson** [comment]
I apologize, I'm new to electron.  I installed `electron` instead of `electron-prebuilt`; when I get home I will try this and see if it works.  

I just read #136 and that blog post, so it sounds like this won't be a problem in the future?

**Comment by Rokt33r** [comment]
We will move `electron` somewhen instead of `electron-prebuilt`. The current build has a problem when clicking iframe. (To prevent XSS problem, Boostnote uses a sandboxed iframe for markdown preview)
But, as long as you don't forget to `npm install` after the dependencies changed, it won't bother you.
