### ISSUE TITLE
Remove volatile hash from note links

### ISSUE THREAD

**Issue by mirsch** [BoostIO/Boostnote#1623]
The current [note hash](https://github.com/BoostIO/Boostnote/wiki/Data-format#note-hash) is a combination of ```Storage key``` and ```Note key```.
E.g.: ```[Note Title](877f99c3268608328037-09f30b3098e7e18fb9f7)```

This is an huge issue because the ```Storage key``` is volatile. It's random generated on the client and will never be the same again. 
So if you have to [recreate your store](https://github.com/BoostIO/Boostnote/wiki/When-your-notes-are-disappeared%3F) or want sync between different machines (#1512) or just switch to a new device you'll get a new ```Storage key``` and **all note links are broken**.

If the ```Note key``` is not unique, I suggest to use an UUID instead. The filename may change, but I think this can be done without breaking backwards compatibility. 

If you don't like to change the filename maybe adding an UUID as a property inside the ```.cson``` is an option to solve the problem.

An other idea is to store the ```Storage key``` in the ```boostnote.json``` and map it to the hash of the current local store. But if we link to an UUID instead of ```Storage key``` and ```Note key``` the link will not break if you move the note to a different storage.

**Comment by Rokt33r** [comment]
Absolutely. I agree with you.

**Comment by mirsch** [comment]
#843 is also related to this toppic.
