### ISSUE TITLE
Export to HTML replaces some special characters with unusual characters

### ISSUE THREAD

**Issue by thedavidgay** [BoostIO/Boostnote#1624]
## My setup
I am running Boostnote 0.10.0 on High Sierra 10.13.3. My broswer is Firefox Quantum 58.0.2 (64-bit).

## The symptoms
Using the export to HTML feature renders some characters incorrectly. For example, the `–` character is rendered as either `â€“Â` or `â€“` , as seen here:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/1376599/36881001-ce876666-1d99-11e8-9651-2b2a0a5d5ae4.png">

It looks like the `Â` occur where `&nbsp`s are, as seen in the developer tools here:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/1376599/36880897-2e3e3ffe-1d99-11e8-8d4e-8597268e7efe.png">

In addition, apostrophes (`'`) render as `â€™`, as seen below:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1376599/36880816-af7ccb7c-1d98-11e8-80ba-76777c590eb4.png">

In the developer tools, here is the same instance of `isn't`:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1376599/36880964-8a906ca0-1d99-11e8-8121-49f9e262d8ae.png">

## Example files
Attached is a note file and its HTML export that demonstrate the issue. I changed the `cson` and `html` file extensions to `txt` so GitHub would accept them.

[403e979b9127baf0d473.txt](https://github.com/BoostIO/Boostnote/files/1773526/403e979b9127baf0d473.txt)
[export.txt](https://github.com/BoostIO/Boostnote/files/1773528/export.txt)

_(I can't provide the exact file I noticed the bug on because it contains private information, but I am providing a heavily censored duplicate which shows the same symptoms.)_

**EDIT:** Another example is double quotes (`"`) being replaced as well. `"Internet of Things"` is rendered as below:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1376599/36881455-35af8dbc-1d9c-11e8-9e11-78741203502f.png">

**Comment by thedavidgay** [comment]
Adding `<meta charset="UTF-8">` to the exported HTML resolves the issue.

I've opened a pull request with a fix. ^

**Comment by Rokt33r** [comment]
@thedavidgay Thank you for the contribution!
