### ISSUE TITLE
Pasting link should not be converted to MD in codeblocks.

### ISSUE THREAD

**Issue by promiseofcake** [BoostIO/Boostnote#1626]
Regarding new feature in: `Version 0.10.0 (0.10.0)`, pasting a link will fetch the remote title and convert to Markdown.

Two things:
- It would be nice to disable smart-pasting functionality via settings
- Pasting anything inside a code-block should not do any sort of smart-paste functionality.

Examples when pasting https://github.com/BoostIO/Boostnote from clipboard:
```
Single paste:
[<fetched site title>](https://github.com/BoostIO/Boostnote)

Paste + ctrl-z (will sometimes re-resolve to MD):
<https://github.com/BoostIO/Boostnote>

Paste inside a code block (should be noformat):
`` `
[<fetched site title>](https://github.com/BoostIO/Boostnote)
`` `
```

**Comment by Rokt33r** [comment]
> It would be nice to disable smart-pasting functionality via settings
We've already had it.

> Pasting anything inside a code-block should not do any sort of smart-paste functionality.
It sounds very difficult. The editor must recognize the code fences. Let's see which options do we have.

**Comment by promiseofcake** [comment]
Ah! Thanks, sorry I missed the option, that is all I need.
