### ISSUE TITLE
Pictures' url error when exporting as HTML

### ISSUE THREAD

**Issue by kikyoulin** [BoostIO/Boostnote#1628]
![imgbug](https://user-images.githubusercontent.com/30592039/36937599-de27713e-1f50-11e8-87f3-38ee5269f361.png)
picture1 (the source code of some picture in html file)  
  

![picture2](https://user-images.githubusercontent.com/30592039/36937604-f7b252ae-1f50-11e8-9313-9084c63028df.png)
picture2 (open html file with browser)  

I think it should be something like
src="X:\xxx\...\images\xxxxx.png", or src="./images/xxxxx.png"(if pictures can copy while exporting as html)

by the way, I do this now:
1. replace the url with edit tools like notepad
2. open with browser(pictures show normally)  & save as...
Then the html can be portable.

**Comment by Rokt33r** [comment]
I can not understand what the problem is. What happens if we keep using relative path for images?

**Comment by kikyoulin** [comment]
Sorry for a bad description.
The problem is, if I export a note as a HTML file to some folder, and read it with Chrome, the pictures can't present normally (as picture 2, it is a cross). 
As picture 1, browsers can't recognize this relative path.

**Comment by nlopin** [comment]
Hi @kikyoulin! 
What version of the app do you have? Can you show the original content of the note?

**Comment by Bubka** [comment]
Hi,
Same issue here with BoostNotes 0.11.3

My MD code:

```Markdown
[![arrowUp.png](\:storage\0.1m3ufuqf63n.png) Retour au sommaire](#Sommaire)
```
The exported HTML code:
```html
<a href="#Sommaire">
  <img src=":storage%5C0.1m3ufuqf63n.png" alt="arrowUp.png"> Retour au sommaire
</a>
```

The export feature do not copy images to the destination folder (i just have a `.\css`  subfolder) and the path set in src attributes are inconsistent in the HTML code.

**Comment by nlopin** [comment]
You have an image with a link. I'll test it today and fix on weekend

**Comment by Bubka** [comment]
The issue occurs even with stand alone images

**Comment by Flexo013** [comment]
This issue does not seem to be present in the latest version of Boostnote.

Feel free to reopen the issue if you still experience this issue.
