### ISSUE TITLE
Selected part can't adapt when changing to fullscreen mode

### ISSUE THREAD

**Issue by kikyoulin** [BoostIO/Boostnote#1629]
First we select a part of articles
![selection1](https://user-images.githubusercontent.com/30592039/36937799-cb45872e-1f53-11e8-93aa-2362973f132c.png)

now we click "fullscreen" button, it shows unnormally.
![selection3](https://user-images.githubusercontent.com/30592039/36937816-e8c05482-1f53-11e8-9255-4b6f0e15f7cc.png)

the white selected part can be edit, even if no words behind them. I delete the end part
![selection4](https://user-images.githubusercontent.com/30592039/36937849-4ecae490-1f54-11e8-9225-0fba684ebe18.png)

**Comment by Rokt33r** [comment]
I can not reproduce this behavior. Is there anyone who can reproduce?

**Comment by Flexo013** [comment]
Can't reproduce this bug. 

Assuming it's fixed until we can find steps to reproduce this.
