### ISSUE TITLE
Make default note type configurable (Markdown or Snippet)

### ISSUE THREAD

**Issue by DamselDefiler** [BoostIO/Boostnote#1642]
Is there a way to preselect "snippet" as "new note". Its unbearable, to take a new note and use tab (it does not save the choice) always to save code snippets?

I cant find anything in the settings to change that behaviour.
Maybe im missing something important?

<img width="1509" alt="screen shot 2018-03-06 at 22 07 07" src="https://user-images.githubusercontent.com/11557893/37058440-cf0786d0-218a-11e8-92cb-1a9a67a894e6.png">

Sadly im not able to contribute. But since its one of the main goals of the software it would be nice if the GUI would spare 2 or 1 interactions for this task.
Atleast its the only reason i started using this software.

**Comment by Rokt33r** [comment]
I also think that it should be nice to have.

**Comment by Flexo013** [comment]
This should be a fairly easy issue to pick and submit a PR for. New contributors are encouraged to give this a try.

**Comment by arcturus140** [comment]
> should be a fairly easy issue to pick and submit a PR for

It is already implemented, anyway ;)

`Preferences -> Interface / Default New Note: Snippet Note`

**Comment by Flexo013** [comment]
Thanks for pointing that out @arcturus140 !
