### ISSUE TITLE
Proposal: Ctrl+N for Markdown and Ctrl+Shift+N for Snippet

### ISSUE THREAD

**Issue by bkjohnson** [BoostIO/Boostnote#165]
The title is fairly self explanatory.  Rather than have `Ctrl+N` bring up the modal where you have to choose which kind of note you want, why not have `Ctrl+N` create a new Markdown note and `Ctrl+Shift+N` create a new Snippet note?  I think this would speed things up and be a little friendlier for the user.

If this is ok then I'd be happy to make the change myself and submit a PR.

**Comment by ruhsuhl** [comment]
can it be Ctrl + N for Snippet and Ctrl + M for markdown

**Comment by bkjohnson** [comment]
I see where you're coming from, matching M to Markdown, but I believe that following [POLA](https://en.m.wikipedia.org/wiki/Principle_of_least_astonishment) is more important.  In the world of keyboard shortcuts, adding  the `Shift` key to a `Ctrl+[letter]` combination usually means 'do something very similar to the normal operation, but vary it slightly'.

Common examples from word processors, text editors, and IDEs:
+ `Ctrl+O` opens a file, `Ctrl+Shift+O` opens a folder
+ `Ctrl+F` opens a finder window for the current document, `Ctrl+Shift+F` opens a finder window for the entire project

Shift has a history of being a contextual modifier for standard keyboard shortcuts, and I think that that usage should be preserved.

**Comment by ruhsuhl** [comment]
Fair point then perhaps an option for priority would surfice

**Comment by bkjohnson** [comment]
Out of curiosity, how would that work?  I figured that having the shortcuts be configurable would solve the problem.

**Comment by ruhsuhl** [comment]
Custom shortcuts I guess

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report like this feature we can reopen.
Thanks @bkjohnson for your reporting!
