### ISSUE TITLE
amd64.deb doesn't work with dpkg

### ISSUE THREAD

**Issue by mockey** [BoostIO/Boostnote#1651]
There's something wrong with the .deb-file (for a couple of releases now).

`sudo dpkg -i boostnote_0.10.0_amd64.deb`
gives you:
```
dpkg-deb: error: archive 'boostnote_0.10.0_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive boostnote_0.10.0_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 boostnote_0.10.0_amd64.deb
```
Linux Mint 17.3 (a.k.a. Ubuntu 14.04) FWIW.

**Comment by theUncanny** [comment]
Hi!

Check your `dpkg` installed version and repos:

```bash
apt-cache policy dpkg
```

The information of this bug report may help you:

* https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

**Comment by mockey** [comment]
@theUncanny 
Wow, I didn't expect a breaking change like this in dpkg. Thanks a lot for the link.
Updating to dpkg_1.17.5ubuntu5.8 fixes the problem.

**Comment by vmaks** [comment]
@mockey I have the same issue with ubuntu 14.04 x64 and *boostnote_0.10.0_amd64.deb*.
Could you tell me how to fix it?

```
apt-cache policy dpkg
dpkg:
  Installed: 1.17.5ubuntu5.7
  Candidate: 1.17.5ubuntu5.7
  Version table:
 *** 1.17.5ubuntu5.7 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.17.5ubuntu5.6 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.17.5ubuntu5 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

**Comment by mockey** [comment]
I simply downloaded the deb from trusty-propsed:
https://launchpad.net/ubuntu/+source/dpkg/1.17.5ubuntu5.8
Direct link to the deb is:
http://launchpadlibrarian.net/359699265/dpkg_1.17.5ubuntu5.8_amd64.deb
You can install this with the old dpkg fortunately :-)

**Comment by MoElaSec** [comment]
for me I did the following:

```bash
sudo apt update

sudo apt install -y qemu-user-static binfmt-support

sudo dpkg --add-architecture amd64

sudo apt update

sudo apt install libc6:amd64
```


Now I'm able to run x86_64 (AMD64) code:

`sudo dpkg -i boostnote_0.10.0_amd64.deb`

> You mieght need to install some extra lib/packages, thou also in the future it's highly dependable but this is how you support AMD64 arch in ARM.
