### ISSUE TITLE
[Feature Request] Fullscreen on Mac with Ctrl+Cmd+F

### ISSUE THREAD

**Issue by gavvvr** [BoostIO/Boostnote#1653]
Hello. It is usually implemented for any OSX app. You press ^+⌘+F (Ctrl+Cmd+F) and expect the app to be opened in full-screen mode. Please implement it for Boostnote. Now I have to press green circle on the top left corner of Boostnote windows.
Other Electron apps I know (Slack/vscode/atom) can do it.

**Comment by rayou** [comment]
Duplicated #1587

**Comment by romainwn** [comment]
Should be added in the next release :)

**Comment by gavvvr** [comment]
Just received 0.11.0 update. It works, thank you 👍
