### ISSUE TITLE
"dos" code block highlighting doesn't work.

### ISSUE THREAD

**Issue by forestail** [BoostIO/Boostnote#1654]
The highlighting doesn't work even if I wrote following Markdown.
```dos
copy tset ..\
```
It doesn't work too that written "bat" or "cmd" instead of "dos".

Here is an "dos" example.
![2018-03-11_09h56_55](https://user-images.githubusercontent.com/11771/37248391-9ea69098-2514-11e8-956b-c1aa0b679390.png)

FYI
Here is an "sh" example. This works fine.
![2018-03-11_09h57_20](https://user-images.githubusercontent.com/11771/37248394-a2b82778-2514-11e8-85b4-36cadf6944d2.png)

**Comment by forestail** [comment]
Sorry. I  I wrote following Markdown.
<pre>
```bat
copy test ..\
```
</pre>

**Comment by Flexo013** [comment]
`dos` and `bat` are not recognized highlight languages. See [codemirror](https://codemirror.net/mode/index.html) for the full list.
