### ISSUE TITLE
Can't type other language

### ISSUE THREAD

**Issue by WyldeCat** [BoostIO/Boostnote#1657]
I use Korean(Hangul) and English in my Ubuntu(16.04) system.
When I change my input source English to Hangul, I can type Hangul in all other applications but not only the boostnote(0.10.0).

Is it a bug or my mistake?

Thanks.

**Comment by Rokt33r** [comment]
Could you tell me which input method(like iBus) you are using?

**Comment by WyldeCat** [comment]
@Rokt33r 
Thanks. I don't know exactly but I can see ***Fcitx*** in my config window.
![image](https://i.imgur.com/cqqk5cJ.png)

**Comment by Paalon** [comment]
In my environment (Ubuntu 16.04 LTS, fcitx-mozc(Japanese)), it works correctly.

**Comment by WyldeCat** [comment]
@Paalon 
Thanks. My shortcut changing input source is same as you. :(
I will install fcitx-mozc and see it's work or not.

**Comment by WyldeCat** [comment]
@Rokt33r 
Hi, I removed and installed Hangul again, and now can type Hangul in the boostnote.
I don't know this situation is app's bug or not, anyway I fixed it by reinstalling Hangul.

Thanks.

**Comment by WyldeCat** [comment]
I found something more.
Reinstall was not a solution and the problem was terminal's user which is ***root***.
When I exec the boostnote with root, I can't type Hangul and with others I can.

**Comment by Rokt33r** [comment]
Is there any reason to run the app as a root?

**Comment by WyldeCat** [comment]
There is no special reason. It's just my habit.

**Comment by Rokt33r** [comment]
Ok, can I close this issue?

**Comment by WyldeCat** [comment]
Yes. Thanks :)
