### ISSUE TITLE
Check boxes not display

### ISSUE THREAD

**Issue by 78points** [BoostIO/Boostnote#1658]
after last update checkboxes not showing 
```
- [ ] sample checkbox - not working anymore
- [x] sample checkbox 2 - not working anymore
```
green bar showing status of the completion for the checkboxes is still showing but no checkboxes on the page

**Comment by sfjohansson** [comment]
Just discovered this too, both mac and pc. Maybe it would be good to have built in "rollback to previous version button"

**Comment by Rokt33r** [comment]
Oops. This is because we start to sanitizing some tags. I'll make a quick fix today.

**Comment by patrick-iv-knowit** [comment]
They are visible again in 11.1 :) just curious, were there always this much indentation? 
![capture](https://user-images.githubusercontent.com/36044123/37281218-93e55310-25f0-11e8-98f3-dc3af03fd654.PNG)

**Comment by michalfita** [comment]
C00l, the checkboxes reappeared in the preview, but they're misaligned.
