### ISSUE TITLE
Windows:  Disable Direct Write not clickable

### ISSUE THREAD

**Issue by Yotaanit** [BoostIO/Boostnote#1665]
I am using Boostnote v0.11.0 on win10

In the interface preference i can not click the option "Disable Direct Write(It will be applied after restarting)"

All other option I am able to toggle.

**Comment by Zay950** [comment]
I am also having this issue.  Windows 10, version 0.11.6

**Comment by Flexo013** [comment]
This option is clickable in the latest version.

**Comment by guruathwal** [comment]
Not working in version 0.15.0. 
it is unchecked by default and I cannot set it to checked.
tried restarting 3 times.

**Comment by Flexo013** [comment]
@guruathwal We are aware. See #3368
