### ISSUE TITLE
Windows: Black rectangle showing

### ISSUE THREAD

**Issue by Yotaanit** [BoostIO/Boostnote#1666]
When changing between "Default view" <-> "compressed view" a black rectangle shows up.
I am not able to click it or interact with it in any way.
Tried finding it with developer tools but failed.
![boostnote](https://user-images.githubusercontent.com/31347307/37293689-581b8e02-2614-11e8-93ba-1afb98e6c7cd.PNG)

Version: 0.11.0
OS: win10

**Comment by Rokt33r** [comment]
I couldn’t reproduce this problem. Do you have any idea?

**Comment by Yotaanit** [comment]
It seems to also apear when I open the setting.
When closing settings it disapears.

Sometimes it seems as if it disapears when there is a scrollbar present and i click the scrollbar.

I'm sorry if that doesn't help.
![boostnote2](https://user-images.githubusercontent.com/31347307/37452846-1194c984-2836-11e8-916a-ad79654303f1.PNG)

Hiding every element shows a white background with the "rectangle"

**Comment by Rokt33r** [comment]
Hmm.... let's see if there are someone else has same problem. 🤔 
We need more information.

**Comment by myxo** [comment]
Same here. Step to reproduse
* Go to one window mode (dont know how it actually called, see screenshot)
* Edit note
* Press Ctrl+S -> note goes to preview mode
* See grey rectangle

![boostnote](https://user-images.githubusercontent.com/2719353/38163732-7426f932-3501-11e8-9fd9-3ab8082bcc67.png)

On windows machine it dissapears sometimes in a few second, on ubuntu it stays there until I select another note. If it help: it seems it has position of the up left corner of "edit" mode container.

![boostnote2](https://user-images.githubusercontent.com/2719353/38163782-7d55dee6-3502-11e8-8555-c471f2263533.png)

**Comment by myxo** [comment]
btw: same problem here: #1292

**Comment by bimlas** [comment]
It's CSS issue, I willy try to fix it soon.

**Comment by Rokt33r** [comment]
@bimlas Thanks... I have no idea why it doesn't happen on my windows. :sob:

**Comment by bimlas** [comment]
I think I just found the steps to reproduce the issue:

* Open up Developer Tools
* Shrink Boostnote to half screen wide (editor gets hidden by Developer Tools)
* Maximize Boostnote
* Click inside then outside of the editor, switch notes, click in it again, etc.

![screencast](https://i.imgur.com/uEcbq55.gif)

**Comment by Rokt33r** [comment]
I'll try it tonight.

**Comment by bimlas** [comment]
It seems that is has to be some issue with scrolling: if I open Boostnote, enable *Allow editor to scroll past the last line* option, then exit from settings, then the rectangle will be exists without the need of shrinking/maximizing the window. It seems to be a CodeMirror bug, but I cannot find it.

**Comment by ZeroX-DG** [comment]
Can't re-produce in the latest version. Please feel free to re-open this issue if it still exists :+1:
