### ISSUE TITLE
Tag latest release on this repository

### ISSUE THREAD

**Issue by clone1612** [BoostIO/Boostnote#1667]
The Arch package of Boostnote is build from source, being this repo. Would it be possible to tag the v0.11.x release on this repo, just like [https://github.com/BoostIO/Boostnote/releases/tag/v0.10.0](url)?

Thanks in advance!

**Comment by Rokt33r** [comment]
I'll do it now.

**Comment by clone1612** [comment]
Thanks for the tags! The package is once again up to date.
