### ISSUE TITLE
can't change text color

### ISSUE THREAD

**Issue by js418** [BoostIO/Boostnote#1668]
"<"span style="color:blue">some  text</span">" does not work

**Comment by jimtremblay** [comment]
Changing text colour does not work if Sanitization is set to "Only allow secure html tags" or "Allow styles". You need to set it to "Allow dangerous html tags".

Don't know what is dangerous in this, but it is the only way I have succeed to change text colour.

![image](https://user-images.githubusercontent.com/7810954/38143802-1d4ae20a-3410-11e8-97ae-19ee01ebd2fa.png)

Jim

**Comment by Rokt33r** [comment]
@jimtremblay Thanks for the answer!

@js418 Now, you can allow it!
