### ISSUE TITLE
Fail to render markdown in Publish blog feature

### ISSUE THREAD

**Issue by lijinglue** [BoostIO/Boostnote#1675]
Repo step:
Try the new publish blog feature. Nothing happens. Open the dev tools you'll find the error prompt.

Expected result:
Blog correctly rendered as html and post to wordpress

Env: 
Win10

> Uncaught TypeError: _markdown2.default.render is not a function
    at WrappedComponent.publishMarkdownNow (file:///C:/Users/user/AppData/Local/boost/app-0.11.2/resources/app/compiled/main.js:54745:38)
    at file:///C:/Users/user/AppData/Local/boost/app-0.11.2/resources/app/compiled/main.js:54713:17

Seems to be a module resolve issue? I did try the feature in the feature branch, but seems the new version is not working now.

**Comment by lijinglue** [comment]
turns out to be the change in lib/markdown broke the feature, i have a small hotfix for it

**Comment by Flexo013** [comment]
Fix was merged.
