### ISSUE TITLE
Adding a tag can overwrite note content

### ISSUE THREAD

**Issue by madc** [BoostIO/Boostnote#168]
I just noticed a strange behaviour and will try to describe it. Happy to provide more information, if needed.

My Setup:

- Freshly downloaded version of Boostnote (Linux, Gnome)
- One Storage, One Folder
- Two Notes, different content, no tags, sorted by last change

If I now add/remove new tags to the first note, everything is fine. But if I add/remove tags to the second note, the content is overwritten with the content of the first note.
If I unto the change of tags (add new tag and instantly remove it again), the content is reset to its original content.

**Comment by twhiting** [comment]
I ran into this problem @madc I've let @Rokt33r know via our private slack group

**Comment by yusiwen** [comment]
Confirmed on the windows x64 version. Adding tags to 2nd note causes overwriting the note with the content of the 1st note, and the 2nd note is totally lost.

plz fix this, otherwise this app is useless.

**Comment by rtauziac** [comment]
I got the same issue. OS X El Capitan (10.11.5). The overridden content depends of the last note previewed.

You have to open another snippet, Click on **Add tag…** to start writing and switch back to your snippet. When you add a tag to your actual snippet, after pressing _Return_, the preview is replaced by the other snippet, but if you click to edit the snippet it shows the original content.  
Switching to another snippet writes the overridden content and your snippet is lost.

**Comment by pba1** [comment]
Confirmed. On pressing tab or return the note is replaced. Only editing it as the next action restores it. Every other action after tab/return and the note is lost.

Windows 10 Pro
Boostnote 0.7.2

**Comment by Rokt33r** [comment]
I'll start fixing this on this weekend. Sorry for the late supporting.

Currently, this project is not a personal project but is a company's one and I quit the company. 
So, that's the why I've been not here for a while.
Recently, I found many people seem to suffer from these bugs, so I'm going to fix only the bugs of this project until my previous company find the new maintainer. 
But, Don't be worry about my absence. My previous company said they already found some candidates for the new maintainer.
