### ISSUE TITLE
Prevent fetch the title when paste URL into inside of a link tag

### ISSUE THREAD

**Issue by kawmra** [BoostIO/Boostnote#1680]
I like the function to fetch the titles when pasting URL, but sometimes I would like to decide a title manually.

I think it makes no sense the title will be fetched automatically even when I paste a URL into inside of link tag manually.

For example, I don't want the title to expand automatically in the following case.

![boostnote](https://user-images.githubusercontent.com/21209469/37415438-c22c3982-27ee-11e8-84e1-4f9049844f52.gif)

How do you think?

And I can submit PR if you like this proposal.

**Comment by Rokt33r** [comment]
I agree with you. Let us know when you are ready.
