### ISSUE TITLE
Error during installation "The installation of a package which violates the quality standards isn't allowed"

### ISSUE THREAD

**Issue by lkmokadam** [BoostIO/Boostnote#1681]
Error during installation
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /tmp/mozilla_0/boostnote_0.11.2_amd64.deb:
no entry control.tar.gz in archive

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
Skipping /tmp/mozilla0/boostnote_0.11.2_amd64.deb: could not read control data in /tmp/mozilla0/boostnote_0.11.2_amd64.deb:  at /usr/share/perl5/Lintian/ProcessablePool.pm line 91.

**Comment by Rokt33r** [comment]
Which OS are you using? We need more information.

**Comment by lkmokadam** [comment]
Ubuntu 14.04

**Comment by Rokt33r** [comment]
How did you install the app?

**Comment by kulkarniamit** [comment]
Downloaded the `.deb` file from https://github.com/BoostIO/boost-releases/releases/download/v0.11.2/boostnote_0.11.2_amd64.deb and tried installing using Ubuntu Software Center

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"

```

**Comment by Rokt33r** [comment]
Hmm.. I'll fix it today. I assume this happens because I've packed it on macOS.

We should have to prepare some kind of CD. 😭 😭

**Comment by kulkarniamit** [comment]
```
$ sudo dpkg -i boostnote_0.11.2_amd64.deb
dpkg-deb: error: archive 'boostnote_0.11.2_amd64.deb' has premature member 
'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive boostnote_0.11.2_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 boostnote_0.11.2_amd64.deb
```
