### ISSUE TITLE
Can no longer configure storage or add notes.

### ISSUE THREAD

**Issue by kengeorge** [BoostIO/Boostnote#1682]
I recently updated and also moved my notes storage, and due to one, the other, or both of these I seem to no longer be able to create or read notes. When opening the app, I see a call stack error in the console and any storage I had previously configured will now be gone:
![bn03](https://user-images.githubusercontent.com/4393342/37435491-cae7607c-27a0-11e8-9a8d-0e65798c478a.PNG)

After adding the storage folder again, I still cannot add a note (I receive the 'no storage to create note' warning message, though it is not pictured):
![bn01](https://user-images.githubusercontent.com/4393342/37435367-45d39a36-27a0-11e8-8858-f433eadbd92d.PNG)

Even though the storage list still contains the newly added location:
![bn02](https://user-images.githubusercontent.com/4393342/37435368-4831a78c-27a0-11e8-8090-27f07f616709.PNG)

Closing and reopening the application starts the process over again: stack error, missing storage folders, so on.

**Comment by Rokt33r** [comment]
Hmm.. How can I reproduce this problem?

**Comment by kengeorge** [comment]
Good question. A bunch of fiddling/uninstalling/reinstalling never got me back to a working state. However, one of the error traces pointed me here: https://github.com/substack/node-mkdirp/issues/126, which sounds a lot like my edge case (as I  mentioned, I just finished moving my notes location, and it *did* involve a volume change)

Following that, to repro, I did the following:
* Inserted a thumb drive to produce a new mounted volume
* Launched boostnote
* Create a storage location on  the thumbdrive
* Closed boostnote
* Unplugged the drive
* Launched boostnote again
* Successfully observed the same error situation

So looks like it's a good old dependency issue.

Also worth noting that order to get boostnote working at all again, I had to uninstall, completely remove the .../AppData/Roaming/Boostnote directory, and reinstall. I'm not sure what in there is persisting the old volume info, but *something* seems to be.

**Comment by Rokt33r** [comment]
I see. Boostnote store volume info to LocalStorage. Hmm.. I think we have to handle the error.

**Comment by marcelbraun1985** [comment]
I had the same issue. Workaround:

1. Open Developer Tools (View -> Toggle Developer Tools)
2. Switch to Application Tab
3. Extend Local Storage
4. Right Mouse Click on file:// and press Clear

After restart all should be work as expected. But note that your settings will be lost!

**Comment by nuxel** [comment]
> I had the same issue. Workaround:
> 
> 1. Open Developer Tools (View -> Toggle Developer Tools)
> 2. Switch to Application Tab
> 3. Extend Local Storage
> 4. Right Mouse Click on file:// and press Clear
> 
> After restart all should be work as expected. But note that your settings will be lost!

This finally worked for me, thank you.

**Comment by billmetangmo** [comment]
It works for me too . Thanks @marcelbraun1985 :) !

**Comment by Flexo013** [comment]
I think this issue is no longer present in the latest version.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
