### ISSUE TITLE
need shortcut for hide/show (sidenav and nodelist)

### ISSUE THREAD

**Issue by masa4u** [BoostIO/Boostnote#1687]
i using vertical monitor. so when i trying to edit note. it's too narrow to edit note.
so mannualy resize sidenav and nodelist.

nedd some shortcut hide and see (alt+1, alt+2 ), like msvc ide.

**Comment by theFool32** [comment]
By the way, is there any method to make preview widget split vertically?

**Comment by Rokt33r** [comment]
@masa4u 
We have to decide which shortcut keys should be used for each OS.
On macOS, `cmd + b` is quite common.(msvc also uses `cmd+b` on macOS).

So, which OS are you using?

**Comment by masa4u** [comment]
yeah i know that toggle mode. 
The mean 'sidenav' and 'nodelist' windows is
'sidenav' = left section that include several icons ('notes' and 'tags' and 'Preference') and storage and folder list 

and 

'nodelist' = middle section of one of three splited windows.

thanks

**Comment by masa4u** [comment]
@Rokt33r  Windows ^^;

**Comment by Flexo013** [comment]
[You can do Ctrl + B to hide the sidebar and note list.](https://github.com/BoostIO/Boostnote/wiki/Keyboard-Shortcuts)
