### ISSUE TITLE
need fixed title for markdown export.

### ISSUE THREAD

**Issue by masa4u** [BoostIO/Boostnote#1688]
i would like export boostnote to gitbook or other markdown file.
and i made script for export tools that using note'title for filename.

but note's title is changing whenever edit note first line.

can u add some checkbod and add some features for
   1. mannual edit note's title 
   2. title fixing checkbox!(not chaning)

thanks.

**Comment by ZeroX-DG** [comment]
You can use front-matter in the latest version for fixed title. Feel free to re-open this issue if it's not want you want :smiley: 

![image](https://user-images.githubusercontent.com/12984316/56134797-6b10f880-5fe3-11e9-8565-8feae1bec0a0.png)
