### ISSUE TITLE
Add a option to decide default mode

### ISSUE THREAD

**Issue by loggerhead** [BoostIO/Boostnote#1693]
In default, Boostnote is in the preview mode, it is inconvenient in some cases. e.g:

- Comparing the raw content in Boostnote and another editor.
- when I search something, it will not highlight the search word in preview mode. But in edit mode, it works well.

![default](https://user-images.githubusercontent.com/5056390/37561348-8e180e82-2a87-11e8-97e1-4ee70ee48b0c.png)

![default](https://user-images.githubusercontent.com/5056390/37561343-7e4f3caa-2a87-11e8-9d1b-c26a314be0f6.png)

-------

And I am not understand why there exists two Edit mode. What can I do if I want the second Edit mode as the default (or only) Edit mode?

![default](https://user-images.githubusercontent.com/5056390/37561428-35e41b78-2a89-11e8-9777-55c536853433.png)

![default](https://user-images.githubusercontent.com/5056390/37561343-7e4f3caa-2a87-11e8-9d1b-c26a314be0f6.png)

**Comment by modmod24** [comment]
there are 2 modes, preview and full view (I don't know how it's called, exactly). The first mode serves as WYSIWYG editor, the second as WYGIWYM editor. 

You can choose which mode to use with the "Toggle Mode" button. The behaviour for switching between editor and full view for the second mode can be customized in Preferences/Interface/Switch to Preview. You can only use edit mode as well, but Boostnote will always leave the editor mode every time you visit a code snippet or restart the application.

**Comment by Flexo013** [comment]
Duplicate:

Searching in the preview window #2735
