### ISSUE TITLE
Notes not rendered anymore

### ISSUE THREAD

**Issue by dyge** [BoostIO/Boostnote#1694]
Boostnote with a storage on a nas accessible via local Network is not displaying all notes anymore. Just 2 notes are displayed. I see the missing notes in the NAS folder and can access, but they will not be displayed.

The difference is between snipped and markdown mode. Markdown will not be displayed anymore

**Comment by Rokt33r** [comment]
Could you attach a screenshot of the error message? You can found it from devtool.

**Comment by dyge** [comment]
there is no error message, just not displaying older notes.

**Comment by dyge** [comment]
did some additional tests, even adding will show the notes in the actual session, but after restart the notes are not displayed anymore

**Comment by Rokt33r** [comment]
Hmm...🤔 tell me if it happens again. I'll close this issue for now.

**Comment by dyge** [comment]
still not displayed, seems a misunderstanding? finally, i lost my notes in the tool but i´m capable to read the cson files and add to another tool .... Losing data through a tool because of proprietary format is a lesson i learned the hard way .....

**Comment by Rokt33r** [comment]
I'm sorry. I misunderstood. 😢 

Btw, there should be some errors in the console of devtool. Could you submit a screenshot to prove that there are not any errors. I've never seen the case like this.

**Comment by dyge** [comment]
![error](https://user-images.githubusercontent.com/22254452/37585234-b809df6e-2b58-11e8-91b7-2404af19e657.JPG)

**Comment by Rokt33r** [comment]
Yea, those are the errors what I've meant. Open those files and investigate what happened.

**Comment by myxo** [comment]
It's worth mention, that if you still have cson files, you didnt lost your data; cson files have quite simple format, you can restore data by hand (or by write simple script)

**Comment by dhaskew** [comment]
I had this same problem.  For me, if I created notes on my Ubuntu 16.04 system using an older version (0.8.x) then I could see my notes on my mac with the newest (0.11.x) versions.  If I created notes on my mac, then I couldn't see those notes on my Ubuntu system.  Presumably, there was a breaking change in how notes are created in newer versions that is not backwards compatible.

**Comment by Flexo013** [comment]
This issue shouldn't be occurring anymore. If it does happen again then please let us know and we will try our best to deploy a fix.
