### ISSUE TITLE
[Feature request] Auto show horizontal scrollbar for table or code.

### ISSUE THREAD

**Issue by loggerhead** [BoostIO/Boostnote#1695]
When table or code is too wide, or the main windows of Boostnote is too narrow, then the table or code will not full display. Maybe add a horizontal scrollbar is a solution.

Version: Boostnote 0.11.2 on window 10 x64

![default](https://user-images.githubusercontent.com/5056390/37564149-0741b2ac-2acb-11e8-91be-433ffe789eb8.png)

**Comment by rayou** [comment]
I tried in Preview and Exported HTML, both of them have horizontal bar if the code is longer than the viewport.

Boostnote: 0.11.2

**Preview**
![screen shot 2018-03-21 at 10 10 29 am 3](https://user-images.githubusercontent.com/3159256/37687675-96eb5594-2cf0-11e8-9b4d-a2cdc52aee04.png)

**Exported HTML**
![screen shot 2018-03-21 at 10 11 59 am 2](https://user-images.githubusercontent.com/3159256/37687676-97467b04-2cf0-11e8-9c04-28f3ad500205.png)

Although I am using macOS, it sohuld have the same behavior.

**Comment by AlexEshoo** [comment]
I am using Ubuntu 16.04 and experience the same behavior. Boostnote v 0.11.8

Would like to see this feature as well.
