### ISSUE TITLE
Select -> Expand All Storage Locations

### ISSUE THREAD

**Issue by makdiuk** [BoostIO/Boostnote#1697]
Have Collapsed Locations
![image](https://user-images.githubusercontent.com/5962295/37565613-f6fc0598-2ab4-11e8-98f8-4b11eeee5f1b.png)
Expand For Example Development:
![image](https://user-images.githubusercontent.com/5962295/37565605-dd6fa6ac-2ab4-11e8-97c7-9e84abf2a28d.png)
After Press on GoLang all Locations Expanded:
![untitled](https://user-images.githubusercontent.com/5962295/37565672-285746ba-2ab6-11e8-85f2-1c405e77a1e6.png)

**Comment by Rokt33r** [comment]
Sorry, I've misunderstood.

**Comment by makdiuk** [comment]
UP :)

**Comment by ZeroX-DG** [comment]
I believe this bug has been fixed in the latest version
