### ISSUE TITLE
Are snippets just notes with syntax highlighting

### ISSUE THREAD

**Issue by mnishizawa** [BoostIO/Boostnote#1702]
I am trying to understand how I can use snippets once I have added them.  For example, I currently have snippets in Dash and my IDE that I associate a certain string to and they complete for me.  When I hear "snippet", that's the functionality I expect.

It's not clear to me how to make that work in BoostNote or if that functionality is even available. Right now I am hesitant to move my snippets into BoostNote as it doesn't seem to do anything different than a regular note.

I want to suggest this tool to the rest of my team, but I want to understand how this feature works first.

Thanks for a great tool.  I am now using it daily for my own tracking but I want to expand that usage into other things.

**Comment by nlopin** [comment]
The snippet in Boostnote is similar to gists at Github. A snippet here is just a bunch of tabs with only code in them. This is the main difference between a note and a snippet – note can mix markdown with code, snippet is just code organized by tabs. 

It's not the same as snippets in IDE for now. So, you can't assign a hotkey to a snippet and expect for replacing. If you want to have such snippets you should probably use a special tool, i.e. Alfred for Mac.

**Comment by i-give-up** [comment]
Text editor style snippets would be a nice feature to have yeah.

**Comment by Flexo013** [comment]
@mnishizawa @i-give-up

Currently Boostnote does not include such features. If you have specific ideas or wishes then feel free to create a new 'feature request' issue [here](https://github.com/BoostIO/Boostnote/issues/new)
