### ISSUE TITLE
React component tests

### ISSUE THREAD

**Issue by nlopin** [BoostIO/Boostnote#1707]
Boostnote functionality grows incredibly fast. Core components became huge and bloated with logic. We should start components refactoring, but, frankly, I'm scared to do that without at least basic set of tests. Unfortunately, we don't have any.

I propose to use usual testing stack Enzyme+Mocha+Chai to test components. Then we can step by step add tests for components before refactoring. I can start this process in my #1557

@kazup01 @Rokt33r What do you think?

**Comment by Rokt33r** [comment]
I prefer jest. How do you think Jest?

**Comment by rayou** [comment]
I prefer jest as well, easy to configure, mock and most impotantly snapshots 👍

**Comment by nlopin** [comment]
Let's try Jest, it's just a matter of choice. I can add it to the project today

**Comment by Rokt33r** [comment]
@nlopin I appreciate your contributions. I'll gladly wait for it. 💯 💯 💯

**Comment by Flexo013** [comment]
@nlopin @Rokt33r What is the current status on this? Are there any points that still need to be discussed about this?

**Comment by Flexo013** [comment]
I'll close this since we are actively using Jest.

For continued discussion on Jest and test coverage let's use #1826
