### ISSUE TITLE
windows version can't edit width when preview markdown notes

### ISSUE THREAD

**Issue by finaliver** [BoostIO/Boostnote#1708]

**Comment by rayou** [comment]
Hi @finaliver could you please give more details?

**Comment by finaliver** [comment]
![](https://github.com/finaliver/Test/blob/master/bug.PNG)

Hi, as the example, preview window cannot draw the width to fix the whole window.

windows version & markdown doc

**Comment by Rokt33r** [comment]
Hmm.. I think something like zen mode of vs code should be great.

**Comment by Flexo013** [comment]
In the current version of Boostnote the preview mode can utilize the full width.
