### ISSUE TITLE
full screen shortcut for non-osx

### ISSUE THREAD

**Issue by Jaeyo** [BoostIO/Boostnote#1711]
I'm ubuntu user.
shortcut for full screen is (cmd + ctrl + F), but ubuntu has no cmd key. so new shortcut is needed for non-osx user.

but (cmd + ctrl + F) combination is widely used in many osx apps(https://github.com/BoostIO/Boostnote/issues/1587), so i think it is better to add new shortcut for full screen instead of replacing (cmd + ctrl + F)

hot abount (alt + enter)?

**Comment by Rokt33r** [comment]
Is using `Alt + Enter` quite common? I assume we should do same as Atom or VSCode do. If you are using one of them, let me know which keys they are using.

**Comment by romainwn** [comment]
Maybe F11 would be more appropriate for Ubuntu / Windows ?

**Comment by Jaeyo** [comment]
full screen shortcut in atom or vscode is `F11`. `F11` also is good, too.

**Comment by Rokt33r** [comment]
Then, let's use `f11`. Do you want to try to implement? @Jaeyo

**Comment by yougotwill** [comment]
@Jaeyo sorted 👍  https://github.com/BoostIO/Boostnote/pull/1754
