### ISSUE TITLE
After restart lost all folders links to storage location

### ISSUE THREAD

**Issue by chiangs** [BoostIO/Boostnote#1712]
v0.11.0

I have been using Boostnote for many months now with no issues and mobile still works. But on Mac OS X after restart, I lost link to my storage and my dropbox folder. I cannot add it back, only new empty storage folders and when i copy paste all the info from my dropbox storage folder, they do not show up even after restarting app. 

I also lose link to any storage folder I created on a local directory after restarting.

**Comment by Rokt33r** [comment]
There should be an error. Could you take a screenshot from dev tool?

**Comment by kijowski** [comment]
I've encountered the same issue on 0.11.2 and 0.11.3 both on Mac and Windows. It boils down to `TypeError: Cannot read property 'forEach' of undefined` on that line: 
https://github.com/BoostIO/Boostnote/blob/1c283f88d03a2c2ee85adf7603bd2203df4ad77f/browser/main/store.js#L56

![boostnote 2018-03-23 08 41 05](https://user-images.githubusercontent.com/4027031/37817260-843c78d8-2e76-11e8-890c-7d0182817149.png)

**Comment by chiangs** [comment]
This fixed it for me, thanks!
I opened up the storage folder with VS Code, looked at all the csons and found one that said:
```
'content': ''
```
I deleted that and restarted and my original storage and alllll the attempts at linking it again showed up. So then I had to unlink each one manually. A future feature that allows you to check and select all might be nice :)
