### ISSUE TITLE
Import text file

### ISSUE THREAD

**Issue by kampiamodikuesto** [BoostIO/Boostnote#1717]
Impossible to import. I'm on mac os high sierra.

**Comment by Rokt33r** [comment]
We need more description. Where are you trying to import from?

**Comment by kampiamodikuesto** [comment]
i try to drag a local txt files but nothing. Same result if i try to import choosing directly the files

**Comment by Rokt33r** [comment]
I assume we don't support it yet. But, I'm affraid how should we deal with it. 

And, I think the behavior must be changed if the target note is snippet note or markdown note.

**Comment by bimlas** [comment]
@kampiamodikuesto, what is the expected behaviour? Do you like to embed the **file** or copy/paste the text itself in to the current note?

**Comment by Flexo013** [comment]
Files can be imported in the latest version of Boostnote.

Since no other info has been supplied by @kampiamodikuesto over the past few months I will be closing this issue for now.

**Comment by kampiamodikuesto** [comment]
thank, last version works fine!

**Comment by prog20901** [comment]
@Flexo013 how the files can be imported in the latest version? Can u please let me know.

**Comment by Flexo013** [comment]
@prog20901 The option is on the top bar. Click `File` -> `Import From` -> `Plaintext, markdown`. Then simply locate the file you wish to import. Both .txt and .md are supported.
