### ISSUE TITLE
Add attachment to note

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#1723]
Hi guys,
i’ve seen that #250 introduced a way to drop images to the markdown editor to get it inserted as an attachment. It is then also copied to the /images folder in the configured storage folder.
It would be quite nice to have this feature for additional attachment types as well. E.g. I would like to include PDF files as attachment in notes. For me it would be enough if they would be included as a link that can be opened by the OS (e.g. a file:// link).
Any Ideas how to do that?
Background of the question is that my storage folder is within a folder synchronized by a cloud client and I want to include attachments in it as well..
Thanks for your help :)

**Comment by ehhc** [comment]
Attached to this issue is a very quick-and-dirty solution for the given problem. Alas I still do have a lot of questions, I can’t figure out (resp. a lot of issues I stumbled over):
1)	The html export of notes containing images is broken -> no images present
2)	Markdown export with embed files/images is broken -> links are broke
3)	Why are the dropped files named with Math.random().toString(36).slice(-16) (CopyImages.js) instead of something more resilient like Hash(Timestamp + filename) ? Math.random() might return the same result again. Especially when not properly initialized! 
4)	Why are there (at various places) different definitions of markdown-templates to include images? I’ve found at least 3 without being able to figure out why they aren’t at one central place and in what cases they are used
5)	Why are there multiple definitions of the image folder path? e.g. moveNote.js:77, exportNote.js:9, copyImage.js:22 and none global definition? A global reliable definition of this constant variable is missing
6)	No documentation (e.g. JavaScript Doc) is provided. You have to guess what a method does and why it is necessary

Further issues coming up with my dirty fix hack: 
-	methods aren’t doing what they promise to do: e.g. copyImage is able to and use for copying abbreviated files. 
-	“Images” folder (see 5) ) contains further non images attachments as well

I hope you can understand my surprise/irritation about these various issues..

**Comment by ehhc** [comment]
@Rokt33r ans ideas about this?

**Comment by Rokt33r** [comment]
Yea, I think most things you've pointed make a sense. There are lots of things to be fixed because I'd been absent for a year. 😭 😭 

Could you help us? It should be grateful if you can contribute our project.

**Comment by ehhc** [comment]
Hi,
Thanks for your reply. Even though, i would really love to contribute, I'm not sure whether I've enough time to do so at the moment.
I will keep that in mind and try to come back to it in the next time.. Maybe i might find some spare time..
Until then: Can you have a look at my proposed "hack"? Might it possible to merge it? Even though ugly, at least it fixes some of the issues currently present..

**Comment by Rokt33r** [comment]
It's okay. If no one has time to do, I'll take care about it.

> Can you have a look at my proposed "hack"? Might it possible to merge it? Even though ugly, at least it fixes some of the issues currently present..

I'm going to review it in this week.

**Comment by nlopin** [comment]
> The html export of notes containing images is broken -> no images present
> Markdown export with embed files/images is broken -> links are broke

Do you use the last version? 

All exports were fixed some time ago. If you do use the last version, please, provide a video and console output after the export.

**Comment by ehhc** [comment]
Hi there, Thanks for your reply @nlopin 
I'm using version 0.11.3.
If i export the following note (markdown):

```
# Bla
test
![cat_scaled.jpg](\:storage\0.950lu04aev7.jpg)

[AR.txt](\:storage\0.9ra1y6n1euk.txt)

```

I get the following html 
<details>
  <summary>long html file</summary>
&lt;html&gt;
                 &lt;head&gt;
                   &lt;meta charset="UTF-8"&gt;
                   &lt;meta name = "viewport" content = "width = device-width, initial-scale = 1, maximum-scale = 1"&gt;
                   &lt;style id="style"&gt;
@font-face {
  font-family: 'Lato';
  src: url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Regular.woff2') format('woff2'), /* Modern Browsers */
       url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Regular.woff') format('woff'), /* Modern Browsers */
       url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Regular.ttf') format('truetype');
  font-style: normal;
  font-weight: normal;
  text-rendering: optimizeLegibility;
}
@font-face {
  font-family: 'Lato';
  src: url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Black.woff2') format('woff2'), /* Modern Browsers */
       url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Black.woff') format('woff'), /* Modern Browsers */
       url('file://C:\Users\Christopher\AppData\Local\boost\app-0.11.3\resources\app/resources/fonts/Lato-Black.ttf') format('truetype');
  font-style: normal;
  font-weight: 700;
  text-rendering: optimizeLegibility;
}
html,
body,
div,
span,
applet,
object,
iframe,
h1,
h2,
h3,
h4,
h5,
h6,
p,
blockquote,
pre,
a,
abbr,
acronym,
address,
big,
cite,
code,
del,
dfn,
em,
img,
ins,
kbd,
q,
s,
samp,
small,
strike,
strong,
sub,
sup,
tt,
var,
dl,
dt,
dd,
ol,
ul,
li,
fieldset,
form,
label,
legend,
table,
caption,
tbody,
tfoot,
thead,
tr,
th,
td {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-family: inherit;
  font-size: 100%;
  vertical-align: baseline;
}
body {
  line-height: 1;
  color: #000;
  background: #fff;
}
ol,
ul {
  list-style: none;
}
table {
  border-collapse: separate;
  border-spacing: 0;
  vertical-align: middle;
}
caption,
th,
td {
  text-align: left;
  font-weight: normal;
  vertical-align: middle;
}
a img {
  border: none;
}
body {
  font-size: 16px;
  padding: 15px;
  font-family: helvetica, arial, sans-serif;
  line-height: 1.6;
  overflow-x: hidden;
  background-color: #fff;
}
body .katex {
  font: 400 1.2em 'KaTeX_Main';
  line-height: 1.2em;
  white-space: initial;
  text-indent: 0;
}
body .katex .mfrac&gt;.vlist&gt;span:nth-child(2) {
  top: 0 !important;
}
body .katex-error {
  background-color: #f2dede;
  color: #a64444;
  padding: 5px;
  margin: -5px;
  border-radius: 5px;
}
body .flowchart-error,
body .sequence-error {
  background-color: #f2dede;
  color: #a64444;
  padding: 5px;
  border-radius: 5px;
  -webkit-box-pack: left;
  -moz-box-pack: left;
  -o-box-pack: left;
  -ms-flex-pack: left;
  -webkit-justify-content: left;
  justify-content: left;
}
li label.taskListItem {
  margin-left: -1.8em;
}
li label.taskListItem.checked {
  text-decoration: line-through;
  opacity: 0.5;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
  filter: alpha(opacity=50);
}
div.math-rendered {
  text-align: center;
}
.math-failed {
  background-color: rgba(255,0,0,0.1);
  color: #d90000;
  padding: 5px;
  margin: 5px 0;
  border-radius: 5px;
}
sup {
  position: relative;
  top: -0.4em;
  font-size: 0.8em;
  vertical-align: top;
}
sub {
  position: relative;
  bottom: -0.4em;
  font-size: 0.8em;
  vertical-align: top;
}
a {
  color: #2bac8f;
  text-decoration: none;
  padding: 5px;
  border-radius: 5px;
  margin: -5px;
  -webkit-transition: 0.1s;
  -moz-transition: 0.1s;
  -o-transition: 0.1s;
  -ms-transition: 0.1s;
  transition: 0.1s;
}
a img {
  vertical-align: sub;
}
a:hover {
  color: #2eb899;
  text-decoration: underline;
  background-color: rgba(255,201,92,0.3);
}
a:visited {
  color: #2bac8f;
}
hr {
  border-top: none;
  border-bottom: solid 1px #d0d0d0;
  margin: 15px 0;
}
h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: bold;
  word-wrap: break-word;
}
h1 {
  font-size: 2.55em;
  padding-bottom: 0.3em;
  line-height: 1.2em;
  border-bottom: solid 1px #d0d0d0;
  margin: 1em 0 0.44em;
}
h1:first-child {
  margin-top: 0;
}
h2 {
  font-size: 1.75em;
  padding-bottom: 0.3em;
  line-height: 1.225em;
  border-bottom: solid 1px #d0d0d0;
  margin: 1em 0 0.57em;
}
h2:first-child {
  margin-top: 0;
}
h3 {
  font-size: 1.5em;
  line-height: 1.43em;
  margin: 1em 0 0.66em;
}
h4 {
  font-size: 1.25em;
  line-height: 1.4em;
  margin: 1em 0 0.8em;
}
h5 {
  font-size: 1em;
  line-height: 1.4em;
  margin: 1em 0 1em;
}
h6 {
  font-size: 1em;
  line-height: 1.4em;
  margin: 1em 0 1em;
  color: #777;
}
p {
  line-height: 1.6em;
  margin: 0 0 1em;
  white-space: pre-line;
  word-wrap: break-word;
}
img {
  max-width: 100%;
}
strong,
b {
  font-weight: bold;
}
em,
i {
  font-style: italic;
}
s,
del,
strike {
  text-decoration: line-through;
}
u {
  text-decoration: underline;
}
blockquote {
  border-left: solid 4px #3fb399;
  margin: 0 0 1em;
  padding: 0 25px;
}
ul {
  list-style-type: disc;
  padding-left: 2em;
  margin-bottom: 1em;
}
ul li {
  display: list-item;
}
ul li.taskListItem {
  list-style: none;
}
ul li p {
  margin: 0;
}
ul&gt;li&gt;ul,
ul&gt;li&gt;ol {
  margin: 0;
}
ul&gt;li&gt;ul {
  list-style-type: circle;
}
ul&gt;li&gt;ul&gt;li&gt;ul {
  list-style-type: square;
}
ol {
  list-style-type: decimal;
  padding-left: 2em;
  margin-bottom: 1em;
}
ol li {
  display: list-item;
}
ol li p {
  margin: 0;
}
ol&gt;li&gt;ul,
ol&gt;li&gt;ol {
  margin: 0;
}
code {
  color: #cc305f;
  padding: 0.2em 0.4em;
  background-color: #f7f7f7;
  border-radius: 3px;
  font-size: 1em;
  text-decoration: none;
  margin-right: 2px;
}
pre {
  padding: 0.5em !important;
  border: solid 1px #d1d1d1;
  border-radius: 5px;
  overflow-x: auto;
  margin: 0 0 1em;
  display: -webkit-box;
  display: -moz-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: box;
  display: flex;
  line-height: 1.4em;
}
pre.flowchart,
pre.sequence {
  display: -webkit-box;
  display: -moz-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: box;
  display: flex;
  -webkit-box-pack: center;
  -moz-box-pack: center;
  -o-box-pack: center;
  -ms-flex-pack: center;
  -webkit-justify-content: center;
  justify-content: center;
  background-color: #fff;
}
pre.CodeMirror {
  height: initial;
  -webkit-box-lines: multiple;
  -moz-box-lines: multiple;
  -o-box-lines: multiple;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
}
pre.CodeMirror&gt;code {
  -webkit-box-flex: 1;
  -moz-box-flex: 1;
  -o-box-flex: 1;
  box-flex: 1;
  -webkit-flex: 1;
  -ms-flex: 1;
  flex: 1;
  overflow-x: auto;
}
pre code {
  background-color: inherit;
  margin: 0;
  padding: 0;
  border: none;
  border-radius: 0;
}
pre&gt;span.filename {
  width: 100%;
  border-radius: 5px 0px 0px 0px;
  margin: -8px 100% 8px -8px;
  padding: 0px 6px;
  background-color: #777;
  color: #fff;
}
pre&gt;span.lineNumber {
  display: none;
  font-size: 1em;
  padding: 0.5em 0;
  margin: -0.5em 0.5em -0.5em -0.5em;
  border-right: 1px solid;
  text-align: right;
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
}
pre&gt;span.lineNumber.CodeMirror-gutters {
  position: initial;
  top: initial;
  left: initial;
  min-height: 0 !important;
}
pre&gt;span.lineNumber&gt;span {
  display: block;
  padding: 0 0.5em 0;
}
table {
  display: block;
  width: 100%;
  margin: 0 0 1em;
}
table thead tr {
  background-color: #fff;
}
table thead th {
  border-style: solid;
  padding: 6px 13px;
  line-height: 1.6;
  border-width: 1px 0 2px 1px;
  border-color: #d0d0d0;
  font-weight: bold;
}
table thead th:last-child {
  border-right: solid 1px #d0d0d0;
}
table tbody tr:nth-child(2n + 1) {
  background-color: #f9f9f9;
}
table tbody tr:nth-child(2n) {
  background-color: #fff;
}
table tbody td {
  border-style: solid;
  padding: 6px 13px;
  line-height: 1.6;
  border-width: 0 0 1px 1px;
  border-color: #d0d0d0;
}
table tbody td:last-child {
  border-right: solid 1px #d0d0d0;
}
kbd {
  background-color: #fafbfc;
  border: solid 1px #d0d0d0;
  border-bottom-color: #888;
  border-radius: 3px;
  -webkit-box-shadow: inset 0 -1px 0 #959da5;
  box-shadow: inset 0 -1px 0 #959da5;
  display: inline-block;
  font-size: 0.8em;
  line-height: 1;
  padding: 3px 5px;
}
body[data-theme="dark"] {
  color: #f9f9f9;
  border-color: #444b59;
  background-color: #2c3033;
}
body[data-theme="dark"] a:hover {
  background-color: rgba(90,214,186,0.2) !important;
}
body[data-theme="dark"] code {
  color: #ea6730;
  border-color: #3d4450;
  background-color: #363a3e;
}
body[data-theme="dark"] pre {
  border-color: #474f5c;
}
body[data-theme="dark"] pre code {
  background-color: transparent;
}
body[data-theme="dark"] label.taskListItem {
  background-color: #2c3033;
}
body[data-theme="dark"] table thead tr {
  background-color: #282b2e;
}
body[data-theme="dark"] table thead th {
  border-color: #444b59;
}
body[data-theme="dark"] table thead th:last-child {
  border-right: solid 1px #444b59;
}
body[data-theme="dark"] table tbody tr:nth-child(2n + 1) {
  background-color: #2c3033;
}
body[data-theme="dark"] table tbody tr:nth-child(2n) {
  background-color: #282b2e;
}
body[data-theme="dark"] table tbody td {
  border-color: #444b59;
}
body[data-theme="dark"] table tbody td:last-child {
  border-right: solid 1px #444b59;
}
body[data-theme="dark"] kbd {
  background-color: #444b59;
  color: #f9f9f9;
}
body[data-theme="solarized-dark"] {
  color: #93a1a1;
  border-color: #444b59;
  background-color: #073642;
}
body[data-theme="solarized-dark"] table thead tr {
  background-color: #06313b;
}
body[data-theme="solarized-dark"] table thead th {
  border-color: #444b59;
}
body[data-theme="solarized-dark"] table thead th:last-child {
  border-right: solid 1px #444b59;
}
body[data-theme="solarized-dark"] table tbody tr:nth-child(2n + 1) {
  background-color: #073642;
}
body[data-theme="solarized-dark"] table tbody tr:nth-child(2n) {
  background-color: #06313b;
}
body[data-theme="solarized-dark"] table tbody td {
  border-color: #444b59;
}
body[data-theme="solarized-dark"] table tbody td:last-child {
  border-right: solid 1px #444b59;
}
/*# sourceMappingURL=browser/components/markdown.css.map */
body {
  font-family: 'Segoe UI','meiryo','Microsoft YaHei','helvetica','arial','sans-serif';
  font-size: 14px;
  padding-bottom: 90vh;
}
code {
  font-family: 'Segoe UI','Monaco','Menlo','Ubuntu Mono','Consolas','source-code-pro','monospace';
  background-color: rgba(0,0,0,0.04);
}
.lineNumber {
  display: block !important;
  font-family: 'Segoe UI','Monaco','Menlo','Ubuntu Mono','Consolas','source-code-pro','monospace';
}

.clipboardButton {
  color: rgba(147,147,149,0.8);;
  fill: rgba(147,147,149,1);;
  border-radius: 50%;
  margin: 0px 10px;
  border: none;
  background-color: transparent;
  outline: none;
  height: 15px;
  width: 15px;
  cursor: pointer;
}

.clipboardButton:hover {
  transition: 0.2s;
  color: #939395;
  fill: #939395;
  background-color: rgba(0,0,0,0.1);
}

h1, h2 {
  border: none;
}

h1 {
  padding-bottom: 4px;
  margin: 1em 0 8px;
}

h2 {
  padding-bottom: 0.2em;
  margin: 1em 0 0.37em;
}

body p {
  white-space: normal;
}
&lt;/style&gt;
                   &lt;link rel="stylesheet" href="css/dracula.css"&gt;&lt;link rel="stylesheet" href="css/katex.min.css"&gt;&lt;link rel="stylesheet" href="css/codemirror.css"&gt;
                 &lt;/head&gt;
                 &lt;body&gt;&lt;h1 data-line="0" id="Bla"&gt;Bla&lt;/h1&gt;
&lt;p data-line="1"&gt;test&lt;br /&gt;
&lt;img src=":storage%5C0.950lu04aev7.jpg" alt="cat_scaled.jpg" /&gt;&lt;/p&gt;
&lt;p data-line="4"&gt;&lt;a href=":storage%5C0.9ra1y6n1euk.txt"&gt;AR.txt&lt;/a&gt;&lt;/p&gt;
&lt;/body&gt;
              &lt;/html&gt;
</details>

As you can see the links refer to the location ":storage%5C0" which is not available on my desktop!
There are no errors in the console and i hope you can understand this issue without a video (i don't have any idea how to do a video expressing more than the attached code here..

Thanks for your help

**Comment by Rokt33r** [comment]
@nlopin I think ehhc is using windows because the pathname is including back tick(<code>`</code>).

**Comment by Rokt33r** [comment]
It seems the bug has been reported already. https://github.com/BoostIO/Boostnote/issues/1628
