### ISSUE TITLE
No confirmation dialog shown when deleting notes

### ISSUE THREAD

**Issue by frankkanis** [BoostIO/Boostnote#1726]
1. Enable "Show a confirmation dialog when deleting notes" in Interface Preferences -> And Save

2. Delete a note via trash button (top right corner, between fullscreen button and info button) -> Dialog is shown, everything ok

3. Delete a note via context menu in NoteList (right click on notelist item -> "Delete Note") -> No dialog is shown -> NOT ok

**Comment by yougotwill** [comment]
Fixed 👍
