### ISSUE TITLE
Language files are converted to *.pak instead of *.json on Windows

### ISSUE THREAD

**Issue by SiSchae** [BoostIO/Boostnote#1727]
There are only *.pak-files in the locales folder. I copied the de.json to the folder and the translation is working.
![unbenannt](https://user-images.githubusercontent.com/7312638/37815469-4154d134-2e6f-11e8-9038-6c829670ef5b.PNG)

![unbenannt](https://user-images.githubusercontent.com/7312638/37815494-5d51e390-2e6f-11e8-925e-cc43fd00fea2.PNG)

**Comment by Rokt33r** [comment]
Hmm.. I assume we forgot to configure webpack to include locales. 😢
