### ISSUE TITLE
Storage Location lost after update

### ISSUE THREAD

**Issue by kijowski** [BoostIO/Boostnote#1729]
Hi, after one of the recent updates (it happened on 0.11.2 and 0.11.3) I've lost the link to a library stored in Dropbox folder. After that I was unable to add this location again - after selecting it in the settings and clicking the `Add` button nothing happened in the UI.

During the app startup and when trying to add the library again this was shown in the dev console:
![boostnote 2018-03-23 08 41 05](https://user-images.githubusercontent.com/4027031/37817260-843c78d8-2e76-11e8-890c-7d0182817149.png)

It boils down to `TypeError: Cannot read property 'forEach' of undefined` on that line: 
https://github.com/BoostIO/Boostnote/blob/1c283f88d03a2c2ee85adf7603bd2203df4ad77f/browser/main/store.js#L56

I was able to investigate it a bit more and I've found out that it broke because in the notes folder I had a file with following content:
```
'content': ''

```
It was named `57910448-d829-430e-b748-bffc42f6f596.cson` if that helps.
After removing that file notes loaded correctly.

I don't know how this file got created, but I suspect it might have happened during app update / initialization. Create date is `2018/03/20 6:40 AM` which is probably the time that I've started the Boostnote app on that day for the first time.

**Comment by Rokt33r** [comment]
I think we need to handle those error properly. I'll create another issue to do it.

**Comment by Rokt33r** [comment]
Anyway, your issue seems to be fixed. Can I close this?

**Comment by kijowski** [comment]
Sure, you can close this issue.
