### ISSUE TITLE
Feature: Allow the "sort by" feature to be different on "Storage" level and "Folder" level

### ISSUE THREAD

**Issue by Gregordy** [BoostIO/Boostnote#173]
When selecting a value for "sort by", the same value is shared across every folder and the storage those folders are in.
My usage of the app would be even greater if we could have a different "sort by" value between "storage" level and folders of the said storage.

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report like this feature we can reopen. Thanks!
