### ISSUE TITLE
Boostnote marked as malware by Bitdefender

### ISSUE THREAD

**Issue by glego** [BoostIO/Boostnote#1730]
Bitdefender marked boostnote as malware, I've sent analysis to bitdefender

* https://www.bitdefender.com/submit/

![image](https://user-images.githubusercontent.com/13739461/37819238-0ce8e288-2e7d-11e8-868a-412c5175fbe9.png)

![image](https://user-images.githubusercontent.com/13739461/37819382-95c56022-2e7d-11e8-8458-917e73538826.png)

**Comment by Rokt33r** [comment]
It should be false positive. We're using Squirrel.Windows to install and update our application. https://github.com/Squirrel/Squirrel.Windows

I think this comment should be helpful. https://github.com/Squirrel/Squirrel.Windows/issues/1116#issuecomment-318980886
