### ISSUE TITLE
suggestion about markdown table

### ISSUE THREAD

**Issue by SilgerZuo** [BoostIO/Boostnote#1731]
i hava to type standart when use makedown table;

**Comment by Rokt33r** [comment]
What is `standart`?

**Comment by SilgerZuo** [comment]
you can try the plugin on atom ,it's quite easy to edit table in markdown.
maby you can add a plugin that could directly edit with atom ,like the "Atomic chrome" plugin of  chrome
by now,i have to eidt table with atom and copy to the boostnote,,,,,,,,

**Comment by SilgerZuo** [comment]
the name of the plugin on atom is markdown-table-editor

**Comment by Rokt33r** [comment]
Atom editor is quite different from Codemirror. So, we have to write the plugin from the scratch.

Could you submit the screenshot of the plugin for other people to understand what you need easily?

**Comment by SilgerZuo** [comment]
![plugin](https://user-images.githubusercontent.com/15605139/37824907-13e70776-2ec9-11e8-9506-d81b39fd5cb4.gif)

**Comment by ZeroX-DG** [comment]
Implemented in https://github.com/BoostIO/Boostnote/pull/2312
