### ISSUE TITLE
[Question][Not a real issue] Figure placement

### ISSUE THREAD

**Issue by lookbehindyoo** [BoostIO/Boostnote#1733]
I like to use Boostnote as a multi-purpose notebook for my research. As such, I place many images in pages. I do so using html tags of the form;

```html
<figure><center>
<a href="PATH_TO_LOCAL_FOLDER_CONTAINING_IMAGE"><img src="PATH_TO_LOCAL_IMAGE"></a>
<figcaption><b>FIGURE CAPTION</b></figcaption>
</center></figure>
```

I have a figure class CSS snippet that I can include to tweak the figure scaling and placement, and to include word wrapping. 

With the latest update, my figures no longer show. Reading your issues page, I understand that this is to do with unsafe html tags? Can somebody explain if this is indeed unsafe in the case of a local notebook with local images? What would be the safe alternative in this case? I could switch to markdown syntax, but this loses out on some of the formatting options (as far as I am aware). I see the option to allow unsafe tags, which works for now, I just wanted to learn a little more on the topic. 

Thanks

**Comment by Rokt33r** [comment]
I think it is one of bug. Your code looks safe for me.

For now, our sanitization is a little broken.(Although it is pretty safe) So, if you can bear with security risk, you can disable the sanitization until we fix.

**Comment by Flexo013** [comment]
The code provide by join works fine. Make sure to start the path with a `/` like this:

```html
<figure><center>
<a href="/D:"><img src="/D:Cats.png"></a>
<figcaption><b>FIGURE CAPTION</b></figcaption>
</center></figure>
```

The clicking of linked images is known to not work entirely, as discussed here #3120
