### ISSUE TITLE
Clean up trash context menu

### ISSUE THREAD

**Issue by frankkanis** [BoostIO/Boostnote#1739]
Currently the note context menu in trash folder has some menu items, that don't make sense in context of a "deleted" note: 

These items are:
- Clone Note
- Copy Note Link
- Publish Blog

I think the context menu in the trash folder should only have these items:
- Restore Note
- Delete Note

Do you agree? Should I clean this up?

**Comment by Rokt33r** [comment]
Absolutely. 👍 👍 Do you want to try to implement it?
