### ISSUE TITLE
support more languages?

### ISSUE THREAD

**Issue by Hunlongyu** [BoostIO/Boostnote#174]
I really like this software, but can support more languages? Like Chinese?

**Comment by kazup01** [comment]
Sorry for late supporting. 
We are Japanese Team, so not familiar with other language.
But we want to support more language. 
Could you help us? If possible, please join to our Slack group.
https://boostnote-group.slack.com/shared_invite/MTU3ODcwNzY1ODk0LTE0OTAwNjQ0NTYtMjY4NTYwOTdmYQ

**Comment by kazup01** [comment]
Thanks for your cooperation @Hunlongyu again! I close this issue.
