### ISSUE TITLE
[question] Importance of features/fixes, where is the TODO list?

### ISSUE THREAD

**Issue by bimlas** [BoostIO/Boostnote#1750]
I like to help to make this project even better. Is there a public TODO list (ordered by importance)? Or what is the "main" channel to authors? As I see, Facebook is dead; Twitter contains automatically added tweets about PRs/issues; Reddit questions are not answered (mostly). Maybe Slack seems to be alive...

**Comment by Rokt33r** [comment]
> Is there a public TODO list

There isn't. We'd had it, but it has been abandoned since I left this project. So, I think we need one.

> Maybe Slack seems to be alive...

Yes, we can use slack.
