### ISSUE TITLE
Show only related tags, select multiple tags (like CintaNotes, PiggyDB, Zim does)

### ISSUE THREAD

**Issue by bimlas** [BoostIO/Boostnote#1756]
I like to narrow down the tags to **related** ones.

Example:

* string (9)
* integer (5)
* array (4)
* print (2)
* length (1)

When you select a tag by clicking on it (after you enabled this feature on the "control bar"), the related tags geting listed. For example if I select the `string` tag, the other tags of the related entries geting listed, like:

* print (1)
* length (1)

The counter now shows the number of entries with `string` **and** `print`/`length`. If you want to get the full list back, then you can do this by clickin on the "reset" button on the "control bar" (or a dedicated "All" tag - I'm not sure which one is better).

It turns the tag list in to some kind of "dynamic table of contents". This behaviour is exists in CintaNotes and PiggyDB thus I think a lot of users would migrate to Boostnote.

I cannot find the PiggyDB documentation, thus I recommend to try it out on http://piggydb.jp/sandbox/home.htm (guest/guest):

* Select a tag from the tag palette ([python](http://piggydb.jp/sandbox/tag.htm?id=357) for example)
![image](https://user-images.githubusercontent.com/7034200/37900311-23f4e652-30ee-11e8-9643-661a5b47244c.png)
* Clicking on it show the related tags - select the plus sign near Ruby to get "notes" tagged with Python **and** Ruby
![image](https://user-images.githubusercontent.com/7034200/37900440-8c6d08e0-30ee-11e8-8e78-c35429338519.png)

> Clicking on a tag activates it, and only notes having this tag will be displayed. Using Ctrl+Click or Shift+Click, you can expand the tag selection to additional tags. Keep in mind that with Ctrl+Click, a tag intersection is used when multiple tags are selected (i.e. notes having all of the selected tags will be included), whereas with Shift+Click, a tag union is used (i.e. notes having any of the tags will be included).
[CintaNotes manual - Using the Tag Sidebar](http://cintanotes.com/help/#managing)

To get the most out of this:

> I recommend that you keep individual fragments (notes) relatively small. Smaller fragments, which focus on single issues, give you more flexibility when you organize and relate them using the tags.
[PiggyDB manual - Knowledge Fragments](http://piggydb.jp/en/tag.htm?id=12)

Here's a concept:

![slice_1](https://user-images.githubusercontent.com/7034200/37903252-8074cd94-30f7-11e8-8864-64ed853e9d83.png)

The plus sings used to narrow down the list (as I said above), "All tags" resets the narrowing.

One drawback about placing the order selector near to "Tags" title: since i18n is supported, it may be take too much space (for example "Tags" could be "Abcdef ghijklm", "Alphabetically" (order) could be "Nop qrstuv wxyz whatever"), therefore it may be hidden if the sidebar is too strait (as it works on note list's control bar).

**Comment by bimlas** [comment]
You can check out the working (but ugly) version on my [`narrow-to-related-tags` branch](https://github.com/bimlas/Boostnote/tree/narrow-to-related-tags) - I will open a PR when it's finished. The plus sign is above the tag currently, because I didn't take care of style yet.

**Comment by bimlas** [comment]
Here's a screencast - the layout is broken, but the behaviour is what I imagined:

![2018-03-30_14-03-26](https://user-images.githubusercontent.com/7034200/38137147-4c220b0e-3423-11e8-838c-9f14a2bd694c.gif)

**Comment by bimlas** [comment]
Please explain me. I think this is some kind of "dynamic table of content" - for now Boostnote storing notes in bulk, the only method to find a desired note is searching.

**Comment by Rokt33r** [comment]
I've changed my mind. It should be fine.

And, I think we have to prepare some instruction which introduce several searching methods of Boostnote.

**Comment by bimlas** [comment]
Do you mean booleans in query, or...? I'm no sure that I'm understaning your idea. But it would be nice to "synchronize" text search with tags list: clicking on a tag should write `#tag` in to the search field. And it would be more usefull if the taglist would contain the tags of currently listed notes by default (so seraching for a word would refresh the tag list too). I think it would be more consistent and unified. For example I could narrow down the notes list by selecting `#pasta` and `#potato` tags from the tag list (thus `#pasta #potato` would be in the search query), then I could narrow it again by adding `spicey` to the search query (so the search query is `#pasta #potato spicey`). It would narrow the tag list to the integridents of spicey foods with pasta and potato.

**Comment by sosukesuzuki** [comment]
Hi @bimlas .
I ran #1775, but just a glance, I could not understand what happened. 
I could understand that you need this feature for you, but I think it is unnecessary for many users.
What do you think about my opinion?

**Comment by bimlas** [comment]
Maybe a checkbox on the settings page would make the behaviour clear, so this feature would became optional - in this case the plus signs (next to the tag) has to be optional too ->it needs different [TagListItem](https://github.com/BoostIO/Boostnote/pull/1775/commits/eaee15c7604bd3c5328506b01204605cf03c83b9#diff-a31f6488b56b2d8ac4c15cc7f55375bf) + [style](https://github.com/BoostIO/Boostnote/pull/1775/commits/eaee15c7604bd3c5328506b01204605cf03c83b9#diff-c40d8fc14219d4f68554d9289a918473).

I know that this change is big and I agree that a lot of users would don't like it (for first), but it could advantage Boostnote if it would become more unequivocal. I'm not sure how to introduce the feature... Making it optional would smash up the code; making it default would smash up the users.

I have only one idea: making it default, BUT tag list would be narrowed only if multiple tags are selected. WDYT?

**Comment by bimlas** [comment]
...I changed my mind: how do you know which tags are related to the currently selected one? OK, another idea: the related tags could have different colors, it would indicate that the currently selected tag are related to those.

**Comment by bimlas** [comment]
Just made the final version, try out #1775, please.

**Comment by outreal** [comment]
Hi,
@sosukesuzuki maybe I'm a bit late for the discussion, but I just want to say that I would love this feature too. Currently, it's what's keeping me from moving from [Zim](http://zim-wiki.org/downloads.html) (which implements this functionnality) to Boostnote.

In Zim there is a feature which let's you insert [tags](http://zim-wiki.org/manual/Help/Tags.html) in a page. Then I activated [this plugin](http://zim-wiki.org/manual/Plugins/Tags.html) which shows a clickable tag cloud. Whenever you click in a tag, it appears like a pressed button, and it filters out other tags that do not relate to the ones selected. And below the tag cloud, there's a list of the pages matching the search.

**Comment by sosukesuzuki** [comment]
@bimlas & @outreal 
I tried out latest #1775 .  It is good for me. I think that it is okay to merge it.

However, if many users want it (like @bimlas and @outreal ), I think that it may be implemented as an option. In this case, another TagListItem + style will be implemented, but I think that it is unavoidable.

(I'm not good at English. Please point out, if you can not understand the meaning of what I am saying.)

**Comment by bimlas** [comment]
I think that the plus sings does not hurts the users eyes, and adds plus info by marking related tags. The tag list is narrowing optionally. Why would you like to add option to hide the plus sings? I don't see the advanteges of this option. The behaviour does not changing basicly, but improving.

**Comment by sosukesuzuki** [comment]
Sorry, I was a little misunderstood.
I agree with your opinion. Latest #1775 is so good!
I'll review #1775.

**Comment by bimlas** [comment]
#1755 is merged. :grin:
