### ISSUE TITLE
Where did Find/Replace go?

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#176]
Pressing `Ctrl`+`F` while editing a note used to open a text search pane at the top of the editor. Similarly, `Ctrl`+`H` would give you find/replace capabilities with regular expression support. I enjoyed that very much, but it seems like it is no longer there in the most recent boostnote version. Any chance of bringing it back?

**Comment by mikeres0** [comment]
How long ago did this work? If you can give us a rough idea we can look through the changes and see what broke it

**Comment by huettenhain** [comment]
I am quite sure this worked in 0.6.9 or 0.6.8.

**Comment by NonlinearFruit** [comment]
<kbd>Ctrl</kbd>+<kbd>F</kbd> would be great for long notes!

**Comment by asmsuechan** [comment]
I also want it, therefore I try to implement it before long. However I have key map problems especially vim mode. Ctrl + f is already used in vim.

**Comment by apiraino** [comment]
Hello,

I've just installed Boostnote 0.8.7 (Linux) and - me too - I'm a bit puzzled on how and where I can use a search function, I couldn't find it.

I've also tried to remap the `Toggle Finder(popup` function to no avail.

Am I missing something? Any hint?

**Comment by asmsuechan** [comment]
Hi, @apiraino. If you would want to search the content of notes, you need to use `search` located at above the note list. We're trying to improve the search function.

**Comment by apiraino** [comment]
Hello, thanks for the hint. I tried that too, but it has an awkard behaviour, here's two use cases:

* Create a Markdown Note, write "AAABBBCCC" inside. Searching for "AAA", "BBB" or "CCC" does highlight the note indeed

* Create a Snippet Note, write "AAABBBCCC" inside and add title "DESCDESC". Searching for "AAA", "BBB" or "CCC" does *not* highlight the note, searching for "DESC" does find it

**Comment by asmsuechan** [comment]
@apiraino They're correct behavior. It means `snippet` note cannot be searched from `MainWindow`. If you'd want to search `snippet`, you need to use `Finder`.
But you know, it's not intuitive. We should improve the `search experience`.

**Comment by apiraino** [comment]
ok, thanks for the clarification. I'll try to remap the "Finder popup" to a hotkey I can use, currently no keycombo seems to work, possibly an issue due to some interference (?) my window manager (LXDE).

**Comment by asmsuechan** [comment]
@apiraino Yes, you should :smile: Feel free to ask me anything when you have questions. And also you can check our slack team :+1:

**Comment by biax** [comment]
Boostnote is a nice piece of software.............. but it SURELY needs a ctrl-f with highlight function

**Comment by huettenhain** [comment]
By chance I observed that in #76, @Rokt33r said that the editor would be switched from Ace to Codemirror. This is how the feature was lost! I checked out the [Ace editor](https://ace.c9.io/) and it does have the find/replace feature that we so desperately want. Why did boostnote switch? Is it easy to switch back?

**Comment by huettenhain** [comment]
Implemented in 0.8.12, thanks guys!

**Comment by jaques-sam** [comment]
This has been closed 2 years ago, but I can't find any reference in the docs about how to use find or/and replace: https://github.com/BoostIO/Boostnote/wiki/Keyboard-Shortcuts. So how do I easily replace words??

**Comment by Flexo013** [comment]
As listed in the first post of this issue the shortcut is Ctrl+H when the editor is selected. I have updated the wiki page to reflect this.

**Comment by jmd338** [comment]
When I use cmd+H in the editor, it hides my application. If I use ctrl+H it acts as if I hit the "delete" key. Using cmd+F doesn't do anything on Mac. I think this is an issue again.
