### ISSUE TITLE
Lock/Unlock icon not so intuitive

### ISSUE THREAD

**Issue by Huachao** [BoostIO/Boostnote#1760]
Following *lock/unlock* icon is not so intuitive for me, it looks like a display/hidden icon.
![image](https://user-images.githubusercontent.com/2796177/38009719-511c4116-3288-11e8-91a8-65274e589476.png)

**Comment by Rokt33r** [comment]
Could you tell me where can I find the icon? (Although I'm an owner of this project now, I'd been absent this project for a year.)

**Comment by Huachao** [comment]
![image](https://user-images.githubusercontent.com/2796177/38283495-dbbf71d4-37e8-11e8-9c4e-118a4eecb3b1.png)

**Comment by Rokt33r** [comment]
You're right. We should fix this. 💯

**Comment by chartotu19** [comment]
@Huachao I dont see that icon on my installation. Which version are you using?
```code
version: v0.11.4
OS : macos High Sierra 10.13.4
```
