### ISSUE TITLE
Interface language / direct write

### ISSUE THREAD

**Issue by mosesontheweb** [BoostIO/Boostnote#1761]
Hi,

just installed the newest version and discovered a few things.

1. I can change the interface language to something else, however, a restart won't show any difference. The language itself remains in English. The value in the dropdown menu is set correctly, even after a restart
2. I can't set a mark in "Disable Direct Write". I can select the text itself, however, the checkbox is not clickable. The two others above will change on click.

Regards, Thomas

**Comment by frankkanis** [comment]
Hi Thomas,

1. Support for multiple languages is a very new feature. There are still some issues with that. At the moment it only works in debug mode. For production mode all the resources get packed, but this seems to be a problem for the language files. See #1727. Maybe you can help us to fix this?

2. This seems to be a windows only feature, and I'm not sure what this really does. However there is already an open issue: #1665

**Comment by davidmigloz** [comment]
> I can change the interface language to something else, however, a restart won't show any difference. The language itself remains in English. The value in the dropdown menu is set correctly, even after a restart

I'm still experiencing this in 0.11.4.

**Comment by frankkanis** [comment]
@davidmigloz Can you please check, if this is true for all languages? What language did you try?

There are some languages (Albanian, Danish, Japanese, Norwegian, Polish) where the translation file isn't completely translated. 

And there are some other languages (Portuguese, Russian, Spanish) with an issue, that I found while checking this.

Chinese, English, French, German, Hungarian, Korean should work.

**Comment by davidmigloz** [comment]
Indeed, it's the issue described in #1801.

I'm also getting "Error occurs!" every time I try to save the changes (video attached).  Is it related?

https://drive.google.com/file/d/18dcubZhDgMJf17yaWQrmDkqTAJGJE9i9/view?usp=sharing

**Comment by frankkanis** [comment]
It seems not to be related. You should create a new issue.

**Comment by davidmigloz** [comment]
I'll do. Thanks!
