### ISSUE TITLE
Deprecation warning from moment.js involving updateLocale and defineLocale

### ISSUE THREAD

**Issue by urda** [BoostIO/Boostnote#1763]
While trying to fix an issue with my local storage folder I came across this warning in my Developer Console. I did a quick issue search here on GitHub and I didn't find any references to it, so I went ahead and reported the issue here.

# Problem

Boostnote is currently reporting a `Deprecation warning` involving `moment.js`. It looks like Boostnote is making a change to a `locale`, but instead of using `updateLocale` it is calling `defineLocale`. 

According to [this link](http://momentjs.com/guides/#/warnings/define-locale/) from the warning, we can see the following:

> This deprecation warning is thrown when you attempt to change an existing locale using the defineLocale function. Doing this will result in unexpected behavior related to property inheritance. moment.updateLocale will properly replace properties on an existing locale.
> 
> [View original pull request](https://github.com/moment/moment/pull/2774)

## Console Output

```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
warn @ /Applications/Boostnote.app/Contents/Resources/app/node_modules/moment/moment.js:293
```

![boostnote-console-screenshot](https://user-images.githubusercontent.com/1648492/38051619-b101380c-3283-11e8-8706-d9e53bd51ae7.png)

# Known Workarounds

None at this time

# Solution Proposal

I took a short look at debugging this through the call stack, and I think this is getting triggered [on this line](https://github.com/BoostIO/Boostnote/blob/80d1ca81acc38926cbd3f421feb7529b0001c339/browser/main/NoteList/index.js#L916) on app startup. Other than fixing the old deprecated call, there is not another obvious solution I can propose at this time.

# Version Information

- Boostnote: `Version 0.11.3 (0.11.3)`
- macOS: High Sierra `Version 10.13.3`

**Comment by urda** [comment]
It looks like the impacted code region was introduced in commit 706b5d253f4603cf7aa1567c963285a6b50d7193

**Comment by urda** [comment]
I also came across [this GitHub issue](https://github.com/moment/moment/issues/3043) which looks pretty similar to what Boostnote is doing.

**Comment by urda** [comment]
@Karrade7 I'm not fully sure as it was a short-lived issue. I will keep an eye out though if I can reproduce it.

**Comment by Rokt33r** [comment]
Thanks for the reporting. I'll fix it in this week.
