### ISSUE TITLE
 Highlight problem of a list-item including a link text with backquotes

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1766]
Hi, I'm running ver 0.11.3 on Windows 10.
When a list-item includes a link text with backquotes, it is not highlighted correctly.

![2e39089deaaba6a62484b69c8fdd9dcc](https://user-images.githubusercontent.com/247498/38080197-be451cd8-337b-11e8-8d11-e181744f5138.png)

**Comment by bimlas** [comment]
You should escape the backquote, because it is used for `monospaced text` - without quotes it's confusing CodeMirror (the editor).

![image](https://user-images.githubusercontent.com/7034200/38136826-438223aa-3421-11e8-88eb-1a6e2de23e5d.png)

**Comment by bimlas** [comment]
@cignoir , please close the issue if this solved your problem.

**Comment by Rokt33r** [comment]
@cignoir Let us know if you have still problem. 😄 
@bimlas Thanks for the answer!
