### ISSUE TITLE
App Icon for Linux

### ISSUE THREAD

**Issue by madc** [BoostIO/Boostnote#177]
You got this really nice app icon, it would be great, if it could also be used in Linux.

![boost](https://cloud.githubusercontent.com/assets/343392/20397261/67f66bbc-ace9-11e6-9cd5-fcc1a4f99cbd.png)
As reference, [Marp](https://github.com/yhatt/marp/) is an electron app, that also shows an icon on Linux.

**Comment by VoLuong** [comment]
@madc  Which distro are you on. Which version of boostnote you are using? Look at my icon on Xubuntu 16.04.2 
![image](https://cloud.githubusercontent.com/assets/15828926/24074445/3282938c-0c3b-11e7-820c-e5c114c6d551.png)

**Comment by madc** [comment]
I'm on Arch Linux with Gnome. Boostnote is stuck on version 0.7.1 (see #299).

**Comment by VoLuong** [comment]
@madc Then you should wait for an update. I am using 0.8.6 and icon is not a problem.

**Comment by madc** [comment]
No hurry on my part. When i created the ticket four month ago, 0.7.1 was still up to date.

**Comment by DenisBY** [comment]
On Plasma 5 it looks like this:
![image](https://user-images.githubusercontent.com/1147703/27141162-d9977b02-5127-11e7-931a-0e7183d71dc6.png)
![image](https://user-images.githubusercontent.com/1147703/27141208-f68d80ee-5127-11e7-85f9-339c9b41fed3.png)
Boostnote 0.8.10

**Comment by inclooder** [comment]
I have the same issue on cinnamon with latte dock.
![zrzut ekranu z 2017-07-31 21-30-00](https://user-images.githubusercontent.com/5146265/28794695-7055b52a-7637-11e7-9818-b42575255521.png)
Boostnote `0.8.12-2` from AUR

**Comment by kazup01** [comment]
Hi guys, sorry for late support. How about v0.8.15? #806

**Comment by DenisBY** [comment]
0.8.15 looks OK.

**Comment by kazup01** [comment]
Thanks @sferra for your cooperation!

**Comment by sferra** [comment]
you are welcome. thanks for the recent release :)
