### ISSUE TITLE
Boostnote preview jumps to page middle when clicking on copy icon

### ISSUE THREAD

**Issue by iandk** [BoostIO/Boostnote#1776]
When clicking on the copy icon of a code block, the Boostnote preview jumps to another section of the page.

**Comment by Rokt33r** [comment]
There might be some errors. Could you attach some screenshots of devtool when the problem occurs?

**Comment by iandk** [comment]
Sure, how can I open the devtool?

**Comment by Rokt33r** [comment]
You can find it from menu. If you are using mac, press `cmd + alt + I`.

**Comment by Flexo013** [comment]
This bug is no longer present in the latest version of Boostnote.
