### ISSUE TITLE
Minor styling issue with collapsed side nav

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#1777]
<img width="1465" alt="screen shot 2018-04-04 at 4 37 57 am" src="https://user-images.githubusercontent.com/5865853/38271683-0b1efe30-37c2-11e8-83aa-7d5a959c83d9.png">

**Comment by Rokt33r** [comment]
@sosukesuzuki Could you fix this?

**Comment by sosukesuzuki** [comment]
I'll try.

**Comment by kazup01** [comment]
Great work Sosuke @sosukesuzuki :)
