### ISSUE TITLE
Status of the official subreddit

### ISSUE THREAD

**Issue by FistfulOfStars** [BoostIO/Boostnote#1779]
Two of the three mods of the subreddit have been suspended from Reddit completely, and the third one (@asmsuechan) is not active at all.

Posts and comments are being auto-flagged and don't show up if they contain any links. This means any community-provided support is next to impossible.

This subreddit is linked on the official Boostnote homepage and GitHub readme, yet is completely non-functional.

We need new mods to take care of the mod-queue if this is going to be an official support/community forum. I am offering my assistance if it is needed.

**Comment by Rokt33r** [comment]
While I absent for a year, other moderators have been banned from reddit. And, @asmsuechan has left our project. :sob:

Do you know what can I do?

**Comment by kazup01** [comment]
Hi @FistfulOfStars , do you know how can I get back my account in reddit? I'm not a scam...
https://www.reddit.com/user/kazup_

**Comment by FistfulOfStars** [comment]
@kazup01 You should submit an appeal to the reddit admins.

Per the [Account Suspension help page](https://www.reddithelp.com/en/categories/rules-reporting/account-and-community-restrictions/suspensions):

>To appeal a suspension, [contact the admins](https://www.reddit.com/message/compose?to=/r/reddit.com&subject=Account+Appeals). Please include your Reddit username and the reason you believe your account should be unsuspended. We suggest that you review the specific area of the [Content Policy](https://www.reddit.com/help/contentpolicy/) related to why you were suspended.

>While we will review each appeal, we cannot guarantee that we will reverse your suspension. Furthermore, any abusive messages sent to the admin as a result of a permanent or temporary suspension could result in an indefinite and immediate suspension of any alternate or newly created accounts.

@Rokt33r We have three options to clean this up from what I can tell:

1. Get @kazup01 or @junp1234 unsuspended from Reddit
2. Get @asmsuechan to make another reddit user a mod
3. There is a long shot way of requesting control over an abandoned subreddit. [Request](https://www.reddit.com/r/redditrequest/comments/8a0ind/requesting_control_of_rboostnote_open_source/)

**Comment by Rokt33r** [comment]
> There is a long shot way of requesting control over an abandoned subreddit. My Request is not likely to be granted, but we'll see. If it is granted, and @kazup01 or another dev reactivates their account, I will relinquish control if they want me to. My only goal is to clean up the subreddit and get it working properly again.

I'm quite new at reddit. So, It should be grateful if we have voluntary mods.
Let us know if you granted. And, I'll also leave a comment to your request. 👍

**Comment by FistfulOfStars** [comment]
@Rokt33r I have been granted moderator access to the subreddit, sent you an invite to be a mod as well.

If there are others you'd like added (who have an active reddit account) let me know.

**Comment by Rokt33r** [comment]
@FistfulOfStars Cofirmed!! Thanks for the help! ❤️ ❤️ ❤️
