### ISSUE TITLE
C++ highlighting doesn't work

### ISSUE THREAD

**Issue by charolles** [BoostIO/Boostnote#178]
![code](http://i.imgur.com/OJqZyu8.png)

C++ highlighting doesn't work because `mt19937` is inserted.

**Comment by Defenderbass** [comment]
now C++ highlighting works correctly
![3](https://user-images.githubusercontent.com/10637135/32952171-701b6998-cbbd-11e7-9270-4898760cd1d9.PNG)

**Comment by yosmoc** [comment]
@kazup01 It has been fixed. You can close this issue.

**Comment by kazup01** [comment]
Thanks @yosmoc :)
I close this issue, but if someone need to more information, feel free to reopen it.
