### ISSUE TITLE
Printing from dark theme results in gray instead of black text

### ISSUE THREAD

**Issue by j9ac9k** [BoostIO/Boostnote#1780]
If Boostnote has a white interface theme selected, when you go to print, the blacks are the appropriate level of black, but if there is a solarized dark, the blacks turn a little lighter, and if you have a dark interface theme, then the blacks turn even more to light gray.

See screenshots:
<img width="1920" alt="screen shot 2018-04-05 at 7 36 36 am" src="https://user-images.githubusercontent.com/646398/38372611-1b94d6b2-38a4-11e8-82e6-d08319ec56a3.png">

<img width="1920" alt="screen shot 2018-04-05 at 7 37 40 am" src="https://user-images.githubusercontent.com/646398/38372744-65463300-38a4-11e8-8e11-c3f17a43aef8.png">

<img width="1917" alt="screen shot 2018-04-05 at 7 34 27 am" src="https://user-images.githubusercontent.com/646398/38372549-f40c58c2-38a3-11e8-921e-65bc9d95fbae.png">

EDIT: forgot to mention, this is on macOS

**Comment by paulromano** [comment]
I run into the same problem on Ubuntu 17.10 running Gnome shell.

**Comment by zzdjk6** [comment]
I am working on this issue, will submit PR soon

**Comment by zzdjk6** [comment]
Fix PR is https://github.com/BoostIO/Boostnote/pull/1865
