### ISSUE TITLE
HTML-like code snippets are not displaying on HTML Export

### ISSUE THREAD

**Issue by vandijkstef** [BoostIO/Boostnote#1781]
A code snippet as follows:
``` HTML
<meta name="description" content="A brief description about the app / page">
```
Will render empty when exported to HTML. This is also true for any XML/HTML-like elements.

To fix this, the < > symbols needs to be replaced(parsed) to `&lt;` `&gt;` like so output will be:
``` HTML
<code>
    &lt; meta name="description" content="A brief description about the app / page" &gt;
</code>
```

**Comment by Flexo013** [comment]
This bug no longer occurs on the latest version of Boostnote.
