### ISSUE TITLE
Don't appear "Successfully applied!" if preferences scrolled down

### ISSUE THREAD

**Issue by htk3** [BoostIO/Boostnote#1782]
`position: fixed` effects for Save button, but don't for that message (and "Error occurs!" in hotkey preferences has same issue).

![boostnote 2018_04_07 0_55_19_](https://user-images.githubusercontent.com/20188597/38431872-a0cc0596-3a00-11e8-8183-17c89b0ed9e4.gif)

**Comment by Rokt33r** [comment]
Thanks for the reporting!
