### ISSUE TITLE
ALL THE LISTS OF THE FOLDERS FROM ALL THE STORAGES are always listed

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [BoostIO/Boostnote#1783]
There is another super painful situation on the black section of the storage/folders list:

Preparation:
I click all the "v" symbols to reduce all lists of the storages (changing the symbol to the ">" ) and then only the storages names appear. This is good. THen If I click the ">" symbol of a single storage things are fine and the list of all the folders within the storage is displayed (which is good).
PROBLEM:
But if I click on a folder to work on it, then: ALL THE LISTS OF THE FOLDERS FROM ALL THE STORAGES are listed, which is VERY ANNOYING. I hope you can fix this.

Many thanks.

**Comment by Flexo013** [comment]
This bug no longer exists in the latest version of Boostnote.
