### ISSUE TITLE
How can I install version 0.12.x (the latest)?

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [BoostIO/Boostnote#1784]
I was able to install v 0.11.3 only, but I see that some of your bug fixes are in version 0.12.x Therefore, how can we install that version instead of suffering with the bugs in v 0.11.3?
Many thanks. Boostnote is great, and I already have so many notes, but for some reason very annoying bugs are appearing with this 0.11.3 version!

**Comment by Rokt33r** [comment]
Which OS are you using?

**Comment by AlexisEspinosaGayosso** [comment]
I use many (Mac, ubuntu and windows10). Right now I'm sitting in front of the Mac. And it have just updated to 0.11.4. Is this the latest release you were talking about? Many thanks Rokt33r. You rock!

**Comment by AlexisEspinosaGayosso** [comment]
Notes now do not disappear which is fantastic. Thanks a lot for this fantastic tool and all your efforts. Now the only issues I have complained are the ones related to the scrollbars not appearing (#1632), which seems to be a pretty old problem that has not been solved. And also the annoying problem with the storage/folders section (#1783).
