### ISSUE TITLE
Bring line-through on finished items back

### ISSUE THREAD

**Issue by lamka02sk** [BoostIO/Boostnote#1785]
I really miss the line-through decoration on finished TODO list items. It is definitely more clear whether the task is done or not. At least, if there is reason behind this step, add opacity to these items.

**Comment by muhammad-saleh** [comment]
That's what I have on v0.11.3

![image](https://user-images.githubusercontent.com/1510608/38522249-487d3f96-3c48-11e8-9329-ab09899a9620.png)

**Comment by Rokt33r** [comment]
I think this should be optional.
