### ISSUE TITLE
After moving the note from one folder to other, the images attached in the note automatically deleted 

### ISSUE THREAD

**Issue by lkmokadam** [BoostIO/Boostnote#1788]
After moving the note from one folder to other, the images attached in the note automatically deleted. Fortunately, i am using Dropbox location and restored the images. 

OS: Ubuntu 16.04
Version using : Boostnote 0.11.2

**Comment by davidmigloz** [comment]
I'm also experiencing this issue in Mac with Boostnote 0.11.3.

**Comment by ShurikuS57** [comment]
I have the exact same problem on linux.

**Comment by Abracakebabra** [comment]
+1. 

This is a major problem. Leads to data loss.
(Seems not to be a problem for all file formats, e.g. .pdf)

**Comment by ehhc** [comment]
I've submitted a fix for the problem based on the refactoring of the attachment management -> https://github.com/BoostIO/Boostnote/pull/1860
