### ISSUE TITLE
Link to places in note

### ISSUE THREAD

**Issue by eecollante10** [BoostIO/Boostnote#179]
I used to be able to write markdown for linking between places in the note like:
`<a name"tag"/>`
and then

`[Name](#tag)`

But it does not seem to work anymore

**Comment by mikeres0** [comment]
How long ago did this work?

**Comment by eecollante10** [comment]
Like a month ago or longer. I think it worked when the app had old UI, when it was mostly green

**Comment by kazup01** [comment]
Can using it at latest version. Sorry for delay in reporting! Thank you for waiting!
