### ISSUE TITLE
deleted note accidentally

### ISSUE THREAD

**Issue by shunchuan** [BoostIO/Boostnote#1791]
I deleted the note accidentally,Where is the recycling bin? Or how to recover the accidentally deleted note ? thank you .

**Comment by Rokt33r** [comment]
Did you delete it again from the trash?

**Comment by bimlas** [comment]
@shunchuan The trash is located on the top-left:

![image](https://user-images.githubusercontent.com/7034200/38550645-63b6f92c-3cb7-11e8-9312-aaa79d0319ab.png)

**Comment by shunchuan** [comment]
@Rokt33r @bimlas  thank you,I hadn't noticed the recycling bin before.
