### ISSUE TITLE
Allow explicit control of updates

### ISSUE THREAD

**Issue by webwake** [BoostIO/Boostnote#1792]
Currently Boostnote automatically updates when a new version is available and the client is restarted. I would like to see a setting to disable this behavior and require explicit choosing to update.

**Comment by Rokt33r** [comment]
https://github.com/BoostIO/Boostnote/issues/2827 will cover this issue.

**Comment by fornous** [comment]
I know you are hard working on the project and it serves well to my needs, but I use it on daily bases and it's always broken after the update comes. 
So please add at least option to switch the auto update off.
