### ISSUE TITLE
[Issue] Right click "Empty trash" not working when the sidebar is folded

### ISSUE THREAD

**Issue by patrick-iv-knowit** [BoostIO/Boostnote#1793]
What the title says, when the sidebar is folded, Empty Trash is not shown when right clicking

<img width="146" alt="screen shot 2018-04-11 at 08 38 34" src="https://user-images.githubusercontent.com/36044123/38600312-03ac54a2-3d64-11e8-81a8-a2e5c0240425.png">

**Comment by Rokt33r** [comment]
Thanks for the reporting!!
