### ISSUE TITLE
[UX Opinion] Remove the folder handles

### ISSUE THREAD

**Issue by patrick-elmquist-knowit** [BoostIO/Boostnote#1794]
Having a handle icon for each folder just to rearrange feels like a lazy solution to a simple issue.
Also if not looking really closely, the icon looks like a "Pause" icon which makes no sense what so ever.

<img width="58" alt="screen shot 2018-04-11 at 08 42 48" src="https://user-images.githubusercontent.com/36044123/38600455-7186d4ca-3d64-11e8-94f0-a611bd73c23b.png">

**Comment by Rokt33r** [comment]
For me, it looks fine. But, I want to hear more opinion.

How do you think? @sosukesuzuki @bimlas @nlopin @rayou

**Comment by bimlas** [comment]
It doesn't hurting my eyes, btw I'm not sure that feasible, but adding drag-n-drop option to the list items exactly would be an improvement.

**Comment by Flexo013** [comment]
Duplicate of #1661
