### ISSUE TITLE
move note at other location, moved folder's note become location's all notes.

### ISSUE THREAD

**Issue by akaikaze** [BoostIO/Boostnote#1796]
before move
![2018-04-11_18-05-47](https://user-images.githubusercontent.com/12650816/38607426-8e95c658-3db3-11e8-8ad8-cd7cbe96cab4.png)
after move from default to Unnamed aaa
![2018-04-11_18-11-42](https://user-images.githubusercontent.com/12650816/38607505-cda92060-3db3-11e8-89c8-54a74cafcad2.png)

reload boostnote, appear only collect note 
![2018-04-11_18-14-05](https://user-images.githubusercontent.com/12650816/38607633-23a2e118-3db4-11e8-92dc-efd29f7af592.png)

**Comment by Rokt33r** [comment]
I couldn't understand what you are saying. Could you take a video? https://getkap.co

**Comment by akaikaze** [comment]
OK
But I use windows
![ice_video_20180412-090451](https://user-images.githubusercontent.com/12650816/38649374-2c74cf72-3e31-11e8-9a3f-800db5d50193.gif)

**Comment by Rokt33r** [comment]
I see. This is a bug definitely. 😭

**Comment by akaikaze** [comment]
oh sorry
