### ISSUE TITLE
Don't open external links in the preview window

### ISSUE THREAD

**Issue by brrd** [BoostIO/Boostnote#1797]
OS : Windows 10 64 bits.

Since version 0.11.4(2018/4/11), when clicking on a link from preview, the link is loaded into the preview webview.

![image](https://user-images.githubusercontent.com/7335302/38610692-e8229e9e-3d81-11e8-9dac-9d62ce57abed.png)

When switching to another note **into the same folder**, the note is displayed with styles included from the loaded website.

![image](https://user-images.githubusercontent.com/7335302/38610646-c2e4da5c-3d81-11e8-9059-a036630c6bab.png)

Previewing a note contained in another folder obviously resets stylesheets to the default appearance.

Links should be opened with the OS default browser instead.

**Comment by AlexisEspinosaGayosso** [comment]
I totally agree with the comment above!!
Nobody wants to open the links in the preview window when we already expect links to be opened in our preferred webbrowser!
Please do not do this. Please please don't! Guys, come on! This feature is a terrible idea. Thanks.

**Comment by brrd** [comment]
@AlexisEspinosaGayosso I think this is not a feature, this looks like a bug.

**Comment by MrBMT** [comment]
Just had the same issue, hopefully this is indeed a bug.

**Comment by brucezz** [comment]
Links should be opened with the OS default browser instead. Please.

**Comment by airosB** [comment]
Totally agree.

**Comment by JesusPerez** [comment]
Links should be opened with the OS default browser should be a default behaviour or at least let us have a preferences option for another things.

**Comment by sukritchhabra** [comment]
Links aren't even opening for me in the preview window. All I see is a blank white screen. And if I switch between notes then the notes lose their styling and appear as black text on a white bg.

An Example note with a link
<img width="700" alt="screen shot 2018-04-14 at 11 07 32 pm" src="https://user-images.githubusercontent.com/6703126/38774506-d7183302-4038-11e8-8982-0502009f3859.png">

After clicking the link
<img width="700" alt="screen shot 2018-04-14 at 11 07 46 pm" src="https://user-images.githubusercontent.com/6703126/38774507-d72ffc30-4038-11e8-861d-6d13e8c5eaef.png">

After switching between notes
<img width="700" alt="screen shot 2018-04-14 at 11 07 54 pm" src="https://user-images.githubusercontent.com/6703126/38774508-d749eca8-4038-11e8-91c6-7f63ab807d5d.png">

**Comment by Rokt33r** [comment]
@JesusPerez It is a bug, not a feature. 😭

**Comment by gavvvr** [comment]
Just came here to express my opinion on this behaviour. I'm OSX Boostnote user. At least I want links to be opened in browser when I hit it with CMD button pressed. 
And if the links opens in Boostnote itself I would like to have a "Back" button or `Cmd + Shift + [` hotkey working.

**Comment by zzdjk6** [comment]
I want to work on this issue and plan to solve it with a pull request in several days.

If anyone has already solved this issue, please let me know so that I don't have to do redundant work, thanks :)

**Comment by zzdjk6** [comment]
My pull request for this issue: https://github.com/BoostIO/Boostnote/pull/1858

**Comment by brucezz** [comment]
May I know when the next version release ?

**Comment by subhojit777** [comment]
Will be released in v0.11.5. See https://github.com/BoostIO/Boostnote/pull/1858
