### ISSUE TITLE
[Feature Request] Add update controls

### ISSUE THREAD

**Issue by MrBMT** [BoostIO/Boostnote#1798]
Hey,

It'd be great to have some control over the updates; on macOS boostnote just tells you an update has been found when you open it, then automatically downloads it and then prompts you to restart the app to install the update.

It would be nice to have a dropdown in options to control updates, I would propose something like:

- Never Check for Updates
- Notify when Updates Available (you receive a notification informing you about the update, but it does not automatically download or install it)
- Automatically Install Updates (current behaviour)

At the moment if a new version of Boostnote is released and there's a bug causing you to want to roll back to a previous version, on macOS at least it's a bit more complicated to stop it from automatically updating after that again.

Thanks for your consideration.

**Comment by Flexo013** [comment]
This issue and https://github.com/BoostIO/Boostnote/issues/2140 are concerning the same problem. Since the other issue already has funding.

Feel free to continue any discussion over there, and potentially upvote the other issue as well to show your interest in this feature.
