### ISSUE TITLE
JavaScript alert when opened

### ISSUE THREAD

**Issue by pollseed** [BoostIO/Boostnote#18]
<img width="422" alt="2016-04-12 19 38 41" src="https://cloud.githubusercontent.com/assets/6825891/14457596/7f8dac40-00e6-11e6-9486-b33cc7007e37.png">

**Comment by Rokt33r** [comment]
Hmm.. This bug seems to be network problem when updating.
Does it show repeatedly?

**Comment by pollseed** [comment]
Since it healed Once you re-install and close.

**Comment by Rokt33r** [comment]
I'm glad to hear that! Anyway, I'll add error handler later.. Sorry to disturb you. 😢
