### ISSUE TITLE
Feature: Add Side View

### ISSUE THREAD

**Issue by ion-storm** [BoostIO/Boostnote#180]
Can you support adding this to the side of the screen in a column view for quick note taking with minimal screen real estate with the Search on top.

**Comment by kazup01** [comment]
Sorry for the late supporting.
We have received this feedback from several people, so we will considering it.
Thank you for your feedback!

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report like this we can reopen. Thanks!
