### ISSUE TITLE
Minimize workspace bug causes to expand when clicking other workspace folders

### ISSUE THREAD

**Issue by DeepakTivari** [BoostIO/Boostnote#1800]
When I minimize a workspace, it expands whenever I click any other folder in a different workspace or the trash/starred/all notes tab

When i minimize  "My Notes"
![image](https://user-images.githubusercontent.com/8651699/38630700-41505192-3dea-11e8-8f41-19d04c03522d.png)

When i click a folder in "Web Dev", the "My Notes" also expands
![image](https://user-images.githubusercontent.com/8651699/38630733-54668b52-3dea-11e8-803b-c88b8ab05aac.png)

**Comment by Rokt33r** [comment]
Sorry for the inconvenience. 😭

**Comment by ZeroX-DG** [comment]
I believe this is no longer an issue in our latest version.
