### ISSUE TITLE
"Error occurs!" when saving preferences

### ISSUE THREAD

**Issue by davidmigloz** [BoostIO/Boostnote#1806]
Whenever I save some change in preferences I get "Error occurs!", although the changes are correctly applied.

Version 0.11.4 (0.11.4) Mac

![apr-12-2018 22-31-59](https://user-images.githubusercontent.com/6546265/38702627-63c565d4-3ea1-11e8-8595-02bfd736917f.gif)

**Comment by Rokt33r** [comment]
Do the new settings persist after restarting the app?

**Comment by frankkanis** [comment]
@davidmigloz By pressing the "Save" button, boostnote checks all your preferences. Not only the interface preferences. Can you take a look at your hotkeys preferences? I assume the error is there.

**Comment by zzdjk6** [comment]
I think it might be better to give more information when error occurs rather than just saying "Error occurs!"

**Comment by Flexo013** [comment]
This error no longer occurs in the latest version.
