### ISSUE TITLE
Menubar pops up when changing to workspace (i3wm)

### ISSUE THREAD

**Issue by hpaantee** [BoostIO/Boostnote#1808]
# Current behavior
In i3 one changes the workspaces via Alt + number. When I switch from a workspace to the workspace with boostnote, the menubar pops up, which is rather annoying. It seems like boostnote uses the moment I release the Alt key to toggle the menu bar. 

In Firefox for example the problem doesn't occur, as Firefox is "listening" for the press event of the Alt key.

# Expected behavior
The menubar should not pop up when switching to the i3 workspace with boostnote
# Steps to reproduce

1.  Go to a i3 any workspace but boostnote 
2.  press Alt + number to switch to the workspace with boostnote
3. when releasing the Alt the menu bar toggles

# Environment
Debian stretch with i3 and Boostnote 0.11.2

**Comment by ZeroX-DG** [comment]
Hi @hpaantee 
I have submitted a PR to fix this error, just wait for the team to approve it :smiley:
