### ISSUE TITLE
Smart indenting does unexpected things

### ISSUE THREAD

**Issue by blinker57** [BoostIO/Boostnote#1812]
# Current behavior
I am currently coding in Ruby. I am working in a Note as opposed to a Snippet. When I work in a code block and enter a def or do block - I, of course, indent my code from the def or do, but when I outdent to type "end", it indents back in by itself. I first outdent where I want - I then type 'e' and 'n' (everything is fine so far), then I type the 'd' and the word indents itself level with the indented code. This is not where I want it.

![image](https://user-images.githubusercontent.com/25513852/38780380-5e09eff8-40a3-11e8-8096-7f292ec643b2.png)
![image](https://user-images.githubusercontent.com/25513852/38780386-6d860afc-40a3-11e8-8666-8e35394398fc.png)
![image](https://user-images.githubusercontent.com/25513852/38780391-7c131cae-40a3-11e8-814c-bc2e4c0d2aa6.png)
 
** It has been brought to my attention that in Snippet mode, the indents/outdents work fine. This anomaly only happens while working in Notes mode.

Thanks!

# Expected behavior
I would like the indent or outdent to be a little smarter where it should be. I don't think leaving 'end' level with the preceding code is not typical.

# Environment
- Version : Boostnote 0.11.4
- OS Version and name : Windows 7 SP1 64-bit

**Comment by bimlas** [comment]
I think it's not a bug:
- indent level: 0 -> 0
- `def` indent level: +1 -> 1
- `... do` indent level: +1 -> 2
- `end` indent level: -1 -> 1

So you opened two blocks (`def`, `do`), but closed only one (`do`).

**Comment by blinker57** [comment]
@bimlas  I see what you are saying - bad example on my part by putting the 'do' in the fake statement.

The reality is, having the 'do' there doesn't make any difference. You can type legit code and outdent before you type 'end' and it will indent itself back in. Try it.

Thanks for responding.

**Comment by blinker57** [comment]
@ZeroX-DG Your animation looks great. Mine doesn't work like this. Your animation looks like it automatically outdents when you type 'end' - mine does not.

Also, you are highlighting syntax on line 1 - without specifying a code block. Again, mine does not do this.

I am running version 0.11.4. What version do you have?

I am relatively new to Boostnote, so perhaps I am missing something here?

Thanks!

**Comment by blinker57** [comment]
@ZeroX-DG Your animation looks great. Mine doesn't work like this. Your animation looks like it automatically outdents when you type 'end' - mine does not.

Also, you are highlighting syntax on line 1 - without specifying a code block. Again, mine does not do this.

I am running version 0.11.4. What version do you have?

I am relatively new to Boostnote, so perhaps I am missing something here?

Thanks!

**Comment by ZeroX-DG** [comment]
Sorry for the late response but make sure that you have specified the `rb` language name. It works fine on the latest version.
