### ISSUE TITLE
Jump to the next highlighted search keywords in the markdown editor search

### ISSUE THREAD

**Issue by yahyavi** [BoostIO/Boostnote#1813]
# Current behavior

It finds and highlights the string but changes focus to the highlighted keyword in the editor so if you press enter or n (as vim) it replaces highlighted work with enter or n.

# Expected behavior

Jump to the next highlighted keyword.

# Steps to reproduce

Search in the markdown editor.

# Environment

- Version : Any
- OS Version and name : Any

<img width="1310" alt="screen shot 2018-04-15 at 11 39 10 am" src="https://user-images.githubusercontent.com/1531957/38782005-21d73a96-40a2-11e8-9934-6cd98225febb.png">

**Comment by aikon2** [comment]
is done?

**Comment by travisluong** [comment]
Seems like this feature already exists. On mac, you can jump to next highlighted result with CMD + G, and previous highlighted result with CMD + SHIFT + G.

**Comment by ebigelow** [comment]
> Seems like this feature already exists. On mac, you can jump to next highlighted result with CMD + G, and previous highlighted result with CMD + SHIFT + G.

@travisluong  Is the `CMD+G` / `CMD+SHIFT+G` shortcut documented somewhere? After looking at the boostnote docs and googling around for a bit for things like "boostnote search next word", this was the first mention I found.

**Comment by travisluong** [comment]
@ebigelow I don't remember where I found that. I might have stumbled upon it by accident.
