### ISSUE TITLE
is opening url inside boostnote a new feature or a bug

### ISSUE THREAD

**Issue by suruoxi** [BoostIO/Boostnote#1815]
# Current behavior

When a url is clicked in the preview mode,  Boostnote will open it directly rather than open it with the default web browser.   If the url must be visited by a proxy, the Boostnote page become blank.

My question is, is opening url inside Boostnote  a designed feature or a bug? I didn't find this in release notes.

# Environment

- Version :  0.11.4
- OS Version and name : macOS High Sierra 10.13.4

**Comment by frankkanis** [comment]
It's a bug. See #1797

**Comment by suruoxi** [comment]
@frankkanis   Thanks. I close this one.
