### ISSUE TITLE
V0.11.4 can`t emit the finder action

### ISSUE THREAD

**Issue by wuliqiangqiang** [BoostIO/Boostnote#1817]
can`t open the  Finder feature use [Command + alt + S] 

![image](https://user-images.githubusercontent.com/16221367/38800532-1ea752f4-419a-11e8-9ca7-388a95507c1b.png)

![image](https://user-images.githubusercontent.com/16221367/38800968-2a92c4e4-419b-11e8-8be9-5ce1bce89390.png)

only allow set hide/show Boostnote in the hotkeys

**Comment by bimlas** [comment]
The finder feature is discarded (#1479), use the search entry by hitting Ctrl-F.
