### ISSUE TITLE
Clicking a note link breaks something

### ISSUE THREAD

**Issue by zacharyrs** [BoostIO/Boostnote#1819]
# Current behavior
When I click a link from one note to another, the note selection changes, as does the editor content, but the note preview never loads, and is simply a white screen.

If I then click back on a different note, the preview of it loads, but it looks like styling isn't applied.

This is best illustrated by this screenshot
![screen shot 2018-04-17 at 6 04 21 pm](https://user-images.githubusercontent.com/10497077/38851424-d474d5fa-4269-11e8-8468-c0fa0e5a513d.png)

# Expected behavior
I'd expect the new note to load fine, and not break everything

# Steps to reproduce
1. Create two notes, one with various content (e.g. titles, latex, tables, etc)
2. Create a link to the note with content in the second note
3. Click the link in the preview

# Environment
- Version : 0.11.4
- OS Version and name : macOS High Sierra 10.13.4

**Comment by ZeroX-DG** [comment]
closed as fixed
