### ISSUE TITLE
Latex Math display wrong with \sum

### ISSUE THREAD

**Issue by se7oluti0n** [BoostIO/Boostnote#182]
Weird display with this math statement
```
d(\vec{x}, \vec{y}) = \sqrt{\displaystyle\sum_{i=1}^{N} \frac{x_i - y_i}{s_i}}
```

Result
![Rendered formula](http://i.imgur.com/CIIRaTg.png)

**Comment by dpo** [comment]
It works for me:
![screen shot 2016-12-09 at 22 32 58](https://cloud.githubusercontent.com/assets/38760/21070954/7d9c5314-be5f-11e6-858e-e0ddca6ea122.png)

**Comment by asmsuechan** [comment]
Does it still happen? I couldn't confirm the same behavior. Please close this if it doesn't happen.

**Comment by se7oluti0n** [comment]
Hi asmsuechan, 
I upgraded to the lastest verion 0.8.5, and it worked perfectly. 
I am closing it now
