### ISSUE TITLE
Add attachment to note

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#1825]
In #1723 i asked for the feature to include attachments in nodes. I've submitted a really ugly quick fix. Unfortunately there are still some points:

1)	Why are the dropped files named with Math.random().toString(36).slice(-16) (CopyImages.js) instead of something more resilient like Hash(Timestamp + filename) ? Math.random() might return the same result again. Especially when not properly initialized! 
2)	Why are there (at various places) different definitions of markdown-templates to include images? I’ve found at least 3 without being able to figure out why they aren’t at one central place and in what cases they are used 
3)	Why are there multiple definitions of the image folder path? e.g. moveNote.js:77, exportNote.js:9, copyImage.js:22 and none global definition? A global reliable definition of this constant variable is missing. 
4)	No documentation (e.g. JavaScript Doc) is provided. You have to guess what a method does and why it is necessary
My quick fix hasn’t fix these issues.
**I’m working on them at the moment and will submit a more suitable solution as soon as possible.**

**Comment by ehhc** [comment]
@Rokt33r can you already tell more about this new app? will it be open source and free as well?

**Comment by ehhc** [comment]
@Rokt33r btw: my issue wasn't meant as a accusation. I can imagine that it's hard to maintain such a big project. I hope to make the project a little better (as it's intended by the open source idea) with my constribution. I've only mentioned the issues above so that's possible to understand why I try to refactor a few things.

I hope to finish my fix during the comming weekend. I'm looking forward to hearing your thoughts about it.

**Comment by Rokt33r** [comment]
@ehhc Yes, it will be opensource and free!
