### ISSUE TITLE
In exports of notes images aren't shown

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#1827]
In #1723 and #1628 it was mentioned that the export of images doesn’t work on windows systems since the links are broken (see previous issues). Even though the issues are marked as closed at least for me they still persist. **I’m working on it. Will submit a solution as soon as i have a nice one.**

**Comment by Rokt33r** [comment]
Thanks for your effort!

**Comment by pjimenezmateo** [comment]
Great news! I just came here to see if this was being worked on.

**Comment by amitkayal** [comment]
Is this fix released? I have latest version and still facing this problem..

**Comment by ehhc** [comment]
@adrichey : It is already merged into the master branch and will be released in the next official build.
@Rokt33r or the other owners might give you a ETA if you ask them...
