### ISSUE TITLE
[Feature Request] Text Expansion

### ISSUE THREAD

**Issue by ThePopularizer** [BoostIO/Boostnote#1830]
Would it be possible to implement text expansion? So, for example, typing "lorem#" in any app' would expand it to "Lorem ipsum dolor sit amet, consectetur adipiscing elit." [Dash](https://kapeli.com/dash) had this feature, but the app is not available on Windows. 

(First time posting a feature request - hope I'm doing this right)

**Comment by ZeroX-DG** [comment]
Good news, there's nothing wrong with your your feature request :smile: and I also have a PR for this feature, gonna submit it in a few days.

**Comment by takacsot** [comment]
Try AHK on windows
