### ISSUE TITLE
[Feature Request] Syntax Highlighting: AppleScript 

### ISSUE THREAD

**Issue by ChristoferK** [BoostIO/Boostnote#1843]
# Current behavior
AppleScript syntax highlighting is not available as an option.

# Expected behavior
That AppleScript syntax highlighting would be available as an option.

# Steps to reproduce

1. Open Boostnote
2. Create a new snippet
3. Click the language selection tool at the bottom of the snippet editing pane
4. Scroll through the list of available languages
5. Quit Boostnote

# Environment

- Version : 0.11.4
- OS Version and name : macOS High Sierra (10.13.4)

**Comment by Rokt33r** [comment]
@ChristoferK Boostnote is using Codemirror and it doesn't support AppleScript syntax.

If you could afford, you can create codemirror language mode for AppleScript. So we can introduce it.

**Comment by Rokt33r** [comment]
So, I'm close this issue for now. Let us know when CodeMirror support AppleScript!

**Comment by ChristoferK** [comment]
@Rokt33r, OK, that makes sense.  Thanks for the response.
