### ISSUE TITLE
Unassigned tag exists

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1844]
Hi, Im running v0.11.4 on Windows10 64bit.

`#SF` tag is currently unassinged but shown as 1. 
Can I clear garbages or reconstruct tags?

![74ee57611ab6297b347c4eadbfd25fe9](https://user-images.githubusercontent.com/247498/39026045-d092f606-4485-11e8-9624-653de340ee83.gif)

**Comment by cignoir** [comment]
I found the note with `#SF` tag in the Trash.
```cson
tags: [
  "SF"
]
isStarred: false
isTrashed: true
```

I think this behavior is a bit weird and hope this will be fixed.
But if the dev team decides it's OK, close this issue please.

Thanks!

**Comment by Rokt33r** [comment]
I think it is a bug. 😭 Thanks for the reporting!!
