### ISSUE TITLE
Wrong rendering in CodeBlock

### ISSUE THREAD

**Issue by ryochack** [BoostIO/Boostnote#1845]
Hi, Boostnote team.
Boostnote is too useful tool and helps me always!

I report a somewhat strange behavior of Boostnote.

# Current behavior

The rendering of CodeBlock goes wrong. ( I think this is an exceptional case. )
![boostnote_issue](https://user-images.githubusercontent.com/356703/39029935-9e10b63c-4499-11e8-9019-108aea9a32d2.png)

1. `&`, `<`, `>`, and `$` are renderd as HTML numerical character references
2. Appear an unexpected close tag `</tag>`

# Expected behavior
On GFM rendering it seems to be parsed as follows.

```
```c
```

`?`
`<`
`>`
`$`

```
<tag>
```

# Steps to reproduce
Insert "\`\`\`x" into the CodeBlock. (x is arbitrary characters)

# Environment

- Version : Boostnote 0.11.4
- OS Version and name : macOS Hight Sierra version 10.13.3 and ArchLinux

**Comment by Rokt33r** [comment]
Looks critical. We should replace markdown renderer fast. I think I could take on it about 2 weeks later.

**Comment by pvanlaar** [comment]
I have another example of the appearance of a closing tag. The second word inside a tag is parsed as an argument to the tag. I tried it with different languages specified for the highlighting, but that makes no difference.

### Closing tag appears
```
~~~
std::map<std::string, int> map = boost::assign::map_list_of ("key1", 19) ("key2", 21);
~~~
```

#### Output
std::map<std::string, int=""> map = boost::assign::map_list_of ("key1", 19) ("key2", 21);
</std::string,>

### Space after opening bracket (no closing tag)
```
~~~
std::map< std::string, int> map = boost::assign::map_list_of ("key1", 19) ("key2", 21);
~~~
```

#### Output
std::map< std::string, int> map = boost::assign::map_list_of ("key1", 19) ("key2", 21);

**Comment by Flexo013** [comment]
This issue is no longer present in the current version of Boostnote.
