### ISSUE TITLE
Automatic export of notes

### ISSUE THREAD

**Issue by peci1** [BoostIO/Boostnote#1846]
It would be nice to be able to automatically export all notes to some specified directory (in HTML), either on note change, or periodically. Then you could quite easily manage "web pages" using Boostnote, just exporting to a network-mapped directory.

**Comment by Rokt33r** [comment]
Hmm.. It is a markdown note app. Why do you think it have to serve HTML page?

**Comment by peci1** [comment]
Sharing of my notes to colleauges who don't use boostnote.

**Comment by bimlas** [comment]
Storing notes in a native (Markdown) format would solve the problem in my opinion; browser extensions (like [Markdown Viewer](https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk) can be used to preview as HTML.

**Comment by peci1** [comment]
Would it also work with images? I know it somehow needs to be told where the web root is to work correctly, and the MD file doesn't contain this information, it only has the relative paths.

**Comment by bimlas** [comment]
Well... Actually it's not working, becuse images directory is outside of notes dir, thus paths to the images are not relative, for example:   `![dojocat.jpg](\\:storage\\0.1knz98wx582j.jpg)`. If the paths would become relative, then images could work.

**Comment by Flexo013** [comment]
You can currently export and entire folder of notes as HTML with images to share a large batch of notes with people who don't use Boostnote. Yes this is convoluted, but fairly reasonable imo. 

If you want easier automatic sharing of notes from Boostnote, then your colleagues will have to use Boostnote, and use a synchronized storage between you.
