### ISSUE TITLE
Better filenames for notes

### ISSUE THREAD

**Issue by cossio** [BoostIO/Boostnote#1849]
Would it be possible to have better file names for notes? Curently it seems notes have a name based on some hashing. I suggest they include the hashing, plus a word or two from the title.

I keep track of the notes in a git repo. When I see what files changes on a commit, it is meaningless at hte moment because the notes have unintelligible names.

**Comment by Rokt33r** [comment]
I agree with you. The current file name is definitely useless. 🤔

**Comment by Flexo013** [comment]
Duplicate of #1447
