### ISSUE TITLE
SyntaxError on note with a file that has ''' (triple apostrophes) in it

### ISSUE THREAD

**Issue by neouser99** [BoostIO/Boostnote#185]
* create new snippet note
* in file, add contents
~~~
''')
~~~
* close and reload boost
* storage doesn't attach, dev utils complain about a "SyntaxError: unmatched ("

**Comment by asmsuechan** [comment]
Hi @neouser99, is it still occur? I didn't find reproductivity.

**Comment by neouser99** [comment]
It looks like it's been fixed. Tried on version 0.8.3 and it doesn't occur any longer.

**Comment by asmsuechan** [comment]
Thanks for your report!
