### ISSUE TITLE
Updating deletes all folders that are not inside of "My Storage"

### ISSUE THREAD

**Issue by baegmon** [BoostIO/Boostnote#1851]
Updating to the latest version resulted in all of my notes being cleared out of every folder except for the ones that were stored in default storage ("My Storage").

Initially happened on my home desktop system when updating (version 0.11.3 -> version 0.11.4), all notes my custom folders (and notes) were cleared.
Saw that updating it via the application on my work laptop (after saving my notes first) also resulted in the same thing.

- Version: 0.10.0 and 0.11.3
- OS Version and name: Windows 10 (Ver. 1709)

**Comment by jsuen123** [comment]
If anyone looking to recover your notes from this, I found all my lost notes at C:\Users\[your user]\AppData\Local\boost

**Comment by Flexo013** [comment]
This issue does not seem to occur in the latest updates anymore.
