### ISSUE TITLE
[Feature Request] Evernote synchronisation 

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#1861]
Some of my colleagues are using evernote as a note taking app. This comes (besides other reasons) from the fact that collaborative working is possible there. I would wish for an evernote sync so that it’s possible to contribute to the shared notes from within boostnote.

Thoughts on this? Am I the only one wishing for that?

**Comment by eyleron** [comment]
So, the use case is, "for these areas of collaborative notes, sync to Evernote (or the Notes' store *is* Evernote) bidirectionally." ?

**Comment by ehhc** [comment]
@eyleron yap, i meant it that way: i want to be able to collaborate with evernote shared notes from within of boostnote. I've seen there is a [evernote nodejs sdk](https://github.com/evernote/evernote-sdk-js) maybe that can be used?

**Comment by dylhack** [comment]
This would be great to have

**Comment by Flexo013** [comment]
This is going to be incredibly complex to implement as both platforms have features that the other doesn't. So notes will change and functionality will be heavily reduced to get this working.
