### ISSUE TITLE
PlantUML support

### ISSUE THREAD

**Issue by micronpn** [BoostIO/Boostnote#1864]
PlantUML recently added some new diagrams:
- deployment diagrams
- timing diagrams
- GANTT diagrams

but seems they are not supported in Boostnote.

**Comment by yosmoc** [comment]
Hi @micronpn ,

## deployment diagrams
In my environment, it seems it has already been supported. I use 0.11.4 in OSX. 
![image](https://user-images.githubusercontent.com/9694/39949561-c01b7af8-557b-11e8-8d69-b3b5639a273a.png)

## timing diagrams

For plantuml support, we use [markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml). This library's current implementation cannot parse the timing diagram correctly, so I sent the [patch](https://github.com/gmunguia/markdown-it-plantuml/pull/6) to this project. When it is merged and the new version, I will send pull request.

## GANTT diagrams

This one is bit tricky. In the [official page](http://plantuml.com/gantt-diagram), they use @startgantt/@endgantt as a delimiter. markdown-it-plantuml can only support one delimiter at the same time.(default is @startuml/@enduml). If you use @startuml/@enduml as a delimiter, the gantt diagram should be correctly rendered. 
![image](https://user-images.githubusercontent.com/9694/39949995-c7651370-557e-11e8-8740-562f16848de9.png)

However, according to [this discussion](http://forum.plantuml.net/6592/add-a-%40startgantt-and-%40endgantt-for-gantt-diagrams), @startuml/@enduml for gantt diagram will not be supported in the future. Gantt chart is still beta and it is bit early to support this syntax, so probably we will live with @startuml/@enduml in this stage.
