### ISSUE TITLE
Fortran syntax don't work after update 0.7.3

### ISSUE THREAD

**Issue by larabih** [BoostIO/Boostnote#187]
```f90
write(*,*) "Message ..."
print*, x,y,z
```
in black color

**Comment by kazup01** [comment]
Oh, thank you for reporting! I will check it.

**Comment by asmsuechan** [comment]
Hi @larabih does it still occur in v0.8.0? In my environment, syntax highlight works well.

![2017-01-12 1 10 25](https://cloud.githubusercontent.com/assets/11307908/21856091/056a14a2-d864-11e6-997d-e92cf7189615.png)

**Comment by larabih** [comment]
Hi

I already use the keyword

```f90
code
```

And now I found another syntax

```fortran

code


```

Now it works perfectly.

Thank you for BoostNote

Hakim

2017-01-11 17:11 GMT+01:00 SuenagaRyota <notifications@github.com>:

**Comment by asmsuechan** [comment]
Good! Have a good Boostnote life!

**Comment by sota1235** [comment]
@larabih If you have no problem more, please close the issue :)
