### ISSUE TITLE
PDF export bug for todo lists

### ISSUE THREAD

**Issue by micronpn** [BoostIO/Boostnote#1877]
Printing from Boostnotes to any PDF virtual printer I have (Adobe, Foxit, Bullzip and iSkye) does not preserve the ticks on the tick boxes. Evary ticbox is printed as empty also if it is ticked.

**Comment by zachselby** [comment]
@micronpn On which OS are you facing the issue? I'm using Version 0.11.4 (0.11.4) on OS X Sierra and the PDF output does contain the modified tickboxes when opening the PDF in Preview, or Saving a PDF [then viewing with Acrobat].

![boostnote-1877-open-in-mac-preview](https://user-images.githubusercontent.com/410813/39852221-597f452e-53e9-11e8-9f34-68e469c79c99.gif)

PS. First comment, and first night using BoostNote. Will join in with some PRs for a few ideas I have already.

Thanks to you all in the community! Great tool.

**Comment by jk3us** [comment]
I'm getting all unchecked boxes when I print as well (on paper).  I'm on Windows 7.

**Comment by Flexo013** [comment]
On Windows 10 with Boostnote version 0.12.1 I don't have any export problems with checkboxes.

Feel free to reopen this thread if the issue pops up again.
