### ISSUE TITLE
Add highlighting

### ISSUE THREAD

**Issue by ctrngk** [BoostIO/Boostnote#1879]
Expected behavior
![image](https://user-images.githubusercontent.com/16743578/39391722-bbe23658-4ada-11e8-91fe-ce7177a14b96.png)

how to implement this in boostnote? 
<mark>Mark word</mark> works out of code block, but <mark> inside code block does not work.
I am not familiar with Markdown, and I doubt about it a really good note-taking approach.  No offense.

**Comment by ctrngk** [comment]
I simply use evernote, which could change any letter in any color. It is a basic feature just like word in ms office. However, it might be overkilled. Simple highlighting is good, isn't it? My eyes will easily focus on important codes between multiple colorful lines.

**Comment by bimlas** [comment]
Sorry, I misunderstood this: "Mark word works out of code block" - I thougth you are doing this in Boostnote.

**Comment by Flexo013** [comment]
@ctrngk So you are asking for some syntax that would add highlighting to the Markdown syntax?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
