### ISSUE TITLE
How about support metaweblog?

### ISSUE THREAD

**Issue by cringha** [BoostIO/Boostnote#1880]
How about support metaweblog ?

**Comment by cringha** [comment]
I fork this project and add metaweblog-api support.   [https://github.com/cringha/Boostnote](https://github.com/cringha/Boostnote), But i don't know how to send a `pull request`. 

This below are something i posted about the metaweblog-api features. 

![image](https://user-images.githubusercontent.com/1596848/39740560-ccc8e728-52c8-11e8-9516-00683342ebb9.png)


![image](https://user-images.githubusercontent.com/1596848/39740444-31019506-52c8-11e8-8760-92f837a79c4f.png)
  
![image](https://user-images.githubusercontent.com/1596848/39740532-9cb6e8aa-52c8-11e8-8dd6-3b60f22ba666.png)

**Comment by Flexo013** [comment]
@cringha Do you still have the code to submit the PR?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
