### ISSUE TITLE
click on link opens within boostnote

### ISSUE THREAD

**Issue by hollstein** [BoostIO/Boostnote#1882]
# Current behavior

After the recent update to 0.11.4, when clicking on a link in Boostnote, the page loads within boostnote.

![grafik](https://user-images.githubusercontent.com/16288266/39427738-31bd20f8-4c85-11e8-9e5c-70267fa5e0d0.png)
![grafik](https://user-images.githubusercontent.com/16288266/39427757-412ca96e-4c85-11e8-98c1-6a63184c2928.png)

# Expected behavior

The link should open in browser.

# Steps to reproduce

1. Add link to note.
2. Click on link.

# Environment

- Version : 0.11.4
- OS Version and name : Windows

**Comment by kazup01** [comment]
Fixed at #1858.
