### ISSUE TITLE
Icons not appearing after installing boostnote in windows 7

### ISSUE THREAD

**Issue by abhiramravipati** [BoostIO/Boostnote#1888]
![image](https://user-images.githubusercontent.com/2103586/39638723-bec3474a-4fe4-11e8-8fbb-dc85e240f5a7.png)
# Current behavior

Hi installed Boostnote recently on windows 7 but the boostnote when I am opening after installation icons are not appearing.Attached the screenshot.

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by bimlas** [comment]
Just tried out a fresh install and the most recent Git version too: icons are shown in both.

**Comment by abhiramravipati** [comment]
![image](https://user-images.githubusercontent.com/2103586/39659868-15e3cb9c-5050-11e8-9276-92e2f07309df.png)
Tried fresh install and most recent Git version in windows 7.Still same issue.

**Comment by ehhc** [comment]
@abhiramravipati could you post the content of the developer console? Use View -> Toggle developer console and post the issues listed there please

**Comment by Flexo013** [comment]
@abhiramravipati @bimlas Does this issue still exist on Windows 7 with the latest version of Boostnote?

**Comment by bimlas** [comment]
@Flexo013 Everything seems to be fine for me.
