### ISSUE TITLE
search ... or no search in snippets?

### ISSUE THREAD

**Issue by chrnoe** [BoostIO/Boostnote#1892]
a little confusing behavior ... I write a snippet note (no markdown), and after this I can't search for words in the snippet, boostnote does not find this entry. If I put some of the words in the description, then this entry will be found, and the searching word is also marked as found in the snippet.

![screenshot](https://user-images.githubusercontent.com/25639324/39805184-680ffbec-5376-11e8-9368-c49f9fd831d7.PNG)

**Comment by hubitor** [comment]
Something like the search function in CherryTree or Freeplane would be great.

**Comment by Flexo013** [comment]
Search within snippets works in 0.15.3 of Boostnote Legacy.
