### ISSUE TITLE
Macos custom keyabord shortcuts break copying and pasting .

### ISSUE THREAD

**Issue by i008** [BoostIO/Boostnote#1896]
# Current behavior

On macos when shortcuts  for COPY and PASTE are remapped (Keyboard->Shortcuts->App Shortcuts)  its impossible to paste or copy in boostnotes. Aswell using control-c and command-c

# Expected behavior
I shouyld be able to paste and copy with control-c and control-v if they are reamepped in macos

# Steps to reproduce

1.  Add shortcuts to menu items ( keyboard-shortcuts-app shortcuts)
![img](https://i.imgur.com/6Meuqru.png)
2. Try copying in the app

# Environment

- Version : Version 0.11.4 (0.11.4)
- OS Version and name :  MACOS HIGH SIERRA

**Comment by Flexo013** [comment]
@i008 Can you confirm that this is fixed in the latest version of Boostnote?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
