### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by bitbonsai** [BoostIO/Boostnote#19]
Hi

I forked Boostnote to create a cask, but I have no idea of what `auth_code.json` is. Could you tell me what's that and how can I have one? My idea is to provide a /releases/ folder with osx versions, and the homebrew formula.

Thanks

**Comment by Rokt33r** [comment]
You don't worry about it. It needs to build installer for Windows app.

**Comment by Rokt33r** [comment]
Could you explain more about providing this app as a homebrew formula?
If you give me some instructions, I think I can help you properly.

**Comment by Rokt33r** [comment]
I'll try to make brew formula myself.

**Comment by bitbonsai** [comment]
So, the advantage is to be able to build Boostnote from Homebrew, and keep a backup for a fresh install.

**Comment by Rokt33r** [comment]
Could you give me more information where I can start to learn it?

**Comment by yosmoc** [comment]
Homebrew cask has already supported boostnote.
https://github.com/caskroom/homebrew-cask/blob/8121f2a73a03ab8d570a7d2c9bc6b09e6fef129b/Casks/boostnote.rb

We can close this issue.

**Comment by Rokt33r** [comment]
OMG, I didn't noticed that! 😮😮😮 Thanks for your reporting!
