### ISSUE TITLE
Change sort order of sub-notes in a Note

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#190]
Can you add the capability to re-arrange and sort the order of sub-notes inside of a note?

![boostnote_2016-12-20_13-32-00](https://cloud.githubusercontent.com/assets/186818/21363098/2b376ad4-c6b9-11e6-805a-7e4c456ba372.png)

**Comment by kazup01** [comment]
Thank you for feedback.
That's a great idea👍 I added the todo list.

**Comment by kazup01** [comment]
Hi @jasondavis san , sorry for our late supporting.
We want to add it but we have other priorities. If possible, could you send PR to us?

**Comment by bimlas** [comment]
It seems implemented, issue may be closed.
