### ISSUE TITLE
Recover .md files frome .cson (encoding conversion)

### ISSUE THREAD

**Issue by tholoz** [BoostIO/Boostnote#1901]
Hi there, 
Like some people all my notes recently disappeared from the interface. Fortunately I was able to make a copy of all the .cson files embedding my notes. They look like this :

```
'createdAt': '2018-04-18T06:19:05.544Z'
'updatedAt': '2018-05-02T12:44:19.801Z'
'type': 'MARKDOWN_NOTE'
'folder': 'c0beb159f2b71c11de80'
'title': 'Métaphysique moderne'
'content': '# Métaphysique moderne\n\n*L\'expérience chez Kant et Hegel*\n\n## 1. L\'expérience comme problème philosophique\n\n'
'tags': []
'isStarred': false
'isTrashed': false
```

Now I want to recover a clean .md file from this `content` field. I tried different encoding conversions but I couldn't find the right way to replace the `\n` by returns in my editor. Moreover this string contains french characters such as `é`.

Please do you have any idea?

Thanks

**Comment by ZeroX-DG** [comment]
Have you tried this feature
![image](https://user-images.githubusercontent.com/12984316/47644375-89537b00-dba0-11e8-9c23-d9018fcd8e66.png)
