### ISSUE TITLE
Amazon Cognito Indentity status 400

### ISSUE THREAD

**Issue by ri7nz** [BoostIO/Boostnote#1905]
# Current behavior
i'm use Boostnote 0.11.4 Amd64 desktop Version. i view development tools and i got an errors on console, on errors message its 400 status for send a post to congnito-identity.us-east-1.amazonaws.com
![selection_410](https://user-images.githubusercontent.com/16365952/39903187-1dc24c16-54fc-11e8-88b5-4721fdaf3027.png)

# Expected behavior
-
# Steps to reproduce
-
# Environment
- Version :  Boostnote 0.11.4 Amd64 desktop Version 
- OS Version and name : Ubuntu 16.04 LTS

**Comment by Rokt33r** [comment]
You can ignore it. We are gathering usage data of Boostnote. It seems the app is failing to send the data. If you don't want to see any more you can disable it from the preferences.

FYI: The usage data doesn't include any content of your notes. We just count your activities. And, we cannot specify who you are from it.

**Comment by ri7nz** [comment]
oh thank you for your information about that

regards.
ri7nz
