### ISSUE TITLE
Feature request: EJS syntax highlighting

### ISSUE THREAD

**Issue by danielzucchi** [BoostIO/Boostnote#1909]
Hello team!

The project is simply amazing and a life-saver! 

Not sure if it has been asked already, but the Code Snippet will recognise Embedded Javascript, but will not highlight the syntax, so it just all goes all black... Is it not implemented yet? Any plans to do it?

Thanks!

**Comment by yosmoc** [comment]
I fixed this issue. Now it renders correctly in the markdown and snippet mode.

![image](https://user-images.githubusercontent.com/9694/39962164-64ae78c4-5647-11e8-92a0-18f15cdba760.png)
![image](https://user-images.githubusercontent.com/9694/39962165-68a2947e-5647-11e8-9238-1c5188dffadb.png)

**Comment by danielzucchi** [comment]
Awesome, thank you guys!
