### ISSUE TITLE
Copying the link to an attachment should make sure that it is located in the same note folder

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#1924]
@Rokt33r  we've discussed this today: 

# Steps
1) Note 1 has an attachment
2) Copy link to the attachment (->` [attachment1](:storage/attachments/notekey/attachment1)`
3) insert it into note 2
4) delete note 1

# Expected behavior
Attachment is still available in note 2

# Current behavior
Attachment was deleted when note 1 was deleted -> it is not available anymore in note 2

**Comment by Rokt33r** [comment]
Thanks for creating this issue!!
