### ISSUE TITLE
colored emoji

### ISSUE THREAD

**Issue by koolayxt** [BoostIO/Boostnote#193]
Hello.
I can not speak English, so I will use Google Translate. I'm sorry.

I use a lot of emoji on My Boostnote. 😜
I would like to use a colored emoji.

Can Boostnote correspond to colored emoji?

**Comment by kazup01** [comment]
No problem! Thank you for your message👏
Ok, we will consider it.
Would you tell me to what kind of use emoji is used?

**Comment by asmsuechan** [comment]
How about this? If it's ok, please close this. I'll close this in under 3 days unless you react.
