### ISSUE TITLE
Keyboard shortcut to Toggle Full Screen on macOS (Ctrl+Cmd+F) does not work

### ISSUE THREAD

**Issue by anothernode** [BoostIO/Boostnote#1930]
# Current behavior

In Boostnote 0.11.4, when pressing `Ctrl+Cmd+F`, the search input field gets focus and the Boostnote window does **not** toggle the full screen mode.

# Expected behavior

The Boostnote window should toggle the full screen mode as announced in the application menu:

![screen shot 2018-05-18 at 10 25 48](https://user-images.githubusercontent.com/3286144/40224375-455c8644-5a86-11e8-83a3-d0296db6c986.png)

# Steps to reproduce

1. Start Boostnote 0.11.4 on macOS
2. Press Ctrl+Cmd+F on the keyboard

# Environment

- Version : 0.11.4
- OS Version and name : macOS High Sierra 10.13.4

**Comment by yougotwill** [comment]
Hey @anothernode, this has been fixed here https://github.com/BoostIO/Boostnote/pull/1754 :)

**Comment by anothernode** [comment]
Awesome!! And sorry for the noise then. I did search for open issues on this, but not for PRs... 😬
