### ISSUE TITLE
Unavailable storage locations prevents application from working at all

### ISSUE THREAD

**Issue by jk3us** [BoostIO/Boostnote#1934]
# Current behavior

If you start Boostnote and one of your storage locations is unavailable the application hangs on start and doesn't show you any of your notes or storage locations. In my case, I have one on a shared network drive and another on Google File Stream, but if I don't have Google file stream running, it just spins on startup:

![image](https://user-images.githubusercontent.com/41621/40253247-ba1a51aa-5aa4-11e8-894a-6bf596c4739f.png)

and the preferences/storage screen doesn't show any of your storage locations:

![image](https://user-images.githubusercontent.com/41621/40253298-db0de408-5aa4-11e8-8496-891c8d8ac504.png)

# Expected behavior

At least throw up an error that says "Some of your storage locations are unavailable".  But even better would be to still let me use the locations that *are* available and indicate any unavailable ones in some way. 

# Steps to reproduce

1. Add 2 storage locations, one of them being a google drive file stream mount.
2. Disable google file stream
3. Start Boostnote. (Looks like screenshots above)
4. (If you try to add any storage locations, they don't show up.  If you add one that is really already there, you get duplicates after the next step that I can't seem to unlink(see screenshot below) (Edit: unlinked storages do go away, but only after you close the preferences window)
5. (Enable google file stream and restart Boostnote, now everything works as expected again)

![image](https://user-images.githubusercontent.com/41621/40253592-f4803eb2-5aa5-11e8-92b4-d1bbe4804cab.png)

# Environment

- Version : 0.11.4
- OS Version and name : Win 7

This might be related to #1871

**Comment by jk3us** [comment]
Because Google File Stream apparently changes it's drive letter willy nilly, I had to go into the storage sqlite file/db and change the drive letter for my Google Drive's storage location for boostnote to even open.  It would be better if it just opened with that location unavailable.

**Comment by Flexo013** [comment]
@jk3us Is this still a problem?

**Comment by Flexo013** [comment]
Due to the lack of activity in this thread I'm going to assume this issue no longer occurs in the latest versions.
