### ISSUE TITLE
I met a bug about link tag

### ISSUE THREAD

**Issue by littledavid-tech** [BoostIO/Boostnote#1937]
# Current behavior
I met a bug,  
When I was writing a markdon file and create a link tag then clickl it , there are a web page `Preview Area`.
I tried to close the web page but I cannot do it.

# Expected behavior
I hope when I click a link tag It will be opend in my browser.
# Steps to reproduce

1.  Create a new markdown 
2.  Write a link tag such as [BaiDu](http:baidu.com)
3. Click it

# Environment

- Version : Boostnote 0.11.4
- OS Version and name : Win10

**Comment by bimlas** [comment]
It's already reported: https://github.com/BoostIO/Boostnote/issues/1878

PS.: Please write more descriptive title in the future, for example "Link tag opens web page in preview area".

**Comment by ZeroX-DG** [comment]
Closed as fixed https://github.com/BoostIO/Boostnote/pull/1858
