### ISSUE TITLE
No image icon when you drag and drop images from file explorer onto a note (Low Priority Bug)

### ISSUE THREAD

**Issue by DaniGithub** [BoostIO/Boostnote#1938]
# Current behavior
When I drag & drop an image from the explorer window onto a note i get a missing image icon in the preview window. 😕

Two ways to fix this:
- Press enter after dropping the image. 
- Remove and re-insert the first slash from the file path in the markdown. 

![bugreport](https://user-images.githubusercontent.com/9342005/40279418-8d91562a-5c42-11e8-8e9c-ecac58512723.png)

# Expected behavior
The image to become visible as soon as I release the LMB when dropping the image onto a note. 😊

# Steps to reproduce

1. Open file explorer and Boostnote
2. In file explorer find an image file
3. Create a new note in Boostnote
4. Drag the file from the explorer to the edit area in Boostnote and release. 

# Environment

- Version : 0.11.5
- OS Version and name : Windows 10 Version 1803 build 17134.48

**Comment by ehhc** [comment]
@DaniGithub is this still an issue in the newest version? Could you close it otherwise?
