### ISSUE TITLE
Change order of storage folders

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#194]
It would be nice to be able to filter and change the order for the Storage and respective folders in left pane, With a lot of notebooks, sometimes is hard to quickly find what I want.

**Comment by kazup01** [comment]
Oh, I see. It's good idea! I agree with you.

**Comment by kazup01** [comment]
Sorry for delay in reporting @brpaz san! @sosukesuzuki added it on #396 . We will add it at next update!

**Comment by zhangxintao** [comment]
Had it been released?
