### ISSUE TITLE
Missing Ctrl+S save and toggle preview mode and ctrl+f for filtering

### ISSUE THREAD

**Issue by fornous** [BoostIO/Boostnote#1947]
# Current behavior
Ctrl+s while editing doesn't make anything. 
Ctrl+f doesn't focus on filter

# Expected behavior
Ctrl+s toggle preview mode and save the article
Ctrl+f focuses on filter input

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 11.5
- OS Version and name : Windows 10 April Update

**Comment by Flexo013** [comment]
There is no need for explicit saving in Boostnote, as your notes are constantly saved.

Ctrl+F does work.
