### ISSUE TITLE
Pasting a link doesn't update cursor position

### ISSUE THREAD

**Issue by davidwolfpaw** [BoostIO/Boostnote#1950]
Boostnote v0.11.5
MacOS v10.13.4

When I paste a link into Boostnote the cursor advances to the end of the pasted text. Boostnote then creates a markdown link with the title of the page that was linked.

The cursor does not update position to be at the end of the newly created link, and instead stays in the position of after paste but before markdown creation.

Expected behavior is that the cursor would auto-advance, to allow easier continuation of typing after a link.

**Comment by ZeroX-DG** [comment]
Fixed in the latest version
