### ISSUE TITLE
Default to sync storage on mobile

### ISSUE THREAD

**Issue by davidwolfpaw** [BoostIO/Boostnote#1957]
It would be great to be able to default to opening a sync storage folder on mobile, like Dropbox, instead of starting at All Notes.

Additionally, a cache of notes, or at least the metadata of those posts (title, excerpt, date) stored on the mobile device would be even better, so there's no need to wait for it to pull files that have already been pulled up last time the app was open on mobile.

The issue currently is that I open the mobile app, have to navigate to Dropbox, then have to wait for it to load all notes before searching through or accessing them.

**Comment by Flexo013** [comment]
Since there currently are no mobile apps for Boostnote I will be closing this issue.
