### ISSUE TITLE
Change titlebarstyle to hidden

### ISSUE THREAD

**Issue by OffCorner** [BoostIO/Boostnote#1958]
# Current View:

![image](https://user-images.githubusercontent.com/7747779/40429017-e3ffa15e-5ea1-11e8-8b58-80a545e92e4b.png)

# Suggested View:

![image](https://user-images.githubusercontent.com/7747779/40428960-bf020662-5ea1-11e8-8366-1d1215aa2378.png)

# Environment

- Version : 0.11.5
- OS Version and name : Mac OS 10.13.4

# Things to add:
`  titleBarStyle: 'hidden'` in main-window.js
and additionally `-webkit-app-region: drag`

**Comment by kazup01** [comment]
#1972
