### ISSUE TITLE
ScrollBar is a Big Problem

### ISSUE THREAD

**Issue by washere** [BoostIO/Boostnote#1961]
**The ScrollBar shows for a few seconds.**

**Then fades away and DISAPPEARS.**

Clicking under it does not really pull page down.

YOU HAVE TO quickly click and hold and drag it while it is fading away.

If you miss the few seconds to catch it, it is impossible.

This is very bad.

**1) ScrollBar  should STAY VISIBLE.**

**2) Scrollbar should go UP or DOWN if we click under or on top of it.**

In preferences is even worse. PageUp & PageDown (or arrow keys) do not work in Preferences (they work in editor/preview).

**BUT MAIN PROBLEM IS IN EDITOR/PREVIEW.** 
**ScrollBar  should STAY VISIBLE in Editor/Preview Windows.**

This is basic for any editor, please fix it.

Thanks.

**Comment by LouWii** [comment]
This is interesting, I didn't understand why this was an issue. Until I realized that yeah, it's annoying if you don't have a scroll wheel or whatever scrolling gesture on a trackpad.
I wonder how many people use scrollbars as their main way of scrolling though.

**Comment by OnlineVagrant** [comment]
i would not like the scroll bar to be visible all the time. I find it a bit distracting. Maybe it should be feature that can be toggled on or off. or maybe appear when hovering the cursor near the edges of the editor/preview windows. Besides, they also appear when scrolling with your fingers or arrow keys.

**Comment by ZeroX-DG** [comment]
Fixed in the latest version
