### ISSUE TITLE
Boostnote freezes

### ISSUE THREAD

**Issue by ghost** [BoostIO/Boostnote#1973]
# Frozen

On start up, boostnote freezes at the loading page. Does not close. Had to killall the process. Uninstalled and reinstalled and problem remains. What should i do?

# Environment

- Version :0.11.4
- OS Version and name :Ubuntu 17.10

**Comment by martinsbruveris** [comment]
I have the same problem since yesterday.
Version: 0.11.4-1
OS: Ubuntu 18.04

**Comment by flugzeit** [comment]
I have been having the same problem. Boostnote freezes when loading and requires killall to halt.

If I delete `~$ home/username/Boostnote` the program will launch successfully. Copying the existing .rm files back into the new `notes` directory, or even recreating them as new notes using the existing markdown text, causes Boostnote to freeze on the next launch.

Output from apport.log:
```ERROR: apport (pid 9225) Thu Jun  7 11:47:38 2018: called for pid 9201, signal 6, core limit 0, dump mode 1
ERROR: apport (pid 9225) Thu Jun  7 11:47:38 2018: executable: /usr/share/boostnote/Boostnote (command line "/usr/share/boostnote/Boostnote\ --type=renderer\ --no-sandbox\ --primordial-pipe-token=BC2EA321E8B3BA0124D79298F71DCBE0\ --lang=en-GB\ --app-path=/usr/share/boostnote/resources/app\ --node-integration=true\ --webview-tag=true\ --no-sandbox\ --enable-blink-features=OverlayScrollbars\ --enable-pinch\ --num-raster-threads=1\ --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553\ --disable-accelerated-video-decode\ --disable-webrtc-hw-vp8-encoding\ --disable-gpu-compositing\ --service-request-channel-token=BC2EA321E8B3BA0124D79298F71DCBE0\ --renderer-client-id=3\ --shared-files=v8_natives_data:100,v8_snapshot_data:101")
ERROR: apport (pid 9225) Thu Jun  7 11:47:38 2018: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 9225) Thu Jun  7 11:47:38 2018: this executable already crashed 2 times, ignoring
```

Boostnote Version: 0.11.5 (installed via .deb)
OS: Linux Mint 18.3 Cinnamon 64-bit

**Comment by VasilikiS** [comment]
So, ps aux | grep note, then kill -9 for all processes related to Boostnote. Then in your config directory you will find the file Boostnote. Rename it, for example call it Boostnote_off. Then reboot your ubuntu and then Boostnote should be working fine. It will create a new Boostnote file inside the config directory. Your old markdowns and and snipets will be found as Unknown, but that's ok, you can rename them. To be safe, i backed up my notes in another drive. 

Let me know if it worked.

**Comment by flugzeit** [comment]
> So, ps aux | grep note, then kill -9 for all processes related to Boostnote. Then in your config directory you will find the file Boostnote. Rename it, for example call it Boostnote_off. Then reboot your ubuntu and then Boostnote should be working fine.

This worked for me. Thanks!

**Comment by martinsbruveris** [comment]
Worked for me too. Thanks!
