### ISSUE TITLE
No folder to create a note

### ISSUE THREAD

**Issue by Texxer** [BoostIO/Boostnote#1974]
# Current behavior

No folder available to create a new note? Come on, where do you think are those notes saved. I bet not in a folder...

[https://puu.sh/AsCfe/85d0fb2e0b.png](url)

# Environment

- Version : 0.11.5
- OS Version and name : Windows 10 Home

**Comment by kazup01** [comment]
Please make at least one folder to make note.

**Comment by Texxer** [comment]
Hey, there IS a folder!

FFS, don't just close a thread when I report a BUG and HELP you.

Again, look closely at the screenshot. There are notes. Where do you think they are saved? In the air or in a folder?

Now I suggest you go to solve the issue within your code. And when you ask nicely I may even help you on that matter.

Kind Regards

**Comment by Texxer** [comment]
Don't use the link above. Copy the URL into your browser bar and it will work. I looks like this when I edit on Github: "[https://puu.sh/AsCfe/85d0fb2e0b.png](url)"

Well, yes I am angry because what's rude is making a false comment and closing an unresolved issue.

You are right, I did not pay for it, and I could simplay delete it. But since I honor good software I decided to keep the installation and play the beta tester in my free time.

**Comment by ehhc** [comment]
@Texxer could you test what happens when you explicitly click on the folder before trying to create the note? I think the problem is that the folder is deselected and the software therefore thinks there is no one to create the note in...

**Comment by Texxer** [comment]
Sure. May I ask where I should click on that folder? I don't see any folder icon or folder path.

**Comment by ehhc** [comment]
@Texxer the folder i ask you to click on is (1) in the image ("here")
btw: i think the problem is that in your default storage, no folder is available (marked with 2 in the image)

you should ask yourself, why you've included a storage without a folder at all.. maybe this storage isn't needed and you could delete it (in preferences -> storage -> unlink (i'm not sure about the wording at the moment, but you'll find it :) )).. but that's just a suggestion.. 

![image](https://user-images.githubusercontent.com/10086873/40613801-508b1f88-6280-11e8-9dae-1345792218db.png)

**Comment by Texxer** [comment]
That works indeed. Although the selected folder is not highlighted. Maybe something for the developers?

I tried your suggestion about removing My Storage since I only use Cloud Folders. Currently it's not possible to unlink My Storage. Maybe also something for the devs!

Thank you ehhc!

**Comment by ehhc** [comment]
What is the problem with removing storage marked with "2" in the image? Do you get an error? Is there a error in the development console (open it by clicking view developer console (or something similar) in the menu of the program (I think it is a sub item of "view") (I hope you know what I mean)..?

**Comment by ehhc** [comment]
Hm.. That's definitely a bug.. Maybe you could try to create a folder in that storage and then try to unlink it?
Maybe the problem is that it does not contain a folder.. But that's just a guess..
