### ISSUE TITLE
Text expansion Features 

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#1978]
Please add multiple cursor positions within a template, for example

```
this is a new templete

\frac{ :{1} }{ :{2} }

this is the end of the new templete 
:{0}
```

where **:{1}** and **:{2}** represent the first and second cursor position while **:{0}** represents the final cursor position.

It would also be nice to have a description at the cursor position after expansion that gets replaced once you start typing at that cursor position. For example,

```
this is a new templete

\frac{ :{1;Numerator} }{ :{2:Denominator} }

this is the end of the new templete 
:{0}
```

where **:{1;Numerator}** represents the first cursor location with the description text "Numerator" that gets replaced once typing begins at that cursor location.

Finally moving back and forth from defined cursor positions would be awesome.

Here is a video of [Ultisnips](http://vimcasts.org/episodes/meet-ultisnips/) that has these features

**Comment by ZeroX-DG** [comment]
The issue is funded in https://github.com/BoostIO/Boostnote/issues/2084
