### ISSUE TITLE
after latest upgrade all my picture links are broken.

### ISSUE THREAD

**Issue by dogfish182** [BoostIO/Boostnote#1988]
# Current behavior

for some reason after upgrade all the pictures are referencing an 'attachments' directory. this directory is empty and all images are stored in an images directory. 

I guess I can manually move them back, but this seems worth reporting.

![image](https://user-images.githubusercontent.com/5390419/40583415-6ef88034-618e-11e8-9612-b5233196ff69.png)

all the broken links refer to the 'attachments' path
![image](https://user-images.githubusercontent.com/5390419/40583421-8ba7aeb2-618e-11e8-9664-b2189a95a1b9.png)

but all images are contained now under the 'images' dir.

I see this running all through developer mode as well

Attachment folder ('/Users/me/onedrive/OneDrive -Me/Boostnote/attachments/76e76858-f85a-4075-866a-712bafefe06d') did not exist..

# Expected behavior
pictures should work after upgrade
# Steps to reproduce
upgrade to 11.5. have broken images.

# Environment

- Version : 0.11.5
- OS Version and name : MacOS high sierra

**Comment by davidmigloz** [comment]
And it is using absolute paths for the new images, making the notes device dependent... E.g:
```
![af334fc8.png](/Users/xxx/Dropbox/Aplicaciones/boostnote-mobile/attachments/47733c82-f357-4a51-954f-561c56cd2353/af334fc8.png)
```

**Comment by ehhc** [comment]
hi, i fear it is my fault. I explained the problem here: https://github.com/BoostIO/Boostnote/issues/1941#issuecomment-390644169
I am very sorry for the problems i caused.. i've already submitted a PR that hopefully fixes the problem, but it can't be released before the next version (in 2-3 weeks,,,).

as a current workaround: if you rename the folder "images" at your boostnote storage location to "attachments" it might work again (see the comment linked above for the explanation)

**Comment by dogfish182** [comment]
so after the latest updates all new pictures are working but all previous ones are still broken. 

all broken pages have a double 

file://file:// 

reference. is this a fixable thing or must I just forget about the screenshots?

**Comment by XarisA** [comment]
@ZeroX-DG I have the same problem. After upgrading to 0.11.13 all image links are broken.
Even when trying to add a new image, preview not working.

![error](https://user-images.githubusercontent.com/3985557/51788132-46934600-2183-11e9-8de6-b6fb506d17db.png)


Steps to reproduce
---
Upgrade to latest version and check image preview or try to add a new image.

Enviroment
---
- Windows 10 
- Bostnote 0.11.13

**Comment by payacoub** [comment]
Same problem as @XarisA ; any image paste turns as a broken image (still visible in folder though)
