### ISSUE TITLE
Bring back folder selection in note

### ISSUE THREAD

**Issue by hotmaskim** [BoostIO/Boostnote#199]
Hello,

I use your app everyday and I change my note folder during its lifetime (todo then done for example...).
With the new version, you removed this feature...

Could you bring it back ?

Thanks for your work by the way ;)

**Comment by kazup01** [comment]
Hi hotmaskim san
Thank you for using!
Yeah, we will add it next version.
I'm sorry to inconvenient :(

**Comment by hotmaskim** [comment]
:)
No problem, thank you for your answer.
