### ISSUE TITLE
the color of code block in single line has changed to gray

### ISSUE THREAD

**Issue by yangsijie666** [BoostIO/Boostnote#1994]
# Current behavior

![default](https://user-images.githubusercontent.com/26850324/40634559-31adec8c-6328-11e8-8d67-18cd3f00498d.png)

Hi, team!
In the latest version, it seems that the color of code block in single line has been changed to gray, which is difficult to be noticed, and it also loses the 'emphasis' effect. I suggest that you change its color back to red or any easily noticeable color.

# Expected behavior

![default](https://user-images.githubusercontent.com/26850324/40634600-6f0b8aee-6328-11e8-9e89-a43be4900cb8.png)

# Environment

- Version :0.11.5
- OS Version and name :Windows10

**Comment by roroyu** [comment]
me too
os: mac
I check it 2 hours

**Comment by Flexo013** [comment]
This is the same issue as mentioned in #2373. I'm closing this one and leaving that one open since it has more discussion.
