### ISSUE TITLE
Is it possible to create tables without headers?

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#1999]
Sometimes I would like to create tables that do not  require headers. In such instances is it possible to create a table without a header?

# Current behavior
The first row of the table is bold even though it isn't a header.
![non header](https://user-images.githubusercontent.com/39413259/40655221-106e2bd8-6317-11e8-9be7-3ad246095963.JPG)

I can omit the header by doing the following, but the table looks incomplete.

![no top border](https://user-images.githubusercontent.com/39413259/40655350-74df94d0-6317-11e8-8ed2-c48510052baf.JPG)

# Expected behavior
![no top border](https://user-images.githubusercontent.com/39413259/40655486-da577774-6317-11e8-91cb-0585c00c7611.JPG)

**Comment by yosmoc** [comment]
Hi @OnlineVagrant ,

No, because this project currently uses markdown-it, and markdown-it's default table doesn't support this format. https://github.com/markdown-it/markdown-it/issues/231

**Comment by OnlineVagrant** [comment]
Thank you for responding.
