### ISSUE TITLE
[FeatureRequest][Questions] Start thirdparty applications with boostnote

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#2000]
It would be nice to be able to start third party applications alongside boostnote automatically.
That would enable to start e.g. a local PLANTUML Server to be started and used from boostnote.

Idea:
- define a path to the application that should be started and the startup parameters in the preferences
- execute the defined application on startup 

What do you think about that?

**Comment by ehhc** [comment]
How can we do that? There is no plugin mechanism implemented as far as I know..

**Comment by bimlas** [comment]
I think it's an overkill: Why don't you creating a shell script / Windows .bat file for it? For example this will start `calc.exe` and Boostnote in paralell:

boost.bat
```
start calc.exe
start %LOCALAPPDATA%\boost\Boostnote.exe
```

**Comment by Flexo013** [comment]
Agreeing with @bimlas here. This is not really a feature that Boostnote needs to support, but the user can use (shell/batch) scripts to launch Boostnote and everything it would like to launch alongside it.
