### ISSUE TITLE
Show thirdparty folders and notes through proxy service

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#2001]
It would be nice to be able to show third party notes and folders through a proxy service.
Idea:
- start a proxy service at localhost at a defined port (might be done through #2000)
- let the proxy service implement a predefined API (via REST)
- Query and display the notes / folders from the service

Then the acutal services could be implemented independently 

Thoughts?

**Comment by Flexo013** [comment]
@ehhc I feel like this is two separate features:

- Display rendered versions of Boostnote notes through a proxy.
- Display other notes through the same proxy.

Or am I misunderstanding your request?

**Comment by ehhc** [comment]
It's a long time ago since i wrote this issue. I don't think it will ever implemented nor am i convinced anymore that it is worth the effort. I'll close the issue therefore
