### ISSUE TITLE
[Bug] Clicking on a link to a local file (attachment) does not open it

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#2003]
... instead nothing happens.. 
there is even no error in the development console!

I am quite sure that it already worked..
I think there was a bug with URL clicking, am i right?
I think who ever fixed that bug, caused *this* bug...

**Comment by ehhc** [comment]
just a guess but maybe the fix for this: https://github.com/BoostIO/Boostnote/issues/1944 caused the bug?!

has anybody an idea what's the problem? 
@Rokt33r ?

**Comment by ehhc** [comment]
@yosmoc thanks for your quick fix. But I think it's not yet complete.. There are still other applications I would like to access by clicking a link (e.g. There is an literature management software called zotero which I referenced from within my notes. The links start with 'zotero://').

Maybe it would be possible to define a kind of white list of link prefixes that I can allow to be executed with the shell?? 
I would suggest to store this in the preferences but *not* to expose it in the ui.. Then everybody is able to change his withe list manually (by editing the preference file with text editor) without giving people without technical knowledge the opportunity to do something stupid or harmful... 

What do you guys think about that idea? 
Could you implement that?

**Comment by yosmoc** [comment]
@ehhc I see your problem. Probably I can solve this issue without having prefix setting. Because what we need to check here is that the link has the url scheme pattern or not.

**Comment by ehhc** [comment]
@yosmoc thanks :) looking forward to seeing your solution :)

**Comment by yosmoc** [comment]
Hi @ehhc,

I thought about security things, What we can check here is only url string, we cannot check the file itself. So even If we have the white list / black list, we cannot prevent to open the malware perfectly.

I cannot find other good solution, so I just re-support the local file link handling that we have before #1944.

**Comment by Rokt33r** [comment]
Fixed!
