### ISSUE TITLE
Multi-tabs support for opened notes

### ISSUE THREAD

**Issue by louiealmeda** [BoostIO/Boostnote#2005]
Being able to link a documents from another document is a great feature!
It will be great if we will have the option to go back to the previous page after we are redirected to another document :)

**Comment by OnlineVagrant** [comment]
The problem with having a link back occurs when you have more than one note linked to the same note. The linked note would require a list of links back to each note. It isn't intuitive to have a list of links in a note just for the purpose of getting back to other notes. However if feature request #1364 is implemented then a link back wouldn't be required.

In this case the link could open the linked note to the right in a side by side view. In which case closing the linked note restores the current note mode state(whether preview mode or split screen mode)

![777](https://user-images.githubusercontent.com/39413259/40718275-d27c218e-63e5-11e8-9988-6c8b4577eb4c.JPG)


![1](https://user-images.githubusercontent.com/39413259/40718069-10773682-63e5-11e8-8e8e-b5b2122382aa.JPG)

**Comment by louiealmeda** [comment]
Good point. Then probably supporting multiple opened notes via tab would be the way to go. Since it is  how code editors normally work.

![2018-05-31 06 18 07](https://user-images.githubusercontent.com/5992303/40750608-6c88e01e-649a-11e8-95c0-647572cf0db7.gif)

**Comment by Flexo013** [comment]
In the latest version of Boostnote you can link notes internally by clicking the 'i' in the top right corner. Then copy the link from there and add it to any note.

As for going back easily you can also add a link for that, or another solution is suggested in #1001
