### ISSUE TITLE
Can't copy paste screenshot in boostnote

### ISSUE THREAD

**Issue by safwanmasarik** [BoostIO/Boostnote#2006]
# Current behavior

# Expected behavior

# Steps to reproduce

1.  Screenshot piece of screen using Snipping Tool or Lightshot or Printscreen. 
2.  Copy and paste it inside Boostnote markdown note.
3.  Image should appear in note(preview mode) but its NOT. 

# Environment

- Version : latest update 25/05/2018
- OS Version and name : Windows 10 64-bit

**Comment by ehhc** [comment]
I'm sorry for that. I hope it will be fixed in the next release. See https://github.com/BoostIO/Boostnote/issues/1953#issuecomment-391605046

**Comment by sosukesuzuki** [comment]
Maybe, This issue is fixed by #1949
