### ISSUE TITLE
Delete sub-tab of snnipet don't work.

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#201]
![jan-04-0029 14-24-45](https://cloud.githubusercontent.com/assets/8602615/21633158/05c8cc74-d290-11e6-84c3-c507b3e9263e.gif)

Delete sub-tab of snnipet don't work after v0.8.0 .

**Comment by asmsuechan** [comment]
I checked this, snippet could not be deleted at least from v7.0.0 in my local environment. Really does it occur from v0.8.0?

**Comment by asmsuechan** [comment]
Hi there! This issue is fixed by @sosukesuzuki in https://github.com/BoostIO/Boostnote/pull/322!

**Comment by kazup01** [comment]
Great work, @sosukesuzuki 🎉
