### ISSUE TITLE
Pasted screenshots deleted when note dragged to other folder 

### ISSUE THREAD

**Issue by remyhonig** [BoostIO/Boostnote#2012]
# Current behavior

Images are deleted when notes are dragged to other folders. 

# Expected behavior

Images are not deleted

# Steps to reproduce

1. Create note
2. Insert screenshot from clipboard (ctrl-v) and press enter
3. Drag note to other folder

# Environment

- Version : 0.11.4
- OS Version and name : Opensuse Tumbleweed

**Comment by ehhc** [comment]
i'm sorry for that. it will hopefully be fixed in the next release. See https://github.com/BoostIO/Boostnote/issues/1953#issuecomment-391605046

**Comment by sosukesuzuki** [comment]
Maybe, this issue is fixed by #1949
