### ISSUE TITLE
Horizontal line markup error

### ISSUE THREAD

**Issue by Texxer** [BoostIO/Boostnote#2028]
# Current behavior

[Screenshot](https://puu.sh/AySo3/6d67deb2f2.png)

--- increases size and thickness of previous text

# Expected behavior

--- should create a horizontal line

# Environment

- Version : 0.11.5
- OS Version and name : Windows 10 Home

**Comment by sosukesuzuki** [comment]
We use `markdown-it` to render markdown.
Your saying is behavior of `markdown-it`.
(This image is taken in https://markdown-it.github.io/)
Perhaps it would be better to create this Issue on [markdown-it](https://github.com/markdown-it/markdown-it).
<img width="1152" alt="2018-06-05 17 36 02" src="https://user-images.githubusercontent.com/14838850/40964782-f06d0b80-68e6-11e8-88ad-ead958fab819.png">

**Comment by Texxer** [comment]
true, thanks for the hint. I posted it to markdown-it repo issues.
