### ISSUE TITLE
Export as HTML not possible

### ISSUE THREAD

**Issue by Texxer** [BoostIO/Boostnote#2029]
# Current behavior

File > Export as > HTML

Will not create a new HTML file. No error is displayed.

File > Export as > Anything else

Will create a new file. Success confirmation dialog pops up.

# Expected behavior

Export as HTML is possible.

# Environment

- Version : 0.11.5
- OS Version and name : Windows 10 Home

**Comment by pmood** [comment]
Disclaimer: have not verified the bug, but just as a workaround in the meantime, anyone who needs this feature right now can go to `view` > `Toggle Developer Tools`, then go to the `Elements` tab and copy from there and save it as an html file.

**Comment by Texxer** [comment]
Saves your way around a converter. Thank you for the hint pmood.

**Comment by thedavidgay** [comment]
Looks like the same issue as #1948.

I also have this issue in macOS High Sierra 10.13.4. Boostnote version 0.11.5.

**Comment by philippvarga** [comment]
Seems like a problem on current version. I have the issue as well.
- Version: 0.11.5
- OS Version and name: Microsoft Windows 10 Education

@pmood workaround worked fine for me
