### ISSUE TITLE
search word can not Highlight。

### ISSUE THREAD

**Issue by fanrongqitiancai** [BoostIO/Boostnote#2032]
# Current behavior
if I search word like "Windows" , it can not show me  the result like this：
![image](https://user-images.githubusercontent.com/9015263/40970418-1ce963ec-68ed-11e8-9b15-4a1a60ec153f.png)

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name : windows 7

**Comment by kzumu** [comment]
I want this function too.

**Comment by Flexo013** [comment]
This feature exists in the latest version of Boostnote. Simply press Ctrl+F.
