### ISSUE TITLE
Boost note suddenly stopped working with Dropbox

### ISSUE THREAD

**Issue by corroded** [BoostIO/Boostnote#2034]
# Current behavior

Notes not loading even after linking back using dropbox

![image](https://user-images.githubusercontent.com/46548/40995909-0f10245e-6933-11e8-943b-38278a538782.png)

After adding the 'Unnamed' folder from dropbox

![image](https://user-images.githubusercontent.com/46548/40995974-406e65f6-6933-11e8-95e1-6bbc7487f17e.png)

# Expected behavior

Should list all my previous notes

# Steps to reproduce

Not sure if connected, but the last thing I did was to load my notes via mobile (same dropbox folder). Then everything stopped working.

1. Load notes via mobile
2. Go to desktop app and try to use it
3. Should not see notes
4. Reinstalled with latest version of Desktop app
5. Still no notes

# Environment

- Version : 0.11.5
- OS Version and name : OSX El Capitan 10.11.6

**Comment by corroded** [comment]
I guess we can have a guard clause for when the `tags` is not included in the notes? I would assume that this happened somehow from my mobile app or something. Not sure how to replicate a note with no tags and just blank content, but maybe just a guard clause like

```
if (note == undefined || note.tags == undefined) // pseudocode  {
  return
} 

note.tags.forEach ....
```

just a suggestion. I don't have much knowledge with Electron to make a PR for this.

**Comment by sunggun-yu** [comment]
Thank you @corroded!

**Comment by Flexo013** [comment]
The current version of Boostnote seems to work with Dropbox.

Please feel free to reopen this issue if you are still experiencing it.
