### ISSUE TITLE
Midnight Theme for other editors.

### ISSUE THREAD

**Issue by TonyLancer** [BoostIO/Boostnote#2035]
What is the full name of the "Midnight" theme used in BoostNote? I would like to use this theme for my Visual Studio Code and other editors that I use

**Comment by yosmoc** [comment]
@TonyLancer This theme is come from Codemirror.
https://github.com/codemirror/CodeMirror/blob/master/theme/midnight.css
Full name is unfortunately "Midnight". As you can see in the source code above link, this theme is based on http://bonsaiden.github.io/JavaScript-Garden/ .
I don't know this color theme is available in vscode marketplace. Good luck for hunting this theme!

**Comment by sosukesuzuki** [comment]
Sorry, I think this issue has nothing to do with Boostnote.
I'll close.
