### ISSUE TITLE
can not search fulltxt and Highlight the result

### ISSUE THREAD

**Issue by fanrongqitiancai** [BoostIO/Boostnote#2036]
# Current behavior
can not search fulltxt and Highlight the result

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by zhuzelong** [comment]
Please add fulltext search in the note window.

**Comment by Flexo013** [comment]
This feature exist in the latest version of Boostnote. Simply press Ctrl+F.
