### ISSUE TITLE
edit mode full screen

### ISSUE THREAD

**Issue by fanrongqitiancai** [BoostIO/Boostnote#2045]
when I switch to edit mode，the note window is split screen.but I like full screen edit mode.please add the options which we can choose it by ourself. 

# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by OnlineVagrant** [comment]
You can still use full screen edit mode. After selecting full screen mode either right click or <Control> + e switches from full screen preview mode to full screen edit mode.

**Comment by fanrongqitiancai** [comment]
![image](https://user-images.githubusercontent.com/9015263/41144058-21f2f586-6b2e-11e8-97d2-29a58a93e327.png)
can not use full screen edit mode.

**Comment by Rokt33r** [comment]
@fanrongqitiancai You can the switch timing from the preferences(Preferences->Interface).

**Comment by fanrongqitiancai** [comment]
thank you very much！
