### ISSUE TITLE
[Feature Request] Support for disabling incremental search

### ISSUE THREAD

**Issue by ymm1x** [BoostIO/Boostnote#2046]
When there are many notes in Boostnote, the response of the search result is slow.
Because full scan of all notes occurs every time a search word input.
Disabling incremental searching and searching by pressing the Enter key will improve search UX.

**Comment by Rokt33r** [comment]
It is already reported. And, I'm going to make it throttling. Anyway, thanks for the reporting! 💯

**Comment by romerosms** [comment]
@Rokt33r If I may add, the idea of ymm1x is good in terms of the user experience, besides any performance effect. Even if the performance is good, it's a bit overwhelming for so many things to change with every single letter one types.

**Comment by Rokt33r** [comment]
@romerosms As I said, It can be fixed by **throttling**.
https://css-tricks.com/debouncing-throttling-explained-examples/#article-header-id-5

**Comment by ymm1x** [comment]
After updating to v0.11.6 in my environment, search performance has improved greatly! 🚀
I have no problem with this issue anymore. thank you.
