### ISSUE TITLE
[Bugs] Boostnote doesn't work on electron v2.0.2

### ISSUE THREAD

**Issue by axionl** [BoostIO/Boostnote#2049]
# Current behavior

Boostnote doesn't work on the latest electron and stay on the loading page.

And there's no any information output on the console.

![image](https://user-images.githubusercontent.com/8396456/41162596-f182a3ac-6b68-11e8-943c-ff1ff60cdab8.png)

# Expected behavior

# Steps to reproduce

1.  Get the latest electron.
2.  Run boostnote

# Environment

- Version :
  - electron 2.0.2-1
  - boostnote 0.11.4-1
  - nodejs 10.4.0-1

- OS Version and name :

  - Arch Linux Latest (Testing)

**Comment by edgar2sbh** [comment]
Maybe related #1862

**Comment by axionl** [comment]
It works for a while, after patching.

[AUR patch](https://aur.archlinux.org/cgit/aur.git/tree/electron-v2-compatibility.patch?h=boostnote)
