### ISSUE TITLE
A bug? Click the link then I have to view the page within Boostnote

### ISSUE THREAD

**Issue by CicoZhang** [BoostIO/Boostnote#2050]
# Current behavior
Click the link then I have to view the page within Boostnote.
![image](https://user-images.githubusercontent.com/11710225/41164940-a68319e4-6b3c-11e8-96a4-9591d24a90a3.png)

# Expected behavior

Click the link, then I can view the page in Chrome; as long as it is beyond the window of Boostnote.

# Environment

- Version : 0.11.4
- OS Version and name : Ubuntu 18.04

**Comment by yosmoc** [comment]
@CicoZhang Please update to 0.11.5. It has already been fixed. You can see another bug #2021, but this behaviour also fixed in the master branch, will be included in the next version 0.11.6.

**Comment by CicoZhang** [comment]
@yosmoc Thank you for the reply. Great to hear that it will be fixed in 0.11.6. However, I did not know there is a version 0.11.5, because I did not find this version from https://github.com/BoostIO/Boostnote/releases. How can I reliably get the notification of the new release?

**Comment by yosmoc** [comment]
@CicoZhang You can find the latest version from https://github.com/BoostIO/boost-releases/releases.
