### ISSUE TITLE
Boostnote doesn't render spaces properly 

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#2052]
When creating tables it is always impossible to have the `|` characters line up properly in the edit window.
# Current behaviour

![render](https://user-images.githubusercontent.com/39413259/41188572-e0d59a14-6b95-11e8-9b58-f55b851c6e45.JPG)

# Environment

- Version :0.11.5
- OS Version and name :Windows 10

**Comment by Rokt33r** [comment]
@OnlineVagrant You should use a mono-spaced font to achieve it!

**Comment by Rokt33r** [comment]
Like Consolas.
https://en.wikipedia.org/wiki/Consolas

**Comment by OnlineVagrant** [comment]
Thank you!!
