### ISSUE TITLE
Ability to attach a date or date range to a note and a calendar view to see my notes on a timeline

### ISSUE THREAD

**Issue by mikeparisstuff** [BoostIO/Boostnote#2061]
# Current behavior

Currently notes are ordered by their creation date and can have tags assigned to them. 

# Expected behavior

I use boostnote for a lot of daily note taking and I will often recall things based on when i thought about it. It would be nice to be able to attach a date or a date range to a note and then be able to visualize my notes on a timeline/calendar. It would be cool if the calendar showed the note's tags as well so i could have a birds eye view of what I was working on when. Date ranges would be useful for another workflow where I will have a single note that is tracking a long-term project or work item. In these cases it would be nice to be able to tag that note with the range of its life and then having the calendar be a simple way to jump to it.

**Comment by Rokt33r** [comment]
Yea, this is out of range. This must be provided as a plug-in. But, I like this feature. Could you join our slack?

**Comment by mikeparisstuff** [comment]
Any resources on how to contribute/build plug-ins? I may have a few hours one of these days to give it a go.

**Comment by Flexo013** [comment]
Currently I don't think there is a way to make plugins. On top of that there are many other features and bugs that would have priority over adding plugin support. So I don't expect to this calendar feature any time soon.
