### ISSUE TITLE
File List Flickering While Searching

### ISSUE THREAD

**Issue by romerosms** [BoostIO/Boostnote#2063]
# Current behavior

The file list is currently flickering when you are trying to search for something. Every single letter you type in the search box causes flicker for those areas. 

# Expected behavior

# Steps to reproduce

1. Search something.
2. See the file list blink

# Environment

- Version : Latest
- OS Version and name : Ubuntu Linux 18

**Comment by sosukesuzuki** [comment]
@romerosms This issue is resolved by #2065 !
