### ISSUE TITLE
Table of Contents Links are Case Sensitive

### ISSUE THREAD

**Issue by ndbeals** [BoostIO/Boostnote#2067]
# Current behavior

Currently, when using a table of Contents (auto generated in another tool, as Boostnote doesn't have this feature yet), the links to the headings must be capitalized the same as the headings themselves are.

![Demonstration](https://media.giphy.com/media/2wVDIBhAOjcAMVF7UM/giphy.gif)

# Expected behavior
When I click on a TOC heading, it'll jump me to the correct heading.

# Steps to reproduce

1. Copy + paste the following markdown into a note

``` - [Test Note](#test-note)
    - [Heading 1](#heading-1)
    - [Heading 2](#heading-2)
        - [Heading 3](#Heading-3)

# Test Note

## Heading 1

## Heading 2

### Heading 3
``` 
2. Attempt to navigate with the Table of Contents in the Preview window.

# Environment

- Version : Boostnote 0.11.5
- OS Version and name : Windows 7 Enterprise

**Comment by allejo** [comment]
I don't think this is a bug in Boostnote. [DOM IDs are generally case-sensitive](https://stackoverflow.com/a/1236864), as are URLs. The [HTML 4 spec](https://www.w3.org/TR/html4/struct/links.html#h-12.2.1) states they were case-sensitive but that's no longer the case in the HTML 5 spec.

In Chrome, if you go to a URL that has an anchor link, and change the case, it'll no longer work so that's the same behavior Boostnote displays.

**Comment by ndbeals** [comment]
Yeah, well every single other markdown table of contents generator (and program that handles them) is case insensitive. Pandoc, typora, markdown-it-toc, etc, etc, etc. 

I don't think it's all of them that're wrong and Boostnote is the only that got it right.

**Comment by MPSinclair** [comment]
> Yeah, well a bunch of other markdown table of contents generators (and programs that follow TOC's properly) are case insensitive. Pandoc, typora, markdown-it-toc, etc, etc, etc.
> 
> I don't think it's all of them that're wrong and Boostnote is the only one that got it right. Also, the [Common Mark Spec](https://spec.commonmark.org/0.28/) defines [label (and link label)](https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%5BBaR%5D%0A%0A%5Bbar%5D%3A%20%2Furl%20%22title%22%0A) matching as [case-insensitive](https://spec.commonmark.org/dingus/?text=%5BFoo%5D%5B%5D%0A%0A%5Bfoo%5D%3A%20%2Furl%20%22title%22%0A).

As the program is built in Electron (and thus wrapped around Chromium), the preview is rendered based on the HTML5 spec. It's not so much that the other content generators are case insensitive so much as it is they automatically convert the link fragments to lowercase.

**Comment by ZeroX-DG** [comment]
We now have TOC generator to take care of this: https://github.com/BoostIO/Boostnote/pull/2281

**Comment by rahulpathakgit** [comment]
I also want to add that if the heading has any part in Italics then also it does not work.
