### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by killgrey** [BoostIO/Boostnote#207]
First of all, I would like to say that I really like this app. Although it's not yet polished but I can see it's kickin ass in the future.

I like the feature of remembering the window size when I quit the app. Because everytime I open it, I have to resize it again to the way I want it. 

Thank you!

**Comment by kazup01** [comment]
Hi killgrey san,
Thank you for your message!
I want it too. We will add to the todo list.
How is the new design? Please feedback to us!

**Comment by killgrey** [comment]
Yeah I've checked your todo list and it's quite awesome! I love the UI & UX better than the old one. It's simple and clean, and most of the missing features are already in your todo list. 

One thing I want to see is I can fullscreen the editor mode or write without distraction. That's all you guys are doin great!

**Comment by sota1235** [comment]
asmsuechan implements it. So this will be released at next version.
Wait a moment please!
