### ISSUE TITLE
insert the image into boosnote can not find in the floder attachments。

### ISSUE THREAD

**Issue by fanrongqitiancai** [BoostIO/Boostnote#2071]
# Current behavior
when I use ctrl+c  ,I copy an image into the shear plate。I click  the bosnote edit ,and use ctrl+v . then I can see this:
```
![2541ff29.png](D:\Documents\booostnote\attachments\4a2fe04c-7eda-4c5e-bea8-ebf8455a9eab\2541ff29.png)
```
but when I open the floder attachments\4a2fe04c-7eda-4c5e-bea8-ebf8455a9eab I can not find the file 
2541ff29.png.
where is it?
<!- -
Please paste some **screenshots** with the **developer tool** open (console tab) when you report a bug.

If your issue is regarding boostnote mobile, move to https://github.com/BoostIO/boostnote-mobile.
-->

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by sosukesuzuki** [comment]
@fanrongqitiancai Maybe, this issue is resolved by #2002. Please wait to release next version!:+1:
