### ISSUE TITLE
Boostnote fails to start up

### ISSUE THREAD

**Issue by jonblack** [BoostIO/Boostnote#2072]
When I start boostnote the spinner icon stops spinning after about 5 seconds and the application appears to be stuck. The storage linked in boostnote is a mounted webdav partition, so perhaps this has some effect on it.

Running boostnote from the command-line revealed no messages at all and I can't find a log file anywhere. There also doesn't appear to be any verbose output or debugging options on the command line (`boostnote --help` does nothing).

To fix the issue I have to delete `Local Storage` and re-configure my preferred settings and storage links.

If you have some tips for debugging the issue please let me know and I'll take a look.

**Comment by clone1612** [comment]
What operating system are you using? For Arch Linux they moved Electron 2 to stable (which is incompatible with Boostnote) where the behaviour you describe appears. However I've already updated the package with a patch (although after your issue was created).

**Comment by jonblack** [comment]
I'm on Debian unstable.

**Comment by clone1612** [comment]
Hmm, so I would say it's Electron related. Is there an error visible on the developer tools console? You can access it with ``Ctrl+Shift+I``.

**Comment by jonblack** [comment]
The error doesn't happen all the time. Every week or so it seems to happen. Next time it occurs I'll open up the console, take a look, and report back.

**Comment by jonblack** [comment]
This is going to sound weird, but I'm going to write it anyway. After a long while the problem has happened again, and I can sort of reproduce it.

I have an ultra wide monitor (3440x1440) and use the i3 tiling window manager. When I run boostnote when no other windows are open, it takes up the entire screen. This is when it freezes. If I have one open window and start boostnote, causing it to split the screen in half vertically, the same thing happens - it freezes.

However, if I have two windows open and start boostnote, causing it to split the screen vertically in three, it works fine. Every time.

I opened a terminal and started boostnote (resulting in two windows) and saw these error messages:

```
[6231:0730/132638.957548:ERROR:gles2_cmd_decoder.cc(17518)] [.RenderWorker-0x351cba3d8c00]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6231:0730/132638.957707:ERROR:gles2_cmd_decoder.cc(16743)] [.RenderWorker-0x351cba3d8c00]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no data for level
```

I'm not sure what to make of this. It's also worth pointing out that when it freezes, I'm unable to open the developer console either. It's fully non-responsive.
