### ISSUE TITLE
Not working inline code syntax hilight.

### ISSUE THREAD

**Issue by syossan27** [BoostIO/Boostnote#208]
![2017-01-05 15 48 05](https://cloud.githubusercontent.com/assets/910446/21671373/69d34220-d35e-11e6-8cb5-39c7e91ae069.png)

![2017-01-05 15 48 20](https://cloud.githubusercontent.com/assets/910446/21671377/6c9eb17e-d35e-11e6-8330-3acc66d58a36.png)

Is the syntax highlight function of inline code deleted?

**Comment by sota1235** [comment]
Thank you for reporting.
It is probably the bug. I will check it!

**Comment by sota1235** [comment]
It's released on v0.8.3. Thank you for reporting!

**Comment by TMorville** [comment]
I have this exact issue in `0.11.8` on OSX and `0.11.9` as well. Inline code is not formatted as code.
