### ISSUE TITLE
[Feature Request] Disable Hotkeys

### ISSUE THREAD

**Issue by kobtea** [BoostIO/Boostnote#2087]
I want to disable hotkeys.

**Comment by OnlineVagrant** [comment]
Simply delete the the key combinations in the hot keys menu.

**Comment by blahah** [comment]
Just adding to what @OnlineVagrant said, the way to do that is to empty the fields and hit the save button:

<img width="603" alt="screenshot 2018-06-16 07 29 20" src="https://user-images.githubusercontent.com/836040/41496404-01d1a356-7137-11e8-936b-75ba1c3c08da.png">

**Comment by sosukesuzuki** [comment]
@kobtea Is this issue resolved?

**Comment by kobtea** [comment]
Thank you for replies.
But, an error `Error occurs!` appears when emptying text boxes.
I'm using v0.11.6.
![screenshot from 2018-06-21 03-09-38](https://user-images.githubusercontent.com/1685207/41676520-c8b5917c-7500-11e8-87b3-5819a9fe8226.png)

**Comment by sosukesuzuki** [comment]
@kobtea I see. I want you to create new issue for that  you said. Also I'll put label "feature request" to this Issue.

**Comment by kobtea** [comment]
Sorry for slow reply.
I wrote new issue https://github.com/BoostIO/Boostnote/issues/2153 .

**Comment by jacobherrington** [comment]
#2430 solves this -- but there is an additional improvement where we add a UI element that allows the user to flag a hotkey as disabled.

**Comment by jacobherrington** [comment]
Important to note as well that setting the hotkey to blank and saving does in fact save the hotkey as an empty string effectively disabling it even though an error message is rendered to the app.
