### ISSUE TITLE
[Feature Request] Save zoom level across sessions

### ISSUE THREAD

**Issue by FistfulOfStars** [BoostIO/Boostnote#2089]
Regarding the recent addition of zoom shortcuts ([pull request by @ZeroX-DG](https://github.com/BoostIO/Boostnote/pull/1969))

Would it be possible to save the zoom level across sessions?

Meaning I set the zoom level, close the application, and that same zoom level is reapplied upon next launch.

**Comment by ndbeals** [comment]
I was going to open a separate feature request for this, however it's relevant to this feature.

Could we also get a "Reset Zoom" function to go along with persistent zoom levels?

**Comment by dpjayasekara** [comment]
It is possible to save the zoom level if you change it using the small magnifier icon at the right bottom (MacOS Mojave). However, it does not preserve the setting you set the keyboard shortcut (`cmd`/`ctrl` + `+`/`-`). I guess it should be fixed too.

**Comment by FistfulOfStars** [comment]
@dpjayasekara That completely solves my problem, thank you very much! Never even noticed that magnifying glass before.

Works well on Linux (Mint 18.3)

**Comment by yougotwill** [comment]
Fixed 👍 https://github.com/BoostIO/Boostnote/pull/2601
