### ISSUE TITLE
Characters are escaped at markdown preview

### ISSUE THREAD

**Issue by kasari** [BoostIO/Boostnote#209]
![boostnote 2017-01-06 22-48-45](https://cloud.githubusercontent.com/assets/18321787/21719933/a2fd84f6-d463-11e6-8568-0b3879c4987c.png)
![boostnote 2017-01-06 22-49-03](https://cloud.githubusercontent.com/assets/18321787/21719938/a55824cc-d463-11e6-88d5-a0e71f030c4c.png)

**Comment by kazup01** [comment]
Thank you for your message!
This bag is same as #205 .
