### ISSUE TITLE
Notes gone after update

### ISSUE THREAD

**Issue by eullerborges** [BoostIO/Boostnote#2090]
# Current behavior
After update to the latest version, all my notes are gone, even though the storage is still registered. I tried unlinking and re-adding the storage location, but Boostnote fails to parse the files. File content is in perfect state, it seems (I've opened them and checked). See below a screenshot of the error, which is `EINVAL: invalid argument, fstat`

![boostnote_error](https://user-images.githubusercontent.com/15127796/41426560-616e80e4-6fda-11e8-9619-27611dcbd932.png)

This looks like some regression related to the fact that this is in a folder managed by OneDrive. I tried copying the folder elsewhere and had success at the import.

# Expected behavior
I'd expect my notes to still be there after the update.

# Steps to reproduce

1. Create notes on Boostonote
2. Update to latest version
3. Open boostnote

# Environment

- Version : 0.11.6
- OS Version and name : Windows 10 Enterprise

**Comment by JustinTisdale** [comment]
I'm seeing the same issue. Filesystem appears unaffected; it simply won't load the folder in Boostnote.

**Comment by ehhc** [comment]
I think this is an issue of electron (https://github.com/electron/electron/issues/11570). I think it's fixed with the new release since we will upgrade to electron 2.x with that.
@Rokt33r could say when the next release will be

**Comment by pranayrauthu** [comment]
I am facing the same issue is there any quick fix for this?

**Comment by ehhc** [comment]
@pranayrauthu you could try to copy them the a location *not* in OneDrive.. and then add that location as storage.. not satisfying but maybe you can access your notes again.. at least..

**Comment by pranayrauthu** [comment]
Thanks @ehhc it worked. Only thing is I had to rename all the folders again.

**Comment by eullerborges** [comment]
Thanks, @ehhc, hopefully this will be fixed on the next release. For now I've been using it on a local folder. 
@pranayrauthu I should have explained the workaround process, sorry about that.

**Comment by islanddog** [comment]
For us people slow to this thread; any suspected release date and renaming the folders on the Boostnote side or folder side? -Thanks

**Comment by Flexo013** [comment]
This is no longer an issue in the latest version of Boostnote.
