### ISSUE TITLE
Possibly a Material Redesign?

### ISSUE THREAD

**Issue by zacharyrs** [BoostIO/Boostnote#2092]
So, I'm not sure what the interest is, as it's been mentioned before, but seems to die off after a bit.

Just wondering what the demand for a material redesign is, especially considering we now have the kinda out of place material admonitions - which are great, don't get me wrong!

I have some time coming up, and perhaps could work with a few people to first put together some mockups, and then restyle the UI.

Also, someone previously linked [HyperMD](https://github.com/laobubu/hypermd/), which could be a promising WYSIWYG. If others feel this way, and I have the time, I'll take a look at getting that working too?

**Comment by ehhc** [comment]
at first look i don't think we could get HyperMD work together with the currently used CodeMirror.
If we use it *instead* i think that would mean we will have to redo a lot of work done to customize codemirror so that it works for us (onBlurr handler, onChange handler, etc...)..

**Comment by ndbeals** [comment]
I think it's been mentioned before, but there is also [Toast UI Editor](https://github.com/nhnent/tui.editor) which could be a good candidate for a WYSIWYG editor.

**Comment by zacharyrs** [comment]
Personally I'm not huge on TUI, as it's basically what we have now with a row of buttons at the top? 

I liked HyperMD as it was more Typora-esk.
I have something similar bookmarked, but I'm a bit busy right now. I'll take a look tomorrow!

**Comment by ndbeals** [comment]
TUI isn't "basically what we have now with a row of buttons at the top"

It's a full WYSIWYG editor, additionally it has a split view like what we have right now. I implore you to read the full ReadMe on both of them before making a judgement, instead of just basing your decision off the first gif (which if you had watched completely, you would have seen it showing off the WYSIWYG mode). 

It's also much older than HyperMD, has more contributors, more features and is also developed by a team of people. Not so say HyperMD is bad, I just believe TUI would be a better choice.

**Comment by ehhc** [comment]
anyway i still think that it would break/complicate a lot of the current features..

**Comment by ndbeals** [comment]
Yeah, I can't argue with that.

**Comment by ehhc** [comment]
Don't understand me wrong: I don't want to discourage you. Try it :)
I just want you to keep in mind that there might be problems.. So that you are not surprised if you encounter some.. :)

**Comment by zacharyrs** [comment]
@ndbeals, sorry for jumping to conclusions, I did actually have an inkling I was wrong, as I'd looked at using TUI in the past, but it was late and I was lazy, my bad. 

Taken a look again this morning, and yeah it does have full functionality, as you stated. 
In the even it's not compatible with what we have now, does that matter? It provides its own split view, so we could potentially completely remove the current editor? 

I get we'd need to rewrite large portions for new API calls, but I might give that a go.

**Comment by zacharyrs** [comment]
Ended up finding [this](https://github.com/marktext/marktext) in my starred repos, might be interesting?

**Comment by nesmyslny** [comment]
As a user I really like that Boostnote uses CodeMirror. I prefer to edit plain text and love to have CodeMirrors vim mode (and hope to be able to configure it more in future versions). Actually I was very happy when finding out Boostnote works like that and doesn't use a WYSIWYG editor :smile: 
Just want to add another point of view, so this is not meant as a negative response in any way :v:

**Comment by Flexo013** [comment]
This discussion is over a year old and it seems as there was no particular opinion or suggestion here that gained a lot of traction. So I'll be closing it for now.

Feel free to reopen or visit a different issue about the discussed features: Material design, WYSISYG editor, HyperMD
