### ISSUE TITLE
Control to collapse sidebar disappears in tag list mode

### ISSUE THREAD

**Issue by blahah** [BoostIO/Boostnote#2097]
# Current behavior

The leftmost pane has a `<<` control to collapse the pane. It is currently:
- visible when that pane is set to list 'Notes'
- not visible when that pane is set to list 'Tags'

<img width="173" alt="screenshot 2018-06-16 07 55 47" src="https://user-images.githubusercontent.com/836040/41496576-cdff7946-713a-11e8-8b22-710c177950b7.png">

![screenshot 2018-06-16 07 52 55_blurred](https://user-images.githubusercontent.com/836040/41496577-d07be72c-713a-11e8-9d62-d5932a57bf42.png)

# Expected behavior

The `<<` control to collapse the leftmost pane should remain visible in both 'Notes' and 'Tags' mode.

# Steps to reproduce

1. Ensure the leftmost pane is visible
2. Set to 'Notes' - notice the `<<` at the bottom of the pane
3. Set to 'Tags' - notice the `<<` disappears

# Environment

- Version : 0.11.6
- OS Version and name : macOS 10.13.3

**Comment by robbawebba** [comment]
@blahah @Flexo013 I just opened a PR to address this issue. Any feedback is welcome!

#3239
