### ISSUE TITLE
Boostnote detecting perpetual CMD keystroke when it's not pressed

### ISSUE THREAD

**Issue by ax-vasquez** [BoostIO/Boostnote#2098]
# Current behavior
- "Lock"/ "Unlock" toggle no longer works

# Expected behavior
- "Lock" behavior keeps the editor in "edit" mode after tabbing to another application or window

# Steps to reproduce

1. Create a new document
2. Edit the document
3. Click the "Lock"/"Unlock" toggle to set it to "locked"
4. Switch to another application or window
5. Go back to Boostnote -> The document will no longer be in "edit" mode, despite being locked

# Environment

- Version : 0.11.6
- OS Version and name : MacOS High Sierra Version 10.13.4 (17E202)

**Comment by ax-vasquez** [comment]
Not sure what happened, but this stopped happening today - I can't replicate the issue, but as far as I can tell, there were no updates. There may be some edge condition here I am unaware of. Will keep my eyes open.

**Comment by ax-vasquez** [comment]
Well that didn't take long, but I am still not sure why this is happening - I started editing a new document and this issue started happening, but only for a brief moment. After toggling back and forth a couple of times, the issue resolved itself.

**Comment by ax-vasquez** [comment]
Last observation for this issue - it seems some pattern of key strokes may cause this issue somehow. I noticed when typing while the document is locked in edit mode, it will automatically toggle the view mode right before the lock icon stops working. 

I realize this is a hard-to-follow issue, so I am doing what I can to get relevant info, but I think the best thing here would be a video of the issue. However, I have not been able to capture the issue in a recording since it's so inconsistent.

**Comment by ax-vasquez** [comment]
Figured it out. The issue is that **the hotkey for 'Toggle Editor Mode` [CMD + M] is somehow messed up**.

**Replication Steps**
1. Create a new document
2. While in edit mode, press the "M" key several times > Observe Boostnote incorrectly toggles the edit mode
3. Now, continue doing so, but press and hold down the COMMAND button > Observe nothing happens when this is pressed

I am certain my keyboard is not broken and I have verified that the hotkey is still configured to be CMD+M, but that doesn't work - only pressing the "M" alone key will toggle the editor.

**Comment by ax-vasquez** [comment]
An additional little "quirk" about this issue - it never happens when typing capital "M" - only lower-case "m". It seems Boostnote is detecting that the command key is always being pressed down when it's not.

**Comment by ax-vasquez** [comment]
(Last comment, I promise) Updated the title to reflect the issue - I think it's simply a matter of the app thinking the CMD key is constantly being held down. This is why the "edit" lock issue also happens. This issue will presumably affect any hotkey that requires the use of the CMD key.

**Comment by kpollich** [comment]
I'm also seeing this behavior, pressing M toggles the editor mode as you've described.

**Comment by bruno-rino** [comment]
Same here, typing a `m` in the editor toggles the editor mode.

**Comment by zhuzelong** [comment]
Same here, it is a bit annoying.

**Comment by ax-vasquez** [comment]
@zhuzelong as a rough "workaround" you can just delete the text from the key bindings fields. 

It's not perfect, but it's made this issue much less annoying :)

**Comment by FaithInMotion** [comment]
I can't type any notes now because of this behavior... unfortunately, M is a very common letter...

**Comment by Rokt33r** [comment]
It seems to be a bug of electron v1.8.6. We have to use `Command` rather than `Cmd` to avoid this bug.
I'm going to release temporary fix soon.

**Comment by Rokt33r** [comment]
Sorry, I misunderstood. It seems to be a bug of Mousetrap.
