### ISSUE TITLE
Selectable system tray icon

### ISSUE THREAD

**Issue by re-fort** [BoostIO/Boostnote#210]
New app icon is good!
However, system tray icons  on darwin are mainly black and white design like a previous app icon.
it would be good to choose between a black and white icon and a colored icon.

**Comment by kazup01** [comment]
Thank you for your message!
I see. We will add to the todo list.

**Comment by kazup01** [comment]
Sorry for late supporting!
We updated it at latest version! Enjoy Boostnote👏
<img width="58" alt="screen shot 0029-03-22 at 4 06 43 pm" src="https://cloud.githubusercontent.com/assets/8602615/24186030/9c601d02-0f19-11e7-86e9-bfdc08d32432.png">
<img width="57" alt="screen shot 0029-03-22 at 4 06 49 pm" src="https://cloud.githubusercontent.com/assets/8602615/24186029/9c5da220-0f19-11e7-8932-5fca4f577fa6.png">

**Comment by re-fort** [comment]
The best solution is that we can choose between a black and white icon and a colored icon.
Thanks, though:blush:

**Comment by kazup01** [comment]
I'm so glad😆 Arigatou gozaimasu!
