### ISSUE TITLE
Please make the preview page width customizable

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#2102]
# Current behavior

when typing text or code the page width isn't a problem. However, when type setting mathematics katext centres the math block at the centre of the page but since the preview page width is so long the katex code ends up being displayed to far to the right.
![boost](https://user-images.githubusercontent.com/39413259/41584859-ca0e19b4-737e-11e8-95c4-4f2ae765c271.JPG)

# Expected behavior
If the preview page width was customizable the following could be achieved.
![boost](https://user-images.githubusercontent.com/39413259/41585380-434f32a8-7380-11e8-9e43-50e76cf5dbfa.JPG)

**Comment by ehhc** [comment]
It might be possible with custom css, woudn't it?

**Comment by OnlineVagrant** [comment]
I'm not sure I know how to do that. I have tried by I wan't successful. Maybe it is because I don't know much css.This is what I did.

![ten percent](https://user-images.githubusercontent.com/39413259/41596041-5c63b3b2-739f-11e8-8a47-cafe15d4a69a.JPG)

only the paragraph is being manipulated the math block stays the same.
![boost](https://user-images.githubusercontent.com/39413259/41596078-809fd42c-739f-11e8-8e34-ede1451929ee.JPG)

**Comment by ehhc** [comment]
Did you try something like the following? As custom CSS ??
```
.katex-display {
    text-align: left;
}
```

**Comment by OnlineVagrant** [comment]
It's not the convention, But I like it. It isn't left justified and everything lines up this way thank you.

**Comment by ehhc** [comment]
you're welcome
