### ISSUE TITLE
Want a new feature: color in markdown

### ISSUE THREAD

**Issue by weaming** [BoostIO/Boostnote#2103]
I want a feature render text in special color:

`#347E5E`   -->    `<p style="color: #347E5E">#347E5E</p>`

**Comment by ehhc** [comment]
If you go to preferences > Interfaces > Sanitizazion and change it to "allow styles" you already are able to do exactly what you want.. :)

**Comment by weaming** [comment]
@ehhc I tried it, but

![image](https://user-images.githubusercontent.com/10275711/41697207-58753df0-754a-11e8-9f09-363f503dfadb.png)

The render color is not red.

And, the feature I want is it can render it automatically

**Comment by ehhc** [comment]
are you sure, you enabled the correct option in the preferences?!

**Comment by weaming** [comment]
@ehhc Okay, html style works. Maybe I forgot click save button.

**Comment by modmod24** [comment]
nice, it works.

**Comment by modmod24** [comment]
@weaming, would you still like some enhancement or close the issue?

**Comment by weaming** [comment]
@modmod24 But I don't want to use html style. 

What I want is it detect the color text automatically

**Comment by ZeroX-DG** [comment]
Well this feature can be achieved but I don't really see why Boostnote should support that feature. Can you show us why that feature is useful?

**Comment by weaming** [comment]
@ZeroX-DG I want to write down a collection of some colors, and pick one to use some day. It's will be more simple with this feature.

Just like color in this issue body, the color could be seen instead of hex characters.

`#00ff00`
`#ff0000`
`#0000ff`

Also, support color like `#abc` is great.

**Comment by Rokt33r** [comment]
I don't think this feature is useful. It must be optional.
