### ISSUE TITLE
  Pressing `m` in editor triggers togglemodemenu

### ISSUE THREAD

**Issue by samontea** [BoostIO/Boostnote#2111]
# Current behavior

Pressing `m` in the editor triggers toggle mode menu and inserts `m` into the current note in v0.11.6

<img width="1380" alt="screen shot 2018-06-20 at 21 24 48" src="https://user-images.githubusercontent.com/1585424/41692911-ca76e644-74d0-11e8-9d56-c5b2bdb19b13.png">

# Expected behavior

Pressing `m` inserts the character `m` into the current note without toggling the mode menu.

# Steps to reproduce

1.  Create new note in Boostnote.
2.  Edit note.
3.  Press `m`.

# Environment

- Version : v0.11.6
- OS Version and name : MacOS 10.13.5

**Comment by srusso** [comment]
Experiencing the same issue myself

**Comment by breath-ee** [comment]
I'm getting similar issues in OSX 10.11.6. 

Change the default hotkey to `Alt + M` seems to sort this!

**Comment by samontea** [comment]
Cool closing duplicate issue. Thanks y'all. 🎉
