### ISSUE TITLE
Pushing "lowercase m" key on the keyboard hits the Toggle button

### ISSUE THREAD

**Issue by thcnunz** [BoostIO/Boostnote#2113]
# Current behavior
When hitting the "lowercase m" key on the keyboard hits the Toggle button.

have only tried this on MacOS. Not sure about Windows.

# Expected behavior
is to type the letter "m" and not to hit the "Toggle" button.

# Steps to reproduce

1. Create or open a note
2. Start typing into the note and push the letter"m"
3. View behaviour.

# Environment

- Version : 10.13.5
- OS Version and name : MacOS

**Comment by jdugan1024** [comment]
I have this problem as well.  I really love Boostnote, but this bug is seriously making it hard to use!

Boostnote version 0.11.6 (0.11.6) -- it started right after the upgrade but I hadn't gotten around to reporting it yet.

I'm using MacOS 10.13.4.

**Comment by forbidden404** [comment]
Same problem here, just noticed it while writing a markdown note.

**Comment by Rokt33r** [comment]
It has been fixed already. And the fixed version will be released in mid of the next week!
https://github.com/BoostIO/Boostnote/pull/2110
