### ISSUE TITLE
Error behaviour while writing

### ISSUE THREAD

**Issue by KenrySanchez** [BoostIO/Boostnote#2114]
# Current behavior

# Expected behavior

Sometimes, while I'm writing the screen changes the display preview without making any option. It just happens. it's really annoying 

# Steps to reproduce

1. write a lot

# Environment

- Version : 0.11.6
- OS Version and name: MacOs Hight Sierra

**Comment by awhale** [comment]
In the Hotkeys panel of the preferences page, there is a keyboard shortcut to toggle editor mode.

The default value is set to 'CMD M' (or 'CTRL M' I cant remember), but the hotkey appears to be triggering on just 'm', so every time you enter 'm' while typing it will toggle preview mode.

As a workaround you can unbind the hotkey

**Comment by Pudge601** [comment]
Looks like this was solved by https://github.com/BoostIO/Boostnote/commit/7c0097951c550c86be785f0150d2c2c835c6f329#diff-38fb68fc79bd352622982a452f398fed

But that's just updating the default, so to get this fix, you'll need to modify the hotkey to change 'Cmd + M' to 'Command + M'

**Comment by renatoliveira** [comment]
Doing what @Pudge601 said fixed this for me. I think it won't happen for new installations, since the default is being set to `Command + M` instead of `Cmd + M`, right?

**Comment by sosukesuzuki** [comment]
@KenrySanchez Maybe, This issue was solved by #2110 .
