### ISSUE TITLE
Bootsnote Should have an option to create more parents Folder

### ISSUE THREAD

**Issue by KenrySanchez** [BoostIO/Boostnote#2119]
# Recommendations!! I'm new in using bootsnote

Like a suggestion, I think Bootsnote should have a way to create more parents folders. It's would make the navigation more efficiently and excited.

Thanks!! KS

**Comment by flyaway1217** [comment]
Can't agree more.

**Comment by mattkoskela** [comment]
This seems to be a duplicate request: https://github.com/BoostIO/Boostnote/issues/586

**Comment by KenrySanchez** [comment]
Yeah. It's exactly what I'm suggesting. I'm going to close the issue!! Thanks!!
