### ISSUE TITLE
Custom theme color

### ISSUE THREAD

**Issue by iChard** [BoostIO/Boostnote#2120]
# Current behavior
Like to custom my own theme colors；Like below~
@kazup01 

# Expected behavior
![image](https://user-images.githubusercontent.com/12317840/41789956-9ef4afa6-7683-11e8-9566-a189a7d21cad.png)

Now i have to switch tothe developer  tools and change the color like Sider/Main and so on! But it will not working while i restart boostnote!

How about custom the theme color like this...
![image](https://user-images.githubusercontent.com/12317840/41790282-97ef7712-7684-11e8-8b8d-6c92cca533ca.png)

**Comment by ZeroX-DG** [comment]
I'm not quite understand your problem. This feature only cover the markdown preview style not the whole UI. Please provide some more details.

**Comment by ZeroX-DG** [comment]
Close due to inactivity
