### ISSUE TITLE
Toggle editor mode bug

### ISSUE THREAD

**Issue by se7oluti0n** [BoostIO/Boostnote#2123]
# Current behavior

In MacOS 10.13.5, The default hot key for toggle editor mode is `Cmd + M`. When I was editing in the editor, I typed `m` key then the GUI switched editor mode. It continued to switch editor mode if I pressed `m` key again.
Current workout is clear toggle editor mode hotkey.

# Expected behavior
The GUI is not switched if I press `m` key. It should switch when I press `Cmd + M`
# Steps to reproduce

1.  The default toggle editor mode hot key is `Cmd + M`. Confirm it by going to Boostnote preferences,
see toggle editor mode in `Hot keys` section
2.  Go to editor, type something which include `m` character.
3.  See the GUI switched

# Environment

- Version : 0.11.6
- OS Version and name : MacOS high sierra, 10.13.5

**Comment by Karrade7** [comment]
Same issue here. It started after the last update.

Version: Version 0.11.6 (0.11.6)

**Comment by sandasai** [comment]
Same issue here, pretty

**Comment by octarrow** [comment]
same issue here. Changing hotkey to Ctrl + M solved the problem

**Comment by sosukesuzuki** [comment]
@se7oluti0n This issue was solved by #2110 :+1:

**Comment by MattWilcox** [comment]
Same issue; my first time using this app and it put a heavy ding in my impression of it. Typing breaks the UI?

**Comment by sosukesuzuki** [comment]
@se7oluti0n Sorry, please wait for release next version(v0.11.7):pray:
