### ISSUE TITLE
Files and directory mode for note management

### ISSUE THREAD

**Issue by arthurkiller** [BoostIO/Boostnote#2126]
Hey guys, really awesome work you've did. 

I want a file management feature, that my note can write on disk files without encode.

with this feature, I can easily import my directory.

**Comment by arthurkiller** [comment]
I think note or files, management around plan text maybe a good idea.

**Comment by arthurkiller** [comment]
With file system browser feature. I can freely gather my picture and markdown together.

**Comment by Flexo013** [comment]
You can already export your files as markdown files (not "encoded").

We also have this issue #490 which requests the same as you, .md files instead of .cson.
