### ISSUE TITLE
Enter Chinese in plantuml will show garbled

### ISSUE THREAD

**Issue by jiangmitiao** [BoostIO/Boostnote#2129]
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.11.6
- OS Version and name : MacOS

**Comment by sosukesuzuki** [comment]
@jiangmitiao I want you to write description :pray:
Also, maybe this issue was resolved by #2122

**Comment by yosmoc** [comment]
Yes, should be solved by #2122. Please wait for the release version 0.11.8.(not 0.11.7).

**Comment by sosukesuzuki** [comment]
Thanks @yosmoc !
@jiangmitiao I'll close this issue!:+1: please wait for next release!
