### ISSUE TITLE
Markdown Math Elements not Showing Up

### ISSUE THREAD

**Issue by chethanjjj** [BoostIO/Boostnote#2130]
# Current behavior

![screen shot 2018-06-25 at 8 44 28 pm](https://user-images.githubusercontent.com/13612172/41888103-94482d62-78b8-11e8-825e-e19df1bafe99.png)

# Expected behavior

Expected the beta symbol to show up

# Environment

- Version : 0.11.6
- OS Version and name : 10.13.5 MacOS High Sierra

**Comment by sosukesuzuki** [comment]
@chethanjjj 
please confirm latex delimiters from  `Preference` > `Interface`.
My delimiters is below:
<img width="586" alt="2018-06-26 14 11 15" src="https://user-images.githubusercontent.com/14838850/41890515-cff0d408-794a-11e8-8fbd-f033c6c3ae80.png">
I tried using Katex.
<img width="719" alt="2018-06-26 14 12 51" src="https://user-images.githubusercontent.com/14838850/41890619-40908afa-794b-11e8-9dd9-92b2d239dc46.png">
Is this issue resolved?

**Comment by chethanjjj** [comment]
Thank you, it is solved.

**Comment by sosukesuzuki** [comment]
@chethanjjj I'll close this issue:+1:
