### ISSUE TITLE
shortcuts operation wrongly triggered under editor mode

### ISSUE THREAD

**Issue by sunbingfengPI** [BoostIO/Boostnote#2141]
# Current behavior

When you hit character 'm' under editor mode, it will toggle on the preview view, and if you hit 'm' again, the preview view will be toggled off.

# Expected behavior

Not trigger any shortcuts operation under editor mode.

# Steps to reproduce

# Environment

- Version : Version 0.11.6 (0.11.6)
- OS Version and name : macOS 10.13.3

**Comment by sosukesuzuki** [comment]
@sunbingfengPI This is resolved by #2110 ! Please wait for release next version(v0.11.7) !:pray:
