### ISSUE TITLE
Highlight breaks when link string has "[]"

### ISSUE THREAD

**Issue by KMR-zoar** [BoostIO/Boostnote#2142]
If "[]" is in the link string in the editing state of the markdown mode, the highlight will not be displayed correctly.

e.g.: [[tag] blogtitle](http://example.com)

I found this issue in Editor Theme's "pastel-on-dark".

![default](https://user-images.githubusercontent.com/6219187/42012811-03340f0c-7ad5-11e8-93d9-739a7363b482.PNG)

Boostbote 0.11.6
Windows 7 Pro 64bit

In View mode, it functions correctly as a link.

**Comment by sosukesuzuki** [comment]
@KMR-zoar Thanks for your bug report. This bug is depends on [Markdown mode of CodeMirror](https://codemirror.net/mode/markdown/).

**Comment by KMR-zoar** [comment]
Hi @sosukesuzuki 
Thank you, I'll report it in CodeMirror 's repository ;-)

**Comment by KMR-zoar** [comment]
This issue was resolved in CodeMirror [repository](https://github.com/codemirror/CodeMirror/issues/5476).

It will be solved by using a version that exceeds 5.39.0 released in the future.

**Comment by bimlas** [comment]
CodeMirror is updated in #2146

**Comment by KMR-zoar** [comment]
I appreciate your efforts.
