### ISSUE TITLE
[Feature Request] Cursor Customization

### ISSUE THREAD

**Issue by limgit** [BoostIO/Boostnote#2143]
# Current behavior
When using the dark editor theme, the cursor (editing position) is barely visible. For example, we can see the cursor position clearly in the light editor theme as following:
![image](https://user-images.githubusercontent.com/10260432/42013965-c9e16c80-7ada-11e8-8fc5-f11bdbe7c8c5.png)

However, with the dark editor theme, it is very hard to see where the cursor is. It is even worse because the cursor is keep blinking:
![image](https://user-images.githubusercontent.com/10260432/42014018-1352a62c-7adb-11e8-9928-222af33ff48e.png)

Since I love the dark editor theme (actually I'm using the entire Boostnote with dark theme :)), I hope there is a cursor customization feature which can improve the visibility of cursor.

# Expected behavior
It would be nice if the cursor customization feature is added. I think the customization for the following items would be enough (from higher priority to lower priority):
 - Cursor color
 - Cursor type: box type, line type, underscore type (see the example in [this link](https://atom.io/packages/block-cursor))
 - (Maybe) cursor width

At least if cursor color customization feature is added, it would highly improve the visibility of the cursor.

# Environment

- Version : Boostnote v0.11.6
- OS Version and name : Windows 10

**Comment by sosukesuzuki** [comment]
@limgit I felt this inconvenient too. But this bug happens only on `darcula` theme. And this bug is resolved by CodeMirror v5.39.0!(CodeMirror which Boostnote depends on is v5.37.0)(Please look [this update](https://github.com/codemirror/CodeMirror/commit/dc573b5a913951a1eb1db9a04400a3b2765b14a2).) So, I think custom cursor is unnecessary. Just enough updating CodeMirror version.

**Comment by limgit** [comment]
@sosukesuzuki Oh I see. Then I think I should wait for such updates :). (I also thought that the cursor customization feature could be a bit overkill)
By the way, I'm really enjoying Boostnote. Thanks for such nice markdown-supported note app.

P.S. Should I close this issue by myself? or are you going to handle it?

**Comment by sosukesuzuki** [comment]
@limgit Oh, Thank you for using Boostnote and creating great issue:smile:

I'll close this issue after update CodeMirror version!

**Comment by alexhkurz** [comment]
"Just enough updating CodeMirror version" --- How do I do this? Google didnt provide the answer ...
