### ISSUE TITLE
Space bar switches views

### ISSUE THREAD

**Issue by jenniferlynparsons** [BoostIO/Boostnote#2148]
# Current behavior
As I am typing, randomly when I press the space bar it switches the editor view. I start without the side by side, then it switches to side by side, then it switches to preview only, where I can't edit any further.

# Expected behavior
To be able to type without the view changing.

# Steps to reproduce

1. Start typing in a note
2. While typing normally, ensure the space bar is triggered occasionally
3. View randomly switches

# Environment

- Version : Desktop
- OS Version and name : MacOS High Sierra 10.13.4

**Comment by jenpen** [comment]
I am experiencing the same behavior. My environment is the same as the reporter has listed.

**Comment by jenniferlynparsons** [comment]
Just following up that it appears it was actually the letter "m" that's causing the issue. Lower case, no other modifier keys.

**Comment by jenniferlynparsons** [comment]
@jenpen i've temporarily worked around the issue by deleting the "Toggle editor mode" configuration in the Hotkeys section of Preferences.

**Comment by sosukesuzuki** [comment]
@jenniferlynparsons @jenpen This issue is resolved by #2110 !! Please wait for release next version(v0.11.7)!
