### ISSUE TITLE
Autoupdate Cannot be Ignored

### ISSUE THREAD

**Issue by promiseofcake** [BoostIO/Boostnote#2149]
# Current behavior

Boostnote informs user there is an update, user clicks later.
On subsequent re-launch of the app the app is updated.

0.11.6 is fundamentally broken so it's frustrating to be stuck in an update cycle that I don't want to participate in.

# Expected behavior

App should not be updated unless user explicitly updates.

# Steps to reproduce

1. Download 0.11.4
2. Wait
3. See Update downloading notice, click later
4. Re-launch app at a later period of time
5. App will be updated

# Environment

- Version : 0.11.4
- OS Version and name : macOS 10.13

**Comment by promiseofcake** [comment]
Has this been solved?

**Comment by ZeroX-DG** [comment]
I think so, can you check it?
