### ISSUE TITLE
In vim mode, the "m" key exits edit mode

### ISSUE THREAD

**Issue by catmeme** [BoostIO/Boostnote#2150]
# Current behavior

When editing a file with vim mode enabled, typing the letter "m" exits edit mode.  This is a regression, it wasn't happening in prior releases.

# Expected behavior

I expect to be able to type "m" in insert mode.

# Steps to reproduce

1. With vim mode enabled, create a new note
2. Press 'i' for insert mode
3. Start typing, "immediate"

# Environment

- Version : 0.11.6 (0.11.6)
- OS Version and name : OSX Sierra 10.12.6

**Comment by zippeellii** [comment]
I believe this issue has been addressed in 7c0097951c550c86be785f0150d2c2c835c6f329 . It is not a problem with the vim mode, it has to do with a typo in the default shortcut for toggle editor mode. Try  `Preferences` -> `Hotkeys` and change `Cmd + M` to `Command + M`. Will most certainly be included in the next release. Hope this helps you!

**Comment by catmeme** [comment]
Thank you so much, this was driving me nuts :)

**Comment by sosukesuzuki** [comment]
@catmeme This issue is resolved by #2110 ! Please wait for release next version(v0.11.7)!
