### ISSUE TITLE
Build With Grunt Fails

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2151]
There is something I am missing or the build guide is not up to date but I tried with the npm and nodejs versions it requires and also with latest versions and the output .deb and linux executable end up corrupted. Compiling this with yarn run-devstart works great. OS on which compilation happen is Ubuntu 18.04. Any ideas ?

**Comment by infosisio** [comment]
@sosukesuzuki On what system do you compile it yourself ? I really tried many setups and I can't get this to compile :(

**Comment by Rokt33r** [comment]
Which node.js version did you use?

**Comment by infosisio** [comment]
@Rokt33r I tried many, tried the latest ones, tried the ones in the build guide. After it compiles with "grunt pre-build" or "grunt build" either it runs and the notes are not displayed, notes cannot be deleted and notes cannot be created or it doesn't run at all. With "yarn run dev-start" it works great but I obviously cannot use that on a daily basis since it won't allow me to install it on my system and I will have to compile it every single time I want to use it :/

**Comment by infosisio** [comment]
I managed to build the .deb with success on Ubuntu 18.04 with the following steps for anyone interested:
sudo apt-get install curl
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm install 7.10.1
cd Boostnote
npm i
sudo apt install node-grunt-cli
sudo apt-get install -y rpm fakeroot
grunt pre-build
grunt build

**Comment by ZeroX-DG** [comment]
Close as solved
