### ISSUE TITLE
I can't see `Toggle Finder popup` in Preference

### ISSUE THREAD

**Issue by mothule** [BoostIO/Boostnote#2155]
# Current behavior

![image](https://user-images.githubusercontent.com/974367/42121569-7c68cdd4-7c6c-11e8-8d60-8ff8909c1c1e.png)

If I press `option + command + s` then don't work `Toggle Finder popup`.

# Steps to reproduce

1. Open boostnote
2. Open Preference by Cmd+,
3. Select HotKeys

# Environment

- Version : 0.11.7 (0.11.7)
- OS Version and name : macOS High Sierra 10.13.5

**Comment by sosukesuzuki** [comment]
@mothule Finder was discarded from v0.9.0(#1497). So, I'll close this issue.
