### ISSUE TITLE
Automatic closing tags conflict with angle brackets in code snippets

### ISSUE THREAD

**Issue by mosaaleb** [BoostIO/Boostnote#2160]
# Current behavior
When using angle brackets in C++ code snippet,  it interprets it as HTML tag and auto closes the tag

![capture](https://user-images.githubusercontent.com/4246637/42124717-7bc11e80-7c68-11e8-8b4e-17a685cc071d.PNG)

![capture1](https://user-images.githubusercontent.com/4246637/42124736-ab53c38c-7c68-11e8-9e2f-421098f3dade.PNG)

# Expected behavior
Removing `</int>` tag at the end
# Steps to reproduce

1. use angle brackets inside code snippets

# Environment

- Version : 0.11.7
- OS Version and name : Windows 8.1

**Comment by Geekfish** [comment]
Hi! Why was this issue closed? I am encountering the same problem which I can consistently replicate in the same manner.
