### ISSUE TITLE
Boostnote 0.11.7 crash (didn't start) on MacOS X 10.9.5

### ISSUE THREAD

**Issue by andreinl** [BoostIO/Boostnote#2161]
# Current behavior

Process:         Boostnote [67151]
Path:            /Applications/Boostnote.app/Contents/MacOS/Boostnote
Identifier:      com.maisin.boost
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [150]
Responsible:     Boostnote [67151]
User ID:         501

Date/Time:       2018-06-30 18:35:55.650 +0200
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  C069AF67-5647-ABB9-D9DA-FA1DE39BB32D

Sleep/Wake UUID: F4084C4A-A6C5-4B24-8B0A-1F59861B0142

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Applications/Boostnote.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
    0x7fff6a191000 -     0x7fff6a1c4887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff85733000 -     0x7fff85874fff  com.apple.QTKit (7.7.3 - 2826.34) <3BB88D64-71FA-3824-A52A-D51C761E6EE0> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff86023000 -     0x7fff86293ffd  com.apple.security (7.0 - 55471.14.40) <58F50B4A-FC1E-3AE0-A5DB-DD737E50AC17> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff86673000 -     0x7fff86698ff7  com.apple.CoreVideo (1.8 - 117.2) <4674339E-26D0-35FA-9958-422832B39B12> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff866d1000 -     0x7fff86718ff7  libcups.2.dylib (372.6) <CBD2F0CF-FA10-36E1-A1D5-1B946B45B3B3> /usr/lib/libcups.2.dylib
    0x7fff86815000 -     0x7fff86c63fef  com.apple.VideoToolbox (1.0 - 1273.57) <AA4D613A-1066-3E85-8BE0-7806566652B4> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff8723d000 -     0x7fff8735ffff  com.apple.avfoundation (2.0 - 651.12.1) <FDCF1F41-E0BD-3F8C-974A-3F48A0A85B00> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff875c9000 -     0x7fff875daff7  libz.1.dylib (53) <42E0C8C6-CA38-3CA4-8619-D24ED5DD492E> /usr/lib/libz.1.dylib
    0x7fff89666000 -     0x7fff89666fff  com.apple.quartzframework (1.5 - 1.5) <3B2A72DB-39FC-3C5B-98BE-605F37777F37> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff89c06000 -     0x7fff89c72fff  com.apple.framework.IOKit (2.0.1 - 907.100.14) <10932113-9F7E-38A0-A158-A019A555CAC3> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8a505000 -     0x7fff8a506ff7  libSystem.B.dylib (1197.1.1) <72A98ACC-7606-3AD5-82AF-02D4EBBD4F02> /usr/lib/libSystem.B.dylib
    0x7fff8aef1000 -     0x7fff8b08cff8  com.apple.CFNetwork (673.6 - 673.6) <CAA196FE-BF5A-384F-975E-E0F81359805B> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff8b23e000 -     0x7fff8b2a1ffb  com.apple.SystemConfiguration (1.13.1 - 1.13.1) <339A2A90-DA25-33AF-88E5-2FB38A758FEE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff8b2a2000 -     0x7fff8b487fff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8baf6000 -     0x7fff8bb8aff7  com.apple.Bluetooth (4.2.7 - 4.2.7f5) <A7F0360A-DBDA-32EA-AA37-6937B94E6A72> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff8be68000 -     0x7fff8beb9ff7  com.apple.audio.CoreAudio (4.2.1 - 4.2.1) <07F2B103-AE29-3118-BBC4-9A72E13B013B> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff8beba000 -     0x7fff8bebafff  com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff8bffd000 -     0x7fff8c046fff  com.apple.CoreMedia (1.0 - 1273.57) <74FA3D80-A6DB-331A-B32A-683C8E0CC0A6> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff8c5e6000 -     0x7fff8c645fff  com.apple.framework.CoreWLAN (4.3.3 - 433.48) <1F17FA12-6E84-309D-9808-C536D445FA6E> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff8c82d000 -     0x7fff8c82dffd  com.apple.audio.units.AudioUnit (1.10 - 1.10) <68B21135-55A6-3563-A3D6-3E692A7DEB7F> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff8c924000 -     0x7fff8c932fff  com.apple.opengl (9.6.5 - 9.6.5) <4FAEADD8-EEB3-3FD9-ADC6-BA65806228CC> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff8c9f6000 -     0x7fff8c9f6fff  com.apple.Accelerate (1.9 - Accelerate 1.9) <509BB27A-AE62-366D-86D8-0B06D217CF56> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff8cd73000 -     0x7fff8cd8ffff  libresolv.9.dylib (54) <11C2C826-F1C6-39C6-B4E8-6E0C41D4FA95> /usr/lib/libresolv.9.dylib
    0x7fff8cd90000 -     0x7fff8cda0fff  libbsm.0.dylib (33) <2CAC00A2-1352-302A-88FA-C567D4D69179> /usr/lib/libbsm.0.dylib
    0x7fff8d3d6000 -     0x7fff8d52aff3  com.apple.audio.toolbox.AudioToolbox (1.10 - 1.10) <69B273E8-5A8E-3FC7-B807-C16B657662FE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff8d5b5000 -     0x7fff8d8b5ff7  com.apple.Foundation (6.9 - 1056.17) <E0B0FAF6-5CA8-3EEB-8BF2-104C0AEEF925> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff8e5b1000 -     0x7fff8e603fff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8e7f6000 -     0x7fff8e820ff7  libsandbox.1.dylib (278.11.2) <5C750008-A22B-35E8-8B11-D84F82E08680> /usr/lib/libsandbox.1.dylib
    0x7fff8eb45000 -     0x7fff8eb48ffc  com.apple.IOSurface (91.3 - 91.3) <E93485CC-12B1-318E-BAE3-AB532B264935> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff90983000 -     0x7fff90b1fff3  com.apple.QuartzCore (1.8 - 332.4) <CFB972D1-FA37-380C-9A47-2A67A84B7442> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff90b20000 -     0x7fff91696ff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff91786000 -     0x7fff91790ff7  com.apple.bsd.ServiceManagement (2.0 - 2.0) <2D27B498-BB9C-3D88-B05A-76908A8A26F3> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff91791000 -     0x7fff917bfff7  com.apple.securityinterface (9.0 - 55047) <0346D8A9-2CAA-38F3-A741-5FBA5E9F1E7C> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff91f2f000 -     0x7fff91f2ffff  com.apple.Carbon (154 - 157) <45A9A40A-78FF-3EA0-8FAB-A4F81052FA55> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon

Model: MacBookPro9,2, BootROM MBP91.00D3.B0C, 2 processors, Intel Core i5, 2.5 GHz, 16 GB, SMC 2.2f44
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x393930353432382D3138362E413030472020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x393930353432382D3138362E413030472020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: KINGSTON SUV400S37480G, 480,1 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: Hub
USB Device: iPad
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

# Steps to reproduce

1. Try to start, it immediately crashes

# Environment

- Version : 0.11.7 
- OS Version and name : Mac OS X 10.9.5

**Comment by mvilain** [comment]
It also crashes on 10.10.5

**Comment by NowStart** [comment]
also 10.11.6

**Comment by andreinl** [comment]
Just tried Boostnote 0.11.8, but it doesn't work either. It crashes the same way as 0.11.7

**Comment by andreinl** [comment]
Finally I figured out the problem:
```
Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Applications/Boostnote.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found
```
Unfortunately _CoreBluetooth.framework_ was introduced in Mac OS **10.10**, so it can't run on a previous versions of OS.
