### ISSUE TITLE
On-purpose incorrect numbering gets overridden with correct numbering

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#2169]
# Current behavior

![image](https://user-images.githubusercontent.com/1558019/42176130-cc55b764-7ddc-11e8-94c5-4b4d8f6add91.png)

# Expected behavior

Numbering in rendered view should match markdown numbering

# Steps to reproduce

1. Number a couple objects
2. Change one of the previous numbers to not follow the number sequence
3. Notice that the rendered view automatically corrects the sequence for you

# Environment

- Version : 0.11.7
- OS Version and name : Windows 10 Pro 64-bit

**Comment by takacsot** [comment]
As far as I know, this is **the** markdown behaviour.

**Comment by Flexo013** [comment]
This is intended Markdown behavior.
