### ISSUE TITLE
Theme examples page

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#217]
Hi, I'm confused when choosing my theme thanks to the amount of them. Thus I want any theme examples page.

**Comment by kazup01** [comment]
Hi asmsuechan san,
Thank you for your message and all of cooperation!
Yeah, I think so too.
If possible, could you publish us to example page?
We will add it to the official landing page.

**Comment by asmsuechan** [comment]
Sure. But I'm not sure how I make it.

**Comment by kazup01** [comment]
If you send me to html and css files, I will check and add it to the lp!

**Comment by asmsuechan** [comment]
I'll try to make a page just place screen shots of themes in order.

**Comment by kazup01** [comment]
Thank you🙏 I'm looking forward it!

**Comment by sota1235** [comment]
I think @asmsuechan want to see preview of the theme, don't you?

I think `Theme Demo` page of CodeMirror is close to your image.

![](https://i.gyazo.com/02ef514c936312e7dc8735e0e676311b.gif)
https://codemirror.net/demo/theme.html#abcdef

If I implement the preview of code theme on config, is it useful for you?

**Comment by asmsuechan** [comment]
@sota1235 Yes, its demo page is the most adequate for me. And the preview of code theme is ofcourse useful.

**Comment by kazup01** [comment]
@sosukesuzuki is trying it.

**Comment by kazup01** [comment]
@sosukesuzuki added it on#290 .🎉
