### ISSUE TITLE
Right click to pin/unpin notes not working

### ISSUE THREAD

**Issue by EvaBrarens** [BoostIO/Boostnote#2175]
# Current behavior
When right-clicking on a note in the overview no options are shown. This effectively makes it impossible to pin/unpin notes. 

JS error in console:
![2018-07-03_14h01_06](https://user-images.githubusercontent.com/6517619/42218641-944d7292-7ec9-11e8-955f-e30933a30e05.png)

# Expected behavior
When right clicking on a note it should give the option to pin/unpin a note to the top. 
As explained here:  https://medium.com/boostnote/boostnote-tips-pin-notes-to-the-top-of-note-list-2475e7129691

# Steps to reproduce

1. Open Boostnote 
2. Right click on a note

# Environment

- Version : 0.11.7
- OS Version and name : Win 7,  Win 10

**Comment by ndbeals** [comment]
I have the same issue, more so, right-click context menus seem to be broken and giving me the above error everywhere.

**Comment by enyaxu** [comment]
This is bug that has been fixed in #2157  #2158. It will being release next version.

**Comment by camelmasa** [comment]
Thanks for reporting. I'm waiting next release for it 😃
