### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by TZTsai** [BoostIO/Boostnote#2182]
# Current behavior
The system prompts that the parallel configuration is incorrect.
![default](https://user-images.githubusercontent.com/34415979/42309389-000a0d0e-806b-11e8-82bd-7ee10dfcae66.PNG)

<!--
Please paste some **screenshots** with the **developer tool** open (console tab) when you report a bug.

**Comment by Rokt33r** [comment]
I cannot understand what the error message means. Could you translate it?

**Comment by TZTsai** [comment]
Error "Could not start the application; the parallel configuration is incorrect. See the event log of the application or use sxsrace.exe tool command line for more details."

**Comment by ZeroX-DG** [comment]
@TZTsai , @Rokt33r I think this is the error message that he's getting
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/windows-10-error-the-application-has-failed-to/5c6a015e-4162-491d-b7d9-f3b13612e304

**Comment by Sylk** [comment]
@TZTsai did @ZeroX-DG response help you get to a solution?

**Comment by Flexo013** [comment]
Closing this issue due inactivity of the issue's author.
