### ISSUE TITLE
Another trigger position of XSS

### ISSUE THREAD

**Issue by v5pingan** [BoostIO/Boostnote#2184]
I'm using the latest version (2018/07/05)

1. new notes, select Markdown, write payload:

<img src= "test" onerror=alert ('test') >

It's not going to trigger now.

2. when I need to highlight the markdown code, I write it before the code.

" ``` "

I trigger xss. when I enter third.

[This is a video display:](https://github.com/v5pingan/github.so/blob/master/bootsnote/bootsnote-xss.mp4)
https://github.com/v5pingan/github.so/blob/master/bootsnote/bootsnote-xss.mp4

Boostnote is great!

**Comment by Rokt33r** [comment]
Thanks for reporting. I'll fix it soon. It looks very critical.
