### ISSUE TITLE
[Discussion] sorting tags - minor change in behaviour

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2185]
hello, 
When viewing the list of all Tags in Boostnote, you can currently sort them alphabetically or by occurrence (counter). I would like to suggest a minor change in this behaviour: 

## Current behaviour: 
- Alphabetical sort is case sensitive, tags starting with Uppercase letters are listed first [A-Z], followed by tags starting with lowercase letters [a-z]

## Suggested behaviour:
- Alphabetical sort is case insensitive, tags are listed [a-Z]

## Thoughts
There is currently no support for the user by inserting tags (auto complete, suggestions, etc). I am using both lowercase tags and uppercase tags. I decide which one applies by convention. This convention is not fail prove, and I'd like to spot these differences in order to merge them when necessary.  
Example:
In a list of many tags using both upper and lowercase, the following might be merged:

    Tags     Alphabetically
    -----------------------
    # Test            5
    # test            1

**Comment by bimlas** [comment]
I think it's OK, but it should be a third option: tags starting with uppercase letter has a special meaning for me, thus I like to find those easily.

**Comment by modmod24** [comment]
I see that there are use case for the current behaviour. I think it does not justify for a third option, closing the issue now.
