### ISSUE TITLE
Random error messages popup

### ISSUE THREAD

**Issue by mokonaDesu** [BoostIO/Boostnote#22]
Sometimes when leaving boostnote open for a long period of time this happens:

![image](https://cloud.githubusercontent.com/assets/5710794/14594631/1a99d7f0-0541-11e6-81bd-ad08d53be571.png)
![image](https://cloud.githubusercontent.com/assets/5710794/14594640/2c8f7992-0541-11e6-8f1b-3f3eed5dcb6e.png)

Running win7 ultimate SP1.

**Comment by Rokt33r** [comment]
Could you re-install Boostnote? Auto-updater doesn't seem to work well. And, the version you using is a bit old.

https://github.com/BoostIO/boost-releases/releases/download/v0.5.9/Boostnote-win.exe

**Comment by mokonaDesu** [comment]
Am I going to lose my notes?

**Comment by Rokt33r** [comment]
That never happens :) re-installing will replace only app not the notes. Don't worry about that.
Only thing you should care is to check if app processes quit before re-installing.

**Comment by mokonaDesu** [comment]
Cool, that seems to have resolved the issue.

**Comment by Rokt33r** [comment]
I'm terribly sorry. I've just realized that was my fault. #25 
Auto-updater on Windows is not able to update with multiple deltas.
