### ISSUE TITLE
HTML export error

### ISSUE THREAD

**Issue by Voriaz** [BoostIO/Boostnote#2200]
# Current behavior

When exporting a note in HTML, got an error message:

![boostnote_2018-07-11_17-26-19](https://user-images.githubusercontent.com/25084999/42584646-f488729a-8533-11e8-8211-663b75a24805.png)

# Expected behavior

note exported 

# Steps to reproduce

1. create a note
2. go to (i) icon on left corner and click HTML icon
3. give a name to the file and validate

# Environment

- Version : 0.11.7
- OS Version and name : Windows 10 1607

**Comment by enyaxu** [comment]
It’bug, seem that css has wrong path.

**Comment by pikatti** [comment]
Is there a way to fix this program?
Do I need to wait for an update?
