### ISSUE TITLE
Cannot run development environment

### ISSUE THREAD

**Issue by mohsenSy** [BoostIO/Boostnote#2210]
# Current behavior

After downloading BootNote and running `yarn` and `yarn run dev-start` it just hangs on main screen and nothing is shown but this picture

![boostnote](https://user-images.githubusercontent.com/11737155/42846225-01723544-8a21-11e8-9801-2b8b94143040.png)

# Expected behavior

The application should run so I can experiment with it.

# Steps to reproduce

1. Clone BootNote repo
2. run `yarn`
3. run `yarn run dev-start`

# Environment

- Version : the one on branch master
- OS Version and name : Ubuntu 18.04

**Comment by ZeroX-DG** [comment]
Can you open the dev tool? Just hit `ctrl + shift + i` to open the developer console and take a picture for us so that we can have more clue on what error is happening

**Comment by mohsenSy** [comment]
@ZeroX-DG I managed to fix it, I just need to wait until webpack compilation is finished then hit reload.
Sorry for creating this issue I should have fixed before opening it
