### ISSUE TITLE
One cannot use Umlauts (üöä) or ß for hotkey

### ISSUE THREAD

**Issue by ablx** [BoostIO/Boostnote#2213]
# Current behavior

Using a umlaut as part of a hotkey (e.g. Show/Hide Boostnote) does not work. The save dialog says only "Error occurred"

# Expected behavior
üöäß work for shortcuts

# Steps to reproduce

1. Try to assign a hotkey with ü ö ä or ß
 

# Environment

- Version : 0.11.7
- OS Version and name : OSX High Sierra

**Comment by Rokt33r** [comment]
It's an electron issue. If it starts to support them, Boostnote also will support it.
