### ISSUE TITLE
Folders no longer show under the My Storage tab - 0.11.8.

### ISSUE THREAD

**Issue by gusgg1** [BoostIO/Boostnote#2219]
# Current behavior
The list of folders under the My Storage tab is no longer displaying, making it very hard to find your notes depending on the folder / topic

# Expected behavior
A list of all the folder to be displayed on the main interface.

# Steps to reproduce

1. Make new folder
2. Give it a name and create
3. Folder can't be found on the main interface, only accessible through "Preferences". 

- Version :
Boostnote 0.11.8
- OS Version and name :
Windows 10 - 64-bit

**Comment by Flexo013** [comment]
Bug is no longer present in the latest version of Boostnote.
