### ISSUE TITLE
Special character rendering issue

### ISSUE THREAD

**Issue by jordankaiser** [BoostIO/Boostnote#2227]
# Current behavior

It looks like there is an issue with special characters showing up in the preview. I've seen it for Javascript and PHP. 

It shows up when I do a markdown codeblock.

![screen shot 2018-07-20 at 10 10 28 am](https://user-images.githubusercontent.com/15913688/43010133-2e35f8be-8c05-11e8-97a9-a82672b96e7c.jpg)
![screen shot 2018-07-20 at 10 08 32 am](https://user-images.githubusercontent.com/15913688/43010134-2e4a5f84-8c05-11e8-8412-e2d2316f2a13.jpg)

# Expected behavior

The special characters to appears as typed in the markdown.

# Steps to reproduce

1. Type a special character such as $ in the markdown view.
2. Preview it to see the escaping issue.

# Environment

- Version : 0.11.8 (0.11.8)
- OS Version and name : macOS High Sierra version 10.13.3

Thanks!!!

**Comment by kulkarniamit** [comment]
Same behavior on Ubuntu.

#### Markdown:
![boostnote-issue-1](https://user-images.githubusercontent.com/4337938/43018552-e995216c-8c0e-11e8-8eb9-58127ecacf89.png)

#### Rendered:
![boostnote-issue-2](https://user-images.githubusercontent.com/4337938/43018574-f63f7804-8c0e-11e8-95f5-962b418bb8d0.png)

#### HTML Output
![boostnote-issue-3](https://user-images.githubusercontent.com/4337938/43018583-fbffe256-8c0e-11e8-91f7-58ee112d5ebb.png)

# Environment
Boostnote version: 0.11.8
OS: Ubuntu 14.04 LTS

**Comment by jordankaiser** [comment]
Closing in favor of this:

https://github.com/BoostIO/Boostnote/issues/2217
