### ISSUE TITLE
"No storage mount." on MacOS Mojave Beta 4

### ISSUE THREAD

**Issue by AndreiGavriliu** [BoostIO/Boostnote#2229]
# Current behavior

Added storage before switching from High Sierra to Mojave, saved everything, installed Mojave, no storage was found. Deleted the app, reinstalled it, no change.

# Expected behavior

Add storages and show notes

# Steps to reproduce

1. Go to preferences, add storages
2. Go back, no storages found
3. Go back to preferences, no storages added

# Environment

- Version : 0.11.8 (0.11.8)
- OS Version and name : MacOS Mojave Beta 4

**Comment by TKCZ** [comment]
I have the very same issue on current Manjaro Linux (Arch-based). After I start Boostnote there is only message "No storage mount" and even if I add it in Preferences it doesn't change anything. I can't use Boostnote at all as it refuses to mount anything whatsoever. What can I do to help you debug this?

**Comment by Flexo013** [comment]
Feel free to reopen (or comment on) this issue if this is still occurring.
