### ISSUE TITLE
Line wrapping breaks LaTeX equations using the aligned environment

### ISSUE THREAD

**Issue by Danmou** [BoostIO/Boostnote#2233]
# Current behavior
When long LaTeX equations using the `aligned` LaTeX environment are wrapped across multiple lines (with the new behavior introduced in #1718), the layout in the preview gets broken.

For example:

    $\begin{aligned}
      y &= \arg\max\limits_{y'} \hat P \left(y' ∣ \mathbf x\right)\\
        &= \arg\max\limits_{y'} \hat P \left(y'\right) ∏\limits_{i = 1}^d \hat P \left(x_i ∣ y'\right)\\
        &= \arg\max\limits_{y'} \left[ \log \hat P \left(y'\right) + ∑\limits_{i = 1}^d \log \hat P \left(x_i ∣ y'\right) \right]
    \end{aligned}$

Results in the following preview (when the window is sufficiently small):

![838](https://user-images.githubusercontent.com/7031745/43039021-a17c7742-8d24-11e8-90b4-952e55b174b2.png)

# Expected behavior
![839](https://user-images.githubusercontent.com/7031745/43039037-d821c69e-8d24-11e8-92ce-878d54b41d1e.png)
except the last line should wrap.

# Environment

- Version : 0.11.7
- OS Version and name : Ubuntu 16.04

**Comment by Flexo013** [comment]
This is behavior no longer occurs with Boostnote 0.13.0 Currently the line just runs out of the frame, which is not ideal, but I don't really see any other options.
