### ISSUE TITLE
Not see the character at the `create new folder`   

### ISSUE THREAD

**Issue by GrassWonder** [BoostIO/Boostnote#2234]
# Current behavior

<img width="737" alt="2018-07-22 20 32 27" src="https://user-images.githubusercontent.com/8503266/43045198-f31c72ee-8dee-11e8-8973-9bde45afa0d4.png">

# Expected behavior

we can ses the character

# Steps to reproduce

1.  click  `+` 
<img width="236" alt="2018-07-22 20 34 29" src="https://user-images.githubusercontent.com/8503266/43045202-0231d170-8def-11e8-8115-0b58f0a16eef.png">

# Environment

- Version : 0.11.8
- OS Version and name : macOS high sierra 10.13.6

**Comment by ZeroX-DG** [comment]
Fixed in the latest version. Feel free to re-open this issue if it still exists.
