### ISSUE TITLE
Boostnote beeing detected and deleted by antivirus

### ISSUE THREAD

**Issue by clementpoiret** [BoostIO/Boostnote#2238]
# Current behavior
When I want to use Boostnote, BitDefender is rising few alerts like "threat detected".
![BitDefender](https://i.imgur.com/fDP4DNZ.png)
![BitDefender](https://i.imgur.com/cFzBXT9.png)

Examples of infected files (all files from the installation seems detected):
- \appdata\roaming\boostnote\cookies is infected with Atc4.Detection,
- \appdata\roaming\boostnote\preferences is infected with Atc4.Detection,
- \appdata\local\microsoft\clr_v4.0_32\usagelogs\update.exe.log is infected with Atc4.Detection.

# Expected behavior
Boostnote should be working correctly but BitDefender Total Security 2019 is deleting some files.

# Steps to reproduce

1. Install Boostnote,
2. Install BitDefender Total Security 2019 (Trial Version here...),
3. Use Boostnote, and BitDefender will detect some files...

# Environment

- Version : Boostnote 0.11.8
- OS Version and name : Windows 10 Build 1803

**Comment by Flexo013** [comment]
@clementpoiret Is this issue still occurring with the latest version of Boostnote?

**Comment by clementpoiret** [comment]
I'm no longer using BitDefender as I completely switched to Arch Linux, so no problem anymore... I can't really give you a better answer, I'm sorry

**Comment by Flexo013** [comment]
@clementpoiret That's okay. Thanks for the info anyways!
