### ISSUE TITLE
Single quotes are rendered as `&apos;` in a code block

### ISSUE THREAD

**Issue by anhhuyalex** [BoostIO/Boostnote#2242]
# Current behavior
Single quotes are rendered as `&apos;` in a code block
![image](https://user-images.githubusercontent.com/17817335/43158407-74fe51a6-8f34-11e8-820c-ebafcc0532b4.png)

# Expected behavior
Single quotes should stay single quotes

# Steps to reproduce

1. type ' in a code block

# Environment

- Version : 0.11.8 (0.11.8)
- OS Version and name : 10.11.2

**Comment by wuliqiangqiang** [comment]
###  I have the same problem
- version: v0.11.8

**Comment by yavuz1986** [comment]
Preferences => Interface => Sanitization => Allow dangerous html tags

![image](https://user-images.githubusercontent.com/3491524/43186847-9a50edaa-8ff8-11e8-95a4-839a887a1046.png)

**Comment by solariz** [comment]
If I change to **Allow dangerous html tags**  it works. Besides the single qoute the escape also happen on $ char.

![screenshot_2018-07-25_11-47-35](https://user-images.githubusercontent.com/4168339/43193687-f559efb4-9000-11e8-820f-795fe3d39a63.png)

**Comment by solariz** [comment]
ok I see a [fix](https://github.com/BoostIO/Boostnote/pull/2240) coming, thanks.

**Comment by Rokt33r** [comment]
https://github.com/BoostIO/Boostnote/issues/2217
