### ISSUE TITLE
Someone broke the search hotkeys

### ISSUE THREAD

**Issue by Redsandro** [BoostIO/Boostnote#2245]
I've upgraded from 0.11.1 to 0.11.7 (because [0.11.8 is broken](https://github.com/BoostIO/Boostnote/issues/2217)).

Now I cannot press Ctrl+S or Ctrl+F anymore to search within notes. I need to click. Moving hands away from keyboard stifles productivity, so I consider this a regression.

Is this intentional or by mistake?

Whodunit?

Is it possible to add a test for this?

**Comment by AamerShareef** [comment]
Hi,
For linux, the focused search is now via ctl+L
I have had to look at the source, I raised a similar issue for moving to next and previous note, which is now ctl+[ and ctl+] 

Hope that helps.

**Comment by Redsandro** [comment]
@AamerShareef thank you for this tip.

I think this is quite unintuitive. The search box template content should start with the same letter as the actual hotkey.

* _Search_ for Ctrl + S
* _Find_ for Ctrl + F
* _Locate_ for Ctrl + L

**Comment by frommberger** [comment]
At least the [documentation](https://github.com/BoostIO/Boostnote/wiki/Keyboard-Shortcuts) should be updated. Hardly any of the shortcuts listed is correct.

**Comment by Flexo013** [comment]
In the current version of Boostnote this seems to be fixed.
