### ISSUE TITLE
markdown error for quote mark in code section

### ISSUE THREAD

**Issue by wonderlives** [BoostIO/Boostnote#2247]
after the recent update, the markdown for code section shows the following bug:
---
**Before update**

```python
#python
a = 'text'
b = "text"
```
will shown correctly as
`a = 'text'`
`b = "text"`

**After update**
```python
#python
a = 'text'
b = "text"
```

will shown only the double quote correctly, the single quote will shown as:
`a = &apos;text&apos`
`b = "text"`

Please kindly advise

**Comment by dsp25no** [comment]
You can use advice from 
https://github.com/BoostIO/Boostnote/issues/2244

**Comment by Rokt33r** [comment]
Close this because it is duplicated.
