### ISSUE TITLE
Scrollbar in dark Theme

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#225]
In the newest version of Boostnote on a Windows 10 machine, the scrollbar for a note is pretty much invisible when using the dark theme.

**Comment by kazup01** [comment]
Thank you for your message!
I will check it.

**Comment by LetItRock** [comment]
Hello @huettenhain @kazup01 ,
I'm working on this, soon I will create PR.

**Comment by kazup01** [comment]
Hi @LetItRock san,
Cool! I'm looking forward it🎉

**Comment by huettenhain** [comment]
This has been essentially fixed by the dark theme overhaul in 0.8.10.
