### ISSUE TITLE
Storage location removed at startup Ubuntu 18.04.1

### ISSUE THREAD

**Issue by dmorand17** [BoostIO/Boostnote#2250]
# Current behavior
I'm having an issue in Ubuntu 18.04.1 where my Storage Location keeps getting removed when I start the application.  I enabled the console, and I see an error that **boostnote.json file doesn't exist the given path**.  I've tried uninstalling the app, and re-installing but the same behavior exists.  One thing I did notice though is that when I re-install, my preferences are still in tact (theme), perhaps there's something manually I need to remove in Ubuntu to re-install?

![image](https://user-images.githubusercontent.com/2649057/43296597-3d6500fe-911a-11e8-9047-32e3cb3e638e.png)

# Environment
- Version : 0.11.8
- OS Version and name : Ubuntu 18.04.1

**Comment by Rokt33r** [comment]
Please execute `localStorage.clear()` in the console. It seems you've used a wrong storage path
