### ISSUE TITLE
Question About Pull Request That Seems Forgotten

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2256]
Blinking markdown crunch fix #2074 has been tested and verified by myself and its authors and it's still pending examinations for 2 months.

I am not criticizing the pace of reviewing these things but it is not clear to me if this was forgotten or so, it's a huge benefit for the experience of the average user and if it's practically possible it shouldn't be left behind in my opinion.

What is the status ? Thank you.

**Comment by ehhc** [comment]
you could try to mention @Rokt33r to get a quick answer :)

**Comment by infosisio** [comment]
@Rokt33r We need your input :)

**Comment by ZeroX-DG** [comment]
Merged :smile:
