### ISSUE TITLE
Syntax Highlighting: .gradle

### ISSUE THREAD

**Issue by DFelten** [BoostIO/Boostnote#2258]
Syntax Highlighting for .gradle code snippets would be great

# Environment

- Version : 1.25.1
- OS Version and name : MacOS 10.13.3

**Comment by takacsot** [comment]
Is groovy/java syntax not enough (of course if it is not in snippets) :)

**Comment by DFelten** [comment]
Groovy looks pretty good, but not really ideal.

**Comment by Flexo013** [comment]
This is something that will have to be implemented into [CodeMirror ](https://codemirror.net/mode/index.html)as that that care of our highlighting.
