### ISSUE TITLE
Make it possible to use Boostnote with the keyboard only

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#226]
Briefly put, it would be very nice to have more (configurable) Hotkeys for:

* Focussing the search field (possible default: `Ctrl`+`S`)
* Focussing the tag editor (possible default: `Ctrl`+`T`)
* Selecting the next and previous note (possible default: `Ctrl`+`Up` and `Ctrl`+`Down`)
* Switch between editor and preview (possible default: `Ctrl`+`E`)
switching to editor should move the cursor focus to the editor window.
* Deleting a note (possible default: `Del`)

This list contains the hotkeys that seem necessary to me to make Boostnote usable without the mouse, which I would consider a great boost in usability, no pun intended.

**Comment by kazup01** [comment]
This is great idea. I think these hotkeys can great usability to Boostnote, too.
Thank you for proposal!
I think that it is better for the Hotkeys to be customizable.

**Comment by asmsuechan** [comment]
Hi @huettenhain, do you know actually some shortcuts already exist (however they aren't customizable).

* Delete a note on pressed `d`
* Create a note on pressed `a`
* Edit a note on pressed `e`

I also think the shortcuts should be customizable.

**Comment by huettenhain** [comment]
Hey @asmsuechan, thanks for that info. Unfortunately, these hotkeys do not seem to work application-wide, I have to select a note in the list with the mouse to make them work. Another issue is that once you are in edit mode, there is no way to leave without using the mouse.

**Comment by asmsuechan** [comment]
I'm also bothered by the key map. Yes, I recognize those key maps work only on focused to note area. Perhaps we developers should discuss about the key map.

**Comment by asmsuechan** [comment]
Hi @huettenhain, finally I implemented the shortcuts and be released.

* Focussing the search field (Ctrl+S)
* Selecting the next and previous note (Ctrl+U and Ctrl+J)
* Switch between editor and preview (Ctrl+E)
* Deleting a note (Ctrl+Del)

Next, I try to enable customizable.

**Comment by asmsuechan** [comment]
To be customizable is the another issue, thus I close this issue. Please check https://github.com/BoostIO/Boostnote/issues/302 and comment you opinions if you're interested in customizable. Thank you!

**Comment by eleijonmarck** [comment]
Could you please make it so that you can at least show the shortcuts available. I think that some shortcuts should be default.

Of course it should be able to customize all the shortcuts. That is awesome.

Nice-to-have:
command mode (all the shortcuts for the editor, navigation within the editor)
edit mode (edit the notes)

Your notetaking app is the only one which incorporates vim. I LOVE IT. Please keep it up!!!!!

**Comment by sachinmaheshwari** [comment]
Search
- Use ctrl + s to focus on search box. Now type something there that should return atleast one result. Now without using mouse you can not open the searched note. It would be awesome if we can use up or down arrow to select and enter to open the selected note.

Switch between edit and preview mode
- Preview to edit mode is working but I'm not able to switch from edit to preview mode by using ctrl + E  

Version used: 0.8.7
OS: macOS Sierra 10.12.4
