### ISSUE TITLE
how to create a new note with emacs mode?

### ISSUE THREAD

**Issue by shuivin** [BoostIO/Boostnote#2262]
Dear Sir,
as title, i can not create new note with CTRL + N or CTRL + X - CTRL + F when i use emacs mode, 
who can help me?

**Comment by scooby** [comment]
This is a project maintained by volunteers, so you have to post issues with the intent of contributing, not with the expectation that there is a technical support department to help you.

So you need to help yourself first and do a thorough investigation: consider what things might be wrong, and then rule them each out. It would be helpful to post all this information as you go so others can benefit, again, you need to be contributing to the project, not expecting that there's a tech support department.
