### ISSUE TITLE
Add support for multi-level folders

### ISSUE THREAD

**Issue by 7e1** [BoostIO/Boostnote#2263]
Can boostnote add multi-level folders?
Examples:

```
My Storage
- folders
    - subfolder
    - subfolder
- folders
    - subfolder
    - subfolder
```

**Comment by ZeroX-DG** [comment]
Currently Boostnote doesn't support multi level folders and maybe it will not be implemented in Boostnote as the developer team is working on a new version of Boostnote and planing on implement this in the new app

**Comment by ndbeals** [comment]
@ZeroX-DG is there any public information regarding the new version (rewrite?) of boostnote?

Is there any way us users can provide input? (and maybe code if possible?)

**Comment by ZeroX-DG** [comment]
Oh, of course @ndbeals ! You can join the slack channel to discuss about the rewrite version of boostnote [slack group](https://join.slack.com/t/boostnote-group/shared_invite/enQtMzkxOTk4ODkyNzc0LThkNmMzY2VlZjVhYTNiYjE5YjQyZGVjNTJlYTY1OGMyZTFjNGU5YTUyYjUzOWZhYTU4OTVlNDYyNDFjYWMzNDM). Please join the `renewal` channel to discuss about the new app.

**Comment by Irindul** [comment]
Is there any update on this issue ? No multi-level folders support is a big turn down as it quickly becomes difficult to keep notes organised.

**Comment by Flexo013** [comment]
This feature is being discussed in #125.

As for a short update: We are very aware of the demand/popularity of this feature. Some people have shown that they are working on developing the feature (as seen in the other thread).

If you really want the subfolder feature then you can check out the new [BoostNote.next](https://github.com/BoostIO/BoostNote.next/releases/), which has this. It currently doesn't have many of the other features of Boostnote, but those will be coming in due time.

**Comment by pabrams** [comment]
> This feature is being discussed in #125.
> 
> As for a short update: We are very aware of the demand/popularity of this feature. Some people have shown that they are working on developing the feature (as seen in the other thread).
> 
> If you really want the subfolder feature then you can check out the new [BoostNote.next](https://github.com/BoostIO/BoostNote.next/releases/), which has this. It currently doesn't have many of the other features of Boostnote, but those will be coming in due time.

I don't understand - why are there two different BoostNote with separate sets of features?  It's very confusing. Why would you want this implemented here if it's already implemetned on the other?
