### ISSUE TITLE
Pasting image from clipboard to a Boostnote (Win10)

### ISSUE THREAD

**Issue by heihachi88** [BoostIO/Boostnote#2264]
Do you plan to add this kind of functionality? So i can printscreen some area of my window, then just paste it from clipboard directly to a boostnote.

**Comment by ZeroX-DG** [comment]
Which version are you using? I remember I've already implemented this feature

**Comment by Rokt33r** [comment]
Actually, we don't have it yet. It only works when the image is coming from web browser. Because we are using its URL rather than the image data.

**Comment by heihachi88** [comment]
well, would be nice to have it. For example - i just printscreen the description and just Ctrl+V to boostnote window.

**Comment by ehhc** [comment]
I'm not sure whether i missunderstand you question or the problem..
If i do the following (using WINDOWS 10):
- Press [alt]+ [print] to create a screenshot of the current window
- go to boostnote and select the editor of a note
- press [crtl] + [v] 
- -> the screenshot was embeded as a image into the note...

Other scenario:
go to MS Paint, do some image things, select all, copy all, insert it into boostnote (ctrl +v) it will also be embeded as an image to boostnote...

So the feature is already working, isn't it?

**Comment by Rokt33r** [comment]
@ehhc @ZeroX-DG Sorry, you guys are right. I misunderstood.

@heihachi88 Could you tell me which version of Windows you are using?

**Comment by heihachi88** [comment]
@Rokt33r Windows 10 (1803) latest

**Comment by heihachi88** [comment]
@ehhc if i choose markdown note, then it pastes this:

`![c784a648.png](:storage\d2733ced-6966-4e35-9d59-e01b93132fc9\c784a648.png)`

But image is not displaying.

If i paste in to snippet note - nothing happens.

**Comment by ehhc** [comment]
@heihachi88 that seems to be good.. can you press return or any other key after that? Will it be shown then? Can you check if there is any information in the developer console?

Concerning the snippet note: it is not implemented there.. :)

**Comment by ehhc** [comment]
@heihachi88 i fear it is not planed to implement it in the snippet note (due to complexity reasons..).
But you are welcome to create a new issue/feature request, asking for it. Maybe, if there are enough wishing for it, somebody will implement it.

So can you close this issue? is it fixed?

**Comment by heihachi88** [comment]
Ok, it's fixed.
