### ISSUE TITLE
Notes entering the edit mode will not flip up and down.

### ISSUE THREAD

**Issue by jiangmitiao** [BoostIO/Boostnote#2270]
# Current behavior

Click on the note to enter the edit mode. If I don't change the contents of the note, the mouse wheel scrolls and the note does not flip up and down.

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.11.8
- OS Version and name : mac os and windows

**Comment by ZeroX-DG** [comment]
I can't reproduce the problem and can you me tell me which version and OS are you using?

**Comment by ZeroX-DG** [comment]
Closed due to inactivity
