### ISSUE TITLE
Switching between tabs with Alt+tab is lagging

### ISSUE THREAD

**Issue by webcoderkz** [BoostIO/Boostnote#2271]
# Current behavior

1. Create a snippet note;
2. Inside that note create 2 notes: first with markdown type, second with javascript. Fill them both with content;
3. Try to switch between them by pressing `Ctrl+Tab` or `Ctrl+Shift+Tab`

It works for the first time, then it seems to be lagging, i only can switch back with mouse.

# Environment

- Version : 0.11.8
- OS Version and name : Windows 10 (1803)

**Comment by tomraithel** [comment]
I can reproduce this on mach and have a rough idea what is causing this Issue. I am going to have a look into that!

**Comment by Flexo013** [comment]
This no longer seems to be the case on Windows 10 with version 0.13.0.
