### ISSUE TITLE
[Feature Request] Export Storages

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2273]
There is a nice feature called `Export Folder`. I use it to export in markdown.
![image](https://user-images.githubusercontent.com/3670907/43946543-d37d6e7a-9c85-11e8-8e2c-84f9b8f5fb97.png)

Why not give an option to export the `Storage Folder`?

![image](https://user-images.githubusercontent.com/3670907/43946547-d5ede194-9c85-11e8-99e6-7781443e6dbd.png)

**Comment by zhoufeng1989** [comment]
That's a useful feature, may I give this a try?
As I can see now, only markdown files can be exported while snippets can't. Is this a feature or a bug?

**Comment by zhoufeng1989** [comment]
Related issues [#2207](https://github.com/BoostIO/Boostnote/issues/2207)
