### ISSUE TITLE
[Feature Request] Export to ONE Markdown File

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2274]
The markdown export is nice.
But every note will be exportet to a new markdown document. Please add an option to export all to one markdown document.

**Comment by ZeroX-DG** [comment]
Hmm...How will this feature be useful? Can you show me an application of this feature?

**Comment by tatoosh** [comment]
@ZeroX-DG: We're writing documentations as markdown. So by exporting them i can save the export in gitlab wiki or a document management system.

**Comment by tatoosh** [comment]
I want to organise the snippets in different bostnote notes. 
So i have to write a batch script or will you stay my request?
