### ISSUE TITLE
[bug] format table not working

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2275]
What can the format table do?
Nothing happens here on my windows 10.

![formater](https://user-images.githubusercontent.com/3670907/43947096-7111c130-9c87-11e8-80aa-ce9e2f2f3f52.gif)

**Comment by OnlineVagrant** [comment]
It only works if you change the ***Editor Font Family** to a ***Monospace font*** like ***Andalé Mono*** for example, rather than ***Segoe UI***

**Comment by AlexEshoo** [comment]
Doesn't work on linux even with monospaced font.

**Comment by modmod24** [comment]
it works for me

-----

version: 0.11.9- pure. 
os and version: Ubuntu 16.04

**Comment by AlexEshoo** [comment]
I tried boostnote v0.11.9-pre.1 as well and it did not work on that either (ubuntu 16.04).

(Also 0.11.9 seems to break edit on right click function...)

**Comment by ZeroX-DG** [comment]
Feel free to re-open the issue if this is happens

**Comment by AlexEshoo** [comment]
I upgraded to 0.11.10 and this still does not work.
Ubuntu 16.04

I even tried `Andalé Mono` font as suggested above. Clicking on "Format Table" has no effect.

**Comment by AlexEshoo** [comment]
Furthermore the "smart table editor" feature (https://github.com/BoostIO/Boostnote/pull/2312) does not work for me
