### ISSUE TITLE
[Feature Request] Export markdown with images

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2276]
Exporting of markdown files with images will not export the images.

There are only links to the storage folder.
Why not exporting the images in the subfolder `\assets` and naming it like the markdownfile with a number suffix?

**Comment by ehhc** [comment]
I think this will be fixed in the next version (it'll be the `attachments`-folder then) :)
Can you check again after the next release please?

**Comment by ZeroX-DG** [comment]
Fixed by https://github.com/BoostIO/Boostnote/pull/2257
Feel free to reopen the issue if you need.
