### ISSUE TITLE
[bug] Unnecessary anti-slash `\` appears

### ISSUE THREAD

**Issue by CicoZhang** [BoostIO/Boostnote#2279]
# Current behavior
In Edit mode:
![image](https://user-images.githubusercontent.com/11710225/43965843-a037211a-9cc0-11e8-83a8-5d33617dabd7.png)
In View mode:
![image](https://user-images.githubusercontent.com/11710225/43965882-b5261eaa-9cc0-11e8-8d1a-3c9f3f4a0924.png)

# Expected behavior
No anti-slash `\` beside the dollar sign.
# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :0.11.8
- OS Version and name : Ubuntu 18.04.1

**Comment by ZeroX-DG** [comment]
Duplicated with https://github.com/BoostIO/Boostnote/issues/2217
