### ISSUE TITLE
Snippets lose focus while editing

### ISSUE THREAD

**Issue by ian-bartholomew** [BoostIO/Boostnote#2280]
# Current behavior
When creating or editing a snippet, the field loses focus after < 1 sec of inactivity, and the first snippet is instead focused

![aug-10-2018 11-18-50](https://user-images.githubusercontent.com/1447602/43974392-485b9880-9c8f-11e8-9215-a91a6001b504.gif)
<img width="1677" alt="screen shot 2018-08-10 at 11 30 54 am" src="https://user-images.githubusercontent.com/1447602/43974974-f4ad28be-9c90-11e8-8d09-db50a288ef62.png">

# Expected behavior
The snippet you are editing should stay in focus until you click on another snippet item or navigate away

# Steps to reproduce

1. go to preferences
2. Go to Snippets
3. Make sure there is at least one existing snippet (create one if dont already)
4. Click on `+New Snippet` to create a new snippet
5. Click on the new snippet, `Untitled snippet`
6. Click on the `Snippet Name` field, and notice that you stay focused
7. Start editing the field and notice that you almost immediately lose focus and are taken back to the first snippet

# Environment

- Version : 0.11.8
- OS Version and name : MacOS 10.13.6

**Comment by ZeroX-DG** [comment]
Thank you for reporting, I'll investigate that bug.
