### ISSUE TITLE
Add Support for GDScript Syntax Highlighting

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2287]
GDScript is the scripting language that the open source game engine Godot uses.

It's a new language but wildly popular nowadays and even supported on Github. 

I think it is worth it to enable markdown and snippet syntax highlighting for it.

It is very close to Python in terms of Syntax and therefore colors.

**Comment by ZeroX-DG** [comment]
Boostnote currently use Codemirror so if you want new syntax highlight, you can submit issue in [Codemirror repo](https://github.com/codemirror/CodeMirror)
