### ISSUE TITLE
Can't read some text under dark theme

### ISSUE THREAD

**Issue by DaemonPhoenix42** [BoostIO/Boostnote#2289]
# Whilst creating a new folder the prompt is a little out of whack.

![boostnote weird](https://user-images.githubusercontent.com/36192863/44008141-d779c5a2-9e54-11e8-85ba-6e77f6e63c80.PNG)

It doesn't seem to have the same sort of issue under the "Default" Theme.

![boostnote weird2](https://user-images.githubusercontent.com/36192863/44008250-1c7fca60-9e56-11e8-952c-fabce265599d.PNG)

# Theme
Under Monokai Theme
+ Add new [My Storage]

# Operating system version
### Windows 10 Version 1709 (16299.431)
Not sure if my windows dark theme (UxStyles) is contributing so if it's just me then my bad!

### Ramble
Considering the price of Gistbox's successor "Cached" This seemed like a decent alternative next to lepton (though lepton doesn't seem to have a dark theme which is an issue for me personally), So thanks.

**Comment by modmod24** [comment]
confirmed!

-----

OS version and name: 16.04 Ubuntu
Version: 0.11.9.pre

**Comment by ZeroX-DG** [comment]
Fixed in the latest version.
