### ISSUE TITLE
Storing Notes as Markdown with YAML Frontmatter

### ISSUE THREAD

**Issue by rnuske** [BoostIO/Boostnote#2291]
# Current behavior
Storing notes in CSON files seem unwieldy (reading, indexing, ...).

# Expected behavior
Store notes as Markdown with YAML-Frontmatter in tree structure in local file system (cf. [knowledge-repo](https://github.com/airbnb/knowledge-repo), [rmarkdown](https://rmarkdown.rstudio.com/)). 

I would love to use boostnote as a personal knowledge base and for drafting new posts to company's  [knowledge-repo](https://github.com/airbnb/knowledge-repo). For both tasks a readable storage of notes or a convenient export to such a format would be needed.

# Steps to reproduce
1. create a note
2. look at it in storage in local file system

# Environment
- Version : 0.11.8
- OS Version and name : ubuntu 16.04

**Comment by ZeroX-DG** [comment]
Probably won't be implemented. However, you can suggest this issue for the team to add in the rewrite version of Boostnote! Please join our [slack group](https://join.slack.com/t/boostnote-group/shared_invite/enQtMzkxOTk4ODkyNzc0LThkNmMzY2VlZjVhYTNiYjE5YjQyZGVjNTJlYTY1OGMyZTFjNGU5YTUyYjUzOWZhYTU4OTVlNDYyNDFjYWMzNDM) at channel `#renewal`.
