### ISSUE TITLE
[bug] SQL code render isn't correct

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2296]
My code from SQL snippet will not be rendered correctly.

```sql
// alte REB Einträge entfernen
DBMS SQL UPDATE Contenit_BelegExport SET beleg_reb = '2' WHERE  (beleg_reb = '1' AND beleg_id = ':beleg_id' AND beleg_type = ':beleg_type' AND transfer_status = 1)
```

Boostnote:
![image](https://user-images.githubusercontent.com/3670907/44081711-a9a38c1a-9faf-11e8-8685-ad24c0ae079c.png)

Boostnote preview:

![image](https://user-images.githubusercontent.com/3670907/44081737-bd05b13e-9faf-11e8-93d4-b3bdcd38e4bd.png)

**Comment by ZeroX-DG** [comment]
Which version of Boostnote are you using?

**Comment by tatoosh** [comment]
Last stabile windows, musst be .18

**Comment by mdusher** [comment]
I'm also seeing this. It's seems to be converting apostrophes to HTML entities.
It just seems to be in code blocks in general because I've got it doing it with languages other than SQL as well.

I'm using 0.11.8

**Comment by ZeroX-DG** [comment]
[The fix for this bug](https://github.com/BoostIO/Boostnote/pull/2230) is in version 0.11.9 which is still in pre-release state. You can wait until the stable version is out.
