### ISSUE TITLE
[Feature Request] Autoexport

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2297]
The Android App development sleeps a long time.
So mabye we can open the markdown files with an altrenative editor on the mobile devices.

For that step it would be nice to auto export all boostnote notes to markdown to a subfolder.
With the help of nextcloud / webdav etc. we can sync and open the exportet files.

**Comment by tatoosh** [comment]
Yes, my whole boostnote storage is in my nextcloud folder. But in mobile App u van Not Chance folder. Also the boostnote extension is Not a default ohne, so a 3rd Party app can Not open the files directly.

**Comment by Flexo013** [comment]
Let's continue this feature request over here: #1250
