### ISSUE TITLE
Checkboxes not shown in shared note

### ISSUE THREAD

**Issue by kakajika** [BoostIO/Boostnote#23]
Hello, 
I found that checkboxes are not shown when I see shared notes on browser.

![image](https://cloud.githubusercontent.com/assets/1480480/14698463/07f719ba-07ca-11e6-911c-1a431553ef2c.png)

When I edit notes in Boostnote, they are surely shown.

Thank you.

**Comment by Rokt33r** [comment]
Thanks for your reporting!

**Comment by Rokt33r** [comment]
Sorry to inform the news. Boostnote server won't support sharing note on web anymore.
Instead of it, we will give you an option to share on Gist soon.
