### ISSUE TITLE
Drag & drop note from a folder to an other

### ISSUE THREAD

**Issue by Kingbalou** [BoostIO/Boostnote#230]
Hi ,

It will be nice if we could change note from a folder to an other folder by dragging them.

Thx for the app btw ;)

**Comment by kazup01** [comment]
Thanks for message👏
Please check #197 . We will improve it!

**Comment by kazup01** [comment]
@sosukesuzuki added it on #374 🎉 
We will add it at next update! Thank you for your reporting @Kingbalou san!
