### ISSUE TITLE
[Feature Request] Show date / timestamp in note view

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#2305]
Boostnote shows the hour or a short date like `2d` or `21h` in the note view.
Can u please add the option to show the timestamp?

**Comment by AlwaysKamin** [comment]
So are you thinking like this? And then have an option of some sort in the preferences panel to swap between that and the default option?

<img width="282" alt="screen shot 2018-09-19 at 4 09 23 pm" src="https://user-images.githubusercontent.com/8315826/45778358-67bcb680-bc26-11e8-9aec-fbe506836a5b.png">

**Comment by SofiaCardosoMartins** [comment]
Hi there! Me and @amrpcosta are really interested in this issue. Could we offer some help?
Thanks in advance :smile_cat:

**Comment by Flexo013** [comment]
This feature is present in the latest version of Boostnote
