### ISSUE TITLE
Suppress `update found` notifications

### ISSUE THREAD

**Issue by annakocheshkova** [BoostIO/Boostnote#2306]
# Current behavior
Right now "Update found" dialogs pop-up every so often and interrupt my work by taking the focus away from the window I am in.
Really frustrating!

# Expected behavior
Could you please add an ability to turn off "Update found" dialogs or at least change their behavior?

# Environment
Windows

**Comment by mather** [comment]
Same problem on macOS 10.13.
It always happens when I changed wi-fi AP.

**Comment by Rokt33r** [comment]
https://github.com/BoostIO/Boostnote/issues/2827 will cover this issue.
