### ISSUE TITLE
Users might think "All files gone!" if changed username (home directory name)

### ISSUE THREAD

**Issue by kawmra** [BoostIO/Boostnote#2309]
If change a username of Mac (maybe also Linux), the home directory name is changed as well.
The old username's home directory doesn't exist, Boostnote will try to create a directory to there.
(because most users are using default setting that uses the home directory as My Storage.)
But Boostnote cannot create that directory, Boostnote will report an error about has not permission to write to there in the console.
But users might not aware that error messages, so users might think "oh, all of my files gone!".

So my proposal is: Boostnote should tell users that the app can't write to specified storage directory by showing a message to users like "you need to change the storage directory or grant write permissions to".

# Environment

- Version : 0.11.8
- OS Version and name : macOS Sierra

**Comment by modmod24** [comment]
you were probably installing boostnote for a different user account. try adding both users too the same usr group or install boostnote for all users.

**Comment by modmod24** [comment]
the thing is, user A should not know about the files of user B.

**Comment by kawmra** [comment]
Sorry for my ambiguous comment.

The point is that the boostnote cannot create a directory to where have not write permission but the boostnote doesn't show up any message that explains what happening now (failed to create the directory).
The home directory example is just an example.
But if you use `~/boostnote` as My Storage and you change your username, that will happen.

**Comment by Flexo013** [comment]
When changing your username one should expect stuff like this. The user should take care of their own storages before changes.
