### ISSUE TITLE
Backslash parsing to yen

### ISSUE THREAD

**Issue by garmede** [BoostIO/Boostnote#2315]
# Current behavior

![image](https://user-images.githubusercontent.com/2133201/44374842-6d41b680-a52b-11e8-8491-390b2c07392a.png)

with KaTeX error

# Environment

- Version :0.11.8
- OS Version and name :Windows 7

**Comment by ZeroX-DG** [comment]
See https://github.com/BoostIO/Boostnote/issues/2310
