### ISSUE TITLE
Add Graphviz support

### ISSUE THREAD

**Issue by boulund** [BoostIO/Boostnote#2324]
I saw that there's support for plantuml and flowcharts and stuff, but I can't seem to find anything about [GraphViz](https://www.graphviz.org/) support in Boostnote. Would it be hard to add? 

I have lots of previous notes containing graphviz code that I would love to be able to render inside Boostnote!

**Comment by dimat** [comment]
plantuml already supports raw dot diagrams. You can write something like:
```
@startuml
digraph G {
a -> b
}
@enduml
```

**Comment by boulund** [comment]
Great, I didn't know that! I stopped using Boostnote many months ago, but I really appreciate you taking the time to reply. Thank you!
