### ISSUE TITLE
Allow 'Search'/Filelist section to be collapsed

### ISSUE THREAD

**Issue by 0xdevalias** [BoostIO/Boostnote#2331]
Currently it is possible to collapse the main 'notes menu' section, but the 'search'/'filelist' section can't be collapsed, which results in a decent chunk of screen space being wasted when it isn't needed.

![image](https://user-images.githubusercontent.com/753891/44561806-e1819180-a799-11e8-887d-3ffe5ee41d25.png)

It would be awesome if this was also able to be collapsed, leaving the focus on just writing my note. One style I have found particularly useful is in JetBrains products, where each 'section' collapses down to a 'sidebar tab', that can be collapsed when not needed:

![image](https://user-images.githubusercontent.com/753891/44561858-142b8a00-a79a-11e8-80d5-bd15e26c4933.png)
![image](https://user-images.githubusercontent.com/753891/44561865-1beb2e80-a79a-11e8-9c55-1ae2cf0acc3c.png)

**Comment by ZeroX-DG** [comment]
Have you try hitting ctrl + b ?

**Comment by ZeroX-DG** [comment]
Yeah, I didn't know it exist at first. Actually, I forgot how I know about that shortcut at the first place :smile: I also think it's a good idea about the chevron, if you can, please help us with that feature. Or else I will add it when I have the time.

**Comment by 0xdevalias** [comment]
After you mentioned the shortcut, I did find it under the `View -> Toggle Sidebar` menu, so it's semi discoverable (if I look properly :p) But yeah, I think chevron would improve the UX as well.

Unfortunately I don't really have spare capacity to contribute to new projects at the moment, so I'll have to leave it on the backburner for when you're able. Thanks :)
