### ISSUE TITLE
Problem when rendering dollar sign ($) and single quotes ('')

### ISSUE THREAD

**Issue by iraklisg** [BoostIO/Boostnote#2332]
# Current behavior

When writting a dolar sign `$` in the editor, it is shown prefixed with a back-slash `\` in preview mode

![image](https://user-images.githubusercontent.com/3668360/44568079-e1739880-a77d-11e8-82d3-6a8dad5a92a0.png)

Moreover, when writting single quotes, it is shown as `&apos;`

# Expected behavior
To parse the code block correctly 

# Steps to reproduce

1. Open Boostnote
2. Type the following in the editor pane:
  ```php
    $foo = 'bar';
  ```
3. See the preview pane

# Environment

- Version : Boostnote 0.11.8
- OS Version and name : Debian GNU/Linux 9 (stretch)

**Comment by ZeroX-DG** [comment]
This bug will be fixed it the next version v0.11.9 . Thank you for reporting!
