### ISSUE TITLE
Prevent escaping '$' (dollar) sign in markdown code snippets

### ISSUE THREAD

**Issue by dpjayasekara** [BoostIO/Boostnote#2333]
Is there a workaround to prevent getting certain characters (dollar, slash etc.) escaped in code snippets? I moved a lot of markdown cheatsheets from another app to Boostnote, but most of them are messed up due to this. Is this an issue?

Expected behavior:
```
$ sudo mycommand
```

Current behavior:
```
\$ sudo mycommand
```
Please see the following screenshot.

<img width="1101" alt="screen shot 2018-08-24 at 12 00 23 pm" src="https://user-images.githubusercontent.com/1533286/44568643-50102080-a795-11e8-81b7-325640b8c6fb.png">

**Comment by dpjayasekara** [comment]
Found it. It was just a configuration. Go to Preference -> Interface, and under Sanitization, select "Allow dangerous html tags". 

<img width="579" alt="screen shot 2018-08-24 at 3 52 26 pm" src="https://user-images.githubusercontent.com/1533286/44580042-0edc3880-a7b6-11e8-9374-af583f7adbdb.png">

Although it looks dangerous, all your code blocks will be messed up if you don't change that configuration. 

Before changing the configuration:
<img width="1120" alt="screen shot 2018-08-24 at 3 51 26 pm" src="https://user-images.githubusercontent.com/1533286/44580058-1e5b8180-a7b6-11e8-9e25-84d4f9426ef7.png">
After changing the configuration:
<img width="1073" alt="screen shot 2018-08-24 at 3 55 41 pm" src="https://user-images.githubusercontent.com/1533286/44580077-30d5bb00-a7b6-11e8-9d7a-0e663a88e847.png">

**Comment by mikesun23** [comment]
good job man, search through all the docs, it is really about to affect my productivity and I see this solution. Thanks!
