### ISSUE TITLE
Over-aggressive Autoclosing (back ticks, asterisks, quotes)

### ISSUE THREAD

**Issue by jstobin** [BoostIO/Boostnote#2334]
# Current behavior
If trying to create a bulleted list the current behavior always enters two asterisks, when trying to close a code block or edit back ticks it aggressively adds 6 back ticks. I believe other characters are impacted but asterisks and back ticks are two I hit many times daily. 

This enhancement may be related:
https://github.com/BoostIO/Boostnote/issues/1428
<img width="529" alt="screen shot 2018-08-24 at 12 53 21 am" src="https://user-images.githubusercontent.com/12701269/44572254-21b02800-a738-11e8-933f-9eae45432c08.png">

# Expected behavior
Smarter detection autoclosing. Not exactly sure how to resolve but some ideas:
 * Detect if closing an open block (quotes seem to behave correctly)
 * When typing an asterisk, detect if the first character is a space (indicating a list) and remove the extra asterisk

# Steps to reproduce

Asterisks
1.  Open editor
2.  Try and make a bullet list
3.  Note the extra asterisk

Back Ticks
1. Open a file with existing (```) code blocks.
2. Try and edit either end of the code blocks.
3. Get buried in back ticks. 

# Environment
- Version : 0.11.8
- OS Version and name : macOS High Sierra

**Comment by nesmyslny** [comment]
:+1:  #2249 is also related to that.

**Comment by ZeroX-DG** [comment]
You can now customize this by removing the `**` from setting.
![image](https://user-images.githubusercontent.com/12984316/56135792-9563b580-5fe5-11e9-8a86-f14e8d979d22.png)
