### ISSUE TITLE
Full preview mode

### ISSUE THREAD

**Issue by petrkrejcik** [BoostIO/Boostnote#2339]
I would like to read my notes in a **full preview mode**.

Currently there are two views on a note:
- Split view (edit + preview)
- Full edit view

The toggle for switching the view mode should be changed to support 3 options.

**Comment by modmod24** [comment]
already supported as Fullscreen `Ctrl + B` and full screen `F11`

-----

Version: 0.11.9-pre.1
OS Version and name : 16.04 Ubuntu

**Comment by petrkrejcik** [comment]
`Ctrl + B` hides the sidebar

`F11` toggles fullscreen

The result looks like this:

![image](https://user-images.githubusercontent.com/5626914/44621168-95ba0f80-a8a1-11e8-8279-8da027f0a97a.png)

My goal is to hide the left side of the screen. Keep only the markdown preview (the right side of the screen). Your solution doesn't solve it.

I'm using MacOS. Maybe the feature is supported on Ubuntu and is missing in MacOS?

**Comment by ZeroX-DG** [comment]
Have you tried the green switch on the top right of the note.

**Comment by petrkrejcik** [comment]
I have achieved the full preview clicking on the green toggle and then somewhere else. It's rather a bug than a feature, because anywhere I click the view is toggled between edit and preview.
I think it is the same issue as reported here: #2196 

![toggle](https://user-images.githubusercontent.com/5626914/44623071-ed6a7200-a8c5-11e8-899d-a53c7c6ca9d1.gif)

**Comment by modmod24** [comment]
you can change the behaviour in the preferences settings.

**Comment by petrkrejcik** [comment]
> you can change the behaviour in the preferences settings.

@modmod24 Modifying `Switch to Preview` option in preferences helped.

Thank you, issue solved.

**Comment by mokeyish** [comment]
I download the latest yesterday.  There are still two views on a note:
- Split view (edit + preview)
- Full edit view

**I clicked somewhere else, It was not change to full preview view.**  @petrkrejcik
