### ISSUE TITLE
Ways to easy edit MD formating

### ISSUE THREAD

**Issue by nadise** [BoostIO/Boostnote#234]
This program is my dream program, always wanted something like this (the closest thing is OneNote but is bulky and more word-like), i have some suggestions:

- Add an easy way to access MD formating:
     - By shortchuts, for example CTRL + B in a word to make it bold 
     - Rightclick > list of options (bold, code block, code, italic, etc)

- Store images in folders, for example if you make a section called "Quick Notes" you get a folder called Quick Notes and all the offline images (in hard drive) from all the notes of the section Quick Notes can go the Quick Notes/images folder, this way is easy to "carry" these sections with all the notes AND images.

- Drag & Drop Images

- The UI is beautiful but i feel the section "folders" would be far better on top so the interface doesn't eat so much horizontal space. Kinda like OneNote. Sections(folders) on top vertical and notes on left horizontal.

I love the program and i think is headed on a good direction

**Comment by asmsuechan** [comment]
Sorry for long absent @UltimateRandom. I think so, Anyway MD input auxiliary is good for us. And **Store images in folders** sounds good, because "Drag & Drop Images" was already implemented. Umm, thanks for layout feedback, we try to discuss it.

**Comment by Flexo013** [comment]
I have created a separate issue for your first suggestion. The images are currently stored on a per note basis and we have exporting of notes available on a per folder basis. Drag & drop images is implemented.

As for the UI, the sidebar is entirely collapsible with (Ctrl/Cmd+B by default) giving you the full horizontal space of you screen.
