### ISSUE TITLE
Code Highlighting Delays

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2341]
# Current behavior

There are a lot of random delays for the code highlighting to render the colors.

This is a user experience barrier and a solution needs to be eventually found for the benefit of users.

With the pull requests of max-buranbaev, tremendous progress has been made in this area.

Unfortunately from time to time, specifically:

- when the program is starting
- when the program is under load
- when switching screens like folders

You see the highlighting delay here and there.

There is no reason users should experience such glitches.

# Environment

- Version : Latest
- OS Version and name : All OS

**Comment by Flexo013** [comment]
This no longer seems to be an in issue. Version 0.13.0
