### ISSUE TITLE
Deleting a Note Prompts for new Note Creation

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2343]
# Current behavior

Deleting a note prompts for new note creation regardless of the order of the note. 
(it switches to the screen that shows when there are no notes)

# Expected behavior

Switch to the next available note.

# Environment

- Version : Latest
- OS Version and name : Linux, Ubuntu 18.04

**Comment by mikaoelitiana** [comment]
I could not reproduce this anymore in latest `master`, it may have been already solved

![deleting-note](https://user-images.githubusercontent.com/674667/44652911-834cec80-a9ed-11e8-9a03-e6b6bc123590.gif)

**Comment by infosisio** [comment]
@mikaoelitiana I have just tested this again on a fresh Ubuntu installation, the issue happens both with compiled version from master and the from the one pre-compiled from the site.

**Comment by modmod24** [comment]
@infosisio could it be that it only happens when the selected folder is empty? This is intended behaviour.

**Comment by infosisio** [comment]
@modmod24 No it happens in all cases, empty or not.

**Comment by jacobherrington** [comment]
I can replicate this on Mac OS with master, will take a stab at fixing it.
