### ISSUE TITLE
How to set default language for code snippet note?

### ISSUE THREAD

**Issue by 181** [BoostIO/Boostnote#2349]
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by 181** [comment]
What I means is, whenever I copy a new snippet into BoostNote, I have to choose the language type to have the syntax highlight, is there a way to choose one language like php as default, not the text as default.

**Comment by daiyam** [comment]
~~~
```php
```
~~~

**Comment by ZeroX-DG** [comment]
@daiyam that's the code in markdown note, he's talking about the code snippet note. Currently there's no way to set the default language for code snippet note. Maybe someone can implement it.

**Comment by daiyam** [comment]
oh! Sorry about that! That should be fairly simple. I will take a look.

**Comment by laike9m** [comment]
Was wondering, is there a way to add some information to a markdown note which can set the default lang for code block?
