### ISSUE TITLE
Code snippet (ruby): wrong apostroph and question mark interpretation

### ISSUE THREAD

**Issue by raddol** [BoostIO/Boostnote#2353]
# Current behavior
Apostroph and question mark is badly interpreted in code snippet.
i.e.
```ruby
wait_until(timeout: 10, message: 'Waiting for all notifications to be closed?')
```
gives &apos and \? for them.

![screen shot 2018-08-31 at 11 17 56 am](https://user-images.githubusercontent.com/42863389/44904503-c7066580-ad0f-11e8-8af1-ce5dbb144e5e.png)

# Expected behavior
It is displayed: 'Waiting for all notifications to be closed?'

# Steps to reproduce

1. input:
```ruby
wait_until(timeout: 10, message: 'Waiting for all notifications to be closed?')
```

# Environment

- Version : Boostnote 0.11.8
- OS Version and name : Mac OS 10.12.6

**Comment by ZeroX-DG** [comment]
This issue is solved in https://github.com/BoostIO/Boostnote/pull/2230 and will appears in v0.11.9
