### ISSUE TITLE
Prefix the String with $ in C#mode

### ISSUE THREAD

**Issue by zzxxhhzxh** [BoostIO/Boostnote#2354]
# Current behavior
When input "$" in ```c#, "$" will become "\$" in the preview, as shown in following fig.

![untitled](https://user-images.githubusercontent.com/42593813/44929693-7f88d500-ad21-11e8-99ef-00ab25f491d6.jpg)

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.11.8
- OS Version and name : Win 10 64bit Home

**Comment by ZeroX-DG** [comment]
This issue is solved in https://github.com/BoostIO/Boostnote/pull/2230 and will appears in v0.11.9
