### ISSUE TITLE
Reconsiering default hotkeys in macOS

### ISSUE THREAD

**Issue by 0xBADDCAFE** [BoostIO/Boostnote#2361]
# Current behavior

In macOS, "Toggle editor mode" default hotkey is assigned Cmd+M. But it conflicts macOS's "Minimize the front window to the Dock." default hotkey so do not works on Boostnote.

Refs: https://support.apple.com/en-us/HT201236

And "Show/Hide Boostnote" default hotkey is assigned "Cmd+Alt+L". If another application also use this keybinding, "Show/Hide Boostnote" hotkey works system-widely, so the app's hotkey do not work. Overriding system-wide hotkey by default keybinding confuses user. So I think this hotkey should disabled by default.

(Note: "Cmd+Alt+L" used by IntelliJ platform to call "Auto formatting code". Boostnote is programmer friendly, so not a few people uses with IntelliJ platform.)

Of course, these keybinding can change, but if clear to want to disable, causes another issue's problem (https://github.com/BoostIO/Boostnote/issues/2153)

# Expected behavior

"Toggle editor mode" default hotkey is assigned without Cmd+M.

"Show/Hide Boostnote" default hotkey is disabled.

# Steps to reproduce

1. keydown Cmd+M
2. minimize Boostnote and do not toggled editor mode.

- - -

1. Open another application that has "Cmd+Alt+L" keybinding
2. keydown "Cmd+Alt+L"
3. Boostnote is focused and another app do not have effects.

# Environment

- Version : 0.11.8
- OS Version and name : macOS High Sierra 10.13.6

**Comment by Rokt33r** [comment]
Close this in favor of https://github.com/BoostIO/Boostnote/pull/2437
