### ISSUE TITLE
New note Hotkey not working on Trash tab

### ISSUE THREAD

**Issue by Djdany95** [BoostIO/Boostnote#2367]
# Current behavior
![Screenshot](https://user-images.githubusercontent.com/665102/45079205-2b4f6d80-b0f2-11e8-89f5-1a15800a7a88.JPG)

Does nothing when do Ctrl+N in Trash section, while working good in other sections.

# Expected behavior
Pulse Ctrl+N to create a new note like in others sections.

# Steps to reproduce

1. Open boostnote.
2. Go to Trash section.
3. Pulse Ctrl+N.
4. Nothing happens.

# Environment

- Version : 0.11.9
- OS Version and name : Windows 10

**Comment by ehhc** [comment]
Can you give me one valid use-case in which you want to create a note that should be marked as deleted directely??????? 😕

**Comment by djdany01** [comment]
Yes, totally unnecessary but the message is there so, maybe delete the message or implement the functionality. :confused:

**Comment by modmod24** [comment]
related use-case: #2186

**Comment by Flexo013** [comment]
I don't see much support for this feature, and since there doesn't seem to be any valid use-case, so I'm closing this as won't fix.
