### ISSUE TITLE
Scroll lag with Electron based apps

### ISSUE THREAD

**Issue by heihachi88** [BoostIO/Boostnote#2370]
Boostnote is affected too, workaround is to minimize and maximize window.

VSCode had similar bug: https://github.com/Microsoft/vscode/issues/13612

Every electron app is affected by this issue.

Scroll just lagging heavily, so you can't properly scroll at all.

**Comment by heihachi88** [comment]
Good news, but when it will be in a stable channel?

**Comment by daiyam** [comment]
@heihachi88 it should be in October since its other name is [`Windows 10 October 2018 Update`](https://blogs.windows.com/windowsexperience/2018/08/31/announcing-windows-10-insider-preview-build-17751/)

**Comment by ZeroX-DG** [comment]
Feel free to switch to linux (highly recommend) and re-open this issue if you think it related to Boostnote :smile:
