### ISSUE TITLE
Inline code is hard to see. Better distinction is needed.

### ISSUE THREAD

**Issue by TMorville** [BoostIO/Boostnote#2373]
# Current behavior

Inline code with backticks does not work for themes other than default and white. For monokai and solarized dark, it looks exactly like issue #208.

![screen shot 2018-09-06 at 11 53 59](https://user-images.githubusercontent.com/4254061/45150442-2c54cd80-b1cc-11e8-9690-8a76c0e880c0.png)

<img width="858" alt="screen shot 2018-09-06 at 11 53 21" src="https://user-images.githubusercontent.com/4254061/45150452-2f4fbe00-b1cc-11e8-934d-493fef4bb64d.png">

# Expected behavior

That code is formatted correctly inline.

# Steps to reproduce

1. Start a markdown node
2. Write This is an example of `inline code`
3. Change theme

# Environment

- Version : 10.12.6
- OS Version and name : OSx Sierra

**Comment by randman1** [comment]
It seems that you already have a handle on this issue but I wanted to provide some additional information. I also feel that inline code and unformatted block code is difficult to see when using the dark theme. I tried to correct this with custom CSS and found that some elements are being overridden. Below is my custom CSS for testing:

```
/*
Dark interface theme overrides custom CSS for some elements.
The below custom CSS properly decorates both inline and block code
for all interface themes except for Dark. When Dark theme is selected:
	* inline code font color and background-color is overridden
	* block code font color is overridden
*/

body[data-theme] code {
 background-color: orange;
 color:white;
}

pre.codemirror {
 background-color: orange;
}
```

**Comment by ZeroX-DG** [comment]
@randman1 is this issue still exists? if not can you close the issue?

**Comment by DenisTome** [comment]
yes, I have the same problem

**Comment by ZeroX-DG** [comment]
Close due to inactivity.

**Comment by jokera666** [comment]
The bug is still exist.

**Comment by Cursea** [comment]
The background colour for inline code in dark themes is still too subtle - tested with the Dracula theme, and the bug is still present.

This issue should be re-opened.

**Comment by brandonfosso** [comment]
Yeah, this is still an issue. The change for inline code is essentially invisible for dark themes and is very subtle for the default scheme.
![image](https://user-images.githubusercontent.com/7997179/61738812-ba886280-ad50-11e9-80ba-81ec09d0837f.png)
![image](https://user-images.githubusercontent.com/7997179/61738707-7f862f00-ad50-11e9-9ff7-0770e7316dc1.png)
I think even github's `coloring` is pretty weak.
Would it be possible to get something like slacks:
![image](https://user-images.githubusercontent.com/7997179/61738969-194ddc00-ad51-11e9-991b-d6fa5696224e.png)
That would make it a lot more readable.
Thanks for your help!

**Comment by Flexo013** [comment]
Agreed that just changing the font is not enough with the default Dark settings. Something should be changed about the styling of inline code to make it more distinct.

**Comment by jtruman88** [comment]
Until there is an actual fix in place, I just wanted to mention that the styles can be manually overridden in Preferences > Markdown. Find the CSS for `code` then just adjust the `background-color` (and other styles) to something more to your liking.

**Comment by arcturus140** [comment]
@ZeroX-DG would custom CSS also be an accepted solution? Coincidentially I made a robust solution for this today for myself:

![image](https://user-images.githubusercontent.com/44707562/74480836-91c0e980-4ea9-11ea-9a12-f476fc68e9cc.png)

![image](https://user-images.githubusercontent.com/44707562/74480919-b4eb9900-4ea9-11ea-82c3-877d6567b5c1.png)

**Comment by ZeroX-DG** [comment]
@arcturus140 wow that looks cool, yes I think we can put it as a default value for the custom CSS. It would be easier and user can customize it too.

**Comment by arcturus140** [comment]
ok, I'll add it to my task list for tomorrow.
