### ISSUE TITLE
export folder as markdown with pictures

### ISSUE THREAD

**Issue by Jayang1998** [BoostIO/Boostnote#2374]
# Current behavior
If I write a note in Boostnote and i insert picture(s) in this note ,when i choose to export this note as markdown file,i will see that these pictures are missing(pictures are not copied to the destination folder and the picture  link in markdown file are not changed )

# Expected behavior
all the pictures are exported to destination folder and the link in md file are changed to correct
# Steps to reproduce

# Environment

- Version : 0.11.9
- OS Version and name :win10 pro

**Comment by ehhc** [comment]
Can you give an example of the content of the note before you've exported it (like it is in Boostnote) and of the content of the exportet markdown file?

Is there an error in the developer console?

**Comment by Jayang1998** [comment]
Of course,If in export my note to markdown in detail window like picture1,all the attachment will be ok,but if i exported a who folder like picture2,all the pictures are missing.My desktop environment is chinese and i hope it won't make trouble in your understanding。Thank you
![7r ko3 pbhecb _2j9 etwl](https://user-images.githubusercontent.com/28175310/45155839-dbb29400-b20e-11e8-8278-89dc38cf26f3.png)
![kimpbtjp ldsf_t g6ml wy](https://user-images.githubusercontent.com/28175310/45156081-b1150b00-b20f-11e8-9461-5d9e77e68ef9.png)

**Comment by ehhc** [comment]
Ah okay. The problem only happens when you export a whole folder?
I will have a look at it when i have time :)

**Comment by Jayang1998** [comment]
yes
thanks
