### ISSUE TITLE
[bug] markdown not rendered correctly

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2375]
# Current behavior

Markdown not rendered correctly. Not sure if this is a known issue. My apology if it has been reported before.

![markdown_error](https://user-images.githubusercontent.com/25648628/45159052-a93c7300-b1dd-11e8-9723-11468dac093f.png)

# Expected behavior

```
git remote set-url origin --push --add <a remote>
git remote set-url origin --push --add <another remote>
```

markdown in this section messed up

code section even more messed up
```
git remote set-url origin --push --add <a remote>
git remote set-url origin --push --add <another remote>
```

# Steps to reproduce

1. create note
2. copy and paste markdown posted below

-----

\`\`\`
git remote set-url origin --push --add <a remote>
git remote set-url origin --push --add <another remote>
\`\`\`
markdown in this section messed up

code section even more messed up
\`\`\`
git remote set-url origin --push --add <a remote>
git remote set-url origin --push --add <another remote>
\`\`\`

-----

# Environment

- Version : 0.11.9
- OS Version and name : 16.04 Ubuntu

**Comment by modmod24** [comment]
Update

-----

due to issues in 0.11.8 I set Sanitization to "Allow dangerous html tags". I no longer need this in 0.11.9 and changing the setting to anything else works fine.

**Comment by ZeroX-DG** [comment]
Solution: If you're having `Allow dangerous html tags` on in your setting then turn it off. However, this is still a bug so I'll let this issue open till me or someone found the fix for it.

**Comment by ZeroX-DG** [comment]
In any case, I'll close this issue until someone able to reproduce this issue
