### ISSUE TITLE
Update is not working

### ISSUE THREAD

**Issue by ihorskyi** [BoostIO/Boostnote#2376]
# Current behavior
App starts and says there are updates available, but then nothing happens. When I run it from terminal I'm able to see the error

```
2018-09-06 13:17:44.942 Boostnote[51162:10033841] Download completed to: file:///Users/mpc/Library/Caches/com.maisin.boost.ShipIt/update.ClvFFat/Boostnote-mac.zip
{ Error: Could not locate update bundle for com.maisin.boost within file:///Users/mpc/Library/Caches/com.maisin.boost.ShipIt/update.ClvFFat/ code: 2, domain: 'SQRLUpdaterErrorDomain' }
```

- Version : 0.11.8
- OS Version and name : MacOS Sierra 10.12.6

**Comment by modmod24** [comment]
hi @ihorskyi mac users should download it manually.

**Comment by ZeroX-DG** [comment]
With the current release Mac users should download it manually.
