### ISSUE TITLE
Shortcut to make text a multiline quote

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2377]
I think it would be nice to have a tool to format text as quotes. For example, select a paragraph and format it as a quote. 

For example, transforming this text: 

Imagination is more important than knowledge.
Life is like riding a bicycle. To keep your balance you must keep moving.
Look deep into nature, and then you will understand everything better.

into:
```
> Imagination is more important than knowledge.
> Life is like riding a bicycle. To keep your balance you must keep moving.
> Look deep into nature, and then you will understand everything better.
```

rendered as:
> Imagination is more important than knowledge.
> Life is like riding a bicycle. To keep your balance you must keep moving.
> Look deep into nature, and then you will understand everything better.

**Comment by ehhc** [comment]
why don't you just add ">"-characters in front of your quote? What tool do you need besides a keyboard?

**Comment by mbarczak** [comment]
I like this idea. @ehhc , it would be just for sake of convenience. We could prepare a whole toolbar with handy shortcuts, similar stuff github is doing in the comment editor : 
![image](https://user-images.githubusercontent.com/1899533/45207785-443e5700-b289-11e8-9b4d-24ba41f619fe.png)

**Comment by modmod24** [comment]
@ehhc ,
I see now what you mean. I wasn't aware a single `> ` is needed for multi-line quotes. 
When writing a quote in the markdown editor, Boostnote automatically adds `> ` to every consecutive line. 

To mark a large text block as quote a single `> ' would be sufficient, as long as there are no empty lines. Empty lines can even be added afterwards within the quote. 

Overall, this is very efficient. What I had in mind was similar to @mbarczak (though I prefer keyboard shortcuts). I could not find an open issue for that, but I find that this should be closed and rephrased in a new issue, or we should change label here from `feature request` to `discussion`.
