### ISSUE TITLE
[Feature Request] Snippet note together with markdown notes

### ISSUE THREAD

**Issue by DFelten** [BoostIO/Boostnote#2378]
For me a great improvement for Boostnote would be the ability to add also Markdown notes to a snippet collection. So there would be a tab within the snippet collection with a formatted markdown note.

I've created for example a markdown note for describing tests for Android and an other snippet collection for some large test helper classes. It would be great if I could combine them. Of course a really large Markdown note is possible, but not clear.

# Environment

- Version : 0.11.8
- OS Version and name : MacOS 10.13.3

**Comment by ZeroX-DG** [comment]
Yeah, why don't you create a md file and paste your note in? If it solve your problem, then can you close this issue?

**Comment by DFelten** [comment]
Oh, I didn't know that the snippets can have file extension. Great, then this issue is solved, because the markdown snippet is then formatted as a markdown.

**Comment by ZeroX-DG** [comment]
I think it's fixed here: https://github.com/BoostIO/Boostnote/pull/2226
