### ISSUE TITLE
How to upgrade manually on mac?

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [BoostIO/Boostnote#2387]
I can't upgrade to the newest version in my mac. I saw in the forum that mac users need to upgrade manually. But, 
Can you give a clear step by step explanation of the process?
I'm worried of loosing my notes if I make any mistake.

Many thanks,
Alexis

**Comment by ghazal** [comment]
+1 here

**Comment by daiyam** [comment]
@AlexisEspinosaGayosso @ghazal you should just install the newer version available [here](https://github.com/BoostIO/boost-releases/releases).
What's the problem?

**Comment by caikovsky** [comment]
Same here. It notifies properly, but nothing changes.

MacOS 10.13.5

**Comment by daiyam** [comment]
@ghazal yes, I've had also the problem. I wonder if it's not a problem with github or aws since the first download couldn't finish...

**Comment by OnlineVagrant** [comment]
I had the same problem so I downloaded the installer form the boostnote.io website an installed it over the existing one.

**Comment by ZeroX-DG** [comment]
We will try to fix the update installer, I'll close this issue
