### ISSUE TITLE
[improvement request] make done tasks strike-through optional

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2388]
hi, 

Can you make strike-through for completed tasks in tasklist optional? 

# Current behaviour

checked tasks have a text-decoration: line-through; (see image right bottom corner, "Styles"). 
![todo](https://user-images.githubusercontent.com/25648628/45598964-998e0d00-b9db-11e8-9eee-62912b14c0bf.png)

# Environment

- Version : 0.11.9
- OS Version and name : 16.04 Ubuntu

**Comment by ZeroX-DG** [comment]
Why don't I have that feature???

**Comment by modmod24** [comment]
@ZeroX-DG, I updated the issue to make it more clear what I meant.
