### ISSUE TITLE
How to manually update Katex?

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#2391]
There are some new features of Katex that I would like to use. However, there isn't a stable release yet so I want to know how to do it manually. I always see four files with every release, but I don't know what to do with them.
https://github.com/Khan/KaTeX/releases
# Environment

- Version :
- windows 10

**Comment by daiyam** [comment]
@OnlineVagrant you will need to build the app from source [here the doc](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md)
We should wait for the final release of KaTex-v0.10 which should be soon.
