### ISSUE TITLE
Input position changed when i turn it to fullscreen

### ISSUE THREAD

**Issue by hevi1991** [BoostIO/Boostnote#2397]
# Current behavior

![jxble-d5i00](https://user-images.githubusercontent.com/15024868/45524564-9dfece00-b801-11e8-9bba-9afda709b430.gif)

# Steps to reproduce

1. typing in markdown field
2. turn to fullscreen
3. typing in markdown field again

# Environment

- Version : 0.11.9
- OS Version and name : MacOS 10.13.4

**Comment by ZeroX-DG** [comment]
Confirm on Linux
