### ISSUE TITLE
[question] Data format naming rules?

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2415]
# How do I name my cson files?

## Context

I want to import a set of notes into Boostnote. I have these notes extracted from an external source and generated into a Boostnote storage location. In this particular case these notes are regularly overwritten to integrate changes applied to the source. 

## Problem

The data format for Boostnotes is [documented here](https://github.com/BoostIO/Boostnote/wiki/Data-format). I noticed that this information is outdated. 

Example filename, as documented: `01f720cbd38f6079e7cd.cson`
Example filename, observed: `1d8a347e-977c-4037-b868-b66ed339de6f.cson`

1. How should I generate filenames
2. Can I generate deterministic filenames?
3. is there a python equivalent for `crypto.randomBytes()`?

thank you 

# Environment

- Version : 0.11.9

**Comment by nagledb** [comment]
Browsing the source code, it looks like note filenames use [Version 4 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)). So my best guess is that you could use the [built-in uuid.uuid4](https://docs.python.org/3/library/uuid.html#uuid.uuid4) to generate filenames.

**Comment by modmod24** [comment]
@nagledb,

I found that any file name works fine with boostnote, I have found no issues so far. 
I'll update my code for UUID. Thank you for the helpful links!
