### ISSUE TITLE
DigitalOcean custom markdown integration

### ISSUE THREAD

**Issue by elric72** [BoostIO/Boostnote#2416]
First of all, thank you for your great job on this awesome tool that is Boostnote.
I have a quick question, is it possible to integrate parts of the custom mardown from DigitalOcean in Boostnote ?
You could have a description in this link : https://www.digitalocean.com/community/markdown

Thank you in advance for your answer
Regards
David

**Comment by daiyam** [comment]
For:
```
<$>[note]
**Note:** This is a note.
<$>
```

You could use:
```
!!! note
**Note:** This is a note.
!!!
```
if empty title was allowed (should be allowed)

**Comment by daiyam** [comment]
But
~~~
```
[secondary_label Output]
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
~~~
might be done with something like:
~~~
```(secondary_label="Output")
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
~~~

**Comment by elric72** [comment]
> For:
> 
> ```
> <$>[note]
> **Note:** This is a note.
> <$>
> ```
> You could use:
> 
> ```
> !!! note
> **Note:** This is a note.
> !!!
> ```
> if empty title was allowed (should be allowed)

@daiyam it works only if you put "note" in the title for example but if you want to put a file name "/etc/nginx/sites-available/default" it fails.
I think we can only use lower case caracters and digits.
But Thank you for your answer, it could even help .

**Comment by daiyam** [comment]
For
~~~
```nginx
[label /etc/nginx/sites-available/default]
server {
    listen 80 default_server;
    . . .
}
```
~~~

You can already do
~~~
```nginx:/etc/nginx/sites-available/default
server {
    listen 80 default_server;
    . . .
}
```
~~~

**Comment by elric72** [comment]
> ```nginx:/etc/nginx/sites-available/default server { listen 80 default_server; . . . } ```

Oh great it works.
@daiyam thank you for your help.
