### ISSUE TITLE
Update found!!!

### ISSUE THREAD

**Issue by codingmatty** [BoostIO/Boostnote#242]
I kept getting a notification saying Update found, preparing to update, but then I open the app and there is no button/link/anything to update the app.

So, I then download what I assume to be the most up to date version from the website, and I am still getting the notification! :(

The version I have from the website is v0.8.0. How do I go about easily updating??

**Comment by kazup01** [comment]
Sorry, we'll check about update problem.

**Comment by asmsuechan** [comment]
Hi @mattjdev, now you can get v0.8.1 from http://boostnote.io#download by installer, at least in my environment (mac) I could get it in this way.

I wish to fix it as soon as possible, of course I'm trying. I remember the updater works fine on v0.7.5 to v0.8.0 thus I checked the diff between them. However no `diff` found between the versions in related file which I guess (`browser/main/index.js` and `lib/main-app.js`). Is it a release problem?

**Comment by gen0083** [comment]
I faced the same issue too.
But I tried to finish the app and restart it, then update dialog was shown (and I can update the app).
I faced the issue on Boostnote's version is v0.8.0 but it seems to be not only this version.
I faced it on previous version too. (I don't remember the version, sorry)

I think that it will be OK if you prepare an "check update" in the menu, right?
Most app has "check update" in their menu.

**Comment by asmsuechan** [comment]
Hi @gen0083, thanks for your feedback! Umm, I heard it's electron or electron-g-release problem from a maintainer. Exactly I've experienced to hit the bug in the past. It's probabilistic bug...?

**Comment by a1292717155** [comment]
I think we faced the same issue.

**Comment by kazup01** [comment]
There seems to be no problem in the current version.
We'll be careful not to cause the same problem. Thank you for your reporting @codingmatty san!

**Comment by TMorville** [comment]
I have this issue in 0.11.8 on OSX 10.12.6.

**Comment by renatoliveira** [comment]
@TMorville you are not alone. Exactly same issue here, same Boostnote version. I'm on macOS 10.13.6 though.

**Comment by sean2121** [comment]
https://medium.com/boostnote/boostnote-v0-11-9-is-out-188085822bb4
it seems that Mac users need update manually.

**Comment by MiroFurtado** [comment]
I am encountering this from the version I downloaded off the homepage (0.11.11)

**Comment by kabirsikand** [comment]
I have this issue still

**Comment by Flexo013** [comment]
@kabirsikand What version are you on?
