### ISSUE TITLE
[Question] How could we add bold words in a code block ?

### ISSUE THREAD

**Issue by elric72** [BoostIO/Boostnote#2422]
Hi all,

I am looking for a solution to be able to add some bold caracters inside a code block.
I have read the Boostnote documentation but I could not find a way to do that.
Does somebody already do that ?

Thank you in advance for your answers.
Regards
David

**Comment by bryanjack** [comment]
Use \<pre> instead of \```
\<pre>
some code \<b>bold code\</b> not bold again
\</pre>

Result:
<pre>
some code <b>bold code</b> not bold again
</pre>

**Comment by elric72** [comment]
bryanjack,

Thank you for your answer but this is not really what I am looking for because I loose the syntax highlighting. I will continue to look for a solution.

**Comment by modmod24** [comment]
what you are trying to do is not feasibly. styling of code is entirely defined by syntax highlighter. you'll need to create a custom style sheet for that. 

what exactly are you attempting to do?

**Comment by elric72** [comment]
To explain what I want to do, I will take a quick example of of a basic shell command :+1: $ ls -al

**Comment by elric72** [comment]
> I am afraid this is not supported. The code styling must be defined by syntax definition and syntax style sheets. Certain rules have to be defined to show all options in bold, for example.

Ok I will try to continue in the way
