### ISSUE TITLE
Note cloning modifies the contents of the note

### ISSUE THREAD

**Issue by ReK42** [BoostIO/Boostnote#2424]
# Current behavior
When cloning a note, some characters are modified in the new copy. Specifically, forward slashes (/) become backslashes (\\).

![image](https://user-images.githubusercontent.com/4775937/46173055-116cfa80-c25a-11e8-8440-237699557fe3.png)

![image](https://user-images.githubusercontent.com/4775937/46173072-1df15300-c25a-11e8-87bd-e63531ccf59d.png)

# Expected behavior
The new copy of the note should be identical except for the name.

# Steps to reproduce
1. Create a note with forward slashes in the text.
2. Clone the note.

# Environment
- Version: 0.11.9
- OS Version and name: Windows 10

**Comment by jamesallured** [comment]
I cannot reproduce this on macOS, on the same version.

**Comment by ReK42** [comment]
I just double checked, building master@2ccd00a, and can reproduce it there. Some more details on my environment:

Windows 10 Pro, version 1803, build 17134.228

```
> node --version
v8.12.0
> npm --version
6.4.1
> yarn --version
1.10.1
> yarn list
See attachment
```

[yarn.txt](https://github.com/BoostIO/Boostnote/files/2447870/yarn.txt)

**Comment by nagledb** [comment]
Using Boostnote 0.11.10 on Mac OS X 10.13.6, I actually see the inverse behavior: backslashes become front slashes.

This:

```md
# Note test
This is a note. It has some / and some \\.
```

when cloned, becomes this:

```md
# Note test
This is a note. It has some / and some //.
```

**Comment by nagledb** [comment]
Actually this is a duplicate of #2310

**Comment by arcturus140** [comment]
@Flexo013 should be closed duplicate?

**Comment by Flexo013** [comment]
Duplicate of #2310

Thanks @arcturus140 !
