### ISSUE TITLE
{question} Can I draw something similar using mermaid or plantuml in boostnote

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#2426]
![tree](https://user-images.githubusercontent.com/39413259/46198045-e201d080-c2e1-11e8-9f27-e4adbeba7ea9.JPG)

**Comment by ZeroX-DG** [comment]
I don't quite understand your question. Can you explain it more? and have you tried to draw that with Boostnote yet?

**Comment by yosmoc** [comment]
@OnlineVagrant I don't recommend to write this kind of circuit diagram in plantuml or mermaid. If you struggle with this and successfully write this, this is not the original aim of these tools.
You can see the supported diagrams in http://plantuml.com/ and https://mermaidjs.github.io/

If you want to know more detail, please ask in plantuml or mermaid repo or forum
