### ISSUE TITLE
Possibility to delete note by CMD/CTRL+Backspace

### ISSUE THREAD

**Issue by Airgunster** [BoostIO/Boostnote#2446]
Hi there,

It would be nice to have possibility to delete note(s) by <kbd>CMD/CTRL</kbd>+<kbd>Backspace</kbd> (it will increase productivity). What do you think?

Thanks a lot in advance,
Alexey

**Comment by modmod24** [comment]
i am not 100 % sure but I think you can delete a note by pressing DEL in linux. I'll test it tomorrow.

**Comment by jacobherrington** [comment]
This is not possible in OS X. @samherrington and I are working on making this a configurable hotkey.

**Comment by modmod24** [comment]
neither in Linux. Sorry, I was imagining things.

**Comment by diegocolombo** [comment]
Is there a way to disable it? I use <kbd>ctrl</kbd>+<kbd>backspace</kbd> to erase the previous word. Actually this is a pretty common usage for this shortcut.

**Comment by Flexo013** [comment]
@diegocolombo This issue is not present in Boostnote 0.14.0. It does exist in Boost Note 0.1.3.
