### ISSUE TITLE
Detail tags not hiding tables and flowcharts etc as expected

### ISSUE THREAD

**Issue by graemearthur** [BoostIO/Boostnote#2458]
![image](https://user-images.githubusercontent.com/826712/46321258-36ef6080-c5da-11e8-947b-5ebc902ce854.png)

# Current behavior

```Does not show Tables or flowcharts or code blocks inside of <details> tags either shows them outside of the collabsable bit or if you leave no free line just shows the RAW text instead```
 
# Expected behavior
I expected code blocks and tables to be able to be hidden inside of collapsible such as happens on github and other places (text can be hidden but tables and code blocks can not)
example from github https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f
 
# Steps to reproduce

1. Make new markdown note
2. paste in the following lines (have put in code block so github shows this correctly)
```<details><summary>CLICK ME</summary>
## yes, even hidden code blocks!
  
  | TYPE        | LINUX           |Windows|
| ------------- |:-------------:| -----:|
| Dell | This is a test | Test |
| HP   | Test |   Still testing |
</details>
```
3. change to viewing mode to see the table is not hidden 

# Environment
Not tested in other OS's
- Version : Boostnote 0.11.9
- OS Version and name : Ubuntu 16.04

**Comment by daiyam** [comment]
@graemearthur Here the correct markdown to reproduce the issue:
```
<details>
## yes, even hidden code blocks!
  | TYPE        | LINUX           |Windows|
| ------------- |:-------------:| -----:|
| Dell | This is a test | Test |
| HP   | Test |   Still testing |
</details>
```

**Comment by graemearthur** [comment]
@daiyam yes this also causes an issue, leaving an extra line causes the table to rendered correctly but not inside the collapsible section both are likely symptomatic of the same underlying issue.

**Comment by daiyam** [comment]
@graemearthur It should work if you choose `Allow dangerous html` for the preference `Sanitization`.

**Comment by graemearthur** [comment]
@daiyam Yes this fixed the issue for me! thank you.
