### ISSUE TITLE
Bug with Text Selection in Finder Window

### ISSUE THREAD

**Issue by winkelsdorf** [BoostIO/Boostnote#246]
Hi,

there is a Bug when using the Finder Window with markdown Notes.

**Steps to reproduce**
- Open Finder Window
- Enable Display of markdown Notes
- Select a markdown Note (e.g. `Welcome to Boostnote :)`)
- Try to selected text from the markdown

**Expected**
Text being selected and be able to copy it

**Actual Result**
Finder jumps back to "All Notes"

**Other Information**
Version tested: 0.8.2 (0.8.2)
Environment: macOS Sierra 10.12.2

hth!

Frederik

**Comment by kazup01** [comment]
Hi @winkelsdorf san,
Thank you for your information.
hmm, my Boostnote is not occur this bug.
version 0.8.2
macOSS Sierra 10.12.2

Does anyone occurred same bug?

**Comment by kazup01** [comment]
We'll check it.

**Comment by winkelsdorf** [comment]
Hi @kazup01, 

You are welcome and thank you for checking it!

I made a quick screencast to show the issue, notice the jump from the note to "All Notes":
![boostnote finder selection](https://cloud.githubusercontent.com/assets/1413291/21981269/e4d7331a-dbe6-11e6-95c8-61bd5f074121.gif)

**Comment by kazup01** [comment]
Oh, I see! I was mistaken, and my Boostnote also occurs the same bug.
Since the code of  Finder Window is complicated, so we need to refactoring it, we'll check it together.
Thank you for your reporting!

**Comment by winkelsdorf** [comment]
Good to hear it's reproducible. This has no hurry, I am usually using the default window. At least it's now a documented bug for others stumbling upon this.

Thank you for this useful application and your work!

**Comment by kazup01** [comment]
Thank you for your compassion and enjoying Boostnote!
We'll do our best to better the Boostnote😤❗

**Comment by winkelsdorf** [comment]
You're very welcome! It's already a very helpful tool 👍

**Comment by kazup01** [comment]
Hi @winkelsdorf san, @asmsuechan san has fixed this bug!(It is very early, so I am surprised.
) We will probably improve to this bug the next update!

**Comment by winkelsdorf** [comment]
Hi @kazup01, thank you - that was very fast! Thanks to @asmsuechan for his help, too!

**Comment by kazup01** [comment]
I close this issue. Thank you @winkelsdorf san👏
