### ISSUE TITLE
Possibility for already defined tags to appear while you're typing

### ISSUE THREAD

**Issue by Airgunster** [BoostIO/Boostnote#2464]
# Current behavior
* When you're typing tags for the `Markdown Note`/`Snippet` you don't see already existing tags in the Boostnote;
  * As a result, you may create a new tag by mistake (like `Project_Meeting` vs. `Project_Meetings`, or `Project_meeting` vs. `Project_Meeting`, just as an example) + tags are always created at the time they are typed, unless exactly the same tag name is used (literally the same name, with same register (tags are case-sensitive));

# Expected behavior
* When you're typing tags for the `Markdown Note`/`Snippet` you can see already defined tags in the Boostnote, and select it from the drop-down list;

# Steps to reproduce
1. Create a new `Markdown Note`/`Snippet`;
2. Type tag for newly created `Markdown Note`/`Snippet`;
3. Observe that there's no drop-down list of tags appearing (from the list of already defined ones) while you're typing the tag name;

# Environment
- Version : `v. 0.11.9`
- OS Version and name : `macOS v. 10.12.6`

**Comment by daiyam** [comment]
@Airgunster it is done in the next release

**Comment by Airgunster** [comment]
@daiyam, thanks. Could you please clarify if this feature will be available in the next release of Boostnote or it will be in the Boost (complete rewrite of Boostnote (ETA is unclear yet (AFAIK)))?

**Comment by daiyam** [comment]
@Airgunster it will be in the next release of Boostnote.

**Comment by Airgunster** [comment]
@daiyam, Wonderful, thanks a lot!

**Comment by ZeroX-DG** [comment]
Closed as implemented

**Comment by ZeroX-DG** [comment]
@Airgunster Added label :+1:
