### ISSUE TITLE
New feature - Line highlighting within code block

### ISSUE THREAD

**Issue by jaepetto** [BoostIO/Boostnote#2469]
It would be super nice to add line highlight within a code block (https://github.com/egoist/markdown-it-highlight-lines).

I quite often put code blocks with some lines of context in order to make sure it is clear. Being able to highlight some specific lines would be great.

**Comment by duartefrazao** [comment]
Hi, jaepetto! I'll will try to add this feature in the upcoming future.

**Comment by jaepetto** [comment]
Great thanks!

**Comment by Flexo013** [comment]
Feature is present in current version Boosnote.
