### ISSUE TITLE
[Feature Request] Link to a line in a note

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#2475]
Would it be feasible to implement a feature that by linking to a note and then adding the line number it brings you directly to that line? Like in a wiki, when you click the links in the numbered list.
For example, if you want to link to line 133 of the note "Test" you could write:
"]Test line 133[):note:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:133("
(I'm writing the wrong parentheses or else it thinks it's markdown and doesn't show.

**Comment by ZeroX-DG** [comment]
Currently, Boostnote doesn't have this feature (not that I'm aware of). Maybe someone will be interested in implementing this.

**Comment by kapad** [comment]
to add to @federicochiesa 's request, I would like to be able to link to a line number or a section/anchor in a note. Just with linking to the line number, my links would often break after the note that has been linked to, gets a new line before the line that was linked to. 

The format that has been mentioned in the note would be ideal if implemented similar to the go-to-anything function of sublime. (i.e. `:note:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:133` for a line link and `:note:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:#Section-1` for a section link).

**Comment by Antogin** [comment]
I will try to implement this!
