### ISSUE TITLE
Update found notification shows, but the update never finishes.

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#2478]
I'm running Boostnote 0.11.8 on macOS 10.14 Mojave on a 2014 MacBook Pro.
Every time I open Boostnote it says there's an update and it's preparing, but it never finishes. I tried leaving it open overnight to see if I closed it too soon to complete the update, but that didn't solve my issue.

**Comment by daiyam** [comment]
@federicochiesa please update manually. There is a bug in the update process. #2376

**Comment by federicochiesa** [comment]
Sorry, I didn't know that. I tried to look for a similar issue but didn't find any. Thanks.
