### ISSUE TITLE
Scrolling beyond last line

### ISSUE THREAD

**Issue by Zuuja** [BoostIO/Boostnote#2479]
It would be nice to be able to scroll beyond last line (especially in preview mode).

If you not sure I mean you can look at this option behavior in monaco editor: 
https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options

_EDIT:_ I found that there is addon in code mirror called *__scroll past end__* which does exactly it.

**Comment by Zuuja** [comment]
Thank you and sorry for stupid question.

**Comment by ZeroX-DG** [comment]
Close as solved
