### ISSUE TITLE
Links within the same note  don't work in the preview. 

### ISSUE THREAD

**Issue by kapad** [BoostIO/Boostnote#2480]
# Current behavior

I've created a manual table of contents for some notes, and tried to link from the TOC to the relevant section, using `#link` but the preview page doesn't work with these links. 

Is this a feature that is broken, or something that hasn't yet been implemented? 

PS: I didn't think screenshots would be relevant for this right now, but let me know if I should add them. 
PPS: a dummed down note text to show what I am trying to do. I know that for such a short note, the preview pane wouldn't even need to scroll, but the actual note that I am working with is much much longer, and even then the preview doesn't scroll to the relevant section when I click on the table of contents link for that section.

```
# Title

## Contents
- [Section 1](#section-1)
- [Section 2](#section-2)

## Section 1
Text for section 1

## Section 2 
Text for section 2
```

**Comment by ZeroX-DG** [comment]
Boostnote TOC is actually case-sensitive. You must capitalize the link just like the section title.

```
# Title

## Contents
- [Section 1](#Section-1)
                       ^--- Capitalize
- [Section 2](#Section-2)
                       ^--- Capitalize
## Section 1
     ^--- Because of this
Text for section 1

## Section 2 
     ^--- And this
Text for section 2
```

In the next version, Boostnote will have a TOC generator to take care of this for you: https://github.com/BoostIO/Boostnote/pull/2281

Thank you for reporting.
I'll close this as duplicate (https://github.com/BoostIO/Boostnote/issues/2067)

**Comment by kapad** [comment]
Thanks for the response. The TOC is working for me now.
