### ISSUE TITLE
[Request] Allow locking preview view. 

### ISSUE THREAD

**Issue by kapad** [BoostIO/Boostnote#2481]
Very often, when I am trying to copy paste from a note (when in the full preview mode, i.e. not side by side editor and preview mode), I select either a bit more than I copied or a bit less. If I click anywhere outside the selection, what I am used to, is for the selection to disappear so that I can start another selection. 

In boostnote what happens is the selection disappears, but the note also changes from preview mode to editor mode (full, not side by side). I know I could just select from the editor mode (and that is what I am doing currently) but this change in mode, takes a little bit away from the UX while using boostnote.

**Comment by daiyam** [comment]
@kapad try by setting the preference `Switch to Preview` to `On Right Click`, it should be better 😉

**Comment by kapad** [comment]
Sweet. the `on right click` option now makes boost note behave exactly like I need. This should be the default option. :)
