### ISSUE TITLE
No dropboox api

### ISSUE THREAD

**Issue by omaidb** [BoostIO/Boostnote#2486]
版本：0.11.9
操作系統：xubuntu18.04
我聽說boostnote 可以將筆記同步到dropbox
但是ubuntu版本的使用後並沒有發現dropbox的同步功能。
能夠盡快加入該功能嗎？
Version: 0.11.9
Operating system: xubuntu18.04
I heard that boostnote can sync notes to dropbox
However, the use of the ubuntu version did not reveal the synchronization of the dropbox.
Can I join this feature as soon as possible?

**Comment by omaidb** [comment]
boostnote 項目和dropbox pager 項目很像。建議boostnote 作dropbox pager的第三方工具使用。或許這應該得到dropbox 的贊助支持

**Comment by Flexo013** [comment]
Sync using Dropbox and other platform is discussed in #308
