### ISSUE TITLE
Textual Arrows turning into graphical arrows

### ISSUE THREAD

**Issue by RachelTyJohnson** [BoostIO/Boostnote#2489]
# Current behavior
I'm trying to put HTML tags in my code block like below but the `</` is turning into an arrow ↙
```
<fieldset></fieldset>
```
I've checked and unchecked and rechecked and restarted the "Convert textual arrows to beautiful signs" option in Interface but it's still happening.

I feel like it's just me drastically missing something but I can't find anything :(

# Expected behavior

For `</` to remain as `</` so I can write HTML notes

# Steps to reproduce

1. Typed `</`
2. ↙ Appears

# Environment

- Version :  0.11.9
- OS Version and name : Windows 10 64bit

**Comment by nagledb** [comment]
Are you using a custom font? Some fonts have ligatures, I wonder if that's what you're seeing. You can test by selecting the ↙ and copying to your clipboard, then pasting into something like notepad to see if it shows up as </ or ↙.

**Comment by RachelTyJohnson** [comment]
> Are you using a custom font? Some fonts have ligatures, I wonder if that's what you're seeing. You can test by selecting the ↙ and copying to your clipboard, then pasting into something like notepad to see if it shows up as </ or ↙.

Oh my goodness @nagledb you were right. I had reinstalled Boostnote and not 'messed' with anything and the </ were coming out fine. You hit the nail on the head. Thank you!!
