### ISSUE TITLE
Add Standard File backend

### ISSUE THREAD

**Issue by spott** [BoostIO/Boostnote#249]
[Standard File](https://standardfile.org/models) is supposed to be a very simple encrypted file store for notes, with an emphasis on simplicity of format and features.

[Standard Notes](https://standardnotes.org) is their current benchmark notes application, however, it lacks some of the nice-to-have features of boostnote.  The two are similar enough, however, that it should be possible to make Boostnote use Standard File as a file store without too much difficulty.

**Comment by asmsuechan** [comment]
Sorry for long absent @spott. Do you mean **Standard File importer** is helpful for you?

**Comment by spott** [comment]
It would be nice to use it as a file store:  saving and syncing with the standard file service rather than on disk.

Similar to using dropbox or iCloud, just a different system.

**Comment by adrm** [comment]
This is a duplicate of #874. I would love to have this feature!
