### ISSUE TITLE
open PDF files at specific page

### ISSUE THREAD

**Issue by jangtsekiang** [BoostIO/Boostnote#2491]
I have a lot of PDF files that I am linking to from my Boostnote markdown notes. Currently, I have:

`[source](/path/to/file.pdf)`

This works great, the OS uses the default application to open the file. 
Now I want to open these files at a specific page. Many PDF reader support this feature, but in formats like:
```
<pdf_reader> <path/to/file> -p 5
<pdf_reader> <path/to/file> -i 5
<pdf_reader> <path/to/file> /a "page=5"
etc
```

Is there a way to support this in Boostnote? For example by defining custom commands to open PDF's. 

# Environment

- Version : 0.11.9
- OS Version and name : 16.04 Ubuntu

**Comment by ehhc** [comment]
as far as i know it is not supported by boostnote at the moment. We do not handle the opening of the file at all but delegate it to the OS to take care of it. Therefore we don't have any option to modify the way special files are opened at the moment (afaik).. sorry

**Comment by ehhc** [comment]
One possible, but ugly, solution might be running a local file server that serves the pdf files and liking it as following: `[cool pdf file at page 4](localhost:8085/path/to/file#page=4)`..

maybe that would be possible.. :)

**Comment by jangtsekiang** [comment]
thanks for the idea

> One possible, but ugly, solution might be running a local file server that serves the pdf files and liking it as following: `[cool pdf file at page 4](localhost:8085/path/to/file#page=4)`..
> 
> maybe that would be possible.. :)

**Comment by ehhc** [comment]
@jangtsekiang 
using node to create a very simple file-server (see e.g. https://stackoverflow.com/a/24575241) the hack i mentioned earlier works :)

Nevertheless: exports and so on will to be able to cover your pdfs if you do something like that anymore...

I fear it's therefore not a good solution.. :(

**Comment by jangtsekiang** [comment]
Well, it works for me at least :)
I've seen this page as well (adobe help). I think this is very genuine and every PDF reader should support it but they don't.

Not sure if others are interested in this feature, it is very useful to me. I'll close this issue for now.
