### ISSUE TITLE
Ability to disable quotes/parentheses matching

### ISSUE THREAD

**Issue by yzaretskiy** [BoostIO/Boostnote#2508]
Could we have an option to disable the automatic matching of various paired delimiters, like quotes or parentheses? I personally do not find this functionality useful outside of writing code.

**Comment by nagledb** [comment]
I'd also like such an option. It'd also be great if it were accessible in the editor directly rather than in the preferences dialog. Maybe as a toolbar button or an (optional?) key-binding? That way we can easily switch back and forth based on what we're currently doing.

**Comment by nagledb** [comment]
I'd especially like the ability to specify which delimiters to enable/disable.

A good example is $. I use that symbol a lot, but *never* as a paired delimiter. Sometimes I like having quotes and parens paired, but I never want $ paired.

**Comment by kyan001** [comment]
I use `*` to make my list, and every time I start a `*` it automatically gives me `**`.

Italy font is not the only use of `*` in markdown, it's so annoying.
