### ISSUE TITLE
App icon not visible when App is open [Arch Linux - Gnome]

### ISSUE THREAD

**Issue by marcosantomo** [BoostIO/Boostnote#251]
When I open the app from 'Favorites' the window is under a generic white Icon while when the app is closed in 'Favorites' I'm able too see the right app icon... 
![untitled](https://cloud.githubusercontent.com/assets/5794716/22147658/e306becc-df09-11e6-86d5-a0041e070223.png)

This is a screenshot of the Opened App... It happens under Xorg and Wayland!

EDIT: I just noticed that on the AUR there is an old version of this App... maybe that's the problem...

EDIT 2: I have compiled and installed the latest version (0.8.2), the problem is still there.

**Comment by kazup01** [comment]
Oh, we'll check it. Thank you for your reporting!

**Comment by sferra** [comment]
Besides the incorrect icon, in Unbuntu Gnome the app name is also incorrect when switching between applications:
![boostnote_alt_tab](https://cloud.githubusercontent.com/assets/596554/25637002/979950a6-2f83-11e7-9692-4405d8f44545.png)

**Comment by sferra** [comment]
#177 seems to describe the same issue.

**Comment by kazup01** [comment]
refs: #177
