### ISSUE TITLE
Tag "counts" in refined search

### ISSUE THREAD

**Issue by sharif1093** [BoostIO/Boostnote#2516]
# Current behavior
The number of **total** pages that have each tag is shown in front of the tag in the tags panel.

![tag count](https://user-images.githubusercontent.com/10884607/47257922-47b92680-d462-11e8-93f8-61f3c9e574be.png)

# Expected behavior
It would be great if the numbers are updated for the current refined search.
Or, at least, the numbers in the current refined search be shown with a different color beside the overall number. Example:

Tags:
```bash
#CLI                  3/22
#Compression          1/1
#File                 1/6
#Stream               1/2
#Ubuntu               3/27
#Unix                 5/28
```

# Steps to reproduce
N/A

# Environment

- Version: 0.11.10
- OS Version and name: Ubuntu 16.04 Xenial

**Comment by Rokt33r** [comment]
It will be included to the new release of this weekend! Thanks @daiyam !!
