### ISSUE TITLE
Copyright Repository?

### ISSUE THREAD

**Issue by nikhiljha** [BoostIO/Boostnote#252]
> If you make a pull request, It means you agree to transfer the copyright of the code changes to MAISIN&CO.

But at the same time you're using the GPL? I think a lot more people would want to contribute if this were switched to MIT or a more permissive license, and withdrew copyright.

**Comment by kazup01** [comment]
I see. We'll discuss it tomorrow. I want to think about license flexibly.
Thanks for your helpful advice!

**Comment by asmsuechan** [comment]
I feel it's just a task of @kazup01, you have all rights of changing copyright. Any reasons of this copyright?

**Comment by nikhiljha** [comment]
@kazup01 Any update on this? Can we make it MIT?

**Comment by ehhc** [comment]
@Rokt33r Any Update concerning a more flexible license ? I would wish for that as well

**Comment by Rokt33r** [comment]
@ehhc @nikhiljha At that moment, we were very conservative. The fully re-written app, which probably be released this summer, will be published under MIT. :)
