### ISSUE TITLE
Cursor is invisible after moving to a new line

### ISSUE THREAD

**Issue by lesyuk** [BoostIO/Boostnote#2520]
# Current behavior
Cursor is invisible after moving to a new line
![2018-10-21_14-11-53](https://user-images.githubusercontent.com/44337476/47266196-de0d4b00-d53b-11e8-829d-6b292e4138a9.gif)

# Expected behavior
Cursor is visible

# Steps to reproduce

1. Create new note
2. Start typing
3. Move to a new line

# Environment
- Version: 0.11.10 (0.11.10)
- OS Version and name: macOS 10.14

**Comment by nagledb** [comment]
I'm on macOS 10.13.6 with Boostnote 0.11.10 and do not see this behavior. Maybe it's specific to macOS 10.14.

**Comment by nagledb** [comment]
Possibly related to #2463? Maybe see if [this workaround](https://github.com/BoostIO/Boostnote/issues/2463#issuecomment-429898449) works for you.

**Comment by lesyuk** [comment]
@nagledb No, it doesn't work. But today I launched Boostnote and found that the bug disappeared.

**Comment by ZeroX-DG** [comment]
Feel free to re-open this issue if it happens again
