### ISSUE TITLE
Install "desktop" version on Ipad

### ISSUE THREAD

**Issue by fzeiser** [BoostIO/Boostnote#2523]
Is it possible to install the desktop version on an ipad? I installed the program on my linux notebook and it works very nice. When I tried the mobile app for the ipad, it didn't work as expected. I don't even see how to create notes with markup.

- Version : Any
- OS Version and name : 
Ipad pro with iOS 12.0.1

**Comment by ZeroX-DG** [comment]
I don't think it's possible to install "desktop" version on IOS devices and the team is working on the new mobile app.
