### ISSUE TITLE
[Feature Request] Add html classes to Table Of Contents Elements

### ISSUE THREAD

**Issue by kyan001** [BoostIO/Boostnote#2525]
# [Feature Request] Add html classes to Table Of Contents Elements
Could you add some classes to auto-generated Table of Contents?
Such as `<ul class="toc">`, `<li class='h4'>` so that I can control TOC styles by myself.
(I wanna make h3/h4 has a smaller font and make h5 disappear in TOC)

BTW, where I can find the corresponding css selector name of each markdown elements (when customizing css)?

**Comment by ZeroX-DG** [comment]
You can search for your header using the dev tool. You can open the dev tool using view > toggle developer tool (ctrl + shift + i). After you find your header you can right click on it and select copy > copy selector.

**Comment by incace** [comment]
I was just about to post up a new issue regarding this. It would be really easy just to add a class to the generated UL that way we could control it in preview mode with the custom CSS box on the interface settings. I was looking to create a fixed/floating TOC via CSS with this method but there is no way to target the TOC without breaking some other styling. You can try and select it via nth-child but that changes per document depending on where the TOC is within the flow.
