### ISSUE TITLE
Missing notes - possibly after update

### ISSUE THREAD

**Issue by Marmalade118** [BoostIO/Boostnote#2527]
# Current behavior

I seem to be missing notes after the latest update. I had some notes in this folder that I used regularly and I last used them on the 18th October, but today at least 1 (that I can say with 100% certainty) of my note files seems to be missing, but I'm sure at least 1 other is missing from this folder. I use the note file frequently so I know it definitely existed. I've checked the trash and it's not in there and I don't share my computer with anyone else so I'm confident it hasn't been deleted by mistake.

![image](https://user-images.githubusercontent.com/11860837/47352289-82fd6480-d6b1-11e8-9e7d-149492fcac9b.png)

I have read a similar issue in the issue log where the person was able to track the note down using the folder key, however trying the same doesn't bring up any un-linked notes for me.

# Expected behavior

Note files don't go missing after updates

# Environment

- Version : 0.11.10
- OS Version and name : Windows 10 64-Bit version 1803 Build 17134.345

**Comment by ZeroX-DG** [comment]
We have received some reports about missing notes after updating.

Maybe you can check out these for more info:
https://github.com/BoostIO/Boostnote/issues/1610, https://github.com/BoostIO/Boostnote/issues/1485, https://github.com/BoostIO/Boostnote/issues/901

**Comment by Marmalade118** [comment]
Thanks, I'll take a look and see if anything helps.

**Comment by Flexo013** [comment]
@Marmalade118 Have you experienced this issue with any of the latest builds of Boosnote?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
