### ISSUE TITLE
contributing.md needs an update

### ISSUE THREAD

**Issue by nagledb** [BoostIO/Boostnote#2528]
The doc states "There is no issue template" but there actually is an issue template and #2504 will add a PR template as well.

#2504 also includes a checklist for PRs, but none of the items listed are documented in contributing.md:
> - My code follows the project code style
> - I have written test for my code and it has been tested
> - All existing tests have been passed
> - I have attached a screenshot/video to visualize my change if possible

I recommend linking to docs/build.md and docs/debug.md.

I recommend giving the steps to run the test suite either in contributing.md or build.md. (It's easy to figure out how to run them, but documenting it may better encourage people to actually run them.)

I recommend explaining what is meant by "project code style". Do you just want us to try to match the style of existing code as best we can? Or are you using a code style that's documented somewhere? If there's tooling to verify compliance with code style, documenting how to run it would also be great.

**Comment by ZeroX-DG** [comment]
You're absolutely right, we don't really pay much attention to the docs, therefore the code quality is bad. That's the reason the team is in progress of re-writing this app into a whole new app. But I'll update the docs soon to keep it up to date.

**Comment by richardtks** [comment]
> You're absolutely right, we don't really pay much attention to the docs, therefore the code quality is bad. That's the reason the team is in progress of re-writing this app into a whole new app. But I'll update the docs soon to keep it up to date.

Hi, may I know the branch/tag that you are referring to "re-writting this app" into a whole new app?

**Comment by ZeroX-DG** [comment]
@richardtks It's this repo: https://github.com/BoostIO/Boost
