### ISSUE TITLE
Two spaces after every new line. 

### ISSUE THREAD

**Issue by eyun89** [BoostIO/Boostnote#2529]
I just wanted to start out by saying that I'm really enjoying Boostnote and thank for very much for everyone who put in the time to make this app possible.

I am having issue where every time I press <kbd>Enter</kbd>, the new line starts with two spaces.

If this is a default setting, are there any options to have the new line start without the spacing?

These are my settings:
<a href="https://ibb.co/efi61V"><img src="https://preview.ibb.co/fCKeMV/Screen-Shot-2018-10-23-at-2-53-21-PM.png" alt="Screen-Shot-2018-10-23-at-2-53-21-PM" border="0"></a>
<a href="https://ibb.co/kChc8A"><img src="https://preview.ibb.co/fJU2aq/Screen-Shot-2018-10-23-at-2-53-44-PM.png" alt="Screen-Shot-2018-10-23-at-2-53-44-PM" border="0"></a>

Again, thank you very much for your efforts!

**Comment by Flexo013** [comment]
Boostnote will keep whatever the current indentation level is. In other words if the line you are currently on starts with 2 spaces then hitting <kbd>Enter</kbd> will make that new line also start with to space to preserve indentation.
