### ISSUE TITLE
Leftmost sidebar cannot be maximized in the Tags view

### ISSUE THREAD

**Issue by deepal** [BoostIO/Boostnote#2536]
# Current behavior

You click on a tag above one of the notes, the leftmost sidebar will change its view from the storage locations/folders to the list of tags view. If you already have minimized the leftmost sidebar before clicking on a tag, it will still switch to the tags view, but you will neither be able to see the tags, nor to maximize the sidebar so that you can see the tags. The only solution I found was to quit and re-open Boostnote. See the attached gif.

![boostnote](https://user-images.githubusercontent.com/1533286/47499275-da413780-d85f-11e8-98e1-912f71268047.gif)

This is because, there is no maximize button in the tags view. 

# Expected behavior

- Tags view also should be able to minimize/maximize using the button (preferred), or
- When the leftmost sidebar is minimized and when you click on a tag above a note, the sidebar should be maximized (compromises the UX)

# Steps to reproduce

- Open boostnote
- Hide the leftmost sidebar (containing storage locations/folders) using the `<<` icon at the bottom of it.
- Create a new note
- Add a tag to the note
- Click on the tag to see all the notes having the same tag
- Try to maximize the leftmost sidebar

# Environment

- Version : Version 0.11.10 (0.11.10)
- OS Version and name : macOS Mojave Version 10.14

# Additional images

<img width="518" alt="screenshot 2018-10-25 at 14 04 09" src="https://user-images.githubusercontent.com/1533286/47499804-36588b80-d861-11e8-98bc-2560ab034243.png">

**Comment by ZeroX-DG** [comment]
Another UI bug :smile: Thank you for reporting.

**Comment by Flexo013** [comment]
This bug is no longer present in Boostnote 0.13.0
