### ISSUE TITLE
can admonitions be nested?

### ISSUE THREAD

**Issue by jangtsekiang** [BoostIO/Boostnote#2537]
I was creating an admonition within an admonition. I can see that it works but it is causing problems. The ending delimiter of the 2nd admonition is simultaneously used as ending delimiter for the 1st admonition. 

# steps to replicate

1. create a new markdown note
2. insert markdown

```markdown
# test

!!! note 1

some text 

!!! note 2

some text

!!!

some more text

!!!
```

**result:**

![admonition](https://user-images.githubusercontent.com/43673946/47520004-e1c80700-d886-11e8-85ba-731a3dc7718e.png)

# expected behaviour

It works half way, Not sure if it is even legal what I am doing :S 
Should I expect it to work or not to work?

# environment

Version: 0.11.10
OS: 16.04 Ubuntu

**Comment by ehhc** [comment]
Hi @jangtsekiang, i think it is not a issue of us but the plugin we use. Would you be so kind and ask your question at the plugin-git? https://github.com/docarys/markdown-it-admonition

**Comment by jangtsekiang** [comment]
@ehhc I created an issue [there](https://github.com/docarys/markdown-it-admonition/issues/6).

I am closing this now and create a new issue once a fix has been released.
