### ISSUE TITLE
Severe lag spikes when typing

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#2541]
I'm running Boostnote 0.11.10 on macOS 10.14 Mojave, and when I type notes there are huge lag spikes where the program freezes and then types a bunch of text all at once.
I'll be more than happy to provide more information about my issue.

**Comment by ZeroX-DG** [comment]
Hey, @federicochiesa do you still have that issue after restart Boostnote or computer?

**Comment by federicochiesa** [comment]
Yes, it's very intermittent but it is really noticeable to the point that I have to guess what I'm writing before it shows up

**Comment by rklasen** [comment]
Can confirm this issue, also Happens on Ubuntu 18.04, Boostnote 11.10. and Ubuntu 18.10. Boostnote 11.11.

No input is lost, but the freezing is very confusing.

**Comment by Flexo013** [comment]
Feel free to comment here or reopen this issue if this is still occurring with the latest version of Boostnote.

**Comment by jensmcatanho** [comment]
I have been experiencing this issue on macOS Mojave 10.14.6 and the latest Boostnote 0.15.3. This is only happening on notes with lots of text. Removing a diagram from the note seemed to reduce lag.

**Comment by Flexo013** [comment]
@jensmcatanho is the lag when typing or rendering? Or both?

**Comment by jensmcatanho** [comment]
@Flexo013 both. The text on preview syncs at the same time as the editor though. Maybe the lag happens when I'm typing and, when the editor syncs, the preview syncs in real-time.

**Comment by arcturus140** [comment]
@jensmcatanho does it happen only in split view?

**Comment by jensmcatanho** [comment]
@arcturus140 yes, only in split view.

**Comment by Flexo013** [comment]
@jensmcatanho Please [create a new issue](https://github.com/BoostIO/Boostnote/issues/new) with all the details of your problem. Then we'll move from there.
