### ISSUE TITLE
Error "Too many open files" on startup

### ISSUE THREAD

**Issue by kam1sh** [BoostIO/Boostnote#2551]
# Current behavior
After upgrading from 0.11.6 to 0.11.9 I could not use boostnote: application always hangs on startup with the next error:

> 
> 
> Uncaught Error: EMFILE: too many open files, open '/usr/share/boostnote/resources/app/node_modules/markdown-it/lib/rules_block/reference.js'
>     at Object.fs.openSync (fs.js:646:18)
>     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
>     at Object.fs.readFileSync (fs.js:551:33)
>     at Object.fs.readFileSync (ELECTRON_ASAR.js:545:29)
>     at Object.Module._extensions..js (module.js:652:20)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:504:12)
>     at Function.Module._load (module.js:496:3)
>     at Module.require (module.js:586:17)
>     at require (internal/module.js:11:18)

Here's full log:
[boostnote-0.11.9.log](https://github.com/BoostIO/Boostnote/files/2522701/boostnote-0.11.9.log)

Stdout:

> [22654:1028/134206.601540:ERROR:CONSOLE(0)] "Failed to load https://chrome-devtools-frontend.appspot.com/serve_file/@7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33/product_registry_impl/product_registry_impl_module.js: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-devtools://devtools' is therefore not allowed access. The response had HTTP status code 404.", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)
> [22654:1028/134206.601817:ERROR:CONSOLE(22)] "Empty response arrived for script 'https://chrome-devtools-frontend.appspot.com/serve_file/@7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/inspector.js (22)
> [22654:1028/134206.603074:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)
> [22654:1028/134206.603341:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)
> [22654:1028/134206.603534:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

# Expected behavior

# Steps to reproduce

1. Launch boostnote.
2. ???
3. PROFIT

# Environment

- Version : 0.11.9, package from https://github.com/SkYNewZ/Boostnote-packages/releases
- OS Version and name : openSUSE Leap 15, Linux kernel 4.12.14-lp150.12.22-default
- Desktop Environment: KDE 5.45.0 / Plasma 5.12.6
- Open files soft limit (`ulimit -n`): 1024

**Comment by Flexo013** [comment]
Feel free to comment here or reopen this issue if this is still occurring with the latest version of Boostnote.
