### ISSUE TITLE
Feature request: allow pure markdown source mode

### ISSUE THREAD

**Issue by NeverwinterMoon** [BoostIO/Boostnote#2552]
# Current behavior

Now there are two view modes: 
- split panels with markdown source text on the left and output of compiled markdown on the right
- "smart mode" where when you are not editing the file, it shows the compiled output and when you click on it, it switches to the markdown editing. When the editor loses focus, it automatically switches to compiled view.

I find both modes useless. The first takes too much screen space and the last keeps toggling between the source and compiled view too often.

# Expected behavior
Ideally, I would love to see it the way Bear does it - there is always only one view. It basically compiles the source on the fly, it works perfectly. But if this is something too hard to do or not desired for the most users, at least I would want to be able to enable just the source code mode (edit mode).

**Comment by ZeroX-DG** [comment]
You can custom how the preview mode should be toggled in the setting. In your case, I think you should set it to right click
![image](https://user-images.githubusercontent.com/12984316/47641678-48a43380-db99-11e8-96e1-bae079f721df.png)

**Comment by NeverwinterMoon** [comment]
@ZeroX-DG Thanks a lot for your help, I did go through the settings but missed that one!

But still, I would leave this ticket as a feature suggestion. Having two different modes does not make much sense. For instance, Bear (which is hands down the best markdown editor I used) has one mode - it's a combination of Boostnote's preview and source views. Basically, it creates the preview on the fly in the same view as you edit. So it looks nice and is easy to use.

**Comment by NeverwinterMoon** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/1917308/47642715-04ea0380-db72-11e8-9e9a-f0cb2a531002.png)

So the markdown is already parsed on the fly and you can type in the same view.

**Comment by ZeroX-DG** [comment]
@NeverwinterMoon I know what you're thinking, your feature request is kinda like this one: https://github.com/BoostIO/Boostnote/issues/1971
The team hasn't had the time to look into that feature yet. However, I'll tell the team about that feature too, it looks cool :smile:

**Comment by NeverwinterMoon** [comment]
@ZeroX-DG OK, after a few hours of use, I noticed a bug when using "Switch to Preview: On Right Click". Basically, it works fine until reopening of the app. When I shut it down and re-open it, I can't start editing. I click on the editor view, but the cursor is not placed anywhere. To solve this, I have to click on "Toggle Mode" twice, then I can start editing. Basically, the "on right click" is definitely broken.

Tested this on Windows and macOS with Boostnote 0.11.10. The same buggy behaviour on both platforms, sad to say.

**Comment by ZeroX-DG** [comment]
@NeverwinterMoon The setting is a bit confusing, you must right click to go to preview and right click on preview mode to go back to editor mode

**Comment by NeverwinterMoon** [comment]
@ZeroX-D What I meant is that every time i restart the app, it shows the editor in the edit mode (not preview), but I can’t edit. This applies only to existing notes. If I create a new note, it’s editable right away.

**Comment by ZeroX-DG** [comment]
Oh sorry, haha, if so can you open up the dev tool to identify the problem? Please open a new issue for it if necessary.
