### ISSUE TITLE
Opening editor from preview scrolls back to the top

### ISSUE THREAD

**Issue by ValGibello** [BoostIO/Boostnote#2553]
# Current behavior

Clicking on the preview panel (once or twice depending on settings) switches to editing mode but the editor goes back to the top of the page or where the cursor previously was in this mode.

# Expected behavior

When scrolling the preview and clicking on it to switch to editor mode, it is expected that the cursor is placed where the click was made in preview mode, or at least the view in the editor should reflect what the user was viewing in the preview.

Instead, it scrolls back to the last position of the cursor in the editor or to the top of the page. This makes a simple modification a bothersome process : 
1. Click on the preview panel to edit
2. Scroll back to the part previously identified in preview mode
3. Make the change

It is expected to behave like this : 
1. Click on some part of the text in the preview panel with the intent to edit it
2. Editor opens and the view is set to the same part of the text, the cursor is placed where the click was made
3. Make the change

# Steps to reproduce

1.  Scroll down a note in preview mode 
2.  Click somewhere in the text
3. The editor opens but the page has scrolled back to the top

# Environment

- Version : 0.11.10
- OS Version and name : all versions

**Comment by ZeroX-DG** [comment]
Thank you for reporting, duplicated: https://github.com/BoostIO/Boostnote/issues/382

**Comment by hinder90** [comment]
Version 0.12.0-0 on MacOS (10.14.5) continues to exhibit this behavior, though it is actually very erratic. The when checking a checkbox in Preview, the page doesn't seem to jump in a reliable manner. It doesn't appear to be relative to where the cursor is in the Editor. It seems that if you type into the editor the location of the Autoscrolling sometimes changes, but I cannot identify the pattern of the location where it scrolls to.
