### ISSUE TITLE
Brackets "<>" are misinterpreted as HTML tags and closing tags are added automatically

### ISSUE THREAD

**Issue by dpjayasekara** [BoostIO/Boostnote#2558]
#2160 
Is this an issue or a just a configuration? It really messes up my markdown as well.

e.g, I need to write `ssh <host_alias` in my markdown. This is how it's rendered:

```
ssh <host_alias>
</host_alias>
```
Boostnote thinks `<host_alias>` is a tag and it automatically closes it. This is painful. Is there any workaround or configuration to fix this? I haven't found one yet.

**Comment by dpjayasekara** [comment]
#2160

**Comment by ZeroX-DG** [comment]
Can you provide more information?
- Which type of note are you using
- Steps to reproduce the problem

**Comment by dpjayasekara** [comment]
It's a markdown note.

Steps to reproduce:

1. Open a new code block with `sh` language type
2. type `ssh <host_alias>` inside the code block (just an example)
3. See the preview

The preview will be :
```sh
ssh <host_alias>
</host_alias>
```
instead of 
```
ssh <host_alias>
```

**Comment by ZeroX-DG** [comment]
I can reproduce the bug. Which version are you using?

**Comment by dpjayasekara** [comment]
It is Version 0.11.10 (0.11.10) (macOS Mojave)

**Comment by dpjayasekara** [comment]
![boostnote](https://user-images.githubusercontent.com/1533286/48159077-9248f880-e2d4-11e8-883d-b2e4b5016f81.gif)

I'm not sure whether there's a configuration to prevent this happening, maybe I can't find it.  :/

**Comment by ZeroX-DG** [comment]
I think this has been fixed here: https://github.com/BoostIO/Boostnote/pull/2712. Feel free to re-open if it's not.
