### ISSUE TITLE
CodeMirror-related refactoring

### ISSUE THREAD

**Issue by nagledb** [BoostIO/Boostnote#2564]
[react-codemirror](https://github.com/JedWatson/react-codemirror) implements a React component for CodeMirror. However, Boostnote currently only uses it in the preferences Interface tab to preview the editor theme and to edit Custom CSS.

The other two places Boostnote uses CodeMirror does *not* use react-codemirror; each place implements its own component that instantiates CodeMirror directly: [browser/components/CodeEditor.js](https://github.com/BoostIO/Boostnote/blob/f92da165445bcad56a2f0188846eb795c07e2d84/browser/components/CodeEditor.js#L23) and [browser/main/modals/PreferencesModal/SnippetEditor.js](https://github.com/BoostIO/Boostnote/blob/f92da165445bcad56a2f0188846eb795c07e2d84/browser/main/modals/PreferencesModal/SnippetEditor.js#L12). Much of the code for SnippetEditor is duplicated in CodeEditor. It also looks like a lot of the code in CodeEditor that isn't duplicated, probably could safely be applied to SnippetEditor.

I would like to refactor the common functionality between CodeEditor and SnippetEditor into a shared base component, possibly using react-codemirror. Since it'd be a fairly significant refactor, I wanted to ask about it before doing the work. Has this been considered before? Are there any reasons why it'd be a bad idea? Are there any reasons for/against using react-codemirror as a foundation?

**Comment by Rokt33r** [comment]
I think we should discard the current usage of react-codemirror. I don't think the module is covering all features of codemirror because it isn't updated for 2 years.
If there is something better in the module, we could pick the cherry.

**Comment by Rokt33r** [comment]
But, we have to refactor CodeEditor component. It is too heavy. I think we split it into several classes like `CodeEditorKeyBinder`, `CodeEditorImageDropHandler`....

**Comment by nagledb** [comment]
Thanks for the feedback. I'll start working on a PR to break up CodeEditor and to update the other 3 places to use it.
