### ISSUE TITLE
How to use vscode to debug boostnote

### ISSUE THREAD

**Issue by richardtks** [BoostIO/Boostnote#2565]
Hi, 

I have read the debug.md, inside the document, it uses the the google developer tools to debug. I am using vscode as the IDE, is it possible to debug the boostnote in vscode instead of using the google developer tools? 

Thank you.

**Comment by ZeroX-DG** [comment]
Currently no, I've been trying to configure it many times but failed every time. It would be great if someone can configure vscode to work with Boostnote.

**Comment by enyaxu** [comment]
@ZeroX-DG I push a pull request in this #2571.

**Comment by richardtks** [comment]
@enyaxu thank you, you are a life saver!

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/BoostIO/Boostnote/pull/2571
