### ISSUE TITLE
Open note in external editor

### ISSUE THREAD

**Issue by 0vermind** [BoostIO/Boostnote#2573]
Hi guys, great work!

I discovered Bootsnote and I think it could be the definitive note taking app!

I think a lot of issues can be closed immediately by using an external code editor instead of edit inside Bootsnote.
Having a button to automatically lunch the editor and passing the current note could be a solution to some requests. We don't need to compete with feature-rich IDE like VisualstudioCode, Atom, Sublime etc. 

Personally I'm a heavy Zim users, looking around to move to bootsnote completly.

**Comment by ZeroX-DG** [comment]
I do not quite understand your feature request. Can you give an example where opening the note in an external code editor will help?

**Comment by Flexo013** [comment]
You can open the .cson files in other editors.
