### ISSUE TITLE
Can't `yarn run dev`.

### ISSUE THREAD

**Issue by Paalon** [BoostIO/Boostnote#2575]
According to the document, to build Boostnote, do `yarn` then `yarn run dev` but it emits the following error:

```
↪ yarn run dev
yarn run v1.12.1
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
As far as I see the package.json, it seems the documentation is not updated.

**Comment by ZeroX-DG** [comment]
Did you pull the latest commit from master branch?

**Comment by mehr-licht** [comment]
It seems this is a yarn problem: [yarn can't run scripts in package.json #1045](https://github.com/yarnpkg/yarn/issues/1045).

try uninstall yarn and reinstalling it through a different method

**Comment by ZeroX-DG** [comment]
or just
```
npm run dev
```
All hail npm

**Comment by Paalon** [comment]
My package.json doesn't have scripts dev

```
{
  "name": "boost",
  "productName": "Boostnote",
  "version": "0.11.5",
  "main": "index.js",
  "description": "Boostnote",
  "license": "GPL-3.0",
  "scripts": {
    "start": "electron ./index.js",
    "hot": "electron ./index.js --hot",
    "webpack": "webpack-dev-server --hot --inline --config webpack.config.js",
    "compile": "grunt compile",
    "test": "PWD=$(pwd) NODE_ENV=test ava --serial",
    "jest": "jest",
    "fix": "eslint . --fix",
    "lint": "eslint .",
    "dev-start": "concurrently --kill-others \"npm run webpack\" \"npm run hot\""
  },
  "config": {
    "electron-version": "1.8.7"
  }, ......
```

**Comment by ZeroX-DG** [comment]
Then it's not the yarn issue. You don't have the latest code. You must pull the new code to your local repo.
Take a look at the latest package.json
https://github.com/BoostIO/Boostnote/blob/37933782d2e0364dc29b94b60bc00ae28f8f5161/package.json#L1-L19

**Comment by serenaFornero** [comment]
`yarn run dev`

**Comment by Dougggggg** [comment]
> or just
> 
> ```
> npm run dev
> ```
> 
> All hail npm

Thank you (as someone teaching myself, this comment has made my day)

**Comment by ZenonMok** [comment]
这种问题，我在输入npm run dev，还是没有解决之后输出的结果是：
yarn run v1.22.19
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Administrator>npm run dev     
npm ERR! Missing script: "dev"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-02-03T20_01_49_772Z-debug-0.log

**Comment by shykay** [comment]
> 这种问题，我在输入npm run dev，还是没有解决之后输出的结果是： yarn run v1.22.19 error Command "dev" not found. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> C:\Users\Administrator>npm run dev npm ERR! Missing script: "dev" npm ERR! npm ERR! To see a list of scripts, run: npm ERR! npm run
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-02-03T20_01_49_772Z-debug-0.log

i have the same question, how do you solve it
