### ISSUE TITLE
[INFO][v0.8.2 -> v0.8.3] Upgrading bug

### ISSUE THREAD

**Issue by sota1235** [BoostIO/Boostnote#258]
If you have the error like the image, please follow the steps below.

![](https://i.gyazo.com/7e6f3f920dd06b8e47b706942b35e640.png)

1. Press `OK` button.
2. Restart your machine or kill the process of Boostnote.
3. Launch Boostnote.

Related Issue https://github.com/BoostIO/Boostnote/issues/243

**Comment by kazup01** [comment]
The latest version(v0.8.3) can be downloaded from http://boostnote.io/#download .
Of course, even if you download again, there is no problem in data!
