### ISSUE TITLE
NPM install fails to find git://github.com/adobe-webplatform/eve.git - no such file or Directory

### ISSUE THREAD

**Issue by mitchellm44** [BoostIO/Boostnote#2587]
# Current behavior
ERR messages on  NPM install - using Windows 10

# Expected behavior
install should work

# Steps to reproduce
npm install

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by ZeroX-DG** [comment]
Hey @mitchellm44 did you submit the wrong repo?

**Comment by mitchellm44** [comment]
I came across the repository when researching electron - I was on my work computer. The comments are emailed to my home computer. I just cloned it on a home computer and the install did not fail here. It might be blocked at work? - I thought I captured and pasted a screen shot of the error when I posted but I do not see how to pull that up on github.  The error was for this repository.

**Comment by mitchellm44** [comment]
after doing the install - I ran the "npm audix fix" and then "npm start" and it seems to have a gif show up in he middle of the screen like it is thinking. The menu items seem to allow me to click on them - but not a thing happens - seems like it is broken.

**Comment by daiyam** [comment]
@mitchellm44 this repo uses `yarn`. Refer to [Build documentation](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md). Thx
