### ISSUE TITLE
Confirmation is needed for the Empty Trash operation.

### ISSUE THREAD

**Issue by kanonji** [BoostIO/Boostnote#2588]
# Current behavior

No confirmation for the Empty Trash operation.

![boostnote 2018-11-09 02 28 28](https://user-images.githubusercontent.com/134377/48216314-b6393680-e3c7-11e8-9b9b-98ec568ce6f2.png)

# Expected behavior

The Empty Trash operation affects much more notes than clicking trash icon on  top-right corner that have a confirmation.
I think it is better to have confirmation for the Empty Trash operation too.

![boostnote 2018-11-09 02 26 15](https://user-images.githubusercontent.com/134377/48216313-b6393680-e3c7-11e8-8f47-de2c60bcfd69.png)

# Steps to reproduce

1. Right-click on Trash
2. Click on Empty Trash

# Environment

- Version : 0.11.10
- OS Version and name : Windows 10

**Comment by ZeroX-DG** [comment]
Thank you for reporting. We'll look into this.
