### ISSUE TITLE
Crash when open Boostnote

### ISSUE THREAD

**Issue by remmyle1102** [BoostIO/Boostnote#2599]
# Current behavior
The latest version can't be opened on Ubuntu 18.10

# Environment

- Version : 0.11.10-1
- OS Version and name : Ubuntu 18.10

**Comment by ZeroX-DG** [comment]
Can you run Boostnote from the terminal and tell us the printed error?

**Comment by remmyle1102** [comment]
> Can you run Boostnote from the terminal and tell us the printed error?
![screenshot from 2018-11-11 15-53-25](https://user-images.githubusercontent.com/25774802/48310939-02ec5f80-e5ca-11e8-8358-60275b84b867.png)

**Comment by ZeroX-DG** [comment]
This is a known issue and has been fixed in https://github.com/BoostIO/Boostnote/pull/2484. The fix will be available in the next release so please wait :smiley:
