### ISSUE TITLE
Code blocks/fences within Admonitions render multiple times

### ISSUE THREAD

**Issue by zambawamba** [BoostIO/Boostnote#2614]
# Current behavior

Using code blocks within an admonition renders three copies of the block, weirdly enough twice before the description and once after. See screenshot for details.

![boostnote_admonition_bug](https://user-images.githubusercontent.com/8958171/48632747-f9943600-e9c1-11e8-8de5-b65613e4fe97.png)

I tried removing the code fence HTML definition but that doesn't make any difference.
The only console errors are about some plantUML issue. I tried removing all plantUML sections from the note on the off chance that it was related but that didn't make any difference either.

# Expected behavior

Only one code block should be rendered, the one after the description.

# Steps to reproduce

1. Define admonition.
2. Insert code fence into admonition.
3. :(

# Environment

- Version : 0.11.11
- OS Version and name : macOS 10.13.6 High Sierra

**Comment by sharif1093** [comment]
I have the same issue on 0.11.11.
However, it renders just fine if I insert an empty line between the text and the code block.

**Comment by zambawamba** [comment]
Yup, that fixes it for me too. After a restart I was able to reproduce the bug on both systems, even though it worked fine one of them before. ¯\_(ツ)_/¯ 
But the empty line is an easy workaround.

**Comment by skynyrd** [comment]
Came to here to report the same bug.

The bug can be reproduced by:
1. Creating a markdown file
1. Put these inside:
    1. `* A`
    1. `* B`
    1. Empty Line
    1. Code block

**Comment by kyan001** [comment]
![image](https://user-images.githubusercontent.com/3616478/48669244-6c74ec80-eb3b-11e8-9b01-30d24f6e5b4c.png)
![image](https://user-images.githubusercontent.com/3616478/48669246-7860ae80-eb3b-11e8-814a-343b3f332a91.png)

**Comment by daiyam** [comment]
Sorry, I'm the sinful who have made the bug. :sob:
It've just created the PR #2622 to fix it. :pensive:

**Comment by wAuner** [comment]
I have this bug as well in 0.11.11 on mac. Happens on all my notes

![screenshot 2018-11-26 at 16 28 26](https://user-images.githubusercontent.com/18383180/49023824-5c42ba00-f198-11e8-8a0a-175149f9e689.png)


![screenshot 2018-11-26 at 16 27 30](https://user-images.githubusercontent.com/18383180/49023829-5d73e700-f198-11e8-90c7-e4fdb063b3f3.png)

**Comment by daiyam** [comment]
@wAuner sorry about that. The fix has been merged into the `master` branch so it will be fixed in the next release.
