### ISSUE TITLE
Annoying Issues 

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2615]
I have reported several times a couple of annoying issues that seem to persist.

One of them is the "Create a new note" screen, after deleting a note instead of taking you to the next and the other is the gray flashing that you see when you create a new note.

It's 2018 and this is a modern web application, out of respect to our eyes, they have to be sorted out, don't you think ?

**Comment by ZeroX-DG** [comment]
I can reproduce the first issue but I couldn't reproduce the second one, can you provide steps to re-produce it?

**Comment by daiyam** [comment]
I can't reproduce none of them... The second one might be due to the rerendering of the full page (I can't find any transition animation).
@infosisio What is your system? Which theme are you using?

**Comment by infosisio** [comment]
@daiyam Default theme, I tried 3 distros and they happen in all of them, I don't know why you can't reproduce the first one, @ZeroX-DG also can.

**Comment by ehhc** [comment]
@infosisio I'm not sure what you know about the developer of this project. But a lot of them are doing it in their free time.
So if you find an error that is that annoying and (at least the first one) mihgt be easy to fix, you're honestly invited to participate, fix it and submit a pull request :)

**Comment by infosisio** [comment]
@ehhc The fix discussed is fairly simple and is important for the userbase of the project. Since I first reported it hundreds of commits have been made. I am not criticizing anyone, I just think someone involved with the project needs to care about it for the sake of the users.

**Comment by infosisio** [comment]
@ZeroX-DG Just curious, are you capable of attempting to fix the first issue yourself? I am only caring about this for the good of the projects users.

**Comment by ZeroX-DG** [comment]
Of course I can! I'm the programmer god! My code is concise, OOP or functional I can handle them all. Great programmers collect my quotes and posts to pass to their offspring. Just kidding, the fix for the first bug is simple so I'll make a PR now.

**Comment by infosisio** [comment]
@ZeroX-DG I have tested this and the same thing seems to happen but maybe I am doing something wrong?

**Comment by infosisio** [comment]
@ZeroX-DG Just curious, are you really sure you can't reproduce the second issue? I've tried it on 3 devices and I see it every single time.
