### ISSUE TITLE
[Feature request] Backup changed/deleted files for a while

### ISSUE THREAD

**Issue by vcvetkovs** [BoostIO/Boostnote#2619]
# Current behavior

When you delete or change note there is no possibility to revert changes. It could happen accidentally (cat lied on keyboard) or it could be bug (as I had with previous version when boostnote emptied my note, it was an issue after which I have switched back to Notepad++ because it is more stable, that was very important note).

# Expected behavior

There could be some trash for deleted notes and changed data (delta) history for reverting back changes. It could help to trust boostnote more ;)

**Comment by ZeroX-DG** [comment]
We currently cannot store all the changes. But when you deleted the note, you can still restore it from the trash section in the left menu.

**Comment by vcvetkovs** [comment]
@ZeroX-DG Thanks, I have forgot that we have such functionality :) And I have found also that Dropbox added version history as google drive, so it could help for such issues. So I think it isn't relevant anymore.
