### ISSUE TITLE
Displayed duplicate code block

### ISSUE THREAD

**Issue by shirakiya** [BoostIO/Boostnote#2624]
# Current behavior

I wrote as in the screenshot(A), so displayed as in the screenshot(B).

(A)
![2018-11-19 12 31 40](https://user-images.githubusercontent.com/7492121/48685090-eff41380-ebf7-11e8-9836-8f15aaf9bed6.png)

(B)
![2018-11-19 12 31 47](https://user-images.githubusercontent.com/7492121/48685096-f7b3b800-ebf7-11e8-82eb-f51e8b285017.png)

# Expected behavior

I want the note to display as below, one element of list and one code block.

- `hoge.py`

```
print('hoge')
```

# Steps to reproduce

1. write as (A)

# Environment

- Version : 0.11.11
- OS Version and name : macOS High Sierra 10.13.6（17G3025）

**Comment by webrsb** [comment]
duplicated #2614
