### ISSUE TITLE
Scripts appear duplicated

### ISSUE THREAD

**Issue by Feralamillo** [BoostIO/Boostnote#2626]
# Current behaviour

I'm in MAC OS Mojave using Boostnote 0.11.11.
Some of the notes include scripts that randomly appear duplicated when they are near a list.

For example:

<img width="1115" alt="screenshot 2018-11-19 at 14 49 19" src="https://user-images.githubusercontent.com/9921230/48714486-b7aa0080-ec0a-11e8-80e8-5ac73cec0214.png">

<img width="843" alt="screenshot 2018-11-19 at 14 49 00" src="https://user-images.githubusercontent.com/9921230/48714493-baa4f100-ec0a-11e8-9c95-7554802e6071.png">

Another example:
<img width="986" alt="screenshot 2018-11-19 at 14 47 33" src="https://user-images.githubusercontent.com/9921230/48714529-ca243a00-ec0a-11e8-8f3c-93f199b13e51.png">

<img width="1140" alt="screenshot 2018-11-19 at 14 47 07" src="https://user-images.githubusercontent.com/9921230/48714536-cc869400-ec0a-11e8-8b95-3f593a589820.png">

# Expected behavior

It should only appear the script once.

# Steps to reproduce

It happens when the script is below a list using numbers or points. 
For example:
1. This is the first item
2. This is a second item
```
Here the script that appears duplicated
```

Other example:
- This is the first item
- This is the second item
```
Here the script that appears duplicated
```

# Environment

- Version : 0.11.11
- OS Version and name : Mac OS Mojave

**Comment by dan-grayson** [comment]
Also seeing this on MacOS High Sierra v10.13.4

The issue appeared with the latest patch- it was not present before. I am also seeing the issue with extremely simple markdown notes, no proximity to a list required. I have not yet been able discern why some code snippets repeat and others do not.

<img width="721" alt="screen shot 2018-11-19 at 5 32 37 pm" src="https://user-images.githubusercontent.com/13227784/48745677-36aa3380-ec21-11e8-85ca-ac4d2c80dcbb.png">

**Comment by dan-grayson** [comment]
Since the previous version, I see changes to markdown for definition lists, and markdown-fold.

**Comment by simosdev** [comment]
Bug seems to also trigger if you have normal text directly before the code block. If you leave an empty line before code block shows only once as expected.

**Comment by ZeroX-DG** [comment]
Duplicated: https://github.com/BoostIO/Boostnote/issues/2614
