### ISSUE TITLE
Nested TODO items lose their hierarchy on check.

### ISSUE THREAD

**Issue by esalexreyes** [BoostIO/Boostnote#2627]
# Current behavior

It's a minor annoyance, but checking a Nested TODO item it immediately becomes a top-tier TODO item.

# Expected behavior

Checked TODO items remain in their hierarchy.

# Steps to reproduce

1. Create a TODO list with nested items with markdown using the following code:
```
- [ ] Task
  - [ ] Sub-Task
  - [ ] Sub-Task
  - [ ] Sub-Task
```
Resulting in the following:
- [ ] Task
  - [ ] Sub-Task
  - [ ] Sub-Task
  - [ ] Sub-Task

2. Checking any subtask on the preview panel will change the markdown to:
```
- [ ] Task
  - [ ] Sub-Task
- [x] Sub-Task
  - [ ] Sub-Task
```
Resulting in the following preview:
- [ ] Task
  - [ ] Sub-Task
- [x] Sub-Task
  - [ ] Sub-Task

3. Tasks' hierarchy breaks, and you need to edit the markdown again to make it right. Again it's a minor annoyance.

# Environment

- Version : Boostnote 0.11.11
- OS Version and name: Windows 10

**Comment by arcturus140** [comment]
@esalexreyes thank you for reporting! this problem has already been described in issue #2618 so we should close this one. 

Please follow #2618 for updates.
