### ISSUE TITLE
Trash can

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#263]
I was so sad when mistakenly deleted a post(deleted permanently), so I want a Trash can(Trash folder?)!

**Comment by asmsuechan** [comment]
Sounds good!

**Comment by asmsuechan** [comment]
To realize trash can, I need to add a state that a note stashed or not like `isTrashed` to NoteItem. I'll try this.

**Comment by asmsuechan** [comment]
Tasks:
* Add `isTrashed` state to NoteItem
* Change how to `delete` a note
* Add `Trashbox`
* Add a button to remove the cson file of note

**Comment by kazup01** [comment]
I'm looking forward it.
Totemo tanoshimi. Kitai dai.
