### ISSUE TITLE
Paste from IDE is just plain wrong

### ISSUE THREAD

**Issue by takacsot** [BoostIO/Boostnote#2634]
# Current behavior

I am using Dbeaver db client and I just copied some sql to Boostnote.

Plain SQL is pasted as the following

```sql
     p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Monaco} p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Monaco; min-height: 15.0px} p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Monaco; color: #941100} span.s1 {color: #941100} span.s2 {color: #ff2600} span.s3 {color: #000000} span.s4 {color: #0433ff} 

select \* from pg\_user\_info;

alter  user u1 CONNECTION  LIMIT  10;
```

the sql editor is syntax highlighting of course.

The same issue when coping from Eclipse.

# Expected behavior

Well. As before. Just paste the text.

# Steps to reproduce

- Version :0.11.11 
- OS Version and name : macos sierra

**Comment by ZeroX-DG** [comment]
Duplicated: https://github.com/BoostIO/Boostnote/issues/2628
