### ISSUE TITLE
Can't see cursor

### ISSUE THREAD

**Issue by luis-pato** [BoostIO/Boostnote#2638]
# Can't see cursor since last update

Since i updated to 0.11.11 (on a mac) most of the time (i would say 95% of the time) i can't see the cursor.
I am using the Dark Theme with the Darcula Editor Theme (not to be mistaken with Dracula).
Sometimes i can see it, but most of the time not (and i can't really figure out when or how)

# Expected behaviour

We should always see the cursor position so we know where we will write or delete.

# Steps to reproduce

I don't need to do anything special to reproduce it. I just open the app and i can't see the cursor.
I have tried to change note, change group, change theme, editor theme,..., but couldn't make it work.

# Environment

- Version : 0.11.11
- OS Version and name : OSX 10.13.6 High Sierra

Please let me know if there is some other information you need.

**Comment by luis-pato** [comment]
i have tried a couple of different things.
resizing the window doesn't seem to help. What sometimes made a difference was the zoom factor.
I had it set to 90%. If i change it o 100% or 80% it works better. When i set it back to 90% i get again the same problem.
Can someone else reproduce this problem?

**Comment by Flexo013** [comment]
@luis-pato Are you still experiencing this issue?

**Comment by luis-pato** [comment]
i have stopped using Boostnote, because without seeing the cursor it was unusable.

I have installed it again and i could now see the cursor in all themes and different zoom levels.
If no one else has had this problem, it was probably just something in my local machine or the bug was fix already!   ;)

**Comment by Flexo013** [comment]
Thanks for the information! Glad the problem is now solved :)
