### ISSUE TITLE
Paste code and the format looks not good.

### ISSUE THREAD

**Issue by ellisonLou** [BoostIO/Boostnote#2640]
# Paste code and the format looks not good

![image](https://user-images.githubusercontent.com/22023447/48979585-31088e00-f0f8-11e8-9e0b-dbfd62a6c97e.png)

![image](https://user-images.githubusercontent.com/22023447/48979550-a9228400-f0f7-11e8-9e31-6461d5d60c07.png)

# Expected behavior

This is code in vscode:

![image](https://user-images.githubusercontent.com/22023447/48979555-bf304480-f0f7-11e8-8cb8-f9777a42b977.png)

# Steps to reproduce

Pretty like Boostnote! Wish to add auto format or a code format shortcut, thank you : )

# Environment

- Version : 0.11.11
- OS Version and name : macOs 10.14.1 majove

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2628
