### ISSUE TITLE
Request: Text Background Color in Code Snippet

### ISSUE THREAD

**Issue by JasonCraneAdkins** [BoostIO/Boostnote#2649]
# Current behavior
Code Hilighting works well
![image](https://user-images.githubusercontent.com/8469829/49007812-ab72f580-f16c-11e8-90c2-c3f9998b12b6.png)

# Expected behavior
But what i would Like to see is text background Color to highlight important parts. Without loosing code highlighting
![unbenannt](https://user-images.githubusercontent.com/8469829/49008928-67cdbb00-f16f-11e8-869c-a104a7e83f8a.png)

# Steps to reproduce

n.v.

# Environment

- Version : 0.11.11
- OS Version and name : Win 10

**Comment by Flexo013** [comment]
Code snippets aren't meant for additional formatting.
