### ISSUE TITLE
Code blocks showing up blank, undeletable

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#2652]
# Current behavior

If i write some code between backticks the rendering of my whole note messes up, as you can see by these images: [link](https://imgur.com/a/w7U5O5k)

# Expected behavior

There shouldn't be multiple code blocks when I only wrote one.

# Steps to reproduce

The behaviour is very weird but easy to reproduce. 
The multiple code blocks appear because I tried to put the instructions in the list (mov cx,0 etc.) in a code block, but it was behaving wrong: When I typed 2 backticks it wouldn't type the third one, but if i pressed the button again it would write three more.
If I put code inside of those it wouldn't show anything in the rendered note, just a blank code block, and if I tried to backspace it started printing red dots on the note, like password dots but red, and I think that now there's some invisible bugged character that's causing the code blocks to clone like that. I tried erasing part of my note but there's no way to delete them.

I hope my explanation was clear, I can send a video if needed.

# Environment

- Version : 0.11.11
- OS Version and name : macOS 10.14.1

**Comment by ZeroX-DG** [comment]
Very sorry about your problem. This is a known issue and the fix for this has been merged. This won't happen again in the next version. Duplicated: https://github.com/BoostIO/Boostnote/issues/2614
