### ISSUE TITLE
url-like text convented into a link

### ISSUE THREAD

**Issue by cyNew** [BoostIO/Boostnote#2654]
Hey, I have a problem.
When I use the * symbol to emphasize a python file name, it is automatically converted into a link in the  preview.
So, how to close this option to disable conversion of url-like text to a link?
Maybe, I hope that add this option to the settings.
Thanks.
<img width="229" alt="2018-11-29 9 29 28" src="https://user-images.githubusercontent.com/42455629/49193219-511aa480-f3b9-11e8-8162-5b654c67de43.png">
<img width="189" alt="2018-11-29 9 29 33" src="https://user-images.githubusercontent.com/42455629/49193220-524bd180-f3b9-11e8-8ef6-dc2db79f6c19.png">

**Comment by ZeroX-DG** [comment]
This is a known issue: https://github.com/BoostIO/Boostnote/issues/2540
