### ISSUE TITLE
Option to have raw markdown view by default when navigating list

### ISSUE THREAD

**Issue by dakuzen** [BoostIO/Boostnote#2659]
# Current behavior

Currently if you have changed the view of a markdown file to editor only, then when navigating the Markdown files you see the Preview display until you place the cursor into the editor area.  This creates a jarring transition into and out of the Preview mode, especially when switching between applications.  The "Lock" feature provides some reprieve, but it cannot be set by default and seems counter-intuitive to the toggle.

# Expected behavior

It would be nice to have an system `Interface` option to set the default view option for Markdown files,  and change the view toggle controls to a three-way Editor / Split / Preview mode similar to Joplin.

# Steps to reproduce

1. Create a markdown file
2. Change the view to Editor only
3. Remove focus and return focus

# Environment

- Version : v0.11.11 
- OS Version and name : Win10

**Comment by ZeroX-DG** [comment]
I think this is the intended behavior. If you want you can configure how Boostnote will switch to preview mode in `interface` tab.

![image](https://user-images.githubusercontent.com/12984316/49334996-73f5c480-f616-11e8-9b26-b9f6e99fda64.png)

**Comment by Flexo013** [comment]
The three way split will be possible if this feature gets implemented: https://github.com/BoostIO/Boostnote/issues/2955
