### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by dakuzen** [BoostIO/Boostnote#2660]
# Current behavior

We are using Boostnote with a local Google Drive folder, which works well except that when the file is updated there is no recognition of the change by Boostnote, and when a local change is made in Boostnote it overwrites the modified file without 

# Expected behavior

Some sort of notification and conflict resolution process.

# Steps to reproduce

1. Create a Markdown note in Boostnote.
2. Open the raw `.cson` file in a text editor and make a change, change the updatedAt date and some value within the content block.  Save it.
3. Make a change to the same file in Boostnote.
4. View raw `.cson` file - your previous manual changes are overwritten without warning.

# Environment

- Version : v0.11.11 
- OS Version and name : Win10

**Comment by ZeroX-DG** [comment]
This is a very complicated feature which I think is not suitable for the current app. However, I'll suggest this feature to the dev team to add in the rewrite version of this app.

**Comment by ZeroX-DG** [comment]
![image](https://user-images.githubusercontent.com/12984316/49515885-b47d6880-f8ca-11e8-90ef-fbae9e3c0587.png)
Good news! The re-write version of the app can take care of it.
