### ISSUE TITLE
xml code syntax bugs

### ISSUE THREAD

**Issue by KROT47** [BoostIO/Boostnote#2662]
I'm experiencing strange behavior with xml and apache configs particulary.

For example this fragment:
```
<VirtualHost *:8080>
    <Directory "/opt/lampp/apps/shop/htdocs/web">
    </Directory>
</VirtualHost>
```

# Current behavior
```
<virtualhost *:8080="">
    <directory "="" opt="" lampp="" apps="" shop="" htdocs="" web"="">
    </directory>
</virtualhost>
```

# Expected behavior

```
<VirtualHost *:8080>
    <Directory "/opt/lampp/apps/shop/htdocs/web">
    </Directory>
</VirtualHost>
```

I think it is easy to repeat with any xml example.

So IMO:
1. No new symbols should appear: `*:8080=""`
2. Letter case should also stay as is: `<virtualhost...`
3. Strings should stay as they were written: `"="" opt="" lampp="" apps="" shop="" htdocs="" web"=""`

Github MD does it correctly.

Sorry if it is duplicate... Couldn't find any.

**Comment by arcturus140** [comment]
I can replicate the issue only with "Allow dangerous tags" enabled. 

    ```xml
    <VirtualHost *:8080>
        <Directory "/opt/lampp/apps/shop/htdocs/web">
        </Directory>
    </VirtualHost>
    ```

This issue should probably be merged into #2644.
