### ISSUE TITLE
Back Tick Marked off Code Displays Incorrectly

### ISSUE THREAD

**Issue by mmcken3** [BoostIO/Boostnote#2663]
# Current behavior

Currently if you enter a few blocks of code marked off with the triple backtick then they may render incorrectly in the formal display mode if there is not a newline between the text and the block. Here is a picture of my editor and then the display of the markdown. 

You can see in the pictures that if where is a line of text above the marked off code, then it will display the first block of code that is below the line, directly above the line twice. 

Markdown Editor:

![markdown-ss](https://user-images.githubusercontent.com/16723603/49332385-507d3c00-f57a-11e8-931c-63bf265e4d84.png)

Preview Display:

![preview-ss1](https://user-images.githubusercontent.com/16723603/49332386-52df9600-f57a-11e8-804f-9d16ecb8e6ad.png)

With newlines:

![withnewline-md](https://user-images.githubusercontent.com/16723603/49332482-76571080-f57b-11e8-96df-86209505f98b.png)

![withnewline-pv](https://user-images.githubusercontent.com/16723603/49332483-79520100-f57b-11e8-9a5b-12dfd4cd55f0.png)

# Expected behavior

I would anticipate that instead of the duplication above the line of text that the code snippet would only appear where it is placed when viewing the nice display of the markdown text. Like below

Line of text:
```
{
    "name": "something"
}
```

# Steps to reproduce

1. Write a line of text in markdown. Add a single new line at the end of line of text.
2. Create a triple backtick marked section for a code snippet.
3.  Ensure there is not a blank line between the text line and the snippet.
4. Switch to the markdown display mode and see this block duplicated twice above the line of text.

# Environment

- Version : Version 0.11.11 (0.11.11)
- OS Version and name : Mac OS High Sierra 10.13.6

**Comment by ellisonLou** [comment]
I have this issue too.

![image](https://user-images.githubusercontent.com/22023447/49334687-a1427280-f616-11e8-9893-1b91049db706.png)

Version: 0.11.11
OS Version and name: Mac OS 10.14.1

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2614
