### ISSUE TITLE
[bug] Code blocks displayed multiple times when following a text block without a whiteline separation

### ISSUE THREAD

**Issue by neutrinoceros** [BoostIO/Boostnote#2670]
# Current behavior

Here's an example: 

<img width="1044" alt="screenshot 2018-12-02 at 20 55 15" src="https://user-images.githubusercontent.com/14075922/49344245-cbc31880-f674-11e8-9afa-220c2ae32464.png">

# Expected behavior

The code block should appear only once in the display panel

# Steps to reproduce

Happens every time I do not include an empty line between text and code.

# Environment

- Version 0.11.11
- OS Version and name : MacOS Mojave 10.14.1

**Comment by ZeroX-DG** [comment]
Duplicated: https://github.com/BoostIO/Boostnote/issues/2614
