### ISSUE TITLE
Ticking nested tick boxes moves them to parent.

### ISSUE THREAD

**Issue by Nicolaasjvv** [BoostIO/Boostnote#2673]
# Current behavior

When ticking nested check boxes (children), the ticked child is moved to the parent tier and all subsequent children recieves a ~strikethrough~ without being ticked.

Before ticking:
![image](https://user-images.githubusercontent.com/14290628/49359526-26915a00-f6df-11e8-9a15-a208c1197fc6.png)

After ticking "Parent1.Child1"
![image](https://user-images.githubusercontent.com/14290628/49359548-3a3cc080-f6df-11e8-84c4-871332c83970.png)

# Expected behavior

For only the single item checked to become checked and strikethrough. And not to affect any parents, hierarchy or siblings. The only exception: If a parent is ticked, then it may affect children. 

# Steps to reproduce

1. Create a checklist by using markdown "- [ ] Your text here"  
2. Create a hierarchy by putting a tab before some items.
3. Tick a child checkbox. 

# Environment

- Version : Boostnote 0.11.11
- OS Version and name : Windows 10 Pro (10.0.17134 Build 17134

**Comment by ZeroX-DG** [comment]
Thank you for reporting, this is a known issue. Please follow it here: https://github.com/BoostIO/Boostnote/issues/2618
