### ISSUE TITLE
Pasting of note link from copy button results in incorrect format (while in editor mode)

### ISSUE THREAD

**Issue by chiangs** [BoostIO/Boostnote#2674]
# Current behavior

When I go to the information panel to copy the note's link and use the copy button, then paste it into another note. The format results in an incorrect format where there are extra slashes. If I remove those two slashes, the link registers and works as expected. 

The incorrect format only happens while using the copy button and copying while in editor view mode and if link is pasted into a note.

If I start in preview mode and copy or if I am in all the conditions above but paste outside the note, like in a browser, then the link format is fine. So this might be an editor view problem.

# Example & Repro:
Be in editor view, not preview
Click on (i) of a note, click on copy button of the note link, paste it into another note.
The result is: 
```
\[Note Name\](:note:acaf547d-1f35-489a-b9a3-119ca121b6ee) 
```
**where it should be:**
```
[Note Name](:note:acaf547d-1f35-489a-b9a3-119ca121b6ee)
```
If you copy while in preview mode or paste outside a note, then the format will be fine.

# Environment

- Version : 0.11.11
- OS Version and name : Windows 10 Home, v1803

**Comment by ZeroX-DG** [comment]
Hi! Thank you for reporting, this is a known issue. Please follow it here: https://github.com/BoostIO/Boostnote/issues/2628
