### ISSUE TITLE
SQL code snippet in markdown document duplicates sql in markdown preview

### ISSUE THREAD

**Issue by an-d-uu** [BoostIO/Boostnote#2677]
# Current behavior
When using the sql code snippet in markdown its duplicating duplicating the code in view mode.

# Expected behavior

I am expecting the sql code snippet to only show once.

# Steps to reproduce

1. create a bullet point with some information 
2. create a ```sql section with sql code 
3. go to preview mode and you will see it duplicated

# Environment
![image](https://user-images.githubusercontent.com/39595991/49383889-6b1cf580-f6df-11e8-825f-6a332fbfe4fe.png)

[Markdown document with SQL snippet duplication.txt](https://github.com/BoostIO/Boostnote/files/2640136/Markdown.document.with.SQL.snippet.duplication.txt)

- Version : 0.11.11
- OS Version and name : WIndows 8.1 Pro

**Comment by genericmoniker** [comment]
Another example -- this document renders the sql code block three times:

~~~
Insert multiple rows
--------------------
Possibly not supported in all database systems
```sql
INSERT INTO table (column1, column2)
VALUES ('value1a', 'value2a'),
       ('value1b', 'value2b');
```
~~~

Adding a blank line before the code block fixes the problem:

~~~
Insert multiple rows
--------------------
Possibly not supported in all database systems

```sql
INSERT INTO table (column1, column2)
VALUES ('value1a', 'value2a'),
       ('value1b', 'value2b');
```
~~~

I'm not sure if it is just SQL -- I was seeing similar behavior with YAML over the weekend.

**Comment by ZeroX-DG** [comment]
This is a known issue, please follow it here: https://github.com/BoostIO/Boostnote/issues/2614
