### ISSUE TITLE
markdown code render error

### ISSUE THREAD

**Issue by Kutear** [BoostIO/Boostnote#2679]
# Current behavior

![image](https://user-images.githubusercontent.com/8605389/49424359-49059f00-f7d5-11e8-80a2-080f0ffef062.png)

# Expected behavior
With Blank line
![image](https://user-images.githubusercontent.com/8605389/49424428-89651d00-f7d5-11e8-9c23-a4bac7d05cab.png)

# Steps to reproduce

1. reproduce everytime
2. 
3. 

# Environment

- Version : Boostnote 0.11.11
- OS Version and name : MacOs 10.13.6 (17G65)

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2614
