### ISSUE TITLE
[Feature Request] Automatic Parsing DOI/arXiv ID etc.

### ISSUE THREAD

**Issue by guanqun-yang** [BoostIO/Boostnote#2680]
As a researcher, I need to deal with up to hundreds of papers every day. DOI/arXiv IDs are unique identifier for them for swift and precise location. Sometimes I could easily acquire these numbers but copy & paste and in Google and find the right website takes extra time and when you multiply the time with 100 or even 1000, it would be quite considerable.

There are some patterns in these IDs and the hope is that when clicking the ID, I could jump to the corresponding site. Say, one paper I read today has arXiv ID 1811.10104 and the corresponding abstract page is https://arxiv.org/abs/1811.10104. DOI is similar,  for paper with ID 10.1109/TPAMI.2007.70733, its abstract page is https://doi.org/10.1109/TPAMI.2007.70733.

By my observation,  patterns in the IDs seem to be difficult to contradict with normal text and it is unlikely to make some unnecessary confusion for users who do not intend to input these information.

Thank developer team in advance.

**Comment by ZeroX-DG** [comment]
This is out of scope for Boostnote and will not be implemented (Unless you can convince me with a reasonable reason). However, I'll show you a small trick back when I study for IELTS. Sometimes I want to search for a word on Cambridge dictionary and googling it is slow and just like your case, the link for all the words on Cambridge dictionary website share the same form
```
https://dictionary.cambridge.org/dictionary/english/<THE_WORD_RIGHT_HERE>
```
So for example, if I want to search for the word `dog` I'll need to navigate to
```
https://dictionary.cambridge.org/dictionary/english/dog
```
So I created a small javascript code and bookmark it in my browser so everytime I needed to search for a word, I can just click on it and it will as for my word and then navigate to the correct page.
The code is:
```
javascript:word = prompt("word to search");if(word)window.open("https://dictionary.cambridge.org/dictionary/english/" + word, "_blank")
```
In your case, it would be something like this:
```
javascript:identifier = prompt("Paper identifier");if(identifier)paperID=prompt("Paper ID");if(paperID && identifier=='arXiv')window.open("https://arxiv.org/abs/" + paperID, "_blank");else if(paperID && identifier=='DOI')window.open("https://doi.org/" + paperID, "_blank");
```
To add it to your bookmark, you can follow this instructions:
- In chrome hit `ctrl + shift + o` and it will take you to the bookmark manager page
- Then on the top right of the page is an icon with 3 dots. Click on in and select add new bookmark from menu
- The name section you can pick any name that you want (maybe `research paper shortcut`)
- Then input the js code above to the url field and hit save
- Now the bookmark will appear on your bookmark bar. When ever you need to search for a paper just click on it and it will first ask the identifier of the paper (input DOI or arXiv) Then it will ask for the id of the paper. After you input all the information, it will take you to the right site for the paper.

Good luck with your research.

**Comment by guanqun-yang** [comment]
This is pretty useful and actually largely resolves my problem. Thank you so much for sharing!

**Comment by ZeroX-DG** [comment]
Close this as won
