### ISSUE TITLE
table of contenst not working

### ISSUE THREAD

**Issue by robertocastellotti** [BoostIO/Boostnote#2681]
# Current behavior
Hi
When i "print to a file" a markdown note with boostnote tool i get a pdf in which i cannot use toc item
Clicking on a toc item it doesn't move to the corresponding header, wile it does while using the boostnote wiewer
here you have my file (btw sorry it is in spaghetti language), 
>"https://gist.github.com/robertocastellotti/c7ae833b2ff931f9d2bba8216faf8f31.js"
# Steps to reproduce
Just try to print to a file the note i pasted
# Environment

- Version : 0.11.11
- OS Version and name : Manjaro Linux (arch)

Ciao!

**Comment by ZeroX-DG** [comment]
It works just fine with me (Linux Mint). Can you restart Boostnote to see if it help?

**Comment by ZeroX-DG** [comment]
Closed due to inactivity
