### ISSUE TITLE
Code block render twice after list

### ISSUE THREAD

**Issue by chenbin11200** [BoostIO/Boostnote#2683]
# Current behavior

if I write in markdown:

1. blablabla
```shell
vi blablabla
```
The code block will be rendered twice.
That happens only when a code block in the numeric list.(As far as I observed.)

# Expected behavior

Code block should rendered only once.

# Environment

- Version : 0.11.11
- OS Version and name : Win10

**Comment by ZeroX-DG** [comment]
This is a known issue and has been fixed in the next version: https://github.com/BoostIO/Boostnote/issues/2614
