### ISSUE TITLE
Duplicated code block

### ISSUE THREAD

**Issue by weaming** [BoostIO/Boostnote#2691]
# Current behavior

![image](https://user-images.githubusercontent.com/10275711/49711530-e285e400-fc0d-11e8-90c4-dfa7db81b7b1.png)

# Expected behavior

![image](https://user-images.githubusercontent.com/10275711/49711541-f3cef080-fc0d-11e8-9f4a-ad031c9172ce.png)

# Steps to reproduce

1. Paste the content of gist https://gist.github.com/weaming/49a514f28afc085b8e60b32aaa507754 to boostnote
2. If only one blank line between `<ul>` and code block, the render will produce two blocks of code with same content.
3. If more than one blank lines, will be same as expect.

# Environment

- Version : 0.11.11
- OS Version and name : OSX 10.13.3

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2614
