### ISSUE TITLE
[Feature Request] Automatic syntax recognition

### ISSUE THREAD

**Issue by egoisticalgoat** [BoostIO/Boostnote#2693]
# Current behavior

When i create a new snippet and type/paste any code into it, i have to manually select the snippet language.

# Expected behavior

Unless explicitly selected by the user, analyze the snippet and decide on the language. 
Might be easier or harder depending on the languages, since not all are as obvious as others (e.g. shebang line, opening PHP tag, etc.)

# Steps to reproduce

1. Create a new snippet note
2. Write code

# Environment

- Version : 0.11.9
- OS Version and name : Ubuntu Budgie 16.04, Kernel 4.18.16

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2351
