### ISSUE TITLE
Discrepency between edit and read view strikethrough text

### ISSUE THREAD

**Issue by andyklimczak** [BoostIO/Boostnote#2698]
# Current behavior

When trying to strike through a line of text, the text looks properly struckthrough in edit view of the note, but does not in the read view. My example text was:
```
~~a note here
```

#### Looks properly strikethroughed in the edit view
<img width="730" alt="screen shot 2018-12-12 at 1 10 04 pm" src="https://user-images.githubusercontent.com/4869742/49889395-5f33e080-fe0f-11e8-867f-dac3eb8a1c72.png">

#### No longer strikethroughed in the read view
<img width="734" alt="screen shot 2018-12-12 at 1 10 09 pm" src="https://user-images.githubusercontent.com/4869742/49889394-5f33e080-fe0f-11e8-998a-2b908b3971d5.png">

# Expected behavior

Edit and read views are consistant

# Steps to reproduce

1. Create a new markdown note
2. Add `~~a new note` to the note
3. Notice the text is strikethrough in the edit view
4. Click away to go to the read view, text is no longer strikethrough

# Environment

- Version : Version 0.11.11 (0.11.11)
- OS Version and name : macOS Mojave 10.14.1

**Comment by KuangLei** [comment]
I think within this design, I could have a real-time styling feedback when I was typing. It can also remind me that I should add another `~~` to close the strike-through zone.  

Btw, the `**Bold` and `*Italic` follow the design too.  

Thanks.

**Comment by ZeroX-DG** [comment]
The correct syntax is `~~text~~`. You forgot to close the `~~`

**Comment by andyklimczak** [comment]
Gotcha, I wasn't sure if it was a bug that the strikethrough text was shown when only `~~test` was typed in the edit view

**Comment by ZeroX-DG** [comment]
@andyklimczak It's the default behavior of CodeMirror: https://codemirror.net/mode/gfm/index.html
