### ISSUE TITLE
Code block withs line numbers

### ISSUE THREAD

**Issue by eschmid72** [BoostIO/Boostnote#27]
I have added a line numbering to the code blocks in the markdown preview:

https://github.com/eschmid72/Boostnote/commit/891cd3124f40545dfc2ccdd07373f4e26ec3f2e3

If the changes are ok, I will send a pull request.

- The gitter maybe should be able to be turned off in the settings.

I would also implement a copy-button: The button will be displayed only when the mouse is over the code, when you click on the button, the code will be copied into the clipboard.

**Comment by dojineko** [comment]
:+1:

**Comment by Rokt33r** [comment]
Looks good to me. Send a new PR. 👍 
I'll make the gutter configurable.

**Comment by Rokt33r** [comment]
Released. v0.5.12
