### ISSUE TITLE
Optimal placement for the " Add storage" button

### ISSUE THREAD

**Issue by Gregordy** [BoostIO/Boostnote#270]
Hi!

I think that the "Add storage" would be much better placed at the top of the Storage menu.

Currently, it is placed at the very bottom of the said menu.

It then forces one to scroll down to the very bottom to add a new storage.

This very bottom can be very long to reach for those that have a lot of storages and/or folders.

I also had trouble to find it at first because it is the only way to add a storage!

Any feedback on my proposition?

Either way, keep it up! I love your software guys!

**Comment by kazup01** [comment]
Hi Gregordy san,

> I also had trouble to find it at first because it is the only way to add a storage!
Come to think of it, maybe you are right.
We will update it. (e.g. Place a button at the top.

Thank you for your feedback!

**Comment by kazup01** [comment]
Done! Thank you for your message! @Gregordy
