### ISSUE TITLE
Can I use snippet finder launcher with Ctrl(Cmd) + Alt + S ?

### ISSUE THREAD

**Issue by SatoshiKawabata** [BoostIO/Boostnote#2700]
Before I heavily used snippet finder with "Ctrl(Cmd) + Alt + S". Now I can't use it... 
How can I use it?

**Comment by shuntaroy** [comment]
Unfortunately, that feature was discarded for a long time ago.
See #1503.
There seems no hope for us to get it again, very sadly.
I rather recommend other snippet manager apps.

**Comment by SatoshiKawabata** [comment]
@shuntaroy  I'm going to watch the issue. Thanks.
