### ISSUE TITLE
Boostnote storage location empty and export doesn't export anything

### ISSUE THREAD

**Issue by challman1** [BoostIO/Boostnote#2703]
I plan to re-image my laptop. I want to copy my notes off the current SSD. When I looked in my customer storage location, nothing is present. I have created 10 notes prior to this. I can't check the default location because I don't know where that is.

I've rebooted and uninstalled/installed but the same thing happens. I have tried to export all my notes. When I chose the format type, it asks for the directory. After I select the directory, the window disappears without any exported data. 

I expect the app to save notes into the chosen storage location. I expect the export to work.

I'm running this on Xubuntu 18.01..

**Comment by OnlineVagrant** [comment]
Preferences --> Storage shows your location for each folder.
In the red rectangle you have the file path of that specific folder and clicking the icon in the red square takes you to the folder location.  
![q](https://user-images.githubusercontent.com/39413259/49972524-5f63d700-ff08-11e8-9a65-44948e8d0016.PNG)

**Comment by challman1** [comment]
I realize this. I wouldn't have asked if I hadn't already checked that. Here is the path:

![selection_009](https://user-images.githubusercontent.com/45859812/49979828-cee4c100-ff1e-11e8-8be2-a61f6828a4b3.png)

Here is the filesystem:

![selection_010](https://user-images.githubusercontent.com/45859812/49979846-e2902780-ff1e-11e8-93b8-e99e8812e324.png)

There are no files present. When I export, all the app does is take me to the filesystem to select a folder and then back to Boostnote.

**Comment by travis23** [comment]
I also have problems with export not exporting anything. I am using Windows 10 with Boostnote version 0.11.12. I select the folder for export and the popup message comes up Exported to "[directory]", but when I go to  the directory it is empty.

**Comment by Flexo013** [comment]
Exporting a folder seems to work fine in 0.11.17 on Windows 10.

@travis23 @challman1 Can you confirm this is still an issue?

**Comment by challman1** [comment]
No. I was able to get it working. I'm traveling at the moment so i can't
check into what I found.

**Comment by Flexo013** [comment]
That's alright. Feel free to let us know whenever you get back from your travels.

If another user on xubuntu could let us know about the status of this that would also be sufficient to close this issue.

**Comment by Flexo013** [comment]
@challman1 Could you try this again?

**Comment by challman1** [comment]
This works well once I figured out how the app was storing data. I've been
storing my notes on a Google Drive backup directory for quite a while now.
