### ISSUE TITLE
Respect self-signed certificates

### ISSUE THREAD

**Issue by bkkgbkjb** [BoostIO/Boostnote#2705]
When using `![](https://testserver.com:443/pictures/upload_1bz213cxasd1321as23dsadb213s90c8ed.png)` to fetch the online pictures, if the certificate of `testserver` is self-signed, `boostnote` would not go to fetch the corresponding file as expected.

However, currently there seems no way to let `boostnote` recognize a self-signed ca as the user's wish.
I'm working on Linux Debian sid, `boostnote` is in `Boostnote 0.11.11` and I have installed my ca via dpkg-reconfigure ca-certificates. All other standard softwares like `curl` and `wget` can successfully respect my ca except `boostnote`

**Comment by Flexo013** [comment]
I will investigate this issue when I am at my Linux machine again.

**Comment by Flexo013** [comment]
I have tested this with a self-signed certificate on Ubuntu 16.04 with Boostnote 0.12.1 and found no problems. The images load fine. I am closing this for now, as this seems fixed.

@bkkgbkjb Feel free to reopen this issue if you still experience this issue.
