### ISSUE TITLE
Translations are missing in the menu

### ISSUE THREAD

**Issue by lutz** [BoostIO/Boostnote#2706]
# Current behavior

Currently the translations are not displayed in the menu.

![image](https://user-images.githubusercontent.com/26437097/50004861-b9b47480-ffa8-11e8-9753-d476a04c8e43.png)

# Expected behavior

That the translations are displayed in the menu

# Steps to reproduce

Select German in the settings!

# Environment

- Version : 0.11.11
- OS Version and name : Windows 10 Pro x64 October Update

**Comment by KuangLei** [comment]
It seems that the menu bar is not available to be translated on any languages.

**Comment by Flexo013** [comment]
Let's add this to #2365
