### ISSUE TITLE
Minimal menu structure

### ISSUE THREAD

**Issue by lutz** [BoostIO/Boostnote#2709]
# Current behavior
The current menu structure looks like this
```
Boostnote
│  Preferences
│  Exit  
File
│  New Note
│  Focus Note
│  Export as
│  [...]
View
│  [...]
Help
│  [...]  
```
# Expected behavior

In my opinion, it would be more consistent with other programs to place the Boostnote commands in the other menus.

```
File
│  New Note
│  Focus Note
│  Export as
│  [...]
│  Preferences
│  Print
│  Exit
View
│  [...]
Help
│  [...]  
```

# Environment
- Version : 0.11.11
- OS Version and name : Windoes 10 Pro x64 October Update

**Comment by jasselin** [comment]
Being able to choose between a Windows-style and Mac-style menu layout would be nice.

**Comment by Flexo013** [comment]
I think that sticking to one layout should be fine. It's not like there are hundreds of options that are hard to find; a bit of trial and error with memorization easily does the job.

**Comment by arcturus140** [comment]
I agree. I think the current design is fine. This shouldn't be a user setting.

**Comment by Flexo013** [comment]
Closing this for now.

If people wish to continue this discussion, then simply leave a comment here and we will reopen it.
