### ISSUE TITLE
No storage is loaded when one storage location is invalid

### ISSUE THREAD

**Issue by maxpei** [BoostIO/Boostnote#2711]
# Current behavior

I have configured two storage locations in BoostNote, one corresponding to a regular folder and the other being mounted when necessary by Cryptomator. But if I open BoostNote without running Crypomator first, the other storage location is not loaded either.

# Expected behavior

It's fine the unmounted storage location is not loaded, but I would expect the other regular location to be loaded as usual.

# Steps to reproduce

1. Create a vault directory in Cryptomator
2. Open the vault and mount it to a drive, say, S:\
3. Add a storage location on S:\ to BoostNote
4. Close BoostNote and unmount S:\
5. Open BoostNote again. 

No other storage locations will be loaded either.

# Environment

- Version : 0.11.11
- OS Version and name : Windows 8.1 Pro (64-bit)

**Comment by ZeroX-DG** [comment]
I can imagine why this happened but it would be great if you can provide a screen shot of the dev console so that I can know the exact problem.

**Comment by maxpei** [comment]
Thanks, here is the screenshot.

![image](https://user-images.githubusercontent.com/7021710/50050789-34fc5e80-0140-11e9-8376-3df822d6394b.png)

**Comment by MiloTodt** [comment]
#2801 should fix this.
