### ISSUE TITLE
Add v0.11.12 release tag to this repository

### ISSUE THREAD

**Issue by nix6839** [BoostIO/Boostnote#2714]
Similar #2513 issue

For the AUR package on Arch Linux we build the source from this repository. The latest version was released on boost-releases but the release isn't yet tagged on this repo (https://github.com/BoostIO/Boostnote/releases).

Thanks in advance!

**Comment by daiyam** [comment]
@Rokt33r please don't forget the tag 😉

**Comment by Rokt33r** [comment]
I did it! https://github.com/BoostIO/Boostnote/releases/tag/v0.11.12
