### ISSUE TITLE
Support tags names with `/`

### ISSUE THREAD

**Issue by PuerorumOne** [BoostIO/Boostnote#2717]
# Current behavior

Selecting a tag with `/` in the title does not open its corresponding page.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/45951653/50115873-ee465b80-0248-11e9-9ead-6749610f877b.png">

If I have a tag with `-` instead of `/` it works fine. Example:
`/DEVOPS/HOWTOS/K8s` - doesn't work - stays on the old page
`DEVOPS-HOWTOS-K8s` - works fine as a tag and opens its page

# Expected behavior

Clicking on `/DEVOPS/HOWTOS/K8s` tag should open its page, I think 🤞 

# Steps to reproduce

1. Create a new page and assign a tag with `/` in the title like `/DEVOPS/HOWTOS/K8s`
2. In the Tags view, click on that tag - it will not open the page that has that tag.
3. To compare: create a new page with tag without '/'  like `DEVOPS-HOWTOS-K8s`. Clicking on that tag in Tags view will open that page.

# Environment

- Version : `Version 0.11.8 (0.11.8)`
- OS Version and name : `High Sierra 10.13.6 (17G65)`

**Comment by daiyam** [comment]
@PuerorumOne please update to the last version, it has been fixed since the `v0.11.10` 😉
