### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by empeje** [BoostIO/Boostnote#2718]
# Current behavior

I'm looking for update button, now I need to download binary manually.

# Expected behavior

Update button not available.

# Steps to reproduce

1. Open Boostnote
2. Look for the update button in the menu bar
3. Nothing there

# Environment

- Version: Mac OSX High Sierra
- OS Version and name: 0.11.11

**Comment by ZeroX-DG** [comment]
Usually, there will be a message box saying `Update available!`.

**Comment by empeje** [comment]
I got the message box prompt when there's an update but I can't trigger it manually.

**Comment by Rokt33r** [comment]
Closed because https://github.com/BoostIO/Boostnote/issues/2827 covers this issue.
