### ISSUE TITLE
Can no longer insert from clipboard on macOS

### ISSUE THREAD

**Issue by BjarkePedersen** [BoostIO/Boostnote#2719]
# Current behavior

When trying to insert an image from the clipboard, nothing happens.

# Expected behavior

When inserting an image from clipboard, it will insert the image and it will look something like this in the markdown:
`![Screenshot 2018-12-18 at 09.28.28.png](:storage/6d36e1fa-99ad-4953-8ada-7afa726719d7/829ee765.png)`

# Steps to reproduce

1. Copy image to clipboard. 
2. Insert image using command+V

# Environment

- Version : 0.11.12
- OS Version and name : macOS Mojave version 10.14.1

**Comment by ehhc** [comment]
This is already known. See https://github.com/BoostIO/Boostnote/issues/2716 for an explanation and a workaround :)

**Comment by daiyam** [comment]
@BjarkePedersen please use `Cmd+Shift+V` for the time being when pasting an image
