### ISSUE TITLE
Keep editor mode even move to another app

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#272]
Hi, I want a function which locks the editor mode in Boostnote, because I often move to another app (e.g. chrome) on the way to using Boostnote then the mode becomes preview mode.Hence I need to change the mode every time. I feel it's troublesome. Therefore I want lock button or something.

**Comment by kazup01** [comment]
Yeah, I think so. I also feel the same troublesome thing.

**Comment by asmsuechan** [comment]
Next, we need to discuss what button and where it puts.
