### ISSUE TITLE
Hierarchical note structure

### ISSUE THREAD

**Issue by DictumMortuum** [BoostIO/Boostnote#2723]
Hello,

I don't know if this is possible with the current implementation of boostnote, however, do you think that it would be possible to create a hierarchical note structure like [cherrytree](https://cdn.portableapps.com/CherrytreePortable.png)?

Regards,
Dimitris

**Comment by ZeroX-DG** [comment]
This is a common feature request but it won't be implemented in the current version. The dev team is working on a rewrite version of Boostnote and this feature will be available there.

**Comment by kwendenarmo** [comment]
It would be good if they were not only hierarchical notes, but also hierarchical folders. It should not be complicated to implement, since the folders are virtual.

**Comment by jcotton42** [comment]
Something along the lines of OneNote's hierarchy (notebook -> section group -> section -> page -> subpages) would be great, though admittedly a bit complicated

**Comment by Kimi-Arthur** [comment]
This is a great feature I'm longing for in Boostnote. It will make the whole thing much more intuitive.

Not sure if I'm oversimplifying things too much. But from understanding basically this is a folder viewer + note viewer. Would also like to help out if anything can make this feature available sooner. Thanks!

**Comment by DictumMortuum** [comment]
I recently switched to Notable mainly because of this feature!

**Comment by hlascelles** [comment]
This is now supported it seems.

![image](https://user-images.githubusercontent.com/299102/72668537-ecd4fd00-3a1f-11ea-82a7-41e05b234693.png)

**Comment by Flexo013** [comment]
Duplicate of #125
