### ISSUE TITLE
Changing editor theme and not saving reverts to default

### ISSUE THREAD

**Issue by bytemybits** [BoostIO/Boostnote#273]
If I change the editor theme and don't save instead of automatically saving or just ignoring my change, it changes to default. However, the selected editor theme remains the one I'd chosen. Here's a nice gif to show the problem:
![boostnote](https://cloud.githubusercontent.com/assets/8046519/22698406/6401cec2-ed4c-11e6-851a-db9e221630c8.gif)

The preview theme works fine from what I was able to test.

Boostnote Version 0.8.4 (0.8.4) on macOS Sierra 10.12.3

**Comment by asmsuechan** [comment]
Hi @bytemybits, thanks for your report! We try to investigate.

**Comment by kazup01** [comment]
Hi @bytemybits san, @sosukesuzuki is fixing it! Plz wait a while.
