### ISSUE TITLE
Note directory support expand in side bar

### ISSUE THREAD

**Issue by richard-yao** [BoostIO/Boostnote#2732]
# Current behavior

Boostnoe just display my all directory in left side bar for now
![image](https://user-images.githubusercontent.com/15257771/50262485-8ceeda00-044c-11e9-9d42-7eb5146ebd03.png)

# Expected behavior

The directory can expand in side bar so that I can find the note directly instead of change every directoy to find that one

# Steps to reproduce

# Environment

- Version : 0.11.12
- OS Version and name : Windows7

**Comment by xvusrmqj** [comment]
> > may you should use global search to find it. not expand directory.
> 
> Your openion is well, but sometimes I just want to find one note with scroll in side bar, just like windows supported.

if boostnote is tree strcutured (like windows file manager, or zim wiki)， it is useful . but it is two-layer structure, so when expand it ,there will many many notes for you ,  it 's not very helpful.

**Comment by Flexo013** [comment]
Thanks for your suggestion @richard-yao!

This feature request hasn't gained any traction within the community, so I will be closing this for Boostnote Legacy. If you would still like this feature, then I recommend checking out the [Boost Note.next repository](https://github.com/BoostIO/BoostNote.next/issues).
