### ISSUE TITLE
About the preview mode ctrl +f search function

### ISSUE THREAD

**Issue by potester** [BoostIO/Boostnote#2735]
First of all, I am very grateful to the developers for their efforts. I have a confusion. In the note preview mode, there is no search function, which leads to a half-day search. Can I add a preview mode search function?

**Comment by ZeroX-DG** [comment]
Have you tried to search in the editor?

**Comment by potester** [comment]
Search is available in the editor, but the visual experience is poor and the code block is not highlighted.

**Comment by ZeroX-DG** [comment]
Looks like we gonna need some improvements on searching experience for each individual note. We have received some issues related to the poor searching experience. Unfortunately, I'm a bit busy now so maybe someone else can fix this but I'll also try to fix this issue when I have time.

**Comment by Flexo013** [comment]
Duplicate of #2625
