### ISSUE TITLE
0.11.12 can't insert pictures like 0.11.11 

### ISSUE THREAD

**Issue by iMcG33k** [BoostIO/Boostnote#2736]
# Current behavior
How to insert pictures with latest version?  

# Expected behavior
Just like 0.11.11, please give me the feature back, please..

# Steps to reproduce

1.  open some .png files with preview
2.  select one picture in the main window, press CMD + C to copy
3.  paste it in boostnote (markdown note), but it doesn't work...

if you do above steps in version 0.11.11, it will automatically generate Markdown image link like this: 
! [5c7958f8.png] (:storage/0f4cf74b-7c1f-4450-a6cf-d51465aea534/5c7958f8.png)

# Environment

- Version : 0.11.12
- OS Version and name : macOS 10.14.1 (18B75)

**Comment by yosmoc** [comment]
@iMcG33k Please enable smart paste option. More detail. https://github.com/BoostIO/Boostnote/issues/2716
