### ISSUE TITLE
Preview pane content doesn't scroll all the way down in markdown mode

### ISSUE THREAD

**Issue by 1npo** [BoostIO/Boostnote#2737]
# Current behavior

When I'm editing a large document in Markdown mode, the preview pane continues scrolling along with the edit pane -- up to a point. Once the text in the edit panel is filled up, the preview pane stops scrolling. Text added in the edit pane doesn't show up in the preview pane. It stays hidden below the bottom of the preview pane.

This screenshot is an exaggerated example -- it doesn't take this much text to cause the problem.

[screenshot 1](https://i.imgur.com/RqBQUmf.png)

[screenshot 2](https://i.imgur.com/WYv0Iyw.png)

# Expected behavior

The content in the preview pane should scroll in sync with the content in the edit pane, regardless of length.

# Steps to reproduce

1. Open a new Markdown note
2. Enable preview mode
3. Continue typing until you fill up the length of the edit pane

# Environment

- Version : 0.11.12
- OS Version and name : Windows 10

**Comment by ZeroX-DG** [comment]
Maybe the same isssue as https://github.com/BoostIO/Boostnote/issues/2636 ?

**Comment by daiyam** [comment]
@ZeroX-DG I'm not sure about that issue. But the PR #2405 fixes the issue when the cursor position isn't shown in the preview (like in `screenshot 1`).

**Comment by Flexo013** [comment]
@1npo Is this issue this present for you when using 0.11.17?

**Comment by 1npo** [comment]
@Flexo013 no, I'm not having the problem anymore in 0.11.17, but I'm running Ubuntu 18.04 on this machine now -- so I'm not sure if the problem persist on Windows.

**Comment by Flexo013** [comment]
I am not encountering this issue anymore on Windows, so it must have been fixed by some PR in the meantime. Closing this issue.
