### ISSUE TITLE
When I used code block the preview window was something wrong

### ISSUE THREAD

**Issue by sanghyukYoon** [BoostIO/Boostnote#2738]
# Current behavior

![2018-12-21 5 18 56](https://user-images.githubusercontent.com/16624147/50332937-066af300-0547-11e9-9e39-8e5b932cf513.png)

# Expected behavior

# Steps to reproduce

1.  use code block
2.  check the preview window

# Environment

- Version : 0.11.11
- OS Version and name : MAC OS HIGH SIERRA 10.13.6(17G3025)

**Comment by ZeroX-DG** [comment]
0This bug has been fixed in 0.11.12 (latest release). Please update Boostnote
