### ISSUE TITLE
Rename Folder font in Dark theme is black and should be white

### ISSUE THREAD

**Issue by bytemybits** [BoostIO/Boostnote#274]
When renaming a folder in the Dark theme the font is black and it should be white, as other parts of the app are. (more of an enhancement than anything else)
<img width="1133" alt="screen shot 2017-02-07 at 5 18 52 pm" src="https://cloud.githubusercontent.com/assets/8046519/22702841/f2d5102a-ed59-11e6-8522-49188ed5851f.png">

Boostnote Version 0.8.4 (0.8.4) on macOS Sierra 10.12.3

**Comment by asmsuechan** [comment]
Hi @bytemybits, thanks for your report! I confirmed this issue. We try to fix it!

**Comment by kazup01** [comment]
Hi @bytemybits san, @ericsolomon san fixed it, and we can use it after  v0.8.6.👏
Thank you for your reporting!
