### ISSUE TITLE
HTML Markdown Mix is not well together as it used to be

### ISSUE THREAD

**Issue by empeje** [BoostIO/Boostnote#2740]
# Current behavior

I want to reproduce something nice like this [one](https://github.com/fgeller/kt/blob/master/README.md) (don't be tricked, below are images)

* before

<img width="510" alt="screen shot 2018-12-22 at 14 22 46" src="https://user-images.githubusercontent.com/11813607/50371838-1ccf8800-05f5-11e9-9bfd-e7df15e400ba.png">

* after

<img width="591" alt="screen shot 2018-12-22 at 14 22 52" src="https://user-images.githubusercontent.com/11813607/50371840-1f31e200-05f5-11e9-9941-a0becce17b9d.png">

That is possible using this

```html
<details><summary>What I want to do</summary>

This is markdown content

</details>

It is so useful, because if I have long list of todo, I can collaps and expand easily using this. I would love if it possible in Boostnote and I believe others will have the advantages as well.

```

# Expected behavior

Able to collaps and expand markdown using `details` html tag.

# Steps to reproduce

1. Create a new note
2. Copy this example

```html
<details><summary>What I want to do</summary>

- [x] Dinner
- [ ] Sleeping

</details>
```

3. You can't collaps and expand markdown.

# Environment

- Version : 0.11.12
- OS Version and name : MacOSX High Sierra

**Comment by ZeroX-DG** [comment]
Works fine for me on Linux
![asdasd](https://user-images.githubusercontent.com/12984316/50384854-8d61cc00-06fd-11e9-8507-25211ced2b3e.gif)

**Comment by empeje** [comment]
Why not work in High Sierra 🤔

**Comment by rklasen** [comment]
Only works if dangerous html elements are not sanitized (tested in Ubuntu 18.04, Boostnote 0.11.12).

Maybe this setting was reset to default (only allow safe html elements)?

**Comment by empeje** [comment]
Oh right @rklasen, tested as well in my case. Should I add this kind of information to readme/docs?

**Comment by ZeroX-DG** [comment]
We currently don't have a doc like that. I think this is a good chance to add a FAQ.md file. What do you think @Rokt33r

**Comment by Rokt33r** [comment]
@ZeroX-DG Sounds nice. 👍

**Comment by ZeroX-DG** [comment]
@empeje we have the permission can you create a FAQ.md file and add this to it?

**Comment by empeje** [comment]
sure, I'll do it.

**Comment by empeje** [comment]
https://github.com/BoostIO/Boostnote/pull/2755

cc: @ZeroX-DG and @Rokt33r
