### ISSUE TITLE
Videos embedded in this website(bilibili) cannot be played

### ISSUE THREAD

**Issue by tanshanli** [BoostIO/Boostnote#2750]
# Current behavior
The code is as follows:

```
<iframe src="http://player.bilibili.com/player.html?aid=38882703&cid=68339355&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" width="500px;" height="500px" allowfullscreen="true"></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/9t-GF_f7eIY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Display failure in bootsnote**
ps: Console has no information output

![bootsnoteview.png](http://oss.z13qu.com/issue/bootsnoteview.png)

# Expected behavior

**Display normal in index.html**
![ok.png](http://oss.z13qu.com/issue/ok.png)

# Environment

- Version :Boostnote 0.11.12
- OS Version and name : win10  1803

**Comment by ZeroX-DG** [comment]
Please change your setting in Interface tab. In preview section change the Sanitization to Allow dangerous HTML tag.
