### ISSUE TITLE
Where can I download app? 

### ISSUE THREAD

**Issue by sowee121** [BoostIO/Boostnote#2754]
Where can I download app? All I saw was win,mac,linux.
I would like to download ios or Android app.

**Comment by Awalvie** [comment]
[https://github.com/BoostIO/boostnote-mobile](url)
As noted here the app is currently unavailable.

**Comment by ZeroX-DG** [comment]
The team will work on the mobile app in the future (after we finish the rewrite version of Boostnote) but we don't have the exact schedule for that.

**Comment by daiyam** [comment]
@sowee121 you can find the releases at [BoostIO/boost-releases](https://github.com/BoostIO/boost-releases/releases)
