### ISSUE TITLE
Maximize window behavior

### ISSUE THREAD

**Issue by Strongaloff** [BoostIO/Boostnote#2757]
# Current behavior

I don't know if it is actually a bug or not, but maximizing the window is not remembered after closing and opening the app again.

So this:

![annotation 2018-12-27 152210](https://user-images.githubusercontent.com/44774998/50481635-533d4680-09eb-11e9-82f1-676c16a9a3a2.jpg)

transforms into this after reopening:

![annotation 2018-12-27 152253](https://user-images.githubusercontent.com/44774998/50481653-67814380-09eb-11e9-9352-c176c9ecf360.jpg)

# Expected behavior

Application being capable of remembering the previous instance, more specifically the window being maximized.

# Steps to reproduce

1. Open Boostnote
2. Maximize the window
3. Close it
4. Open it again

# Environment

- Version : Boostnote 0.11.12
- OS Version and name : Microsoft Windows 10 Pro

**Comment by KuangLei** [comment]
Duplicated. #2708
