### ISSUE TITLE
An option to allow text wrapping for code elements

### ISSUE THREAD

**Issue by jsnjack** [BoostIO/Boostnote#276]
Please consider adding an option for text wrapping inside the code elements. I think it will make, for example, long commands more readable and copyable. I think it might be done by adding following styles:
```
word-wrap: break-word;
white-space: pre-wrap;
```

**Comment by kazup01** [comment]
refs: #570

**Comment by neouyghur** [comment]
with custom CSS, according to @jsnjack answer, I solved this problem.

```
code{
  word-wrap: break-word;
white-space: pre-wrap;
}
```
