### ISSUE TITLE
# = Massive Font Size and Bold in Note Preview

### ISSUE THREAD

**Issue by HatterTheMadd** [BoostIO/Boostnote#2760]
# Current behavior
"#" bolds and increases font size in note 'preview' -- and there is no setting I can see to remove this.

# Expected behavior
There should be a setting to turn off the #,*,-, and whatever other special syntax is out there for boostnote. I don't think this language specific as any language I turn it to this happens. 

# Steps to reproduce
1. Type a #
2.  Type anything after it
3.  Text is now massive and bold in preview

# Environment
- Version : Current version as of Dec 27th.
- OS Version and name : Win10

**Comment by HatterTheMadd** [comment]
![image](https://user-images.githubusercontent.com/25492218/50498112-dd95a280-0a0b-11e9-94d9-3f42e6738936.png)

**Comment by HatterTheMadd** [comment]
You mean this? I saw that, how do you change what the # does here?
![image](https://user-images.githubusercontent.com/25492218/50500523-e5f7d880-0a1f-11e9-8554-3f4ba54186ad.png)

**Comment by HatterTheMadd** [comment]
Ok, this looks like it's just *literally* editing the css on your notes. I don't want to have to do this. What if I actually want `<h1>` to show up at some point. I just want  to remove whatever tie # has to `<h1>`. There's no `# =/= <h1>` that I can tell.

![image](https://user-images.githubusercontent.com/25492218/50500871-1c365780-0a22-11e9-8618-5bb5246b37d4.png)

**Comment by ZeroX-DG** [comment]
Well, `#<space>text = <h1>text</h1>` is the markdown syntax and there's no way you can change it. If you remove the space then it will become the normal text `#text`. You can see the markdown syntax here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers

**Comment by HatterTheMadd** [comment]
man... i thought I finally found a note taking program I could stick with.. Got my hopes up this time. # is an almost universal key for 'note' in many languages. A ton of what I would need this for I need a space between the # and the text (as putting text next to it will auto-pull for other snippets I would be working on or be a key for engineers to #remove '#' to use this as a piece of code. It's pretty obvious if it is a comment or a piece of code, but I wouldn't be surprised if someone did this and completely shut down one of our prod servers. Since this would be distributed to different engineer teams and we all use the same format. I don't think this'll work. So I guess I'll either try to change this myself or move back to npp/atom :(

**Comment by ZeroX-DG** [comment]
@HatterTheMadd You can add the space between it. You just need to wrap it inside a codeblock like this.

![image](https://user-images.githubusercontent.com/12984316/50502008-a0262900-0a8e-11e9-880b-c6e1d1410bb9.png)

It will generate this:
```
# text
```

**Comment by daiyam** [comment]
@HatterTheMadd it seems that you should create snippet notes instead of markdown notes (which use the [markdown language](https://guides.github.com/features/mastering-markdown/) where `#`, `*`, `-` are keywords)

In the preferences, you can change the default type of the note (ask, markdown or snippet) and the default language of a snippet note.

**Comment by MiloTodt** [comment]
There are many ways to escape Markdown inside of Boostnote, here are four options:

![image](https://user-images.githubusercontent.com/21070668/51075193-549e7e00-163d-11e9-95b2-bb1290870a81.png)

The only way otherwise to stop Boostnote from rendering Markdown would be to disable it entirely, which seems counter productive to the point of the app.

**Comment by Flexo013** [comment]
If you don't like the # being part of the syntax for headers, then simply look for a note taking app that isn't focused on Markdown.
