### ISSUE TITLE
Export as PDF code block display bug

### ISSUE THREAD

**Issue by tangjiabing** [BoostIO/Boostnote#2765]
Boostnote 0.11.12 PC.

After exporting the PDF file, if the content of markdown \`\`\`  fills two pages, the following problems will occur:  \`\`\`  the content number is not aligned, the line content at the end of the first page, and the beginning of the second page, only show half.

![qq 20181229151455](https://user-images.githubusercontent.com/8198969/50534786-de017b00-0b7c-11e9-9b37-a694805134b7.png)

@yosmoc

**Comment by tangjiabing** [comment]
用中文说一下，导出PDF文件后，如果 \`\`\` 包裹的内容单独占两页时，会出现以下问题：\`\`\` 内容的序号未对齐，第一页末尾和第二页开头的内容只显示为一半，完整内容被割裂开了。

**Comment by tangjiabing** [comment]
Are you sure it's a bug? @ZeroX-DG

**Comment by Flexo013** [comment]
Reproducible on Windows 10 with 0.11.17:

Exporting a large code block to PDF causes misalignment if the code block gets split over 2 pages *and* if at least one of the lines of the code is longer than the page width (line 8 in the example).

![image](https://user-images.githubusercontent.com/4507015/61406300-dbc5fa80-a8db-11e9-8af4-536fc0e942f9.png)

**Comment by Flexo013** [comment]
Related to: https://github.com/BoostIO/Boostnote/issues/2984
