### ISSUE TITLE
Mark of end syntax highlight does not work properly

### ISSUE THREAD

**Issue by zzxxhhzxh** [BoostIO/Boostnote#2767]
# Current behavior
In 0.11.11 and 0.11.12
Mark of end syntax highlight (```) does not work properly.
And some parts of code do not show correct color.

# Expected behavior
They work all good in 0.11.10

# Environment
- Version : 0.11.12
- OS Version and name : Win10 pro 64bit Eng

![new bitmap image](https://user-images.githubusercontent.com/42593813/50550259-ace38200-0c32-11e9-9702-27bd9649db25.jpg)

**Comment by ZeroX-DG** [comment]
Thank you for reporting this issue. I think you should follow this issue here because it describes the issue better: https://github.com/BoostIO/Boostnote/issues/2773

**Comment by zzxxhhzxh** [comment]
Sorry about that, my main problem is the end mark of code block (```) does not work for "End code block" in edit mode, but in preview mode, everything looks good. This happens in 0.11.11 and 0.11.12 only. I am using English windows 10 1809 and add "Simplified Chinese language package".
