### ISSUE TITLE
How to recover deleted folder & notes from my storage folder 

### ISSUE THREAD

**Issue by yappps** [BoostIO/Boostnote#2775]
# How to recover deleted notes from my storage folder 

Deleted notes in My Storage folder via here and couldnt recover the deleted note in the Trash folder

![image](https://user-images.githubusercontent.com/36840989/50623876-27731100-0f55-11e9-824c-e9948819bf8d.png)

# Environment

- Boostnote Version : Boostnote 0.11.8
- OS Version and name : macOS high Sierra v 10.13.6

**Comment by KuangLei** [comment]
I got this when trying to delete a folder from the main UI. It seems that deleting a folder **'can not be undone'**.
![screenshot_20190103_155823](https://user-images.githubusercontent.com/12217600/50647463-84c88b80-0f70-11e9-8b95-c0dd4ff0daf6.png)
