### ISSUE TITLE
Katex functions not supported

### ISSUE THREAD

**Issue by rahulpathakgit** [BoostIO/Boostnote#2777]
Boostnote -  11.12
OS: Ubuntu 16.04

There are multiple Katex functions which are not supported by Boostnote.. For instance 

$$\real$$, $$\reals$$ nothing works.
Error: KaTeX parse error: Expected 'EOF', got '\reals' at position 1: \̲r̲e̲a̲l̲s̲

![screenshot from 2019-01-04 14-29-34](https://user-images.githubusercontent.com/10892516/50680592-3bd70c80-102e-11e9-895b-3588541c8403.png)

**Comment by Flexo013** [comment]
Can be closed due to #2998.
