### ISSUE TITLE
Double dollar  sign

### ISSUE THREAD

**Issue by hampusfredriksson** [BoostIO/Boostnote#2778]
# Current behavior

Whenever I'm typing $ it prints $$, 

![dollarsign](https://user-images.githubusercontent.com/42962227/50724554-c2075780-10ef-11e9-9932-82611badc46a.gif)

# Expected behavior
Single $ sign

# Steps to reproduce

1. Type dollar sign :) 
2. 
3. 

# Environment

- Version : Latest 0.11.12
- OS Version and name : macOS 10.14.2

**Comment by KuangLei** [comment]
A pair of \$ is to add a LaTeX math expression to your markdown, so Boostnote handles \$ just like \` and \*.  
To understand how \$ works, you can try to type `$v=\frac{\Delta{s}}{\Delta{t}}$` in Boostnote.  
Thanks.

**Comment by ZeroX-DG** [comment]
This bug has been fixed in this PR: https://github.com/BoostIO/Boostnote/pull/2586. You can customize this behavior in the next version.
