### ISSUE TITLE
Behavior of "Focus Search" menu

### ISSUE THREAD

**Issue by ymm1x** [BoostIO/Boostnote#2780]
# Current behavior

The "Focus Search" menu behaves as a toggle. If the search box is already in focus, it will be blurred.

# Expected behavior

Do not blur the search box when it is focused. I think that the menu naming of "Focus Search" will become more natural behavior by always focusing.

NOTE: Also the behavior of  `Files > Focus Note` menu is not a toggle.

# Steps to reproduce

1. Focus the search box.
2. Click main menu of `View > Focus Search`.
3. It will be blurred.

# Environment

- Version : 0.11.12
- OS Version and name : OS X 0.11.6

**Comment by Flexo013** [comment]
I can't reproduce this in 0.11.17 on Windows 10.

@ymm1x Is this issue still present for you (on OSX)?

**Comment by ymm1x** [comment]
@Flexo013 
Yes I am using MacOS.  After you said that, it certainly looks like that on version 0.12.1.
Thank you for your confirmation. 🙇‍
