### ISSUE TITLE
[Feature Requested] Can Table of Content (TOC) update automatically?

### ISSUE THREAD

**Issue by kyan001** [BoostIO/Boostnote#2782]
# Current behavior
Every time I changed my headers, I need update Table of Contents manually by pressing `Ctrl + Shift + T`

# Expected behavior
After the TOC is generated, I'd like to see it update itself. Because I have no reason to keep an outdated TOC which is inconsistent with my contents.

If the TOC can updated itself every time I changed a header, that would be cool. Or it can updated every X mins or every time I lose focus on that note.

# Environment

- Version : 0.11.12
- OS Version and name : macOS Mojave 10.14.12

**Comment by Flexo013** [comment]
In 0.14.0 the TOC will update automatically.
