### ISSUE TITLE
App icon looks bad on Windows 10 taskbar

### ISSUE THREAD

**Issue by delk0** [BoostIO/Boostnote#279]
It's a small glitch but seems like the icon on my windows 10 taskbar doesn't have proper resolution. Does this happen to anyone else?

![lowresicon](https://cloud.githubusercontent.com/assets/19197011/22810659/7af216a6-ef3a-11e6-9bae-05414192c3aa.PNG)

**Comment by twhiting** [comment]
+1

**Comment by kohei-takata** [comment]
I'll fix it.
Thanks!

**Comment by agenestar** [comment]
Still have the same issue on Windows 10 with the version 0.8.7.

![image](https://cloud.githubusercontent.com/assets/10512395/25121456/08f8d752-2422-11e7-8eef-0664fa3ae92b.png)

**Comment by nhat-thien** [comment]
![](https://i.imgur.com/noAMonO.png)

Still have the same thing in Boostnote 0.11.11
