### ISSUE TITLE
While using dark themes changing panel sizes results in a flash of white

### ISSUE THREAD

**Issue by MiloTodt** [BoostIO/Boostnote#2790]
# Current behavior

Quickly changing panel sizes results in a flash of the white undercolor when using a dark theme.

# Expected behavior

The colour under the panel should be the same or more closely match the selected theme so as to be less noticeable. 

# Steps to reproduce

![giphy.gif](https://media.giphy.com/media/9xeB7UAswMEOezn8FJ/giphy.gif)

# Environment

- Version : 3.0.8
- Windows 10

**Comment by ZeroX-DG** [comment]
Stop breaking the app, normal users don't do that, why can't you just use it like a normal user? :smile: Just kidding, thanks for reporting, I'll fix this bug asap.

**Comment by Rokt33r** [comment]
Fixed by #2791
