### ISSUE TITLE
"Exporting as markdown" for a note with a broken image results in an exception

### ISSUE THREAD

**Issue by MiloTodt** [BoostIO/Boostnote#2793]
# Current behaviour
![image](https://user-images.githubusercontent.com/21070668/51062035-350a4580-15aa-11e9-9e3e-809e39aa48d8.png)

the folder for attachments is created with a 0bit file in it, the .md is not saved.

# Expected behavior

As it is valid markdown syntax the file should save with it instead of throwing an exception and not saving. User's responsibility to provide good links of their own content.

# Steps to reproduce

1. Create a new note and paste this in:
```
![This file doesn't actually exist](:storage\Bad link on puropse)
```
2. File->export as-> markdown

# Environment

- Version : 3.0.8, master branch.
- Windows 10

**Comment by Flexo013** [comment]
This will most likely be resolved during the fixing of #3262, as that also pertains to how images are handled.

If this issue does pop-up again after that has been solved, then feel free to post here again (or recreate the issue).
