### ISSUE TITLE
Unable to handle notes on removable media ("No storage mount.")

### ISSUE THREAD

**Issue by paolostefan** [BoostIO/Boostnote#2799]
# Current behavior

When adding a _Storage location_ from a removable media, it works **only the first time**. 

When you quit the app, eject the media, and then come back to the app, the error "No storage mount." appears.

![schermata 2019-01-13 alle 12 05 31](https://user-images.githubusercontent.com/1904907/51084727-27ca9380-172f-11e9-992e-85b6f2f804b1.png)

Now, it's not possible to see any saved note, nor take any new note.
Reinserting the media, uninstalling and reinstalling the app, and/or adding other storage locations does not bring the app back to a working state.

# Expected behavior

The storage locations which aren't found should be simply marked as "Not found" until the removable media are reinserted. 

Other (found) storage locations should show up as normal. 

The app should then run normally.

# Steps to reproduce

1. Add a storage location choosing a folder on a removable media (e.g. a pendrive).
2. Quit BoostNote.
3. Eject the removable media.
4. Run BoostNote again.
5. All the storages are now gone, and you're welcomed from the error message "No storage mount.". Undercover, this is what dev tools report:
![devtools](https://user-images.githubusercontent.com/1904907/51084762-8bed5780-172f-11e9-8634-fbae0f4ac921.png)
6. The app becomes unusable.

## Steps to temporarily fix the issue (non-tech)

1. Download and run [AppCleaner](https://freemacsoft.net/appcleaner/) (disclaimer: I'm not sponsoring it, but it just works)
2. Drag and drop BoostNote app icon on AppCleaner window
3. Untick all the locations except **~/Library/Application Support/Boostnote**
![schermata 2019-01-13 alle 12 11 50](https://user-images.githubusercontent.com/1904907/51084777-cd7e0280-172f-11e9-82a4-13f0cb82ec5a.png)

4. Click the "Remove" button on the bottom right
5. Run BoostNote again but avoid adding storage locations from removable media :wink:

## To temporarily fix the issue from bash

Run the following command:

    rm ~/Library/Application\ Support/Boostnote/Local\ Storage/leveldb/*

# Environment

- Version : 0.11.12
- OS Version and name : MacOS X 10.11.6 El Capitan

**Comment by MiloTodt** [comment]
Thank you for including the Developer console stack trace and a detailed report, that made it much easier to track down what was causing it. 

Issue addressed here: https://github.com/BoostIO/Boostnote/pull/2801

Under current fix the app will no longer crash and become inaccessible if initializing with a missing usb drive.

Under this fix, if you start the app with your USB drive removed it will not show up on the sidebar at all. You will need to restart Boostnote with the drive inserted and then it'll show up just fine and be accessible as before.
