### ISSUE TITLE
Clicking "x" (close) doesn't really close the app on Windows 10

### ISSUE THREAD

**Issue by delk0** [BoostIO/Boostnote#280]
I have noticed that clicking the x button doesn't close the app but instead it just hides it minimizing it to the taskbar. I have to go to the menu, click "Boostone" the hit "close" to really close it. I will look more into this.

**Comment by VoLuong** [comment]
@delk0  It must be a feature like Skype app, not a bug.

**Comment by kazup01** [comment]
Does it still occur?
