### ISSUE TITLE
Boostnote 0.11.12 is not responding in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by itouri** [BoostIO/Boostnote#2807]
# Current behavior

I can't control except preference.
But I can't save the changes.

![screenshot from 2019-01-16 01-20-15](https://user-images.githubusercontent.com/10162288/51194029-907f5f00-192d-11e9-8bf5-b33f84f05dea.png)

And, I already read the issue #2167.
This issue is very similar.
But suddenly closed without comments.

- Version : 11.12
- OS Version and name ubuntu 18.04 LTS

**Comment by MiloTodt** [comment]
https://askubuntu.com/questions/842409/what-is-run-user-1000-gvfs

To help narrow this down, have you manually set a storage location on a device such as a phone in direct file access mode?

**Comment by Flexo013** [comment]
@itouri Are you still experiencing this issue?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
