### ISSUE TITLE
Add ability to toggle the menu bar

### ISSUE THREAD

**Issue by delk0** [BoostIO/Boostnote#281]
The expected behaviour on Windows (and linux, I guess) is that when you press the alt key it allows you to toggle the menu bar.
Or, also would be cool to have an option like some others apps do such as Atom for example where there's an option to hide it on the "View" section which this app also has. I think it would make Boostnote look a lot more cleaner.

**Comment by kazup01** [comment]
Thank you for your feedback! Along with improving the current design, I will consider it.

**Comment by klauscfhq** [comment]
Hi! 
I have created the #339 PR probably solving this issue as well as issue #169 .
I hope that it can be actually of some help!
Love the project 🎉

**Comment by kazup01** [comment]
Thank you for your cooperation @klauscfhq san! Your work is great🎉 We will update it sometime soon!

**Comment by Right2Drive** [comment]
What is the status of this? It doesn't look like the PR was ever merged?

**Comment by KuangLei** [comment]
@Right2Drive 
>  It doesn't look like the PR was ever merged?

Yes, it's not merged now, but the Boostnote developers will add the feature sooner or later.  

If you want to hide the menu bar, 

>  You can add the feature to your local build just by switching the `autoHideMenuBar: showMenu` property to `autoHideMenuBar: true`, which is located inside the `resources/app/lib/main-window.js` file.

Thanks.
