### ISSUE TITLE
Reloading Boostnote via the CLI

### ISSUE THREAD

**Issue by dbuskariol** [BoostIO/Boostnote#2821]
Is it possible to perform the reload of Boostnote (cmd+r) via the CLI?

**Comment by dbuskariol** [comment]
I've just realised I can use Applescript in my bash script in lieu of a native solution:

```
osascript -e 'activate application "Boostnote"
tell application "System Events" to key code 15 using {command down}'
```

**Comment by MiloTodt** [comment]
It seems you've found the solution on your own. May I ask, what is the usecase in which you need to do this?

**Comment by dbuskariol** [comment]
@MiloTodt I’ve created a command line utility that I use with Alfred to automatically create notes based on some input variables. 

Once the note is created, Boostnote needs to be reloaded for the note to show. At the end of my script I wanted to open and reload Boostnote automatically so I didn’t have to manually do it –which is what I needed this for 😁
