### ISSUE TITLE
a unfriendly user interaction at creating new note

### ISSUE THREAD

**Issue by hevi1991** [BoostIO/Boostnote#2823]
# Current behavior
The opening folder would change, when I created a new note.

# Expected behavior
The opening folder what I'm opening should not be change, when I create a new note.

# Steps to reproduce

1. open a folder
![](https://ws1.sinaimg.cn/large/006tNc79gy1fzf6eh9fu8j31d90u0qo2.jpg)
2. create a new note
![](https://ws4.sinaimg.cn/large/006tNc79gy1fzf6fa1lwmj31d90u0tdm.jpg)
3. It would return to **All Notes**
![](https://ws4.sinaimg.cn/large/006tNc79gy1fzf6icft9cj31d90u0aj1.jpg)

# Environment

- Version : 0.11.12
- OS Version and name : MacOS 10.14

**Comment by pcoridan** [comment]
@ZeroX-DG I don think this is an improvement request but more a bug, Two updates ago this was not the behavior, for a a few years before that, we had when creating a new note.  It would originally just open a new note and STAY in the folder it was created in.

**Comment by neosix** [comment]
This is super annoying. We should mark this as a bug.

**Comment by Flexo013** [comment]
This bug is no longer present.
