### ISSUE TITLE
Application is showed at unselectable display field

### ISSUE THREAD

**Issue by c13proto** [BoostIO/Boostnote#2841]
# Current behavior

I usually use  two displays and shows this app at sub monitor's field.
After close this app at sub monitor's field then disconnect main display( switch main display to previous sub display) and start app, app's window is showed at unselectable area.
So, I cannot do anything at that situation.

# Expected behavior

Application window shows at center of display area.

# Steps to reproduce

1. connect more than two display and set extended screen mode.
2. application close at sub screen area.
3. disconnect main screen's display and start application

# Environment

- Version :Boostnote 0.11.12
- OS Version and name :Windows 7 64bit pro, 
- gpu : Intel HD graphic

**Comment by ZeroX-DG** [comment]
Is it a duplicate of https://github.com/BoostIO/Boostnote/issues/2803 ?

**Comment by c13proto** [comment]
oh,looks so. sorry
