### ISSUE TITLE
Pasted Images No Longer Work

### ISSUE THREAD

**Issue by mjtlee** [BoostIO/Boostnote#2845]
# Current behavior
Pasting photos from my clipboard results in this error:
![image](https://user-images.githubusercontent.com/42304224/51848833-97b64d80-22db-11e9-8d59-c64bd16b5000.png)

Additionally, I have found out that in some of my previous notes, the photos I pasted in their are also displaying the same issue.
![image](https://user-images.githubusercontent.com/42304224/51849108-3b9ff900-22dc-11e9-9c93-e56a66c77bda.png)

I have investigated in my folders and found that the pictures are still in the stated path written in Boostnote.

Edit 1:
Curiously, I do **not** have this issue on Ubuntu 18.10. All of the pictures are present and working as usual. Could this be a Windows bug?

# Environment

- Version : Boostnote 0.11.13
- OS Version and name : Windows 10

**Comment by dkulczycki** [comment]
I have the same, Boostnote accepts only the splash mark in the path
![53d8e1b2.png](:storage**/**787799f0-f28e-4a2c-95e0-bde7fc6cdf86**/**53d8e1b2.png)

Additionally, ctrl + v (and shift + ctrl + v) does not work 


- Boostnote 0.11.13 
- Windows 10

**Comment by ZeroX-DG** [comment]
Thank you for reporting, we are discussing this issue here: https://github.com/BoostIO/Boostnote/issues/2834. Please follow us there.
