### ISSUE TITLE
Softbreak handling is not CommonMark compliant by default

### ISSUE THREAD

**Issue by anothernode** [BoostIO/Boostnote#2849]
# Current behavior

Boostnote inserts a line break into the rendered text if there's a line break in the Markdown code, even when the line break is not preceded by two spaces or a backslash:

![linebreak](https://user-images.githubusercontent.com/3286144/51975883-a8092c80-2483-11e9-8f74-b14dfa6a50c1.png)

This means that it's impossible to format your text nicely in Markdown with hard line breaks without at the same time inserting hard line breaks into the rendered text which completely messes up the rendered paragraph. As a result, you can only have nicely formatted paragraphs either in Markdown or in the rendered output, but not in both.

# Expected behavior

A line break in the Markdown code that is __not__ preceded by two spaces or a backslash should be rendered as a _softbreak_ [according to the CommonMark specification](https://spec.commonmark.org/0.28/#softbreak) which basically means that it should __not__ insert a line break into the rendered text.

# Environment

- Version: 0.11.13
- OS Version and name: macOS Mojave 10.14.3

**Comment by anothernode** [comment]
I found the _Render newlines in Markdown paragraphs as <br>_ option in the _Interface_ preferences. Activating it makes the rendering CommonMark compliant. That's fine for me.

I'll still leave this issue open as I think the CommonMark compliant behavior should be the default.

**Comment by ZeroX-DG** [comment]
@Rokt33r I think leaving CommonMark compliant as default seem reasonable but could potentially confuse current users. What do you think that we should do?

**Comment by Rokt33r** [comment]
@ZeroX-DG I think we don't have to change our default behavior. But it would be better to add the description about it to FAQ.md. 😄
