### ISSUE TITLE
Change icon color in macOS menu bar

### ISSUE THREAD

**Issue by igoradamenko** [BoostIO/Boostnote#285]
Hey guys!

Thanks for Boostnote, it's great. Is it possible (or is it in a roadmap) to change color of app icon in macOS menu bar? It's hellishly bright. Check this out:

<img width="479" alt="screen shot 2017-02-11 at 15 42 19" src="https://cloud.githubusercontent.com/assets/6537798/22853819/b78ae9da-f070-11e6-9517-129c51de67fb.png">

It would be great to get a monochrome icon!

**Comment by asmsuechan** [comment]
Hi @igoradamenko, Thanks for your feedback! We'll try to confirm the icon.
