### ISSUE TITLE
Inserted images are not displayed

### ISSUE THREAD

**Issue by dredav** [BoostIO/Boostnote#2850]
# Current behavior
I want to add some images to my note. So I'm drag & drop the file to boostnote and get the following syntax:
`![2019-01-30 11_42_07-Window.png](:storage\c2ab1458-717d-47f1-b74d-f292769a5e44\8751afbf.png)`

Screenshot:
![2019-01-30 11_47_05-boostnote](https://user-images.githubusercontent.com/731073/51976404-dcc9b380-2484-11e9-8c0d-61ca36f78252.png)

Developer console:
![2019-01-30 11_51_41-boostnote](https://user-images.githubusercontent.com/731073/51976622-72654300-2485-11e9-9782-33830d453786.png)

Attachments folder:
![2019-01-30 11_47_33-window](https://user-images.githubusercontent.com/731073/51976405-dd624a00-2484-11e9-9361-6b8fe2160641.png)

# Expected behavior

A note with the inserted image

# Steps to reproduce

1. Create new note (or use an existing one)
2. Drag one image into the note

# Environment

- Version : 0.11.13
- OS Version and name : Windows 10 Version 1803

**Comment by dredav** [comment]
Using the element inspector the html for the image is
```html
<p data-line="36"><img src="file:///C:\Users\dd\OneDrive\Boostnote\attachments\f21e142b-1623-44c8-a059-ee54ed6b8d9d%5Ca3f6ec82.png" alt="Konzept.png"></p>
```

and should be

```html
<p data-line="36"><img src="file:///C:\Users\dd\OneDrive\Boostnote\attachments\f21e142b-1623-44c8-a059-ee54ed6b8d9d\a3f6ec82.png" alt="Konzept.png"></p>
```

**Comment by claudiospizzi** [comment]
Hi

I can second that, same issue on my system (Windows 10 1809, Boostnote 0.11.13).

Regards
Claudio

**Comment by Devsper** [comment]
Hello, 

I think there's a fix coming up soon for this problem, more info in the links. 

[issue#2834](https://github.com/BoostIO/Boostnote/issues/2834)
[pull#2848](https://github.com/BoostIO/Boostnote/pull/2848)

**Comment by Dhruvjit** [comment]
I just found a simple workaround for this bug: 

When adding or dragging image into boostnote, you will see the link getting generated like this `![2019-01-30 11_42_07-Window.png](:storage\c2ab1458-717d-47f1-b74d-f292769a5e44\8751afbf.png)` 

if you change the all the backward slashes to forward it will work like normal. in the versions before all the slashes where forward by default, but it seems to be a bug in this version that by default all slashes in the image path are backwards.

so change your path slashes to `![2019-01-30 11_42_07-Window.png](:storage/c2ab1458-717d-47f1-b74d-f292769a5e44/8751afbf.png)`

now images should be displayed and also correctly getting saved in your attachment folder

cheers!

**Comment by Rokt33r** [comment]
We will fix this bug in this week. Hang on a little bit more. 😭 😭 😭

**Comment by Rokt33r** [comment]
I'll close this issue because the bug has been reported already.

**Comment by marcofavale** [comment]
I have this issue still present

**Comment by dredav** [comment]
> I have this issue still present

What version of boostnote are you using? You need to update manually to version 0.11.15 to get this bugfix.

**Comment by marcofavale** [comment]
I'm using version 0.11.15 on ubuntu 18.04

![immagine](https://user-images.githubusercontent.com/7520748/55146491-f9146480-5144-11e9-959e-cd4c11a52773.png)

![immagine](https://user-images.githubusercontent.com/7520748/55146441-e13ce080-5144-11e9-9958-6c4bc5fc1607.png)

**Comment by xkLander** [comment]
Getting the issue on this version.
![image](https://user-images.githubusercontent.com/24826344/99195759-0baf3780-2788-11eb-9c88-fe7b04caf569.png)

**Comment by Flexo013** [comment]
@xkLander Could you update to 0.16.1 and see if the issue still persists? (Also double check is the attached file actually exists within the path.)

**Comment by xkLander** [comment]
Apparently it was due to some attachments missing. However, it is still an issue since I imported from the legacy boost note, and I would say that like half of the attachments have been carried to the new boost note.

**Comment by Flexo013** [comment]
Yeah, that definitely sounds like a problem. Could you add info about it on this issue: https://github.com/BoostIO/BoostNote.next/issues/697

Then we can work on a solution over there. :)
