### ISSUE TITLE
Creating new document swithes folders to "All Notes" view.

### ISSUE THREAD

**Issue by jlwestsr** [BoostIO/Boostnote#2851]
# Current behavior

When creating a new document in a specified folder the left view is switched to "All Notes". 

# Expected behavior

When creating a new document in a specific folder the left view should stay in the selected folder and not switch to "All Notes". 

# Steps to reproduce

1. Select any folder in the left view other than "All Notes".  
2. Create either a new MD or Script file
3. View switches to "All Notes" 

# Environment

- Version : Boostnote v0.11.13
- OS Version and name : macOS Mojave (v10.14.3)

NOTE: My instance of Boostnote is setup with 3 different storage areas.

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2823
