### ISSUE TITLE
Attached image files grow in size and get corrupted meta info

### ISSUE THREAD

**Issue by Diomas** [BoostIO/Boostnote#2858]
# Current behavior

When you drag an image file into a note, boostnote creates a new file in `{storage_folder}\attachments\{note_id}\{some_hash}.jpg` and insert a link to it. The problem is that new file size appears few times bigger than original one and its image metadata is corrupted (or deleted):

![2019-01-31_18-26-15](https://user-images.githubusercontent.com/856038/52066410-8befb300-2589-11e9-8f82-246bf650c156.gif)

Original file is **1.05 MB** and has some usual image meta info:
![image](https://user-images.githubusercontent.com/856038/52066224-2d2a3980-2589-11e9-9e6c-1f6134f1cd11.png)

Attached file is **9.13 MB** and all meta is missed:
![image](https://user-images.githubusercontent.com/856038/52066292-4cc16200-2589-11e9-9aca-05b3ca6d450c.png)
More over some programs like embedded window image viewer even don't recognize this file as an image.

# Expected behavior

When I attach a file I expect it to be untouched (same file size, same meta info etc).

# Steps to reproduce

1. Drag'n'drop a JPG file into a note
2. Compare attached file to original one

# Environment

- Version : 0.11.13
- OS Version and name : Windows 10

**Comment by Diomas** [comment]
Update: attached PNG images don't grow in their file size (the size becomes even slightly smaller), but they do loose all image metadata as JPG images do

**Comment by MiloTodt** [comment]
Issue looks to be related to lib/dataApi/attachmentManagement.js

In the function handeAttachmentDrop:
![image](https://user-images.githubusercontent.com/21070668/54382633-a3709000-464d-11e9-8cfd-68a375c4912e.png)

A call to fixRotate is made

![image](https://user-images.githubusercontent.com/21070668/54382556-7b812c80-464d-11e9-8943-061449a5a195.png)

fixRotate redraws the image by mapping it to a new canvas and saving. This would strip metadata and potentially change the file format.

What is the purpose of fixRotate?

**Comment by ZeroX-DG** [comment]
@MiloTodt The fix rotate function used to rotate the image into the right direction. You can take a look at this PR for more information: https://github.com/BoostIO/Boostnote/pull/2322
