### ISSUE TITLE
Can Paste image from clipboard

### ISSUE THREAD

**Issue by pcwu** [BoostIO/Boostnote#286]
Hey guys! Boostnode is really awesome!

I wish a new useful feature:

When paste image to markdown ,can make a directory name "assets" and paste the image as a png file in this image ,then will insert a relative image url

like this:

[Atom package: markdown-image-helper](https://atom.io/packages/markdown-image-helper)

![](https://i.github-camo.com/0c0a490d69ebcf133428aedf407b3216c9d3fdd2/68747470733a2f2f6769746875622e636f6d2f62696779756b692f6d61726b646f776e2d696d6167652d68656c7065722f7261772f6d61737465722f6173736574732f524541444d452d64316562612e706e67)

**Comment by kazup01** [comment]
Oh right! That sounds good.
What do you think about it? @asmsuechan

**Comment by asmsuechan** [comment]
Hi @pcwu, is it for prevention of broken link? If it's true, I'll try to ensure that create a directory into boostnote storage like '~/boostnote/images' and images are thrown into it on paste. Does this suit your needs?

**Comment by pcwu** [comment]
Hello @asmsuechan, it sounds great! Thanks!

**Comment by pcwu** [comment]
Hello @asmsuechan, it sounds great! Thanks!

I think relative path is better. It might sync-up in different device with different absolute path in the future.

Maybe 'images' dir is beside 'notes' dir and the insert link is like ![](images/xxx.png)

**Comment by asmsuechan** [comment]
@pcwu, I understand what you want. It's for transplantable. I feel it's so good interface. Nice suggestion!

**Comment by thomas-lange-smf** [comment]
yeah relative paths in general would be great (for sync)

especially, as the markdown viewer does not seem to pick up on OS specific "shortcuts" like ~ or ..
So this does not work on macOS, as it searches in the Applications Folder, which it assumes to be the Web Root

![Cap-theorem](~/Desktop/someImage.png)
![Cap-theorem](../assets/someImage.png)

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Applications/Boostnote.app/Contents/Resources/app/media/365505812.png 
```
Put it in a fixed location besides the notes folder sounds great (under whatever name).

BTW: I ❤️ your application

**Comment by evmin** [comment]
+1
 The app is great.
* Vim mode
* Night mode
* Great  edit/preview switch
* Markdown

Next step is easier image paste functionality and probably search within the notes!

**Comment by kazup01** [comment]
How about this? #730

FYI @evmin, Added context search box at v0.8.12👍 #696

**Comment by asmsuechan** [comment]
It's been a while, but I'm working on this request now.
ref: https://github.com/BoostIO/Boostnote/pull/818

**Comment by kazup01** [comment]
👍👍👍👍

**Comment by kazup01** [comment]
Thank you for you guys discussion and support.

**Comment by loggerhead** [comment]
Is this issue solved? I find that 0.11.2 on windows 10 x64 still can't paste image from clipboard.

**Comment by iax7** [comment]
it does, just use `command+shift+V`

**Comment by ijoseph** [comment]
Can't find this on the new version of the app, sadly.

**Comment by Flexo013** [comment]
@ijoseph There is a [different repo](https://github.com/BoostIO/BoostNote.next/issues) for the new app in case you want to post a new issue.
