### ISSUE TITLE
Image not displayed in markdown preview

### ISSUE THREAD

**Issue by fzzylogic** [BoostIO/Boostnote#2862]
Duplicate of issue #2834

# Current behavior

After direct paste or drag and drop of an image in markdown mode, image preview does not work due to insertion of %5C character instead of back slash in preview HTML. Similar to #2815, but relates to markdown preview window, not html export.

![screenshot](https://i.imgur.com/VQ2eC74.png)

# Expected behavior

Image preview should work.

# Steps to reproduce

1. Cut and paste or drag and drop an image into a markdown note.
2. Observe broken image link in html preview window.
3. Open dev console and find the link
4. Change %5C to back slash. 
5. Observe correctly displayed image.

# Environment

- Version : 0.11.13
- OS Version and name : Windows 10 [Version 10.0.17134.523]

**Comment by 0xcc-Since2016** [comment]
Yeah i suffer from exactly same issue.

**Comment by zzdjk6** [comment]
This issue seems not happen in Ubuntu system, it could be related to Windows

**Comment by Devsper** [comment]
Hello,

This is a known issue and they are working on it.

[issue#2834](https://github.com/BoostIO/Boostnote/issues/2834)
[pull#2848](https://github.com/BoostIO/Boostnote/pull/2848)

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/BoostIO/Boostnote/pull/2835
