### ISSUE TITLE
add HTML 5

### ISSUE THREAD

**Issue by CarinaGood** [BoostIO/Boostnote#2865]
# Current behavior
Feature request!
Does not support HTML 5. The command``` <mark>``` is not working.

# Expected behavior
The command ```<mark> ```should work.

# Steps to reproduce

1. ```<mark>Hello</mark>```

# Environment

- Version : 0.11.9
- OS Version and name : Ubuntu 16.04

**Comment by ZeroX-DG** [comment]
I gonna need more information on this. I can't reproduce this problem with just the `Hello` step :smile:

**Comment by CarinaGood** [comment]
Oh I am sorry. xD 

What I meat was:

```
<mark>Hello</mark>

```

**Comment by ZeroX-DG** [comment]
Works fine for me in v0.11.13, you should try update to the latest version.
![image](https://user-images.githubusercontent.com/12984316/52330085-551e0f00-2a59-11e9-91be-8fb0629293d3.png)

**Comment by CarinaGood** [comment]
I made the update. It is still not working. I am now on version v0.11.13. My OS is Ubuntu 16.04.

![image](https://user-images.githubusercontent.com/29724589/52332015-de055e00-29f9-11e9-8b48-a4a17cff06d2.png)

**Comment by Devsper** [comment]
Actually have the same issue on Windows 8.1. Boostnote v0.11.13

![image](https://user-images.githubusercontent.com/19436156/52338857-d2229780-2a0b-11e9-9eb4-205138fd3dda.png)

**Comment by dayfuaim** [comment]
Mine also doesn't work:
![2019-02-06 16 19 37](https://user-images.githubusercontent.com/1274699/52344164-17a28d00-2a2b-11e9-8ce5-18ea4d2891f6.png)
OS X 10.10, Boostnote 0.11.13

**Comment by XarisA** [comment]
It will work if you allow "dangerous html tags"

![1](https://user-images.githubusercontent.com/3985557/52345883-f344b180-2a26-11e9-9694-1e404c092097.PNG)

**Comment by Flexo013** [comment]
Works as intended. See @XarisA's comment for the solution.
