### ISSUE TITLE
[Feature request] Automatic unchecking for repeating everyday tasks

### ISSUE THREAD

**Issue by Dene33** [BoostIO/Boostnote#2871]
# Current behavior
I have a question/suggestion about behavior of checking. Now it looks like:

- [x] Check 1
- [ ] Check 2

I just create a task and check it if it's done.
# Expected behavior
What's about repeating everyday tasks? Is it possible to make additional checking behavior with possibility of automatic unchecking? 

Example: 
1. I have everyday task 'Check e-mail'
2. I wake up, check my mail and mark this task as done with [x]
3. Next day when I wake up, 'Check e-mail' task is unchecked again [ ]
4. One may add custom interval for unchecking

Love the Boostnote, this feature will make it nearly perfect. Thanks!

# Environment

- Version : 0.11.13
- OS Version and name : Win 10

**Comment by dredav** [comment]
You can use the "clear" button in the top right corner to clear all checkboxes in the evening / morning. Sure, that not an automatic clear each morning...
![kapture 2019-02-07 at 20 33 29](https://user-images.githubusercontent.com/731073/52437626-a8569700-2b17-11e9-8d81-7fd662903055.gif)

**Comment by Dene33** [comment]
That's nice, didn't notice that. Thanks! But it would be super cool to add more functionality to `clear` button, though.

**Comment by Flexo013** [comment]
Boostnote should not be your all purpose todo list. It wasn't made for that. Use something like Todoist if you wish to have more logic within your tasks.
