### ISSUE TITLE
Drag and Drop of images doesn't work (win 10)

### ISSUE THREAD

**Issue by Dene33** [BoostIO/Boostnote#2872]
# Current behavior
Drag and drop doesn't add images. It creates folder inside attachments with hash like `d0e696ea-02c7-4a9b-a4b1-107a768d83f5` and file inside it like `c7b889e6.png` 

![d&d](https://i.imgur.com/7Rz4npi.gif)

I've noticed that Boostnote actually works great with images placed into `attachments` folder itself. It also works with images placed in `attachments\folder_name` but it can't handle `d0e696ea-02c7-4a9b-a4b1-107a768d83f5` kind of path. And **that happens because of `-` symbol**, as I can tell.

# Expected behavior

Drag and drop adds images into Boostnote.

# Steps to reproduce

If you want to check `-` symbol:
1. Create two folders inside `attachments`: one with `-` in its name and one without;
2. Put some images into these folders;
3. Add `![Test.png](:storage\folder_with_-\Test.png)` and `![Test.png](:storage\folder_without_-\Test.png)`

# Environment

- Version : 0.11.13
- OS Version and name : Win 10

**Comment by MaaadMax** [comment]
I have the same issue.

Temporary fix:
Turn the last **Backslash** into a **forward slash**.
![Test](:storage\ca510772-a710-4e8e-8f43-23bae549b16f**/**b53453a3.png)

**Comment by Rokt33r** [comment]
It has been fixed v0.11.15. But, sadly, you have to install it manually because the auto updater in v0.11.13 is broken too... Please download it from https://github.com/BoostIO/boost-releases/releases/tag/v0.11.15.

**Comment by Dene33** [comment]
> It has been fixed v0.11.15. But, sadly, you have to install it manually because the auto updater in v0.11.13 is broken too... Please download it from https://github.com/BoostIO/boost-releases/releases/tag/v0.11.15.

Should I reinstall Boostnote uninstalling it first?

**Comment by Rokt33r** [comment]
@Dene33 If you're using Windows, you don't have to uninstall. Installer will replace the old one.
