### ISSUE TITLE
innerText is exited when using a href

### ISSUE THREAD

**Issue by centell** [BoostIO/Boostnote#2877]
# Current behavior

`[name](https://url)` works well but `<a href="url">name</a>` has a problem.

```
<a href="https://www.w3schools.com">Visit W3Schools</a>
```
 The above tags are replaced with the following tags.
```
<a href="https://www.w3schools.com"></a>
"Visit W3Schools"
```

<img width="1161" alt="screen shot 2019-02-10 at 03 09 46" src="https://user-images.githubusercontent.com/19484641/52524556-8a3c9280-2ce1-11e9-9c58-3a943e374f0d.png">

# Steps to reproduce

1. make a new note
2. write these codes
```
<a href="https://www.w3schools.com">Visit W3Schools</a>
```

# Environment

- Version : Version 0.11.8 (0.11.8)
- OS Version and name : macOS Mojave(10.14.3)

**Comment by ZeroX-DG** [comment]
You can switch your setting to `Allow dangerous HTML tags` in Interface setting and everything will be good
![image](https://user-images.githubusercontent.com/12984316/52527826-f9db6d80-2d33-11e9-94e9-155cb98083ca.png)
