### ISSUE TITLE
Snippet tabs overwriting other tabs when closed

### ISSUE THREAD

**Issue by ericsolomon** [BoostIO/Boostnote#288]
When you create a snippet note with multiple tabs, upon closing the tab, the editor of the tab you closed overwrites the contents of the tab to the right, effectively losing all of the content in the right tab. I will try to post a gif of this in action.

Steps to re-create:

1. Create snippet note
2. Add text into editor (e.g. "foo 123")
3. Hit '+' to create new tab
4. Add text into editor of new tab (e.g. "foo 234")
5. Navigate back to original tab
6. Click to 'x' in the original tab to close it
7. Tab that contained "foo 234" now contains original tab content "foo 123"

This only seems to occur when you close a tab that has a tab to its right. Closing a right tab does not copy the contents over to the left tab.

![snippet_bug](https://cloud.githubusercontent.com/assets/3520251/22924544/177353f4-f26b-11e6-8c29-a128f1333568.gif)

**Comment by ericsolomon** [comment]
For the record, I have been looking into fixing this. I am not too familiar with developing an electron app though so I have had some issues into debugging the process. Is there an IRC/slack that I could discuss this?

**Comment by asmsuechan** [comment]
Hi @ericsolomon, you can ask us anything here. Actually, the maintenance of any IRC is not in place so far.

**Comment by asmsuechan** [comment]
And this snippet issue is a quite complicated. Thus I'm pleased you are attempting to fix it.

**Comment by redcom** [comment]
One should not change directly the  state of the component using assignation or . 

this.state.*=* can lead to undesired behavior.


Try altering the code
'''
  deleteSnippetByIndex (index) {
    let snippets = this.state.note.snippets.slice()
    snippets.splice(index, 1)
    this.state.note.snippets = snippets
    let snippetIndex = this.state.snippetIndex >= snippets.length
      ? snippets.length - 1
      : this.state.snippetIndex
    this.setState({
      note: this.state.note,
      snippetIndex
    }, () => {
      this.save()
    })
  }
'''

this.state.note.snippets = snippets

this.setState accepts also a function so you can scope the note.snippets and work inside that closure.

**Comment by redcom** [comment]
Sorry for bad formatting. I am on the road

**Comment by asmsuechan** [comment]
Hi, @redcom. Why don't you send a PR?

**Comment by redcom** [comment]
I was trying to actually run this application with npm run hot or npm run start or grunt and npm start.
I was not able to start it and there is no error in the electron javascript console
I will submit a patch.

**Comment by prat0318** [comment]
It is still happening on the latest release.

![Screencast]()

![](https://media.giphy.com/media/xT9IgDKtEaeBTOqnks/giphy.gif)
