### ISSUE TITLE
[Bug] Path not replaced when exporting file

### ISSUE THREAD

**Issue by Aaron-Bird** [BoostIO/Boostnote#2884]
This ":storage" is not replaced with "attachments" when exporting files  

First, export the file to "1.md"
![5](https://user-images.githubusercontent.com/25508292/52755962-c30a9d80-303a-11e9-807d-f16c4098a306.PNG)

Then, Open "1.md"
Image storage path is not replaced
![4](https://user-images.githubusercontent.com/25508292/52755971-cdc53280-303a-11e9-94cb-25f714a09e79.PNG)

I think maybe it is caused by "removeStorageAndNoteReferences"
![3](https://user-images.githubusercontent.com/25508292/52756182-78d5ec00-303b-11e9-82b7-affedd75f1c8.PNG)

**Comment by Aaron-Bird** [comment]
In addition, exporting html files also has bugs
![1](https://user-images.githubusercontent.com/25508292/52757489-c81e1b80-303f-11e9-8116-f0abb8ddf229.PNG)
![2](https://user-images.githubusercontent.com/25508292/52757493-cb190c00-303f-11e9-8741-8b5b88c575da.PNG)

**Comment by ehhc** [comment]
@Aaron-Bird why do you close the bug? As far as i know, the patches for the problems aren't merged yet.. Was it fixed and i missed it?

**Comment by Rokt33r** [comment]
Fixed by https://github.com/BoostIO/Boostnote/pull/3549
