### ISSUE TITLE
[Bug] Input tool isn't available on the search box

### ISSUE THREAD

**Issue by Aaron-Bird** [BoostIO/Boostnote#2885]
# Current behavior
The input word cannot be displayed in the search box by Google Chinese input tool
![geda](https://user-images.githubusercontent.com/25508292/52777134-0f2b0180-307e-11e9-80ac-b18479492587.gif)

# Expected behavior
It works if I change the code in "browser/main/TopBar/index.js"
![1](https://user-images.githubusercontent.com/25508292/52778093-2539c180-3080-11e9-84ca-5d8a6c755e71.PNG)
![2](https://user-images.githubusercontent.com/25508292/52778082-20750d80-3080-11e9-82ed-c214d9ca217e.PNG)

![2](https://user-images.githubusercontent.com/25508292/52778102-2b2fa280-3080-11e9-9590-91515a69277b.gif)

**Comment by Aaron-Bird** [comment]
> # Current behavior
> The input word cannot be displayed in the search box by Google Chinese input tool
> ![geda](https://user-images.githubusercontent.com/25508292/52777134-0f2b0180-307e-11e9-80ac-b18479492587.gif)
> 
> # Expected behavior
> It works if I change the code in "browser/main/TopBar/index.js"
> ![1](https://user-images.githubusercontent.com/25508292/52778093-2539c180-3080-11e9-84ca-5d8a6c755e71.PNG)
> ![2](https://user-images.githubusercontent.com/25508292/52778082-20750d80-3080-11e9-82ed-c214d9ca217e.PNG)
> 
> ![2](https://user-images.githubusercontent.com/25508292/52778102-2b2fa280-3080-11e9-9590-91515a69277b.gif)

**Comment by ksunyata** [comment]
Same behavior in Japanese with Google input tool.
I hope to be fixed it, too.

**Comment by Agile-yun** [comment]
Same behavior in Korean on the search box... 
I hope to be fixed it, too.
