### ISSUE TITLE
[Feature Request] In app markdown cheatsheet

### ISSUE THREAD

**Issue by Kevin-Chung** [BoostIO/Boostnote#2895]
It would be nice to have a markdown syntax cheatsheet with [helpful information](https://github.com/TobseF/boostnote-markdown-cheatsheet/blob/master/README.md) available inside of the editor somehow, possibly as a popup / modal. 

Either way I really enjoy this app!

**Comment by ZeroX-DG** [comment]
You can go to help -> cheatsheet to view it
