### ISSUE TITLE
[Bug] Synchronizing notes between computers deletes attachments 

### ISSUE THREAD

**Issue by DavidMChan** [BoostIO/Boostnote#2896]
# Current behavior

When using a cloud provider to synchronize data between computers if the note referencing an attachment is out of date on a computer (though either lag of the provider, or a broken update ordering in the app), Boostnote will delete the attachment because no reference to the attachment exists in the outdated version of the note. 

It seems like the note is able to synchronize perfectly well, however the incoming note when it synchronizes has broken attachment links because the computer has already deleted them from the shared provider. 

# Expected behavior

Attachments should not be deleted until the note is up to date.

# Steps to reproduce

This one is slightly tricky to reproduce because it requires creating an out of date note reference however I have found the following steps to be rather reliable:

1. Create a note on a shared storage (such as dropbox)
2. Open boostnote on two computers simultaneously
3. Add an attachment on one computer
4. Open boostnote on the second computer with the outdated note, and refresh boostnote

# Potential Solutions

Adding versioning to notes/attachments so that attachments newer than the note version will not be deleted. Another option would be to add a delay in the deletion of files by marking files for deletion, and deleting them at a later time if no references continue to exist. 

# Environment

- Version : 0.11.15
- OS Version and name : OSX 10.14.2 (Mojave), Ubuntu 18.04
- Storage Provider: Dropbox

**Comment by Diomas** [comment]
I have to comment out the code that manages attachments because of that. It deletes files not only while directory sync process but when a note is edited and attachment references are copy/pasted inside the note itself.

This:
```
// const {
//   storageKey,
//   noteKey
// } = this.props
// attachmentManagement.deleteAttachmentsNotPresentInNote(
//   this.editor.getValue(),
//   storageKey,
//   noteKey
// )
```
And this:
```
// } else if (attachmentManagement.isAttachmentLink(pastedTxt)) {
//   attachmentManagement
//     .handleAttachmentLinkPaste(storageKey, noteKey, pastedTxt)
//     .then(modifiedText => {
//       this.editor.replaceSelection(modifiedText)
//     })
```

Now everything works just fine. I can sync notes folder via Syncthing, manually add files to attachments folder and add references to them without worrying anything can be silently deleted

**Comment by Flexo013** [comment]
I can't reproduce this issue. 

Feel free to comment/reopen this issue if you still experience it.
