### ISSUE TITLE
Editing a searched Note not possible, when deleting the searched word in the note

### ISSUE THREAD

**Issue by iBaff** [BoostIO/Boostnote#29]
Note example:

> Test for the win.

Now if you put **Test** in the search bar, you will find this note. If you now edit the note and delete the word Test, the note obviously doesn't match the search criteria any more. It will vanish from the search result list, whilst editing the note.

**Comment by Rokt33r** [comment]
Yes, you're right. I'm going to show another popup rather than article list like below.

<img width="755" alt="screen shot 2016-05-04 at 1 09 50" src="https://cloud.githubusercontent.com/assets/5865853/15005002/8b60238a-11f9-11e6-848c-4b56a9dedf7a.png">

Thank you for reporting. 😄

**Comment by Rokt33r** [comment]
This problem has been fixed from v0.6.*. But, It still sucks. I still have some plans to enhance more. Please keep watching.
If you have any idea, it it good to reopen this issue or make a new one.
