### ISSUE TITLE
main search input do not accept Chinese input

### ISSUE THREAD

**Issue by weaming** [BoostIO/Boostnote#2904]
# Current behavior

Main search input do not accept Chinese input. 

# Expected behavior

The normal Chinese input:
![image](https://user-images.githubusercontent.com/10275711/53391727-4086c400-39d2-11e9-829c-d8c5bd8c0149.png)
You can see the alphabets in the input area, after click space or number to select text, the Chinese text will replace the alphabets.

But the current behavior will clear the alphabets in step one, no Chinese can be input into, this is not correct.

# Environment

- Version : 0.11.13 (0.11.13)
- OS Version and name : macOS Mojave 0.14.2

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2885. Feel free to re-open the issue if you believe it's not a duplication.
