### ISSUE TITLE
make backticks more slack-ish

### ISSUE THREAD

**Issue by prydda** [BoostIO/Boostnote#2905]
# Current behavior
This is more of a suggestion than a issue 💯 

When using the same interface theme as codeblock the backticks goes invisible as you can see in the screenshot below. 
![image](https://user-images.githubusercontent.com/2561787/53408285-6bffb380-39be-11e9-9994-75f25e52ca8f.png)

# Expected behavior

Can we make the backticks on words or oneliners more slack-ish? 
![image](https://user-images.githubusercontent.com/2561787/53408277-6904c300-39be-11e9-9da0-ac5e7d169a8b.png)

If so, it will be visible regardless of your theme 👍

**Comment by ZeroX-DG** [comment]
Thanks for reporting but we already have someone reported this issue: https://github.com/BoostIO/Boostnote/issues/1994

Good thing is there's a PR for that ready: https://github.com/BoostIO/Boostnote/pull/2724
