### ISSUE TITLE
"Copy to clipboard"-button scrolls view to the top in toggle mode

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#2911]
# Current behavior

On a long markdown note clicking the "copy to clipboard" on a code block scrolls the note all the way to the top.

# Expected behavior

The view should not be changed by the "copy to clipboard" button.

# Steps to reproduce

1. Have a long markdown note, with a code block at the bottom using triple quotes.
2. Make sure to use the toggle mode view (not the side by side view).
3. Click the "copy to clipboard" on the code block.
4. The copying goes through but the note is also scrolled to the top.

# Environment

- Version : 0.11.15
- OS Version and name : Windows 10 and Ubuntu 16.04

**Comment by ZeroX-DG** [comment]
I submitted a PR for this: https://github.com/BoostIO/Boostnote/pull/2914. Thank you for reporting.

**Comment by Flexo013** [comment]
@ZeroX-DG Should I be the one to close this issue as the PR is merged? Or should that be done once this big fix is released?

**Comment by ZeroX-DG** [comment]
I didn't realize that it was merged. I'll close this issue. Thanks for reminding me, mate!
