### ISSUE TITLE
[Feature Request] Theme for preview

### ISSUE THREAD

**Issue by tomasforsman** [BoostIO/Boostnote#2915]
# Current behavior

I can make editor and sidebar use one theme and the rest of the interface including the preview window another theme.

# Expected behavior

I want to be able to set a theme for the preview alone. I want everything dark except for the preview window.

# Environment

- Version : 0.11.15
- OS Version and name : win10

**Comment by ZeroX-DG** [comment]
Currently you can customize the preview style using the custom css box in the interface setting (at the bottom).
