### ISSUE TITLE
Can't type chinese when searching

### ISSUE THREAD

**Issue by lonelyma1021** [BoostIO/Boostnote#2925]
I use two different chinese input method. Both of them can not type chinese in searching bar.  But I can type English letter there. I think it's a bug.

# Environment

- Version :0.11.15
- OS Version and name : Deepin linux 15.9 & windows 7

**Comment by liupengfei66** [comment]
i had the same problem.

env: mac os, version 0.11.15

**Comment by johan456789** [comment]
Doesn't work with Japanese too. Probably doesn't work for CJK languages.

**Comment by forestail** [comment]
This is the same as #2885.

**Comment by JunweiZheng93** [comment]
same problem +1

**Comment by sdvdxl** [comment]
me too mac os 10.14.4 (18E226) ，Boostnote 0.11.15，0.11.13

**Comment by Ronnie-6606** [comment]
same problem +1

mac os 10.13.3 boostnote 0.11.15

**Comment by ANTON072** [comment]
same problem +1

mac os 10.14.5
boostnote 0.11.17

**Comment by copetit** [comment]
also Korean. downgradinng to 0.11.10 , can type.

**Comment by Flexo013** [comment]
This now possible in the current version of Boostnote.
