### ISSUE TITLE
unable insert text in search field

### ISSUE THREAD

**Issue by proidit** [BoostIO/Boostnote#2928]
does not allow you to enter text in the search field

**Comment by ZeroX-DG** [comment]
Can you describe more about your problem

**Comment by faustomura** [comment]
already described, i type in the search field but does not write any character in the search field. flash cursor appear but not write!
![image](https://user-images.githubusercontent.com/4655081/54466490-432e3b00-4780-11e9-9a9f-557a2c456555.png)

**Comment by faustomura** [comment]
instead if I paste the text it works! very strange.
![image](https://user-images.githubusercontent.com/4655081/54466572-9b653d00-4780-11e9-8412-9b8ad1a1a7ed.png)

**Comment by ZeroX-DG** [comment]
Are you using any special input method like Japanese, etc?

**Comment by faustomura** [comment]
cancel everything! 
it was a problem caused by ghostpress! 
turning it off everything works perfectly. 
I'm sorry

**Comment by ZeroX-DG** [comment]
No problem 😄
