### ISSUE TITLE
[feature request] Multilevel catalogue

### ISSUE THREAD

**Issue by lqzhgood** [BoostIO/Boostnote#2932]
# Current behavior
Boostnote now has only one level catalogue .
![qqq](https://user-images.githubusercontent.com/9134671/54519300-291f7300-49a1-11e9-9144-c90c80c98d15.jpg)

# Expected behavior

Add Multilevel catalogue would be better.
Like  
- System
  - Linux
     - openwrt
     - centos
   - Windows

# Environment
- Version : 1.7.9.0
- OS Version and name : Windows 10

**Comment by Diomas** [comment]
duplicate of https://github.com/BoostIO/Boostnote/issues/586
