### ISSUE TITLE
Bug(?): Selecting multiple notes when opening them

### ISSUE THREAD

**Issue by JayZ2398** [BoostIO/Boostnote#2935]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/BoostIo/Boostnote/issues/2935)

# What's happening
Opening notes highlights/selects them in the sidebar. If you try to delete a single note and forget this, you will delete all notes you have opened (and not deselected) in your session.

*Possible solution*: Introduce checkboxes/a field on each note in the sidebar to toggle selection, and leave the rest of the note's box in the sidebar for opening the note.

# Expected behavior
Perhaps I am misunderstanding this feature that may be intentionally designed. However, I would expect that clicking on a new note in the sidebar would only open it rather than select it.

# Steps to reproduce
**EDIT**: I should note that I installed Boostnote on Windows with Chocolatey (a package manager).
1. Open a note.
2. Have the sidebar open.
3. Open another note.
4. Original note and newly opened note are both highlighted in sidebar. In order to return to first note (or any previously visited/highlighted note), need to unhighlight/deselect and then select again.

![image](https://user-images.githubusercontent.com/28042291/54569866-8282b300-4a30-11e9-9aa7-2c4a1c3f7e71.png)

# Environment

- Version : 0.11.15
- OS Version and name : Windows 10 64-bit (v1803)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars1.githubusercontent.com/u/25799946?v=4' alt='hub45' width=24 height=24> hub45](https://issuehunt.io/u/hub45) ($20.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIo/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Devsper** [comment]
This happens for me as well, but not all the time. It usually happens after Boostnote have been running for a while. I've been trying to replicate the problem with different sequence of actions but to no success.
It returns to normal if you restart Boostnote.  

Environment
---
Version : 0.11.15
OS Version and name : Windows 8.1 64-bit
