### ISSUE TITLE
extra closing tags

### ISSUE THREAD

**Issue by H-I-D** [BoostIO/Boostnote#294]
Hi,
When I write some kind of html tags that is not closed in code blocks, its closing tags appeared in preview.
Is this issue related to #205?

![boostnote_issue](https://cloud.githubusercontent.com/assets/12569381/23091317/bd527cd0-f5f6-11e6-9c0d-acf68c706f9a.gif)

App version is 0.8.5.

**Comment by asmsuechan** [comment]
Hi @H-I-D, thanks for your report! Umm, we developer confirmed this bug of the code block. We're considering to fix it as soon as possible. Please wait a while. Sorry for any inconvenience.

**Comment by kazup01** [comment]
Hi @H-I-D san, @asmsuechan fixed this bug🎉
We will update next version! Thank you for waiting!

**Comment by H-I-D** [comment]
Great job! 👍

**Comment by kazup01** [comment]
Enjoy😆
