### ISSUE TITLE
Switching editor takes priority over (un)fold button

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#2950]
# Current behavior

On a markdown note clicking the fold or unfold arrow causes a switch to editing mode rather than just folding or unfolding.
![image](https://user-images.githubusercontent.com/4507015/55093835-7f816580-50b5-11e9-9890-ab0b532d4d56.png)

# Expected behavior

The editor mode should not be switched to when clicking the (un)fold arrow.

Small side note: Performing a long click on the arrow does perform the expected behavior.

# Steps to reproduce

1. Have a markdown note, with a fold HTML block.
```md
<details><summary>Test summary.</summary>
Test body
</details>
```
2. Make sure to use the toggle mode view (not the side by side view).
3. Click the (un)fold arrow.
4. It switches to the editor mode.

# Environment

- Version : 0.11.15
- OS Version and name : Windows 10 and Ubuntu 16.04

**Comment by MiloTodt** [comment]
Should be addressed and fixed in https://github.com/BoostIO/Boostnote/pull/2952
