### ISSUE TITLE
Reading folders rather than database? 

### ISSUE THREAD

**Issue by TobiasDev** [BoostIO/Boostnote#2954]
While I love boostnote, the lack of a mobile app at the moment is stopping me from being able to use it (since I really need a mobile app). What I have done is that I now use one app for desktop, and another for my phone (markor), and I sync between these by syncing a folder directly through my cloud provider. 

Would it be possible for Boostnote to read folders instead of a database? Eg. I have a folder called Notes, with sub-folders for my different notes. Would it be possible for Boostnote to read this?

**Comment by tamvcspk** [comment]
You can add folder with whatever name you want.
Go to preference -> Storage -> storage location.
Unfortunately you cannot arrange your note as a folder tree, and I want that feature too.

**Comment by TobiasDev** [comment]
Yeah, but then my .md notes doesn't show up for me, so I guess they have to be in a database or such?

**Comment by tamvcspk** [comment]
This is boostnote.json file in the root of storage location:
`{
  "folders": [
    {
      "key": "80287a70da85f6715ab5",
      "color": "#FF8E00",
      "name": "Cheat sheet"
    },
    {
      "key": "69a6b1691ec4c6f2e7fe",
      "color": "#E10051",
      "name": "Snippest"
    },
    {
      "key": "f29cb8e2a1eebb58d7c3",
      "color": "#B013A4",
      "name": "Server Tutorial"
    },
    {
      "key": "3d21e133d4c3c782f16f",
      "color": "#B013A4",
      "name": "Tutorial"
    }
  ],
  "version": "1.0"
}`
This is how a note is stored in ~<location>/notes:
`createdAt: "2019-03-21T05:06:45.472Z"
updatedAt: "2019-03-21T05:06:49.834Z"
type: "MARKDOWN_NOTE"
folder: "3d21e133d4c3c782f16f"
title: ""
tags: []
content: ""
linesHighlighted: []
isStarred: false
isTrashed: true`
Boostnote used json and cson file as its database.

**Comment by Flexo013** [comment]
#490 is for changing from cson to md.
