### ISSUE TITLE
Snippet Expansion Bug?

### ISSUE THREAD

**Issue by omnomz** [BoostIO/Boostnote#2958]
# Current behavior

# Expected behavior

# Environment

- Version : 0.11.15
- OS Version and name : 10.13.6 macOS High Sierra

**Comment by serima** [comment]
@omnomz Is #2959 same issue? Should we close this issue?

**Comment by omnomz** [comment]
Yes it is, apologies. First time making a post and didn’t realise my text didn’t show. Thanks!
