### ISSUE TITLE
Markdown symbols in LaTeX blocks changing next to them text style in editor

### ISSUE THREAD

**Issue by ftvkyo2011** [BoostIO/Boostnote#296]
[0.7.1 from AUR]
[0.8.5]

text in editor:
`$$2*tsize$$, so it is...`
screenshot of editor:
    ![screenshot](https://cloud.githubusercontent.com/assets/17923271/23092817/4b2bd3c0-f5e4-11e6-8be3-4bed9caf1d5e.png)

As you can see, text next to asterisk became italic.

Also, it works for `_` and `__`, `**` and `***` etc.

~~If you already fixed it, please, just update AUR package.~~
I edited PKGBUILD, here is the new one.
[PKGBUILD.txt](https://github.com/BoostIO/Boostnote/files/784988/PKGBUILD.txt)

__UPD__: So, i checked version [8.5.0], and this bug is still there.

**Comment by ftvkyo2011** [comment]
Please, update AUR package.

**Comment by asmsuechan** [comment]
Hi @ftvkyo2011, thanks for your report! Actually, we've confirmed this problem and we're considering its priority is a quite low. So if you feel inconvenient so much, you should fix it and open PRs.

**Comment by ftvkyo2011** [comment]
It will be hard for me, but I'll try. Can I also try to add highlighting for LaTeX in editor?

**Comment by asmsuechan** [comment]
@ftvkyo2011 Why not, thank you. Ask me anything, I can support you.

**Comment by ftvkyo2011** [comment]
So...
![untitled1](https://cloud.githubusercontent.com/assets/17923271/23093543/9aeb3cd0-f5f7-11e6-8661-9b2e126d9b2c.png)
![untitled2](https://cloud.githubusercontent.com/assets/17923271/23093544/9eb44d0c-f5f7-11e6-9e40-4932c3f44b36.png)

**Comment by asmsuechan** [comment]
@ftvkyo2011 Yes... I've confirmed this issue, too. And it was reported by https://github.com/BoostIO/Boostnote/issues/294. I wanna fix it as soon as possible.

**Comment by kazup01** [comment]
Hi @ftvkyo2011 san, @asmsuechan fixed this bug🎉
We will add it on next udpate! Thank you for waiting!

**Comment by kazup01** [comment]
Released at v0.8.9🎉
