### ISSUE TITLE
The NPM package js-sequence-diagrams has been deleted, which breaks the pipeline

### ISSUE THREAD

**Issue by MiloTodt** [BoostIO/Boostnote#2969]
https://www.npmjs.com/package/js-sequence-diagrams
Every pull request will be failed on CI for this until resolved.

![image](https://user-images.githubusercontent.com/21070668/55831128-4094dc00-5ac7-11e9-978a-1219ed2b783d.png)

**Comment by jghyllebert** [comment]
Some from trying to install on AUR:
```
==> Starting build()...
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for js-sequence-diagrams@^1000000.0.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'Boostnote-0.11.15'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonas/.npm/_logs/2019-04-09T19_46_18_946Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
Error making: boostnote
```

**Comment by Xiao1209** [comment]
I also have such a problem, please tell me how to deal with it.
Thanks.

**Comment by MiloTodt** [comment]
For local building, open your package.json and delete this line.
![image](https://user-images.githubusercontent.com/21070668/55996826-6fe54d80-5c6d-11e9-8669-7b40acccc5c5.png)

The issue with the CI will need to be addressed on this end.

**Comment by captn3m0** [comment]
Please create a new release

**Comment by serima** [comment]
@MiloTodt 
It seems that @Rokt33r has been changed to use forked js-sequence-diagrams in this [commit](https://github.com/BoostIO/Boostnote/pull/2881/commits/df0634fe60082405adcc7ad7f8369c255d7983c4) yesterday, but does CI still fail?

**Comment by ZeroX-DG** [comment]
Nope, I have just restarted the build and everything is fine now. Feel free to re-open the issue if this still happens.
