### ISSUE TITLE
Is syntax highlightning available for code in Markdown? 

### ISSUE THREAD

**Issue by nemecsek69** [BoostIO/Boostnote#2972]
Code in Markdown preview is not highlighted. 
Any way to visualize it with colors as in snippets?

Markdown:

![github001](https://user-images.githubusercontent.com/10434760/56110618-73225700-5f55-11e9-82b7-573e788b08b4.PNG)

Snippet:

![github002](https://user-images.githubusercontent.com/10434760/56110776-fcd22480-5f55-11e9-878e-c292c6740b1c.PNG)

**Comment by eVen-gits** [comment]
Yes, surround your code like this:

    ```java
    <code>
    ```
![Example](https://i.imgur.com/nKmQC9h.png)

**Comment by nemecsek69** [comment]
Thank you @eVen-gits! Of course I overlooked this feature...
