### ISSUE TITLE
Hello,I want to know what should i do to make the compile sound code,thanks!

### ISSUE THREAD

**Issue by merroneutron** [BoostIO/Boostnote#2973]
I have downloaded the sound code package,and decompressioned it,but i don't know what to do next,anybody help me？

**Comment by ZeroX-DG** [comment]
Can you tell us what are you trying to do?

**Comment by MiloTodt** [comment]
You can find the instructions for manually building the source code here: https://github.com/BoostIO/Boostnote/blob/master/docs/build.md

If you're just trying to install Boostnote for normal usage, the easiest way is to use one of the pre-compiled installers here: https://boostnote.io/#download
