### ISSUE TITLE
Boostnote Portable (#344)

### ISSUE THREAD

**Issue by moses-bowman** [BoostIO/Boostnote#2974]
https://github.com/BoostIO/Boostnote/issues/344#issuecomment-480596979
Hopefully this has been looked upon by the developers. 
Been looking forward to storing Boostnote's `config` files on a custom folder. :suspect:
Tried @nickbe's solution to no avail :feelsgood:

🙌  @boostIO team, for this app.

**Comment by MiloTodt** [comment]
Have you tried one of the solutions here? 

http://carlcheo.com/portable-app-creators

**Comment by Flexo013** [comment]
Thanks for your enthusiasm!

It would be really nice to have a portable version of Boostnote. Let's continue this on the other issue that you linked. That way we can keep everything in one place. And on top of that it already has funding 😉
