### ISSUE TITLE
Latex inline $ shifted slightly down for some characters

### ISSUE THREAD

**Issue by johannmeyer** [BoostIO/Boostnote#2975]
# Current behavior

![image](https://user-images.githubusercontent.com/25986904/56205126-333c9c00-6049-11e9-8558-25037c1743eb.png)

# Expected behavior

I am expecting the inline text in math mode to be inline with the text like the capital letters in math mode.

# Steps to reproduce

1. Some text $x$ $x_i$ $\eta$ what I want is this $X$ $X_i$ $\theta$

\* It appears to mostly occur with lower case characters but also some symbols like \eta

# Environment

- Version : 0.11.15
- OS Version and name : Ubuntu Gnome 16.04 LTS

**Comment by johannmeyer** [comment]
Duplicate of https://github.com/BoostIO/Boostnote/issues/2922

**Comment by omnomz** [comment]
If it really bugs you, you can adjust the katex display `vertical-align` for a quick fix. It bugged me to no end since I type a lot of math.

**Comment by BryantKunZhe** [comment]
> If it really bugs you, you can adjust the katex display `vertical-align` for a quick fix. It bugged me to no end since I type a lot of math.

Hello omnomz, where can I adjust the katex display? I didn't find it.

**Comment by omnomz** [comment]
@BryantKunZhe By custom CSS. Try:
`.katex{ display: inline-block; vertical-align: bottom !important; }`
Let me know if it works for you!

**Comment by BryantKunZhe** [comment]
> @BryantKunZhe By custom CSS. Try:
> `.katex{ display: inline-block; vertical-align: bottom !important; }`
> Let me know if it works for you!
It does work! Thank you very much!
