### ISSUE TITLE
Home/End goes to end of markdown line instead of end of wrapped line

### ISSUE THREAD

**Issue by jat255** [BoostIO/Boostnote#2976]
This might be the intended behavior, but Boostnote's editor operates unlike other text editors that I have experience, in that when you have a line that wraps due to a long width, pressing the `Home` or `End` keys, moves the cursor to the end of the actual line (where there is a newline character), rather to the end of the soft-wrapped line. Compare this to editing a long line in a comment in the Github editor, where those keys will move the cursor just to the or beginning of the current line, rather than the end of the entire text block.

# Current behavior

Home/End keys move to the end of the "logical line" as delimited by line numbers

# Expected behavior

Home/End would move to the beginning or end of the current soft-wrapped line in the editor (like most other programs)

# Steps to reproduce

1. Type a line in the editor long enough that it wraps around (without adding a newline with the Enter key) 
2. Press Home or End from within that line

# Environment

- Version : 0.11.15
- OS Version and name : Arch Linux

**Comment by jat255** [comment]
I just realized this is a duplicate of the unaddressed issue #689. I'll close it, if desired.

**Comment by ZeroX-DG** [comment]
I'll close this issue. Thanks for reporting anyway.
