### ISSUE TITLE
Nested checkbox shows incorrect progress bar

### ISSUE THREAD

**Issue by zhangyuting** [BoostIO/Boostnote#2977]
# Current behavior
I have below nested checkbox. However, If I check one of the sub-checkbox, the progress bar shows 33% instead of 50%.

- [ ] You complete me
  - [ ] Function paramerts hint
  - [ ] Update ALL_IN_ONE_CONFIG

![image](https://user-images.githubusercontent.com/615755/56337824-c3115000-61d9-11e9-94e5-c3e567aa9aec.png)

# Expected behavior
I think the progress bar should show 50% since there are only two subtask

# Steps to reproduce
- [ ] You complete me
  - [ ] Function paramerts hint
  - [ ] Update ALL_IN_ONE_CONFIG

# Environment

- Version : Boostnote 0.11.13
- OS Version and name : Windows10

**Comment by dredav** [comment]
I'm pretty sure, that this is not an issue. You have three checkboxes (one at the top with two sub items). So if you tick one of these three checkboxes is that a progress of 33% each.
If you don't want that the top level checkbox is an "task" you can convert it to a list item.
```markdown
* You complete me
  - [ ] Function paramerts hint
  - [ ] Update ALL_IN_ONE_CONFIG
```

**Comment by ZeroX-DG** [comment]
I agree with @dredav and will close this. Feel free to re-open this issue if you need.
