### ISSUE TITLE
[Feature Request] Overview of current document

### ISSUE THREAD

**Issue by johannmeyer** [BoostIO/Boostnote#2980]
# Expected behavior

It would be nice to have an overview of the current document on the side that can be toggled on and off. So that it is easier to jump to the different headings and subheadings in a document like a lot of PDF readers and IDEs can do. Basically the table of contents feature but without having to scroll up the entire document each time.

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2502. But thanks for reporting!
