### ISSUE TITLE
Split Window Horizontally

### ISSUE THREAD

**Issue by cybergenerx** [BoostIO/Boostnote#2981]
Currently using 0.11.15 on MacOS.

At the moment, within Boostnote, you can only split the Toggle Mode vertically. So you have the editor as leftmost pane and preview at the rightmost pane.

When I am writing a note, I often have one program like a browser or pdf on the left of my screen and Boostnote on the right side. 

Because of the vertical limitations, it means you can't see as much of Boostnote editor as you would. But by allowing the window to be split horizontally we can maximise screen space and write and see a lot more.

**Comment by ZeroX-DG** [comment]
There is a PR for this https://github.com/BoostIO/Boostnote/pull/2936
