### ISSUE TITLE
Update to Arch User Repository PKGBUILD

### ISSUE THREAD

**Issue by gromain** [BoostIO/Boostnote#299]
Hi,

Is it possible to update the AUR (Arch User Repository) PKGBUILD to the new version? Here: https://aur.archlinux.org/packages/boostnote
We are stuck with version 0.7.1 .

Thanks a lot!

**Comment by gromain** [comment]
Also, I'm happy to do it myself, I just needs the rights to do it.

**Comment by cajone** [comment]
I would also like to see this happen

**Comment by gromain** [comment]
For the record, my pseudo on AUR is gromain. You know, in case you want to transfer the ownership.

**Comment by ftvkyo2011** [comment]
Hey, here is the new PKGBUILD.

```
# Maintainer: Dick Choi <fluke8259@gmail.com>
# Contributor: Romain Bazile <gromain.baz@gmail.com>
pkgname=boostnote
pkgver=0.8.6
pkgrel=1
pkgdesc="Opensource note app for developer"
arch=('x86_64')
url="https://b00st.io/"
license=('GPL')

source=(
  "https://github.com/BoostIO/boost-releases/releases/download/v$pkgver/boostnote_${pkgver}_amd64.deb"
  )

noextract=()

md5sums=('238e691f62ce47d799438316703e2cf2')

validpgpkeys=()

package() {
      tar -xa -f ${srcdir}/data.tar.xz
        cp -r "${srcdir}/usr" "${pkgdir}/usr"
}
```

**Comment by gromain** [comment]
Thanks, but I'd rather have it pushed in AUR!

**Comment by ftvkyo2011** [comment]
I would like to do it, but I don't know how to contribute to AUR. (I think, that only the package maintainer can do it).
_Sorry for my bad English._

**Comment by gromain** [comment]
No worries, my comment was addressed at the package maintainer in AUR!

**Comment by ftvkyo2011** [comment]
@sota1235 , can you please update AUR PKGBUILD?

**Comment by Flexo013** [comment]
I'm checking the AUR right now and it seems to be down, so I can't see when it was last updated.

Feel free to reopen this issue if the AUR still needs updating.
