### ISSUE TITLE
Images linking to attachments folder have incorrect path

### ISSUE THREAD

**Issue by isaacgr** [BoostIO/Boostnote#2995]
# Current behavior
Images pasted from the clipboard get backslashes added in Windows 10

![image](https://user-images.githubusercontent.com/20640588/57403197-19edc200-71a7-11e9-858a-03fb9ae45d2a.png)

This is not the correct path. The image does not show up in the note.

![image](https://user-images.githubusercontent.com/20640588/57403218-2c67fb80-71a7-11e9-9037-5b7942012818.png)

# Expected behavior

Using forward slashes render the image correctly.

![image](https://user-images.githubusercontent.com/20640588/57403281-58837c80-71a7-11e9-9c07-3308635ae741.png)

![image](https://user-images.githubusercontent.com/20640588/57403291-5e795d80-71a7-11e9-9728-e567501364c9.png)

# Environment

- Version : 0.11.13
- OS Version and name : Windows 10

**Comment by dredav** [comment]
This Bug is already fixed with 0.11.14. You need to update Boostnote manually once (the auto updated was broken) by downloading the newest release from https://boostnote.io/

**Comment by isaacgr** [comment]
Awesome that worked. Thank you.
