### ISSUE TITLE
Search box ignores dead keys

### ISSUE THREAD

**Issue by tewe** [BoostIO/Boostnote#3004]
Possibly related to #2925 

# Current behavior

Dead keys are ignored when typing into the search box.

The steps below insert a regular `e`.

# Expected behavior

`é`

# Steps to reproduce

1. hit option+e
2. hit e

# Environment

- Version : 0.11.15
- OS Version and name : macOS 10.13.6

**Comment by Flexo013** [comment]
Can't reproduce this issue on 0.11.17 of Boostnote.

@tewe Feel free to reopen this issue if you are still experiencing it on the latest version.
