### ISSUE TITLE
Create new note, sidebar jumping to "All notes" view from selected storage

### ISSUE THREAD

**Issue by the-c0d3r** [BoostIO/Boostnote#3006]
# Current behavior

When creating new markdown note, the sidebar will automatically go to "All notes" view, no matter which collection/storage you're in previously. 

# Expected behavior
When creating a new note, after selecting "Markdown" or "snippet", the view should go back to the same state, instead of going back to the "All notes" view. It is annoying to see the view goes back to the all notes. The reason I use different storage/collection is to better organize the notes, and filter out irrelevant notes from my view. 

# Steps to reproduce

1. Go inside any storage/collection/subdir
2. Click create new note, select Markdown or snippet
3. The sidebar "notes list" goes to "All notes" view. 

# Environment

- Version : 0.11.15
- OS Version and name : MacOS Mojave 10.14.5 Beta

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2823
