### ISSUE TITLE
Attachments: why jpg convert to png?

### ISSUE THREAD

**Issue by w123475** [BoostIO/Boostnote#3008]
OS: Ubuntu
Version: 0.11.15

Hello.

I use Boostnote for file management (1 file = 1 note with description and tags).

This is convenient, but I noticed one unpleasant moment: for some reason, the images are converted to png and their weight increases (in some cases, 8-9 fold increase!)

original: http://i.imgur.com/RYqJCQg.png
copy in Boostnote: http://i.imgur.com/VTfM6cQ.png

original: http://i.imgur.com/ZtC6XMq.png
copy in Boostnote: http://i.imgur.com/DkwWnK1.png

The file extension does not change to PNG (programmers-love-cats.jpeg => 20c22146.jpeg), but the file is defined as the PNG file manager and Krita.

In this case, if I open a copy of the file from Boostnote in Krita and re-save it as jpg, the size of the copy will be equal to the size of the original and the boostnote will continue to work normally.

**Comment by w123475** [comment]
In this case, if I open a copy of the file from Boostnote in Krita and re-save it as jpg, the size of the copy will be equal to the size of the original and the boostnote will continue to work normally.

**Comment by MiloTodt** [comment]
Related to this: https://github.com/BoostIO/Boostnote/pull/2961
