### ISSUE TITLE
Debian - Unrendered Window on startup

### ISSUE THREAD

**Issue by Ezneh** [BoostIO/Boostnote#3019]
# Current behavior
Boostnote starts with an unrendered Window
![image](https://user-images.githubusercontent.com/1930305/58176751-46273980-7ca3-11e9-969b-73699b237beb.png)
(What you see on the screenshot is the actual Boostnote Window. It just doesn't render itself and keeps w/e was on the screen before).

# Expected behavior
Boostnote should start without any issue

# Steps to reproduce
1. Install Boostnote (any version ?) with the .deb package as root
2. Launch Boostnote (root or any other user)

# Environment

- Version : 0.11.14, 0.11.15
- OS Version and name : Debian GNU/Linux 9
- XFCE

**Comment by clone1612** [comment]
That error should only appear if you're using Electron 4+, would you mind giving the output of ```electron --version```?

I've submitted a pull request to make it compatible (#2971) but as the .deb package still uses an older Electron that might not be the root cause of your problem.

**Comment by Ezneh** [comment]
So, seems like electron was not installed (even npm and nodejs). And afetr the installation of everything, electron --version doesn't print anything. So I guess it's not specifically related to boostnote.

**Comment by Flexo013** [comment]
@Ezneh Is this still occurring with v0.11.17?

**Comment by Ezneh** [comment]
Yes, sadly it is still occurring. 

My electron version is now: 5.0.7, boostnote on latest version as well.
Still trying to run it on Debian, as root user on xfce version 4.12.

**Comment by Flexo013** [comment]
According to [this comment](https://github.com/BoostIO/Boostnote/issues/3122#issuecomment-511251856) Electron `3.0.8` should work with v0.11.17 of Boostnote. Maybe the newer versions of Electron somehow cause this issue. Could you see if the issue persists with Electron `3.0.8`?

**Comment by Ezneh** [comment]
This is still not working with version 3.0.8. But I think the issue might be from the electron side as I tried another app this week (which I guess is electron based, but didn't verify) and had the same issue.

**Comment by Flexo013** [comment]
Strange... For now I will mark this as an upstream issue with Electron.

If somebody else could test running Boostnote on Debian and see if they have the same issue, then we can look into this further.

**Comment by Ezneh** [comment]
Hello, after the full upgrade of Debian Stretch to Buster, the application seems to work properly now.
I have actually no real clue what was the problem, but at least in my case it is resolved.

**Comment by Flexo013** [comment]
@Ezneh Thanks for the info!
