### ISSUE TITLE
MAke markdownlinter to switch off

### ISSUE THREAD

**Issue by takacsot** [BoostIO/Boostnote#3025]
Please make an option to switch of markdown linter.

**Comment by AWolf81** [comment]
Once PR #2983 is merged you can disable linting with the markdown config field:
```json
{
  "default": false
}
````

Maybe a checkbox to enable/disable markdown linting would be better instead of the config. Or is the config input enough?

**Comment by d3vnick** [comment]
I am wondering how this feature has been accepted in the first place. One of the most appreciated "feature" of the Markdown markup language is its flexibility and syntax error tolerance. Also it nice to put some extra line when you read it (not parsed).

**Comment by benbucklin** [comment]
@AWolf81 I think the config input is a good workaround for now, but having a checkbox would be much more intuitive and save a lot of users from having to dig for a solution. When I saw the linter warnings the first thing I did was look for a checkbox under "Interface".

**Comment by Flexo013** [comment]
0.11.17 has been released and allows for configuration of the Markdownlinter. By default linting will be off.
