### ISSUE TITLE
how to add subcatalog?

### ISSUE THREAD

**Issue by lzjqsdd** [BoostIO/Boostnote#303]
is there any way to add  subcatalog or do you have the plan ？

**Comment by asmsuechan** [comment]
Hi @lzjqsdd, does `subcatalog` mean `subdirectory`? If true, developers are not contemplating to implement it for now soon.

**Comment by lzjqsdd** [comment]
thx.
To me it's a great feature,I love boostnote.

I've found the list of requested features,there are Google drive,Dropbox,Onedrive and so on . And I use [Nutstore](https://www.jianguoyun.com/)(like dropbox)  for a long time and it supports webdav.And now I use it as backend sync service of Boostnote.
If possible,add this to support list.

**Comment by asmsuechan** [comment]
We've not done any special supports for WebDav. It means we're just claiming that Boostnote supports them. Thus you can use Nutstore as your WebDav even though it's not supported officially. You can ask us anything when you hit some issues according to WebDav. We'll try to support after that.

**Comment by lzjqsdd** [comment]
ok,thank you !

**Comment by lixingcong** [comment]
Yes I thought syncing notes with webdav is a good option.
