### ISSUE TITLE
Finding a note Chinese input can't be entered

### ISSUE THREAD

**Issue by yuamera** [BoostIO/Boostnote#3030]
# Current behavior
![image](https://user-images.githubusercontent.com/50633505/58310344-02663880-7e39-11e9-9369-a34fa58c1144.png)

# Expected behavior
Finding a note Chinese input can't be entered
I am using mac sogou
https://github.com/yuamera/image/blob/master/issue-gif/boostnote-issue.gif

# Environment

- Version :0.11.16
- OS Version and name : macOS Mojave 10.14.4

**Comment by jhdcruz** [comment]
It's probably a `Font` or `locales` problem...

**Comment by yuamera** [comment]
When can I fix it?
Can't search Chinese is equal to not searching for a user who uses Chinese

**Comment by ZeroX-DG** [comment]
@yuamera There's a pull request to fix this issue and it has been approved. This bug will be fixed in the next version of Boostnote.

**Comment by ThaddeusJiang** [comment]
@ZeroX-DG when we get the new release?

**Comment by ZeroX-DG** [comment]
That's depend on @Rokt33r

**Comment by Rokt33r** [comment]
@ThaddeusJiang In the next week! Sorry for being late.

**Comment by Flexo013** [comment]
Closing this issue as the next release 0.12.0 fixes this issue.
