### ISSUE TITLE
Please give instructions to make .rpm package for fedora.

### ISSUE THREAD

**Issue by RatanShreshtha** [BoostIO/Boostnote#304]
It would be really nice if you can provide instructions to build .rpm package for fedora in [build.md](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md).

**Comment by kazuhisya** [comment]
@RatanShreshtha  Hi,

It does not seem to be ready yet.
Please check this PR. #266

As a temporary solution, you will be able to use [this gist](https://gist.github.com/kazuhisya/98e8f480d5edfcf50cc52755c352ebb0).

**Comment by RatanShreshtha** [comment]
I tried alien to convert .deb to .rpm and when I am trying to install it is giving me libffmpeg.so()(64bit) is needed by boostnote-0.8.6-2.x86_64, how can

**Comment by petercheco** [comment]
Install repo RPMFusion:
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm
dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm

Update system:
dnf update

Install FFmpeg:
dnf install ffmpeg
if need
dnf install ffmpeg-devel

Install your alien converted package...

**Comment by jcbritobr** [comment]
Error: Transaction check error:
  o arquivo / da instalação de boostnote-0.8.11-2.x86_64 conflita com o arquivo do pacote filesystem-3.2-37.fc24.x86_64
  o arquivo /usr/bin da instalação de boostnote-0.8.11-2.x86_64 conflita com o arquivo do pacote filesystem-3.2-37.fc24.x86_64

this not work. There is a conflict with filesystem-3.2-37.fc24.x86_64

**Comment by shotor** [comment]
@jcbritobr : Forcing the installation worked for me for the most part - https://stackoverflow.com/questions/27172142/conflicts-with-file-from-package-filesystem-3-2

```sh
sudo rpm -ivh --force boostnote-0.8.14-2.x86_64.rpm
```

Don't know how to do it with `dnf`. There's a weird problem with squares being drawn for text when browsing the file system - if you avoid that and type your paths you'll be fine.

Having an `AppImage` would be great
https://github.com/BoostIO/Boostnote/issues/66#issuecomment-291001510

**Comment by alefisico** [comment]
Hi, is there any follow up to this issue? I would like to use boostnote in fedora

**Comment by kazuhisya** [comment]
@alefisico Hi, it is already on the documents. so may be of your help.

https://github.com/BoostIO/Boostnote/blob/master/docs/build.md#make-own-distribution-packages-deb-rpm

**Comment by murpholinox** [comment]
Can someone explain with more detail how to build the rpm... From download source to voilà!

**Comment by SkYNewZ** [comment]
Hi all! I just finish to create a repo that contain "official" .rpm package as well as the standalone package. I invite you to check it : https://github.com/SkYNewZ/Boostnote-packages/releases.
I hope it will be helpfull for you.

![capture du 2018-01-16 01-07-33](https://user-images.githubusercontent.com/26750012/34966114-ac1ffde4-fa59-11e7-8600-9382f6a50833.png)

**Comment by murpholinox** [comment]
Hi. Thanks @SkYNewZ 
Seems to work!! 

(Downloaded and installed with `dnf install *.rpm`)

**Comment by alefisico** [comment]
thanks @SkYNewZ it works perfectly

**Comment by jimpriest** [comment]
It's 2018 - how about a Snap, AppImage or Flatpack instead of distro specific downloads?

**Comment by ruffson** [comment]
+1 for a rpm package or snap/appimage/flatpack

**Comment by jhit** [comment]
It is not difficult to build the packages. It is described here: https://github.com/BoostIO/Boostnote/blob/master/docs/build.md

**Comment by jhit** [comment]
@SkYNewZ Maybe you can get in touch with the maintainers of boostnote and move your build pipeline into the official repository. I think this would be great to keep things more easy for users.

**Comment by MostafaNorzade** [comment]
Hi. @SkYNewZ
Thanksssssssssssssssssssss .

**Comment by ZeroX-DG** [comment]
The build instruction for rpm is at the bottom of our [build guide](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md). I'll suggest the dev team to also build rpm package in the next release. I'll close this issue, if there's anything else please tell me I'll re-open it.
