### ISSUE TITLE
Annoying exclamation mark

### ISSUE THREAD

**Issue by yuamera** [BoostIO/Boostnote#3040]
# Current behavior
![image](https://user-images.githubusercontent.com/50633505/58391780-cd8cf800-8069-11e9-9dbf-ccced7ae7905.png)

# Expected behavior
make the exclamation mark disappear
can I  repair MD010
or
ignore the markdown check

I tried a lot of methods and can't get rid of these exclamation marks.

# Environment

- Version :0.11.16
- OS Version and name :mac mojave 10.14.4

**Comment by sosukesuzuki** [comment]
These exclamation marks is shown by Markdown Lint. The feature has became optional (default `false`) on Version 0.11.17. Please try upgrade to Version 0.11.17.
