### ISSUE TITLE
Changing between editing and viewing mode is not working properly

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#3043]
# Current behavior
When I click on my note, it doesn't switch to editing mode, I have to click a bunch of times, it's almost random whether it works or not.

# Expected behavior

When I click on my notes it should switch to editing mode, and when I click away it should switch back to viewing mode

# Steps to reproduce

1. Open the note (it opens in viewing mode)
2. Click on it
3. It stays in viewing mode

Here is a short video that explains the issue better: [link](https://youtu.be/iHR0qyHm0JY)

# Environment

- Version : 0.11.17
- OS Version and name : macOS 10.14.5

**Comment by MiloTodt** [comment]
Duplicate of https://github.com/BoostIO/Boostnote/issues/3024
