### ISSUE TITLE
Preview scrollbar changes position so that entered text is not visible

### ISSUE THREAD

**Issue by Tyilo** [BoostIO/Boostnote#3047]
# Current behavior

When typing something after a large image, the preview scrolls back to the top instead of staying at its current location, so you can see the output of what you type. I don't know if it can be triggered without an image.

Enabling or disabling the "When scrolling, synchronize preview with editor" option, doesn't fix the problem.

Before step 3 (below):
![Before step 3](https://i.imgur.com/8F8aAoL.png)

After step 3 (below):
![After step 3](https://i.imgur.com/pBe9Ywr.png)

# Expected behavior

The preview's scrollbar doesn't change position.

# Steps to reproduce

1. Create a new snippet and paste the following:
```
# Test

A

![892ea562.png](:storage/ea2f7416-c3c2-478a-b65d-7f930e9f8174/892ea562.png)

B
```

Here the image is a very high image, higher than your screen's height. (You can use: https://transfer.sh/11osU9/892ea562.png)

2. Enable preview and scroll down to the bottom of the preview, so you can see "B".
3. Type something after "B".
4. The preview's scrollbar scrolls up to the top, so you can't see the result of what you are typing.

# Environment

- Version : 0.11.16
- OS Version and name : Arch Linux

I think it might be a good idea to an option to never change the position of the scrollbar of the preview pane, when typing in the editor pane. (No smart algorithm to figure out where the best scrolling position is, but just remembering position before rendering and then restoring that position after re-rendering).

**Comment by ZeroX-DG** [comment]
Possible related https://github.com/BoostIO/Boostnote/issues/3023

**Comment by ZeroX-DG** [comment]
@Tyilo A bug fix has just been merged to fix this issue. Feel free to re-open this issue if you can test the latest code and this still occurs to you.
