### ISSUE TITLE
Enable UI rescale

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#305]
Hi developers of Boostnote. First of all, I want to give a warm hug to you all. Thank you for making such a great app. 

My problem is that the UI seems to be so small.  I can't find a way to make it bigger. Available options only supports changing font size of the editor and the preview part. Even changing the DPI of the operating system couldn't help (*as you can see in the photo, the system's "file view help" is big enough but others are small*). 

I would like to see if there is any way to achieve UI rescaling, so that text and UI elements get a little bigger. Thank you so much.
![image](https://cloud.githubusercontent.com/assets/15828926/23336783/47a09e7e-fc0c-11e6-826b-dbf813a74370.png)

**Comment by kazup01** [comment]
Thank you for enjoy Boostnote!
You can resize UI and font, refer to this image.
![aaaa](https://cloud.githubusercontent.com/assets/8602615/23336941/98bc153a-fc21-11e6-8ebc-532a478928f3.png)

**Comment by VoLuong** [comment]
Wow thank you.

**Comment by VoLuong** [comment]
actually i dont want to rescale everything, but enlarge the tittle text, ( or in this case, it is "5 minutes ago" , "Snippet note example" ). But well, at least it works :+1:
