### ISSUE TITLE
Missing startup icon or location

### ISSUE THREAD

**Issue by parthi2929** [BoostIO/Boostnote#3053]
# Current behavior
Unable to locate boostnote to launch

After I install, boostnote opens and I could create notes. Once I close it, I am nto able to re open, because there is no icon on desktop, or system tray or task bar or anywhere. I could not even find the exe location via task manager. So I could not find anyway to launch it again. Giving boostnote in windows R only opens the boostnote.json folder, where there is also no exe to launch.

# Expected behavior
Give me at least one icon or a way to launch in windows. Show some options during installation to choose the method. 

# Steps to reproduce
Install latest boostnote in windows 10, close and try finding it to launch again.

# Environment

- Version : latest
- OS Version and name : Windows 10

**Comment by ZeroX-DG** [comment]
This is a very strange behaviour, boostnote can't just auto disappear from your computer, maybe any virus scanner deleted it by accident?

**Comment by parthi2929** [comment]
I do not say it was removed, it is there just that we do not know where. No, my anti virus usually reports if it deletes or does anything on anything.  

Where will usually be the installation location in windows?

**Comment by ZeroX-DG** [comment]
I'm not on Windows so I can't be sure about that, but have you try to search it in the start menu?

**Comment by parthi2929** [comment]
yes I did. I could not find it anywhere except the folder containing boostnote json file.

**Comment by Flexo013** [comment]
The `.exe`to launch Boostnote on Windows can be found in "C:\Users\<your_username>\AppData\Local\boost", which you can navigate by pressing Win+R and then typing "%appdata%".

**Comment by Flexo013** [comment]
@parthi2929 Does this solve your problem?

**Comment by parthi2929** [comment]
yes, I was able to find here "C:\Users\your_username\AppData\Local\boost" but I prefer some obvious exe location and icon to access in any location like tray or desktop etc.

**Comment by Flexo013** [comment]
Searching Boostnote within your start menu should locate it (if it doesn't then check your windows search indexing settings). From there you can choose yourself if you want a tray icon or desktop icon.

I do agree that it is quite common for installers to ask whether they should add a desktop icon, and if I remember correctly the Boostnote installer has no such feature. I will create a new feature request issue to see if we can add this.
