### ISSUE TITLE
HTML and PDF export is broken

### ISSUE THREAD

**Issue by szjani** [BoostIO/Boostnote#3054]
# Current behavior

The recently added PDF export functionality may broke the HTML export. I get the following error 
whenever I want to export a note into either HTML or PDF.

![image](https://user-images.githubusercontent.com/545872/58787796-d726da80-85ea-11e9-9a5e-f6e8f6ab01b4.png)

HTML export was working fine until a recent update.

# Expected behavior

As the HTML export worked before I would like that part to be fixed. PDF export would a nice feature but now I am completely blocked, cannot do workaround (export to HTML and printing that into PDF).

# Environment

- Version : 0.11.17
- OS Version and name : Windows 10

**Comment by ZeroX-DG** [comment]
This is strange I thought this bug has been fixed a long time ago? I also can't reproduce this bug. @Rokt33r can you reproduce this on windows?

**Comment by Flexo013** [comment]
This might be related to #3048

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2968
