### ISSUE TITLE
Editor theme change not working

### ISSUE THREAD

**Issue by ositowang** [BoostIO/Boostnote#3057]
# Editor theme not working on Win 10
I downloaded the boostnote on my new computer(version Boostnote 0.11.17). When I tried to modify the Editor Theme. It is not working. I tried with uninstalling and restarting and it is still not working.

Operating system:  Win 10 64bit.
Boostnote version: 0.11.17

![image](https://user-images.githubusercontent.com/26860856/58900105-88ea0800-86cc-11e9-9947-539ff7792c5d.png)

**Comment by fkholmat** [comment]
This is the same issue as #3018. This solution worked for me: https://github.com/BoostIO/Boostnote/issues/3018#issuecomment-495294972

Operating system: Win 10 64bit.
Boostnote version: 0.11.17

**Comment by ositowang** [comment]
Great, Thanks a lot @fkholmat. However, I hope this bug could be fixed soon.

**Comment by reneottowebdesign** [comment]
Same issue here the css styles does not load.
