### ISSUE TITLE
Context Search for Snippet Note

### ISSUE THREAD

**Issue by camcramz** [BoostIO/Boostnote#306]
Feature Request:  Would it be possible to add a contextual search on Snippet note similar to how it works with markdown notes?  I love the interface of snippet notes vs markdown notes because of the additional description and name data capture and the only thing that is missing is the ability to search contextually on the note.

**Comment by Gernatch** [comment]
+1 on this request. I knew I had a function in a long piece of code called updateList(), and it would have been extremely quick to just search for it. 

Additional points for making it allow for Regex (maybe for phase 2?)

**Comment by evmin** [comment]
+1

**Comment by kazup01** [comment]
Added context search box at v0.8.12. #696

**Comment by vgrange** [comment]
+1 for the mac app

**Comment by DFelten** [comment]
A better search is necessary. I have now created a snippet and could not even search for the title of the snippet.
