### ISSUE TITLE
When editing, I always jump to the top of the page.

### ISSUE THREAD

**Issue by RunningXJ** [BoostIO/Boostnote#3069]
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by RonelYin** [comment]
I have the same issue.
The editor will scroll up to top, when I type the beginning of the last line.
For example, I have finished 998 lines, and I scroll to buttom for the 999th line. It will happen, if I typed the first alpha, and if the 999th line already has some alphaes, It will not happen.

**Comment by RonelYin** [comment]
It seems to happen with "editor and preview" mode. if I toggle to the "editor" mode, it will not happen.

**Comment by jsosulski** [comment]
Have the same behaviour here.

Version: 0.11.17
OS: Ubuntu 18.04

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/3023

**Comment by incace** [comment]
This is driving me crazy because I work in editor/preview mode 99% of the time.
