### ISSUE TITLE
Shift-Cmd-/ on Mac opens the Help menu

### ISSUE THREAD

**Issue by dtom90** [BoostIO/Boostnote#3074]
# Current behavior

Changes from https://github.com/BoostIO/Boostnote/pull/2962 add the shortcut `Shift+Ctrl+/` on Windows and [`Shift-Cmd-/` on mac](https://github.com/BoostIO/Boostnote/pull/2962/files#diff-4771352a7e4e4f9d82f0be3e914757adR215) to insert today's date & time. However, on macOS, `Shift-Cmd-/` simply opens the Help menu of the application:

<img width="712" alt="Screen Shot 2019-06-11 at 20 50 11" src="https://user-images.githubusercontent.com/911671/59316128-dea15000-8c8a-11e9-8322-d28afe56b2f2.png">

This is due to a system shortcut. From [Mac keyboard shortcuts](https://support.apple.com/en-us/HT201236):
<img width="499" alt="Screen Shot 2019-06-11 at 20 59 45" src="https://user-images.githubusercontent.com/911671/59316325-e4e3fc00-8c8b-11e9-90a3-b19e60bbeb1a.png">

# Expected behavior

When the equivalent shortcut of `Shift+Ctrl+/` for Windows is pressed on Mac, the current date and time should be inserted. E.g.:

<img width="849" alt="Screen Shot 2019-06-11 at 20 55 04" src="https://user-images.githubusercontent.com/911671/59316197-32ac3480-8c8b-11e9-9520-e60b0ccb7700.png">

# Steps to reproduce

1. Open Boostnote 11.17 in macOS
2. Create a new note
3. Press `Cmd-/`
4. Press `Shift-Cmd-/`

# Environment

- Version : 11.17
- OS Version and name : macOS 10.14.5

**Comment by Flexo013** [comment]
Fixed by #3076. This is part of the 0.12.0 release.
