### ISSUE TITLE
Jumps to the top of the page when a checkbox is clicked

### ISSUE THREAD

**Issue by sleeplynerd** [BoostIO/Boostnote#3077]
# Current behavior

When I click on a checkbox, Boostnote throws me at the top of the page.

# Expected behavior

Checkbox should stay inside of the observed area.

# Steps to reproduce

1. Place a checkbox down. Low enough to make the editor's field scrollable.
2. When in "preview mode", click the checkbox. The page will be scrolled up to the beginning. 

# Environment

- Version : 0.11.17-1
- OS Version and name : Ubuntu 18.04.2 LTS (Bionic Beaver)

---
p.s. Maybe this issue #3021 is related to mine?

**Comment by ZeroX-DG** [comment]
I think you should wait until the https://github.com/BoostIO/Boostnote/issues/3021 is fixed and check again because there's a high chance that this is related. I'll close this for now, feel free to re-open if this bug still exists.
