### ISSUE TITLE
Editor UI Padding for first layer of TODO List

### ISSUE THREAD

**Issue by LordDashMe** [BoostIO/Boostnote#3083]
# Current behavior

The **todo** check-boxes feature are in half as you can see in the below screenshot:

![Selection_001](https://user-images.githubusercontent.com/12311971/59578704-1893ab80-90fc-11e9-8414-2f1b2d3ad6a2.png)

# Expected behavior

If the padding for the Markdown Editor Body adjusted from **15px** to **20px**, the below screenshot fixed the UI issue.

![Selection_002](https://user-images.githubusercontent.com/12311971/59578780-7922e880-90fc-11e9-89e8-e0913edb0a9f.png)

# Steps to reproduce

1. Create a default note.
2. Make a todo list markdown syntax.
3. View the markdown syntax in the markdown editor preview.

# Environment

- Version : Boostnote **0.11.17**
- OS Version and name : **Ubuntu 18.04**

**Comment by LordDashMe** [comment]
This pull request affected the UI for Ubuntu 18.04.

https://github.com/BoostIO/Boostnote/issues/2729

**Comment by Mayank-MP05** [comment]
This issue is fixed already...

**Comment by Mayank-MP05** [comment]
Why this is not closed

**Comment by Komediruzecki** [comment]
I'll close the issue as this is fixed.
