### ISSUE TITLE
Search box cannot use Chinese input method (fcitx-rime )

### ISSUE THREAD

**Issue by imaojun** [BoostIO/Boostnote#3084]
# Current behavior
I tried to use the Chinese input method to search for input in the search box, but I could not complete the text on the screen.When inputting Chinese, the input method candidate box will flash and disappear.

Chinese content can be entered in the text area, but the search box cannot. I have to paste the clipboard into the search box to search for Chinese content.

I uploaded a GIF as my demo, and I still have this problem when I upgraded from 0.11.15 to 0.11.17.
![Peek 2019-06-17 18-31](https://user-images.githubusercontent.com/28778042/59598164-1e09e980-912e-11e9-8363-cfa1c2e31c85.gif)

# Steps to reproduce
1. I use pamcan as my package management tool and use the fcitx-rime input tool.
```sh
# intall input tool
$ sudo pacman -S fcitx-rime
$ sudo pacman -S fcitx-configtool
# intsall boostnote 
$ yaourt -S boostnote-bin
```
2. Install the Simplified Chinese input method in the input tool.

3. Switch to Chinese input status and enter Chinese in the search box

# Environment
- Boostnote 0.11.17
- Archlinux

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/2925
