### ISSUE TITLE
The software is not working properly

### ISSUE THREAD

**Issue by Aquarian-Age** [BoostIO/Boostnote#3090]
# Current behavior

git clone https://github.com/BoostIO/Boostnote.git
cd Boostnote/
yarn
yarn run dev
sudo npm install -g grunt-cli
grunt pre-build

# Expected behavior

cd dist/Boostnote-linux-x64/
./Boostnote

# Steps to reproduce

The system is openSUSE 15.0
Yarn run dev can run everything is fine
 Cannot edit files after grunt pre-build build software
The ./Boostnote startup software will generate three files in the /home/name/.config/Boostnote/ directory.
```
SS -> /tmp/.org.chromium.Chromium.mER3QI/SS
 SingletonLock -> liangzi.local-3983
 SingletonCookie -> 15321198581131783175
```

Running the software with yarn run dev without the above three files I don't know why.

[![2019-06-20.png](https://i.loli.net/2019/06/20/5d0bab45f1f7649714.png)](https://i.loli.net/2019/06/20/5d0bab45f1f7649714.png)

[![2019-06-20_1.png](https://i.loli.net/2019/06/20/5d0bab79883e182545.png)](https://i.loli.net/2019/06/20/5d0bab79883e182545.png)

# Environment

- Version :15.0
- OS openSUSE

**Comment by ZeroX-DG** [comment]
Can you tell me what you're trying to do?

**Comment by Aquarian-Age** [comment]
> Can you tell me what you're trying to do?
Start the executable file in ELF format
