### ISSUE TITLE
Export Error when Exporting PDF

### ISSUE THREAD

**Issue by Mitrimo** [BoostIO/Boostnote#3091]
# Current behavior
When trying to export a simple note with pure text and one link to another site (like [this](google.com)), the program reports an
Export error
callback must be a function

This happens under Windows 10 Pro, Version 1803 with Boostnote Version 0.11.17. .md and .html exports work flawlessly.

# Expected behavior
Exporting a regular plaintext .pdf.

# Environment

- Version : 0.11.17
- OS Version and name : Windows 10 Pro Version 1803

**Comment by amedora** [comment]
duplicates #2968, will be resolved by #3048 .
