### ISSUE TITLE
collapsible markdown rendering on boostnote is not normal.

### ISSUE THREAD

**Issue by imaojun** [BoostIO/Boostnote#3092]
# Current behavior
The following collapsible markdown can be rendered correctly on github, but rendering on boostnote is not normal.

The content has not been folded. If the line break is removed, the content can be collapsed, but the markdown syntax cannot be rendered.

**collapsible markdown**

<details><summary>CLICK ME</summary>

*yes, even hidden code blocks!*
```python
print("hello world!")
```
</details>

![Peek 2019-06-23 13-18](https://user-images.githubusercontent.com/28778042/59972015-b8987b80-95b9-11e9-9fba-846988ffc1e4.gif)

# Expected behavior

collapsible markdown works just like github.

# Steps to reproduce

```md
**collapsible markdown**

<details><summary>CLICK ME</summary>

*yes, even hidden code blocks!*
\```python
print("hello world!")
\```
</details>
```

# Environment

- Version :
Boostnote 0.11.17
- OS Version and name :
Archlinux

**Comment by mevers** [comment]
I cannot reproduce the issue on Boostnote 0.11.13 (MacOS Sierra).

Before unfolding:
![Screen Shot 2019-07-13 at 10 33 52 am](https://user-images.githubusercontent.com/9429788/61164578-dffbbc00-a559-11e9-9c5f-d47e12ef819e.png)

Unfolded:
![Screen Shot 2019-07-13 at 10 34 16 am](https://user-images.githubusercontent.com/9429788/61164586-f0ac3200-a559-11e9-8b69-207e08a8019c.png)

Must have `"Allow dangerous html tags"` in Preferences -> Interface -> Sanitisation.

**Comment by imaojun** [comment]
@mevers Awesome, it works.
