### ISSUE TITLE
No ability to disable HTML Code Warnings

### ISSUE THREAD

**Issue by RavenTheDev** [BoostIO/Boostnote#3095]
![BoostNote_Bug](https://user-images.githubusercontent.com/11475987/60016931-27f59480-96ba-11e9-845d-a4faec13fcfc.png)
# Current behavior

When writing code in Markdown or HTML, there are random "Notes" that show up which are designed to show issues with the coding, and how to fix it. This is extremely annoying if you don't need those prompts, and there is currently no method to disable them.

# Expected behavior

There should be an option to enable or disable the option for HTML / MD Code Comments (as per the attached screenshot)

# Steps to reproduce

Just starting typing in code!

# Environment

- Version : boostnote 0.11.16-1
- OS Version and name : Linux UX430UA 5.1.12-arch1-1-ARCH #1 SMP PREEMPT Wed Jun 19 09:16:00 UTC 2019 x86_64 GNU/Linux

**Comment by Flexo013** [comment]
Update to 0.11.17 as it introduces this feature. 

Go to Preferences -> Interface and then uncheck 'Enable MarkdownLint'.
![image](https://user-images.githubusercontent.com/4507015/60017821-fb298900-9689-11e9-971e-42e551e260dd.png)

**Comment by fabiopedrosa** [comment]
@Flexo013 was this option removed?

**Comment by Flexo013** [comment]
@fabiopedrosa Nope, it's still exists in Boostnote Legacy. It does not exist in BoostNote.next
