### ISSUE TITLE
[feature request] auto enclosure for back ticks

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3096]
# Current behavior

Currently, selected text is automatically enclosed by ". Would be nice to have the same for backticks. 

![selected text](https://user-images.githubusercontent.com/44707562/60276590-d3d5f480-98f3-11e9-9e31-2051d8bc4e3d.gif)

# Expected behavior

1. select text in markdown note: `selected text`
2. type: \`

3. result: \`selected text\`

# Environment

- Version : 0.11.12
- OS Version and name : 16.04 Ubuntu

**Comment by ZeroX-DG** [comment]
We have supported this feature. Go to setting -> interface. And add 2 ``` in the `Matching character pairs` setting.
