### ISSUE TITLE
BUG after update to 0.11.17

### ISSUE THREAD

**Issue by dayfuaim** [BoostIO/Boostnote#3101]
# Current behavior
After upgrade from 0.11.x to 0.11.17 the following happens.
Markdown preview is not rendered or not rendered properly.
+ Error at start.
![Снимок экрана 2019-07-01 в 13 18 25](https://user-images.githubusercontent.com/1274699/60429208-46501880-9c03-11e9-9b1d-fa8105c374b0.png)
+ Errors during switching the notes.
![Снимок экрана 2019-07-01 в 13 28 31](https://user-images.githubusercontent.com/1274699/60429646-308f2300-9c04-11e9-820c-fcb95ff89af2.png)

# Expected behavior
Switch to current note is proper.
Markdown preview is rendered properly for the note I am at.

# Steps to reproduce
1. Upgrade to 0.11.17.
2. Run Boostnote.
3. Walk through some notes.

# Environment

- Version : 0.11.17
- OS Version and name : Mac OS X 10.10.5

**Comment by ZeroX-DG** [comment]
@Rokt33r can you reproduce this error on MacOS?

**Comment by Flexo013** [comment]
@dayfuaim Do you still have these errors when using 0.12.1?

**Comment by dayfuaim** [comment]
@Flexo013 No, in 0.12.1 there's no issue.

We can close this, I think.

**Comment by Flexo013** [comment]
Thanks for the info!
