### ISSUE TITLE
Preview scrolls back to the top on its own

### ISSUE THREAD

**Issue by NorimasaFukuoka** [BoostIO/Boostnote#3102]
# Current behavior

When I edit last line on the left editor pane, the right preview pane scrolls back to the top on its own and the editor pane scrolls to its top at the same time. Then I enter something, it comes to the cursor but I enter again, the same thing happens again.

# Expected behavior

Preview just comes with editor, doesn't move on its own.

# Steps to reproduce

1. Separate the pane into editor and preview by clicking 'Toggle Mode'
2. Input some texts on editor. (Long texts are better because it's an error with scrolling)
3. Input some texts on the last line, the preview scrolls back to the top.

# Environment

- Version :
- OS Version and name :

macOS ver10.14.5

**Comment by xyhuangjia** [comment]
the same thing happen to me

**Comment by ZeroX-DG** [comment]
Duplicated https://github.com/BoostIO/Boostnote/issues/3023
