### ISSUE TITLE
figures display error during pdf/html export

### ISSUE THREAD

**Issue by TerryLuo** [BoostIO/Boostnote#3106]
# Current behavior

When I try to export my markdown note into pdf or html format, it does not display the figures inside the notes.  The figures are only shown as broken link.
One possibility could be due to the the link to the figures.  during the exporting, the exporter does not recognize the link the figures.

# Expected behavior

I should expect the figures are displayed correctly.

# Steps to reproduce

1. Create one markdown note, copy one figure into this note.  Usually the figure will be copied to the storage folder, under folder attachments.  The text in the markdown note, will be shown as , e.g. 
`` ![4d871fbe.png](:storage/92b6eb73-60f3-4ad8-9f62-27ea1aea0dca/4e14861b.png)``

2. After doing that, then export this markdown note to pdf. And you will see the errors.

# Environment

- Version : 0.11.17
- OS Version and name : Mac Os, 10.12

**Comment by Flexo013** [comment]
I can reproduce this issue on Ubuntu 16.04.

It should be noted that this issue only occurs for local images. Online/remote images export fine.

- Local `[39d1d282.png](:storage/b770d5d7-4037-45b0-9ab6-6a11e7eef008/39d1d282.png)`
- Remote: `![Title](https://boostnote.io/assets/img/logo.png)`

**Comment by ZeroX-DG** [comment]
This PR should fix this bug https://github.com/BoostIO/Boostnote/pull/3068
