### ISSUE TITLE
Syntax highright is something wrong.

### ISSUE THREAD

**Issue by ktny** [BoostIO/Boostnote#3109]
# Current behavior
![image](https://user-images.githubusercontent.com/10214742/60753072-af230080-a008-11e9-971a-7f9d6ae350f7.png)

![image](https://user-images.githubusercontent.com/10214742/60753023-168c8080-a008-11e9-96cb-6f7a3fe849e8.png)

# Expected behavior
Syntax highlight works prpoerly.

# Steps to reproduce
There was no problem soon after installing it first. Something went wrong after a while. It is not corrected even if it reinstalls afterwards.

# Environment
- Version : 0.11.17
- OS Version and name : Windows10 Home

**Comment by ZeroX-DG** [comment]
Duplicated: https://github.com/BoostIO/Boostnote/issues/3018
