### ISSUE TITLE
Chinese character(simplified) display error

### ISSUE THREAD

**Issue by fengshens** [BoostIO/Boostnote#311]
![jing](https://cloud.githubusercontent.com/assets/7369515/23611897/19ce7648-02b4-11e7-905d-743393e3aa30.gif)

**Comment by kazup01** [comment]
Sorry for inconvenience, but we are not familiar with Chinese language. If possible, would you send us PR?

**Comment by Aaron-Bird** [comment]
Maybe this is the default font error
![jing](https://cloud.githubusercontent.com/assets/25508292/23617602/93e98a9e-02c8-11e7-8da9-acf515c362dc.gif)

**Comment by asmsuechan** [comment]
Hi, @fengshens. What's going on? Perhaps this issue is a problem of the font setting. You need to change the font to fix it.

**Comment by asmsuechan** [comment]
I close because of no reaction.
