### ISSUE TITLE
Deleted search term stays highlighted

### ISSUE THREAD

**Issue by tobysoby** [BoostIO/Boostnote#3111]
This may be not that big an issue, but it gets badly on my nerves nonetheless. You know how it is sometimes...

# Current behavior
When I search for something and delete the search term from the search field, the search term stays highlighted in the editor panel.

# Expected behavior
The search term does not stay highlighted.

# Steps to reproduce
1. Search for something
2. Empty search field by clicking on x-Button or hitting Escape
=> search term stays highlighted
<img width="1392" alt="boostnote" src="https://user-images.githubusercontent.com/5843710/60772137-42843080-a0f2-11e9-8b2c-b002ceab1c69.png">

# Environment
Boostnote 0.11.17
MacOSX 10.14.5

Since it bothers me that much, I'll create a PR with a fix. If you can think of a different (better) way to fix this, please don't hesitate to tell me! Thanks for this great software!

**Comment by Flexo013** [comment]
Thanks for reporting the issue and supplying the fix! It will be part of the next release 0.12.0
