### ISSUE TITLE
[Feature Request] Three mode Toggle

### ISSUE THREAD

**Issue by kumarve** [BoostIO/Boostnote#3113]
# Current behavior
currently, we have only 2 modes of toggle - that is preview mode and editor mode.
preview mode shows both editor pane and read-only rendered pane

preview mode
<img width="721" alt="image" src="https://user-images.githubusercontent.com/14313593/60779406-45197100-a158-11e9-89e8-5454fe1bf39a.png">
In this mode , both editor and notes pane is displayed

edit mode 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/14313593/60779442-6d08d480-a158-11e9-886d-6f4ce8d156b9.png">
only editor is displayed

# Expected behavior
There should be an option for view mode without editor pane. Other note taking apps like joplin we can do that.
1. View Mode - that only shows rendered notes, read-only (This is missing)
2. Editor Mode - that only shows the  editor and no side pane
3. Preview Mode - that shows both editor and notes rendered side by side. 

# Steps to reproduce
1. go to boosnote and create a notebook
2. create a note and type anything 
3. click on toggle switch icon on top right 
<img width="72" alt="image" src="https://user-images.githubusercontent.com/14313593/60779625-0fc15300-a159-11e9-868f-e9c4873e0eab.png">

# Environment

- Version : 0:11:17
- OS Version and name : MacOS 10.12.6

**Comment by MiloTodt** [comment]
There's a trick to do this currently... Click on the toggle button and hold the mouse down, and then drag it down.
![](https://media.giphy.com/media/PntD0NkUjFfwwp4SA4/giphy.gif)

Could use a dedicated way to do it though!

**Comment by arcturus140** [comment]
This is already implemented. you can hide side pane, lock editor or full View Go to preferences and choose different options to switch between modes

**Comment by kumvenka** [comment]
@MiloTodt , thanks. I followed the trick and it worked. I am new to Boosenotes and i don't know what is dedicated way. The full preview mode just flickers for me while changing between the mode, following @arcturus140  steps. I think i am running into this issue https://github.com/BoostIO/Boostnote/issues/2196 
An honest feedback. this feature is not  intuitive for users

**Comment by kumarve** [comment]
@MiloTodt , thanks. I followed the trick and it worked. I am new to Boosnotes and i don't know what is dedicated way. The full preview mode just flickers for me while changing between the mode, following @arcturus140 steps. I think i am running into this issue #2196 ,@arcturus140 thanks for steps though
An honest feedback. UX is not intuitive in this case

**Comment by ZeroX-DG** [comment]
I'll close this issue, feel free to open another issue for the UI/UX problem 👍

**Comment by arcturus140** [comment]
@kumarve sorry for the late reply. As a long time user I am perfectly fine with the current behaviour. 
I am not surprised with your feedback, though. You are certainly not the first one finding the toggle modes confusing. For a first time user UX is not intuitive at all and you have to go to the settings to see which configurations are available and how to set it up. 

There are plans for a new Boostnote for a more extensible and clear UX. This is heavily under development and it is going to take some time until it will be released.

**Comment by Flexo013** [comment]
Somewhat related: https://github.com/BoostIO/Boostnote/issues/2955
