### ISSUE TITLE
Export and import preferences

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3114]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/BoostIo/Boostnote/issues/3114)

# Current behavior

preferences cannot be exported. It would be nice if I could import preference settings to a new installation of Boostnote. 

# Expected behavior

Import and export preferences to back up Boostnote configurations.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/13612118?v=4' alt='boostio' width=24 height=24> boostio](https://issuehunt.io/u/boostio) ($60.00)
### Submitted pull Requests
- [#3146 Created import/export tab](https://issuehunt.io/r/BoostIO/Boostnote/pull/3146)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIo/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by bertomoore** [comment]
Hello, I'm interested in adding this feature! I picture the export file to be a JSON file and an "Import/Export" tab placed after "Snippets" in "Preferences". Let me know if this works. Thank you!

**Comment by Flexo013** [comment]
@bertomoore That sounds great! Feel free to start working on a pull request.

**Comment by bertomoore** [comment]
Awesome! I'll start working on this now.

**Comment by themattgabriel** [comment]
I currently do this manually.

I created a batch file that exports the following directories:

- Exports `%USERPROFILE%\AppData\Local\boost`
- Exports `%USERPROFILE%\Boostnote`
- Exports `%USERPROFILE%\AppData\Roaming\Boostnote`

```bat
@ECHO off
REM Export boostnote-local
ROBOCOPY C:\Users\<username>\AppData\Local\boost <destination> /MIR /R:1 /W:0 /REG /MT:16 /XA:SH /XJ
REM Export boostnote-files
ROBOCOPY C:\Users\<username>\Boostnote <destination> /MIR /R:1 /W:0 /REG /MT:16
REM Export boostnote-roaming
ROBOCOPY C:\Users\<username>\AppData\Roaming\Boostnote <destination> /MIR /R:1 /W:0 /REG /MT:16 /XA:SH /XJ
```

Switching the source and destination above simple imports my preferences and notes.

## Environment

OS: Windows 10
Version: 1903

**Comment by ips138** [comment]
> * Exports `%USERPROFILE%\Boostnote`
Note that this is pointing to the default notes storage folder. If you changed your default location, and/or added others to give you a n hierarchy of note folders (like I have) then you'd need to take this into account.

I created a folder called Boostnotes into my sync location to collate all my storage locations together. I then added a few folders within, each mapped in Boostnote storage settings. I use each of those as a collection: Coding, Personal, etc. Each collection you can add folders as normal.

HTH
