### ISSUE TITLE
[Feature Request] Scroll past the last line in the editor

### ISSUE THREAD

**Issue by reklanirs** [BoostIO/Boostnote#3115]
# Current behaviour
The best angle of view when taping should be in the middle of the screen. But currently in boostnote, after filling one page in a note, new lines will always appear from the bottom and you have to always look down at the bottom of the screen. (Unless you tap a lot of blank lines at the end of the passage.)

# Expected behaviour
There is an option in preference ```Allow preview to scroll past the last line``` but it's only for preview. I hope this feature can be added to the editor, too.

**Comment by arcturus140** [comment]
already supported

**Comment by reklanirs** [comment]
Didn't notice that option in preference. Sorry about that.
@arcturus140  Thank you!
