### ISSUE TITLE
Deprecation causing a crash

### ISSUE THREAD

**Issue by Berkmann18** [BoostIO/Boostnote#3116]
# Current behaviour
It opens (the frame shows up) but remains unresponsive with an error on the terminal: `(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead`.

# Expected behaviour

Boostnote should open and work

# Steps to reproduce

0. Open a terminal
1. Type `yay -S boostnote-bin`
2. Then type `boostnote`
3. Watch

# Environment

- Version : 0.11.17-1
- OS Version and name : Linux 5.1.16-arch1-1-ARCH x86_64

**Comment by ZeroX-DG** [comment]
I don't think the deprecated code cause the crash. Can you remove the repo and re-clone and setup everything again?

**Comment by clone1612** [comment]
Is there any error showing up on the Boostnote developer console itself (`ctrl+shift+i` in the actual boostnote frame)?

**Comment by Berkmann18** [comment]
@ZeroX-DG 
> I don't think the deprecated code cause the crash. Can you remove the repo and re-clone and setup everything again?

You may be right, the fact it's about the app instance made me think it was (at least partly) due to that.

@clone1612 
> Is there any error showing up on the Boostnote developer console itself (ctrl+shift+i in the actual boostnote frame)?

On the Electron app?

**Comment by clone1612** [comment]
Yes, the actual Electron app.

**Comment by Berkmann18** [comment]
The issue is that there's no window when I launch it (just a border with whatever is behind it or what was at the same place before) so I can't open the dev tools from it (unless there's a way that I was unaware of).

**Comment by clone1612** [comment]
No indeed, that's true. Quite strange though as `boostnote-bin` uses the official released package (no building from source) and therefore shouldn't have any issues. Would you mind deleting the package and attempting to install the other AUR package `yay -Rsn boostnote-bin && yay -S boostnote` to see if that AUR boostnote version works? Alternatively you could also post a comment on [AUR boostnote-bin package website](https://aur.archlinux.org/packages/boostnote-bin) to see if the author also has experienced some problems.

**Comment by Berkmann18** [comment]
Here's what I get from after running `yay -Rsn boostnote-bin && yay -S boostnote`:
```shell
...
(3/3) checking keys in keyring                                                                                  [###################################################################] 100%
(3/3) checking package integrity                                                                                [###################################################################] 100%
(3/3) loading package files                                                                                     [###################################################################] 100%
(3/3) checking for file conflicts                                                                               [###################################################################] 100%
error: failed to commit transaction (conflicting files)
yarn: /usr/lib/node_modules/yarn/LICENSE exists in filesystem
yarn: /usr/lib/node_modules/yarn/README.md exists in filesystem
yarn: /usr/lib/node_modules/yarn/bin/yarn exists in filesystem
yarn: /usr/lib/node_modules/yarn/bin/yarn.cmd exists in filesystem
yarn: /usr/lib/node_modules/yarn/bin/yarn.js exists in filesystem
yarn: /usr/lib/node_modules/yarn/bin/yarnpkg exists in filesystem
yarn: /usr/lib/node_modules/yarn/bin/yarnpkg.cmd exists in filesystem
yarn: /usr/lib/node_modules/yarn/lib/cli.js exists in filesystem
yarn: /usr/lib/node_modules/yarn/lib/v8-compile-cache.js exists in filesystem
yarn: /usr/lib/node_modules/yarn/package.json exists in filesystem
Errors occurred, no packages were upgraded.
Error installing repo packages
```

**Comment by clone1612** [comment]
It seems that you have installed yarn before, not using pacman/yay but rather with npm hence the conflicts as yay attempts to install the arch yarn package (from the community repo, building from source depends on it). So run `npm uninstall -g yarn` and afterwards `yay -S yarn`.

If that works you have resolved the conflict and can run `yay -Rsn boostnote-bin && yay -S boostnote` again.

**Comment by Berkmann18** [comment]
Sweet, that solved the issue.
