### ISSUE TITLE
Show tags in sidebar

### ISSUE THREAD

**Issue by jhit** [BoostIO/Boostnote#312]
I'm tagging all my notes, but had to realize they are not used much in the app.

Please list all tags in the sidebar for easy filtering / navigation of notes, like evernote can do this.

**Comment by kazup01** [comment]
I was just thinking about it.
How do you think about that separate in Folder area and Tag area in sidebar? 
<img width="405" alt="screen shot 0029-03-06 at 10 50 29 pm" src="https://cloud.githubusercontent.com/assets/8602615/23612593/59ca3e98-02bf-11e7-8585-120af483643f.png">

**Comment by jhit** [comment]
Not exactly sure what would be the best behaviour.
I see two options:
1. Tags belong to a single notes storage and therefore maybe should be shown as children of the storage they belong.
2. Tags are global and are all shown in a seperate tab like in your example.

I would be ok with any of the solutions. If you have different storages for very different type of content, solution 1 would be preferable I think.

**Comment by kazup01** [comment]
Thanks for your suggesting! We will consider it.

**Comment by kazup01** [comment]
Please check #371 . Thank you for your message @jhit san!
