### ISSUE TITLE
Can't rename notes

### ISSUE THREAD

**Issue by hubitor** [BoostIO/Boostnote#3121]
# Current behavior
Not sure if it's a bug or my incompetence but I can't find an option to rename the notes.

EDIT:
I see now that I can set the name in the first line of the note if it's a Markdown Note. 
Is it related to "Extract title from front matter" in the preferences?
I have deactivated this option and it still gets the name from there.
I find it weird to not have an option to rename the note otherwise.

# Expected behavior
I would expect to find it in the context menu together with the other options (Delete Note, Clone Note etc.) or to directly edit the name when I double click onto it.

# Environment

- Version : 0.11.17
- OS Version and name : Arch Linux

**Comment by ZeroX-DG** [comment]
Well, by default the title of the note is the first line or heading. If you enable the option "Extract title from front matter", you can have a custom title by specifying it in the front matter:
```
---
title: Your custom title
---
```
