### ISSUE TITLE
Update to Electron 5, 6, or 7

### ISSUE THREAD

**Issue by Redsandro** [BoostIO/Boostnote#3122]
# Current behavior

When clicking around in the Boostnote 0.11.17 Interface Settings and trying to change the theme, Linux 5.2 will freeze. No error message. No kernel panic. Just frozen. Sysrequests don't work anymore.

__I have reverted to the older 0.11.7 and the issue is gone.__

# Steps to reproduce

0. use AMD "Picasso" APU hardware
1. go to preferences > interface
2. browse around, mess with interface theme and editor theme
3. after a few minutes, observe freeze

# Environment

- Boostnote 0.11.17
- Linux Mint 19.1 Cinnamon x64
- Linux 5.2.0-050200rc7-generic
- AMD Ryzen 5 3400G with Radeon Vega Graphics
- AMD RAVEN (DRM 3.32.0, 5.2.0-050200rc7-generic, LLVM 8.0.0) (0x15d8) 19.0.2
- OpenGL 4.5 (Compatibility Profile) Mesa 19.0.2
- OpenGL shading language 4.50
- OpenGL ES 3.2 Mesa 19.0.2
- OpenGL ES GLSL ES 3.20

# Other comments

Hardware is relatively new. Not sure if this is something related to some Boostnote programming, or an Electron issue. Where can I see the electron version? Curious to know what is the Electron version for both 0.11.7 and 0.11.17.

**Comment by ZeroX-DG** [comment]
For 0.11.7 the electron version is `2.0.3` and for 0.11.17 is `3.0.8` I think. Based on the commits that I found.

**Comment by Redsandro** [comment]
Major version upgrade makes the synopsis plausible. Do you know of any simple 3.0.8 electron app I can test to see if it also crashes?

**Comment by Flexo013** [comment]
@Redsandro  Is this still happening with 0.12.1?

**Comment by Redsandro** [comment]
@Flexo013 0.12.1 crashes too. Usually when I click the Interface Settings > Editor Theme popup.
I reinstalled 0.11.7.

**Comment by Redsandro** [comment]
https://github.com/BoostIO/Boostnote/pull/2603/commits/1388e7d7f478102fc98dce303cbed883b06ff9bd

**Comment by daiyam** [comment]
@Redsandro, can you try to update the electron version to v3.1.13?

**Comment by Flexo013** [comment]
@Redsandro Thanks a bunch for all the helpful info!

**Comment by Redsandro** [comment]
@daiyam is there an app that already uses 3.1.13? I've tried 3.1.10 (which crashes) but I don't have too much time to do this manually. (I'm not so good with this.)

I believe all Electron versions above 3.0.3 and below 4 crash. Although this is indeed an upstream issue, it seems to be fixed in the next major release branch. I wonder if there are any major things stopping us from updating to Electron 4.2.7.

**Comment by Redsandro** [comment]
This is fixed upstream in `4.2.7`. Can Boostnote upgrade Electron to 4?

**Comment by Flexo013** [comment]
@Rokt33r is this possible?

**Comment by Redsandro** [comment]
Electron 7 was just released. :heart: 

https://electronjs.org/blog/electron-7-0

Anyway, small reminder that Boostnote is incompatible with Picasso hardware and we need to use Electron 4.2.7+. Until that time, Linux Picasso users will experience computer crashes when using Boostnote.

**Comment by Flexo013** [comment]
While I agree that this issue is important to solve it's lower on the priority list as there are other issues that affect more users.

I don't know exactly what all is involved in upgrading the Electron version, but since the project is open source you can give it a go @Redsandro

**Comment by Redsandro** [comment]
@Flexo013 I've done commits on the server and the react client of the Boostnote Electron app in the past. I have no experience with Electron itself though, and I don't feel confident taking on something like the entire scaffolding of the app. I was hoping someone with Electron experience and a better overview of dependencies in this project would just fly over this in an hour. :angel: 

I apologize if I sounded a bit frustrated before. It's just that I've committed PRs in the past to improve this software, and now there's something blocking me from using it but it's beyond my skill level to fix it. After committing I have an emotional connection to Boostnote and I find it difficult to use Joplin, even though it's rather similar.

**Comment by Flexo013** [comment]
@Redsandro That's completely understandable. Thanks for your message. 

I have contact @Rokt33r about this issue directly. Hopefully this is something that we can pick up fairly fast.

**Comment by Rokt33r** [comment]
@Rokt33r @Redsandro Sorry I had completely forgotten  about this. I'll do it tonight.

**Comment by Redsandro** [comment]
Received this on the [upstream issue](https://github.com/electron/electron/issues/19269#issuecomment-546921436):

> Electron 3 and 4 are not supported anymore, so there is nothing to back-port.

I would be happy just to get Boostnote working (with Electron 4.2.7+), but judging from the above comment, it would be beneficial to upgrade to a supported version, which is 5, 6 or 7.

**Comment by Rokt33r** [comment]
I'm going to use v4 for v0.14.0. But I'll try to upgrade v6 again for v0.15.0.

**Comment by Redsandro** [comment]
https://github.com/BoostIO/Boostnote/pull/3322

Was it really that simple? :sweat_smile: 

Looking forward to the 0.14 release. :muscle:

**Comment by Redsandro** [comment]
@Rokt33r can we get a release out?

**Comment by Flexo013** [comment]
I imagine that this will take some time, since there are a few PRs that are ready for a last check from Rokt33r. Once those are in I see no reason to delay a release any further.

My best guess would be that we will have a release by the end of the week.

**Comment by Redsandro** [comment]
@Rokt33r can we please get one more release with Electron 4 before you focus on Boostnote Next?

E.g. 0.13.1

**Comment by Flexo013** [comment]
Will be fixed as of 0.14.0

**Comment by Redsandro** [comment]
Great, this version works without crashing on Picasso hardware. :+1: 

https://github.com/BoostIO/boost-releases/releases/tag/v0.14.0
