### ISSUE TITLE
PDF code block blurry for colour scheme

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3128]
# Current behavior

PDF output is blurry when using the colour theme `lesser dark` for preview. 

![image](https://user-images.githubusercontent.com/44707562/61468083-9f92a880-a974-11e9-8865-8cb1fe60e88e.png)

# Expected behavior

clear and readable text output. 

# Steps to reproduce

1. Preferences -> Interface / Code Block Theme: 'lesser dark'
2. create new markdown note with code block
3. print file to PDF

# Environment

- Version : 0.11.12
- OS Version and name : 16.04 Ubuntu

**Comment by Flexo013** [comment]
Can't reproduce this using 0.12.1. @arcturus140 Can you?

**Comment by arcturus140** [comment]
@Flexo013 Initially I wrote the issue applies to 0.11.12 and 0.11.17. 
It appears that it only applies to 0.11.12 so I edited the issue, my bad.

I noticed now that 0.11.17+ don't have syntax highlighting. #3125 only complains about background colour. From the images shown there it is not appearant if syntax highlights or not.

Here is a direct comparisson of PDF exports between boostnote version 0.11.12 and 0.12.1:

[#3128_0.11.12_0.pdf](https://github.com/BoostIO/Boostnote/files/3446693/3128_0.11.12_0.pdf)
[#3128_0.11.12_1.pdf](https://github.com/BoostIO/Boostnote/files/3446694/3128_0.11.12_1.pdf)
[#3128_0.12.0_0.pdf](https://github.com/BoostIO/Boostnote/files/3446695/3128_0.12.0_0.pdf)
[#3128_0.12.0_1.pdf](https://github.com/BoostIO/Boostnote/files/3446696/3128_0.12.0_1.pdf)

In boostnote 0.11.12 syntax highlighting works for all themes I've seen so far but `lesser dark`. It has no background colour. My comment here: https://github.com/BoostIO/Boostnote/issues/3125#issuecomment-512846031 was referring to this behaviour. 

Later version of boostnote do not have syntax colouring nor background colour for code blocks. 

I suggest to close this issue and add syntax highlighting to this improvement request: #3125

I am sorry for the mess.

**Comment by Flexo013** [comment]
Thanks for the detailed information. Don't worry too much about the mess. The issue tracker here has been quite a mess anyway, which I'm working on fixing 😉 

Adding this to the other issue sounds good to me.
