### ISSUE TITLE
icon on Mac take up full height of menubar

### ISSUE THREAD

**Issue by chantlong** [BoostIO/Boostnote#313]
Thank you for creating Boostnote.

The current Boost Note icon on the Mac OS top menu bar (not the dock icon) is too big. 
It takes up the full height of the menu bar. From an aesthetic point of view, can you please make the icon smaller so it does not take the full height of the menu bar. Currently it looks big relative to the other icons in the menu bar.

A black and white icon would be nice too!

**Comment by asmsuechan** [comment]
Hi @chantlong, please paste the screen shot.

In my environment, it's displayed like this below.
<img width="193" alt="screen shot 2017-03-08 at 15 01 05" src="https://cloud.githubusercontent.com/assets/11307908/23692111/1d6b1312-0410-11e7-88b1-861ebe04c3a6.png">

Is it same? If so, I don't think it's too big.

**Comment by chantlong** [comment]
<img width="404" alt="screen shot 2017-03-08 at 5 08 24 pm" src="https://cloud.githubusercontent.com/assets/17346712/23695351/0d57ceae-0422-11e7-84e6-12ccab58eba1.png">
It's the same, but if you look at your other icons, there is more gray space above and below the icon for more breathing room.

**Comment by asmsuechan** [comment]
@chantlong, I see. I'll try to decrease the size if you want.

**Comment by asmsuechan** [comment]
Hi @chantlong, is it attractive?
<img width="169" alt="screen shot 2017-03-15 at 13 42 38" src="https://cloud.githubusercontent.com/assets/11307908/23973741/be6c6796-0994-11e7-9de2-108b73b085b8.png">

**Comment by chantlong** [comment]
@asmsuechan @kazup01 ありがとうございます！ The smaller one definitely looks better. I like the grayscale version too. It blends in nicely with the other icons.

**Comment by kazup01** [comment]
Wow! どういたしまして（You are welcome）🙌 We'll update tomorrow!

**Comment by kazup01** [comment]
Thank you for your cooperation @chantlong san!
