### ISSUE TITLE
Could I get a release in which the "export pdf" is good to use ? 

### ISSUE THREAD

**Issue by Yablon** [BoostIO/Boostnote#3130]
I love boostnote and I use it in my daily recordings. I recommend it to my friends and some of them like it too. Thank you for your efforts.
I also use boostnote to write some unofficial documents to share with my partners, so the "export pdf" is needed. I use other tools to generate pdfs before, but I really hope that I can do that directly in boostnote. 

I know the [export pdf](https://github.com/BoostIO/Boostnote/pull/3048) was fixed, but could I ask that when could I get a release that has the "export pdf" fixed ?
I don't know if it is polite to ask for a release to use, you can also tell me how to compile one by myself.
I can understand that you have your own plans and road map. Thank you for the time you spend to read this.

**Comment by Flexo013** [comment]
This is now released.
