### ISSUE TITLE
new tab

### ISSUE THREAD

**Issue by DePaTech** [BoostIO/Boostnote#314]
I had multiple tabs in a note. When I deleted the second tab, the content of the tabs at the right shifted-i.e., the third tab had the content of the second tab, and the fourth tab had the content of the third tab...!

**Comment by kazup01** [comment]
Oops this is an error. Sorry for inconvinience. 
Even if you delete the tab, data remains because of #201'bug.

**Comment by asmsuechan** [comment]
Hi there. It's as same as https://github.com/BoostIO/Boostnote/issues/288, not https://github.com/BoostIO/Boostnote/issues/201.
