### ISSUE TITLE
Styling of Storage tab in Preferences broken

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#3143]
# Current behavior

Storage tab in preferences isn't displayed properly after updating to 0.12.0 (from 0.11.15).
![image](https://user-images.githubusercontent.com/4507015/61782156-def24680-ae05-11e9-9137-1dc92700630d.png)

# Expected behavior

The styling should work.

# Steps to reproduce

1. Open the preferences.
2. (Select the storage tab if needed.)

# Environment

- Version : 0.12.0
- OS Version and name : Windows 10

**Comment by themattgabriel** [comment]
![screenshot](https://user-images.githubusercontent.com/51425211/61912570-5c45b600-aeef-11e9-8b78-d3050da0785d.png)

# Environment

- Boostnote Version: 0.12.0
- OS: Windows 10
- Version: 1903

**Comment by Rokt33r** [comment]
Fixed by https://github.com/BoostIO/Boostnote/pull/3165
<img width="724" alt="Screen Shot 2019-07-26 at 11 49 20" src="https://user-images.githubusercontent.com/5865853/61922461-7e950d80-af9b-11e9-8453-bb59ea5930a2.png">
