### ISSUE TITLE
Note editor doesn't wrap long lines in markdown

### ISSUE THREAD

**Issue by sriharshachilakapati** [BoostIO/Boostnote#3145]
Text is not wrapped in markdown note editor. Happening in 0.12. How to enable wrapping of text?

**Comment by Flexo013** [comment]
Confirmed. I highly suspect something went wrong in #3063 that has affected the line wrapping of markdown notes.

@sriharshachilakapati Currently there is no way to turn it back on, sorry. You will either have to downgrade to a previous version or wait for the next release which will hopefully contain a patch for this bug.

**Comment by amedora** [comment]
sorry for the inconvenience. I hope #3150 will fix the problem.

**Comment by Rokt33r** [comment]
#3150 has been merged!
