### ISSUE TITLE
Markdown lint not working

### ISSUE THREAD

**Issue by judsoniv** [BoostIO/Boostnote#3147]
# Current behavior

Beginning in v0.12.0, the Markdown lint feature no longer works.

The configurations are still present, as is the configuration-options box introduced in the previous release. However, making a syntax error in your markdown to longer results in a "warning" marker in the margin.

I've attempted toggling the feature, turning on line numbers, etc., to no avail.

# Expected behavior

Return to the previous behavior. Making a syntax error in your markdown should result in an interface warning, unless turned off in your configuration settings.

# Steps to reproduce

1. Turn on linting 
2. Make a mistake, such as starting your document with an H2 rather than an H1
3. Be saddened by the lack of a lint warning

# Environment

- Version : 0.12.0
- OS Version and name : Mac OS 10.14.5

**Comment by Flexo013** [comment]
Confirmed this issue on Windows 10.

**Comment by Flexo013** [comment]
Confirmed for 0.12.1

**Comment by Flexo013** [comment]
@roottool Could you look into this, since you were the one who added the feature?

**Comment by ZeroX-DG** [comment]
Fixed: https://github.com/BoostIO/Boostnote/pull/3285
