### ISSUE TITLE
pasted IMG src with non existing path continue to reload

### ISSUE THREAD

**Issue by simiula** [BoostIO/Boostnote#315]
I pasted this as Memo for a project..
<img src="your.svg" onerror="this.src='your.png'">
Go in loop! continue to reload the page!

**Comment by asmsuechan** [comment]
Hi @simiula, thank you for your reporting. Could you paste a screenshot?

**Comment by asmsuechan** [comment]
What's going on @simiula?

**Comment by VoLuong** [comment]
@simiula Please provide a good screenshot. Noone can help you if you don't provide enough information on what's going on.

**Comment by asmsuechan** [comment]
@simiula I'll close this issue within three days if you won't reply.
