### ISSUE TITLE
Some editor themes do not work

### ISSUE THREAD

**Issue by brennaveen** [BoostIO/Boostnote#3151]
# Current behavior

Solarized dark editor theme displayed with no background color or syntax highlighting.

![Annotation 2019-07-24 221615](https://user-images.githubusercontent.com/10182193/61843289-bd727880-ae60-11e9-9377-39ecb896c602.jpg)

![Annotation 2019-07-24 221723](https://user-images.githubusercontent.com/10182193/61843335-d7ac5680-ae60-11e9-8516-8966e9622ae9.jpg)

# Expected behavior

Theme works as it did before update.  Sorry I don't have a screenshot from the previous version.

# Steps to reproduce

1. Update editor to Version 0.12.0
2. Select Solarized Dark editor theme

# Environment

- Version : 0.12.0
- OS Version and name : Windows 10 Version 1809 (OS Build 17763.615)

**Comment by Flexo013** [comment]
I have checked all editor themes and the following do not work in version 0.12.0:
- `ambiance-mobile`
- `solarized dark`
- `solarized light`

**Comment by Rokt33r** [comment]
It seems to be fixed now in master branch. I'm going to release v0.12.1 today or tomorrow!

**Comment by Rokt33r** [comment]
Sorry, it isn't working in Windows only. I'll investigate it.

**Comment by Rokt33r** [comment]
Fixed! Will be shipped today or tomorrow!!
