### ISSUE TITLE
Code block containing grep pattern blanks out window

### ISSUE THREAD

**Issue by invad0r** [BoostIO/Boostnote#3155]
# Current behavior
I have a shell code block with a grep regex expression:

    ```sh
    grep "^[]"
    ```
adding another code-block above grep will blank window:

    ```sh
    ```sh
    ```
    grep "^[]"
    ```

[screenshots](https://imgur.com/a/9uxtDYx)

# Expected behavior

Should just display

    ```sh
    ```sh
    ```
    grep "^[]"
    ```

# Steps to reproduce

1.  create code-block
2. add `grep "^[]"` in code block 
3.  insert another codeblock above `grep` line
=> blank window

# Environment

- Version : Version 0.12.0 (0.12.0)
- OS Version and name : macOS High Sierra 10.13.6

**Comment by Flexo013** [comment]
Confirmed on Windows 10. Pasting the second snippet just kills the entire UI/app.

**Comment by Rokt33r** [comment]
https://github.com/BoostIO/Boostnote/pull/3149/files is fixing this problem. It will be shipped tomorrow.
