### ISSUE TITLE
Clicking tags does not switch to the tags in sidebar

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#3157]
# Current behavior

Nothing happens when clicking a tag of a note.

# Expected behavior

Clicking a tag should take you to the tag filtering sidebar. (As listed in this issue #3156.)

# Steps to reproduce

1. Add a tag to a note
2. Press <kbd>Enter</kbd>
3. Click the tag

# Environment

- Version : 0.12.0
- OS Version and name : Windows 10

**Comment by arcturus140** [comment]
this is working in 0.12.0, can be closed

**Comment by Flexo013** [comment]
On my Windows 10 machine it does not work for 0.12.0.

@arcturus140 What OS are you using?

**Comment by arcturus140** [comment]
Linux Ubuntu

**Comment by incace** [comment]
Does not work for me in 0.12.1-1 on Mac.

**Comment by arcturus140** [comment]
Does not work in 0.12.1 on Linux Ubuntu.

**Comment by Flexo013** [comment]
Fixed in the next release.
