### ISSUE TITLE
Boostnote blanking with "href" in an element

### ISSUE THREAD

**Issue by EnglicGud** [BoostIO/Boostnote#3159]
# Current behavior

The problem is that Boostnote blanks the window if this is typed into a note  (except the menu at the top):

`<a href><`
or this
`<a href></a>`

(`href `without `=""`)

As long as href is in the element it will cause Boostnote to blank the window. 

For now, I got around it by going into the file and changing `href` to `href=""` and clicking wildly, when it's starting, where another note should be listed (at the left side).

# Expected behavior
Typing `<a href><` without an `=""` shouldn't blank Boostnote.

# Steps to reproduce

1.  Make a new note.
2.  write `<a href><`

# Environment

- Version : 0.12.0
- OS Version and name : Windows_NT x64 10.0.17134

**Comment by Flexo013** [comment]
Confirmed for 0.12.1 on Window 10.
