### ISSUE TITLE
Sorting selected lines

### ISSUE THREAD

**Issue by themattgabriel** [BoostIO/Boostnote#3160]
# Current behavior

unable to sort lines in editor

# Expected behavior

- sort lines using a keyboard shortcut or by clicking on the *File* menu
- sort lines in ascending/descending order

# Steps to reproduce

1. Highlight text that are in different lines.
2. Sort lines by:
    - pressing a keyboard shortcut (e.g., F9)
    - going to *File* in the menu bar and hovering over *Sort Lines* and a menu appears with the  option to select whether to sort lines in ascending/descending order

# Environment

- OS: Windows 10
- Version: 1903
- Build: 18362

**Comment by Olcod** [comment]
Gave this issue a go.
Please let me know what do you think?

**Comment by Flexo013** [comment]
Feature is available as off 0.13.0
