### ISSUE TITLE
Clicking on Check boxes and footnotes take you back to the very top of the note

### ISSUE THREAD

**Issue by themattgabriel** [BoostIO/Boostnote#3163]
# Current behavior

## Checkbox

- While in preview mode, checking/unchecking items takes you back to the beginning of the note

![Boostnote 2019-07-25 15-39-49](https://user-images.githubusercontent.com/51425211/61913901-78e3ed00-aef3-11e9-83d4-29c3a1cec03f.gif)

### Console Output
![Annotation 2019-07-25 155246](https://user-images.githubusercontent.com/51425211/61914110-44246580-aef4-11e9-9fe0-389b3c020275.png)

## Footnote

- While in preview mode, clicking on a footnote's "return to context" takes you back to the beginning of the note

![Boostnote 2019-07-25 15-56-03](https://user-images.githubusercontent.com/51425211/61914349-29062580-aef5-11e9-95d1-f0c6c396ab4c.gif)

### Console Output

none

# Expected behavior

- When checking/unchecking items in a checkbox, the note should stay in place and only the movement of the progress bar is expected.
- After viewing a footnote, clicking on "return" should take you back to the context rather than to the beginning of the note.

# Steps to reproduce

**Checkboxes**

1. Open a note. 
2. Add some long place holder text to add some volume to the note.
3. Do:

    ```md
    - [ ] Item 1
    - [ ] Item 2
    ```

4. Toggle preview mode.
5. Check/uncheck items.

**Footnotes**

1. Open a note.
2. Add some long place holder text to add some volume to the note.
3. Do:

    ```md
    Here's a simple footnote [^1], and and longer one [^note].
    [^1]: simple footnote
    [^note]: complex footnote with multiple paragraphs.
    Indent paragraphs to include them in the footnote.
    
    ```shell
    echo "Hello, World!"
    ```

4. Toggle preview mode.
5. Click on the footnote `[1]` link.
6. After viewing the footnote, click on `↩︎`.

# Environment

- Boostnote: 0.12.0
- OS: Windows 10
- Build: 1903

**Comment by hikerpig** [comment]
I've created a PR (check the timeline above) to fix the checkbox issue.

But footnotes are caused by a completely different reason. May need a little bit more investigating.

**Comment by beneccles** [comment]
I'm experiencing the same issue as #3163, except on Mac OS Mojave. There is a brief pause when I click, then the page re-renders, going back to the top of the page rather than where I was on the page. This happens both with the render page toggled full screen, as well as when I use the edit and rendered screen side-by-side.

**Comment by Flexo013** [comment]
I highly expect this to be fixed in the next release, which should be soon. Once 0.13 is released could you test if the issue persists? And if it does then feel free to reopen this issue.
