### ISSUE TITLE
Chinese characters are not highlighted by search queries

### ISSUE THREAD

**Issue by ThaddeusJiang** [BoostIO/Boostnote#3164]
# Current behavior

can't highlight search word(Chinese)
[![Screenshot from Gyazo](https://gyazo.com/e155c4e4810aeb98703598093f7a8108/raw)](https://gyazo.com/e155c4e4810aeb98703598093f7a8108)

# Expected behavior
The same as the English word.

[![Screenshot from Gyazo](https://gyazo.com/3d901ce156d9650b58d01d13a13dee9d/raw)](https://gyazo.com/3d901ce156d9650b58d01d13a13dee9d)

# Steps to reproduce

1. focus search input
2. type or copy "测试" in that

# Environment

- Version : 0.12
- OS Version and name : MacOS 10.14

**Comment by hikerpig** [comment]
Something seems went wrong with 0.12.0,  maybe you should try [v0.12.1-1](https://github.com/BoostIO/boost-releases/releases/tag/v0.12.1-1)

**Comment by Flexo013** [comment]
Added the `needs investigation` label to check if this is still present in 0.12.1, when it is fully released.

**Comment by Flexo013** [comment]
Confirmed to still be present in 0.12.1 on Windows 10
