### ISSUE TITLE
Add class to generated TOC <ul>

### ISSUE THREAD

**Issue by incace** [BoostIO/Boostnote#3172]
This was brought up a while back, but the issue was closed so here's a new request. It would be really easy just to add a class to the generated UL that way we could control it in preview mode with the custom CSS box on the interface settings. I was looking to create a fixed/floating TOC via CSS with this method but there is no way to target the TOC without breaking some other styling. You can try and select it via nth-child but that changes per document depending on where the TOC is within the flow.

A kindof "hack" to this would be to always put your TOC before any other UL elements in the document flow, then target it with `body > ul:first-of-type`. The bummer with this is it is prone to break when moving around the TOC or with files that have no TOC.

**Comment by incace** [comment]
Basic duplicate of #2525

**Comment by incace** [comment]
Here's an example of an implementation I mocked up in the last few hours:

![Boostnote-floatingTOC-optimized](https://user-images.githubusercontent.com/61343/61990965-18de6b00-b007-11e9-83ea-bde7b90647d4.gif)

**Comment by Flexo013** [comment]
I really love this suggestion of having a separate TOC box like that.

@incace Would you be willing to provide your work as a PR, and then we move from there?

**Comment by incace** [comment]
@Flexo013 sure, but I want to clean it up a bit first. I probably won't be able to get back to this until end of next week. I'll see if I can work out a global style that matches each theme, otherwise I'll just do separates.

Also, for reference I've only added the CSS to the custom CSS box within the Interface settings and haven't messed with any core files. If this would be pushed into a release at some point, where would the CSS need to be added?

**Comment by Flexo013** [comment]
@incace There's no rush with making the PR, take your time 😄 

As for the location, I'm not quite sure about that. Once you submit a PR the reviewer can point you to the right location.

**Comment by Flexo013** [comment]
@incace How is the TOC with custom CSS box coming along?

**Comment by incace** [comment]
@Flexo013 I got it to a point and had to leave it due to other things coming up. I will look into it this week again if possible.

**Comment by Flexo013** [comment]
Somebody else is working on similar functionality in #3352.

**Comment by Flexo013** [comment]
This feature is present as of 0.15.0
