### ISSUE TITLE
Can not drag one note to another note folder

### ISSUE THREAD

**Issue by zzxxhhzxh** [BoostIO/Boostnote#3174]
# Current behavior
Can not move a note to another note folder by  dragging it. But in previous version it's fine. And there is not a option for moving notes in left click menu.

# Expected behavior
Can move a note to another note folder by  dragging.

# Steps to reproduce
Choose a note and drag it.

# Environment

- Version : 0.12.1
- OS Version and name : Windows 10 pro 64bit 1903

**Comment by alex-moreno** [comment]
same here, I was using that functionality a lot and suddenly this has disappeared in latest update

**Comment by AWolf81** [comment]
Thanks for reporting the issue.

I'll fix it. It's related to CSS styles in `MarkdownNoteDetail.styl` (last styles with `user-drag: none`) that accidentally disabled dragging.

I think that styles should have a more specific selector to apply only to the buttons / icons in the Note details.

**Comment by alex-moreno** [comment]
I also discovered that on the meantime you can select which folder you want the note just clicking on the top of the note, just next to tags.

Thanks for the awesome work on this :-)

**Comment by gerroon** [comment]
I have this under 0.12.1 on Linux as well

**Comment by Flexo013** [comment]
This will be fixed in the next release.
