### ISSUE TITLE
Real Time Md Preview

### ISSUE THREAD

**Issue by varad6771** [BoostIO/Boostnote#3176]
# Current behavior
A right side pane displays the Preview of markdown content in the left pane. 
Instead, if the live previews could be generated in the same (writing) pane (left one), IMHO it would be far more intuitive, for newbies and pros alike. That is not to suggest the removal of current side pane, it is immensely useful in many cases. But just an optional feature, if feasible.     

# Expected behavior
For reference behavior, please check out [Typora](https://typora.io./).
The writing pane automatically converts the Md tags to their relevant implementation after completion (closure) of that tag, all while we are writing the document.

**Comment by Flexo013** [comment]
Nice suggestion! You can find the original suggestion here #2927
