### ISSUE TITLE
Exporting to PDF contains opportunities for XSS attacks

### ISSUE THREAD

**Issue by v5pingan** [BoostIO/Boostnote#3178]
# Current behavior

Notes Exported to PDF Format Is Existing XSS Attacks.

# Expected behavior

Notes Exported to PDF Format Is Existing XSS Attacks.

When there is a code in the note:

\``` JavaScript
% 3Cscript%3Ealert('XSS')%3C/script%3E
\``` 

XSS attacks are triggered when the export PDF function is reused.
![xss-payload1.png](https://i.loli.net/2019/07/28/5d3dacfe8b00798461.png)

# Steps to reproduce

#### 1. Put the payload below into your notes.

- Payload:
\``` JavaScript
% 3Cscript%3Ealert('XSS')%3C/script%3E
\``` 

 I cut a picture:
![xss-payload.png](https://i.loli.net/2019/07/28/5d3daae59837570430.png)

#### 3. Here is a demo video:
https://github.com/v5pingan/github.so/blob/master/bootsnote/boostnote-xss-20190728.mp4

# Environment

- Version : 0.12.1
- OS Version and name : Microsoft Windows 10 Home Chinese Version

**Comment by Flexo013** [comment]
Will be fixed in 0.13.0
