### ISSUE TITLE
Searching for the word "tags" results in an empty window.

### ISSUE THREAD

**Issue by lvets** [BoostIO/Boostnote#3183]
# Current behavior

Searching for the word "tags" results in an empty window. I have to restart Boostnote to get my main window back.

# Expected behavior

Search for "tags", not clear my whole window :)

# Steps to reproduce

1. Type "tags" in the search box.

# Environment

- Version : 0.12.1
- OS Version and name : Windows 10

**Comment by hikerpig** [comment]
This is indeed a bug, I've created a PR to fix.

For now, I will suggest you use uppercase `TAGS` for searching.
