### ISSUE TITLE
Deleting characters in the middle of the search bar text does not work properly.

### ISSUE THREAD

**Issue by imaojun** [BoostIO/Boostnote#3188]
# Current behavior
Delete the character in the middle of the search bar text and the cursor will move to the end.

# Expected behavior
let cursor don't automatically jump to the end when deleting text

**as the gif shows**：
![Peek 2019-07-31 14-22](https://user-images.githubusercontent.com/28778042/62188364-b2f33a00-b39e-11e9-85cf-da9648add023.gif)

# Steps to reproduce

Search for **boostnote** in the search bar and try to move the cursor to the end of **boost**, then delete **t, s, o, o, b** in turn. When you deleted **t**, the cursor has jumped to the end.

# Environment

- Version :Boostnote 0.11.17
- OS Version and name :Archlinux

**Comment by Flexo013** [comment]
This bug no longer occurs when using 0.12.1 on Windows 10.

@imaojun Can you confirm that this is fixed int he latest release?

**Comment by imaojun** [comment]
@Flexo013   updated to version 0.12.1.
COOOOOL！Fixed search bar cursor problem and can search in Chinese! awesome!
