### ISSUE TITLE
Switch to Preview does not switch back to editor

### ISSUE THREAD

**Issue by ebal** [BoostIO/Boostnote#3189]
#2997 Current behavior

In previous versions like app-0.11.17 it was possible to switch from editor to preview by using right click.

From  v0.12.0 to v0.12.1 you can switch from editor to preview,
but now you can not switch back to editor !!

# Expected behavior

Using Right Click to switch between editor - preview and vice-verse (as it was working back in 0.11.17

# Steps to reproduce

Please review attached screenshots

![image](https://user-images.githubusercontent.com/3049624/62196351-86cbbf00-b386-11e9-8b8f-94320ba387d7.png)

![image](https://user-images.githubusercontent.com/3049624/62196362-8af7dc80-b386-11e9-83d4-44aa284e1e43.png)

# Environment

- Version : v0.12.1
- OS Version and name : Win10 - 1903

Thank you in advance,
best regards

-ebal

PS:  Is there a way to disable auto-update? Perhaps through an option in preferences.

**Comment by ebal** [comment]
by pure luck a minute ago,
 I've found that switching back to editor from preview is:
 `ctrl+left click`

So it this the correct behavior? 

- Editor Mode: Right Click  to Preview 
- Preview Mode: ctrl+Left Click to Editor

**Comment by RonWalker22** [comment]
Right click should toggle from editor mode to preview mode. You can discuss the bug here #3144.

I have a fix awaiting  feedback #3186.

**Comment by Flexo013** [comment]
Thanks for reporting the issue.

This a known issue: #3144
