### ISSUE TITLE
How to install to specific Folder Location? How to verify?

### ISSUE THREAD

**Issue by CyberLustHD** [BoostIO/Boostnote#3198]
Label: Question; Help Wanted;

I want to try out boostnote. I downloaded the file into my downloads folder and then ran it to install boostnote. The problem I had is that it did not ask where to install boostnote. It installed in my programs files so I uninstalled boostnote hoping that I could find an answer where I can install boostnote into a specific folder. I would like to install boostnote into a specific folder I made called Apps. How can I do this?

Lastly, how can i verify this boostnote and not a dangerous/intercepted one? fingerprint? sig? SHA?

OS for boostnote: Windows10

**Comment by Flexo013** [comment]
Thanks for your interest in Boostnote!

Currently there is no way to select the installation directory of Boostnote. This is a planned feature, as requested here: #2350

Currently there is no fingerprint, signature or SHA hash for verification. This is a planned feature, as requested here: #387 

I'm sorry that these features don't exist yet, but such is the nature of OSS. If you would like to incentivize contributors to pick up either of these feature requests, then consider funding them on IssueHunt. That way they are more likely to be picked up.

Does that answer all your questions?

**Comment by CyberLustHD** [comment]
Yes. Thanks for the reply! I subscribed to those two posts and am eagerly waiting for the feature! 😄 
but how to do this part of 

> If you would like to incentivize contributors to pick up either of these feature requests, then consider funding them on IssueHunt. That way they are more likely to be picked up.

or rather, i don't understand that part. sorry.

**Comment by Flexo013** [comment]
On IssueHunt you can add funding/bounties to GitHub issues. When the feature described in the issue is completed, the funding is rewarded to the developer who implemented it.

You can check out the IssueHunt by clicking the Sponsor button at the top.

Here are the IssueHunt links:
https://issuehunt.io/r/BoostIO/Boostnote/issues/387
https://issuehunt.io/r/BoostIO/Boostnote/issues/2350
