### ISSUE TITLE
Search doesn't work?

### ISSUE THREAD

**Issue by DanielSundberg** [BoostIO/Boostnote#320]
I have the following window with some text:

![image](https://cloud.githubusercontent.com/assets/1454200/23852063/4e375c1a-07e6-11e7-9ea8-4c003ab09384.png)

Opening search:
![image](https://cloud.githubusercontent.com/assets/1454200/23852041/3c7875fe-07e6-11e7-8436-b46102695441.png)

Typing some text that should be found, nothing is found???
![image](https://cloud.githubusercontent.com/assets/1454200/23852080/69041150-07e6-11e7-9b83-5586e4bbc611.png)

Using Windows 10. Have tried with "only snippets" and "only markdown" checked and unchecked. Just downloaded the installer a few minutes ago. Not a good experience for a new user.

**Comment by asmsuechan** [comment]
Hi @DanielSundberg, that search modal was created for searching snippets, it means you need to use this (below) if you'd like to search for the content of notes by a word.

<img width="325" alt="screen shot 2017-03-13 at 14 28 22" src="https://cloud.githubusercontent.com/assets/11307908/23876188/6eaf706e-07f9-11e7-8522-be104ba0aafc.png">

Actually, there is a shortcut for `Focus Search` by `Ctrl-s` on the main window.

**Comment by DanielSundberg** [comment]
Ok, that explains a lot.

**Comment by smprather** [comment]
I got here via Google search with the same question. Not very intuitive.
