### ISSUE TITLE
Feature Request: Task / Todo List - Overview

### ISSUE THREAD

**Issue by n3x77** [BoostIO/Boostnote#3220]
# Current behavior

If TODO-Lists are created within a project folder the progress is shown on top of the single note. 

# Expected behavior

It would be great to get a better overview of current tasks if we could link all todo-Items from a note in one Overview Todo list. 
To improve this it would be very cool if a task is done in one of the notes the general overview task list will also update or vice versa.

**Comment by Flexo013** [comment]
Duplicate of #1208
