### ISSUE TITLE
[Idea] A possible idea

### ISSUE THREAD

**Issue by gjae** [BoostIO/Boostnote#3221]
## Hello, first of all I must say that I love this application !.

I was thinking about the possibility of writing a client-server version where the application can be synchronized with a web service as evernote does, that would give the possibility of integrating it into a mobile app, which I would like to join the project to be like this maybe with react -native since the main application is based on electronjs + reactjs
:smiley:

**Comment by Flexo013** [comment]
Thanks for the kind words! :smile: 

The idea of implementing a method to support syncing has been around for a while. You can find more about that on the issues #827 and #1250. You can also search the GitHub issues for 'sync' or 'cloud' and you should find some threads to continue on and help out with.

If you would like to discuss more details, then I highly encourage you to join [our slack](https://join.slack.com/t/boostnote-group/shared_invite/enQtMzkxOTk4ODkyNzc0LThkNmMzY2VlZjVhYTNiYjE5YjQyZGVjNTJlYTY1OGMyZTFjNGU5YTUyYjUzOWZhYTU4OTVlNDYyNDFjYWMzNDM). There you can find active discussions and updates on development, especially for mobile.
