### ISSUE TITLE
Anonymous notes

### ISSUE THREAD

**Issue by lucmski** [BoostIO/Boostnote#3224]
Hi guys,

Hope you are all well !

Was just wonderint if the storage of notes can be in memory and cyphered at the same time.

Cheers,
L.

**Comment by Flexo013** [comment]
If you use something like BitLocker then all files on that drive will be encrypted and usable at the same time.

There is no way to decrypt just the Boostnote files and still have them be used at the moment. There is a feature request for this that you could check out and fund if you would really like this feature: #827
