### ISSUE TITLE
Export diagrams in PDF and HTML

### ISSUE THREAD

**Issue by nlsn** [BoostIO/Boostnote#3229]
# Current behavior
Diagram types added for #771 are visible in Boostnote, but when exporting HTML or PDF the diagrams are not rendered.

# Expected behavior
The plantuml, mermaid, and other diagram types should be rendered and included in the HTML and PDF exported files.

# Steps to reproduce
1. Type up any diagram description until it appears correctly in the preview.
2. File > Export as > HTML|PDF
3. View the HTML or PDF file in a separate application.

# Environment

- Version : 0.12.1
- OS Version and name : macOS 10.14.6

**Comment by Flexo013** [comment]
Will be fixed as of 0.14.0
