### ISSUE TITLE
Comment in python turns into note's name 

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#323]
Hi, Boostnote team.

I am using **Boostnote 0.8.6** on **Windows**. 

Recently I encounter a problem that I believe happens on all platform and has never been in this issue section. So far, the problem was not so critical but it is annoying and I cannot find any reference or documentation on how to fix it myself.

**Commenting in python turns into the note's name**. It seems like the application misread this with a h1 in markdown. (although I did use the code block in markdown)

.

![image](https://cloud.githubusercontent.com/assets/15828926/23999274/6f140f5e-0a8a-11e7-990e-1c546182046d.png)
![image](https://cloud.githubusercontent.com/assets/15828926/23999648/96b62f14-0a8b-11e7-9dfd-a28dfa840008.png)

**Comment by sosukesuzuki** [comment]
Hi @VoLuong , thank you for your reporting. This bug is happens on OSX. 
I think that This is very inconvenient. I'll investigate the cause soon and resolve it.

**Comment by asmsuechan** [comment]
Hi @VoLuong, actually, it occurs regardless of language. To avoid this, you should put any `#`, `##`, `###` or something at the first row in your note for now.

**Comment by VoLuong** [comment]
@asmsuechan  Yes I already tried that. It's a neat workaround. But I am looking forward to something more of a solution. We have a submenu to rename folder, why not notes? Why do we have to bind the name of the note with the "#" ( a.k.a headings ) as I don't think people will always use markdown in boostnote, as well as like how the first line need to be big and bold.

**Comment by asmsuechan** [comment]
Hi @VoLuong, @sosukesuzuki solved this issue!

**Comment by VoLuong** [comment]
I am very happy. Thank you all, @asmsuechan  @sosukesuzuki
