### ISSUE TITLE
Scrolling needs serious work. Practically unusable?

### ISSUE THREAD

**Issue by NateOsterfeld** [BoostIO/Boostnote#3230]
# Current behavior
I'm sure I can't be the only one, but whenever I type something into Boostnote the page scrolls all the way to the top. Then when I try to scroll all the way back down (when splitting markdown and preview) preview doesn't even respond. So every time I type something the page flies all the way to the top and then I have to scroll both sides back down, until I type again.

# Expected behavior
Scrolling would scroll

# Steps to reproduce
I don't know.. scroll?

# Environment

- Version : app-0.12.1
- OS Version and name :
Operating System: Windows 10 Pro 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
                Processor: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 CPUs), ~3.7GHz
           DxDiag Version: 10.00.17763.0001 64bit Unicode

**Comment by Flexo013** [comment]
Thanks for the report! 

We are aware of this issue, see #3023. The fix for this is ready and will be part of the next release.
