### ISSUE TITLE
文档中有图片，再输入就会跳开头

### ISSUE THREAD

**Issue by jujunchen** [BoostIO/Boostnote#3236]
这是git图片,这个问题让人很烦
![git图片](http://pic.aliali.vip:81/pic/boostnote-bug.gif)

**Comment by Flexo013** [comment]
Please post issues in English. We can't provide help with your issue, if we can't read it.

Also please use the provided template when submitting an issue. Without that information it is very unlikely that your issue will be solved.

I will be closing this issue for now. Once you have updated the description and title with the required info, you can reopen this ticket.
