### ISSUE TITLE
Dracula theme buttons in storage settings improperly styled

### ISSUE THREAD

**Issue by pointfour** [BoostIO/Boostnote#3237]
# Current behavior

<img width="684" alt="Screen Shot 2019-09-02 at 2 10 17 PM" src="https://user-images.githubusercontent.com/28244551/64133518-7a72c180-cd8b-11e9-8f8d-f294f795ba4d.png">
one warning in developer tools:
<img width="404" alt="Screen Shot 2019-09-02 at 2 11 48 PM" src="https://user-images.githubusercontent.com/28244551/64133549-a726d900-cd8b-11e9-926c-1a6434bac63a.png">

# Expected behavior

Buttons to the right of "my storage location" should be styled.

# Steps to reproduce
1. Use dracula theme
2. Open settings

# Environment

- Version : 0.12.1
- OS Version and name: Mac OS Mojave

**Comment by Flexo013** [comment]
Feature is available as of 0.13.0.

Thanks @pointfour 👏
