### ISSUE TITLE
How to import CSON files to Boostnote?

### ISSUE THREAD

**Issue by ngeegoh** [BoostIO/Boostnote#3242]
# Current behavior
My old laptop died and I had to find way to retrieve all the data from it including Boostnote workspace folder which contains a bunch of CSON files. I have set up a new laptop with BoostNote installed, but I cannot find a find to recover those CSON files and import them back to the Boostnote app in the new laptop. 

Could anyone please help me out with this and import all the old notes back to Boostnote app in my new laptop? 

Thanks,

- Version : 0.12.1
- OS Version and name : Windows 10

**Comment by jhdcruz** [comment]
**Try** opening the Boostnote app, _add new storage location_, and in that storage location, move all your CSON files, then reopen boostnote.

**Comment by Flexo013** [comment]
Could you try adding the Boostnote workspace folder (not just the notes folder) as a storage location?

So if you have your CSON files in `C:Users\Me\my_storage\notes\bla-bla.cson`, then add `C:Users\Me\my_storage` as the new storage. There should also be a boostnote.json in here.

**Comment by Flexo013** [comment]
Closing this for now as the question is answered.

If thing are still unclear @ngeegoh, then please reopen this ticket, and I'll try to provide more help.

**Comment by seliverstov-maxim** [comment]
![image](https://user-images.githubusercontent.com/4324963/85947779-75ec4a80-b955-11ea-8c67-8dc198be1e6c.png)
![image](https://user-images.githubusercontent.com/4324963/85947817-99af9080-b955-11ea-873b-95709f9bbd26.png)

**Comment by seliverstov-maxim** [comment]
not working

**Comment by Flexo013** [comment]
@seliverstov-maxim Importing notes from Boostnote Legacy into BoostNote.next is not supported yet.

**Comment by Hoss3770** [comment]
What about importing notes from BoostNote to BoostNote ?

**Comment by Komediruzecki** [comment]
Hi, Hoss3770,

can you further clarify what exactly are you trying to import where?
From boost note next (new application) to legacy, you could copy paste content as there is no way to do it.
From boost note legacy to boost note next (there is a way to do it, the tutorial is created https://medium.com/boostnote/how-to-migrate-data-from-old-boostnote-efd8a5c7aa7d)
From boost note next to boost note next, just load the storage again, or sign in for cloud spaces

**Comment by Hoss3770** [comment]
Loading the storage directory again gives me this error

![image](https://user-images.githubusercontent.com/9167620/128300869-bb73d537-9dc7-4eb9-b0b0-1dfbf0616a17.png)

**Comment by Komediruzecki** [comment]
Hi, Hoss3770,

I think what you are trying to do is load legacy boost note storage into new boost note next application, this won't work as this is loading or creating a new boost note next space in new application.

You need to follow import from legacy to load legacy boost note storage into new boost note next.

If you want faster support, please contact me on our slack.

If you are not trying to load legacy notes into boost note next, there might be some corruption on storage level and I would need more information about the location you are trying to load, please ensure you have only boost note next valid files inside that location:

To load the boost note next storage as in the create space screenshot above, you should have:
- boostnote.json file
- attachments folder
- notes folder

In notes folder should be *.JSON file type notes, nothing else
In attachments, probably only *.PNG file type attachments

Can you show me the structure you are loading on your disk? Do you have legacy storage notes or new boost note next?

**Comment by mordr** [comment]
This issues is marked closed, but it fails for me importing legacy notes (cson based) into newer BoostNate (Boost Note - Local Version 0.22.3 (0.22.3))

This blog https://medium.com/boostnote/how-to-migrate-data-from-old-boostnote-efd8a5c7aa7d does not watch with what I see, that is, I don't see any import feature.

My legacy notes structure

```
├── attachments
│   └── e7f52028-846d-404a-b13e-63616378f4a9
├── boostnote.json
└── notes
    ├── 02f718b7-bf82-4d0d-80ea-2e9f70a60864.cson
    ├── 165483ad-d903-4e49-ac94-3d1d72e2356c.cson
    ├── 1bdbb402-bd74-4648-94ea-9010f468a15e.cson
    ├── 36e5134a-3231-4b64-b680-bd9b6e154873.cson
    ├── 43f80134-5f81-459e-a6ce-e9aac7975159.cson
    ├── 4a41a709-14c5-4e86-9e93-d3ddab05be42.cson
    ├── 5e442f6a-080a-4d3c-96d0-4f8a7e880019.cson
    ├── 6999610e-5073-4a72-bfce-41c03deb44b0.cson
    ├── 715863b6-85ec-42d9-85dd-2237f4e9051a.cson
    ├── 81b7c907-6a19-440b-8d73-8d606a14a30a.cson
    ├── a21b35ec-3370-45f6-8011-90aebc7bc6dd.cson
    ├── a48206b0-31c3-4213-b5f4-3e45c370b2af.cson
    ├── a5acbb00-f4a8-48ca-a7a7-9b6e723bf6a6.cson
    ├── d19db36e-e077-4bfd-b952-61b28e2bf5a8.cson
    ├── e3bf9943-1a66-4dcf-9819-484571dda777.cson
    ├── e7f52028-846d-404a-b13e-63616378f4a9.cson
    ├── ee9da152-82a8-47bc-b707-7858cad4b6a5.cson
    ├── ef6a7c3f-687a-4130-9e40-f0301362632e.cson
    └── f23c47d2-ddae-45c0-ad52-532a16e42d5b.cson
```

Is there an update to this? Or any workarounds for cson based notes?

Thanks.

**Comment by Komediruzecki** [comment]
Hello, mordr,

Can you please see this discussion (https://github.com/BoostIO/BoostNote.next-local/discussions/53) on our Boost Note local spaces repository? 

if you still don't find it useful, please join our slack and contact me directly, I can navigate you through the process.

Basically, you need to install a bit older version of boost note next (e.g., 0.19.x) and import/convert legacy notes with it to local space (*.JSON notes). The option is found in Preferences | Space, should be similar to what the tutorial states.

Then you just install the latest version and import the boost note next storage directly (new space form).

**Comment by maximouche** [comment]
Hi,

Could you share a link to the 0.19 release?
- Only source code is available here : https://github.com/BoostIO/BoostNote-Legacy/releases/tag/v0.8.19
- Only release 0.21 and above is available here : https://github.com/BoostIO/BoostNote.next-local/releases
- Only releases up to 0.16.1 are available here : https://github.com/BoostIO/boost-releases/releases

Could you help and provide a link to packages (.dmg/.exe/.rpm) that have the convert feature to export *.cson notes to the new *.json format? 
Thanks


EDIT : I finally found it ==>  https://github.com/BoostIO/BoostNote-App/releases/tag/v0.19.0

EDIT 2 : I'm adding more details, because I must say this is not straight forward.

0) you have notes in *.cson format you need to convert
1) install version 0.19.0 : https://github.com/BoostIO/BoostNote-App/releases/tag/v0.19.0
2) create a new local storage (bottom of the startup screen). Create an empty one, do not try to import your old notes now
3) go to Preferences > Space and scroll down to "Import notes from Legacy BoostNote, and select your old notes foder. The notes will be imported in the new format to the empty location space you create on step 2.
4) Finally you can use the latest version of boost note local : https://github.com/BoostIO/BoostNote.next-local/releases
