### ISSUE TITLE
Default hotkey for "Prettify Markdown" conflicts with capital `F` character

### ISSUE THREAD

**Issue by robbawebba** [BoostIO/Boostnote#3246]
# Current behavior
Atom formats the contents of the currently-opened note when `shift-F` is pressed.

# Expected behavior
a `F` character is added to the editor at the current location of the cursor when `shift + F` is pressed.

# Steps to reproduce
1. Open any note.
2. Press `shift-F`.
3. Observe that no `F` character is inserted into the editor.

# Environment
OS: Fedora 30
Version: 0.12.1, checked out from the master branch
![image](https://user-images.githubusercontent.com/10067384/64657750-c657e300-d3e9-11e9-8f3e-c67c914e6d92.png)

**Comment by robbawebba** [comment]
PR #3903 seems to have introduced this hotkey.

**Comment by Flexo013** [comment]
I am unable to reproduce this on Windows 10.

**Comment by robbawebba** [comment]
@Flexo013 I noticed this feature has not yet been released, and is expected to be released with 0.13. Are you not able to reproduce this on the master branch, or are you testing on a stable release?

**Comment by Flexo013** [comment]
This problem is solved in the latest pre-release.

**Comment by frizop** [comment]
Howdy folks, I'm running into the same issue here, I can't re-open this issue without opening a entirely new one but I wanted to throw my hat in.

Currently running this version as it's the last one I can get functional:
![image](https://user-images.githubusercontent.com/3605906/67252970-0673a200-f43b-11e9-9125-6018f1831416.png)

I'm also on fedora Linux 5.3.5-200.fc30.x86_64 #1 SMP Tue Oct 8 12:41:15 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I did a git bisect and concluded (with limited success) that the issue resides in one of the following three commits:
```
The first bad commit could be any of:
7e3c662374904ecbe24f5062d2bb9f4c6e143919
a39e9c2da64b29602ffbad7160291078b6c32ced
33161e46e63e54d2bd26aceb91232b80973c0126
We cannot bisect more!
```

**Comment by Flexo013** [comment]
@frizop Could you check your preferences when using 0.13.0? Looking at the `ConfigManager.js` there should be no way for it to trigger on just Shift + F. [See this commit](https://github.com/BoostIO/Boostnote/commit/8736666e91d83a9d701ca48aa3d9ee9844ac9d5d)

**Comment by frizop** [comment]
Good call! 
![image](https://user-images.githubusercontent.com/3605906/67295624-0613ef00-f4ad-11e9-95eb-7baece73622c.png)
I don't remember ever setting this, but there it is!

**Comment by Flexo013** [comment]
It might have been caused by one of the previous faulty builds. And after that it simply read from the preferences.

Glad to hear the problem is solved! :smile:
