### ISSUE TITLE
How to move notes from a folder to another one

### ISSUE THREAD

**Issue by fzh0917** [BoostIO/Boostnote#3248]
# Current behavior
I can't move notes from a folder to another one.

# Expected behavior
Add a function `Moving note` as same as the "EverNote".

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.12.1
- OS Version and name : macOS, Mojave 10.14.6

**Comment by antiphasis** [comment]
You see the folder symbol at the top of the note? Click it and it'll show you your notebooks. Then click on the desired notebook and the note is moved there.

**Comment by fzh0917** [comment]
> You see the folder symbol at the top of the note? Click it and it'll show you your notebooks. Then click on the desired notebook and the note is moved there.

OK, it works well. Thanks!

**Comment by aciarochi** [comment]
I don't see a folder at the top of my note....

**Comment by gan3sh500** [comment]
@aciarochi If App mode is Notes then they are movable. But in Wiki mode I am not sure how to move it.

**Comment by Flexo013** [comment]
The instructions in this issue are for Boostnote Legacy. 

@aciarochi I assume you are using BoostNote.next (0.10.x). In that version you need to be using the Note mode (not the Wiki mode) to move notes from folder to folder. Then you can simply drag the note from the note list to the correct folder.
