### ISSUE TITLE
Display long LaTeX formulas properly

### ISSUE THREAD

**Issue by fzh0917** [BoostIO/Boostnote#3250]
# Current behavior
As the figure [here](https://figures-1252154746.cos.ap-guangzhou.myqcloud.com/Screenshot%20at%20Sep%2016%2020-42-02.png), the very long LaTex formula can't show in one line, and there isn't a horizontal scroll bar to the tail.

# Expected behavior
A feature of `Auto word wrap` or a **horizontal scroll bar** is required.

# Steps to reproduce

1. Create a note with a long LaTeX formula

# Environment

- Version : 0.12.1
- OS Version and name : macOS, Mojave 10.14.6

**Comment by Flexo013** [comment]
How fixable this is for us depends on what the options are for KaTeX, the LaTeX to Markdown markdown library that we use.

If they don't have any helpful way to split something into multiple line then I think the only option will be the scrollbar as you suggested.
