### ISSUE TITLE
PDF export does not support cyrillic characters

### ISSUE THREAD

**Issue by bravo321** [BoostIO/Boostnote#3253]
# Current behavior

1. Create a note encoded ru-RU.UTF8
2. Export to PDF
3. Cyrillic characters are not displayed in PDF
4. Old notes in Cyrillic are displayed normally.

# Environment

- Version : Ubuntu 18.04.3 LTS
- OS Version and name : Kernel: 5.0.0-25-generic x86_64 bits: 64 Desktop: Gnome 3.28.4
- Boostnote 0.12.1

**Comment by Flexo013** [comment]
So far I have been unable to reproduce this. Cyrillic characters export fine on my end (Ubuntu 16.04):

![image](https://user-images.githubusercontent.com/4507015/65957820-28868f80-e44e-11e9-9feb-4c22f1a20791.png)

@bravo321 Can you provide an example .md file with character encoding that causes this issue?

**Comment by bravo321** [comment]
[noPDFexport.md.txt](https://github.com/BoostIO/Boostnote/files/3682971/noPDFexport.md.txt)
[noPDFexport.pdf](https://github.com/BoostIO/Boostnote/files/3682972/noPDFexport.pdf)

**Comment by bravo321** [comment]
Strange, but new notes are exported normally, only this note is not currently exported.

**Comment by Flexo013** [comment]
That is indeed very strange.

If I copy the contents of that note into a note on my end then it compiles fine:
[testexport.pdf](https://github.com/BoostIO/Boostnote/files/3691196/testexport2.pdf)

Could you try to cloning the note and exporting the clone?

If that doesn't work, then could you make a new Markdown notes and copy paste the entire contents of the note into the new note? Then try exporting the new note.

**Comment by bravo321** [comment]
After cloning, the export was successful. Apparently there was some kind of glitch, I just after creating a note, updated the program from the previous version.

**Comment by Flexo013** [comment]
If we can't reproduce the issue then we can't really fix whatever might have caused this. Since this currently looks like a one off occurrence and we have the easy fix of just copying the content to a new note, I don't think it's worth to spend more time on this issue.

In the event that this issue does pop-up again, then we can investigate this further.
