### ISSUE TITLE
If you screenshot an image, and paste it with clipboard it breaks preview

### ISSUE THREAD

**Issue by FrederikGullberg** [BoostIO/Boostnote#3254]
If you screenshot an image, and paste it from clipboard. Then whenever you type enough to where you have to scroll in the editor, the preview will forever scroll up to the image everytime you write something new.

**Comment by BlancLoup** [comment]
Also, any little change to a markdown of inserted image removes that image forever. It is very annoying. Especially when you added screenshot proof of something and after time you open Boostnote but link and image are dead.

**Comment by Flexo013** [comment]
Thanks for the report!

We are aware of this issue, see #3023. The fix for this is ready and will be part of the next release.
