### ISSUE TITLE
Boostnote not starting

### ISSUE THREAD

**Issue by malorie16** [BoostIO/Boostnote#3260]
# Current behavior

Boostnote shows perpetual loading screen

<img width="1079" alt="Screen Shot 2019-10-03 at 8 06 39 AM" src="https://user-images.githubusercontent.com/37854050/66125417-de6bee00-e5b4-11e9-84e1-2e95b11752aa.png">

In terminal:
<img width="1160" alt="Screen Shot 2019-10-03 at 8 07 00 AM" src="https://user-images.githubusercontent.com/37854050/66125426-e3c93880-e5b4-11e9-86ac-dc9a070638d1.png">

I found issues similar to this but none were for mac.
One issue said this [PR](https://github.com/BoostIO/Boostnote/pull/3243) potentially fixes it but after including the changes from that PR I still got the perpetual loading screen but without the devtools console error as in the first screenshot  and a syntax error in the terminal output:

<img width="1145" alt="Screen Shot 2019-10-03 at 8 18 25 AM" src="https://user-images.githubusercontent.com/37854050/66126012-656d9600-e5b6-11e9-8265-a5bf319fc1d7.png">

# Expected behavior
Boostnote opens properly

# Steps to reproduce
1. Fork repo
2. Clone down repo 
3. Run `yarn` and `yarn run dev` per [docs](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md)

# Environment

- Version : 0.12.1
- OS Version and name : Mac Mojave 10.14.5

**Comment by jhdcruz** [comment]
In the second screenshot you've provided, my PR #3243 fixed the issue that was showing in the first screenshot. It was a fix for multiple instances that was deprecated, and is no way related to the perpetual loading issue you're having.

I believe the issue you're having relates to the second error that is showing:
![Annotation 2019-10-04 111905](https://user-images.githubusercontent.com/28413338/66178738-ef8e2b00-e698-11e9-9435-81317beac1f6.jpg)

**Comment by malorie16** [comment]
@jhdcruz Right! Your PR is the one linked in the issue. Strange that it caused different behavior even though I, too, agree that this issue isn't related to an issue with multiple instances...

Kind of at a loss here. Would love to contribute to Boostnote but I can't seem to get it running locally 😕

**Comment by Flexo013** [comment]
Is this still a problem with 0.13.0?
