### ISSUE TITLE
Support for coloring font tag in preview

### ISSUE THREAD

**Issue by Shigenori-Sagawa-nm** [BoostIO/Boostnote#3265]
# Current behavior

In preview coloring font tag is not work.

# Expected behavior

Support for coloring font tag in preview.

```html
This is <span style="color: red;">red</span> color.

This is <font color="red">red</font> color.

```

# Environment

- Version : 0.12.1 (0.12.1)
- OS Version and name : macOS Mojava 10.14.6

**Comment by Flexo013** [comment]
These tags are already supported:
![image](https://user-images.githubusercontent.com/4507015/67162001-52054d80-f360-11e9-92d3-427d333b7ae2.png)
