### ISSUE TITLE
Boostnote crashes if I type in a specific line of a note

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#3269]
# Current behavior
If I type on a specific line on a note, Boostnote will freeze, and if I quit and reopen, it doesn't save what I just typed ([video link](https://youtu.be/FqGX_bbxLrM))

# Expected behavior

I should be able to type normally

# Steps to reproduce

1. Open the note
2. Type on the specific line
3. Quit and reopen boostnote

[note file](https://mega.nz/#!1Y00UQgB!q0iJNLj2lzkqWFwHF5ZNbiGJqfLU7oWq0YYmconjSic), you just have to write in the parentheses that say "write here"

# Environment

- Version : 0.12.1
- OS Version and name : macOS 10.14.6

**Comment by Flexo013** [comment]
I pasted the content of your note in a new Markdown note. I can edit the line with write here when using Boostnote 0.13.0 on Windows 10.

Does the problem persist if you:
- copy-paste the content into a new note
- use the new version 0.13.0 of Boostnote

**Comment by federicochiesa** [comment]
No, it doesn't seem to happen anymore in 0.13.0.
