### ISSUE TITLE
Storage unlinked when opening Boostnote

### ISSUE THREAD

**Issue by tacchan7412** [BoostIO/Boostnote#327]
I'm using Boostnote v0.8.6 on Mac(macOS Sierra).
Every time I open the app, the storage disappears and I need to 'Add storage'.

I once deleted the app and reinstalled. Since the second installation, this problem has occurred.

**Comment by kazup01** [comment]
That's the first time I heard that. My dev environment is same(macOS Sierra), but not occured.
We'll investigate the cause.

**Comment by illia1** [comment]
Hi,  I'm using Boostnote 0.8.7 on Windows 10 and have same problem but reinstallation dont help.

**Comment by illia1** [comment]
I fix this problem for me by deleting lacal folder  BoostNote

**Comment by tacchan7412** [comment]
@illia1 Could you provide with me detailed instruction since I could not fix the problem by just deleting the local folder.

**Comment by asmsuechan** [comment]
@tacchan7412 Thanks for reporting. I cannot reproduce this issue, could you paste any screenshots (with opening developer tool)?

**Comment by tacchan7412** [comment]
Here is the screenshot.
<img width="1920" alt="screen shot 2017-04-08 at 13 51 28 2" src="https://cloud.githubusercontent.com/assets/6593362/24825833/b1168e10-1c62-11e7-9fa4-7dbf11d0b3e0.png">

**Comment by asmsuechan** [comment]
@tacchan7412 Mostly, this bug happens when something is wrong in `boostnote.json`. But I cannot reproduce this bug. Do you mind if you show me your storage? Probably it's located at `~/Boostnote`, I want to know the content of `boostnote.json` and the names of `.cson` files.

**Comment by tacchan7412** [comment]
Below is boostnote.json
```
{
  "folders": [
    {
      "key": "00ab6e580046e6bdc6ae",
      "color": "#E10051",
      "name": "programing"
    }
  ],
  "version": "1.0"
}
```

Below is the screenshot of my ~/Boostnote files (including .cson files)
<img width="405" alt="screen shot 2017-04-08 at 14 31 10" src="https://cloud.githubusercontent.com/assets/6593362/24826042/1ebc42de-1c68-11e7-9905-c58dcfde3a7a.png">

**Comment by asmsuechan** [comment]
@tacchan7412 I suggest it's a bug depends on the content of the note. Because your case is similar to https://github.com/BoostIO/Boostnote/issues/300. Could you move the latest note?

**Comment by tacchan7412** [comment]
@asmsuechan I moved all notes and open the app again, but it does not solve problem. By the way, why do you prefer the latest note as a note to be moved?

**Comment by asmsuechan** [comment]
@tacchan7412 Umm, what's happening if you rename the folder?
Because I suggest you wrote a word which brakes application as same as https://github.com/BoostIO/Boostnote/issues/300. (It's obviously bad...)

**Comment by tacchan7412** [comment]
@asmsuechan What do you mean by "folder"?

**Comment by asmsuechan** [comment]
@tacchan7412 "folder" means your local folder mounted to Boostnote, in this case, `~/Boostnote`. Could you change `~/Boostnote` to `~/Boostnote_back` or something?

**Comment by tacchan7412** [comment]
@asmsuechan I changed the folder name, but the issue still occurred. (Sorry for late response)

**Comment by illia1** [comment]
I have same problem again. 
![screenshot_20170521140300](https://cloud.githubusercontent.com/assets/8217933/26283405/94ce019e-3e30-11e7-8d7e-9a073cc793a0.png)


In console I  try `localStorage.clear();`  . This help me.

**Comment by tacchan7412** [comment]
@illia1 That helped me as well! Thanks so much!

**Comment by kazup01** [comment]
Thanks @tacchan7412  for your reporting, and thanks @illia1 for your supporting! Enjoy Boostnote :)
