### ISSUE TITLE
The link to the Slack channel is broken.

### ISSUE THREAD

**Issue by BlancLoup** [BoostIO/Boostnote#3276]
# Current behavior
The link to the Slack channel is broken.
# Steps to reproduce
Visit link https://join.slack.com/t/boostnote-group/shared_invite/enQtMzkxOTk4ODkyNzc0LThkNmMzY2VlZjVhYTNiYjE5YjQyZGVjNTJlYTY1OGMyZTFjNGU5YTUyYjUzOWZhYTU4OTVlNDYyNDFjYWMzNDM

**Comment by Flexo013** [comment]
We are aware of the issue, see #1889
