### ISSUE TITLE
Package that needs to be installed to build the app is not mentioned in docs

### ISSUE THREAD

**Issue by DrFelder** [BoostIO/Boostnote#3278]
# Current behavior

electron-installer-debian has to be installed to build the application, but is not mentioned in the README/docs:

```
secret/auth_code.json is not found. CodeSigning is not available.
Loading "electron-installer-debian.js" tasks...ERROR
>> ReferenceError: internalBinding is not defined

Running "build" task
Warning: Task "electron-installer-debian" not found. Use --force to continue.

Aborted due to warnings.
```

# Expected behavior
When following the guide in https://github.com/BoostIO/Boostnote/blob/master/docs/build.md, everything works as expected (it should be mentioned that this package needs to be installed).

-> After I installed the package using `npm install -g` it worked as expected.

Can someone confirm this? Did I not follow the steps correctly?

# Environment

- Version :
latest/master
- OS Version and name :
OS: Fedora 30 Thirty
Kernel: x86_64 Linux 5.2.17-200.fc30.x86_64

**Comment by jhdcruz** [comment]
It is included in the `optionalDependencies`:
```json
"optionalDependencies": {
   "grunt-electron-installer-debian": "^0.2.0",
   "grunt-electron-installer-redhat": "^0.3.1"
},
...
```

**Comment by DrFelder** [comment]
well, as i wrote, it is _not_ optional. The build will _fail_.

**Comment by jhdcruz** [comment]
> well, as i wrote, it is _not_ optional. The build will _fail_.

Can you elaborate what exactly did you do/run? why did you run `npm i -g`?

**Comment by DrFelder** [comment]
I had to run npm i -g in order to install the package `grunt-electron-installer-debian`

**Comment by jhdcruz** [comment]
> I had to run npm i -g in order to install the package `grunt-electron-installer-debian`

**You didn't really need to install every packages on your global filesystem, it'll bloat your global `node_modules/`, and isn't recommended at all**.

You can just run `yarn`, then manually installing it using `yarn add --dev grunt-electron-installer-debian` instead.

----
Haven't really tried building/compiling with `Fedora Linux`, so I guess you gotta wait until someone who did encounters this or not.

**Comment by robbawebba** [comment]
Hi @jhdcruz, I wanted to let you know that I'm able to successfully build deb and rpm packages after follow the steps of docs/build.md plus your suggestion of installing runt-electron-installer-debian grunt-electron-installer-redhat manually.

So I think @DrFelder's request is still valid that we should probably add a note about installing runt-electron-installer-debian grunt-electron-installer-redhat manually to the build documentation.

**Comment by jhdcruz** [comment]
It is actually written in the docs, to install the build dependency packages.

> After installing the supported version of node and npm, install build dependency packages.

But I'll try submitting a PR about this to be more specific and noticeable.

**Comment by DrFelder** [comment]
I mean, `install build dependency packages.` just tells me to run `yarn install` if nothing else is specified.
The time spent to discuss this issue would've been enough to clarify the README about 20 times.

**Comment by jhdcruz** [comment]
> I mean, "install build dependency packages." just tells me to run `yarn install` if nothing else is specified.
> The time spent to discuss this issue would've been enough to clarify the README about 20 times.

Running `yarn install` probably doesn't include the `optionalDependencies`, and are installed manually. That's the reason why it is included in the build docs.

> After installing the supported version of `node` and `npm`, **install build dependency packages.**

Which can be achieved by installing these required build dependencies:

```
$ yarn add --dev grunt-electron-installer-debian grunt-electron-installer-redhat
```

Install the packages that are required in your distro:

**Fedora**

```
$ sudo dnf install -y dpkg dpkg-dev rpm-build fakeroot
```

Then proceed with:

```
$ grunt build
```

**Comment by Flexo013** [comment]
Fixed by https://github.com/BoostIO/Boostnote/pull/3304

Will be part of the next release (0.15.0)
