### ISSUE TITLE
[Feature Requests] New Dark Theme, Export options, Markdown buttons, Tag menu, and image support

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#328]
Boostnote is easily one of my FAVORITE app and the fact it uses ElectronJS is even cooler.

Now a few days ago I discovered another favorite ElectronJS app called **Eagle** - https://eagle.cool which is an Inspiration and Asset file Manager which allows to create folders and tags and add PNG, JPG, GIF, AI, PSD, and Sketch image files in a really organized manner.

It also allows to add annotation text on top of the images with text notes and view the images in different sizes.

It is a program I have wanted to exist for years now but the only thing like it is for Mac only and Windows has nothing like it so finding Eagle App made me super happy.

Based on Eagle app and it using ElectronJS like Boostnote, I have some great feature request from it I would like to share.  Also I highly recomend installing Eagle and checking out its features, UI, and UX for inspiration too.

# Feature Requests:

## New Dark Theme

-I am a big fan of dark themes for apps however I find it hard to use the current dark theme in Boostnote.  I really like the dark theme in Eagle app though so I request adding a 2nd dark theme to Boostnote based on the color scheme of Eagle app.  It is only about 3 colors in use however the borders really help break up the sections.

This image shows it....
Full screen image - https://cloud.githubusercontent.com/assets/186818/24053639/147ea74e-0b10-11e7-8448-2539aa4c7ef4.png

![image](https://cloud.githubusercontent.com/assets/186818/24053639/147ea74e-0b10-11e7-8448-2539aa4c7ef4.png)

compared to the Boostnote Dark theme where each of the sections just blend together.  Using different shades and borders really helps break the sections up for a better UI in my opinion as I find it somewhat hard to see where one section ends and another starts....:

![image](https://cloud.githubusercontent.com/assets/186818/24053782/7eb8a20e-0b10-11e7-9350-04b6eb055143.png)

---

## File Export as HTML file and multiple files as a ZIP file:

Currently Boostnote has export options to export a file as a .md markdown file and as a .txt text file.

- A feature request would be to allow exporting a Markdown file as an HTML file.  Another ElectronJS app named Caret which is a Markdown editor just added this feature.
- Another export feature request is for Boostnote files which contain multiple files like a GIST.  On these file it would be nice to allow to export all the files in one of these files as a .ZIP file.  I believe GitHub GIST allow to export as a ZIP file which will contain all files within that file.

---

## Markdown BBCode Style Button Bar

Even though Markdown is a simple syntax to learn sometimes it is nice to be able to simple click a button.  Across the top of a Markdown file it would be nice to have some buttons which insert the Markdown code just like GitHub issue editor input box has!

---

## Image Upload

It would be great to add support for uploading images into a Markdown doc.  Simply click a button which would open a modal to upload a file from computer or from a URL and have it save that file to local disk space with the markdown file.

---

## Tag Menu in Sidebar to load list of Notes with that Tag

Right now it seems the Tags are somewhat useless unless they are a work in progress.  It would be nice to see a collapsible list in the sidebar list all the tags and clicking a tag would load the 2nd sidebar with notes tagged with the selected tag.  Also clicking a Tag inside of a Note would do the same action.

---

These are all just ideas on my personal Boostnote wishlist.  I would love to hear your thoughts on them and the possibility of any of them being added?

I love Boostnote and appreciate all your work in building it so thank you!

**Comment by asmsuechan** [comment]
Hi @jasondavis, thanks for great opinions! It makes me happy so much :smile: Yes, they are my opinions below:

****

### New Dark Theme
I'm trying `Eagle` now because I didn't know it. I feel it has very sophisticated UI/UX. I'd like to use as a reference. Thanks for informing!

### File Export as HTML file and multiple files as a ZIP file
Yes, I also want a feature `Export as HTML`. I'll try to implement it 👍. And to export multiple files sounds good. I'll try to implement it too.

### Markdown BBCode Style Button Bar
Actually, I don't like `BBCode Style Button Bar`. Perhaps it won't be added by me in Boostnote.

### Image Upload
Is this like https://github.com/BoostIO/Boostnote/pull/293? Regarding a button, I'll consider.

### Tag Menu in Sidebar to load list of Notes with that Tag

****

Thanks for using Boostnote! I appreciate your continued support!

**Comment by jasondavis** [comment]
Thanks for the feedback, you have done a great job so far so I look forward to seeing the app progress as it can really become even more amazing.

Just a thought for down the road in addition to the current 2 file types **Markdown** and **Snippet Note**.  The online Code Playgrounds like CodePen.io and JSFiddle, JSBin which all have these panels:

- HTML
- CSS
- JavaScript
- HTML Output

It would be amazing to add this as a new type as it would be the only Code Playground that is a self hosted on computer version in a Desktop app!

The 3 code panels could use the existing code editor you currently use in the app and then it would just be a matter of have it save there data and parse the output.

I would pay for this feature!

Any thoughts?  I have several ideas for it if you are interested in pursuing it

**Comment by asmsuechan** [comment]
I can do my best with that voice 💯.

I think the thought of Code Playgrounds is far from Boostnote. I'd like to keep the simplicity in Boostnote. Thus, in my opinion, I don't want to implement it because it makes Boostnote more complex. I want to hear another opinion from @kazup01.

**Comment by jasondavis** [comment]
Ok I  can respect that decision.  Perhaps its an idea for a separate app similar in UI to Boostnote but for Code Playground style items.

Another idea would be in addition to these Issues on GitHub is a Roadmap of planned features.  The new GitHub Projects https://github.com/BoostIO/Boostnote/projects would be a great place to publish planned feature and allow feature request and ideas if you are open to it and then it would be contained in this GitHub repo

**Comment by kazup01** [comment]
Thank you for your great feedback, @jasondavis san! 

Actually, I also think that Code Playgrounds(Just like CodePen.io and JSFiddle! I love CodePen and I use it everyday.) seems very interesting.
But as @asmsuechan said, we want to keep Boostnote simple.
Though, I think that there are users who are seeking Code Playgrounds (eg front-end engineers), so how about providing it like a plug-in?

**Comment by kazup01** [comment]
And as you said, Eagle app's dark theme is great. I did'n know that, so thank you for your information @jasondavis !
I will improve the Boostnote's dark theme.

**Comment by jasondavis** [comment]
@kazup01 in response to a codepen type function as a plugin, I think some sort of plugin system in general would be amazing.

**Comment by kazup01** [comment]
Many features are added to current version. Try it!
