### ISSUE TITLE
Internal links and TOC links are not working on 0.13.0

### ISSUE THREAD

**Issue by InfinitelyUncertain** [BoostIO/Boostnote#3287]
# Current behavior
Internal links and TOC links to headers don't seem to be working on version 0.13 on Windows.  When clicking on the links it will only shift the page by a tiny amount.  This happens in both split view and whole page view.

Internal Links to Headers in ver. 0.13:
![boostnote_0 13_header_link](https://user-images.githubusercontent.com/50601879/67136147-dd0e1700-f27e-11e9-9841-e74e6fc08ea3.gif)

TOC Links to Headers in ver. 0.13:
![boostnote_0 13_toc_link](https://user-images.githubusercontent.com/50601879/67136204-8bb25780-f27f-11e9-9eec-22e4e7414481.gif)

# Expected behavior

In the preview pane, clicking on the links would jump to the respective header stated in the markdown.

Example in ver. 0.12.1:
![boostnote_0 12 1_header_link](https://user-images.githubusercontent.com/50601879/67136176-28c0c080-f27f-11e9-9295-329170ba21e3.gif)

# Steps to reproduce

1. Create a link to a header or create a [TOC]
2. Click on the link in the preview pane/view.

# Environment

- Version : 0.13.0
- OS Version and name : Windows 10 (or in Boostnote's About: Windows_NT x64 10.0.18362)

**Comment by microcreators** [comment]
TOC's not working on Linux either.

**Comment by Flexo013** [comment]
For me it jumps to the right location when using the generated TOC on Windows 10. Manual links work as well. But I do get weird scrolling behavior.

I think something is wrong with the scroll bar of the preview side. Sometimes the links work, sometimes they don't...

**Comment by omsblackelf** [comment]
Similar issue, but a bit different behaviour (Mac/Win) after update to 0.13.0:

All links (not only Toc) are not working, depending on the link I see two kinds of behaviour:

1. Clicking on most links leads to an empty page, to see any contents of the note, switching to another note and back is necessary.
2. Clicking leads to the correct Heading, but the note is not displayed correctly: only a part of the note is visible.

**Comment by Flexo013** [comment]
We are working on fixes for this. The next release should have these problems fixed.

**Comment by SchrodingersDice** [comment]
Thanks, @Flexo013 and team.  Appreciate. =)

**Comment by Flexo013** [comment]
Confirmed to be solved in the latest [pre-release](https://github.com/BoostIO/boost-releases/releases/).
