### ISSUE TITLE
Add admonition type "question"

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3295]
# Current behavior

https://github.com/docarys/markdown-it-admonition has an admonition type for questions. 

# Expected behavior

An admonition to highlight questions would be very useful. I miss that a lot.

```
!!! question

!!!
```

Other types provided by markdown-it-admonition and currently not supported in Boostnote are: 

- abstract
- tip
- success
- warning
- failure
- example
- quote

However, I think adding all of them would be confusing as `caution`, `danger` and `warning` can be used exchangeable.

# Steps to Replicate

```
!!! question

!!!
```

# Environment

- Version : 0.11.12
- OS Version and name : 16.04 Ubuntu

**Comment by ibraude** [comment]
Hey, 
See #3297  for the added question, quote, and abstract types. 

You can add as many as you'd like by adding styles to `markdown.styl`:
```
admonition_types = {
    note: {color: #0288D1, icon: "note"},
    hint: {color: #009688, icon: "info_outline"},
    danger: {color: #c2185b, icon: "block"},
    caution: {color: #ffa726, icon: "warning"},
    error: {color: #d32f2f, icon: "error_outline"},
    question: {color: #64dd17, icon: "help_outline"},
    quote: {color: #9e9e9e, icon: "format_quote"},
    abstract: {color: #00b0ff, icon: "subject"},
    attention: {color: #455a64, icon: "priority_high"},
}
```
and adding the name of the admonition at `markdown.js`
```
   this.md.use(require('markdown-it-admonition'), {types: ['note', 'hint', 'attention', 'caution', 'danger', 'error', 'quote', 'abstract', 'question']})
```

**Comment by LuaGeo** [comment]
Hello, how could i access the file `markdown.js` in the application?
