### ISSUE TITLE
Feature request: Export notes as Markdown files

### ISSUE THREAD

**Issue by evitalis** [BoostIO/Boostnote#3298]
# Current behavior

Currently BoostNote saves notes as a key in a CSON file and does not seem to have a way to export as plain Markdown (.md) files for use in other notebook applications.

# Expected behavior

Ability to export notes in a common format for use when switching notebook applications or to share with other non-BoostNote users.

Sometimes it would be nice to just send someone a text file or collection of them in a tarball or zipfile. When trying to extract the content key from the CSON file using Python's JSON module, an error is reported that the file is not valid. The leading and trailing curly braces are missing.

# Steps to reproduce

1. Create any new note
2. Observe the CSON file at the default location
3. No menu option for export

# Environment

- Version : latest (not in front of the system at the moment)
- OS Version and name : MacOS / any

**Comment by arcturus140** [comment]
@evitalis ,

did you try to `File -> Export As -> Markdown`?

**Comment by evitalis** [comment]
Not sure how I missed that, it seems to work but is there an easy way to export the whole notebook at once?

**Comment by arcturus140** [comment]
I think there isn't any way to export your entire notes or snippets in any way from Boostnote.

**Comment by Flexo013** [comment]
You can export an entire folder of notes by right-clicking it in the sidebar. Currently there is no way to export an entire storage or multiple folders at once.
