### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by benjamindahl** [BoostIO/Boostnote#33]
Hey,
Boostnote looks great but though I'm missing cloud storage, android version and note encryption.

Would appreciate to see them implemented

cheers.

Benny

**Comment by Rokt33r** [comment]
## About cloud service

After v0.6.*, all notes will be stored anywhere in filesystem. It means you will be able to any cloud service you want such as Google drive, Dropbox, and even Github.

## About mobile app

I'm actually going to make mobile web by web view. I'll start to work after v0.6.* becoming stable.

## Note encryption

I'll add it to my todo list. I understand it is important for some user.

**Comment by benjamindahl** [comment]
Thanks.

**Comment by alexanderadam** [comment]
Regarding encryption: people opened a few duplicates for it like #94, #827 and #1511.
