### ISSUE TITLE
Add support for Windows x32-bit

### ISSUE THREAD

**Issue by Zorono** [BoostIO/Boostnote#3301]
Hello everyone,
Thanks for sharing the awesome Notes Management Tool `Boostnote` but it'd be great if you adopted the **Windows x32-bit** support please

i couldn't reinstall my **_whole windows&applications_** at the current time... please take my order seriously :(

**Comment by Flexo013** [comment]
Boostnote works on both 32bit and 64bit Windows systems.

I don't quite understand what the problem is. Could you elaborate?
