### ISSUE TITLE
Can not download from the website

### ISSUE THREAD

**Issue by Tao-Zhou** [BoostIO/Boostnote#3307]
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by arcturus140** [comment]
hi,

the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

**Comment by Tao-Zhou** [comment]
> hi,
> 
> the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

I know, but when I click the button, ERR_CONNECTION_REFUSED appeared.

**Comment by Tao-Zhou** [comment]
> hi,
> 
> the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

ok, I downloaded it with VPN

**Comment by Flexo013** [comment]
Duplicate of #3303
