### ISSUE TITLE
Can't make new notes after failed URL to note conversion

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#3308]
# Current behavior

The new note button stops working after entering a non existent URL to convert.

# Expected behavior

A failure message appears about the previous URL to note conversion.
AND
The new note button does not stop working after a failure.

# Steps to reproduce

1. Open the new note selection (Ctrl+N).
2. Select new markdown note from URL.
3. Enter a non existent URL, e.g. https://www.bgvoirhbvoojwscj.com
4. Hit Enter. (No new note is made, as expected.)
4. Try clicking the new note button (or Ctrl+N).

Dev tools console: 
![image](https://user-images.githubusercontent.com/4507015/67404357-8de42100-f5b3-11e9-9c7e-d2ca231ee467.png)

# Workaround

Reload Boostnote (Ctrl+R) to fix the issue temporarily.

# Environment

- Version : 0.13.0
- OS Version and name : Ubuntu 16.04

**Comment by AWolf81** [comment]
@Flexo013 Oh good catch. I haven't noticed that before.

I'll fix this by adding error handling to `createNoteFromUrl`. I'll create a PR soon.
