### ISSUE TITLE
Script support for .cshtml (Razor syntax)

### ISSUE THREAD

**Issue by MarcAndreJean** [BoostIO/Boostnote#3309]
# Current behavior

There is no syntax highlighting for .cshtml files. No current syntax in boostnote seems to support razor syntax.

# Expected behavior

Add the Razor syntax to support .cshtml files

**Comment by Flexo013** [comment]
We use CodeMirror for syntax highlighting. [It does not look like it supports the Razor syntax](https://codemirror.net/mode/index.html).

I suggest taking this issue to [the CodeMirror repo](https://github.com/codemirror/codemirror/issues). Once they support it, so will Boostnote.
