### ISSUE TITLE
Why not switch three views by button directly?

### ISSUE THREAD

**Issue by mokeyish** [BoostIO/Boostnote#3321]
I download the latest mac os client yesterday.  There are still two views on a note:
- Split view (edit + preview)
- Full edit view

**I clicked somewhere else, It was not change to full preview view.**  @petrkrejcik

_Originally posted by @mokeyish in https://github.com/BoostIO/Boostnote/issues/2339#issuecomment-547161833_

**Comment by Flexo013** [comment]
I can't reproduce this on Linux. As long as I clicking outside the edit frame it will switch to full preview view.

Could you try narrowing down when this occurs for you?

**Comment by mokeyish** [comment]
It works as expected now. But I still didn't know how it caused. 😂
