### ISSUE TITLE
HTML tag got rendered inside code block

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#333]
Hi, Boostnote team. Here we meet again.

I am using **Boostnote 0.8.6 on Linux** (Ubuntu 16.04.2)

Recently I encounter a problem that I believe happens on all platform and has never been in this issue section. So far, the problem was not so critical but it is annoying and I cannot find any reference or documentation on how to fix it myself.

**While typing some html elements inside a code block in markdown, it got rendered**. It seems like the application doesn't try to ignore markdown's code block. More information in photos below.  

![image](https://cloud.githubusercontent.com/assets/15828926/24071798/5bc9494e-0c0d-11e7-987b-9c7e87723c20.png)

Before: 

![image](https://cloud.githubusercontent.com/assets/15828926/24071833/e9038e3c-0c0d-11e7-827a-e3064574024c.png)

After: 
![image](https://cloud.githubusercontent.com/assets/15828926/24071844/2b6c46b0-0c0e-11e7-8251-9b949dc4049b.png)

**Comment by asmsuechan** [comment]
Hi @VoLuong, thanks for informing. But actually, I know it already. It is reported https://github.com/BoostIO/Boostnote/issues/205 and https://github.com/BoostIO/Boostnote/issues/294. I'm trying to fix although this is a quite complicated. So perhaps it takes a while to solve this problem perfectly. Sorry for inconvenient :fearful:

**Comment by VoLuong** [comment]
@asmsuechan  I really like how you guys deal with issues so no inconvenience is gonna discourage me from using the app . The one who should apologize is me. I haven't reached those issues before reporting this one. (Actually, Google didn't index them and I wasn't keen enough to look in every issue)

**Comment by VoLuong** [comment]
@asmsuechan The fix is promising. Otsukarasama deshita.

**Comment by asmsuechan** [comment]
谢谢 :smile:

**Comment by kazup01** [comment]
We will update at next release! Thank you for waiting! refs: #341
