### ISSUE TITLE
export function: images are not present in any exported format

### ISSUE THREAD

**Issue by JBPlinn** [BoostIO/Boostnote#3333]
# Current behavior

In any exported format (md, pdf, html) images are not present or path to images is wrong.

# Expected behavior

# Steps to reproduce

1. export to md ot html or pdf a note with embedded images.
2. 
3. 

# Environment

- Version :
Boostnote 0.11.17
- OS Version and name :
Linux - Manjaro 18.1.2

**Comment by Flexo013** [comment]
Duplicate of #2815
