### ISSUE TITLE
Render Emoji in note list

### ISSUE THREAD

**Issue by qihuazhong** [BoostIO/Boostnote#3338]
# Current behavior

Displaying emoji as text in the note list
<img width="303" alt="Screen Shot 2019-11-01 at 4 31 26 PM" src="https://user-images.githubusercontent.com/22231207/68054647-2457c700-fcc5-11e9-8f82-e2bbc1bae2fc.png">

# Expected behavior
like being done with Gmail's subject line.

<img width="797" alt="Screen Shot 2019-11-01 at 4 33 29 PM" src="https://user-images.githubusercontent.com/22231207/68054743-64b74500-fcc5-11e9-8dc6-876ab381037f.png">

It just looks nicer if the emoji can be rendered in the note list. plus, it allows us to identify notes much quicker  among many similar note titles

thank you
# Environment
Version: 0.13.0
Electron: 3.0.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 19.0.0

**Comment by Flexo013** [comment]
Agreed that the titles should perform the same as the Markdown preview title:
![image](https://user-images.githubusercontent.com/4507015/68113784-cdd0cf80-fef4-11e9-9fd2-20c1e43c060e.png)

**Comment by abnersajr** [comment]
I'm working on this one.
