### ISSUE TITLE
auto wrap selected text when tpying "~", like other formating chars such as *`(

### ISSUE THREAD

**Issue by qihuazhong** [BoostIO/Boostnote#3339]
# Current behavior

![Nov-01-2019 16-56-11](https://user-images.githubusercontent.com/22231207/68056052-91209080-fcc8-11e9-8713-7c1386dc9b10.gif)

typing ~ over selected text will replace the text with ~.
typing other formating characters like *(` will wrap the text

# Expected behavior

auto wrap selected text when typing "~" (used for formatting text with strikethrough or subscription)

# Environment

Version: 0.13.0
Electron: 3.0.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 19.0.0

**Comment by arcturus140** [comment]
you should be able to choose which characters are used for wrap in Boostnote preferences.

**Comment by qihuazhong** [comment]
> you should be able to choose which characters are used for wrap in Boostnote preferences. did you try it?

It worked!
I was not aware of it. Thank you!
