### ISSUE TITLE
Link feature requests to issues

### ISSUE THREAD

**Issue by tracker1** [BoostIO/Boostnote#334]
Would be nice if the [List of requested features](https://github.com/BoostIO/Boostnote/wiki/List-of-the-requested-features) list had backlinks into related issues. :-)

**Comment by asmsuechan** [comment]
Hi @tracker1, I've heard it from many people (https://github.com/BoostIO/Boostnote/issues/179, https://github.com/BoostIO/Boostnote/issues/41). So I'll implement it as soon as possible.

**Comment by kazup01** [comment]
Done! Thank you for your feedback! I tired my hand, so I want to drink beer🍻
