### ISSUE TITLE
Customized Background image for the Editor view

### ISSUE THREAD

**Issue by shmolf** [BoostIO/Boostnote#3343]
# Current behavior
Static background color defined by the selected CodeMirror theme.

# Expected behavior
Option for a customizable background image for the Editor input, given a provided URL of the image path.

Example:
![custom-background](https://user-images.githubusercontent.com/6433103/68176468-f38cc180-ff52-11e9-902f-5152c31ed1f9.gif)

The setting to the URL path for the background image would be in the settings, somewhere near the bottom because it's not directly relevant to other settings.

# Steps to reproduce
NA

# Environment
NA

**Comment by Flexo013** [comment]
This feature is considered to be bloat by the community. (See Slack)

Don't worry though. With the Boosnote.next there will be plugin support. And this feature sounds perfect for a plugin!

**Comment by shmolf** [comment]
@Flexo013 Is there documentation for Plugin support in Boostnote.Next?

I'll ask in the `renewal-mobile` channel in slack in case.

**Comment by Flexo013** [comment]
Not yet. The focus is on functionality that is in Boostnote and not in Boost Note.next.

You could already create an issue with the plugin idea on the other Repo.

**Comment by shmolf** [comment]
@Flexo013 [Done](https://github.com/BoostIO/BoostNote.next/issues/306)
