### ISSUE TITLE
Add 'OK' button to Export prompt

### ISSUE THREAD

**Issue by aakbar5** [BoostIO/Boostnote#3344]
# Current behavior
Export dialog does not have any ok button to close the dialog. Only ESC key works to close this dialog. In my opinion it should have ok button and enter key should work to close that dialog.
![bug](https://user-images.githubusercontent.com/16612387/68289962-08ff0a00-007f-11ea-97a6-e5ee80073862.png)

**Comment by Flexo013** [comment]
On my end there is also an `X` button:
![image](https://user-images.githubusercontent.com/4507015/68291132-7d3eab00-0089-11ea-8e81-1f3b7009bd7e.png)

But I agree that an OK button would improve this prompt.
