### ISSUE TITLE
Exported PDF content missing (except codes in blocks)

### ISSUE THREAD

**Issue by qihuazhong** [BoostIO/Boostnote#3349]
# Current behavior

## contents in exported PDF are missing

The pdf export function is broken and all contents are missing in the exported file except some codes.

<img width="329" alt="Screen Shot 2019-11-08 at 12 32 40 AM" src="https://user-images.githubusercontent.com/22231207/68452187-a95c4800-01bf-11ea-9be7-2049a260fdb2.png">

This was very frustrating. I used boostnote to write up my assignment report because of all its neat functions(katex, code blocks etc.). But I realized it too late and missed my assignment deadline and had to reinstall a V12.1.0 to get the export function working again.

# Expected behavior

Export PDF properly

## What it looks like in preview mode
<img width="778" alt="Screen Shot 2019-11-08 at 12 33 21 AM" src="https://user-images.githubusercontent.com/22231207/68452182-a4979400-01bf-11ea-986c-fdcb0419b204.png">

# Steps to reproduce

1. Copy & paste, or import this note file:
[Untitled.txt](https://github.com/BoostIO/Boostnote/files/3823116/Untitled.txt)
 
2. Export PDF 

# Environment

Version: 0.13.0
Electron: 3.0.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 19.0.0

**Comment by antiphasis** [comment]
Tested with the document on macOS Mojave, Boostnote Version 0.13.0 
PDF looks good and complete to me. 

[Untitled.pdf](https://github.com/BoostIO/Boostnote/files/3825038/Untitled.pdf)

**Comment by shmolf** [comment]
Related: https://github.com/BoostIO/Boostnote/pull/3317

**Comment by qihuazhong** [comment]
The behaviour is getting very random....

After reading your comment, I tested again, it worked. 

After a few hours, I tried again, didn't work, like this:
[Untitled.pdf](https://github.com/BoostIO/Boostnote/files/3826925/Untitled.pdf)

Tried a different note, still didn't work. 
[Untitled.pdf](https://github.com/BoostIO/Boostnote/files/3826926/Untitled.pdf)

Tried a third different note, worked fine.
[Untitled.pdf](https://github.com/BoostIO/Boostnote/files/3826930/Untitled.pdf)

Tried the 1st note, now it worked....
[Untitled.pdf](https://github.com/BoostIO/Boostnote/files/3826931/Untitled.pdf)

I am totally lost..

**Comment by qihuazhong** [comment]
not sure if this will help. but here you go. the developer tool screenshot after trying to export pdf

<img width="1204" alt="Screen Shot 2019-11-09 at 12 03 06 AM" src="https://user-images.githubusercontent.com/22231207/68523242-56989400-0284-11ea-9ddf-4f1768f8fdd9.png">

**Comment by shmolf** [comment]
@qihuazhong are those PDF examples from using an instance of my fork, or from your normal install?

**Comment by qihuazhong** [comment]
> @qihuazhong are those PDF examples from using an instance of my fork, or from your normal install?

They are from a normal install.

**Comment by shmolf** [comment]
> They are from a normal install.

Good to know. Thank you.

**Comment by Flexo013** [comment]
Will be fixed as of 0.14.0
