### ISSUE TITLE
Feature: Android & iOS Versions

### ISSUE THREAD

**Issue by tracker1** [BoostIO/Boostnote#335]
Not sure how modular the code is, but would be cool to see even Cordova versions of the app for use with iOS and Android.  :-)

Would love to see this on my phone, but will require some form of server-storage module first (Dropbox, git, gist, etc).

**Comment by asmsuechan** [comment]
Hi @tracker1, I think it sounds great, too. And I've heard from many people like https://github.com/BoostIO/Boostnote/issues/55. Please wait a while to get any mobile app because I'd like to improve desktop app first and I'm not familiar with development of mobile app.

**Comment by kazup01** [comment]
Hi @tracker1 san, @kohei-takata san said that make the mobile app using React Native. But he is busy so need help!

**Comment by BinaryWaves** [comment]
I would like to help with android programming. I am always extremely busy but will try and contribute when I can. I was kind of working on a similar app for android anyway :)

**Comment by kazup01** [comment]
Great! Thank you so much for your cooperation!
Could you join Boostnote slack group?

https://boostnote-group.slack.com/shared_invite/MTU3ODcwNzY1ODk0LTE0OTAwNjQ0NTYtMjY4NTYwOTdmYQ

**Comment by axemclion** [comment]
If you guys are writing the app in React Native, I can help with set up of a continuous build and integration system.

**Comment by kazup01** [comment]
Thank you so much for your cooperation! @axemclion 
Could you join Boostnote slack group? Let's discuss it here!


https://boostnote-group.slack.com/shared_invite/MTU3ODcwNzY1ODk0LTE0OTAwNjQ0NTYtMjY4NTYwOTdmYQ

**Comment by axemclion** [comment]
@kazup01 Joined the slack - where is the react native discussion happening ?

**Comment by kazup01** [comment]
Welcome🎉 I will talk about iOS app within this week in slack group, so please wait a while! @axemclion

**Comment by robtassl** [comment]
If you go with react native, and are looking for contributors. I could devote some time.

**Comment by evmin** [comment]
+1

**Comment by Introvertuous** [comment]
Same here, I would be very much interested in helping out with the react native version.

**Comment by dangji** [comment]
Why not make a PWA ?

**Comment by Introvertuous** [comment]
@dangji PWA is not always the best solution, where will the notes be stored?

**Comment by yashha** [comment]
Cordova has an option to access files
https://cordova.apache.org/
https://github.com/apache/cordova-plugin-file/blob/master/README.md

**Comment by kazup01** [comment]
We will release iOS and Android app within some days. Thanks for you guys waiting!
These apps are made with React Native.

**Comment by kazup01** [comment]
Android and iOS app is launched today! #831

**Comment by kazup01** [comment]
We made Boostnote Mobile to Open source.

🎉🎉 https://github.com/BoostIO/Boostnote-mobile

Since we have implemented only MVP, we need you guys help!
- Feature requests
  - [Full text search](https://github.com/BoostIO/boostnote-mobile/issues/11)
  - [Star the notes](https://github.com/BoostIO/boostnote-mobile/issues/10)
  - [Image attachment](https://github.com/BoostIO/boostnote-mobile/issues/9)

- Bug
  - [iOS app crashes when press the eye icon of note modal](https://github.com/BoostIO/boostnote-mobile/issues/1)

**Comment by kazup01** [comment]
We are waiting for you guys contribution to Boostnote Mobile. Enjoy!
