### ISSUE TITLE
AutoHotkey syntax support

### ISSUE THREAD

**Issue by Denis-net** [BoostIO/Boostnote#3351]
Hello !

Congratulations for the great App !

I would love to store [Ahk](https://www.autohotkey.com/) snippets for future references.
But I noticed that syntax don't get highlighted.
Could you add its syntax colors ?
Not sure if it could help but, you could parse this [tmLanguage](https://github.com/stef-levesque/vscode-autohotkey/blob/master/syntaxes/ahk.tmLanguage)
or supporting tmLanguages, so people that came from VSCode can extend your syntax ecosystem.
This was just an idea;

Thanks anyway 😊👍🏻.

**Comment by Flexo013** [comment]
Hi!

Thanks for the idea! We use the syntax highlighting as provided by [CodeMirror](https://codemirror.net/mode/index.html). You could look into contacting CodeMirror about supporting ahk. Once they have it working this will also become part of Boostnote.
