### ISSUE TITLE
KaTeX not rendering if I clone a note

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#3353]
# Current behavior

If I clone a note, the KaTeX doesn't render, as you can see from [this video.](https://youtu.be/OoZjR5hoifo)

# Expected behavior

The cloned note should display the same as the original one

# Steps to reproduce

1. Choose a note with KaTeX
2. Clone it
3. Open the cloned note

# Environment

- Version : 0.13.0
- OS Version and name : macOS 10.14.6

**Comment by Flexo013** [comment]
Duplicate of #2310
