### ISSUE TITLE
Add v0.13.0 release tag to this repository 

### ISSUE THREAD

**Issue by jetm** [BoostIO/Boostnote#3357]
Similar #2513 #2714 issues

For the AUR package on Arch Linux build the source from this repository. The latest version was released but the release isn't yet tagged on this repo (https://github.com/BoostIO/Boostnote/releases). Just need a tag for 0.13 version.

Thanks in advance!

**Comment by Flexo013** [comment]
@Rokt33r Can you handle this?

**Comment by Rokt33r** [comment]
Sorry I forgot to push tags! Now it is fixed!
