### ISSUE TITLE
Prettify Markdown should not update spaces in checkbox lists

### ISSUE THREAD

**Issue by fnsne** [BoostIO/Boostnote#3361]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2422%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/BoostIO/Boostnote/issues/3361)

# Current behavior
The normal checkbox by typing `- [ ]` is clickable on the rendered HTML.
![h7otx-fxd83](https://user-images.githubusercontent.com/11658267/68916715-3005bc00-07a2-11ea-9e97-64ee5a6e38e1.gif)

After using `Prettify Markdown`, the rendered HTML becomes not clickable.
![50vpf-04c36](https://user-images.githubusercontent.com/11658267/68916855-bae6b680-07a2-11ea-8154-63f5e97e9637.gif)

# Environment

- Version : 0.13.0
- OS Version and name :  Windows 10

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $22.00)

- [<img src='https://avatars2.githubusercontent.com/u/3984265?v=4' alt='r4meau' width=24 height=24> r4meau](https://issuehunt.io/u/r4meau) ($2.00)
- [<img src='https://avatars3.githubusercontent.com/u/13612118?v=4' alt='boostio' width=24 height=24> boostio](https://issuehunt.io/u/boostio) ($20.00)

### Submitted pull Requests
- [#3413 Fix prettier configuration](https://issuehunt.io/r/BoostIO/Boostnote/pull/3413)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIO/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fstanley** [comment]
+1. Came here to report the same issue

**Comment by Flexo013** [comment]
@JenyMzo you will receive the funding soon.

This issue will be fixed in the next release.
