### ISSUE TITLE
Export to pdf or any document - toc contents links are not rendered to Bookmarks

### ISSUE THREAD

**Issue by yetAnotherUsernameTaken** [BoostIO/Boostnote#3365]
# Current behavior

After exporting the markdown note to pdf, the toc contents links are not rendered as bookmarks.
They are not clickable, not navigable after exporting to pdf, in the pdf. 

# Expected behavior

The toc contents links should be rendered as bookmarks into the exported pdf document.
They should be clickable, navigable after exporting to pdf, in the pdf, atleast with respect to bookmarks . 

# Steps to reproduce
1) Make a new note in boostnote
2) generate content and toc for the note
3) export the note to pdf
4) the toc content links are missing and not clickable, not navigatbale.

They are not clickable, not navigable after exporting to pdf, in the pdf. 

# Environment

- Version : 0.13
- OS Version and name : xubuntu 18.04

**Comment by Flexo013** [comment]
I have just tried to reproduce this on Ubuntu 16.04 and the generated TOC works fine on my end when exporting to PDF:

[export.pdf](https://github.com/BoostIO/Boostnote/files/3857779/export.pdf)

Could you provide the PDF file and the raw MD that generated it?

**Comment by yetAnotherUsernameTaken** [comment]
Please find the markdown document. It will be better if the toc links are generated as bookmarks. 
I have uploaded the markdown, but with extension with txt, please change the extension and export.



[interview pdf.pdf](https://github.com/BoostIO/Boostnote/files/3858884/interview.pdf.pdf)
[interview questions.txt](https://github.com/BoostIO/Boostnote/files/3858887/interview.questions.txt)

**Comment by arcturus140** [comment]
@Flexo013 what PDF viewer are you using? I opend your attached file, there are no links in the document.

**Comment by yetAnotherUsernameTaken** [comment]
@arcturus140 

Please check the issue once again, it would be better if boostnote can render the toc links from mark down note to as pdf bookmarks. 

The links are clickable and go to respective content from first page, but again we have to comeback for the first page repeatedly.

 Instead, i propose that toc links can be rendered as bookmarks, for easy navigation in the pdf document.

**Comment by arcturus140** [comment]
title and description are misleading. Bookmarks are usually created manually by the user, AFAIK. Do you perhaps mean the PDF headers being listed in contents area? Not exactly sure how it is called.

**Comment by Flexo013** [comment]
> the toc content links are missing and not clickable, not navigatbale.

This is a problem with your PDF viewer. The TOC links are clickable in the PDF you provided.

If you would like the exported PDFs to _also_ include bookmarks like in the image below, then please make a new GitHub issue for that specific feature request, since this current one is very confusing.
![image](https://user-images.githubusercontent.com/4507015/69119632-7f483700-0a97-11ea-9c1e-1c018dc0d031.png)
