### ISSUE TITLE
Notes are gone

### ISSUE THREAD

**Issue by tyurderi** [BoostIO/Boostnote#3366]
# Current behavior
I mean, this is a nice notes taking editor but on a monday, you know, you don't expect that all your notes (at least it was one with a big roadmap) to be deleted. I haven't touched these files myself I just used Boostnote to edit the files.

I have already tried [this](https://github.com/BoostIO/Boostnote/wiki/When-your-notes-are-disappeared%3F) without success. The notes are really gone. I also looked in the trash folder - nothing.

What can I do to get the data back?

# Expected behavior
The notes shouldn't be deleted.

# Steps to reproduce
I don't have any idea how this happened.

# Environment

- Version : 0.13.0
- OS Version and name : Linux tyurderi 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Flexo013** [comment]
Have you checked your storage folder to see if it still contains the notes folder? If you can't find that anywhere then - I hate to tell you this - your notes might be lost.

I would recommend keeping important files backed up; whether it be through a cloud or other remote service. You can synchronize your Boostnote storage folder with something like Google Drive or MEGA to make sure your never lose any data.

**Comment by tyurderi** [comment]
Yeah - it's really gone. That hurts.

**Comment by Flexo013** [comment]
I'm really sorry, I wish I could help. :cry:  Best of luck with setting stuff back up!
