### ISSUE TITLE
Image disappears

### ISSUE THREAD

**Issue by ThisIsIsaac** [BoostIO/Boostnote#3374]
# Current behavior

I drag-and-drop images from the web to Boostnotes. They are inserted correctly, no problem. After closing and reopening boostnotes, this happens:

<img width="2136" alt="Screen Shot 2019-11-22 at 11 16 35 AM" src="https://user-images.githubusercontent.com/49523965/69392565-bc236080-0d19-11ea-9e00-4720b02d19b3.png">

The images disappear

Please include some **screenshots** with the **developer tools** open (console tab) when you report a bug.

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.13.0
- OS Version and name : MacOS Catalyna. 

Folder is set to a directory in iCloud.

**Comment by Flexo013** [comment]
Does this note contain more that 5 images by any chance?

**Comment by ThisIsIsaac** [comment]
no

**Comment by Flexo013** [comment]
Could try un-ticking this setting in Preferences->Interface (about halfway down):
![image](https://user-images.githubusercontent.com/4507015/69418353-ce51ce80-0d1a-11ea-879f-70abcbd09624.png)

Please let us know whether that helps at all or not.

**Comment by ThisIsIsaac** [comment]
Gave it a shot.

I'll ping you if it occurs again.

**Comment by victorbrca** [comment]
I have had the exact same issue on Windows 10 for quite a while. I paste the image in the note and it shows. However, when I change to another note and them back to the original one the image has disappeared. The attachment folder still exists, however the image is no longer there.

I will also change the  setting to see if it makes a difference for me. 

![](https://i.imgur.com/hd3vtlg.png)

![](https://i.imgur.com/6uGl68X.png)

![](https://i.imgur.com/7CzDqxd.png)

![](https://i.imgur.com/xsTzK2i.png)

**Comment by Flexo013** [comment]
For now this fix seems sufficient. I'll close this issue.

If you do have this problem AFTER applying the above fix, then leave a comment here and we'll reopen this issue.
