### ISSUE TITLE
Vim mode editing in Korean is not working occasionally

### ISSUE THREAD

**Issue by jinhongjung** [BoostIO/Boostnote#3375]
# Current behavior

Vim mode editing in Korean is not working occasionally.

# Expected behavior

That mode should work when we use any language.

# Steps to reproduce

Step 1. Open a new markdown note. 
Step 2. Push the button `i` to enter insert mode
Step 3. Write any sentence in Korean (e.g., 한국어 테스트)
Step 4. Push `esc` button to leave the mode out; then, the vim mode editing becomes broken.

# Environment

- Version : 0.13.0
- OS Version and name : mac OS Mojave version 10.14.3

**Comment by initialkommit** [comment]
What about changing input source to English from Korean after leaving insert mode?
and then it would be working I guess.

**Comment by Flexo013** [comment]
@jinhongjung Could you attempt the above suggestion?

**Comment by jinhongjung** [comment]
@Flexo013 it works after changing the input mode (vim mode works with English). Thanks! @initialkommit
