### ISSUE TITLE
deleteUnusedAttachments  is evaluated inverted --> if it's true attachments are not delete and vice versa

### ISSUE THREAD

**Issue by ehhc** [BoostIO/Boostnote#3379]
I have no idea why but i noticed that, at least for me, the deleteUnusedAttachments-preference setting   is evaluated inverted --> if it's true attachments are not delete and vice versa

**Comment by Flexo013** [comment]
Are you sure? I just tried it on Ubuntu 16.04 and it seemed to work as expected.

When this is unticked:
![image](https://user-images.githubusercontent.com/4507015/69719384-adb9b800-1110-11ea-8d2a-7251719c8b69.png)
No attachments are deleted and the amount of storage of unused attachments becomes bigger in the Storage tab.

When it is ticked all unreferenced attachments are deleted, and the aforementioned amount becomes 0 B.

**Comment by Flexo013** [comment]
Related to #3225

**Comment by ehhc** [comment]
@Flexo013 maybe i did something else wrong.. can somebody else confirm or disprove this issue?

**Comment by Flexo013** [comment]
Can confirm that on Windows the settings also work like I described above.

**Comment by ehhc** [comment]
@Flexo013 maybe it happens only on my system due to other reasons.. therefore, i'll close this issue again (if it's only my problem,..)
