### ISSUE TITLE
Question: how do I revert to a previous version?

### ISSUE THREAD

**Issue by federicochiesa** [BoostIO/Boostnote#3380]
This is not to be intended as a rant, but with the current version of Boostnote I can't export my notes to a PDF in any way: export to PDF doesn't render KaTeX, and regular print and then saving to PDF only prints the first page, and then a bunch of blank pages, and this is an issue with both macOS and Windows 10.

Can I revert to an older, known working version? 

I kept 0.11.17 on my Surface but for some reason it updated automatically.

# Environment

- Version : 0.13.0
- OS Version and name : macOS 10.14.6

**Comment by Flexo013** [comment]
You can find the downloads of 0.11.17 here:
https://github.com/BoostIO/boost-releases/releases/tag/v0.11.

There shouldn't be any auto-updating. It should only prompt you that a new one is available and ask you if you wish to install.

**Comment by arcturus140** [comment]
never read it but there's a wiki page about downgrading

**Comment by Flexo013** [comment]
https://github.com/BoostIO/Boostnote/wiki/Downgrade-Boostnote

**Comment by Sylk** [comment]
The new Boostnote doesn't work for me, and I don't support the vision of this project anymore. It doesn't allow you to use cloud storage of your own now.

**Comment by Flexo013** [comment]
@Sylk 
There are currently two versions of Boostnote that are still being updated and maintained. Choose whichever you like:
[Boostnote - the old version](https://github.com/BoostIO/boost-releases/releases/)
[Boost Note - the beta version](https://github.com/BoostIO/BoostNote.next/releases/)
