### ISSUE TITLE
Support for inline latex [Feature Request]

### ISSUE THREAD

**Issue by kingvagabond** [BoostIO/Boostnote#3384]
# Current behavior

Trying to test "inline latex" that is to mix latex block with normal texts:

![image](https://user-images.githubusercontent.com/3144518/69998883-f90f0480-151c-11ea-9f3d-b164f9dcdbc8.png)

# Expected behavior

Expect the inline latex blocks can be rendered like

![image](https://user-images.githubusercontent.com/3144518/69998965-28be0c80-151d-11ea-9dfd-07b8264a41b1.png)

# Steps to reproduce

The steps to reproduce is very simple

1.  Type normal markdown text
2.  Use $$ .. .$$ to mark an inline latex block with the text
3.  See if the latex blocks are rendered

I'd say this is the most important feature I am looking for - with more latex commands supported the better, but inline block is a must.

# Environment

- Version : latest - tried to locate a dialog to check for vesion but did not find it.
- OS Version and name : Windows 10 enterprise

**Comment by Flexo013** [comment]
This functionality already exists within Boostnote:
![image](https://user-images.githubusercontent.com/4507015/70040155-5bb6dd80-15bb-11ea-9709-8ec7a39709ed.png)

Note that you can configure the characters used for this in Preference -> Interface:
![image](https://user-images.githubusercontent.com/4507015/70040285-8ef96c80-15bb-11ea-84d6-2e920d6bde28.png)

To find the version number you can press Alt to make the menu bar appear (on Windows). Then click Help -> About, which will open a pop-up with version info:
![image](https://user-images.githubusercontent.com/4507015/70040417-d1bb4480-15bb-11ea-8c66-6c68f1026a93.png)

**Comment by Corvu** [comment]
I've had the same problem on Windows 10. Turns out that version from https://boostnote.io/ is 0.1.4, which is highly outdated.

**Comment by Flexo013** [comment]
@Corvu 0.1.4 is the new Boost Note.next (beta app). The most recent build (0.2.1) of that does support LaTeX. Check that here: 

If you wish to still use the old Boostnote, then grab the latest (0.15.1) of that here: https://github.com/BoostIO/boost-releases/releases/tag/v0.15.1
