### ISSUE TITLE
Add latex support to pdf export

### ISSUE THREAD

**Issue by yvquanli** [BoostIO/Boostnote#3391]
Could you please add latex support to pdf export, it's very important to me.
It was a raw latex code after the pdf export.

Version: Boostnote 0.13.0 
OS: windows10 1909

**Comment by yvquanli** [comment]
Yeah, I had read about the formula and some words about katex. So, I just want to know what I have to do.

**Comment by Flexo013** [comment]
Duplicate of #3342
