### ISSUE TITLE
First line of a new markdown note isn't used as title if broken markdown markup is somewhere in the body

### ISSUE THREAD

**Issue by stayen** [BoostIO/Boostnote#3395]
# Current behavior

When a new Markdown note is added and saved, it's first line isn't used as title, "Empty note" is shown instead. That happens if a broken/invalid Markdown markup is somewhere in note's body.

# Expected behavior

First note line should be used as title regardless of possible further markup problems. Alternately, warn about broken markup.

# Steps to reproduce

1. Create a note, use first line as title
2. Add several lines of text
3. Include a line containing many equal signs in a row, without a text following (such as "==========")

# Environment

- Version : 0.11.15
- OS Version and name : Ubuntu 18.04.3

**Comment by Flexo013** [comment]
I can't reproduce this on Ubuntu 16.04 with version 0.13.0.

Test note I used:
```
# Missing title test

content

breaking Markdown

==========

```

Result:
![image](https://user-images.githubusercontent.com/4507015/70631628-bab8ca00-1c2d-11ea-9888-ccd158ef5779.png)

@stayen Could you provide a note that this issue occurs with (and maybe a screenshot)? That way we can see if this issue still persists on the latest version.

You could also try updating to 0.13.0 to see if the issue persists.

**Comment by stayen** [comment]
I enclosed a screenshot with the sample note text resulting in the mentioned issue.

I will update to 0.13.0 and check whether it still happens.

![boostnote-markdown-error](https://user-images.githubusercontent.com/10847/70681853-c390b680-1c94-11ea-8a36-94ab3861495e.png)

**Comment by Flexo013** [comment]
I see now. What you are currently describing is intended behavior. In Markdown the line directly before 3 or more equals sign is considered a header. That line is empty, therefore the title is empty.

To get around this you would nee to use your own explicit header or use frontmatter.

Header example (you can use 1 to 4 `#`):
![image](https://user-images.githubusercontent.com/4507015/70723351-0dab8380-1cf9-11ea-8337-d26409889179.png)

Frontmatter example:
![image](https://user-images.githubusercontent.com/4507015/70723552-5a8f5a00-1cf9-11ea-8b87-e9db5fd49457.png)
