### ISSUE TITLE
Cannot open attachment on storage with path containing non-English letter

### ISSUE THREAD

**Issue by hiiwave** [BoostIO/Boostnote#3397]
# Current behavior

When a note with attachment saved on a storage with path containing non-English letter (e.g. `test_chinese` with Path `D:\測試` as follows), clicking on the link of this note does not open the attachment (like what happened in https://github.com/BoostIO/Boostnote/issues/2003).

**EDIT:** [Here](https://github.com/BoostIO/Boostnote/issues/3397#issuecomment-567133922) is an animation illustrating it.

![image](https://user-images.githubusercontent.com/5608511/70737893-87ba2780-1d4e-11ea-91a8-818795fb190f.png)

Currently the best solution is *right click > Show in explorer*, and open that manually in explorer.

# Expected behavior

Attachment should be able to open on storage with path containing non-English letter.

# Steps to reproduce

1. Create a storage with path containing non-English letter 
(I only confirmed Chinese letter without trying other language)
2. Create a folder in that storage and add a note
3. Add an attachment into the note
4. Click on the link, the attachment fails to open, *without error message*.

# Environment

- Version : 0.13.0
- OS Version and name : Windows 10

# Diagnosis

When doing *right click -> copy url*, it will copy something like `file:///D:/%E6%B8%AC%E8%A9%A6/attachments/f1acb39f-c175-474c-9a68-fb5523d0d3dd/61b30404.pdf`, this cannot be opened by windows explorer. The url should be `file:///D:/測試/attachments/f1acb39f-c175-474c-9a68-fb5523d0d3dd/61b30404.pdf` instead.

This should be not difficult to solve. I can try to make a PR to fix this.

**Comment by hiiwave** [comment]
This seems to be windows-only issue. This problem does not exist under mac.

**Comment by Flexo013** [comment]
I will test this under Linux tomorrow.

**Comment by Flexo013** [comment]
Hmm, under Linux I can't even get a file with only latin characters in the path to be linked properly. The URL does open fine in a browser, so this should work, but it doesn't:
![image](https://user-images.githubusercontent.com/4507015/71073416-a2423580-2180-11ea-9971-399e33f45e40.png)

**Comment by arcturus140** [comment]
I don't understand this issue. Attachments are stored under the path `:storage:`. No non-English letter will ever be generated.

![image](https://user-images.githubusercontent.com/44707562/71077792-057f9800-2180-11ea-853e-e0a7c4c57a9d.png)

![image](https://user-images.githubusercontent.com/44707562/71078008-72932d80-2180-11ea-85b4-d3d663d51a37.png)

@Flexo013 the issue is about storage location path not file links. File links follow the format:

```
[/home/a/.bashrc](/home/a/.bashrc)

[測試/äöïü](/tmp/測試/äöïü)

[測試/測試](/tmp/測試/測試)
```

all of which is working on Ubuntu with Boostnote v0.11.12.

**Comment by hiiwave** [comment]
@arcturus140 The issue is, clicking on the link of this note does not open the attachment (like what happened in #2003).

Isn't that clear to you?

**Comment by arcturus140** [comment]
@hiiwave I think we have different understanding on storage and attachment. 

It is unclear how to replicate the issue. Is it enough to create a link in a Markdown Note?

    [link](D:\Users\測試\Desktop\測試.txt)

(Note that the path must contain **non-english letter** to fail.)



I am making extensive use of links to local files on a Linux machine. I never used this on Windows OS. 

The format I am using on Linux is

    [測試](/tmp/測試/測試)

I was told on slack that `file:///` format is not supported. Unfortunately the reference is gone as I am using a free account.

**Comment by hiiwave** [comment]
Steps to reproduce this issue:

1. Create a storage with path containing non-english letter
2. Create a folder in that storage and create a note.
3. Drag a local file into the note. This will create a link as "file:///"
4. Click the link. The file should open. But the file does NOT open. That is the issue.

**Comment by Flexo013** [comment]
@hiiwave Step 3 does not create a link as "file:///" for me. It creates this:

`[export.pdf](:storage/d8f0fc49-4085-482e-a650-b9eead8690cf/3adc9fb3.pdf)`

This is on Ubuntu 16.04, with 0.13.0, and by dragging a file from Files onto Boostnote.

**Comment by arcturus140** [comment]
these are the steps I followed on Linux. The 1st image shows the result for step 1, the 2nd the result of step 2 & 3. 

@Flexo013 did you follow steps 1 and 2? Someone needs to confirm it on Windows.

**Comment by hiiwave** [comment]
I'm not sure the link format. I will confirm it later. What I confirmed is that step 4 does not open this file, and #3398 fixed this.
I can probably make a GIF later to clatify this issue.

**Comment by hiiwave** [comment]
This GIF should clarify the situation. 
`chinese_dummy` is a folder on storage `test_chinese` with path `D:\測試` which contains non-english letter.
As you can see, the file cannot be opened by clicking the link.

On the other hand, attachment on storage `test_english` can be opened successfully.

![demo_3397](https://user-images.githubusercontent.com/5608511/71108906-0f94ab80-21ff-11ea-8dd8-ebefee12d3e8.gif)

Both link can be opened after PR #3398.

**Comment by arcturus140** [comment]
@hiiwave yes, it is clear now. Thank you.

**Comment by arcturus140** [comment]
I made a couple of tests and found some more files that are not working:

# Steps to replicate

1. create a file named _%E6%B8%AC%E8%A9%A6.txt_, write `open this file` in it
2. create a file named _測試.txt_, write `do NOT open this file` in it
3. link to the file in markdown: `[link](/home/a/測試/%E6%B8%AC%E8%A9%A6.txt)`
4. click on the link, wrong file is opened: _測試.txt_

(note: storage location and path are irrelevant for this test)

# Explanation

1. the file name is valid
2. the file name is not encoded
3. the link is interpreted as encoded: instead of `%E6%B8%AC%E8%A9%A6.txt` Boostnote links to `測試.txt` which doesn't exist

# Affected Versions

OS: Ubuntu 18.10
Version: 
- Boostnote 0.11.12
- Pull request: #3398

**Comment by arcturus140** [comment]
it happens in other cases as well. If you create a folder named `%20` and use it for your storage location, any link to `:storage/` of that location will fail. 

To replicate, apply on Step 1:

1. Create a storage location in folder `%20`

then follow steps 2 - 4.

This can be replicated in Linux.

**Comment by hiiwave** [comment]
IMHO, users should not create a folder named `%20` in any case. I don't think anyone will ever do it as well.

**Comment by Flexo013** [comment]
> IMHO, users should not create a folder named `%20` in any case. I don't think anyone will ever do it as well.

While I agree with you, I do thin it would be best for the code to correctly handle this case.
