### ISSUE TITLE
Markdown to centre an image

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3399]
# Current behavior

Markdown does not allow to centre images. Sometimes there are images I'd like to centre and it looks weird with left aligned due to their ratio. 

As a workaround some suggest using HTML tag `<center>`. I am not sure if this is working in Boostnote, when I try with version 0.11.12 it doesn't:

    <center>This text is centered</center>

Additionally I added custom CSS rule:

```
center {
    text-align: center; 
}
```

Related: #1496

I would suggest to extend the markdown for images like this:

    ![Title](https://boostnote.io/assets/img/logo.png =center)

Is there currently a way to centre images in Boostnote v0.11.12?

**Comment by Flexo013** [comment]
Unsure, I will investigate this soon. Do keep in mind that I will test with 0.13.0 exclusively. (Since we'd everyone to use the most up to date version.)

**Comment by Flexo013** [comment]
@arcturus140 Is there a specific reason as to why you closed this issue?

Do you no longer need/want this feature? Or did you find a different way to get this working?

**Comment by arcturus140** [comment]
@Flexo013 happy new Year!

Personally I am still interested in this feature.

Issue has been closed for the following reason:

- it doesn't seem an important issue
- lack of response / interest by others

In the next occation I'll test different ways to get it working, if there is any. When I have something working I'll share results here.

Feel free to reopen the issue if you think it should be!

**Comment by Flexo013** [comment]
@arcturus140 Happy new year to you too! 🎆 

Alright, that makes sense. We'll see how things go.
