### ISSUE TITLE
bug report: an error occurred when updating the app

### ISSUE THREAD

**Issue by askg7dawn** [BoostIO/Boostnote#34]
@Rokt33r 
Hi, i love your Boostnote.app, and i wanna thank you so much for your contribution on this app.
when i updated the app (from 0.5.11 to 0.5.12), an error occurred.

![2016-05-16 19 33 38](https://cloud.githubusercontent.com/assets/14368425/15322369/560c1b5c-1c77-11e6-9f4e-0f520210b79a.png)

after rebooting the app, the update was completed.
Now i can use Boostnote(0.5.12) without any incident.
i don't know what it is but want to share this bug report.

at last, my environment is as follows:
- Mac yosemite (10.10.5)
- node.js (v0.10.40)

**Comment by Rokt33r** [comment]
Currently I don't know why it occurs... we should keep watching.
I'm sorry for make you feel uncomfortable.

**Comment by Rokt33r** [comment]
I think the problem is due to the internet connection.
And, I'd made the app handling errors from `electron-gh-releases`. So, this error won't be seen anymore.
