### ISSUE TITLE
chinese language support 

### ISSUE THREAD

**Issue by duansheli** [BoostIO/Boostnote#3401]
appearance language has 
* english
* japanese 

think about chinese

**Comment by Flexo013** [comment]
Boostnote is already available in Chinese:

![image](https://user-images.githubusercontent.com/4507015/71264994-905dbf80-2345-11ea-95fa-7d3be850f10a.png)

**Comment by duansheli** [comment]
i saw the i18n file 
but select option only hava two 
system  windows 10


![image](https://user-images.githubusercontent.com/8579595/71307730-9d55de00-242d-11ea-9d89-79f73286f498.png)

**Comment by duansheli** [comment]
@Flexo013 

![image](https://user-images.githubusercontent.com/8579595/71307758-f02f9580-242d-11ea-850b-d000470433b1.png)
open in browser

**Comment by duansheli** [comment]
in browser 
login by github account 
![image](https://user-images.githubusercontent.com/8579595/71307800-72b85500-242e-11ea-988a-22ecd61ea592.png)

**Comment by Flexo013** [comment]
@duansheli These are issue of Boost Note (aka BoostNote.next) and not Boostnote.
