### ISSUE TITLE
Export error when exporting all file types md\txt\html\pdf

### ISSUE THREAD

**Issue by nefusmzj** [BoostIO/Boostnote#3403]
# Export error when exporting md\txt\html\pdf

Export error when exporting all types (md\txt\html\pdf)，ErrorBox show "Callback must be a function!"。

![export call back error](https://github.com/nefusmzj/ImageCache/raw/master/export.png)

![export call back error2](https://github.com/nefusmzj/ImageCache/raw/master/callbackerror.png)

# Environment

- Version : Boostnote 0.13.0
- OS Version and name : Windows10 x64 1809

Thank You

**Comment by Flexo013** [comment]
Duplicate of #3262
