### ISSUE TITLE
Show vim status line

### ISSUE THREAD

**Issue by Cosmicist** [BoostIO/Boostnote#3405]
# Expected behavior

When having vim key mapping enabled, it would be useful to have the status line show the command you're using. For example, if I want a to do a regexp search and replace like this `:%s/foo/bar/g`, it would be useful to see what I'm typing. The command works, but what you type it is not displayed.

# Steps to reproduce

1. Enable vim keymap
2. Type `[esc]` to make sure you're in `normal` mode
3. Type the desired vim command (e.g: `:%s/foo/bar/g`)

# Environment

- Version : 0.13.0
- OS Version and name : Ubuntu 19.04

**Comment by RyanGreenup** [comment]
I use vim in Boostnote all the time, in both v 13 and 14 commands do appear in the bottom left of the editor, I'm using the `.deb` packages on Ubuntu 19.10 with Cinnamon DE.

I often use it to do things like `: imap jj <Esc>` and search/replace.

Refer to my screenshot and you should see in the bottom left:
![image](https://user-images.githubusercontent.com/47832594/71895071-eef9aa80-3147-11ea-8dde-c74d0ea43b7d.png)

**Comment by Cosmicist** [comment]
looks like I had an older version, werid, I updated it and it works fine now. thanks!
