### ISSUE TITLE
Inequality sign not rendered correctly in pdf.

### ISSUE THREAD

**Issue by IceCreamWW** [BoostIO/Boostnote#3412]
First thank you for making such a great app. I've noticed in the latest update many bugs are fixed (such as TOC link and pdf for math formula). 

The problem I encounter is the appearance of rendered `inequality sign` both in app and in exported pdf.

# Current behavior

```tex
$$
a \ne b
$$
```
produced following results:

In boostnote:  (slash seems weird)
![image](https://user-images.githubusercontent.com/20967938/71765512-ccda0f80-2f30-11ea-8bd9-b8c4bbe5dd5a.png)

In pdf:

![image](https://user-images.githubusercontent.com/20967938/71765522-e7ac8400-2f30-11ea-80db-d284525cb9c9.png)

# Expected behavior

Here is an example inequality sign rendered with xelatex

![image](https://user-images.githubusercontent.com/20967938/71765617-1ecf6500-2f32-11ea-85c7-766b379a2ba2.png)

# Environment

- Version : 0.14.0
- OS Version and name :  macOS 10.15.2 Catalina

**Comment by Flexo013** [comment]
Thanks for the kind comments and glad to hear that you really like the app!

This bug is already known, see #3252, but this does confirm it still exist in the latest version.
