### ISSUE TITLE
Image file disappear randomly 图片随机消失

### ISSUE THREAD

**Issue by lxcypp** [BoostIO/Boostnote#3424]
# Current behavior
Paste image file into note and exit app.
The image file disappear the next time when I open app.
It happened randomly.

粘贴进去的图片莫名其妙的下一次打开时就不见了，图片文件也消失了，但是文档里的引用还在。
遇到了很多次了。退出程序之前图片还在，下一次打开就不见了。
随机出现。

# Expected behavior

As long as the image reference exists, do not delete the image file.

只要文档里的引用存在，就不要删除文件

# Steps to reproduce

It's total randomly .

# Environment

- Version : 0.14
- OS Version and name :
Boostnote for Mac

**Comment by AndrinGautschi** [comment]
I struggle with that too. I assume it has something to do with the copy and paste store but I really cannot test it either. Unfortunately boostnote is unusable like that.

**Comment by AndrinGautschi** [comment]
I found an issue that might help you: https://github.com/BoostIO/Boostnote/issues/3203

I managed to restore the lost pictures by going (I have synced the boostnote storage folder with OneDrive) into OneDrive bin an there I can restore the deleted files.

**Comment by Flexo013** [comment]
@lxcypp @AndrinGautschi Do you have more than 5 images in the note that has this problem?

**Comment by AndrinGautschi** [comment]
@Flexo013 No, I do not. It happened to notes with various amounts of pictures but all below five. 

PS: boostnote is at 0.14.0. I work on MacOS Catalina 10.15.2

**Comment by lxcypp** [comment]
> @lxcypp @AndrinGautschi Do you have more than 5 images in the note that has this problem?

No matter more than 5 or less than 5 it happened.

**Comment by lxcypp** [comment]
> I found an issue that might help you: #3203
> 
> I managed to restore the lost pictures by going (I have synced the boostnote storage folder with OneDrive) into OneDrive bin an there I can restore the deleted files.

I also save the storage in iCloud. But unfortunately I can't find the deleted file in iCloud  :(

**Comment by lxcypp** [comment]
v0.13.0 doesn't have this problem.
I've already change back to this older version.

**Comment by VishwasGagrani** [comment]
https://github.com/BoostIO/Boostnote/issues/3203

Comment the code responsible for this. I am doing the same for every update of boostnote. It seems developers have not yet been able to solve the issue.

**Comment by Flexo013** [comment]
@VishwasGagrani If you know the code responsible for this bug then please submit a PR so we can fix this issue for everybody.

@lxcypp @AndrinGautschi Uncheck this option and see if the problem still occurs.
![image](https://user-images.githubusercontent.com/4507015/72006410-d5dc2100-324f-11ea-8832-a42d71cd8ecd.png)

If you still experience the issue then comment here and I will reopen this issue.

**Comment by lxcypp** [comment]
> @VishwasGagrani If you know the code responsible for this bug then please submit a PR so we can fix this issue for everybody.
> 
> @lxcypp @AndrinGautschi Uncheck this option and see if the problem still occurs.
> ![image](https://user-images.githubusercontent.com/4507015/72006410-d5dc2100-324f-11ea-8832-a42d71cd8ecd.png)
> 
> If you still experience the issue then comment here and I will reopen this issue.

I don't think it's ok to uncheck this option.

**Comment by lxcypp** [comment]
> @VishwasGagrani If you know the code responsible for this bug then please submit a PR so we can fix this issue for everybody.
> 
> @lxcypp @AndrinGautschi Uncheck this option and see if the problem still occurs.
> ![image](https://user-images.githubusercontent.com/4507015/72006410-d5dc2100-324f-11ea-8832-a42d71cd8ecd.png)
> 
> If you still experience the issue then comment here and I will reopen this issue.

I'll try this. 

But I don't think it's ok to uncheck this option to solve this problem.
We DO NEED boostnote delete the useless attachment file automatically.

**Comment by VishwasGagrani** [comment]
> @VishwasGagrani If you know the code responsible for this bug then please submit a PR so we can fix this issue for everybody.
> 
 I have already mentioned it there:
https://github.com/BoostIO/Boostnote/issues/3203#issuecomment-518583535

As a temporary solution I searched Main.js in "compiled" folder and commented this section:

files.forEach(function (file) {
if (!attachmentsInNoteOnlyFileNames.includes(file)) {
/var absolutePathOfFile = path.join(targetStorage.path, DESTINATION_FOLDER, noteKey, file);
fs.unlink(absolutePathOfFile, function (err) {
if (err) {
console.error('Could not delete "%s"', absolutePathOfFile);
console.error(err);
return;
}
console.info('File "' + absolutePathOfFile + '" deleted because it was not included in the content of the note');
});/
}

**Comment by Flexo013** [comment]
@lxcypp We can't reproduce this issue, so it's hard to figure out exactly what is causing it and how to fix it. For the time being we have introduced that checkbox to prevent this bug from occurring, and only requiring the user to clear their unused attachments every so often.

@VishwasGagrani Unchecking the option I referenced does the exact same thing. It disables the clearing of attachments, so the bug can't occur. This will also be consistent across version, so you won't need to change the compiled file every update.

**Comment by emcangi** [comment]
Just wanted to add that I have unchecked the 'delete unused attachments' box, but I am still getting random image removal from the storage. OS Ubuntu 18.04.3.

**Comment by VishwasGagrani** [comment]
@emcangi Try this way to stop deletion:
 https://github.com/BoostIO/Boostnote/issues/3203#issuecomment-518583535

**Comment by arelra** [comment]
Same issue on Mac Sierra, Boostnote 0.15.1

Dragging images into a note and after moving to another note and returning (without any edits) it will have disappeared.

I have unchecked the 'delete unused attachments' box but bug is still happening.

Could you share any progress on this bug please? I see it has been raised multiple times.

I really like the application and have invested a lot of time creating notes but this is forcing me to consider moving to another app.

Thanks

**Comment by Flexo013** [comment]
@arelra Check #3348

**Comment by arelra** [comment]
Hi @Flexo013 this issue occurs regardless of the number of previous notes.

From a user pov it seems intermittent with no discernible steps to reproduce.

Can we can gather root cause analysis that I've seen spread over multiple tickets? I'm sure there are many of us that would like to help fix this.

I've seen you mentioned you were unable to reproduce the issue.

Do you have automated integration tests that could help to reproduce?

**Comment by Flexo013** [comment]
As mentioned in #3348 is does not depends on the previous number of notes, but on the already present amount of images within a specific note.

So far the amount of images seems to be the only thing that can consistently reproduce this. You can uncheck this option in preferences to suppress the bug:
![image](https://user-images.githubusercontent.com/4507015/77757672-f38c7b80-7031-11ea-8c4e-a3c751c22425.png)

I think the analysis efforts are focused in the issue that I have linked.

To my knowledge the integration tests have not yet encountered this issue.

**Comment by arelra** [comment]
Sorry I have edited - I did mean number of images within a note.

As mentioned previously unchecking that option has no effect.

Given the number of users reporting this issue it would seem your tests are not capturing this workflow.

I don't see any automated functional tests in the repo - ie selenium or cypress tests. Is this something that other developers could contribute to?

Thanks

**Comment by Flexo013** [comment]
@Rokt33r would know more about this.

**Comment by Rokt33r** [comment]
@arelra 
> I don't see any automated functional tests in the repo - ie spectron, selenium or cypress tests. Is this something that other developers could contribute to?

Yes it is. But I'm not sure how should I do e2e test with electron. Do you have any idea?
