### ISSUE TITLE
Questions about this application

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [BoostIO/Boostnote#3431]
I did extensive research, and I found that this application is what suitable for my needs, because it supports offline storage, and Supports Linux at the same time, but I am little confused about this application, so I will ask some question, and I hope people here can help me figuring things out.

**First:** I don't know where the application saves the local storage, I tried to search my computer by the name of the storage, and I found nothing!

**Second:** The **file** menu only contains the command: **Quit**, so I am confused about: how can I import external notes?! and how can export my local storage?!

**Third:** The cloud storage has two options, GitHub, and entering an email to register a new account for this application, but I heard that this application supports OneDrive, and Google Drive. Did that change?

**Fourth:** the **help** menu contains the command: **Learn more** which redirects me the official website, and not a help guide!

**Fifth:** the help menu doesn't contain **About**  which can be found in every application to give a little details about this application like the current version, the company name/developer name, the copyrights, and the license.

Sorry for asking a lot of questions, and I hope that my questions are reasonable.

**Comment by arcturus140** [comment]
> because it supports offline storage, and Supports Linux at the same time

Yes, Boostnote meets all requirements

1. notes are stored in plain text as cson files in your storage location. Add a storage location in your preferences. 

2. the file menu contains commands for note manipulation, import, export, print and preferences

3. the application does not directly support google drive, dropbox, etc but you can use them to synchronize your notes. Be aware that conflicts may occur.

4. You are correct, the help menu is indeed not helpful at all. [You can find the Wiki for Boostnote here](https://github.com/BoostIO/Boostnote/wiki). Adding it to the help menu is a very good idea, I'll make a feature request for it. 

5. the about has been added to the menu [since version 0.12.0](https://github.com/BoostIO/boost-releases#01202019724)

**Comment by ahmed-elsayed2017** [comment]
> 1.notes are stored in plain text as cson files in your storage location. Add a storage location in your preferences.
I can't find any option inside Preferences to add a storage, or any option to change the location of local storage, but I found **Import** inside Preference which gives me the option to import .cson file a storage that I created before.

> 2.the file menu contains commands for note manipulation, import, export, print and preferences.
Here is a screenshot that preview the file menu:

![Boost Note_File](https://user-images.githubusercontent.com/29783425/72549765-fa607a80-3899-11ea-85eb-befb2d5d7daf.png)

5. the about has been added to the menu since version 0.12.0

I found **About** inside Preferences, and that is the last place I thought it could be there!

![Boost Note_About](https://user-images.githubusercontent.com/29783425/72549777-00565b80-389a-11ea-8b52-f8015c4c3b18.png)

**Comment by arcturus140** [comment]
I am not familiar with Boostnote.next. I recommend you [to use Boostnote, instead](https://github.com/BoostIO/boost-releases/releases/). I think it better fits your requirements, at least for the time being.

**Comment by ahmed-elsayed2017** [comment]
> I am not familiar with Boostnote.next. To my knowledge, local storage is not supported yet, but I am not up to date with development.
> 
> I recommend you [to use Boostnote, instead](https://github.com/BoostIO/boost-releases/releases/). I think it better fits your requirements, at least for the time being.

That one is better, and it has .deb files instead of .AppImage files which integrates nicely with my OS. Thanks for you help.
