### ISSUE TITLE
Enabling dangerous HTML tags

### ISSUE THREAD

**Issue by katarkor** [BoostIO/Boostnote#3432]
Hi,
I'm new to Boostnote and so far I'm very happy with it, but I can't find the option to enable dangerous HTML tags to change things like font color. In the previous version (0.13.0) it was in Preferences -> Interface -> Sanitization, but the latest version doesn't seem to have that option. 

# Environment

- Version : 0.1.4 (shouldn't it be 0.14.0?)
- OS Version and name : macOS Catalina 10.15.2

**Comment by MiloTodt** [comment]
![image](https://user-images.githubusercontent.com/21070668/72570109-d50b4680-3870-11ea-9657-5e83da0e8695.png)


    Version : 0.1.4.0
    OS Version and name : Ubuntu 19.10

**Comment by katarkor** [comment]
Ok, now I know what happened: I downloaded Boost Note, not Boostnote, apparently that's what you get when you download from the official website https://boostnote.io/
What's interesting is that the website links you to this github repo, not https://github.com/BoostIO/BoostNote.next as it should. Since the name is basically the same and I'm new I got confused. Thanks for your answer anyway :)

**Comment by arcturus140** [comment]
> What's interesting is that the website links you to this github repo, not https://github.com/BoostIO/BoostNote.next as it should. 

in this case it should be fixed
