### ISSUE TITLE
Add the Wiki to the help menu

### ISSUE THREAD

**Issue by arcturus140** [BoostIO/Boostnote#3435]
# Current behavior

When the user is looking for help in the help menu it would be useful to have a link to [the Wiki for Boostnote](https://github.com/BoostIO/Boostnote/wiki). 

# Steps to reproduce

1. menu -> help

# Environment

- Version : 0.11.12
- OS Version and name : 19.10 Ubuntu

**Comment by Flexo013** [comment]
Fix has been merged. Next release (0.15.0) will have this feature.
