### ISSUE TITLE
Backspacing text in the Search bar changes focus to a found note

### ISSUE THREAD

**Issue by alanschneider** [BoostIO/Boostnote#3436]
# Current behavior
When backspacing text in the Search bar, focus is lost and goes to one of the found notes. This  causes the user to backspace text out of the focused note.

This occurs when the user types enough of a matching term to cause a note to be found, then types more to have no results, then backspaces the non-matching characters

# Expected behavior
Focus is **not** moved from the Search bar to a found note.

# Steps to reproduce

1. Type something into the Search bar that matches multiple notes.
2. Type more letters that cause the Search to show no results
3. Begin backspacing until matches are found again
4. Once matches are found, the focus will change from the Search bar to the first found note

# Environment

- Version : Boostnote 0.11.15
- OS Version and name : Ubuntu 18.04.3 LTS

**Comment by MiloTodt** [comment]
Unable to duplicate with the current version of Boostnote 0.14.0 on Ubuntu 19.10

**Comment by Flexo013** [comment]
This bugs was fixed in the past. Please update your Boostnote to the latest version: https://github.com/BoostIO/boost-releases/releases/

**Comment by alanschneider** [comment]
The update fixed it. Thanks!
