### ISSUE TITLE
Backslashes get doubled when I copy paste LaTeX

### ISSUE THREAD

**Issue by shoshievass** [BoostIO/Boostnote#3449]
# Current behavior

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/3093378/73297251-12040100-41c0-11ea-9449-9b7df6a34bdd.png">

# Expected behavior

When I copy/paste Latex (even from the same Boostnote document), the backslashes ('\') get doubled up. This shouldn't (ideally) happen.

# Steps to reproduce

1. Write some Latex with backslashes (e.g. $\frac{a}{b}$)
2. Copy-paste it in Boostnote
3. 

# Environment

- Version :0.14.0
- OS Version and name : MacOS Mojave

**Comment by Flexo013** [comment]
There are 2 different ways of pasting. Ctrl + V and Ctrl + Shift + V. One tries to format and escape the text/code that you paste, thus resulting into the backslashes being escape with another backslash. The other one does nothing and pastes the raw text.

Try the other one. Hopefully this works.
