### ISSUE TITLE
Doesn't open in macOS Catalina

### ISSUE THREAD

**Issue by codenift** [BoostIO/Boostnote#3452]
# Current behavior
Doesn't work on Catalina.

Shows error message saying software needs to be updated.

![Screen Shot 2020-01-29 at 10 09 08 PM](https://user-images.githubusercontent.com/6990593/73417168-2beb3400-42e5-11ea-87a2-a164619f97a5.png)

# Expected behavior

Open application.

# Steps to reproduce

1. Downloaded app from Boostnote website
2. Dragged to Application and tried to open, shows error

# Environment

- Version :
- OS Version and name :
10.15.2 (macOS Catalina)

**Comment by Lucarus** [comment]
That's a security feature of macOS.
Here is a tutorial on how to allow Boost Note https://www.macworld.co.uk/how-to/mac-software/mac-app-unidentified-developer-3669596/

I would not recommend to allow Apps from Anywhere, just the apps you want to run.

**Comment by codenift** [comment]
You are right. I should've known. Thanks.
