### ISSUE TITLE
Inconsistent Dropdown styling

### ISSUE THREAD

**Issue by TheAifam5** [BoostIO/Boostnote#3455]
# Current behavior

Styling of the dropdown is not consistent with the operating system theme and the dark theme selected in the application.

![app-theme](https://user-images.githubusercontent.com/2192274/73599150-96e47700-4540-11ea-9e2f-b56bde58d280.png)

# Expected behavior

In dark mode, dropdowns should be dark, not white.

![system-theme](https://user-images.githubusercontent.com/2192274/73599151-9fd54880-4540-11ea-94f2-03352ce6a924.png)

# Steps to reproduce

1. Gnome with Dark theme
2. Click on "Updated" in "Search"
3. For comparison, use right-click on the "Trash"

# Environment

- Version : 0.14.0
- OS Version and name : ArchLinux with Gnome

**Comment by Flexo013** [comment]
Solved as of 0.15.0
