### ISSUE TITLE
Background-color is not retained when exporting to PDF.

### ISSUE THREAD

**Issue by joelmagner** [BoostIO/Boostnote#3458]
# Current behavior

Does not retain background color when exporting to PDF.

# Expected behavior
Color Should Persist.
# Steps to reproduce

1.  Enable custom CSS.
2.  Create a custom background-color.
3.  Export to PDF.

# Environment

- Version : 0.14.0
- OS Version and name : Windows 10.

**Comment by Flexo013** [comment]
Duplicate of #3125
