### ISSUE TITLE
Feature: Add the function of exporting a markdown file as a pdf

### ISSUE THREAD

**Issue by Kajiyu** [BoostIO/Boostnote#346]
I want to export my markdown file as a pdf.

**Comment by kazup01** [comment]
Yeah it's exactly as you said. We want to add it but we have other priorities.
If possible, could you send PR to us?

**Comment by asmsuechan** [comment]
Hi, @Kajiyu! I've heard it from a lot of people https://github.com/BoostIO/Boostnote/issues/133#issuecomment-287870588, https://github.com/BoostIO/Boostnote/issues/52, and https://github.com/BoostIO/Boostnote/issues/51. I also want it, but it's quite complicated. Perhaps it takes a while. Could you add it?

**Comment by Kajiyu** [comment]
Of course😃 I'm trying it😃

**Comment by kazup01** [comment]
Great🎉

**Comment by Kajiyu** [comment]
I tried to make an 'add pdf-export' function, but when I debug with the command `grunt pre-build`, the screen does not update from the initial state, like this. Do you have anything to think about?<br/>
<img width="1182" alt="2017-03-21 17 21 58" src="https://cloud.githubusercontent.com/assets/12061702/24138269/f39508e0-0e5a-11e7-86cb-6a3844e20bde.png">
Also, I found this message while building app, is 'auth_code.json' needed to debug?
```
secret/auth_code.json is not found. CodeSigning is not available.
Running "pre-build" task

Running "compile" task
node_modules/.bin/webpack --config webpack-production.config.js
Hash: 58bc1566479ec76dcf25
Version: webpack 1.14.0
Time: 29577ms
    Asset     Size  Chunks             Chunk Names
  main.js  1.42 MB       0  [emitted]  main
finder.js  1.03 MB       1  [emitted]  finder
    + 799 hidden modules


Running "pack:osx" (pack) task
/Users/YumaKajihara/oss/Boostnote/dist
Downloading electron-v1.2.8-darwin-x64.zip
[============================================>] 100.0% of 42.74 MB (3.98 MB/s)
Packaging app for platform darwin x64 using electron v1.2.8
```

This is my commit, please watch when you are free.
[https://github.com/Kajiyu/Boostnote/commit/18da79c8a6604442aa80dd2372af876ca1d66829](https://github.com/Kajiyu/Boostnote/commit/18da79c8a6604442aa80dd2372af876ca1d66829)

**Comment by asmsuechan** [comment]
you don't need to build, could you run these commands in 2 terminals?

```
$ npm run webpack
$ npm run hot
```

**Comment by Kajiyu** [comment]
Thank you!
When I run `npm run webpack`, the message 'webpack: bundle is now VALID.' is not shown, and the process has been continuing like the picture below.

<img width="849" alt="2017-03-21 17 38 48" src="https://cloud.githubusercontent.com/assets/12061702/24138871/47e94b8e-0e5d-11e7-838a-c943ff8dcd68.png">

Two js files(finder.js, main.js) is built successfully.
When I run `npm run hot`, the same thing happens as above...

**Comment by asmsuechan** [comment]
Debug it 😃 At least current master, Boostnote works well. I assume it's because of `markdown-pdf`.

**Comment by asmsuechan** [comment]
An error occurs at [this line](https://github.com/raszi/node-tmp/blob/master/lib/tmp.js#L468), it's a node module which dependents with `markdown-pdf` (refs: https://github.com/alanshaw/markdown-pdf/blob/master/index.js#L8).

**Comment by asmsuechan** [comment]
@Kajiyu What's going on?

**Comment by Gernatch** [comment]
No constructive feedback to offer. Just want to +1 on the suggestion to accomplish this goal. Also, first time speaking up here...I'm highly impressed with the direction of this software.

**Comment by asmsuechan** [comment]
@Gernatch Thanks for the comment. I try to implement it.e

**Comment by asmsuechan** [comment]
@Kajiyu As also written above, this feature request is duplicated. If you won't response in a day, I'll close this issue.

**Comment by asmsuechan** [comment]
I close because of no reaction.
