### ISSUE TITLE
CodeMirror rendering error in code editor

### ISSUE THREAD

**Issue by Aaron-Bird** [BoostIO/Boostnote#3467]
# Current behavior
CodeMirror rendering error in code editor.  
Caused incorrect "highlight" and "foldGutter".  

# Steps to reproduce

Test text:

    ```js
 
    ```

    ## test

![1](https://user-images.githubusercontent.com/25508292/74399253-22210f00-4e55-11ea-81a3-29c68557cd1b.gif)

# Environment

- Version :4.2.12
- OS Version and name : Windows

**Comment by Aaron-Bird** [comment]
Maybe the custom mode "Boost Flavored Markdown" caused the error.  

https://github.com/BoostIO/Boostnote/blob/53aa142d94d260926de2f206f2a95420a8b7a00f/extra_scripts/codemirror/mode/bfm/bfm.js

I don't understand why it works fine after adding breakpoint on line 90.

```js
 if (state.fencedEndRE && stream.match(state.fencedEndRE)) {
```


Temporary solution(Don't know what bugs will cause):  
Delete the objects in line 52.Replace with.

```js  
return baseMode
```

Hope someone can fix this bug.

**Comment by Flexo013** [comment]
I can't seem to reproduce this error with Boostnote 0.14.0 on Windows 10.
![image](https://user-images.githubusercontent.com/4507015/74489094-7e6f4780-4ec4-11ea-81d9-569637d63867.png)

Could provide the Boostnote version you are using (the one you posted is the Electron version)?

**Comment by Aaron-Bird** [comment]
@Flexo013 
Need to manually add characters in the backquote.  
Trigger the bug process in the above gif.  

![74399253-22210f00-4e55-11ea-81a3-29c68557cd1b](https://user-images.githubusercontent.com/25508292/74491974-4984e400-4f08-11ea-871b-52577759599c.gif)  

Step 1, Enter the following characters:

    ```js

    ```

    ## test

![1](https://user-images.githubusercontent.com/25508292/74491787-987e4980-4f07-11ea-905b-4f2a5dce07e2.PNG)  


Step 2,Type the letter "a" in backquote:  
![2](https://user-images.githubusercontent.com/25508292/74491938-265a3480-4f08-11ea-823c-4d9b3009a0e7.PNG)  

program version:  4.2.12
![3](https://user-images.githubusercontent.com/25508292/74492033-7cc77300-4f08-11ea-89d4-8bfbd9a78027.PNG)

**Comment by Flexo013** [comment]
Confirmed on Windows 10 with Boostnote 0.14.0

**Comment by Aaron-Bird** [comment]
Looks like the bug has been fixed
