### ISSUE TITLE
Window bug freeze 

### ISSUE THREAD

**Issue by MarkoShiva** [BoostIO/Boostnote#3470]
# Current behavior

Window freezes once you enter something as code snippet with 
```
code
```
and try to click copy next to code block
At that point window bugs and it stay in the click finger mode for next 10 seconds 
durrng that time not a single thing in the editor is clickable.

# Expected behavior

It should work once its copied it should copy to clipboard and continue working.

# Steps to reproduce

1.  create markdown note 
2.  add a code snippet with  multiline ticks``` ```  
3.  click on copy next to the code snipet 
 window will freeze and icon will be point finger for  around 10 seconds 

# Environment

- Version : 0.14.0
- OS Version and name : ArchLinux

**Comment by AWolf81** [comment]
@MarkoShiva  can you please create a screen-recording that's showing the issue? I couldn't recreate the behavior on Windows - maybe I did it differently or it's not a problem on Windows.
So a recording would be great to see how you did it.

**Comment by arcturus140** [comment]
@AWolf81 note that he is using linux, not windows.

**Comment by Flexo013** [comment]
I can't reproduce this on Linux either.

**Comment by MarkoShiva** [comment]
ok I'll try to make a recording and upload it.

**Comment by MarkoShiva** [comment]
Here you go 

This is a bug and performance issue for over 30 seconds it stays as a hand cursor before moving to edit mode after doing copy.

[Link to video](https://imgur.com/a/DHqqlM2)

**Comment by ZeroX-DG** [comment]
I think this is the same issue as this one:
https://github.com/BoostIO/Boostnote/issues/2988

**Comment by Flexo013** [comment]
That's very likely. Let's continue over there. If it does end up being two different causes then we can reopen this.
