### ISSUE TITLE
[FEATURE REQUEST] Use Github Styles for general preview

### ISSUE THREAD

**Issue by bdbch** [BoostIO/Boostnote#348]
So I love the tool but I think the preview theme is kind of strange. If you compare it to the Github stylesheet, `h1` and `h2` both have underlines which help the document to get structured.

How about just using githubs styles for Markdown Preview instead of using a your own CSS?

**Comment by VoLuong** [comment]
Personal Opinion : Github style should be a theme, not  a standard to be compared with.

**Comment by huettenhain** [comment]
I must say I actually like the current style - bootstnote used to have those underlines as well, and I didn't like them. I guess the best way to satisfy everyone would be to allow the user to create their own theme, and publish the currently built-in themes as possible themes to download.

**Comment by asmsuechan** [comment]
Hi, @db2k, @VoLuong and @huettenhain. Thanks for your opinion. Yes, the preview theme is not customizable for now. I would say I don't need to change the **default** theme as same as GitHub.

> to allow the user to create their own theme

True, I think so it may be useful and should be customizable. Actually, I'm attempting to implement it by `~/.boostnoterc` https://github.com/BoostIO/Boostnote/issues/302. What do you think it?

**Comment by kazup01** [comment]
I close this issue because it has been neglected for a long time. Please reopen it if necessary.
