### ISSUE TITLE
CTRL-Right toggles Left-to-Right 

### ISSUE THREAD

**Issue by cdokolas** [BoostIO/Boostnote#3485]
# Current behavior

CTRL-Right should only move the cursor one word to the right.

# Expected behavior

Cursor is moved one word to the right but text direction is also toggled (right-to-left vs left-to-right)

# Steps to reproduce

Type some text. Try to move right by a word using CTRL-Right.

# Environment

- Version : 0.15
- OS Version and name : Windows 10 (64-bit)

**Comment by Rokt33r** [comment]
I'll release a fix for this issue on this Sunday. (I should start working on this on this weekend. So if there are any people want to tackle before I do, please leave comments here!)
