### ISSUE TITLE
Can't scroll in sidebar

### ISSUE THREAD

**Issue by Flexo013** [BoostIO/Boostnote#3486]
# Current behavior

Can't scroll in the sidebar so not all folder are viewable:
![image](https://user-images.githubusercontent.com/4507015/75180898-61950880-573d-11ea-99f2-6e926b249ffc.png)

# Expected behavior

The ability to scroll in the sidebar

# Steps to reproduce

Have more folder than the screen is long.

# Environment

- Version : 0.15.0
- OS Version and name : Windows 10

**Comment by gator-mk** [comment]
I am on macOS Catalina 10.15.3 and I am also facing this issue since upgrading to 0.15.0.

**Comment by rwperrott** [comment]
Also on Windows 10, and this bug is very annoying because I need long lists because it doesn't support nested folders, like BoostNote.next, which I dislike, so downgrade time, again...

**Comment by mondeja** [comment]
In Ubuntu 18.10 I am also facing this issue since after upgraded to v0.15.0.

**Comment by bmckissen** [comment]
Same issue on macOS Mojave 10.14.6 after upgrade to v0.15.0

**Comment by Rokt33r** [comment]
Fixed by https://github.com/BoostIO/Boostnote/pull/3490
The fix will be deployed on this Sunday.
