### ISSUE TITLE
Add a setting to hide "rtl toggle button"

### ISSUE THREAD

**Issue by Aaron-Bird** [BoostIO/Boostnote#3493]
Feature request:
Add a setting to hide "rtl toggle button"

In most cases this button is rarely used, and it is easy to confuse with the toggleMode Button.
![1](https://user-images.githubusercontent.com/25508292/75231542-957d3600-57f0-11ea-979b-2fdb866f6fe6.PNG)

**Comment by Flexo013** [comment]
Agreed that this button should not be in your face like it currently is. (Much less should it hijack a default key combo #3485.)

Adding this to the top menu bar in view should be sufficient.

**Comment by Rokt33r** [comment]
I'm sorry for making this trouble. I didn't review enough the PR, introducing RTL, at the first time. I totally agree with you. It must be presented optionally. This will be solved on this Sunday with #3485.
