### ISSUE TITLE
No Scroll Bar in Left Dir Navigate Window

### ISSUE THREAD

**Issue by StandOutstar** [BoostIO/Boostnote#3496]
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

## Desktop/Web
- Boost Note.next version: 0.15.0
- OS version and name: MacOS 10.15.3

## Mobile
- Boost Note app version: 
- OS version and name:

**Comment by Flexo013** [comment]
Wrong repo (Boost Note.next vs Boostnote)

**Comment by Flexo013** [comment]
Duplicate of #3490
