### ISSUE TITLE
Small GUI bug with scrollbars

### ISSUE THREAD

**Issue by WinaZar** [BoostIO/Boostnote#35]
Hello. I found a non-critical gui collision. Maybe you already know about this bug, but anyway.
I'm working on Ubuntu 14.04 / 64
Thanks for your great work!

![little_bug](https://cloud.githubusercontent.com/assets/2156116/15421941/82636166-1e7e-11e6-9563-29829a3e5531.png)

Best regards, Stephan

**Comment by Rokt33r** [comment]
Thank you for reporting. I'll fix z-index of modal.

**Comment by nicklaw5** [comment]
+1 Also occurs with my Windows 10 (64-bit) version

**Comment by Rokt33r** [comment]
Sorry for my late response. I actually going to publish v0.6.*. but, it has been delayed... 
So, the fixed version will be published on this weekend!

**Comment by Rokt33r** [comment]
I forgot to close this issue. It has been already fixed.
