### ISSUE TITLE
Boostnote's slack group🚀

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#350]
We just started the Slack group!
Let's talk about Boostnote. 🏃💨

~~https://boostnote-group.slack.com/shared_invite/MTU3ODcwNzY1ODk0LTE0OTAwNjQ0NTYtMjY4NTYwOTdmYQ~~

**Comment by jasondavis** [comment]
Link no longer valid

**Comment by kazup01** [comment]
Oops, thank you.
New link is https://boostnote-group.slack.com/shared_invite/MTU5OTMwNjMyNjQxLTE0OTA2NzkyNzktYzkzYmZhYjk0Nw

**Comment by louiealmeda** [comment]
@kazup01 I can't join the slack group, it says `This invite link is no longer active.`

**Comment by kazup01** [comment]
Hi @louiealmeda , please join slack group from [here](https://github.com/BoostIO/Boostnote#community). Thank you:)
