### ISSUE TITLE
When scrolling in split-view, editor flickers and doesn't sync with preview

### ISSUE THREAD

**Issue by Ploonet** [BoostIO/Boostnote#3512]
# Current behavior
When scrolling on the preview side, the editor flickers / disappears until I click on it again
![image](https://user-images.githubusercontent.com/53194438/75860857-c9fa7e80-5dfc-11ea-93eb-4e19000cf691.png)

When scrolling on either side, the other view doesn't sync its position
![image](https://user-images.githubusercontent.com/53194438/75860978-fca47700-5dfc-11ea-868c-0b0aa8f01ac2.png)

# Expected behavior

- Editor should not flicker / disappear when scrolling
- Each view should sync its position when scrolling 

# Steps to reproduce

1. Access a note long enough to scroll on each side
2. Get in split-view mode
3. Scroll on either sides

# Environment

- Boostnote version: 0.15.1 (_"An open source note-taking app made for programmers just like you."_ How dare you assume what I do !? I feel personnaly offended by this false statement ! 😉
- OS version and name: Windows 10

Let me know if I can help with more screenshots / info :)

**Comment by MichelleJY** [comment]
Same issue with:
Boostnote version 0.15.1 
OS version:  macOS Catalina Version 10.15.2

**Comment by Rokt33r** [comment]
I'll fix the bug in this week!

**Comment by incace** [comment]
Confirmed on my end as well, 0.15.1, macOS High Sierra 10.13.6

**Comment by Satanepigone** [comment]
Same issue in same environment.

**Comment by ugolole-mio** [comment]
I notice this bug, righter after 0.15.1 install, I decided to revert to 0.15 momentarily. Are there any know fixes.

**Comment by beauwilliams** [comment]
Thanks for getting onto it quick guys. I'm running into it on Mojave

**Comment by Rokt33r** [comment]
Sorry for being late. I was too busy... This will be fixed in this week. I'm currently working on it.

**Comment by Rokt33r** [comment]
It's been fixed in v0.15.2! Thanks for waiting!
