### ISSUE TITLE
Sync desktop with mobile app

### ISSUE THREAD

**Issue by natafrank** [BoostIO/Boostnote#3515]
# Current behavior

I'm not able to sync the notebooks from my Mac app into my Android app.
My notes are stored in Google Drive.

- Do you have this feature enabled?

Thank you!

**Comment by Flexo013** [comment]
What version of Boost Note.next (which does have a mobile app) are you running?

Also note that this is the repo for Boostnote (which does not have a mobile app).

These aren't fully compatible, so you can't sync between Boost Note.next (mobile) and Boostnote.

**Comment by devellopah** [comment]
is there a full sync between desktop app, mobile app and web app?

**Comment by Flexo013** [comment]
There is no automatic (back-and-forth) syncing between Boostnote and Boost Note.next.
