### ISSUE TITLE
Build procedure creates amd64 Debian on an ARM64 system

### ISSUE THREAD

**Issue by johnblommers** [BoostIO/Boostnote#3516]
**Current behavior**

Following the [build instructions](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md) on an arm64 system we get an amd64 Debian file. We want an arm64 architecture installer.

We need information on how to build Boostnote from source on an arm64 Linux system such as Kali Linux.

**Update** To be clear: a working executable is generated and Boostnote does launch upon typing

```bash
yarn run dev
```

The deploy phase  builds the actual `.deb` and `.rpm` installers ends with

```bash
grunt  build
```

but that step is what generates the Intel-based `.deb` package - on an ARM64-based Kali Linux system on the Raspberry Pi 4 B.

Many thanks.

**Comment by Flexo013** [comment]
@ZeroX-DG @Rokt33r Do either of you know anything about this issue?

**Comment by Rokt33r** [comment]
@johnblommers You need to configure electron-packager. Please https://github.com/electron/electron-packager.

**Comment by Flexo013** [comment]
For now I'll close this issue.

If you need more info, then feel free to continue this thread, and I'll reopen it.
