### ISSUE TITLE
Support GraphQL language type in Snippet Notes

### ISSUE THREAD

**Issue by dhwaneetbhatt** [BoostIO/Boostnote#3518]
Hello maintainers, I use Boostnote to store a lot of stuff and some of our internal APIs are in GraphQL. Normally I'd use Postman for sending requests, but I store a lot of pre-crafted GraphQL queries and mutation in Boostnote snippets.

Currently I use JSON formatting for GraphQL queries and it works okay, but it would be better if Boostnote supported GraphQL schema language in the snippet notes.

**Comment by Flexo013** [comment]
Hey! 👋 

Boostnote is using CodeMirror for syntax highlighting. All supported languages are listed here:
https://codemirror.net/mode/index.html

If you want, you can request this to CodeMirror
https://github.com/codemirror/CodeMirror/issues
