### ISSUE TITLE
Support Apache syntax highlight

### ISSUE THREAD

**Issue by enriqueism** [BoostIO/Boostnote#3519]
I'm using Boostnote 0.15.1. I see Nginx syntax highlight is supported, is there a chance to add Apache as well. Thanks.

**Comment by ZeroX-DG** [comment]
Boostnote is using CodeMirror for syntax highlighting. All supported languages are listed here:
https://codemirror.net/mode/index.html

If you want, you can request this to CodeMirror
https://github.com/codemirror/CodeMirror/issues
