### ISSUE TITLE
Official website Version Problem

### ISSUE THREAD

**Issue by feng20190** [BoostIO/Boostnote#3526]
I downloaded your software from official website, but the version number is version 0.1.4. The page jumps to another warehouse. At the same time, the version on Google Play is too old to be used. Can it be updated in time？Although the problem is not big, I think it has some influence.

**Comment by Flexo013** [comment]
Both apps have been updated in the last few days. See https://note.boostio.co/

Also, you are using Boost Note.next and not Boostnote.
