### ISSUE TITLE
Please update the website https://boostnote.io/.

### ISSUE THREAD

**Issue by Lunaxx88** [BoostIO/Boostnote#3533]
# Current behavior
Please update the website https://boostnote.io/ download exe file and showing picture.
I found the website is out of date and I used this before.
After facing some problems later I found the newest version

Maybe you can set up that if people click on the "Windows Download" Button, they will go to the Github latest version page.

Best Regards,
![BoostNote Issue1](https://user-images.githubusercontent.com/54644860/77812422-9a473b00-7077-11ea-93b8-f979c78c3c59.JPG)

**Comment by arcturus140** [comment]
the Download links to the latest version, you are using An old version

**Comment by Flexo013** [comment]
Please beware that Boostnote and Boost Note.next are different applications:

- https://github.com/BoostIO/boost-releases/releases/latest
- https://github.com/BoostIO/BoostNote.next/releases/latest
