### ISSUE TITLE
Publishing to wordpress weblog not working because of WP_POST_PATH

### ISSUE THREAD

**Issue by karstenpe** [BoostIO/Boostnote#3534]
# Current behavior
Trying to publish to a standard wordpress installation ( Version 5.3.2 ) fails in boostote 0.15.2.

# Expected behavior
Publishing succeeds.

# Steps to reproduce
1. Create an arbitraty entry in boostnote; 
2. configure wordpress blog endpoint and 
3. use "Publish Blog"

# Patch
I could patch the issue by changing (in compiled main.js)
var WP_POST_PATH = '/wp/v2/posts'; 
to
var WP_POST_PATH = '/wp-json/wp/v2/posts';
Obviously the API endpoint has slightly changed.

Maybe it helps to make it configurable,

# Environment
Trying to publish to a standard wordpress installation ( Version  ) fails in boostote 0.15.2.
Trying to publish to a standard wordpress installation ( Version 5.3.2 ) fails in boostote 0.15.2.

- Boostnote version: 0.15.2
- OS version and name: Windows 10 
- Wordpress Version: 5.3.2; WP BASIC Auth Plugin V 1.1.3

**Comment by Flexo013** [comment]
Thanks for reporting the issue and already looking for a fix!

Could you submit a PR with the suggested change? That way we can review it and make it part of the next release.

**Comment by karstenpe** [comment]
Thank for getting back. I haven't set it up but will try!

**Comment by ZeroX-DG** [comment]
After investigating this issue, it's not Boostnote issue. You have to specify the url with `/wp-json` in the configuration. This is a example from our default config:
https://github.com/BoostIO/Boostnote/blob/4fbbb4651dd5ef1164fd3885ee354368673fbb08/browser/main/lib/ConfigManager.js#L135

**Comment by karstenpe** [comment]
Thanks for investigating; I will try with the next update.
Still skeptical about compatibilty with self-hosted wordpress. Let's see.
