### ISSUE TITLE
Unable to import old notes

### ISSUE THREAD

**Issue by melston** [BoostIO/Boostnote#3538]
# Current behavior

I followed the directions for importing old cson files and every file gives me the error that the file is invalid.  No old notes are imported.

# Expected behavior

I expect to be able to import my old notes into the new version of the application.

# Steps to reproduce

1.  Go to the import screen.
2.  Using Windows Explorer drag a cson file from the old storage location onto the form.
3. The form says "Invalid File: &lt;filename&gt;.cson  remove"

# Environment

- Boostnote version: 0.3.0
- OS version and name: Windows 10

**Comment by Rokt33r** [comment]
Please check this issue. https://github.com/BoostIO/BoostNote.next/issues/393 The current importing feature is broken. It will be implemented again before the end of this June. Until then, please keep using the old app! You can download it from https://github.com/BoostIO/boost-releases/releases
