### ISSUE TITLE
Simplified Chinese can't show normally

### ISSUE THREAD

**Issue by iPolluxGem** [BoostIO/Boostnote#3539]
# Current behavior

The Chinese characters looks like bit of a strange. Maybe because of the truetype? Hope can support normal types for Chinese Simplified language supporting, such as Arial or Song. 
![实际输出效果](https://user-images.githubusercontent.com/49026347/78329743-0f090080-75b5-11ea-879b-4738eecc0ab7.png)

# Expected behavior

![Normal_Simpified](https://user-images.githubusercontent.com/49026347/78329728-06182f00-75b5-11ea-9964-ab46aa5c2be3.png)
![正常效果举例](https://user-images.githubusercontent.com/49026347/78329736-0a444c80-75b5-11ea-8a28-1b143dd7ab43.png)

# Steps to reproduce

1. Type Simplified Chinese, then show it as md
2. Characters' type will turn into wrong ones(Not even traditional Chinese)

# Environment

- Boostnote version: 
- OS version and name:

**Comment by Flexo013** [comment]
Could this be related to #3393?

**Comment by iPolluxGem** [comment]
> Could this be related to #3393?

I've checked that before, and I think it's still unsolved.

**Comment by Flexo013** [comment]
Yes, that issue is still open, but I was wondering if both the issues concern the same problem. If that's the case we can close this issue, and focus our efforts on that issue.

**Comment by iPolluxGem** [comment]
> Yes, that issue is still open, but I was wondering if both the issues concern the same problem. If that's the case we can close this issue, and focus our efforts on that issue.

I think these two issues are about the same problem, and I opened this because I noticed that issue hasn't been updated for some time. 
It's okay to close this issue, if you guys are dealing with it. Hopefully it can be solved earlier, I really like Boostnote, afterall.

**Comment by Flexo013** [comment]
Duplicate of #3393

**Comment by Flexo013** [comment]
@iPolluxGem Feel free to post anything to that might help in the other thread.
