### ISSUE TITLE
DOWNLOAD MAC APP buttons in Boost Note website downloads old version 0.3.0

### ISSUE THREAD

**Issue by ShintaroOkuda** [BoostIO/Boostnote#3541]
`DOWNLOAD MAC APP` buttons (there are 2 buttons) in  https://boostnote.io/ downloads a very old version `0.3.0`.

**Comment by Flexo013** [comment]
There are two versions of Boostnote. Both are still being develop. You are looking for the latest legacy build.
Boostnote (legacy): https://github.com/BoostIO/boost-releases/releases/latest
BoostNote.next (new): https://github.com/BoostIO/BoostNote.next/releases/latest

**Comment by ShintaroOkuda** [comment]
Oh - I see. Thanks for the clarification!
