### ISSUE TITLE
Thanks for  App .Please Include an automated alarm system !!! backup !!!

### ISSUE THREAD

**Issue by Aminur670** [BoostIO/Boostnote#3545]
Hi,
I'm Asaduzzaman
I Use it for my all note works  !!!
Thanks for New Awesome App . I loved this from the start.

Please Include

1. An automated alarm system for reminder !!!
2.  Backup & Restore !!!
3. A Text editing Tool Bar Like CK Editor !!!
4.  Add an Autometic Photo storing System to app !!!
5.  Add an Autometic Photo Viewer(Like LightBox) System to app !!!

Thanks All.

**Comment by arcturus140** [comment]
point 5 already supported. 

what's the intended use of point 4, do you have lots of hand written notes that you photograph?

**Comment by Aminur670** [comment]
Some time I had to keep a screenshot of my works for my clients.
I installed the new version, but it is not storing photos by pasting !!!
And a Ck editor would be useful integration for me.

Thanks a lot !

**Comment by arcturus140** [comment]
image files are automatically imported and embedded. use ctrl shift v to insert an image from clipboard to the editor.

**Comment by arcturus140** [comment]
point 3 is a duplicate

**Comment by Aminur670** [comment]
And add a *Popup Menu* at right click on editor & previewer !!!

**Comment by arcturus140** [comment]
context menu is a feature request, see #3543. You can give it a thumbs up to show your interest.

**Comment by Flexo013** [comment]
Like arcturus pointed out, points 2 through 5 are duplicates or already fixed issues.

As for point 1, Boostnote won't be a universal app for everything. If you want something for tasks and reminders then use one of the many todo-list applications out there.
