### ISSUE TITLE
Unable to import old notes

### ISSUE THREAD

**Issue by BrunoLagoa** [BoostIO/Boostnote#3546]
# Current behavior

I followed the directions for importing old cson files and every file gives me the error that the file is invalid. No old notes are imported.

# Expected behavior

I expect to be able to import my old notes into the new version of the application.

# Steps to reproduce

1. Go to the import screen.
2. Using Windows Explorer drag a cson file from the old storage location onto the form.
3. The form says "Invalid File: <filename>.cson remove"

# Environment

Boostnote version: 0.3.0
OS version and name: MACOS Catalina 10.15.4

**Comment by ZeroX-DG** [comment]
This is the repo for the old boostnote. You must be using the re-write version of Boostnote. And also there's already an issue for this in the new app repo:
https://github.com/BoostIO/BoostNote.next/issues/393
