### ISSUE TITLE
Can't paste image to boostnote 

### ISSUE THREAD

**Issue by marshuang80** [BoostIO/Boostnote#3548]
# Current behavior

Can't paste image to boostnote either by drag and drop from browser or by copy and paste from screenshot. 

#2716 mentioned that I should enable "smart paste", but I couldn't find the interface section in my preference. 

![image](https://user-images.githubusercontent.com/15271135/79090054-49814480-7cfd-11ea-80bb-eb0dc464c228.png)

# Expected behavior

Paste image to boostnote

# Steps to reproduce

1. Open browser
2. Find image 
3. Drag and drop to boost note

OR 

1. Command+Shift+4 
2. copy screenshot
3. control+v or control+shift+v to paste

# Environment

- Boostnote version: <-- 0.1.4. -->
- OS version and name: <-- Mac OS 10.15.2 -->

**Comment by uscsnostromo** [comment]
I have been having the same issue and writing to the Boost Note folks for weeks now, I think they don't care at all about this feature. This tool seems to be strictly about text.

**Comment by Flexo013** [comment]
Pasting images works fine.

You are use [BoostNote.next](https://github.com/BoostIO/BoostNote.next/releases/latest) which is a beta version with less features than the legacy app.

Please download the latest version of the [legacy Boostnote here](https://github.com/BoostIO/boost-releases/releases/latest). If you encounter any problems with pasting using 0.15.2 then please create another issue.

**Comment by mechs85** [comment]
Sorry I know this is closed but I have the exact issue. The app version on your site is old (0.4x) and now I have pulled down (0.15.3) today and still cannot paste on OSX
