### ISSUE TITLE
Loss of local storage

### ISSUE THREAD

**Issue by wubinbin0403** [BoostIO/Boostnote#3552]
# Current behavior
All my local storage disappeared after the software was automatically updated. So how do I solve this problem?

# Environment

- Boostnote version:  update to 
- OS version and name:

**Comment by AlecCh0402** [comment]
You might need this [Notes disappear after 0.3.0 update #380](https://github.com/BoostIO/BoostNote.next/issues/380#issuecomment-608569928)

**Comment by Flexo013** [comment]
Sorry to hear that you lost your notes. We will need info as to what version of the app you are using. Without that we can't help you.
