### ISSUE TITLE
There's no "about..." option in the "help" menu

### ISSUE THREAD

**Issue by frenchiveruti** [BoostIO/Boostnote#3557]
As title says, there's no way to tell the current version being used by the user.  
I guess I'm using the new version of the app, I just downloaded it and I wanted to report another bug and I couldn't find the version anywhere easy to access.

**Comment by frenchiveruti** [comment]
https://github.com/BoostIO/BoostNote.next/issues/432

**Comment by arcturus140** [comment]
@Flexo013 this is about next version, should be cloesd.
