### ISSUE TITLE
English menu translated into Chinese

### ISSUE THREAD

**Issue by Hunlongyu** [BoostIO/Boostnote#356]
I want to translate the menu. Is this the file? BOOSTNOTE/lib/main-menu.js

**Comment by asmsuechan** [comment]
Hi @Hunlongyu, you need to restart the electron app for reflection the changes when you change a code in `lib/main-menu.js`.

**Comment by Hunlongyu** [comment]
I want to make a Chinese version, but I don't know how to pack it into an installer.

**Comment by webmastak** [comment]
How did you solve this problem?
