### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by cross-hello** [BoostIO/Boostnote#3560]
# Current behavior

When I export md with multiply photos, it false.
Here are the feedback.
![image](https://user-images.githubusercontent.com/42733664/80552443-38248180-89f9-11ea-9c93-182ee1fb14ec.png)

# Expected behavior
It should export normally

# Steps to reproduce

1. insert some phtots.
2.  export md.
(When I delete the photos, it is normal again = - =)
# Environment

- Boostnote version:  0.15.3
- OS version and name:  Win7-64bit

**Comment by cross-hello** [comment]
I don't know why.
But when I insert photos once again, everything looks so normal. = - =

**Comment by Flexo013** [comment]
Duplicate of #3262
