### ISSUE TITLE
Why should I choose Boostnote instead of MarkText?

### ISSUE THREAD

**Issue by RuikangSun** [BoostIO/Boostnote#3567]
This question title might be a little bit aggressive, but this question really bothers me : (
Both of these softwares seem to be great Markdown editor, why should I choose Boostnote instead of MarkText?

**Comment by RuikangSun** [comment]
Mirror issue: https://github.com/marktext/marktext/issues/2095

**Comment by arcturus140** [comment]
Boost Note is a note taking app, not a markdown editor. To edit Markdown, use a Markdown editor and v.v. 

Otherwise, it's up to you.

**Comment by RuikangSun** [comment]
> 
> 
> Boost Note is a note taking app, not a markdown editor. To edit Markdown, use a Markdown editor and v.v.
> 
> Otherwise, it's up to you.

Thanks fot your reply! I will download BoostNote and have a try.
