### ISSUE TITLE
About KaTeX 's Error

### ISSUE THREAD

**Issue by Orange-Jun** [BoostIO/Boostnote#3569]
# Some errors when writing mathematical formulas using KaTeX

# For example:
1. ` $\S$ `  
2. ` $$ y = x^2 \; \mbox{(二次函数)} $$ `
3. ```   $$ \begin{equation}
    \left\\{
    \begin{aligned}
    2x + y &= 1 \\\\
    2x + 2y &= 2
    \end{aligned}
    \right.
    \end{equation} 
4.  `......`

These errors are just a few
# Error message
> KaTeX parse error: Undefined control sequence: \S at position 1: \̲S̲
> KaTeX parse error: Undefined control sequence: \mbox at position 12: y = x^2 \; \̲m̲b̲o̲x̲{(二次函数)}
> KaTeX parse error: No such environment: equation at position 7: \begin{̲e̲q̲u̲a̲t̲i̲o̲n̲}̲ \left\\{ \begi…

# Environment

- Boostnote version:  0.15.3
- OS version and name: Windows 10 

# Thanks
Can you help me understand the cause of this problem？
If you can solve it, thank you very much！
谢谢！

**Comment by Flexo013** [comment]
Thanks for creating this issue! Here are solutions to your problems:

1. KaTeX does not support `\S` in math mode, so you need to escape it like this: `\text{\S}`
2. You are in a math environment so use `y = x^2 \text{;(二次函数)}`
3. There is a typo in your snippet, so an error is expected. Remove one backslash after `\left`, and also don't end the equation environment yourself, the `$$` already does that for you:
```
\left\{
  \begin{aligned}
    2x + y &= 1 \\\\
    2x + 2y &= 2
  \end{aligned}
\right.
```
