### ISSUE TITLE
can't seach a word in one note

### ISSUE THREAD

**Issue by chillbest** [BoostIO/Boostnote#3570]
Win10 V0.4.1
I have many long note, so i always want seach one word in one note.
I think is a high frequency demand, so plz update it . plz

**Comment by Flexo013** [comment]
Thanks for making an issue with your suggestion!

The version of BoostNote you are using is called BoostNote.next. Please create a feature request in this repo and fill out the entire template: https://github.com/BoostIO/BoostNote.next/issues

Also give a quick search around the existing issues in that repo to see if anyone has already made the request.
