### ISSUE TITLE
Display snippet code inline instead of link

### ISSUE THREAD

**Issue by it4577** [BoostIO/Boostnote#3572]
# Current behavior

Currently, when linking a snippet within a markdown note a link to the the snippet is created.

# Expected behavior

Desired result is to have an option/flag to display the code snippet inline (within the markdown note) and formatted appropriately based on language. This would reduce the size of markdown notes and allow for an additional usage of code snippets.

# Environment

- Boostnote version: 0.15.3
- OS version and name:  Windows 10

**Comment by Flexo013** [comment]
Duplicate of #597
