### ISSUE TITLE
Missing folder and notes

### ISSUE THREAD

**Issue by Ashllives** [BoostIO/Boostnote#3575]
# Current behavior
When I reopened my app to update one of my notes, it's folder is gone and so are my notes. When I checked the storage, the folder for my other storage aside from default is gone too. I tried to retrieve my notes from my drive but they were not updated also, most of my notes were not there too. I don't know what happened. I did not update my OS. But my boostnote app was updated lately, its current version is **(Version 0.15.3 (0.15.3))**.

Please help me retrieve my notes. Thank you.

# Expected behavior
There should be two folders (storages): the default storage and the other storage I called booky. As you can see, only the default folder is remaining.

<img width="1440" alt="Screen Shot 2020-05-12 at 7 57 44 PM" src="https://user-images.githubusercontent.com/28987668/81686147-f67ce780-948a-11ea-9d43-909a3b98e559.png">

# Environment

## Desktop
- Boost Note.next version:  Version 0.15.3 (0.15.3)
- OS version and name:  macOS mojave version 10.14.6

**Comment by Flexo013** [comment]
@jhdcruz Thanks for pointing that out! I have moved the issue to the correct repo.

@Ashllives It sucks to hear that you seem to have lost your notes, but we'll see if we can do something to get them back.

Updates of Boostnote are very unlikely to modify existing notes and storages. Unless you haven't updated in over a year, I don't there have been any changes to that part.

>  the folder for my other storage aside from default is gone too. 

Just to make sure I understand, you had two folders, each being one storage. Within those storages there used to be note files. The folder for Default Storage is still present, and does still have all notes. The folder for the Booky storage is gone from your device, including all notes it had. Is that correct?

What cloud service are you using? Many offer some sort of history or previous versions. Looking for one of those might help you with getting your folder back.

Then some other info that would be helpful: How often does your software sync? Do you use Boostnote on multiple computers or only on this iMac?

**Comment by Ashllives** [comment]
Hello,

Thank you for reaching out to me. I really appreciate it. Here the answers
to your questions:

Q: Just to make sure I understand, you had two folders, each being one
storage. Within those storages there used to be note files. The folder for
Default Storage is still present, and does still have all notes. The folder
for the Booky storage is gone from your device, including all notes it had.
Is that correct?

A: Yes, your understanding is correct.

Q:  What cloud service are you using? Many offer some sort of history or
previous versions. Looking for one of those might help you with getting
your folder back.

A: I connected it to my google drive before but somehow sometime during the
year it got unlinked probably because when I checked my drive I was only
able to find 4 of my notes and they were not even updated.

Q: Then some other info that would be helpful: How often does your software
sync? Do you use Boostnote on multiple computers or only on this iMac?

A: I have boostnote both on my mac and on my windows laptop. But I don’t
think they are connected. I don’t remember ever syncing them together. I
think of them as separate storages.. Not a very good practice I guess..

Cheers

**Comment by Flexo013** [comment]
Thanks for the detailed response!

On which device did you lose your storage folder? I can give some tips for a nice successfully synced setup between two devices if you'd like.

If the storage you need is gone, and you are sure that the folder is also gone, then there is very little we can do. You can try a system-wide search for `*.cson` to hopefully find any notes that might still exist. You could check your trash bin, any previous system backups you made, or maybe check something like Mac's Time Machine, if you're on Mac that is. Finally you could check previous versions of files in your Google Drive.

If none of those avenues works, then I hate to tell you, but you are out of luck. 😢

**Comment by Ashllives** [comment]
Hello,

Thank you for being so responsive.

I am using Boostnote in my Macbook Pro for my notes and I rarely use the
one on my Windows laptop for note taking so I don't really want them
synced.

May I ask if none of my notes are saved in your database? Or is it only
saved in my local disk unless I link it to some other storage like Google
Drive? In that case, if it somehow got unlinked for unknown reasons from my
Google Drive, then that means those notes are not recoverable anymore since
they cannot be found in my laptop also?

Would you know any possible reason why my storage got unlinked? I really
hope it does not happen again.

Cheers.

**Comment by arcturus140** [comment]
> Would you know any possible reason why my storage got unlinked? I really
> hope it does not happen again.

your files had been stored only locally. your folder has not been deleted by Boostnote. Something else is responsible for your lost files. Your only option to regain your files is to recover deleted files from your hard drive.

Data loss is a very frustrating experience. The one and only way to safe you from this situation in the future is an up to date, healthy backup. Never trust storage media, local or cloud. As someone who spend 1 month recovering 1 TB worth of files I cannot stress this enough.

**Comment by Flexo013** [comment]
To add onto what arcturus said, Boostnote will not delete any folders. It only unlinks them and leaves the folder and files intact. That way they user can decide what they want to with their data using the normal file manipulation they are comfortable with.

Boostnote does not store any files in the cloud by itself. - I mean, they could be confidential for all we know - So that's not a way to get your notes back. The only thing you can do is to have the physical storage disk analyzed by some professional/forensic tools, and hope that the data is still there. This will costly in both time and money.

All I can recommend for the future is that you never allow for a [single point of failure](https://en.wikipedia.org/wiki/Single_point_of_failure). Make sure you have at least one backup of files you don't want to lose; be it in the cloud or on a separate device.

I wish you the best of luck, and hopefully this won't happen again. 😢

**Comment by Ashllives** [comment]
Alright thank you :)
