### ISSUE TITLE
TOC navigation is not working

### ISSUE THREAD

**Issue by Messmania** [BoostIO/Boostnote#3580]
# Current behavior
- It was working few days back but no longer. Nothing happens when I click on a TOC link.

# Expected behaviour
- Clicking on a TOC item should take me to that section.

# Steps to reproduce
- Open any note and generate TOC
- Click on any item, doesn't navigate.

# Environment
![image](https://user-images.githubusercontent.com/7437953/82961016-24355680-9f8a-11ea-80ce-b42906349238.png)

**Comment by jensmcatanho** [comment]
@Messmania Try to update to the [latest version](https://github.com/BoostIO/boost-releases/releases/latest) and see if this behavior is still happening.

**Comment by Messmania** [comment]
@jensmcatanho thanks for the quick reply. I installed the latest version. but it doesn't allow me to link my local storage path (containing my notes) to the workspace.
![image](https://user-images.githubusercontent.com/7437953/83042148-4e7d2780-a00f-11ea-90a3-892ffe3efb4f.png)

**Comment by jensmcatanho** [comment]
The Boost Note is a renewal of the current Boostnote app and both are being maintained in parallel. You can find updates from the old app in this link: https://github.com/BoostIO/boost-releases/releases/

**Comment by ZeroX-DG** [comment]
I think it resolved then. Feel free to re-open the issue if you still have problem this the TOC:)
