### ISSUE TITLE
Editor: Find **and Replace**

### ISSUE THREAD

**Issue by ToastedBits** [BoostIO/Boostnote#3581]
# Current behavior

While in the editor, pressing Ctrl+f brings up the find text box
Cannot find where or how to open the "and replace" feature (does this even exist in boostnote?)
Tried pressing various combinations of Ctrl+r, Shift+Ctrl+f, Alt+f, Alt+r, Ctrl+Alt+r, Ctrl+Alt+f

# Expected behavior

Should be able to perform a simple find and replace functionality within the editor
Ideally with hotkeys configurable in Interface settings

# Steps to reproduce

1. Open an editor
2. Type in some text
3. Attempt to use find **and replace**

# Environment

Ubuntu Linux 18.04
BoostNote version 0.14.0
Electron: 4.2.12
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.0-53-generic

**Comment by ZeroX-DG** [comment]
Thank you for reporting this but this feature already existed, you can use <kbd>ctrl</kbd> + <kbd>h</kbd> to search & replace. For example:
![replace](https://user-images.githubusercontent.com/12984316/83095498-924b5c00-a0f7-11ea-8c9d-1bd60bc129fa.gif)
