### ISSUE TITLE
Something about font

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#359]
I have some small, unannoying problems with the fonts.  It is that I can't change the font inside a code block. Changing the editor font family inside UI setting doesn't affects the texts in the code blocks. I am sorry that I have no photos here (cuz my machine is in a repair shop right now and I am making this issue from my phone)

**Comment by kazup01** [comment]
Thank you for your reporting!
hmm, I can change the font inside a code block.
macOS Sierra v10.12.3

Can you teach me your environment?

**Comment by VoLuong** [comment]
**Notice that the font in the code block doesnt change while the font outside changes.**

before :
![before1](https://cloud.githubusercontent.com/assets/15828926/24364998/b18271a2-133e-11e7-9aff-ae24b21b8056.png)

before:
![before2](https://cloud.githubusercontent.com/assets/15828926/24365001/b49016f6-133e-11e7-9c58-99de25e5220d.png)

After:
![after1](https://cloud.githubusercontent.com/assets/15828926/24365008/b905e454-133e-11e7-84a4-3471cc7b1dea.png)

After: 
![after2](https://cloud.githubusercontent.com/assets/15828926/24365010/bb2ad7da-133e-11e7-8735-548aa92fbdac.png)

Another try:
![image](https://cloud.githubusercontent.com/assets/15828926/24365112/00debfe4-133f-11e7-8a61-8ca8c4e59ebc.png)

But still the code didnt seem to change the font:
![image](https://cloud.githubusercontent.com/assets/15828926/24365144/18ee4a6e-133f-11e7-90b5-f5a35687f97f.png)

**Comment by VoLuong** [comment]
@kazup01 Pls correct me if I do something wrong, thank you. I am on the latest version on Windows.

**Comment by kazup01** [comment]
You can change the font at Menu->UI->Editor->Editor Font Family.

<img width="626" alt="screen shot 0029-03-28 at 12 54 55 am" src="https://cloud.githubusercontent.com/assets/8602615/24365550/472d0296-1351-11e7-871d-16f994da4361.png">

**Comment by kazup01** [comment]
But it should be edited at Preview->Preview Font Family as you said. We will improve it! Thank you for your reporting @VoLuong !

**Comment by VoLuong** [comment]
@kazup01 Thank you. But isn't it confusing since what I desired to change was the font of the preview, but what I need to change now is the font in the editor section ❓ 😕  Just some personal feelings, though.

**Comment by VoLuong** [comment]
@kazup01 OK. Thank you so much
