### ISSUE TITLE
Emoji is not rendering inside triple backticks

### ISSUE THREAD

**Issue by paxcodes** [BoostIO/Boostnote#3592]
# Current behavior

Emoji is not rendering inside triple backticks:

![Screen Shot 2020-06-15 at 4 56 20 PM](https://user-images.githubusercontent.com/13646646/84716863-2ce5d080-af29-11ea-86c1-5a70573f7d22.png)

# Expected behavior

The screenshot above is an output of the brew installation process. The  ![Screen Shot 2020-06-15 at 4 57 21 PM](https://user-images.githubusercontent.com/13646646/84716916-4b4bcc00-af29-11ea-826d-255b7e03a073.png) should be a beer emoji:

![Screen Shot 2020-06-15 at 4 57 59 PM](https://user-images.githubusercontent.com/13646646/84716955-63235000-af29-11ea-8ea3-7d2c069826d3.png)

# Steps to reproduce

1. Write
````
```
🍺 
```
````

# Environment

- Boostnote version: 0.15.3
- OS version and name: MacOS 10.14.6 (Mojave)

**Comment by daiyam** [comment]
@paxcodes I can't reproduce your issue.

**Comment by arcturus140** [comment]
> I can't reproduce your issue.

@daiyam that's because you have an emoji font installed on your system. 

> Emoji is not rendering inside triple backticks

@paxcodes Boostnote does not ship with its own font for emoticons. You must install it on your system. I am not familiar with this process for MacOS.

**Comment by paxcodes** [comment]
Thanks for the tip. Fixed it.

![Screen Shot 2020-06-16 at 5 49 53 AM](https://user-images.githubusercontent.com/13646646/84776501-39077780-af95-11ea-8e5f-baa1afaed51c.png)
