### ISSUE TITLE
Zoom level resetted after restore window minimizing

### ISSUE THREAD

**Issue by airosB** [BoostIO/Boostnote#3597]
# Current behavior

- Restoring minimized boostnote window causes zoom level resetting.
- Also maximize/restore window causes this sometimes.

# Expected behavior

Maintein zoom level through minimizing, maximizing and restoring.

# Steps to reproduce

1. open a markdown note
1. change zoom level (ex. 150%)
2. open another markdown note
3. minimize boostnote window
4. restore minimizing
5. **zoom level is now reseted to 100%** 
    - _(boostnote tells it's 150% but markdown note is displayed as 100%)_

# Environment

- Boostnote version: v0.15.3
- OS version and name: Windows10 Home x64

**Comment by ShangxuanWu** [comment]
Same here. I am on Mac10.15 and Boostnote 0.16.1. This issue has been bothering me for some long time.

**Comment by Flexo013** [comment]
Duplicate of #3251
