### ISSUE TITLE
Default storage location on Archlinux

### ISSUE THREAD

**Issue by jerome-diver** [BoostIO/Boostnote#3598]
# Current behavior

Impossible to unlink default boostnote storage location (/home/jerome/Boostnote), after to delete it (outside of the software) myself, then re-open boostnote does create it again the same place.

# Expected behavior

It should be possible to be free to choose an other one storage location and to remove/unlink the default first start one.

# Steps to reproduce

Test it on archlinux, please.

**Comment by arcturus140** [comment]
# Current behaviour

Boostnote does not start after installation. The application launches into a blank window. 

# Expected behaviour

Boostnote starts after installation.

# Steps to reproduce

1. `chmod 0600 ~/`
2. install Boostnote
3. start Boostnote

**Comment by arcturus140** [comment]
duplicate of #3126
