### ISSUE TITLE
New style

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#360]
I customize the layout and enjoy using it.

What do you guys think about layout like these images?
If you guys think looks good, I'll improve it at the next update.
![screen shot 0029-03-27 at 11 44 33 pm](https://cloud.githubusercontent.com/assets/8602615/24363145/d915be1c-1349-11e7-8703-cc3af4bc0d6c.png)
![screen shot 0029-03-27 at 11 41 04 pm](https://cloud.githubusercontent.com/assets/8602615/24363151/dee0781e-1349-11e7-9b34-e70c105f5593.png)

**Comment by huettenhain** [comment]
Maybe I am dull, but I can only see one difference to the current layout, namely the font in the editor is not monospaced. Frankly, I would not like that. Am I missing something, though?

**Comment by kazup01** [comment]
Comparison:
![white](https://cloud.githubusercontent.com/assets/8602615/24364672/7a21c720-134e-11e7-8208-5697fbbcbe46.png)

![black](https://cloud.githubusercontent.com/assets/8602615/24364487/dc9eb6fc-134d-11e7-9326-1a1317c770fc.png)

**Comment by jasondavis** [comment]
No offense meant but the only difference I can really notice is the selected item background colors.  If that is the point then I do like the new selected item colors better.

If you are to push a theme update my preference would be to do something similar to my post here https://github.com/BoostIO/Boostnote/issues/328 where each panel/section of the app has a defined border so you can tell where one section start and another ends!  Especially on the dark theme as all 3 columns blend together right now with the same background and no border.

Just my thoughts!

Love to see any updates to the app, I use it daily now to really organize tons of planned and in progress projects

**Comment by kazup01** [comment]
Thank you for support us everyday! @jasondavis  Your feedback is very helpful.

 
>I do like the new selected item colors better.

I agree! I'll improve it more.

I tried the border in dark theme as you say, but I could not make satisfactory one, so I need more time.
I'm glad if there are other examples like Eagle app.

**Comment by kazup01** [comment]
I will improve it more.
