### ISSUE TITLE
Tag list vertical scrolling

### ISSUE THREAD

**Issue by Mirdarthos** [BoostIO/Boostnote#3604]
# Current behavior
I have many tags on my notes. When I view the tags they aren't all visible and I cannot scroll the listing. 
# Expected behavior
The list should be scroll-able so that all tags can be used.
# Steps to reproduce
Have many tags and try to scroll thorough list when viewing.
# Environment
- Boostnote version: 0.15.3
- OS version and name: Manjaro 20.0.3
# Proposed fix
Add a CSS style of `overflow-x: auto;` onto the pane, I suspect the `.SideNav__tabBody___browser-main-SideNav-` class. When I added said styling with the Developer Tools it seemed to work perfectly.

**Comment by Flexo013** [comment]
You could submit a PR with your suggested change. That will get it released faster. 😄

**Comment by Mirdarthos** [comment]
Thanks for the idea. I have no qualms about that.

Unfortunately, I have never used any source version control before.

The result being that I'd need a bit (Or a lot) of help doing it.

**Comment by Flexo013** [comment]
@Mirdarthos Check out [this guide](https://www.thinkful.com/learn/github-pull-request-tutorial/), and Google around a bit. You can also check out the [our wiki](https://github.com/BoostIO/BoostNote.next/wiki/How-to-contribute).

**Comment by Mirdarthos** [comment]
Well, I've just upgraded to version 0.10.1 (According to what I can see, anyway).
And, WOW! The new interface totally eliminates this request, so I'm closing it, happy and impressed.
