### ISSUE TITLE
PDF printing option

### ISSUE THREAD

**Issue by TMB-HUB** [BoostIO/Boostnote#3606]
This is rather a feature request than a bug report. I'm new to Boostnote and I started to like it very quickly but the lack of pdf support is a huge roadblock for me cause basically it means that I can't distribute the documentation I create. Its quite like having MS-Word on your PC without the possibility to print out documents. Its defeats the purpose of any document creating software.

At this point I need to copy my markdown to for example VS-code and print it from there, which just raises the question why to use Boostnote instead of VSC?

using version: 0.7

**Comment by ZeroX-DG** [comment]
You must be using the new Boostnote app which has the official repo here: https://github.com/BoostIO/BoostNote.next

There's already a PR to support this feature so we will try to get it merge soon: https://github.com/BoostIO/BoostNote.next/pull/456

**Comment by TMB-HUB** [comment]
I have downloaded the application to my PC from the official(ly looking) [site](boostnote.io)

I have no idea what to do with the github repo you linked.

**Comment by arcturus140** [comment]
@TMB-HUB your issue is a duplicate of BoostIO/Boostnote.next#243. There are no actions required from your side.
