### ISSUE TITLE
string "(p)" display to "§", bug?

### ISSUE THREAD

**Issue by MatthewP-Newbee** [BoostIO/Boostnote#3607]
# Current behavior

For example, "参考基因组是按染色体方向，也即短臂(p)到长臂(q)方向为正向。"   
display shows me: "参考基因组是按染色体方向，也即短臂§到长臂(q)方向为正向。"

# Expected behavior

"参考基因组是按染色体方向，也即短臂(p)到长臂(q)方向为正向。" 

# Environment

- Boostnote version: Boostnote 0.15.3
- OS version and name: Windows 10

**Comment by arcturus140** [comment]
this is intended. Some examples:

```
(p)

(c)

(tm)
```
to disable it, use `\(p\)`. For example, "参考基因组是按染色体方向，也即短臂\(p\)到长臂\(q\)方向为正向。"

**Comment by Flexo013** [comment]
Slight correct, it can be escaped like this `(p\):

![image](https://user-images.githubusercontent.com/4507015/87225360-a0de9180-c38c-11ea-8b1f-5fca1a6c7142.png)

**Comment by arcturus140** [comment]
@Flexo013 my suggestion should also work.
