### ISSUE TITLE
[ FEATURE-REQUEST ] - New Website/URL File Type

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#361]
## Feature Request for new File Type as single file and as a Snippet File

Since Boostnote is so darn useful for organizing Projects with Markdown files and code snippet files alal within a single file like GitHub GISTS, my request for this new File Type seems practical in my opinion and I would be very happy if it was added!

Most of my files are of the Snippet type so I can have multiple markdown files for a project and code snippet files.  With this new file type I could have app URL's that I am working on for the project load into the frame mainly for a preview of it.

## Website/URL File Type

- This file type would simply require the URL of a webpage which would then include the webpage/URL into an Iframe just like many other ElectronJS apps do for RSS feeds and Website previews.

---

## Other Possible Uses

- Load a GitHub Repo for a Project
- Load JSFiddle type sites
- Load Documentation sites for a project
- Load GitHub Issues for a Project
- obviously many more useful ideas, Task lists, KanBan boards, Calendards, etc could all be added as a Webpage loaded into Iframe on a Snippet project.

---

## Iframe URL Test in Boostnote:
This Animated GIF image below shows a quick test I did in Chrome Dev tools inside Boostnote to load a project I am working on inside of an Iframe and the image shows that it works on this particular test.
Obviously some remote URLs won't work but thats beside the point and nothing new.

![boostnote-webpaage-url-iframe-test](https://cloud.githubusercontent.com/assets/186818/24366943/cd931ca8-12e8-11e7-84b8-e338f22d1ec2.gif)

---

Thoughts please?   I would potentially pay to have this added however would rather it be in the core repo so that future versions of Boostnote would have the new file type as well.

**Comment by jasondavis** [comment]
@VoLuon discovered that you can embed an Iframe into a Boostnote already so that is amazing!  It should be listed as a feature.

### Some ideas for usage

- Embed CodePen.io projects
- Embed JSFiddle projects
- Embed Documentation websites for a project
- Embed online Tool websites like JS Beautifier
- 

### Issues

- Obviously some sites like Trello, GitHub, etc have a HEADER setting **X-Frame-Options** to `DENY` which makes it not possible to embed those websites in an Iframe.  This isn't really an issue but more of a fact to keep in mind when adding iframes to a file.

### Demo Images of Websites Embeded into a Boostnote File using an Iframe

![boostnote-with-iframe](https://cloud.githubusercontent.com/assets/186818/24423489/20606eb2-13cb-11e7-9ebd-eb6d7bc585b6.gif)

### Multiple Boostnote Files each with different Website Iframes

- Boostnote.io
- MKDocs.org Markdown Documentation Generator
- CodePen.io Project Embeded

![boostnote-with-iframe-2](https://cloud.githubusercontent.com/assets/186818/24424277/0d212fbe-13ce-11e7-8dce-2e77f05b5490.gif)

---

### WorkFlowy App Embeded into Boostnote Iframe

![boostnote-with-iframe-workflowy](https://cloud.githubusercontent.com/assets/186818/24425269/91f40038-13d1-11e7-9cd0-5e64fa2c5a16.gif)

**Comment by Flexo013** [comment]
To me this feature feels too much like turning Boostnote into a all-purpose browser and not just a note-taking app.

Recently a smaller, but more appropriate issue was opened for web-related content: #3124 

I'm closing this issue for now due to the low amount of comments. If you are very interested in this feature still, then feel free to reopen/comment on this issue.
