### ISSUE TITLE
Support base64 images

### ISSUE THREAD

**Issue by MatthewP-Newbee** [BoostIO/Boostnote#3611]
I like to insert picture like
```
![histological][iamge1]


[image1]:data:image/png;base64,iVBORw0KGgo...
```

You know base64 of a picture usually very long text, Boostnote takes very long time to paste them in. Meaning while you can't do other operation.

**Comment by MatthewP-Newbee** [comment]
And boostnote will eat lots of ram after insert some base64 picture and slow your typing into note.

**Comment by ZeroX-DG** [comment]
I really don't think using base64 pictures are a good idea. You should first convert them to normal jpg or png before using it in boostnote, this will help reduce ram usage & slowing down the app.

**Comment by MatthewP-Newbee** [comment]
> I really don't think using base64 pictures are a good idea. You should first convert them to normal jpg or png before using it in boostnote, this will help reduce ram usage & slowing down the app.

Jpg and png relie local storage, which adds extra management and sync.

**Comment by MatthewP-Newbee** [comment]
I find image relative path suits me. Thanks anyway.
