### ISSUE TITLE
[improvement requests] show path of file system storage when right clicking > Configure Storage & more

### ISSUE THREAD

**Issue by huzibizi** [BoostIO/Boostnote#3616]
# Current behavior

Right now, there doesn't seem to be any way to view the path where a File system storage is located. 

I have also noticed some additional issues / improvements, which I've detailed in the second attached image. 

[Image 1](https://i.imgur.com/ka2sCOB.png)

[Image 2 (please read the annotations!)](https://i.imgur.com/3qF9XVy.png)

# Expected behavior

Path should be shown in the 'Configure Storage' section (located [here](https://i.imgur.com/ka2sCOB.png)). 

# Steps to reproduce

1) Right click on a File System storage in the left sidebar. 
2) Click on 'Configure Storage' 

![boostnote1](https://user-images.githubusercontent.com/67965345/88182336-f7b75700-cc27-11ea-96cb-002175e9d2f7.png)

![boostnote2](https://user-images.githubusercontent.com/67965345/88182263-e4a48700-cc27-11ea-95d0-4652228219e7.png)

# Summary of improvements
1) **Show whether the selected storage is File System, Local or Cloud in the 'configure storage' section.** 

2) **Show the local path of the selected (file system/local) storage in the 'configure storage' section located [here](https://i.imgur.com/ka2sCOB.png).  (most important!)**

3) Add 'back up this storage' function that would back the storage folder up to an archive **(with a timestamp/time and date as the default filename)** and prompt the user to choose a location to save the archive to. (prompt to set optional archive password too maybe) 

4) Add 'move this storage' function or similar that would allow you to move a file system storage folder to a new location. **Prompt the user and ask whether they want to keep a copy of the old storage in the old storage location or delete it.** 

5) Add 'restore file storage by archive' option or similar into the menu (and 'create storage' section), that would allow a user to restore backups in archive format (not replacing any existing saved storages).

6) Add 'restore file system storage by path' option or similar into the menu (and 'create storage' section), that would allow a user to restore backups from specific folders that were backed up manually (not replacing any existing saved storages).

7) (optional) Add 'Organise Storages' option into the top menu or wherever convenient, that allows users to organise the order storages are displayed in the sidebar - and could also allow them to view paths, back things up, **back up multiple storages at once (multiple folders within 1 archive)**, etc!

# Environment

- Boostnote version: Latest windows version as of 22 July 2020
- OS version and name: Windows 10 Pro x64

**Comment by Flexo013** [comment]
Issues pertains to BoostNote.next: https://github.com/BoostIO/BoostNote.next/issues/554
