### ISSUE TITLE
[improvement requests] allow easy embedding of images into notes, add WYSIWYG style buttons, and (less importantly) WYSIWYG display mode

### ISSUE THREAD

**Issue by huzibizi** [BoostIO/Boostnote#3617]
# Current behavior

images cannot currently be easily embedded into notes, at least not without using HTML and knowing the exact path of your image. this can be changed.

# Expected behavior

Have a button that allows users to select a local image (or type in an online URL), and embed that image into their notes. 

The app would prompt the user and ask them whether they want to link the image from a specific chosen path whether online or offline, OR, copy/download the image to the Boostnote storage folder and link using that path instead. 

( maybe add option for compression and cropping in the future too within the app? )

# Environment

- Boostnote version: Latest windows version as of 22 July 2020
- OS version and name: Windows 10 Pro x64

# Further future improvements eg. WYSIWYG editor style buttons for easy formatting

It'd be nice if we could have options (WYSIWYG style buttons etc) to format text too: **bold / italic / underlined, font colours, font sizes, font types - plus dreamweaver/frontpage/WYSIWYG style buttons for hyperlinks, quotes, creating custom tables, bullet points/numbers/checkboxes, etc.**  These buttons could be also be used to conveniently disable things like auto enumeration where they are inserted automatically. 

They could output WYSIWYG style, or just simple HTML that can be viewed in the live preview section; 

An additional option could be added in the future to view the code in **'WYSIWYG' mode** instead of being limited to just code & live preview. 

( Also, add option in preferences, or a WYSIWYG editor style button **(or both - the option in preferences could be a more permanent solution for users who don't want to be clicking the button all the time)** to disable automatic enumeration on request. This would provide a solution the problem described in #3609 and maybe #3610 too . )

**Comment by huzibizi** [comment]
Comment taken from #236 : 

> 'wysiwyg mode' would still be extremely useful as an option though - users can choose the mode they want to use just like they can switch between markup/splitscreen/live preview. 
> 
> the wysiwyg editor buttons could also be enabled and disabled via the preferences section, so that if you want, you can use the wysiwyg buttons in 'markup mode' too, as opposed to just them working when using the wysiwyg editor feature!
> 
> the option could slot in easily between the markup button and split screen button (see below image), and could be disabled/enabled via preferences.
> 
> ![boostnote2a](https://user-images.githubusercontent.com/67965345/88195037-710a7600-cc37-11ea-8074-449f48b811d4.png)
> 
> im a coder, but making a bunch of things bold using a wysiwyg style button is way quicker and easier to remember than inserting the characters before and after every peice of text... don't you agree?
> 
> (itll be even quicker if the wysiwyg buttons had shortcut keys to use, eg. CTRL + B for making a selected peice of text bold. )
> 
> if users don't like it for whatever reason, they can opt out of it via Preferences.
> 
> I really think its a good idea and should be pretty easy to implement as there are so many open source wysiwyg editors out there that could be taken and implemented into boostnote.

**Comment by Flexo013** [comment]
Closing this issue as it pertains to BoostNote.next, and it also exists there: https://github.com/BoostIO/BoostNote.next/issues/553
