### ISSUE TITLE
some/most buttons have no tooltip text on boostnote for windows

### ISSUE THREAD

**Issue by huzibizi** [BoostIO/Boostnote#3618]
# Current behavior

when hovering over some buttons, eg. the preferences button, there is a tooltip text shown, which is great. 

![boostnote1b](https://user-images.githubusercontent.com/67965345/88189523-0fdfa400-cc31-11ea-9a7a-e713da707f27.png)

However for most other buttons, there is no tooltip text displayed to describe them. The most annoying button with no tooltip text is probably the Trash button, especially for someone like me with bad eyesight lol. 

Please see the attached pictures below for some more examples of this. 

![boostnote1c](https://user-images.githubusercontent.com/67965345/88189534-11a96780-cc31-11ea-9640-2e695f976b7f.png)

![boostnote1d](https://user-images.githubusercontent.com/67965345/88189543-13732b00-cc31-11ea-9d95-03a88c1afa81.png)

![boostnote1e](https://user-images.githubusercontent.com/67965345/88189553-153cee80-cc31-11ea-88bb-4df3dd435b77.png)

# Expected behavior

when hovering over buttons that are unlabelled, it should display tooltip text to describe what the button does - especially if the button is unlabelled. 

( if the button has an assigned shortcut key, it should also display that in the tooltip text. )

please see the attached example of tooltip text below (mozilla firefox)

![boostnote1a](https://user-images.githubusercontent.com/67965345/88188885-52ed4780-cc30-11ea-8441-32e900742160.png)

# Steps to reproduce

Hover over any unlabelled button as shown in the image below, eg. the preferences button. 

# Environment

- Boostnote version: 0.7.0
- OS version and name: Windows 10 Pro x64

**Comment by Flexo013** [comment]
Issues pertains to BoostNote.next: https://github.com/BoostIO/BoostNote.next/issues/552
