### ISSUE TITLE
Issue with image display

### ISSUE THREAD

**Issue by GuoYu-Peng** [BoostIO/Boostnote#3619]
# Current behavior

I store notes and images in my Mobile hard disk so I can use boostnote on different computer without network.  
I drop image to my notes with mouse this generate image path, however the path may change when I open boostnote, even on the same computer after reboot.  
Here is example, I drop image get the path yesterday.  
```
![Mut_4Cluster.png](:storage\9688f4ca-a6ce-445b-b529-d8026d65918c\e95126b7.png)
```
Today, the link is broken, I drop again and get
```
![Mut_4Cluster.png](:storage\9688f4ca-a6ce-445b-b529-d8026d65918c\0e823cc4.png)
```
Image path on my computer is
```
D:\Notes\images\TCGA_BLCA_2017\Mut_4Cluster.png
```
Where `D:\Notes` is notes stroge.

# Expected behavior

Generate stable image path.
# Environment
Win 10.
Boostnote Legacy 0.16.0

**Comment by GuoYu-Peng** [comment]
Updata, today's link also broken now. No compute reboot, just have boostnote reboot.

**Comment by Flexo013** [comment]
Once you paste an image into Boostnote it makes a copy of the image into the storage/attachments. There are some other errors that currently exist with regards to images: #3348. It is possible you are running into those.

Are all of your images no longer working, or only a few?

**Comment by GuoYu-Peng** [comment]
> Once you paste an image into Boostnote it makes a copy of the image into the storage/attachments. There are some other errors that currently exist with regards to images: #3348. It is possible you are running into those.
> 
> Are all of your images no longer working, or only a few?

Only a few, and I solved this problem by disable "Delete attachments, that are not referenced in the text anymore", thanks anyway.

**Comment by Flexo013** [comment]
Glad to hear that it was fixed that way 👍
