### ISSUE TITLE
Can I import notes from an old version to the latest version of BoostNote?

### ISSUE THREAD

**Issue by int-a** [BoostIO/Boostnote#3627]
I was running version 0.16.0 on my old laptop (was never prompted to update) and now I've installed the newest version on my new laptop. I tried just migrating my boostnote folder containing my boostnote.json file and notes folder to the new version but now BoostNote will not load. It appears that the boostnote.json file of the new version is in a different format than the old one. Is there any way to easily migrate?

Old Boostnote.json:
`{
  "folders": [
    {
      "key": "b6719036b1c58d8b07a0",
      "color": "#1278BD",
      "name": "Default"
    },
    {
      "key": "074acdaa99b1c34aa3c1",
      "color": "#3FD941",
      "name": "Work"
    },
    {
      "key": "2a0d72f7a59970aa0e08",
      "color": "#E8D252",
      "name": "KT Sessions"
    },
    {
      "key": "d33683a954a545cf9c70",
      "color": "#3FD941",
      "name": "Career Development"
    }
  ],
  "version": "1.0"`

New (empty) boostnote.json:
`{"folderMap":{"/":{"_id":"folder:/","createdAt":"2020-08-24T19:11:48.109Z","data":{},"updatedAt":"2020-08-24T19:11:48.109Z"}},"tagMap":{}}`

**Comment by Flexo013** [comment]
Migrating from Boostnote Legacy to BoostNote.next is possible with import featurre in 0.9.0.
