### ISSUE TITLE
Cannot find Dropbox Syncing on the Ipad Version

### ISSUE THREAD

**Issue by chloechen8** [BoostIO/Boostnote#3640]
I download iPad version on the apple store.

In this version, I find cloud storage but I cannot find Dropbox Syncing.

Like in the screenshot, when I try to open the menu, I just find the folder in this place.
I found the ios helper website before, in that website, ios provide Dropbox.

Could you help with Ipad Version?

And I found the sign-in option, I am not sure where can I sync the Boostnote Cloud folders.

![06158019f968712d942c8760655d727](https://user-images.githubusercontent.com/54644860/93089074-5b607c80-f6cd-11ea-8323-8651fa4f36dd.jpg)

**Comment by Sylk** [comment]
Gonna have to ask for a follow up on this.

**Comment by Flexo013** [comment]
The mobile version does not support Dropbox syncing. Only native cloud syncing is an option.

**Comment by sceptiq** [comment]
> The mobile version does not support Dropbox syncing. Only native cloud syncing is an option.

is this for now or will third party sync stuff be available in the future? 

Because I remember this has been asked in the KS campaign and the answer was DAV/third party storage/sync will be supported.

**Comment by Sylk** [comment]
https://github.com/BoostIO/Boostnote/issues/3643

Seems third party syncing is not a concern.
