### ISSUE TITLE
(ctr + c) don't copy the text is also paste the text

### ISSUE THREAD

**Issue by George35mk** [BoostIO/Boostnote#365]
When i press ctr + s  is not only copy the text on markdown but also paste the markdown on  the same time in the begging all work ok but afer 5 lines is start this bug for example

i type this 

?### insert data insite the collection
?### db.collection.insertOne('name : 'george')

?after i copy the markdown is look like this
?*******### ******insert data insite the collection
?### db.collection.insertOne('name : 'george')

dont focus on (?) i put this because i dont want to render the markdown on github ignore the (?)

**Comment by asmsuechan** [comment]
Hi, @George35mk. Could you explain this issue more explicit? I'm having trouble grasping the main point you want to convey.

**Comment by George35mk** [comment]
omg i mean ctr + c i am sry my mystake

**Comment by VoLuong** [comment]
I cannot reproduce  this bug on my machine. Please clarify : your operating system & your Boostnote version.

**Comment by muhmarigo** [comment]
This also happens to me, Windows 10 + Boostnote 0.8.7
When I Ctrl+C or Ctrl+Z it add `****` to the line that is focused
I was going to add some screenshots to clarify what happen, but I just find out it is a random behavior and I can't reproduce now. I will try to find out what I did just before it started happening and then add more details here

**Comment by asmsuechan** [comment]
I removed the `Ctrl - B` shortcut. Probably this issue won't happen after next release.
