### ISSUE TITLE
Mac to PC local storage issue. 

### ISSUE THREAD

**Issue by rpavantica** [BoostIO/Boostnote#3652]
# Current behavior

Trying to Transfer Notes from Mac to PC getting this error 

`TypeError: Cannot destructure property `mime` of 'undefined' or 'null'. boostnotes`

# Expected behavior

Import success

# Steps to reproduce

1. Set Local Storage
2. Name Folder
3. error

# Environment

Windows 10 / OSX

**Comment by Flexo013** [comment]
It's not quite clear what you are trying to achieve.

What version of Boostnote are you using on either machines? And are you trying to have the notes synchronized between two devices, or are you just trying to migrate the notes from one machine to the other.

**Comment by DenisTome** [comment]
Same error here. Both on ubuntu and OSX.
I'm using version 0.10.1 when I am trying to import notes from Legacy BoostNote.

**Comment by Flexo013** [comment]
@DenisTome Please add any info you have regarding to the problem [here](https://github.com/BoostIO/BoostNote.next/issues/618), as you are using BoostNote.next, not Boostnote Legacy.
