### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by antysocl** [BoostIO/Boostnote#3655]
# Current behavior

Boostnote v0.16.1 won't load in Gnome 3.38.1.  Every time I attempt to open it -- either from the launcher or terminal -- it never progresses past the loading screen.  The output from `journalctl` results in the following:

```bash
Can't update stage views actor StWidget is on because it needs an allocation.
Oct 19 17:20:18 archer gnome-shell[1906]: setup_framebuffers: assertion 'width > 0' failed
Oct 19 17:20:18 archer gnome-shell[1906]: Can't update stage views actor StWidget is on because it needs an allocation.
```

# Environment

- Boostnote version: 0.16.1
- OS version and name: Arch Linux, Gnome Shell 3.38.1

![image](https://user-images.githubusercontent.com/73122519/96513057-7d4ea100-122f-11eb-89e1-743b2a170efc.png)

**Comment by victorbrca** [comment]
Same issue on Arch with KDE Plasma. I cannot open the editor, and that's a big problem.

**Comment by clone1612** [comment]
Arch package maintainer here. I've updated the package with a patch for Electron 10 compatibility. Feel free to let me know if you continue to experience any issues.

**Comment by antysocl** [comment]
@clone1612 That fixed it.  Thanks!
