### ISSUE TITLE
add right click fuctionality

### ISSUE THREAD

**Issue by George35mk** [BoostIO/Boostnote#366]
add right click fuctionality

**Comment by VoLuong** [comment]
@George35mk  Please care to elaborate your request. It is bad just saying `add right click fuctionality` without mentioning *where should we add that, why should we add that and clearly what should be added*

**Comment by asmsuechan** [comment]
Hi, @George35mk. Could you explain this issue more explicit?

**Comment by George35mk** [comment]
yes bro :)

- copy
- paste
- find (like ctr + f)
- delete 
- open 
- save
- save as

**Comment by asmsuechan** [comment]
@George35mk Do you mean like this?
![image80](https://cloud.githubusercontent.com/assets/11307908/24623339/edea3288-185c-11e7-805a-764cde85d673.png)

**Comment by George35mk** [comment]
yep is there??

**Comment by asmsuechan** [comment]
No. I cannot implement that right click. Because right click already has a feature.
<img width="727" alt="screen shot 2017-04-03 at 11 04 22" src="https://cloud.githubusercontent.com/assets/11307908/24623469/5750b274-185d-11e7-9139-5c3a3d8d28ab.png">

**Comment by George35mk** [comment]
on menu side add new folder - that gona hold the snipets in my case for example
if i want to make snipets for angular i want to make folder with name angular 2 that gona hold all my snipets that related with angular

**Comment by George35mk** [comment]
are you have VS CODE ?? look this editor for example

**Comment by George35mk** [comment]
the boostnode is realie good i have save a lot of snipets thnx to creator for sharing this usefull tool

**Comment by VoLuong** [comment]
Your description is hard to comprehend. Can you attach a photo? Also, your right clicking idea is very very bad interms of UI and UX, considering it will requires users to dig down the menu for what they need. Why don't use make an issue regarding a feature request then?
**And please, at least use English the right way.**

**Comment by George35mk** [comment]
my english is not my first language try to speak greek and **then ask that question again**

**Comment by asmsuechan** [comment]
Hey... please don't quarrel...

**Comment by VoLuong** [comment]
![image](https://cloud.githubusercontent.com/assets/15828926/24623912/4abfcbf4-18d4-11e7-9944-8252bb4edf26.png)

I think this is what he is requesting. 
By the way, I am not quarreling at all.

**Comment by asmsuechan** [comment]
Oh, I got it!

<img width="319" alt="screen shot 2017-04-03 at 11 20 26" src="https://cloud.githubusercontent.com/assets/11307908/24624108/a0043318-185f-11e7-94ba-1cf284fced33.png">
