### ISSUE TITLE
Collapsible notes column

### ISSUE THREAD

**Issue by Darkcast** [BoostIO/Boostnote#3665]
Hey team thanks for the great app, I just found it and I fell in love with it.
The only think that I would add/change to it is to have the ability to collapse the my notes column so there more screen realstate to write on 

something like this
![alt text](https://d1r27dnp1fh4g5.cloudfront.net/i/tutorial/sidebar4-animated.gif )

Thank you.

**Comment by Flexo013** [comment]
This feature already (sort of) exists. You can go into full focus mode by pressing Ctrl+B. This will hide the entire sidebar.
