### ISSUE TITLE
add images [Feature Request]

### ISSUE THREAD

**Issue by Darkcast** [BoostIO/Boostnote#3666]
HI team 

Thanks again for this great product. 
I just wante to ask if there is a a way (other thean linking from an external site) to add screenshots into notes ?
I understand that this is beyond the scope of the project but this tools would be a great replacement for MS one note and so many other apps people use to take notes in project etc.

Thank you again and keep up the great work.

**Comment by Flexo013** [comment]
Hi @Darkcast,

This feature already exists. You can copy any image to your clipboard and paste it into any note.

On top of that you can drag and drop images onto the editor if you are using Boostnote Legacy.
