### ISSUE TITLE
Icon is low resolution (1440p) (taskbar pinned)

### ISSUE THREAD

**Issue by Flandre-X** [BoostIO/Boostnote#3671]
# Current behavior

![image](https://user-images.githubusercontent.com/38332081/101474678-184f2780-3911-11eb-90b0-b96abfa98ec5.png)

(1440p display)
(Similar behavior also occurs on 1080p display)

# Expected behavior

![image](https://user-images.githubusercontent.com/38332081/101474731-23a25300-3911-11eb-8d11-70f71a6afdea.png)

(3840x2400 display)

# Environment

- Boostnote version: 0.16.1
- OS version and name: Windows 10

**Comment by Flexo013** [comment]
Duplicate of #1046
