### ISSUE TITLE
Could not load notes

### ISSUE THREAD

**Issue by Imoustak** [BoostIO/Boostnote#3677]
# Current behavior

After reboot my pc and open Boostnote I am prompted to setup storage again. 

Tried `/Users/<my_name>/Boostnote/notes` it opens but no notes appear in Boostnote app. 

I can see in the folder some `.cson` files but when I load this storage I dont get any notes. Could you please advise how I can restore my notes?

![Screen Shot 2020-12-24 at 13 14 43](https://user-images.githubusercontent.com/13902948/103088369-e44f5400-45ea-11eb-860a-53535a85a999.png)
<img width="1057" alt="Screen Shot 2020-12-24 at 13 17 16" src="https://user-images.githubusercontent.com/13902948/103088371-e74a4480-45ea-11eb-8272-31c3965ccd6d.png">

# Expected behavior
To restore my notes 

# Steps to reproduce

Not sure how, I just rebooted my PC

# Environment

- Boostnote version: Version 0.12.2 (0.12.2)
- OS version and name: maOS High Sierra 10.13.4

**Comment by Rokt33r** [comment]
BoostNote.next don't store a note as a CSON file. I think you're trying to load notes from old format storage. Please create a new fresh folder and migrate the notes from your legacy storage.

<img width="1173" alt="Screen Shot 2020-12-27 at 11 12 17 AM" src="https://user-images.githubusercontent.com/5865853/103162471-74340e80-4834-11eb-9d8c-e8b0bf353f39.png">

If my solution doesn't work, please join our slack and ping me so I can directly investigate your problem and address the solution. https://join.slack.com/t/boostnote-group/shared_invite/zt-cun7pas3-WwkaezxHBB1lCbUHrwQLXw

**Comment by Imoustak** [comment]
messaged you on slack!
