### ISSUE TITLE
Any plan or information on Apple Silicon support?

### ISSUE THREAD

**Issue by mtslzr** [BoostIO/Boostnote#3687]
# Current behavior

Runs on M1 Macs via Rosetta 2.

# Expected behavior

Runs natively on Apple Silicon

# Steps to reproduce

N/A

# Environment

N/A

Apologies if this is available elsewhere, but I couldn't find anything from the website nor FAQs... does Boostnote have any current plans or information on supporting Apple Silicon natively?

**Comment by Komediruzecki** [comment]
Hi, mtslzr

Did you target the correct project, you are talking about Boost Note Legacy support for Apple Silicon?

The new Boost Note next is written in the almost latest version of Electron and Electron will soon support the Apple Silicon so it should not be a problem to build the app for Apple Silicon too (found info about this here: https://www.electronjs.org/blog/apple-silicon, might be outdated).

Boostnote legacy is similar but the version of the electron is very outdated, so don't know how many changes would be needed.

**Comment by mtslzr** [comment]
Awesome, thanks! I opened the same issue in `boostnote-next`; will close this and track it there.
