### ISSUE TITLE
Can't pull legacy cloud data locally

### ISSUE THREAD

**Issue by ksmithut** [BoostIO/Boostnote#3689]
# Current behavior

I cannot find a way in the Desktop app to sign into a legacy cloud workspace.

# Expected behavior

I expect to be able to sign into my legacy cloud workspace so that I can retrieve all of my notes.

# Steps to reproduce

1. Have legacy cloud storage.
2. Completely remove boostnote from the computer (I did a clean install of my machine)
3. Reinstall latest boostnote application
4. Click on `+` button in bottom left to create a new space. I only see "Get started for free" which I believe is referring to the new cloud storage, and then there is a "Create a local space" link at the bottom. Through the various links I can't for the life of me figure out how I can sign into my legacy cloud environment.

I still have access to my notes on my mobile app, so they're still in my cloud storage as far as I know. I just can't figure out how to access it in the app. If there's an API for me to retrieve my notes I'd be happy to dig in and pull my stuff out manually as well.

# Environment

- Boostnote version: 0.14.1
- OS version and name: Ubuntu 20.10

**Comment by Komediruzecki** [comment]
Hi ksmithut,

I think the proper tutorials is here: 
https://intercom.help/boostnote-for-teams/en/articles/5018710-how-to-migrate-data-to-the-cloud-space

But It could be impossible to do it in the latest release since login to cloud storage is deprecated, in that case, please use the previous version to log in to your legacy cloud storage, and then once logged in, upgrade to the latest version and migrate your data.

**Comment by ksmithut** [comment]
Ah, makes sense. Apologies for posting to the wrong place. Your suggestion worked for me, thanks :)

**Comment by Komediruzecki** [comment]
I think there is a way to sign into legacy cloud storage but there is a link only when creating/using local space storage, see images:

1. You create local space storage (not file system local storage)
2. Then you go to space settings and there is a legacy cloud storage link that will sign you in
![image](https://user-images.githubusercontent.com/18196945/111750719-d9c3f400-8893-11eb-878e-953c3fed8d7e.png)
![image](https://user-images.githubusercontent.com/18196945/111750724-dcbee480-8893-11eb-9da4-fbc8e1608c35.png)

I am posting this if anyone else has the same problem, the above workaround should work too.
