### ISSUE TITLE
I can't add an external storage from Synology NAS

### ISSUE THREAD

**Issue by zak39** [BoostIO/Boostnote#3707]
# Current behavior

# Expected behavior

Hi everyone 👋 

I use boostnote daily and I would like to share my notes between my devices (laptop and desktop).

But, I didn't add external storage from my Windows 10 pro :/

# Steps to reproduce

1. Open the folder shared from File Explorator (example: `\\Your_Synology_NAS\Note_Shared`
2. Open Boostnote application and click on *Create a space*
3. Then, click on *Create a local space without creating an account*
4. Define the space type on *File System*, then click on  *Select Folder* and select the folder shared `\\Your_Synology_NAS\Note_Shared`
5. Then, click on *Create Space* button and you have the error (see the screen shot below). Here is the error message : `Something went wrong - TypeError: Cannot read property '/' of undefined`

![image](https://user-images.githubusercontent.com/28636549/120077008-8991bb00-c0a8-11eb-9e72-379b8ac12575.png)

# Environment

- Boostnote version: 0.14.1
- OS version and name: Windows 10 Professionnel / 20H2 release

Thank you 😃

**Comment by Komediruzecki** [comment]
Hi zak39,

The application you are showing is boost note next, not boost note legacy application.
Please reopen this issue in boost note next repository issues (https://github.com/BoostIO/BoostNote.next)

**Comment by zak39** [comment]
Hi @Komediruzecki ! :)

Oooh okay I'm sorry !!

I should install the BoostNote.next application on my laptop under Ubuntu 20.04 !

Can I migrate of BoostNote Legacy to BoostNote Next application ?

I reopen this issue in boost note next repository issues ! ;)

I'm sorry for this inconvenience 🙏

**Comment by zak39** [comment]
This issue is moved : https://github.com/BoostIO/BoostNote.next/issues/978

**Comment by Komediruzecki** [comment]
Hi, I left you an reply here: https://github.com/BoostIO/BoostNote.next/issues/978#issuecomment-851841250
