### ISSUE TITLE
macOS keymap(maybe shortcut key) is not user-friendly

### ISSUE THREAD

**Issue by usagrada** [BoostIO/Boostnote#3714]
# Current behavior
I am using default keymap not vim or emacs.
When writing in a markdown editor on macOS
<kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>→</kbd>
<kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd>
If you select all the characters with, the focus will be on create new doc in the sidebar or the workspace name above. Similar problems did not occur with the up and down arrow keys.

# Expected behavior

Even if you select all the characters with the shortcut key map <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>→</kbd> or <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd>, you can delete them while the editor is still in focus.

# Steps to reproduce
Open the editor and press <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd> to select all the characters on that line.

# Environment

- Boostnote version: 0.19.0 
- OS version and name: MacOS Big Sur 11.2.3
- Keyboard: Japanese(JIS)

**Comment by usagrada** [comment]
I've created an issue in the wrong repository.

In addition, this problem is solved by [this merge ](https://github.com/BoostIO/BoostNote.next/pull/1028), so I close this issue by myself.

**Comment by Komediruzecki** [comment]
Yes, you are correct.

The next release should fix the problem.

Please reopen if needed.

Thank you for your patience!
