### ISSUE TITLE
Analytics floods system with requests when using a DNS blocker

### ISSUE THREAD

**Issue by Joshhua5** [BoostIO/Boostnote#3719]
# Current behavior

When using a network based DNS blocker, boost note will receive a 502 when reporting analytics to AWS.
The current retry policy will constantly retry multiple times a second endlessly.  

# Expected behavior

There should be a retry policy which eventually stops sending these requests.

# Steps to reproduce

Block AWS analytic servers using Pi-hole. 

# Environment

- Boostnote version: 0.16.1
- OS version and name: Windows 10

**Comment by Rokt33r** [comment]
I'm assuming you're using local space of the new app. Please check here. It won't send HTTP requests except ones for update check
https://github.com/BoostIO/BoostNote.next-local/releases

**Comment by Joshhua5** [comment]
I'm not, I'm using the original Boostnote, I personally thing .next was the wrong move. 

https://github.com/BoostIO/boost-releases/releases/
