### ISSUE TITLE
UI bugs that scrollbar's overlaid on popup and position of hid box with mouseover.

### ISSUE THREAD

**Issue by memnoth** [BoostIO/Boostnote#372]
OS : elementary OS 0.4 Loki (Based on Ubuntu 16.04)
Ver : Boostnote 0.8.6
Installed by *.deb file.

### Scrollbar's overlaid on popup.
![img1](http://i.imgur.com/Vefvtxp.png)

---

### Position of hidden box with mouseover on **+** button.
![img2](http://i.imgur.com/UYjeL2O.png)

Thank you :)

**Comment by kazup01** [comment]
Thank you for your reporting! We'll check it.

**Comment by jasondavis** [comment]
The scrollbar issue doesn't happen or appear to be an issue on my Windows 7 install

**Comment by dvanderfaeillie** [comment]
Another user of elementary OS here, I can confirm the bug.

**Comment by kazup01** [comment]
Hi @memnoth san, this bug is fixed by @bbtran san on #513 🎉  Enjoy!
