### ISSUE TITLE
Feature request: Import markdown files

### ISSUE THREAD

**Issue by UnR34L** [BoostIO/Boostnote#376]
I like the look and feel of Boostnote so I'd like to start using it but I've built up a collection of .md files that I would need to import before I could commit to using Boostnote.

Is there a way to import .md files, without copying and pasting.

Also, I'd like to request that there be a way to import them from the UI.

Thanks.

**Comment by asmsuechan** [comment]
Hi, @UnR34L. Check this: https://github.com/BoostIO/Boostnote/pull/325. And I'll try to add bulk importer.

**Comment by asmsuechan** [comment]
Duplicated
