### ISSUE TITLE
Failed to get service for display 4

### ISSUE THREAD

**Issue by haxpor** [BoostIO/Boostnote#378]
I cloned the project, do `npm install`, then `npm start`. After that I got error.

```
192:Boostnote haxpor$ npm start

> boost@0.8.7 start /Volumes/Slave/scrap/Boostnote
> electron ./index.js

/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.16/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4
```

I'm using macOS `10.12.4`.
Node version `v.7.5.0`, and npm version `4.1.2`.

**Comment by asmsuechan** [comment]
Hi @haxpor, did you check https://github.com/BoostIO/Boostnote/blob/master/docs/build.md? I recommend you to use `npm run hot` insted of `npm run start` or `npm start`.

**Comment by haxpor** [comment]
OK, thanks a lot. I'm able to run now.
