### ISSUE TITLE
Visual distortion

### ISSUE THREAD

**Issue by metinn** [BoostIO/Boostnote#38]
Hi, 
i have interesting problem. When i move the cursor random partition of boostnote app going to dark.
Here is a screenshot
![screen shot 2016-05-24 at 09 04 10](https://cloud.githubusercontent.com/assets/1876064/15494232/f87b0136-2191-11e6-9a77-12f105e46469.png)

Thank you.

**Comment by Rokt33r** [comment]
It doesn't seem to be a fault of Boostnote itself, the codes I written.
Could you give me more hint?

**Comment by metinn** [comment]
i agree, this is something else. This issue does not happen all the time.
i changed theme. The problem disappeared. then returned to beginning theme but the problem doesn't come back. i am using app without problem for now.

System: OS X Yosemite 10.10.5
If there is a app log i can send it.

**Comment by Rokt33r** [comment]
I'm sorry... we have no way to see app log currently....  the current version doesn't allow users to open dev tool.
(I'm going to enable it on next update)

Anyway, I think it's okay to ignore that problem until someone find the way to repopulate this problem.
Thanks for reporting. :)
