### ISSUE TITLE
Feature: Collapse menus

### ISSUE THREAD

**Issue by mathieug** [BoostIO/Boostnote#380]
It'd be nice to be able to collapse the menus on the left.

**Comment by mathieug** [comment]
Especially in full screen when we want to focus on one note.

**Comment by kazup01** [comment]
Thank you for your suggestion! It is similar to #116.
What do you think about the note opens in a separate window?

**Comment by mathieug** [comment]
Great idea. With the possibility to reduce the main window and also to reduce it into the taskbar (instead of the dock). It'd be like evernote with the Markdown support.

**Comment by kazup01** [comment]
Enjoy Boostnote :)
![screen shot 0029-11-07 at 1 35 16 am](https://user-images.githubusercontent.com/8602615/32452099-edb3c220-c35b-11e7-8f53-37ebe20f85f7.png)
