### ISSUE TITLE
Unnecessary space character when using single quote

### ISSUE THREAD

**Issue by maxart2007** [BoostIO/Boostnote#381]
When using ' character app adds some redundant space after it, I tried using \' but result is the same.
![image](https://cloud.githubusercontent.com/assets/15210696/24647356/403589d6-1928-11e7-942a-c1666d779550.png)

OS: Windows 10

**Comment by kazup01** [comment]
Change the font family and try it(Menu->UI->Preview Font Family) .
I use monaco and it looks like below image.

<img width="669" alt="screen shot 0029-04-04 at 10 52 06 pm" src="https://cloud.githubusercontent.com/assets/8602615/24660273/12d99420-198a-11e7-87a0-2d33f59dff9d.png">

**Comment by asmsuechan** [comment]
This page is probablly helpful https://msdn.microsoft.com/en-us/library/windows/desktop/dd144832(v=vs.85).aspx
