### ISSUE TITLE
Formatting error with Markdown preview

### ISSUE THREAD

**Issue by ajyotirmay** [BoostIO/Boostnote#383]
I was taking notes in Markdown, and this error occured with the "Button" tag. Instead of displaying the code, it creates a button in the preview mode.
**Code:**
![boostnote_001](https://cloud.githubusercontent.com/assets/8706789/24650902/703a5b40-1949-11e7-88f7-53b74d1c2d6a.png)

**Preview:**
![boostnote_002](https://cloud.githubusercontent.com/assets/8706789/24650903/7203aff8-1949-11e7-957d-8dba7f05300b.png)

**Comment by asmsuechan** [comment]
Hi, @ajyotirmay. Actually, I fixed this problem on https://github.com/BoostIO/Boostnote/pull/341. 
Please wait until the next release.

**Comment by kazup01** [comment]
We will update it on next update👍

**Comment by kazup01** [comment]
Sorry we can't release this feature at current version(v0.8.8) because it is too less time.
We'll release it next time. Thank you for your waiting! @ajyotirmay

**Comment by ajyotirmay** [comment]
@kazup01 no problem, I'm just glad that this minor inconvenience got fixed. I can wait for the release to be finally out with this fix. I'll be patient ;)

**Comment by kazup01** [comment]
Thank you @ajyotirmay san! arigato gozaimsu👍
