### ISSUE TITLE
KaTeX wrong subscript baseline.

### ISSUE THREAD

**Issue by farebord** [BoostIO/Boostnote#388]
![imagen](https://cloud.githubusercontent.com/assets/602693/24721984/65c2e0c2-1a18-11e7-9a40-e0183f9283f6.png)

Thats what I wrote: A_{mxn}

**Comment by asmsuechan** [comment]
Hi, @farebord. I assume it's not Boostnote's bug.

![screen shot 2017-04-05 at 11 58 04](https://cloud.githubusercontent.com/assets/11307908/24722077/360f976a-19f7-11e7-9916-74baa19188e5.png)

**Comment by farebord** [comment]
Well in khan.github.io/KaTeX/ It worked well, but not in Boostnote.

**Comment by asmsuechan** [comment]
Please tell me your environments.

**Comment by farebord** [comment]
OS: Windows 10.
Last version of Boostnote.
Preview font: Lato.

**Comment by farebord** [comment]
@asmsuechan in the Boostnote image you share the mxn its at same baseline as A, when it should be lower than A.

**Comment by asmsuechan** [comment]
Could you paste a screenshot with opening Developer tool here?

**Comment by asmsuechan** [comment]
@farebord Got it.

**Comment by farebord** [comment]
![imagen](https://cloud.githubusercontent.com/assets/602693/24722582/a24301c4-1a1a-11e7-811e-590e3615fd3d.png)

**Comment by asmsuechan** [comment]
Are there any errors in console?

**Comment by farebord** [comment]
file:///C:/Users%E0%BE%ACundoppDataLocal%0Boostpp-0.8.7resourcespp/resources/fonts/Lato-Regular.ttf Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by asmsuechan** [comment]
That is the cause of the bug. You need to change the font. Sorry, it's Boostnote's bug. We try to change the default font.

related: https://github.com/BoostIO/Boostnote/issues/381

**Comment by farebord** [comment]
I did change the font to Monaco, its still showing me a wrong baseline. No console errors this time...

**Comment by tmaetzold** [comment]
Not a solution but a workaround seems to be to add an additional subscript inside a brace. i.e. r^* = r(1 - t_{_{blend}}) outputs as:

![image](https://user-images.githubusercontent.com/29001110/34564220-69b8301c-f11b-11e7-8875-cea42f04bf2d.png)

**Comment by Flexo013** [comment]
I think that this was fixed when we updated our version of KaTeX.

This looks good to me: 
![image](https://user-images.githubusercontent.com/4507015/61999796-45f35200-b0c9-11e9-87ab-812b28777127.png)
