### ISSUE TITLE
Cursor does not track with where the text is actually being inserted

### ISSUE THREAD

**Issue by Jeremy-Walton** [BoostIO/Boostnote#39]
I just downloaded this today and I am noticing that the cursor does not track with where the text gets placed.
Boostnote Version:  0.5.12 
OS: OSX El Capital

See the Gif below:
![screen recording 2016-05-26 at 04 01 pm](https://cloud.githubusercontent.com/assets/5957102/15588372/a0fd23c8-235b-11e6-9adb-8fb844d58f1a.gif)

**Comment by Rokt33r** [comment]
You should use mono spaced font. :smile: 
https://en.wikipedia.org/wiki/Monospaced_font

Try 'monaco' or 'menlo'

**Comment by Jeremy-Walton** [comment]
That fixed it, thanks.

**Comment by sami3d** [comment]
Was facing the same problem after changing the font to Lato. Installed/Uninstalled nothing worked(!) Anyway, why doesn't it work with other fonts?? that's weird.

**Comment by Rokt33r** [comment]
@sami3d
If you are using Windows, try `Consolas`.

It is a common behavior of Ace editor. To map selectable area, The editor calibrates the width and height of font by calibrating a random char. So you should use monospaced font.
