### ISSUE TITLE
Editing Tags Interface Problem

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#390]
The area where tags are displayed is quite small and does not resize when more tags are added. When a note has a larger number of tags, some of them are not visible and can not be removed. Expected behaviour would be the opposite, i.e. the area resizes so that all tags are visible and can be edited.

**Comment by sosukesuzuki** [comment]
Hi @huettenhain ! thank you for reporting. Certainly, even if you add a tag, the display area will remain small. But, I think that it is possible to remove tags by scrolling horizontally and push remove buttons. however, your opinion may be good. We will discuss that.

**Comment by huettenhain** [comment]
Hey @sosukesuzuki, thanks for the answer. I tried hovering over the tags area and scrolled with my mouse wheel, but nothing happened.

**Comment by sosukesuzuki** [comment]
Thank you for the reporting @huettenhain . hmm, What OS are you using? I'm using OSX 10.11.2. Behavior may be different in other OS.

**Comment by huettenhain** [comment]
This happens both on my Windows 10 Professional machine and on Windows 2008 Server R2.

**Comment by kazup01** [comment]
Sorry for the late support! This problem has fixed at #1121.
Please wait for the next update.

<img width="638" alt="screen shot 0029-11-14 at 9 24 35 pm" src="https://user-images.githubusercontent.com/8602615/32779979-0e9671f4-c983-11e7-909d-1375d2706554.png">
<img width="396" alt="screen shot 0029-11-14 at 9 29 44 pm" src="https://user-images.githubusercontent.com/8602615/32779980-0ec064e6-c983-11e7-92c3-94bac03fe664.png">
![Uploading Screen Shot 0029-11-14 at 9.32.00 PM.png…]()
