### ISSUE TITLE
Area for Tags is too small & not scrollable & not auto-expandable

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#391]
Area for Tags is too small & not scrollable when scrolled & not auto-expandable when window is resized.
I experience this issue on Ubuntu 16.04.2, Boostnote 0.8.7. 
Pls, view this video for detailed description. Here I type in five tag but there is no way to see the fifth tag and resize windows doesnt not resize tag area
https://openload.co/f/JxUCd3lFfcc/2017-04-06_22-08-37.flv

**Comment by huettenhain** [comment]
I [just said the same thing](https://github.com/BoostIO/Boostnote/issues/390), but less elaborate.

**Comment by VoLuong** [comment]
@huettenhain Sorry, I didnt see yours

**Comment by huettenhain** [comment]
@VoLuong No apologies required, I am happy to get support on the issue ;-).

**Comment by kazup01** [comment]
refs: #390
