### ISSUE TITLE
Web version?

### ISSUE THREAD

**Issue by pffreitas** [BoostIO/Boostnote#394]
Have anyone considered a Web version? I think this would make things easier for Boostnote Team

**Comment by asmsuechan** [comment]
Hi, @pffreitas. [Boostnote Team](https://boostnote.io/team/) is Web version for you. What do you mean about web version?

**Comment by pffreitas** [comment]
I mean run Boostnote as a web app on the cloud rather than as a client app on my machine. I figured that Boostnote Team would be web, but I haven't been granted access to it yet.

But I think what I miss are some collaborative features, that are probably on Team version

**Comment by asmsuechan** [comment]
@pffreitas Does it mean `cloud sync`? If so, you need to use other services such as `Dropbox` or `GoogleDrive`. I don't contemplate to implement sync feature in Boostnote app.

**Comment by skogsmaskin** [comment]
I think it would be great to just have it running as a Node web app somewhere without the Electron wrapper. Then it could be run everywhere. Not having Andorid or web access to my notes is kind of a showstopper for me.

**Comment by kazup01** [comment]
Thanks for suggestion! But I'm sorry, this feature is out of scope.

**Comment by txchen** [comment]
@pffreitas I was thinking about this as well. The use case is, I'd like to access and read my notes anywhere.

If we only need readonly mode, I think it won't be too difficult: 
* create a git repo to store the note files
* manually git push to the remote repo
* create a webapp, which reads the git repo and render notes.

Of course, if 3rd party storage integration is done, it would be easier.

**Comment by yashha** [comment]
Good Ideas,
You can also think about LocalStorage integration.
And when you leave the site you are asked to save it locally.
I like how https://github.com/Laverna/laverna did it.

**Comment by chreniuc** [comment]
I also like this idea of having a web based instance running(self-hosted). This way I won't need to install boostnote on all devices.
