### ISSUE TITLE
Prompted to "Update & Install" but nothing happens

### ISSUE THREAD

**Issue by mbchoa** [BoostIO/Boostnote#395]
**Versions**
OSX 10.11.6
Boostnote 0.8.6

Hello!  Really digging this app!  Wanted to quickly report a recurring bug on startup of app.  

**Steps to reproduce:**

1. Open app
    - OS notification appears saying "Update found: Preparing to update..."
    - A few moments later a prompt appears saying: "Update Boostnote:  New Boostnote is ready to install"
2. Click the "Restart & Install"

**Result**
Nothing happens after the application is closed.  The same behavior persists upon re-opening the app every time.

**Comment by asmsuechan** [comment]
Hi, @mbchoa. Thanks for reporting. I assume it's not Boostnote's bug, it's electron-g-release's bug.
Actually, I don't know well how to fix it. But you can download & install the latest version from [our homepage](https://boostnote.io).

refs: https://github.com/BoostIO/Boostnote/issues/242

**Comment by mbchoa** [comment]
Hey @asmsuechan, thanks for the quick reply!  I think the version I got (0.8.6) is already the latest since I just downloaded it from the homepage.  Would be great if there was option to disable the auto-update prompt.

**Comment by asmsuechan** [comment]
> option to disable the auto-update prompt

Good idea! No, current latest version is 0.8.7. OMG, the version on HP is incorrect :fearful: Thank you for reporting again, we'll fix it as soon as possible.

**Comment by kazup01** [comment]
Fixed download link!
https://boostnote.io/

**Comment by mbchoa** [comment]
Thanks @kazup01 and @asmsuechan!
