### ISSUE TITLE
Incorrect behaviour with title rendering if it contains _underscores_

### ISSUE THREAD

**Issue by feikname** [BoostIO/Boostnote#397]
Version: `Boostnote 0.8.7`

In a note title that contains underscores (the `_` character) within the title, Boostnote will attempt to parse those underscores as markdown even when I do not expect it to.

I'd like to have underscores on my titles due to having some projects that actually contain them as part of their names. The actual rendered document is parsed correctly, only the title displayed in the "Notes list" section is wrong.

![image](https://cloud.githubusercontent.com/assets/4926869/24825344/64f4c80e-1bf3-11e7-8d74-6768784765ff.png)

Sample inputs and output:
```text
# `MY_TITLE` → MY_TITLE (OK)
# `MY_TITLE_` → MYTITLE_ (This doesn't even make sense?)
# MY_TITLE → MY_TITLE (OK)
# MY_TITLE_YAY → MYTITLEYAY (Unexpected, but makes sense)
# MY_TITLE_YAY_YEAH → MYTITLEYAY_YEAH (Unexpected, but makes sense)
```

~Also, please note that Boostnote won't do this to titles containing the minus sign (`-`), so this behaviour is inconsistent if the reason for this was to improve readablity in markdown titles containing common separator characters instead of spaces (which is bit weird anyway).~

Related: #95 (perhaps it may be even considered a duplicate, sorry!)

**EDIT:** I wasn't thinking very well, oops! If you saw the previous content (e.g. archived email), please ignore it and only consider the actual one.

**Comment by asmsuechan** [comment]
Hi, @feikname. Thank you for reporting. I reproduce this bug, I'll fix it.

**Comment by asmsuechan** [comment]
Hi, check this https://github.com/BoostIO/Boostnote/pull/398.

**Comment by kazup01** [comment]
Great supporting @asmsuechan .👏

**Comment by feikname** [comment]
@asmuechan Thank you!
