### ISSUE TITLE
Wrong markdown syntax highlighting when specifying source language

### ISSUE THREAD

**Issue by pendar747** [BoostIO/Boostnote#40]
When I specify the source language it sometimes gets confused with syntax highlighting, although the preview displays the code correctly.
This usually happens when the code is right bellow a list:
![example 1](https://cdn.pbrd.co/images/1juZBQVD.png)

But then the issue is resolved once you insert a line bellow the list item
![example 2](https://cdn.pbrd.co/images/1jveKFVb.png)

I'm using 0.4 on ubuntu

**Comment by Rokt33r** [comment]
I confirmed this problem. 

But, it is a bug of Ace editor. It should be fixed from here.
https://github.com/ajaxorg/ace/issues/2978

**Comment by Rokt33r** [comment]
Ace doesn't seem to afford to fix this bug. I'm currently going to replace Ace with Codemirror.

**Comment by Rokt33r** [comment]
Sorry for wait a long time. From v0.7.0, Boostnote will use codemirror. So, this problem will be gone soon.

**Comment by Rokt33r** [comment]
Close it now. You can track the progress on TodoList #68
