### ISSUE TITLE
[FEATURE REQUEST] List of tagged notes

### ISSUE THREAD

**Issue by veszby** [BoostIO/Boostnote#402]
I as a user would like to have a collapsable list of tags  on the left side (below the list of storages). When I select a tag, I would like to see all notes marked with this tag (similarly as I see all notes contained in selected storage).

**Comment by kazup01** [comment]
We are consider about tag area. What do you think about tag UX like #371 ?

**Comment by veszby** [comment]
Great, #371 looks good!

**Comment by kazup01** [comment]
Thank you for checking!
