### ISSUE TITLE
Can be Add Storage after update v0.8.7 for mac version

### ISSUE THREAD

**Issue by ymow** [BoostIO/Boostnote#403]
Cant be add storage direct address after update v0.8.7
![CantCreate](http://i.imgur.com/FfNJXjz.png)

**Comment by ymow** [comment]
Cant be add storage direct address after update v0.8.7

**Comment by asmsuechan** [comment]
Hi, @ymow. I cannot reproduce this issue. Let me know your environment?

**Comment by asmsuechan** [comment]
@ymow Oh, you seem to add a folder located in `/Volumes`, it's not good. Because Boostnote probably doesn't have R/W permission to the directory.

**Comment by ymow** [comment]
but I can save there in last version.
OK, thanks for quickly reply, appreciated for your work.

**Comment by asmsuechan** [comment]
Umm, it's weird... Can you add your folder in under `$HOME`?

**Comment by 1ps0** [comment]
I had the same issue. I then tried moving the storage components to the local drive and reloading, no dice. 

I also rolled back to `0.8.6` and the issue persisted, no mounted volumes involved at all this time. 

Creating an entirely new storage folder failed as well. Refreshing the app (`cmd+r`)  much less restarting it, would remove the entire storage list.

**Comment by asmsuechan** [comment]
Hi, @1ps0. Thank you for reporting. Sorry for inconvenient. Umm, I cannot reproduce it... :fearful: Where was the storage located?

**Comment by 1ps0** [comment]
I created an encrypted dmg specifically for note storage, mounted and aimed the initial storage there. It worked great until I did a restart/security patch (hmm that might be important). Then it just wouldn't acknowledge any data stored in any location.

From the dev console. I'm back on `0.8.7`. 

> When I first load the app.

```
// warning
boostnote.json file doesn't exist the given path 
// error. the volume isn't mounted
Uncaught Error: EACCES: permission denied, open '/Volumes/NO NAME/boostnote.json'
```

> When I try to create a new note w/storage added in menu, but it doesn't show up in main UI

```
Uncaught TypeError: Cannot read property 'folders' of undefined
```

Adding storage doesn't throw any errors.

When I look in `~/Library/Application Support/boost/Local Storage/`, the `file__0.localstorage` file has multiple locations setup in `storages[]`, so my guess is that it's going for index `0` or something. 

If there was any action item I would suggest, maybe list out known storages in the Settings UI, even if they're not working, and allow for purging them.

Gonna purge that whole Local Storage folder and start from scratch. I expect it would fix my issue.

**Comment by ymow** [comment]
@asmsuechan yes, I set direction at Desktop also has the same issue.

**Comment by ymow** [comment]
I got a boostnote.json in desktopn direction.
It's content as below 
{
  "folders": [],
  "version": "1.0"
}

Is it correct?

**Comment by Flexo013** [comment]
I'm closing this issue for now due to prolonged inactivity.

Feel free to reopen/recreate the issue if you are experiencing it.
