### ISSUE TITLE
go through search results with tab

### ISSUE THREAD

**Issue by eleijonmarck** [BoostIO/Boostnote#404]
I would love to be able to search through my notes and to switch between the results with a key 

Given a search
![image](https://cloud.githubusercontent.com/assets/7727602/24839160/b6f0c712-1d55-11e7-9365-ef20d0b98ba2.png)

suggestions:
tab 
down arrow 
ctrl + j (vim)

**Comment by asmsuechan** [comment]
Hi, @eleijonmarck. There is a shortcut key `Ctrl-S` for it.

**Comment by eleijonmarck** [comment]
Sorry I will make it more clear for you. I mean that I would like to go through the search results given a search.

**Comment by asmsuechan** [comment]
@eleijonmarck Oh, I got it. Exactly, current specification is not convenient. Thanks for your feature request :smile:
