### ISSUE TITLE
import / export notes in html

### ISSUE THREAD

**Issue by eleijonmarck** [BoostIO/Boostnote#405]
I would like to import multiple files into boostnote that are in .html

Currently I am using Evernote, but would love to import my notes from evernote into boostnote.
The way that you can export a note from evernote is to export it into html

Sample html:
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta name="exporter-version" content="Evernote Mac 6.10 (454267)"/><meta name="keywords" content="2-next"/><meta name="author" content="Eric Leijonmarck"/><meta name="created" content="2016-10-11 09:06:31 +0000"/><meta name="source" content="desktop.mac"/><meta name="updated" content="2016-10-11 09:07:10 +0000"/><title>add to your CV</title></head><body>
<div>attended a beginner course of golang</div>
<div><br/></div>
<div><br/></div>
</body></html>
```

This would be
Title "add to your CV"; content "attended a beginner course of golang"

**Comment by asmsuechan** [comment]
Hi, @eleijonmarck. Thanks for your feature request. Have you tried [ever2boost](https://github.com/BoostIO/ever2boost)?

**Comment by eleijonmarck** [comment]
That one looks exactly what I am talking about. Just have to somehow deal with the rate limit as pointed at out by the documentation.

How are the capabilities for exporting notes from boostnote? Same like a boost2ever?

**Comment by asmsuechan** [comment]
@eleijonmarck To deal with the limit, I recommend you to use `convert` command.

Umm, to implement `Export as .enex` in Boostnote is probably good.

**Comment by eleijonmarck** [comment]
Great ! Thank you
