### ISSUE TITLE
Request: Global Keyboard shortcut

### ISSUE THREAD

**Issue by xepher0coded** [BoostIO/Boostnote#408]
Could there be a global keyboard shortcut config added for "Open Finder Window" menu bar item?

**Comment by asmsuechan** [comment]
Hi, @xepher0coded. Do you mean this?

![screen shot 2017-04-10 at 12 23 50](https://cloud.githubusercontent.com/assets/11307908/24878592/99f59f32-1de8-11e7-82d3-1eb360e4ae3d.png)

**Comment by xepher0coded** [comment]
Yes, how do you get to that?

**Comment by asmsuechan** [comment]
Here :smile:

![651851931b34ddcd45da00cf56bcd542](https://cloud.githubusercontent.com/assets/11307908/24878751/3d062836-1de9-11e7-9cab-fed6bc5450f8.gif)

**Comment by xepher0coded** [comment]
Thank you!
