### ISSUE TITLE
Better packaging for Linux

### ISSUE THREAD

**Issue by ziggy42** [BoostIO/Boostnote#409]
It would be great to have the app as an [Appimage](http://appimage.org/) or [Flatpak](http://flatpak.org/). Should be very easy to do and would be great for us not running Ubuntu.

**Comment by asmsuechan** [comment]
Hi, @ziggy42. Are they available for electron app? I'm not sure how Linux app works in packaging.

**Comment by ziggy42** [comment]
Hi, 
I'm not sure since I don't develop electron apps but [electron-builder](https://github.com/electron-userland/electron-builder) does support Appimages out of the box and I hope they'll add flatpak [soon](https://github.com/electron-userland/electron-builder/issues/512).

**Comment by asmsuechan** [comment]
@ziggy42 Thank you for informing us! We consider packing for Linux using them.

**Comment by bivainis** [comment]
Isn't it possible to publish electron app for other linux distros? I don't think Slack uses Flatpak or Appimage, yet it's still packaging .rpm for Fedora.

**Comment by ziggy42** [comment]
Sure, you can but then you'll have one package for debian-based distros (.deb) and one (.rpm) for rh-based ones. Appimages work almost everywhere.

**Comment by sferra** [comment]
Related issue: #66

**Comment by IceWreck** [comment]
I think an AppImage is available.
https://bintray.com/probono/AppImages/Boostnote#files

**Comment by probonopd** [comment]
This was just a test AppImage made by me. 

Providing an __official Boostnote [AppImage](http://appimage.org/)__ would have many advantages, as described [here](https://github.com/BoostIO/Boostnote/issues/66#issuecomment-291001510). Let me know if Boostnote developers are interested, I'm here to help.

**Comment by sferra** [comment]
Is there anything we can do to get things moving with regard to this issue?

Having AppImage support would really help with distribution of Boostnote in general on the Linux desktop and maybe also provide a conventient way to update to new releases.

@probonopd is your offer to help still open?

**Comment by probonopd** [comment]
@sferra yes. Boostnote is using `electron-packager`, right? If so, https://github.com/electron-userland/electron-packager/issues/428#issuecomment-292724143 might be what is needed.

**Comment by sferra** [comment]
@kazup01 would you care to comment? :)

**Comment by SkYNewZ** [comment]
Hi all! I just finish to create a repo that contain "official" .rpm package as well as the standalone package. I invite you to check it : https://github.com/SkYNewZ/Boostnote-packages/releases.
I hope it will be helpfull for you.

![capture du 2018-01-16 01-07-33](https://user-images.githubusercontent.com/26750012/34966114-ac1ffde4-fa59-11e7-8600-9382f6a50833.png)

**Comment by Tajnymag** [comment]
There's a Deb->AppImage conversion recipe available in the AppImageKit repository.

* https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#2-convert-existing-binary-packages
* https://github.com/AppImage/AppImages/blob/master/recipes/Boostnote.yml

**Comment by comzeradd** [comment]
You could check [Flathub](https://flathub.org/). They could probably help provide the app as a Flatpak and make it available to almost all linux distributions.

**Comment by probonopd** [comment]
> You could check Flathub. They could probably help provide the app as a Flatpak and make it available to almost all linux distributions.

Does not work on many distributions, at least not out of the box.

**Comment by jimpriest** [comment]
They seem to cover a majority of distros... https://flatpak.org/getting.html

**Comment by probonopd** [comment]
On most distributions, the user has to install Flatpak first, and then needs to install one or more runtimes, and then needs to install the Boostnote Flatpak. Even then it is not working on any Live ISO I have tried so far. In constrast, the user can simply download the Boostnote AppImage, set the executable bit, and be done.

electron-builder can create AppImages easily these days.

**Comment by comzeradd** [comment]
And how do you get updates with AppImage?

**Comment by probonopd** [comment]
Using whatever update method the author of the application has built into the particular AppImage. [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) is recommended, but not mandatory.

**Comment by jaybaeta** [comment]
@SkYNewZ Thanks for doing that. I haven't tried the rpm yet, but the tar works perfectly. Is it possible to also build a 32-bit version, though?

**Comment by chkumar246** [comment]
> Hey, I want to create the Flatpak package for Bootsnote.

Hey any update on Flatpack package? If not then Can I take it?

**Comment by Flexo013** [comment]
@chkumar246 Feel free to take it.

I will be closing this issue as there are many other issues for the exact same feature, some of which already have funding. #2115 #379 #2164 

Let's continue discussion and development of this feature there.

**Comment by probonopd** [comment]
Those are not about AppImage, hence I am opening a ticket regarding AppImage now:
https://github.com/BoostIO/Boostnote/issues/3216

Sad that the 7 "thumbs up" for my AppImage post above are "lost" this way.

**Comment by Flexo013** [comment]
I would love there to be a way to transfer those to the relevant issue, but sadly there isn't. Sorry about that. :(

The GitHub issues of Boostnote have been quite disorganized leading to many duplicate (or very similar) issues. Which on its turn leads to people missing each other or issues getting fragmented. For this reason sometimes these issues have to closed or moved.
