### ISSUE TITLE
Link to another note

### ISSUE THREAD

**Issue by Jeremy-Walton** [BoostIO/Boostnote#41]
I think it would be great to be able to link to another note you have saved. With this, you could create one note that acts as a master list and link it to other notes for finer detail. I would assume when you click the link it would just switch to that note or open it in a split panel.

![screen shot 2016-05-31 at 12 03 03 pm](https://cloud.githubusercontent.com/assets/5957102/15681562/ad532242-2727-11e6-8d9a-195aaafd4aa2.png)
![screen shot 2016-05-31 at 12 02 16 pm](https://cloud.githubusercontent.com/assets/5957102/15681541/95e41f4e-2727-11e6-8c69-24b00954aa99.png)

**Comment by Rokt33r** [comment]
I've been considering it also. So, the next version of Boostnote will use react-router and provide URL of each folder and note.

<img width="351" alt="screen shot 2016-06-01 at 10 25 00 am" src="https://cloud.githubusercontent.com/assets/5865853/15695529/1ec07a40-27e3-11e6-8cd2-260934d20476.png">
> v0.6.* will display current URL in status bar below.

And, the behaviour should be like the behaviour of common browsers.
(Click to switch note / Shift + Click to open in new window)

**Comment by Rokt33r** [comment]
Close it now. You can track the progress on TodoList #68 
I'll implement it soon.

**Comment by schmidt-fu** [comment]
> Close it now. You can track the progress on TodoList #68
> I'll implement it soon.

Are there any updates on this? On #68 it says there's a new todo list in the wiki, but the link doesn't lead to one. I tried to link between nodes in Markdown with e.g. `[Test](Test)`, but I only get a warning that the file could not be opened.

**Comment by modmod24** [comment]
this feature is already supported. you can reference to any note by its ID.

**Comment by modmod24** [comment]
example: [test](:note:<note_id>)

**Comment by iqgustavo** [comment]
Hello ... I really love the idea of Boostnote, I am a constant Wikidpad user but I see many advantages of using Boostnote ... I was wondering if you could implement CamelCase linking.
Wikidpad link: http://wikidpad.sourceforge.net

**Comment by skystack** [comment]
Where does one find the Note IDs in Boostnote?

**Comment by Flexo013** [comment]
@skystack You can find that by clicking the Info button in the top right:  
![image](https://user-images.githubusercontent.com/4507015/94205924-8e242500-fec4-11ea-95ee-779662f7f8d7.png)

**Comment by skystack** [comment]
@Flexo013 
Thank you for the quick response. Unfortunately, I am still having trouble finding the "info button"
Below is a screenshot of my entire boostnote window and I do not see the symbol you shared anywhere.
![Boostnote ID Photo](https://user-images.githubusercontent.com/47925281/95275660-213f5200-0817-11eb-8032-339aa533c4e4.png)

Any help is appreciated! Thank you.

**Comment by Flexo013** [comment]
@skystack You are using [Boost Note.next](https://github.com/BoostIO/BoostNote.next), not Boostnote Legacy. The linking feature is currently only available on Boostnote Legacy.

The feature is request in the new app here: https://github.com/BoostIO/BoostNote.next/issues/313

**Comment by skystack** [comment]
Ahh Thank you!
