### ISSUE TITLE
[FEATURE REQUEST] New Tabs CSS on a Snippet File Type

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#410]
I really like the `Snippet` File Type like a GitHub GIST record.

Right now with the Theme CSS if you have more than 1-2 "Files" in a Snippet file, it is very difficult to see which files you have on the snippet and to select and switch focus between them.

The image below shows a mockup of the current Tabs with a few files and a proposed new version which make each file really stand out more and noticeable....

[View full size image](https://dl.dropboxusercontent.com/s/jkglk623nvpq28w/boostnotes_new_tabs.png)
![](https://dl.dropboxusercontent.com/s/jkglk623nvpq28w/boostnotes_new_tabs.png)

**Comment by kazup01** [comment]
> it is very difficult to see which files you have on the snippet and to select and switch focus between them

That makes sense. I improve UI now, so I will also improve it based on your advise.
Thanks!

**Comment by kazup01** [comment]
This feature is out of scope.

**Comment by PascalAOMS** [comment]
Why is it out of scope?
I think it's pretty important since you miss the tabs on first sight.
