### ISSUE TITLE
Is this a rendering error?

### ISSUE THREAD

**Issue by take-twit** [BoostIO/Boostnote#412]
Hi,

thx for useful app. i always use when i take a note.
but i found a rendering error on windows version.
i write down the following line in code block,
 `<Directory "/home/webadmin/www/public_html">` in edit mode
but it was rendered as
`<directory "="" home="" webadmin="" www="" public_html"="">`
in preview mode.

if i misunderstand, tell me the help such as how to escaping letters.

thx

**Comment by kazup01** [comment]
Hi @take-twit san,
This is error, but @asmsuechan fixed it on #341 , so we will release at next update!

**Comment by kazup01** [comment]
Sorry we can't release this feature at current version(v0.8.8) because it is too less time.
We'll release it next time. Thank you for your waiting! @take-twit

**Comment by take-twit** [comment]
Thank you for telling me that,@kazup01 san.
I'm looking forward to release repairment.
