### ISSUE TITLE
[Theme Request] Remove Menu button on top left

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#413]
The Menu button on the top left sidebar is somewhat a waste of space at the moment.  I think it would be better to move its functionality to the Header menus perhaps inside the 1st menu item "Boiostnote"

[![](https://www.apollowebstudio.com/screenshots/2017/04/Freeter_2017-04-11_10-37-33.png)](https://www.apollowebstudio.com/screenshots/2017/04/Freeter_2017-04-11_10-37-33.png)

**Comment by kazup01** [comment]
Oh looks good! I will consider it! Thank you @jasondavis !

**Comment by loicteixeira** [comment]
FWIW, I don't know if Electron has something built-in for application settings so it adapts to each platforms, but on MacOS, the preferences menu is expected to be accessed from `Boostnote > Preferences` and the keyboard shortcut to be `cmd + ,`.

**Comment by kazup01** [comment]
Thanks for suggestion! But I'm sorry, this feature is out of scope.
