### ISSUE TITLE
Boostnote won't open hyperlinks in external browser

### ISSUE THREAD

**Issue by tombrereton** [BoostIO/Boostnote#414]
When I write a note with a link e.g.

[Secretary problem](https://en.wikipedia.org/wiki/Secretary_problem)

When I click on it after saving it does not open in an external browser.

I'm using windows 10, firefox, (and vim keybindings if that matters)

**Comment by asmsuechan** [comment]
Hi, @tombrereton. Do you mean it cannot open any browsers on click when you put links like this `[Boostnote](https://boostnote.io)` into your note?

Could you paste the markdown text here as far as you can?

**Comment by tombrereton** [comment]
Sorry false alarm - it's because I had [Intel true key](https://www.truekey.com/) installed. 

I've uninstalled it and now it works fine.

**Comment by asmsuechan** [comment]
It's OK! Thank you for using Boostnote :smile:
