### ISSUE TITLE
[REQUEST] Dark+ editor theme (default of Visual Studio Code)

### ISSUE THREAD

**Issue by DFelten** [BoostIO/Boostnote#415]
Thanks for this great tool! I'm using Visual Studio Code for my daily work with the [Dark+ editor theme](https://code.visualstudio.com/docs/getstarted/themes). This is the standard dark design of Visual Studio Code.

It would be great if the design could be implemented in Boostnote.

**Comment by asmsuechan** [comment]
Hi, @DFelten. Thank you for your request! I also feel the dark theme can be better. So we're trying to improve it now. Please look forward to new design :muscle:And feel free to join our slack team when you have something to say casually about Boostnote :smile:

related: https://github.com/BoostIO/Boostnote/issues/328

**Comment by jasondavis** [comment]
I just did a mockup for a dark theme I'm doing as well...

[View fullsize image for details](https://www.apollowebstudio.com/screenshots/2017/04/Boostnote_2017-04-12_05-41-05.png)
![boostnote_2017-04-12_05-41-05 png 1920x956 - httpswww apollowebstudio](https://cloud.githubusercontent.com/assets/186818/24951580/e6d3d480-1f42-11e7-8402-e8d649eb82da.png)

**Comment by kazup01** [comment]
So cool! @jasondavis

**Comment by DFelten** [comment]
@jasondavis The dark skin looks great 👍

**Comment by jasondavis** [comment]
@kazup01 @DFelten Thanks I added a couple more screenshots above just now.  

I basically just open Dev Tools in Boostnote and concentrate on making each section a different color to indicate it's a different component on the page as well as playing around with adding lighter and darker borders in areas to give it more of a "Desktop App" appearance

**Comment by DFelten** [comment]
@jasondavis It would be great if you publish the design when you're ready!

**Comment by lsale66** [comment]
I really hope the implement your themes, my biggest issue is the current themes are difficult to look at.
