### ISSUE TITLE
\\ not working as expected between $$$ $$$

### ISSUE THREAD

**Issue by farebord** [BoostIO/Boostnote#416]
So if I try to inserte a line break in KaTeX, it fails:

What I've tried so far:
`
$$$
A + B = C \\
C - B = A
$$$
`

`
$$$
\text{A + B = C \\ C - B = A}
$$$
`

`
$$$
\text{A + B = C} \\
\text{C - B = A}
$$$
`

`
$$$
\text{A + B = C}
\text{C - B = A}
$$$
`

None of this worked. And the first three fails with a KaTeX error.

**Comment by asmsuechan** [comment]
Hi, @farebord. It's not our issue. [This](http://www.intmath.com/cg5/katex-mathjax-comparison.php) web page is helpful for you :smile:

```
$$$
\begin{aligned}
\text{A + B = C} \\
\text{C - B = A}
\end{aligned}
$$$
```

![screen shot 2017-04-12 at 14 10 39](https://cloud.githubusercontent.com/assets/11307908/24979648/e4c9874c-1f89-11e7-86e4-b7b7ed7e4d6f.png)


refs: https://github.com/Khan/KaTeX/issues/208#issuecomment-215194224
