### ISSUE TITLE
Spanish accents dont working in KaTeX mode.

### ISSUE THREAD

**Issue by farebord** [BoostIO/Boostnote#417]
Every spanish accent I enter between $$$ will return a KaTeX error.
None of this one worked: áéíóúäöü

**Comment by kazup01** [comment]
We are not familiar with Spanish, so could you help us PR?

**Comment by farebord** [comment]
Sure I can, can you point me the file/files I should check?

**Comment by kazup01** [comment]
Thank you for your cooperation!

>Every spanish accent I enter between $$$ will return a KaTeX error. None of this one worked: áéíóúäöü

Please fix this.

**Comment by asmsuechan** [comment]
Hi, @farebord. Would you like to write any documents by katex? If so, bad news, you cannot (https://github.com/Khan/KaTeX/issues/643). Else, you can :smile:

```
$$$
\grave{a}\grave{i}\grave{u}\grave{e}\grave{o}\ddot{a}\ddot{o}\ddot{u}
$$$
```

![screen shot 2017-04-12 at 14 18 52](https://cloud.githubusercontent.com/assets/11307908/24979957/07c3fe16-1f8b-11e7-895b-8f9696487aa8.png)

refs: http://tex.stackexchange.com/tags/accents/info
