### ISSUE TITLE
Scroll bar not showing up when it should after edits

### ISSUE THREAD

**Issue by Snuupy** [BoostIO/Boostnote#419]
~Edit: Restarted boostnote and the bug went away.~

This bug happens on the following conditions:
1. create a new note
2. your note in edit mode is not long enough to need a scroll bar (check the bottom of this post to see a sample file, may differ depending on your screen resolution and font size)
3. your note in display mode is long enough to need a scroll bar

The bug goes away if you change to a different note or restart Boostnote (re-rendering the view)

I'm on Windows 10 x64, Boostnote version 0.87. Screen resolution is 1600x900.

Both editor and preview sizes are font 14 and Consolas font.

![image](https://cloud.githubusercontent.com/assets/964538/24943993/ea6de214-1f0d-11e7-89ac-eba193bbacfd.png)
![image](https://cloud.githubusercontent.com/assets/964538/24943996/ee2f9ad2-1f0d-11e7-8d10-3cb1e5ccb2dc.png)

After scrolling on my mouse to the bottom, there should be a "b" at the last line, but it doesn't show up.

```markdown
# Test
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
b
```

**Comment by joeschwa** [comment]
I have the same bug, but the scroll bar is there (perhaps @Snuupy cannot see it due to his dark theme). In my case the scroll bar does not work at all and re-launching Boostnote or changing notes does not fix the issue. Scroll bars in Windows Boostnote do not work.

Windows 10 x64 
Resolution 1920 x 1080
Boostnote version 0.8.8
Editor Consolas 14 pt

**Comment by Techadler** [comment]
I have the bug in a similar manner.
For me the scroll bar is visible and can be used manually, but the mouse wheel has no effect.
After i switch to another note and back everything works as expected.

Boostnote version 0.8.11

**Comment by joeschwa** [comment]
Installed 0.8.11 and the bug changed for me. Whenever a note that requires scrolling is first displayed, the scroll bar cannot be moved via the mouse. Once the note is scrolled using a mouse scroll wheel or by moving the insertion point via the keyboard, the mouse cursor can then manipulate the scroll bar and scroll the note. Additionally, if I have a note that I can scroll via the mouse cursor manipulating the scroll bar, I can switch between notes that are longer than the window length and use the mouse to scroll them without any initial scrolling by other means. However, once I switch to a note that is shorter than the window length and has no need for a scroll bar, returning to a note that can be scrolled displays a scroll bar that cannot be manipulated with the mouse. Again, once that note is scrolled via keyboard or mouse scroll wheel, the scroll bar can be manipulated via the mouse cursor. 

Windows 10 x64
Resolution 1920 x 1080
Boostnote version 0.8.11
Editor Consolas 14 pt

**Comment by Flexo013** [comment]
This issue is no longer present in the latest version of Boostnote: 0.12.0
