### ISSUE TITLE
Auto-insert bullet in list

### ISSUE THREAD

**Issue by JasonBoccuti** [BoostIO/Boostnote#42]
When writing an unordered list in markdown, Boostnote inserts a new asterisk as you hit return in the list.  But, if you hit return twice (to start writing new content outside the list) that last asterisk should delete itself.

This would really help with productivity while writing!

**Comment by Rokt33r** [comment]
Great idea. 
The only problem is that I don't know how to modify the behaviour of Ace editor. Anyway, I'll give a shot.
If you know some kind of hint to embed it, please teach me.

**Comment by Rokt33r** [comment]
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/markdown.js#L59-L71
It occurs here. But, it doesn't seem to be possible to do that by just modifying method, `getNextLineIndent`. I'll try to find another approach. :)

**Comment by Rokt33r** [comment]
Closed! You can track the progress on TodoList #68
