### ISSUE TITLE
Not using the latest KaTeX version

### ISSUE THREAD

**Issue by dvanderfaeillie** [BoostIO/Boostnote#421]
I think Boostnote uses KaTeX as math render-engine, but this doesn't seem te be the lastest version.

Typing `$$(\hat \theta - \theta) \stackrel{D}{\rightarrow} N(0,1)$$` results in an error:
`KaTeX parse error: Expected 'EOF', got '\stackrel' at position 32: heta) \stackrel̲{D}{\rightarro`

According to the KaTeX (now v0.7.1) pages, since v0.7.0 support for `\stackrel` was added.

**Comment by asmsuechan** [comment]
Hi, @dvanderfaeillie. Thank you for reporting. I didn't notice it so I will try to update KaTeX.

**Comment by asmsuechan** [comment]
Done. https://github.com/BoostIO/Boostnote/pull/422
