### ISSUE TITLE
[Feature-Request] - Add feature to right click a Note and  "Pin to Top" of Notebook Note List

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#423]
Add a feature to show a new Note context menu item when you right click a note in the note list that says something like **Pin to Top**.

When clicked it would:
- flag that note to show at the top of the tag list regardless of the other notes sort and filter options
- apply a new CSS class "pinned" which can be used to style the background color of pinned Notes 
- If a Note is pinned already and the context menu is opened on it, then show a button to reverse the process and un-pin the Note..

**Comment by asmsuechan** [comment]
Hi, @jasondavis! Thank you as always. I feel it's a cool idea so much :smile: But this feature affects data structure of note. I'll need to contemplate it when I implement.

**Comment by jasondavis** [comment]
perhaps just store a list of note ID's that are pinned

**Comment by asmsuechan** [comment]
yeah, I know. it may not be an easy way. But if I would use `LocalStorage`, I can do it not take so much time.

**Comment by jasondavis** [comment]
@asmsuechan Using LocalStorage to store a list of IDs of Pinned notes sounds like an acceptable way as it wouldn't be super important if the pinned ID list was ever reset or lost.  Either way it's just an idea.

**Comment by kazup01** [comment]
@asmsuechan was implemented it. https://github.com/BoostIO/Boostnote/pull/956
We will release it next version!
