### ISSUE TITLE
Boostnote Projects Board for Roadmap

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#427]
With all the good ideas and the community building up around this great software, can I suggest that we put the GitHub Project Boards to use for store Feature requests that are approved/planned, in progess, and completed along with bugs.

Right now this issue tracker is great for discussing them however there are so many ideas that get discussed and then forgot about as they move down the issue line.

The Project boards are here https://github.com/BoostIO/Boostnote/projects the 4th Tab at the top of this GitHub repo.

---

I even setup a mock version on my Forked Boostnote repo to show example https://github.com/jasondavis/Boostnote/projects/1#card-2506299

On a card you can link to the GitHub issue where discussions on a topic take place.

If you think this is a good idea I can even help go through the issue list and add cards for past issues if you need.

I just think this would help put things in perspective as to what has already been discussed and asked about and what is planned for a future release and can even add a rejected column for ideas that are rejected

![chrome_2017-04-14_22-34-40](https://cloud.githubusercontent.com/assets/186818/25060081/aa4db14e-2162-11e7-985a-44fd32ed18a8.png)

**Comment by kazup01** [comment]
Oh that's good idea. I will make it sometime soon!
Thank you for your everyday support @jasondavis !

**Comment by jasondavis** [comment]
@kazup01 Thanks, I am happy to contribute ideas to improve the app as it benefits all of us.

I have 8 Notebook Apps like EverNote, Collate, LeaNote, BoostNote, Nimbus Notes, and 4-5 other Notebook apps to test the features of all of them.

So I am a good source for Feature Ideas.

Also I am really using BoostNote as my main Notebook app for Programming docs, code snippets, and more now.  I really want a Backup/Export feature soon so that if my Boostnote library files become corrupted I will be able to restore and not lose all my work and data....pleeeeeeeease!

**Comment by jasondavis** [comment]
Also if you would like, I can help set up the Project Bpoards by at least adding my Issues posted here to the Board if that would help you, just let me know.  Glad to help in any way.  I have been a PHP and JavaScript Developer for 14 years!

**Comment by jasondavis** [comment]
Sorry I just saw you or someone has already done it! Awesome! thank you

**Comment by kazup01** [comment]
Sorry for delay in reporting! I made [Project board](https://github.com/BoostIO/Boostnote/projects/3).

Thank you for choose the Boostnote!
Since we are developing Boostnote with a very small team, we can't fix all bugs and development speed is not fast. We are terribly sorry about that.
So we need more help in development via Pull Request.What do you think about how can we get more help?
Your advice is very helpful everyday, thank you @jasondavis san ;)


> if designed correctly you should be able to make it where users can upload there own CSS theme files.
Yes, we also want to do so!

> Backup/Export feature soon so that if my Boostnote library files
Have you tried #427 already? This is @asmsuechan  's great work👍

**Comment by jasondavis** [comment]
> Have you tried #245 already? This is @asmsuechan 's great work

I have seen this and it is a great feature to have however when you have 100's+ of notes in 30-40 Notebooks then it is not practical to backup each note separately!  

That is why I request a "Backup/Restore" feature which will save the actual backend `CSON` files and directories all into a single ZIP archive file which can be used to make a whole complete backup and eventually could even add a Restore from Backup function which would allow to use one of these ZIP files to restore a backed up Boostnote colletion.

This is useful:
- When your Boostnote source becomes corrupted with bad files
- You install Boostnote on a new PC/Mac
- You can save your Boostnote backup ZIP file to cloud service so you don't lose any important work stored in Boostnote.

Most ElectronJS apps that create data on a large scale like Boostnote does have a Backup/Restore solution for the reasons above.  

The Export Note feature is great for a per note basis but the backup solution is more for emergencies to make sure work isn't lost.

I realize I could simply backup the source folders/files myself but having a button inside Boostnote menu to zip them all to 1 files and allow me to save somewhere would simplify the process.

Also I don't think it would be too difficult to implement the feature if we can find a good ZIP file Node module it would just be a matter of installing the library and pointing it to the source files directory and adding a Menu button to run it.  Perhaps when I get some time I will look into it.

---

I would love to contribute myself but as of right now I have no previous experience with React so I need to study and work with that some to be of much contribution on Boostnote.

As for getting more Developers to contribute to the project.  I think the project is off to a great start right now as more and more people are sharing on Twitter and writing articles about the app.  It is very useful, the main key is keeping it useful so implementing some of these features will help make the app more useful to more and more users so I think over time they will keep coming as long as the development of features keeps on continuing and stays active.  So far it is pretty active so I think things are on a good path so far!

Another idea would be to list some of the planned features that are to be added in the near future to the `README.md` file as a `Roadmap` of features to come.  It can list the current features the app has and the features that are planned to be added still.

Also a link to the Project Board so people can see what features are planned and what has already been requested.

--- 

Thats all I got for now, keep up the good work.  I use Boostnote everyday on a large scale so I will continue to post ideas that would improve the workflow and UI to make it more useful.  thanks
