### ISSUE TITLE
[Feature Request] - Note Lock Mode Setting

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#429]
# Note Lock Mode Setting

The way I use Boostnote has me often copy and pasting things both to and from a Note.  The result of this is that in some cases if not careful it is possibble to paste over existing text or make modifications on a note that you have no desire in changing.

Because Boostnote doesn't have a **Save** button/function and it auto-saves everything it means that its possibble to lose data easily by mistake.

One cool way to get around the issue is to have a **Lock Mode** for notes.  Simply click a Lock Icon to toggle a Notes Lock state on/off.

## When a note is in lock mode:

- Right clicking a Markdown file will not toggle between editor and preview modes
- No auto-save will be triggered if something was to get deleted or added by mistake
- If a change did try to get by it could show a note to the user oletting them know they are in lock mode and to unlock the file to edit it.

![boostnote_2017-04-15_00-26-53](https://cloud.githubusercontent.com/assets/186818/25060765/25e5ee10-2173-11e7-8228-90d67883e65e.png)

**Comment by larrysolis** [comment]
please add lock feature for code snippets not just for markdown

**Comment by Flexo013** [comment]
@larrysolis What would the lock feature do for snippet notes?

**Comment by larrysolis** [comment]
Same as the lock for markdown.. Prevent unintentional editing of code in snippet..

**Comment by Flexo013** [comment]
That's not the intended feature of the lock button for markdown notes. For those notes it simply locks the interface so it does not switch to the rendered view. Thus allowing you to see the source markdown code without having to have the window in focus.

While a markdown note is 'locked' you can still make edits.

If you want to prevent unintentional editing, then I suggest changing the permissions of that specific note file through your OS and disabling your write permissions.

**Comment by Flexo013** [comment]
A better solution to the original problem as posted in this thread and to @larrysolis's problem as well would be to allow users to turn of auto-saving and provide them with a 'Save Note' button. This however would become a fairly complex feature.
