### ISSUE TITLE
[Feature Request] Note Details and Info

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#430]
Tonight I needed to know the creation date of a note and realized it is not even available in the GUI for viewing.

Would love to see the Note Details popover....

[View fullsize image](https://cloud.githubusercontent.com/assets/186818/25068806/b66d0288-223c-11e7-81f3-1fdebddeb900.png)
![untitled-3](https://cloud.githubusercontent.com/assets/186818/25068806/b66d0288-223c-11e7-81f3-1fdebddeb900.png)

**Comment by sota1235** [comment]
Hi, jasondavis.
Thank you for your proposal!

I want to ask one question for you.
Why do you want this feature? What does it help you for? :)

**Comment by jasondavis** [comment]
@sota1235 1 thing is all the other 8-9 Notebook Apps have this feature and it is useful to see the meta type data for a Note in 1 place like that.

The other day I needed to know the Creation Date and Time and the Created Date and Time of the note but it was not available anywhere in the app.

**Comment by kazup01** [comment]
Hi @jasondavis ,
We will improve this feature at next version like following image!

![info_area 1](https://user-images.githubusercontent.com/8602615/27896503-71afb844-6255-11e7-9f1a-9a4b1b1b437e.png)

**Comment by kazup01** [comment]
Thanks for your suggestion!
