### ISSUE TITLE
Markdown note view not OK

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#432]
I pasted part about "dlg_proc" from http://wiki.freepascal.org/CudaText_API - now MD viewed not like it is on Wiki.
Wiki shows it
 
1) part titles in big font
2) indented text shown as code

Boostnote
1) part titles shown as plaintxt
2) indented text in plaintxt

Linux
![note](https://cloud.githubusercontent.com/assets/4154978/25071601/3ada102e-22c4-11e7-9f36-a9e06f2cfdff.png)

**Comment by asmsuechan** [comment]
Hi, @Alexey-T. 
Could you explain it more explicit? I could not catch it clearly. You mentioned [this page](http://wiki.freepascal.org/CudaText_API), but it doesn't have any MD texts.
A screenshot of the note with Editor mode is helpful for me.

**Comment by Alexey-T** [comment]
I found it was not ok syntax, it was wiki text, wikimedia.
