### ISSUE TITLE
Markdown note, cannot show nested bullets

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#433]
viewer shows bad nested bullets. Ie bullets started from `** `. It is nested to `* `.

Example
```
====Control properties====


* "callback": str: If not empty, active control calls this callback instead of on_dlg event. Has one of forms:
** "module=mmm;cmd=nnn;" - to call method nnn (in class Command) in plugin mmm (mmm is usually subfolder in the "cudatext/py", but can be any module name)
** "mmm.nnn" - the same, to call method, short form
** "module=mmm;func=nnn;" - to call function nnn in root of module mmm
```

**Comment by Alexey-T** [comment]
![not 2](https://cloud.githubusercontent.com/assets/4154978/25071646/740e7802-22c5-11e7-865d-77411bc6b193.png)

**Comment by asmsuechan** [comment]
Hi, @Alexey-T. I assume you misunderstand. You want to nest them, you can write like this below:

```
* "callback": str: If not empty, active control calls this callback instead of on_dlg event. Has one of forms:
  -  "module=mmm;cmd=nnn;" - to call method nnn (in class Command) in plugin mmm (mmm is usually subfolder in the "cudatext/py", but can be any module name)
  -  "mmm.nnn" - the same, to call method, short form
  -  "module=mmm;func=nnn;" - to call function nnn in root of module mmm
```

Also, this web page is helpful: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by FabienDeborde** [comment]
For people like me who couldn't get a sublist to work, I just realized that you need two spaces (one tab won't work).
Hope this helps!

**Comment by Flexo013** [comment]
@FabienDeborde That is configurable in your preferences.

**Comment by FabienDeborde** [comment]
@Flexo013 Oh! I didn't notice. Thank you for correcting me!!
