### ISSUE TITLE
Keymap is not applied when it's just changed.

### ISSUE THREAD

**Issue by Corea** [BoostIO/Boostnote#436]
## Environments
- iMac Retina 4K, 21.5-inch, Late 2015
- macOS Sierra 10.12.3
- Boostnote Version 0.8.7

## Issue
When I changed keymap on boostnote, I couldn't use that new keymap on the editor of document which was already opened. After I opened other documents, the keymap was applied appropriately.

**Comment by asmsuechan** [comment]
Hi, @Corea. Did you try to reload after you had changed?

**Comment by Corea** [comment]
@asmsuechan Oh I didn't read the hint on configuration page :'( Sorry! Then I'll close this issue.

**Comment by asmsuechan** [comment]
No problem. And I think it's a bit confusing behaviour, so I'll fix it. Enjoy :smile:
