### ISSUE TITLE
Markdown syntax highlight issue after code insert 

### ISSUE THREAD

**Issue by Ilyes-Hammadi** [BoostIO/Boostnote#437]
## Description
The markdown highlight system is not working correctly after a code insert. The code highlight shows the titles in blue color, but when inserting a code the next title is in black, then the title after the black is in blue.

## My Configuration
Boostnote version: Version 0.8.7 (0.8.7)
OS: MacOS Sierra 10.12.4

## Screenshot of the issue
![The problem](https://c1.staticflickr.com/3/2809/33928793062_236a1d7fac_b.jpg)
![](https://c1.staticflickr.com/3/2812/33955516771_0cede96502_b.jpg)

**Comment by asmsuechan** [comment]
HI, @Ilyes-Hammadi. Thank you for reporting. I try to investigate it.

BTW, it's very good style issue like role model!

**Comment by asmsuechan** [comment]
Oh, I had fixed it in this PR https://github.com/BoostIO/Boostnote/pull/341 but I didn't notice :laughing:


![screen shot 2017-04-16 at 22 16 01](https://cloud.githubusercontent.com/assets/11307908/25077777/8b3b8326-22f2-11e7-8746-9f46bc3b511d.png)

**Comment by kazup01** [comment]
Great work @asmsuechan 👍

**Comment by Ilyes-Hammadi** [comment]
Great work guys 👍

**Comment by kazup01** [comment]
Enjoy😆

**Comment by kazup01** [comment]
Sorry we can't release this feature at current version(v0.8.8) because it is too less time.
We'll release it next time. Thank you for your waiting! @Ilyes-Hammadi
