### ISSUE TITLE
Group folders into Books

### ISSUE THREAD

**Issue by sambody** [BoostIO/Boostnote#44]
My suggestion is to somehow add the possibility to make separate "books" or "notebooks" or "groups" or "tabs" (or another name) of folders & tags. **Only one "book" would be open at the time**. It would allow to group things separately, for example:

- code snippets
- software notes
- personal notes
- recipes

When I open "recipes" for example, I would only see the folders and tags of "recipes". (And search would only work on "recipes", as an option.) That way Boostnote would be more of a universal note taking application.

**Comment by Rokt33r** [comment]
It will become like you said. I'd been called it as 'Repository'. But, I think the word 'Book' is much better.
Thanks for your opinion and sorry for late answering. :)

**Comment by Rokt33r** [comment]
From v0.6, you can make it.
But, the app uses the word 'Storage' instead of 'Book'.
Thanks for your suggesting.
