### ISSUE TITLE
150% scales content but not menus

### ISSUE THREAD

**Issue by DanielRamosAcosta** [BoostIO/Boostnote#440]
This is what I say:

![image](https://cloud.githubusercontent.com/assets/11427028/25094561/abbfdeec-238f-11e7-82dd-4a6887a55a79.png)

All the content of the main window scales up, but not the top menu... related to #305

**Comment by asmsuechan** [comment]
Hi, @DanielRamosAcosta. Probably it's a specification of electron.
related: https://github.com/BoostIO/Boostnote/pull/339

**Comment by DanielRamosAcosta** [comment]
![image](https://cloud.githubusercontent.com/assets/11427028/25307130/b2bdf316-2793-11e7-94d0-7ce1d9e94f3c.png)
Now looks awesome, thanks @asmsuechan and @sota1235

**Comment by asmsuechan** [comment]
Anytime :smile:
