### ISSUE TITLE
Search Popup not coming up in Ubuntu 16.04

### ISSUE THREAD

**Issue by NourEldin275** [BoostIO/Boostnote#444]
I installed it on Windows and Ubuntu. In Ubuntu the search popup doesn't work with the stock hotkey and even when changed the hotkey.

**Comment by VoLuong** [comment]
Yes I can produce this issue on Ubuntu 16.04.2. There must be something wrong, not hotkey conflict with the system because regardless of what you change it into, it just doesn't work

**Comment by VoLuong** [comment]
@NourEldin275  I can fix this issue now. Please try to change the default hotkey. In ubuntu many hot keys are already assign to something so my advice is that you should try to avoid keys like Alt or Super

**Comment by kazup01** [comment]
Search feature is improved at current version. Try it👍
