### ISSUE TITLE
 wrong-file-owner-uid-or-gid

### ISSUE THREAD

**Issue by lanthaler** [BoostIO/Boostnote#445]
When installing the package on Ubuntu it complains that the package is of low quality and may harm the system. The reason is mainly due to `wrong-file-owner-uid-or-gid`. Try

     lintian boostnote_0.8.7_amd64.deb

The package would need to be build with fakeroot to prevent that

**Comment by Flexo013** [comment]
Thanks for the report! This warning is no longer present during installation on Ubuntu.
