### ISSUE TITLE
Move post from a folder to another

### ISSUE THREAD

**Issue by simiula** [BoostIO/Boostnote#45]
I didn't find any way to do post from a folder to another folder.
I try drag , copy and paste of the 'post' not work.

**Comment by Rokt33r** [comment]
You can change folder from folder select.
<img width="694" alt="screen shot 2016-06-16 at 11 22 54" src="https://cloud.githubusercontent.com/assets/5865853/16103592/b9959424-33b4-11e6-8741-c40a92722aeb.png">
