### ISSUE TITLE
Search within markdowns and scripts not working ??

### ISSUE THREAD

**Issue by ArunNairID** [BoostIO/Boostnote#450]
# **Is this a known issue or is there something wrong with my settings or installer ??**
Search(focus or within the main console) is only able to find the tags and Headings.

![image](https://cloud.githubusercontent.com/assets/25216201/25145409/ba909c40-248e-11e7-84d9-6451bc26e318.png)
![image](https://cloud.githubusercontent.com/assets/25216201/25145421/c4f128bc-248e-11e7-8ef8-632f57a00edf.png)

**Comment by kazup01** [comment]
Current Boostnote does not support contextual search on Snippet, but we will improve it. #306 #400 #404

**Comment by nnsense** [comment]
I was about to raise the same request, today I was afraid I've lost a note but actually wasn't found because I saved it as a snippet! I'll wait patiently :)
