### ISSUE TITLE
Add about section and version info

### ISSUE THREAD

**Issue by RomelSan** [BoostIO/Boostnote#452]
Can't find on what version i am...
add an about section with version information.
Thanks.

**Comment by kazup01** [comment]
Please check info tab(menu->info)
<img width="848" alt="screen shot 0029-04-19 at 1 08 36 pm" src="https://cloud.githubusercontent.com/assets/8602615/25162930/639d9438-2501-11e7-9725-915bcd396f62.png">

**Comment by RomelSan** [comment]
Add a shortcut to the info window in help -> about
Thanks.
