### ISSUE TITLE
Java code (with angle brackets) doesn't render properly in Markdown

### ISSUE THREAD

**Issue by vadimvera** [BoostIO/Boostnote#458]
Whenever I write some Java code there is always a closing XML tag that appears at the end of the code snippet — that refers to the "generic" type I was using (the type between the angle brackets).

For instance, this is how it "looks like":

<img width="1064" alt="note" src="https://cloud.githubusercontent.com/assets/26421776/25209594/2967562a-254a-11e7-945a-c2016697e884.png">

...and this is the markdown "syntax":

![note_markdown](https://cloud.githubusercontent.com/assets/26421776/25209756/03455252-254b-11e7-874b-a4fe63538da6.png)

I'm using `Version 0.8.7 (0.8.7)` under macOS 10.12.4 (Sierra) and Ubuntu 16.04.2 LTS (Xenial Xerus).

**Comment by kazup01** [comment]
Hi @vadimvera san, thank you for your report! This bug is fixed by @asmsuechan on #341 . We will release it at next update on maybe the day after tomorrow.

**Comment by kazup01** [comment]
Sorry we can't release this feature at current version(v0.8.8) because it is too less time.
We'll release it next time. Thank you for your waiting! @vadimvera
