### ISSUE TITLE
Esc key to cancel Editor

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#460]
Wish:
to use Esc to cancel editing mode,and activate Viewer.
For markdown note.
Now i need mouse for it

**Comment by asmsuechan** [comment]
Hi, @Alexey-T. Sadly, I don't intend to add the shortcut because it conflicts with vim keymap.

**Comment by Alexey-T** [comment]
What is vim keymap. I dont use Vim, i use Cudatext.

**Comment by asmsuechan** [comment]
You can set vim keymap from the menu.
Exactly, it doesn't matter who doesn't use vim. Well, I try to contemplate to implement it.

**Comment by miguelprada** [comment]
Hi @Alexey-T, hitting `ctrl+s` (focus search shortcut) does the job for me.

**Comment by Alexey-T** [comment]
Esc is more comfortable, many agree.

**Comment by miguelprada** [comment]
That may or may not be true, depending on the person. :wink: 

Anyways, I was only trying to point out a way to do what you want without reaching for the mouse.

**Comment by Flexo013** [comment]
This shortcut/hotkey is configurable nowadays, thus you can make it <kbd>Esc</kbd> if you prefer that.
