### ISSUE TITLE
Keep resized window size

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#461]
I resized wnd to half of monitor height.
now after restart, I want the same window size.
Pls save it (or pls the option)

Ubuntu x64.

**Comment by asmsuechan** [comment]
Hi, @Alexey-T. I assume it's a bug. So could you open a bug report in accordance with https://github.com/BoostIO/Boostnote/blob/master/contributing.md?
related: https://github.com/BoostIO/Boostnote/pull/221

**Comment by Alexey-T** [comment]
I dont know how to do it, i opened this bug.
