### ISSUE TITLE
Feature: Bold the text based on the text selection

### ISSUE THREAD

**Issue by stenalpjolly** [BoostIO/Boostnote#463]
If I select some text and Press Ctrl+B  '\*\*\*\*' comes after the text like SomeText\*\*\*\*. It should be like \*\*SomeText\*\*

**Comment by kazup01** [comment]
Hi @stenalpjolly , 
That's what I thought. We will remove it at next version, and improve it! #399

**Comment by stenalpjolly** [comment]
Thanks. Looking forward to it.
