### ISSUE TITLE
Feature: Please add dictionary support.

### ISSUE THREAD

**Issue by stenalpjolly** [BoostIO/Boostnote#464]

**Comment by kazup01** [comment]
Hi @stenalpjolly san!
What is "dictionary support"?

**Comment by stenalpjolly** [comment]
Normal English dictionary. Like correction suggestions for spelling mistakes and grammar mistakes.

**Comment by jasondavis** [comment]
this is a nice feature however most apps that do this also make sure it is an option that the user can turn on/off as it can be a bit slow in some cases as the dictionary files are huge!  Also it's not just English, there are dictionary files in every language pretty much

**Comment by kazup01** [comment]
Sorry this feature is out of scope.

**Comment by stenalpjolly** [comment]
How come it is out of the scope. Markdown or any other note taking app mainly used for the documentation where correct grammar and spelling it so important. Even online text editors has the capability to do this. So why can't we do this?

**Comment by kazup01** [comment]
Yes you are right. However, many people don't want this feature at soon, and since we are very small team so we have other priorities.

If you add it and send us a PR, we will check it. This is very helpful for us.

**Comment by stenalpjolly** [comment]
I will try.

**Comment by asmsuechan** [comment]
I have an anxiety.
Programmers often use proper nouns so I think a bunch number of grammatical errors will appear when it will be implemented.
