### ISSUE TITLE
[Feature Request] Export all files within a Snippet Boostnote Note as a ZIP Archive

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#466]
As the image below shows.  We now have an Export as Markdown and Text file option for Markdown files.  We need a way to export a Snippet Note which can contain multiple files within it.

When you view a GitHub Gist that has multiple files it allows you to download the collection of files as a ZIP file.

[Fullsize Image](https://cloud.githubusercontent.com/assets/186818/25287304/dbe2cbe6-268e-11e7-8e84-dacda7bc39a1.png)
![boostnote_2017-04-21_12-30-24](https://cloud.githubusercontent.com/assets/186818/25287304/dbe2cbe6-268e-11e7-8e84-dacda7bc39a1.png)

**Comment by jasondavis** [comment]
I found a nice Node ZIP library https://github.com/cthackers/adm-zip

Can easily add files to a zip archive as wel as read them for an import

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix. Thanks @jasondavis !
