### ISSUE TITLE
Feature: subfolders

### ISSUE THREAD

**Issue by esmeepeters** [BoostIO/Boostnote#467]
When you create a new folder, it would been nice you can add the parent folder. So you can create submaps.

**Comment by klauscfhq** [comment]
Great suggestion! Though probably this is a duplicate of #125 , so you may want to subscribe there for updates : )

**Comment by esmeepeters** [comment]
It's indeed the same request. Thanks for your suggestion, didn't see it before. I'll subscribe to this issue for the updates 👍
