### ISSUE TITLE
Quit Boostnote unexpectedly 

### ISSUE THREAD

**Issue by tomkenta** [BoostIO/Boostnote#47]
Every time I close Boostnote with shortcut cmd + W , The window comes up which says Boostnote quits unexpectedly. While, I can close it correctly when I push window's red close button.

**Comment by Rokt33r** [comment]
Sorry for late answering. I'll check it soon.

**Comment by Rokt33r** [comment]
@tomkenta Which OS you are using? Does it still occur after updating v0.6?
If the problem isn't gone, please reopen this issue.
