### ISSUE TITLE
Zoom reset on changing from snippet to normal note

### ISSUE THREAD

**Issue by mpizenberg** [BoostIO/Boostnote#475]
As soon as I change of current note from a snippet note to a normal note, the zoom is reset to default (even if the value in status bar does not change)

**Comment by kazup01** [comment]
Could you tell me about your development environment? My computer doesn't occur this bug.

**Comment by mpizenberg** [comment]
I'm using arch Linux and installed it from AUR repositories. I launched it
from GUI though so I didn't check any potential console message . It was
just a try so I uninstalled it. When I have some time I will reinstall it
(maybe from source) and check if there are any message

On Apr 24, 2017 13:17, "Kazu Yokomizo" <notifications@github.com> wrote:

Could you tell me about your development environment? My computer doesn't
occur this bug.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BoostIO/Boostnote/issues/475#issuecomment-296526697>,
or mute the thread

**Comment by jasondavis** [comment]
@mpizenberg  You mention changing a Note from a Snippet note into a Normal Note which I presume is a Markdown Note as these are the 2 Note types in Boostnote....
![image](https://cloud.githubusercontent.com/assets/186818/25382612/6ea1fcfa-2986-11e7-8e46-5ea7a5c22307.png)

---

Is this what you mean by that text or do you mean something else?

**Comment by mpizenberg** [comment]
Yes this was what I meant. But not by creating a new note like in the image above (though I don't remember If I tested this). Just switching to an already created markdown note. Sorry for the incomplete issue. I thought this was something easily reproducible. I will complete the issue as soon as I have some time.

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix. Thanks!
