### ISSUE TITLE
Colors unreadable in Dark Theme after Upgrade to 0.8.8

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#478]
After the recent upgrade to 0.8.8, on Windows 10 (and Windows 2k8R2), most of the dark editor themes have severe contrast problems, as I hope you can see from the following sceenshots:

**base16-dark**:
![base16-dark](https://cloud.githubusercontent.com/assets/11869704/25304533/6658c98a-2769-11e7-8268-20ca1443ffbd.png)

**ambiance**:
![ambiance](https://cloud.githubusercontent.com/assets/11869704/25304537/665f07c8-2769-11e7-805d-b2503c485433.png)

**icecoder**:
![icecoder](https://cloud.githubusercontent.com/assets/11869704/25304535/665cc616-2769-11e7-8932-82fb384b0922.png)

**isotype**:
![isotype](https://cloud.githubusercontent.com/assets/11869704/25304536/665e7786-2769-11e7-9f6d-f3b5e923052e.png)

**lesser-dark**:
![lesser-dark](https://cloud.githubusercontent.com/assets/11869704/25304534/665afa16-2769-11e7-98d5-3f3f662e880e.png)

There are some themes that work okay, I am currently using **twilight**. Still, all of the above themes and also some others are practically unusable because some of the code highlighting simply becomes unreadable.

**Comment by kazup01** [comment]
Thank you for trying new design!
hmm, my computer(windows 10) is not occur this problem. I'll investigate it!

**Comment by sota1235** [comment]
Can you give me the text? 
(I guess it is like below)

```markdown
Simply type `test` or `test -help mode:7`
```

**Comment by huettenhain** [comment]
@sota1235: Yea, that's the text. But quite generally, there are some visibility issues in the editor. Not the viewer mind you, only the editor. I don't know where I mentioned this the first time, but I still believe making this fully customizable would be the best idea, i.e. give the users an option to overwrite the default CSS for the design themselves.

**Comment by huettenhain** [comment]
This problem is seriously hindering me from using Boostnote at the moment, because I cannot read what I write in the editor. I think the main problem is that the font weight is far too low, making the font barely visible. Apart from that, some of the colors in some of the themes just don't have enough contrast against the background.

**Comment by kazup01** [comment]
Sorry for inconvenience. I think I should improve windows UI.
Have you already tried to change the font size, font family, editor/code block theme from setting?
We can not make fully customizable theme soon because it is low priority, but you can customize it because Boostnote is Open source software.

**Comment by huettenhain** [comment]
Oh you're brilliant - it was my fault. I had changed the font and font size several versions ago and for some reason, it was always rendered fine until the recent upgrade. A few tiny adjustments to the font and the font size fixed it.

**Comment by kazup01** [comment]
Wow that's great! Enjoy👍
