### ISSUE TITLE
add a backup menu?

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#481]
I git the source of the notes to the github. But it must to open the command line when git push the notes.
Could add a menu or a shortkey to do this automatically?

**Comment by asmsuechan** [comment]
Hi, @xbotao. Yeah, I contemplate implementing that feature. Check it out! :smile:

FYI, how about using https://github.com/gruntjs/grunt-contrib-watch?

**Comment by xbotao** [comment]
Wow, you mean to do the `git push` automatically without any operation by watch the file changes? That sounds very nice.

**Comment by asmsuechan** [comment]
I'm happy to help you :smile:

**Comment by xbotao** [comment]
@jasondavis, What I want to do is export whole Notebook to some html files, and could show by the github-pages. like [this](http://www.lazyboy.site/codes/) what I'm developing.

**Comment by xbotao** [comment]
Sorry, I reply to the wrong issue. @jasondavis
