### ISSUE TITLE
problems of the menu @0.8.8

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#483]
There are some problems about the menu.

![tim 20170422234648](https://cloud.githubusercontent.com/assets/6964173/25305890/23c9d990-27b6-11e7-92a6-4d870e965e3b.png)
![tim 20170422234715](https://cloud.githubusercontent.com/assets/6964173/25305891/244239a8-27b6-11e7-8bdc-fb2c9c6ae1dd.png)

**Comment by sota1235** [comment]
Thanks for reporting.
Please tell me that how can I confirm it?

**Comment by xbotao** [comment]
There is a scroller for notes list. And it should not show at the menu window. My system is win10. 

发自我的 iPhone

**Comment by kazup01** [comment]
Sorry for inconvenient. This bug is already reported, so we will fix it sometime soon. Please check it #154.
