### ISSUE TITLE
generate snippet storage to htmls 

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#485]
I have an idea about share codes to others.
Generate the snippet storage to many static htmls, and push it to github pages.

**Comment by asmsuechan** [comment]
Hi, @xbotao! Sadly, here is no way to export snippets as .md/.txt for now :cry:

**Comment by xbotao** [comment]
Why it cannot work on the windows?  I could not export the snippet.

**Comment by asmsuechan** [comment]
It's a specification. Sorry, it's a bit buggy :sob: Usually, a message box is shown if you manage to export snippets.

**Comment by asmsuechan** [comment]
refs: https://github.com/BoostIO/Boostnote/issues/486

**Comment by xbotao** [comment]
My Email is `xbotao2014@163.com`, could I email you by `suenagaryoutaabc@gmail.com`.
