### ISSUE TITLE
Message box is not shown

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#486]
An error happens when I try to export snippet. The expected behavior is to be shown a message box which describes snippet is not be exported.

```
Uncaught Error: Could not call remote function 'showMessageBox'.
```

![screen shot 2017-04-22 at 20 03 47](https://cloud.githubusercontent.com/assets/11307908/25310394/2cebd6ae-2798-11e7-9ea1-c1ef6f50c9b7.png)

**Comment by LeoLamCY** [comment]
A message box shows up fine here when I try to export a snippet?

![ss](https://cloud.githubusercontent.com/assets/4132984/25323134/4aff90e2-288b-11e7-92b1-0dc8981eed54.jpg)

**Comment by asmsuechan** [comment]
Hi, @LeoLamCY! Thank you for informing me :+1: Umm, it works fine on windows.
