### ISSUE TITLE
Chinese look not clear in docmnets lists

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#487]
Chinese look not clear in docmnets lists.

![chinese look not clear in docmnets lists](https://cloud.githubusercontent.com/assets/6964173/25311904/cc060164-283e-11e7-8ba8-7bc01cef2bfc.png)

**Comment by kazup01** [comment]
Sorry for inconvenient.
We have no Chinese, so we are not familiar with Chinese language. 
If possible, can you try to fix it? We are looking forward to your PR!

**Comment by xbotao** [comment]
I think it can be fixed by set the font-family. I konw how to debug the mainWindow， but donnot konw how to dehug the search window. Could you tell me which style class should I change.

发自我的 iPhone

在 2017年4月24日，上午9:43，Kazu Yokomizo <notifications@github.com<mailto:notifications@github.com>> 写道：


Sorry for inconvenient.
We have no Chinese, so we are not familiar with Chinese language.
If possible, can you try to fix it? We are looking forward to your PR!

**Comment by kazup01** [comment]
Could you tell me what font-family should be used? I'll fix it.

**Comment by xbotao** [comment]
`Monaco, Consolas, Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace`

**Comment by LeoLamCY** [comment]
Or you could set line height to 15px, but the overall height of the notes in the list will be slightly higher.

**Comment by kazup01** [comment]
Could you tell me about your development environment? @xbotao 
My computer doesn't occur this bug.
macOS Sierra
ver 10.12.13

**Comment by xbotao** [comment]
Win10
Bosstnote 0.8.8，update 2days ago

发自我的 iPhone

在 2017年4月24日，下午1:07，Kazu Yokomizo <notifications@github.com<mailto:notifications@github.com>> 写道：


Could you tell me about your development environment? @xbotao<https://github.com/xbotao>
My computer doesn't occur this bug.
macOS Sierra
ver 10.12.13

**Comment by kazup01** [comment]
Thank you. I'll check it.
