### ISSUE TITLE
Does Markdown footnotes support?

### ISSUE THREAD

**Issue by tuewnr** [BoostIO/Boostnote#49]
마크다운 각주 기능은 지원되지 않는건가요? 버그인가요?
[^~], [^~]:를 써봐도 되지 않습니다.

Boostnote는 유용하게 쓰고 있습니다 감사합니다

**Comment by Rokt33r** [comment]
그렇게 필요한것같지 않아서 아직 넣지않고 있었어요.
딱히 어렵진 않아보이니 다음패치떄 넣어볼게요!
감사합니다... 새 버젼 준비중인데 아직 학생이라서 영 개발할 시간이 안나네요...ㅠㅠ
일본은 방학이 한달느려서..ㅠㅠ

여튼 짬짬히 개발하고 있으니 얼른 개선될수 있도록 노력하겠습니다!

**Comment by Rokt33r** [comment]
이번주중으로 적용됩니다!!

**Comment by BaroqueCoding** [comment]
적극반영해주셔서 감사합니다!!

**Comment by Rokt33r** [comment]
@BaroqueCoding 혹시 아이디어나 개선점이 떠오르시는거 있으면 언제든 말씀해주세요! 적극 검토하겠습니다.
다음주 수요일 이후로 시험이 다 끝나고 방학이 시작되기 때문에 8월부터는 제대로 개발에 집중 할 수 있을 것 같아요.
