### ISSUE TITLE
Deleting of note: 2 confirms

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#492]
COnfirm1: from popup menu with 1 item "delete"
Confirm2: from messagebox.
Pls del confirm1. Menu is bad here.

**Comment by asmsuechan** [comment]
Hi, @Alexey-T. I've deleted it already https://github.com/BoostIO/Boostnote/pull/340. And it's released (v0.8.8). Something goes wrong on your update?

**Comment by Alexey-T** [comment]
Tks, it is ok now
