### ISSUE TITLE
Add export function? 

### ISSUE THREAD

**Issue by BevalZ** [BoostIO/Boostnote#493]
I really appreciate your great job. Boostnote replaces remarkable as my default markdown edit,and I love it. But I find I can't export my note to pdf or html,thats really let me down. Hope you could add this to your to-do list. :)

**Comment by kazup01** [comment]
Hi @BevalZ , thank you for your using and message!
Current Boostnote has only .txt and .md export, but we intend to implement pdf export. #133 #245

**Comment by BevalZ** [comment]
Thank you :] Have a nice day

**Comment by BevalZ** [comment]
ThankS! Hava a nice day :]

**Comment by kazup01** [comment]
Same to you👍

**Comment by kazup01** [comment]
refs: #133 #245

**Comment by BevalZ** [comment]
Great! I'm looking forward!

**Comment by kazup01** [comment]
Enjoy!
