### ISSUE TITLE
Nothing works anymore on Mac osx

### ISSUE THREAD

**Issue by jorenrothman** [BoostIO/Boostnote#494]
Just updated the app for Mac osx and nothing works cant add new notes or snippets and i cant view my saved notes and snippets!

**Comment by kazup01** [comment]
Could you tell me about your development environment? 
This bug has not been reported, and my computer doesn't occur it.
macOS Sierra
ver 10.12.13

**Comment by jorenrothman** [comment]
MacOS Sierra
Ver 10.12.4

Getting some error is the js files

main.js:2 Uncaught TypeError: Cannot read property 'setOption' of undefined,
main.js:28 Uncaught TypeError: Cannot read property 'reload' of undefined,
sass.js:16 Uncaught TypeError: Cannot read property 'propertyKeywords' of undefined,

**Comment by sota1235** [comment]
Sorry, it is too few information.
Can you investigate stack trace of the error?

**Comment by jorenrothman** [comment]
Restarted my Mac everything works now

**Comment by kazup01** [comment]
Thank you for your reporting! We will investigate it.
