### ISSUE TITLE
Note title bug when using markdown syntax for h1.

### ISSUE THREAD

**Issue by SMontgomery** [BoostIO/Boostnote#495]
```
Title 1
=======

# Title 2
```

Both of the above lines are rendered as h1 but the title will actually be Title 2.

I would expect the first h1 to be the title.

**Comment by sosukesuzuki** [comment]
Thank you for reporting @SMontgomery ! I knew it for the first time. I'll fix it.

**Comment by sosukesuzuki** [comment]
Hi, @SMontgomery ! This bug was fixed by pull request #510.

**Comment by kazup01** [comment]
Great work @sosukesuzuki !
