### ISSUE TITLE
[Feature Request] Find inside note

### ISSUE THREAD

**Issue by ivoanjo** [BoostIO/Boostnote#499]
Hello!

I would like to request a find (possibly triggered by ctrl/cmd + f) that finds inside the file itself; right now the current search only tells me that a note contains a certain text, not where it is on the note, which is not very helpful.

Thanks for boostnote, and have a great day!

**Comment by kazup01** [comment]
Hi @ivoanjo san,

**Comment by kazup01** [comment]
Thank you for your reporting!
But it already exists the issue at #176 .

If you have any idea, please discuss it in there!

**Comment by ivoanjo** [comment]
Sorry for the duplicate and thanks for the feedback!

**Comment by kazup01** [comment]
No problem! Thank you for your message @ivoanjo san!
