### ISSUE TITLE
about Linux app

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#5]
## [AUR Package for Arch Linux](aur.archlinux.org/packages/boostnote)

You can install Boostnote with the command below.

```
git clone https://aur.archlinux.org/boostnote.git
cd boostnote
makepkg -si
```

# Planned target

## Target OS

- Arch(AUR)
- Ubuntu(PPA)
- Fedora

## Target Desktop Environment

- Unity
- Xfce
- Gnome
- Cinnamon

**Comment by lucaskatayama** [comment]
Yay.....

**Comment by Rokt33r** [comment]
Download links are below.
Be careful. This is currently work in progress. 

Linux app
https://www.dropbox.com/s/bdvk5ebt8s530wp/Boostnote-linux-x64.tar.gz?dl=0

Debian package
https://www.dropbox.com/s/u9nlh0oxsg4id25/boost_0.5.8_amd64.deb?dl=0

**Comment by lucaskatayama** [comment]
Uhuuuuuu so fast

**Comment by Rokt33r** [comment]
I think I should remove Finder and Tray on all of Linux for awhile.

1\. `libappindicator1` is required to show Tray icon on several Desktop environments.
- Xfce doesn't need to install it. 
- Unity seems to be needed to install it.

2\. The method, `app.focus()`, seems to be broken on Linux.
- Xfce : app is not be focused although it comes top of screen.
- Ubuntu : it doesn't work well after it called several times.

Btw, I think these features are not so important.
So, I will implement it one by one after v0.6.* released and become stable.

**Comment by Rokt33r** [comment]
@lucaskatayama 
Could you tell me which desktop environment you are using?

**Comment by lucaskatayama** [comment]
I'm usign Gnome 3.18
Arch linux

**Comment by Rokt33r** [comment]
@lucaskatayama
Thanks! I'll cover it also.

**Comment by Rokt33r** [comment]
Everything seems to be going well. I'll publish Linux app on UAR, PPA on this weekend.
- App will quit on Main window closing or Ctrl + Q
- Finder disabled(this feature will come back after v0.6.*)

**Comment by gromain** [comment]
Yay!

**Comment by Rokt33r** [comment]
I'm really sorry for being late... It is because of my poor English skill...

@gromain 
I pushed it to `git+ssh://aur@aur.archlinux.org/boostnote.git`, but I realized I forgot to change the name of binary. I'll reupload it again.

And, I can't find my package from https://aur.archlinux.org/packages/?SeB=m&K=rokt33r 
How much it takes to be published? I confirmed my pushing finished successfully.

Btw, these are the files I submitted.

.SRCINFO
```
arch = x86_64
pkgbase = boostnote
    pkgdesc = Opensource note app for developers.
```

PKGBUILD
```
# Maintainer: Dick Choi <fluke8259@gmail.com>
# Contributor: Romain Bazile <gromain.baz@gmail.com>
pkgname=boostnote
pkgver=0.5.8
pkgrel=1
pkgdesc="Opensource note app for developer"
arch=('x86_64')
url="https://b00st.io/"
license=('GPL')
groups=()
depends=()
makedepends=()
checkdepends=()
optdepends=()
provides=()
conflicts=()
replaces=()
backup=()
options=()
install=
changelog=

source=(
  "https://github.com/BoostIO/boost-releases/releases/download/v0.5.9/boost_0.5.9_amd64.deb"
  )

noextract=()

md5sums=('df56bf3167dddb3eb2e1b263c65e61ba')

validpgpkeys=()

package() {
      tar -xa -f ${srcdir}/data.tar.xz
        cp -r "${srcdir}/usr" "${pkgdir}/usr"
}
```

**Comment by Rokt33r** [comment]
Hmm... I'm reading again and again.
Should I provide the installing instruction like below?

```
git clone https://aur.archlinux.org/boostnote.git
makepkg -si
```

**Comment by Rokt33r** [comment]
I've just fixed most of problems. App seems to be installed successfully with the shell script above.
But, I still don't know how can I show my app on [AUR packages page](https://aur.archlinux.org/packages/).

**Comment by Rokt33r** [comment]
OMG, I misstake pushing my PKGBLD. I'll delete this comment after I finish fixing this problem.

**Comment by Rokt33r** [comment]
I ask about this problem on Arch forum. It was because the submitted .SRCINFO file was invalid..
https://bbs.archlinux.org/viewtopic.php?pid=1619904#p1619904

Eventually, my app shows up. https://aur.archlinux.org/packages/boostnote/
But, I think I have to make my PKGBLD build the app from scratch.

**Comment by gromain** [comment]
Sorry I didn't get back to you earlier, I was away!
I'm glad to see you got it working!

Pacman even made the update automatically this morning! ;-) This is super great!

**Comment by gromain** [comment]
As for their comment, here is a changed PKGBUILD, with empty fields removed and use of `$pkgver`:
```
# Maintainer: Dick Choi <fluke8259@gmail.com>
# Contributor: Romain Bazile <gromain.baz@gmail.com>
pkgname=boostnote-bin
pkgver=0.5.9
pkgrel=1
pkgdesc="Opensource note app for developer"
arch=('x86_64')
url="https://b00st.io/"
license=('GPL')

source=(
  "https://github.com/BoostIO/boost-releases/releases/download/v$pkgver/boost_$pkgver_amd64.deb"
  )

md5sums=('df56bf3167dddb3eb2e1b263c65e61ba')

package() {
      tar -xa -f ${srcdir}/data.tar.xz
      cp -r "${srcdir}/usr" "${pkgdir}/usr"
}
```

**Comment by Rokt33r** [comment]
I'm so glad to hear that. Thank you again. I'll update it soon. Haha

**Comment by brpaz** [comment]
finder is a very important feature for me. Hope to see it re-enabled soon :)

**Comment by Rokt33r** [comment]
@brpaz 
Yes, I'll. But, It needs to be hacked on my own.
https://github.com/electron/electron/issues/5011

Btw, Which desktop environment you use?

**Comment by Rokt33r** [comment]
@gromain @brpaz To honor your efforts, I want to add your name as contributors to `readme.md` and `package.json`.
Is it okay to do that?

**Comment by fernandofreamundenl** [comment]
Hey @Rokt33r I dont know where to place this question so I'm asking it here, the question is, will we be able to sync notes between devices? 

I'm asking this because I use a different computer for work(mac) and at home where I also do some development I use a Linux distro(it changes from time to time :) )

so if you have an official way of doing this it would be great if you don't, can we sync a folder with dropbox or other cloud software? 

Thanks in advance, or better Domo Arigato! :)

**Comment by gromain** [comment]
@Rokt33r, sure, please do! Thanks a lot!

**Comment by Rokt33r** [comment]
@fernandofreamundenl 
Note will be shared by filesystem :)
It means you will be able to use your dropbox, google drive and even Github repo.
And I have a plan to support fully automatic syncing with github/bitbucket repository.
Btw, we should talk about this issue here #21 

> Domo Arigato! :)

Sadly, I'm not a Japanese although I'm living in Japan. LOL 😆

**Comment by fernandofreamundenl** [comment]
Thanks for the input, I'm looking forward to use v0.6 then.

About being Japanese, it is not the Japanese outside that counts it the one in your heart xD
And you live in Japan and that is Awesome :D

**Comment by brpaz** [comment]
@Rokt33r sure. you can add me as contributor.
I am using Linux Mint and finder seems to work fine before it was removed. but I haven't it much.

**Comment by Rokt33r** [comment]
@brpaz Okay, I'll add you soon. :)

About Finder, I'm sorry about that. I'd checked Finder on unity and xfce only...(both of them didn't work well)
I'll check finder on cinnamon. If it works fine, I'll enable it again when user is using cinnamon.

**Comment by Rokt33r** [comment]
@brpaz I confirmed Finder works fine on Cinnamon. So, I have to make a function to check if user is using cinnamon. It would be finished on this week. :smiley:

**Comment by Rokt33r** [comment]
Great! I found It can be accessed by `process.env.DESKTOP_SESSION`.

**Comment by brpaz** [comment]
Great news :)

**Comment by Rokt33r** [comment]
I need some help to register Boostnote to PPA... I'd been trying to do it. but I couldn't make it.

**Comment by Rokt33r** [comment]
Ubuntu issue has been moved. #66

**Comment by the-mcnaveen** [comment]
I wrote a Brief article about installing Boostnote in Ubuntu and Debian systems.
[Full Install Instruction for Ubuntu/Debian Systems](https://webcheerz.com/install-boostnote-in-ubuntu/)

**Comment by asmsuechan** [comment]
@the-mcnaveen  Awesome! Thank you so much :smile:

**Comment by the-mcnaveen** [comment]
@asmsuechan Welcome Buddy :)
