### ISSUE TITLE
add a link for snippet code 

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#501]
Add a link for `snippet code`, and could add it to the `markdown note`. When click the link, can open the snippet automatically.

What do you think about this?

**Comment by kazup01** [comment]
Hi @xbotao san, your idea is like this #336?

**Comment by xbotao** [comment]
thanks!

**Comment by kazup01** [comment]
Enjoy😆

**Comment by xbotao** [comment]
But I donnot konw how to get the link of a snippet?
