### ISSUE TITLE
[Bug] [UI Enhancement] Tag input at top of a Note cuts off view if Tags are wider than the Input field

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#503]
The image below shows on my Windows version of Boostnote a Note with Tags that are wider than the Tag Input.

Could you make the tag input field wider?

Possibly make the folder select dropdown field a little wider and maybe even add a Folder icon to the lect of it so people know it is a folder field

![image](https://cloud.githubusercontent.com/assets/186818/25382094/3ae5ddca-2984-11e7-8dc7-9dd2db1be1d5.png)

**Comment by huettenhain** [comment]
I [already reported this earlier](https://github.com/BoostIO/Boostnote/issues/390).

**Comment by jasondavis** [comment]
@huettenhain thanks I didn't see that.  You think I should delete this post?

**Comment by kazup01** [comment]
Yes, we should fix it. I think @jasondavis 's proposal at #430 is so good!

**Comment by kazup01** [comment]
I close it, please check #390. Thanks!
