### ISSUE TITLE
[UI Enhancement] Note list in Sidebar has a scrollbar that shows on top of the Create New Note Modal WIndow

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#504]
When you open the New HNote Modal window in Windows Boostnote and resize the window to a smaller width...

The Note list Sidebar scrollbar has a higher CSS `z-index` value than the Modal DIV making the scrollbar show up on top of the Modal.

Maybe could increase the Modal window `z-index` value to fix in next release.

![image](https://cloud.githubusercontent.com/assets/186818/25382687/bfa9580a-2986-11e7-95db-277cfc6e7b43.png)

**Comment by kazup01** [comment]
Please fix it and send us to your PR. We'll check it.

**Comment by bbtran** [comment]
@kazup01 Has a PR been created for this yet?
On windows, adjusting the z-index does not fix the scrollbar above the modal.

After looking into the modal styl, it looks like the only fix for now would be to set the `::-webkit-scrollbar` display property to none. Another alternative would be to add and remove the class `.hide-scrollbar` whenever the modal component mounts and unmounts, which would also toggle the display property.

**Comment by kazup01** [comment]
Hi @bbtran ,
Perhaps no one has fixed this yet. Oh, I see. It will be very helpful if you fix it and send us a PR!
Thank you for your cooperation!

**Comment by jasondavis** [comment]
@bbtran thanks
