### ISSUE TITLE
Cannot change folder of a saved note

### ISSUE THREAD

**Issue by fmomin** [BoostIO/Boostnote#506]
If a note was created under Default then unable to set it to different folder again nor can drag/drop

**Comment by fmomin** [comment]
Seems like issue for specific note. No matter how many times I create it. It gets moved to Default.

**Comment by kazup01** [comment]
Could you tell me about your development environment? 
This bug has not been reported, and my computer doesn't occur it.
macOS Sierra
ver 10.12.13

**Comment by kazup01** [comment]
And current version can not using drag&drop. please check it #396

**Comment by fmomin** [comment]
Boostnote 0.8.8
Windows 10 x64

**Comment by kazup01** [comment]
Can you recover it after restart?

**Comment by fmomin** [comment]
Sorry, didn't understand you comment.

I have 4 folder (including default) in My Storage.
Default has 2 Notes
Folder 2 has 14
Folder 3 has 4
Folder 4 has 6

Whenever I create a new note now in Folder 2 it automatically gets moved to Default.

**Comment by fmomin** [comment]
I just deleted Default folder for now (Seeded Folder) and seems to keep the note in Folder 2 now

**Comment by fmomin** [comment]
I was copy pasting my notes to the app to sync and all of sudden the app went white and after restart it is not showing the storage. I do see the json/cson files in folder but the application is not detecting it any more even if I click Add Storage. Please help.

**Comment by fmomin** [comment]
Can you please help me relink the storage that went missing. Thanks

**Comment by kazup01** [comment]
You can relink that storage if you choose the correct file. 
Menu->Storages->Add storage->Location

**Comment by fmomin** [comment]
It was not linking coz there seems to be a special character issue. I created a new Issue for that. Let me know if you need any additional inputs to troubleshoot it.

Thanks for all your help. Appreciate it.

**Comment by fmomin** [comment]
Issue is not related to moving notes but Special Characters issue
