### ISSUE TITLE
[Discussion] Export note to web page like GitHub Pages

### ISSUE THREAD

**Issue by xbotao** [BoostIO/Boostnote#507]
Export note storage to htmls, and show by the github-pages, like [this](http://www.lazyboy.site/codes/).

What do you think about this?

**Comment by kazup01** [comment]
Please check it #493
You have too many duplicates.

**Comment by xbotao** [comment]
Sorry, @kazup01 .  
I know it can export to `.md/.txt` file, I think it's different.
see [this: http://www.lazyboy.site/codes](http://www.lazyboy.site/codes)

**Comment by kazup01** [comment]
Oh sorry, that was my misunderstanding
In which scene do you think this feature is convenient?

**Comment by kazup01** [comment]
Please change title more clearly.

**Comment by xbotao** [comment]
Do you think which title is clear?
I think this could be add to blogs, and share the code just by a link.

**Comment by kazup01** [comment]
Make clear the purpose. (e.g. [Discussion] Export note to web page like GitHub Pages.)
I see. Your idea is sounds interesting! How about embed like GitHub Gist?
<img width="332" alt="screen shot 0029-04-25 at 11 35 39 pm" src="https://cloud.githubusercontent.com/assets/8602615/25390982/0a6e07da-2a10-11e7-8b81-994317fac39b.png">

**Comment by xbotao** [comment]
Sorry, I cannot visit the Github Gist.
I use Booste to manage my code snippets, but it is offline. When I want to share a code with my Classmate, it is Inconvenient. So, I have this idea.
 I do a simple nodejs project to convert the storage to many htmls, and show it by the github pages. But I am not a javascript developer, it's ugly.

**Comment by kazup01** [comment]
> I want to share a code with my Classmate

Maybe Boostnote Team is suitable.(Coming soon!)
Let's learn the Javascript!Go🔥

**Comment by kazup01** [comment]
refs: #405

**Comment by xbotao** [comment]
https://github.com/xbotao/Boost2html @kazup01

**Comment by kazup01** [comment]
Wow, cool!
