### ISSUE TITLE
Copy note in viewer mode--looses EOLs

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#509]
copied all note from MD note in viewer mode. Pasted to other app.
All EOLs lost.
If copy in editor mode-- EOLs are ok.

Linux Ubuntu 

![note--](https://cloud.githubusercontent.com/assets/4154978/25420585/726582fe-2a61-11e7-8884-6b4970fc0bd5.png)

**Comment by LeoLamCY** [comment]
This can be fixed by passing `breaks: true` to markdown-it so line breaks will be rendered as <br>, but I'm not sure if it has been left as default (false) deliberately by @kazup01.

**Comment by kazup01** [comment]
Thanks for your support @LeoLamCY san!
