### ISSUE TITLE
Method to import a large number of notes from elsewhere.

### ISSUE THREAD

**Issue by mike-pittelko** [BoostIO/Boostnote#51]
Needs some what to migrate data in from another app.  Could be a mass of files, each file name should be a new note, the contents of the file should be the content of the file. Could be web archives, pdfs, etc.

**Comment by Rokt33r** [comment]
I agree with that. But I can't understand how to import a note from PDF.(PDF => Markdown)
Could you tell me more information?

**Comment by mike-pittelko** [comment]
Make them attachments to a note.

Mike Pittelko

**Comment by Rokt33r** [comment]
Closed. I need more information to proceed. I'll open it again after you giving more.

**Comment by ttdtrang** [comment]
Just get to know about Boostnote and would like to vote for this feature request. :) Could you please re-open it?

I currently have a bunch of notes in text files I would like to import. So I guess Mike's suggestion is to import only the content of text files into notes. The other files are organized as attachments, similarly to the way html files organize their assets. For example

```
-- my_note.txt
-- my_note  # a directory
  |-- an_attachment.pdf
  |-- a_picture.png
  |-- an_equation.tex
```

Would be nice if `an_equation.tex` can be integrated into resulted markdown file. I can provide some example files for testing if necessary.
