### ISSUE TITLE
Focus/minimize keymap conflict with PhpStorm

### ISSUE THREAD

**Issue by crlssn** [BoostIO/Boostnote#511]
Hi!

I've recently started using Boostnote to save some dev notes, and it looks promising so far. However, the keymap you are using to focus/minimize your app is the same as code formatting in PhpStorm, i.e. alt+cmd+l and yours takes priority even though I have PhpStorm in fullscreen. Because of this I need to close Boostnote after I've saved my note. Please consider changing this or give the user the option to change it to a custom one.

Thank you!

**Comment by kazup01** [comment]
Hi @crlssn san, thank you for your using and message!
You can customize Hotkey yourself.(at Menu -> Hotkey)

<img width="882" alt="screen shot 0029-04-27 at 2 17 19 pm" src="https://cloud.githubusercontent.com/assets/8602615/25468991/6afcfbe8-2b54-11e7-8ed8-5e75ec210c12.png">

**Comment by crlssn** [comment]
Cool, thank you!
