### ISSUE TITLE
The app name in Program Files is 'boost' not 'Boostnote'

### ISSUE THREAD

**Issue by angeloanan** [BoostIO/Boostnote#514]
After updating, the app name on the Programs and Features menu is changed to 'boost'. 

![boostonet](https://cloud.githubusercontent.com/assets/2129163/25482370/b38f37d2-2b7b-11e7-8055-9a6bb2082f50.png)

**Comment by kazup01** [comment]
Could you tell me about your development environment?

**Comment by angeloanan** [comment]
Running Windows 10 64-bit.

**Comment by angeloanan** [comment]
Apparently, No. The app is called 'boost' even after reinstalling. Before the update, It's called Boostnote. Should this be closed / renamed?

**Comment by kazup01** [comment]
It will be fixed at #477 👍
