### ISSUE TITLE
Special Characters Issue

### ISSUE THREAD

**Issue by fmomin** [BoostIO/Boostnote#515]
Note created with Special Characters causes Boostnote to no longer start until the cson is deleted from notes folder.

1. I created a SQL type note with below characters
SELECT COL1, COL2, COL3, COL4, COL5, COL6,
'exec my_pkg.my_func(ATTRIBUTE1=>' || '''' || COL1 || '''' || ', ATTRIBUTE2=>' || '''' || COL2 || '''' || ');'

2. After I saved and restarted boostnote it doesn't show any storage until I delete that cson I had just created

3. Boostnote Version: 0.8.8 Windows x64

4. Boostnote cson when saved looks like this
type: "SNIPPET_NOTE"
description: "Test"
snippets: [
  {
    name: "test.sql"
    mode: "SQL"
    content: '''
      SELECT COL1, COL2, COL3, COL4, COL5, COL6,
      'exec my_pkg.my_func(ATTRIBUTE1=>' || \'''' || COL1 || \'''' || ', ATTRIBUTE2=>' || \'''' || COL2 || \'''' || ');'
    '''
  }
]
title: "Test"
folder: "0fd4494d8d2bd3d5c230"
createdAt: "2017-04-27T14:49:28.936Z"
updatedAt: "2017-04-27T14:49:28.936Z"
isStarred: false
tags: []

**Comment by fmomin** [comment]
Can you please confirm if this a bug or problem with my PC ?

**Comment by kazup01** [comment]
I could reproduce it. This is dangerous, so we will take countermeasures. Thanks for your info!

**Comment by kazup01** [comment]
refs: #677
