### ISSUE TITLE
Alt+tab on Ubuntu

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#516]
- Edit MD note
- On active editor, Alt+tab to Firefox
- Copy some txt in Firefox, Alt+tab back

--> Viewer is active
expected: Editor is active

**Comment by asmsuechan** [comment]
Hello, @Alexey-T. This issue still appears under your environment? If so, let me know more detail, please :smile:

**Comment by Alexey-T** [comment]
More detail? I alt+tab to another app DoubleCommander while Edit mode active (md note). on activating DoubleCommander, edit mode is not active. viewer active.

**Comment by VoLuong** [comment]
Hi @Alexey-T , I think you should choose the lock option, which will keep the editor active after you returned from another application
![image](https://cloud.githubusercontent.com/assets/15828926/25715460/bc0c0552-3125-11e7-9f3e-ab49a2f1149d.png)

**Comment by Alexey-T** [comment]
Okay
