### ISSUE TITLE
[Feature Request] [UI] Make background color of Storage Folder different than its child folders

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#517]
Two UI Request to make the folders look different than there parent storage folder.

1) The child folders could have a larger left padding to make them look indented more, like they are child folders of the parent folder.
2) Also if the Parent storage folder had a slightly different shade background color it would be easiar to see where a storage folder starts.

---

Left image shows current sidebar

Right image shows sidebar with storage folders highlighted and child folders indented for a nested folder look

https://cloud.githubusercontent.com/assets/186818/25511816/4bb7d1d4-2b97-11e7-8eaa-9530ddf2ccb5.png
![image](https://cloud.githubusercontent.com/assets/186818/25511816/4bb7d1d4-2b97-11e7-8eaa-9530ddf2ccb5.png)

**Comment by kazup01** [comment]
That's so good! I will improve it👍

**Comment by kazup01** [comment]
I fixed it. Check #520!

**Comment by kazup01** [comment]
merged
