### ISSUE TITLE
[Feature Request] New Note Type - Kajero Note

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#518]
It would be really cool to add a 3rd Note type using this library Kajero https://github.com/JoelOtter/kajero

## Features

- It is a markdown file but it lets you add "blocks" with a button click.  The block types includes:
  - Markdown/Text block
  - Graph/chart block using 3 different libraries.
  - JavaScript code snippet block with a **Play/Run/Execute** code button that will allow the code in the JS snippet to be ran and show the output below it.
- Data sources - This feature allows you to put in the URL of JSON API's and it will make the data available for use in any of your code snippet blocks!
- Static file.  The Notebook is saved as a Markdown or HTML file.
- If you do not wish to save the file it can be uploaded to GitHub Gist and the URL is returned.

---

## Data Sources

Data sources can be defined. These will be automatically fetched when the notebook is loaded, and made available for use inside code blocks.

![image](https://cloud.githubusercontent.com/assets/186818/25512262/5987106a-2b9a-11e7-82ee-2e31f38f14cf.png)

---

If this was integrated as a new note type, it could instead simply save the doc to Boostnote like the other notes currently are.

The best way to see how amazing it is is to simply look at the demo Notebook Markdown file here http://www.joelotter.com/kajero/

Open that page and click the edit mode button on the top right corner.

In edit mode you can add new blocks, delete blocks, create new blocks, and also move blocks up or down in the page.

Once done you click the "Export notebook" button in the top right corner which shows a screen to save the notebook as Markdown or HTML with a 3rd option of uploading to GitHub Gist.

If integrated to Boostnote, this export note screen could simply over-write the existing "saved file" in boostnote so that the same note can be edited over and over without making a new file.

---

What are the thoughts on this?  I know it is a big request but it is super cool and would be really cool if it was a note type in Boostnote.  

I really like how the JS code snippets have a run button to run the snippet of code in the note.

---

There is a blank note here https://www.joelotter.com/kajero/blank.html

---

## Code Snippet Block with result shown below it

![image](https://cloud.githubusercontent.com/assets/186818/25512363/202ba2e4-2b9b-11e7-8b33-98efd788ca1b.png)

---

## Graph Block

![image](https://cloud.githubusercontent.com/assets/186818/25512343/e8e2e9dc-2b9a-11e7-8d4d-41228f662cd1.png)

**Comment by huettenhain** [comment]
Frankly, this is a bit over the top fancy for my taste. Boostnote is a note taking application. I feel like the functionality you request belongs in your IDE, not your note taking application.

Also, not everyone is a JavaScript developer. To me personally, most of these features are borderline useless. But you do not hear me requesting git integration and a gcc interface, because I have that in Visual Studio code.

**Comment by jasondavis** [comment]
@huettenhain thats fine I just came across it and it is something you don't see everyday.  You see thousands of code snippets but rarely one that runs the code inline.  Also Boostnote it note a regualt notebook app like the other 20 out there, its a "programmer notepad".

In any case i'm not mad or anything just pitched the idea and you pitched your thoughts on it so it's all good =)

**Comment by kazup01** [comment]
Thanks for suggestion! But I'm sorry, this feature is out of scope.
