### ISSUE TITLE
Export Notes

### ISSUE THREAD

**Issue by ishu3101** [BoostIO/Boostnote#52]
Is it possible to export your notes to markdown, html, microsoft word, pdf?

**Comment by Rokt33r** [comment]
Exporting as a markdown or html file will be possible soon.
And exporting as a pdf, docx file would be possible somewhen.

**Comment by ishu3101** [comment]
What about exporting all your notes at once?

**Comment by Rokt33r** [comment]
It is also needed. I'll implement it the update of this weekend.
And, It would appreciate if you please give me more specific hint. 😃

**Comment by Rokt33r** [comment]
Closed. I listed this issue to #68. please track the progress from there!
