### ISSUE TITLE
[Feature] Reload file on change

### ISSUE THREAD

**Issue by dsbert** [BoostIO/Boostnote#521]
I store my notes in a drop box folder. When I change notes on one computer, I have to reopen boostnote on any other computer in order for it to pick up changes. It would be ideal if boostnote automatically detects file changes and updates the notes in memory.

**Comment by kazup01** [comment]
Boostnote Team will play its role. https://boostnote.io/team/
We will release it sometime soon!

**Comment by inovek** [comment]
https://boostnote.io/team/ → Still under construction and a tool like this without collaborative features and missing auto-reload is... sad.
