### ISSUE TITLE
There is a way of using shortcuts in MD?

### ISSUE THREAD

**Issue by UltimateRandom** [BoostIO/Boostnote#528]
I think keyboard shortcuts for formating are a basic feature, example CTRL + B = Bold, CTRL + I = Italic, otherwise doing manually takes far more time, there is a way to do this in boostnote?

**Comment by kazup01** [comment]
Since keyboard shortcuts conflict with vim keymap, it is under consideration.

<img width="870" alt="screen shot 0029-04-30 at 4 28 29 pm" src="https://cloud.githubusercontent.com/assets/8602615/25562510/5d8ec82c-2dc2-11e7-8bce-01d80f00312f.png">

**Comment by kazup01** [comment]
I also want to add keyboard shortcuts in markdown.

**Comment by gabber12** [comment]
Can we have markdown specific shortcuts, if editorKeymap is default. This seems to be a pretty nifty feature for markdown editing. I would guess something like below
```javascript
        keyMaps: {
            "Cmd-B": 'bold',
            "Cmd-I": 'italicize',
            "Cmd-'": 'blockquote',
            "Cmd-Alt-L": 'orderedList',
            "Cmd-L": 'unorderedList',
            "Cmd-Alt-I": 'image',
            "Cmd-H": 'hr',
            "Cmd-K": 'link'
        }
```

I would love to get this started.

**Comment by kazup01** [comment]
That’s really helpful! Thanks a lot! @gabber12

**Comment by gabber12** [comment]
[PR](https://github.com/BoostIO/Boostnote/pull/572) submitted.

**Comment by kazup01** [comment]
We will improve this feature next release!
