### ISSUE TITLE
Rendering subscripts in KaTeX

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#529]
Subscripts in KaTeX are not displayed correctly. System is Windows 10 here.

**Way to reproduce:** Create a MD note and enter `$$s_k$$` .
**Result:** The subscript **k** is displayed in a smaller font and raised slightly above the baseline.
**Expected Behaviour:** The subscript **k** is displayed in a smaller font but slightly dropped *below* the baseline (duh).

Could be a bug in KaTeX or something else interfering.

**Comment by kazup01** [comment]
Thank you for your everyday support. Could you fix it and send us PR?

**Comment by huettenhain** [comment]
Oh, you can close this, it's #388. Sorry for the duplicate.

**Comment by kazup01** [comment]
Thanks!
