### ISSUE TITLE
Tab in list / sublist

### ISSUE THREAD

**Issue by RoToRx88** [BoostIO/Boostnote#53]
A good idea should be to grab the Tab key when in list mode to create a sublist in the list.

* list
* list
  * sublist addes with Tab instead of adding 2 space then a star
* Shift+Tab to return to the main list

The idea is to match the mechanics of https://stackedit.io/editor# maybe ?

**Comment by Rokt33r** [comment]
Good idea. Acutally, I'm gonna make an unique editor for Boostnote.
This would be helpful to enhance UX

**Comment by Rokt33r** [comment]
Closed. I listed this issue to #68. please track the progress from there!

**Comment by RoToRx88** [comment]
Seems like the idea has been implemented, but the issue #68 still refers to the point as not done and I can't edit it.

Anyway, thanks for the feature it's really great !
