### ISSUE TITLE
Wish: dont show last note on start

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#531]
Last MD note shows on start on right.
big note- always shows.
it's not nice for me.
I want to see blank ui. I.e., not my last notes.

E.g., i want to make new note. And on each start I see some of prev notes.
I don't want to see it.

**Comment by kazup01** [comment]
If you want it please customize it yourself.

**Comment by Alexey-T** [comment]
Can you tell, what setting is it?

**Comment by huettenhain** [comment]
@Alexey-T it's in the sourcecode somewhere ;-). You can pull the project and alter it.

**Comment by Alexey-T** [comment]
I cannot, I don't use js

**Comment by sferra** [comment]
I suppose that this feature should not be all too hard to implement and it looks like a legitimate feature request. Why was this issue closed?

I would give it a try if I can find some spare time.

**Comment by sferra** [comment]
@Alexey-T could you please elaborate why you need this behavior? if the reasons are good enough, someone may pick up the task.

**Comment by Alexey-T** [comment]
I wrote, ie copy pasted some long note, It is text from www.
Now on each start I see this long post. about Green tea.
I want to see empty face on start.
to not see my last long note,
