### ISSUE TITLE
Is there a list of keyboard shortcuts?

### ISSUE THREAD

**Issue by arieljannai** [BoostIO/Boostnote#533]
Is there a list of keyboard shortcuts?
For both default and vim mode.

Thanks!

**Comment by kazup01** [comment]
Hi @arieljannai san, There are none list of shortcuts, but we will add it!

**Comment by arieljannai** [comment]
I tried to create a Wiki Page to start gathering the shortcuts I know, but couldn't create a page 🤔 😮

**Comment by asmsuechan** [comment]
Hello, @arieljannai. Here's default shortcuts!

![1-puyfxxdbwfyvgi2c6ujvvw](https://cloud.githubusercontent.com/assets/11307908/25593606/3180fa74-2e72-11e7-8d2b-518b8e292182.png)

**Comment by arieljannai** [comment]
Thanks!

Is there (or can we make) an issue that will list all the relevant keyboard shortcuts, with marks on the ones already exist?
That way people will know what's the status of each keyboard shortcut, and could propose new ones in one issue instead of opening more issues for single specific shortcut.

**Comment by VoLuong** [comment]
Hi @asmsuechan , are you sure these are all the default shortcuts ?
