### ISSUE TITLE
Detects update available, but does not update

### ISSUE THREAD

**Issue by tkshnwesper** [BoostIO/Boostnote#534]
Hi,

I don't know if there is a feature to automatically update Boostnote, but I get a notification that a new update has been found and it's processing, etc. From that message I concluded that it might be downloading the update in the background or something, but it didn't seem to update the app even after a long time. I even tried closing Boostnote and opening it again.

I'm using Windows 8.1.

I just thought it might be faster to ask than read the code ^^

**Comment by kazup01** [comment]
Hi @tkshnwesper san, thank you for your report!
That's the first time I heard that. My computers(macOS Sierra and Windows 10) are not occurred it.
We'll investigate the cause.

**Comment by Pitu** [comment]
I'm having the same issue on Windows 10, Creators Update. I get the new update found notification at least 8 times a day, been happening for the past 2 or so. If you need logs or anything, I can provide.

**Comment by kazup01** [comment]
Thank you for your cooperation @Pitu san!
Could you provide your logs to here? It is so helpful.

**Comment by Pitu** [comment]
Could you tell me where the logs are stored so I can provide them? Thanks!

**Comment by kazup01** [comment]
Please open terminal and send error log.Thanks! refs: #538

**Comment by zdooder** [comment]
I believe I'm having the same problem.  I tried launching the app from a command prompt but there was no output shown there.  I'm attaching the SquirrelSetup.log file that I found, however, and it appears to indicate a problem:

`2017-05-03 20:34:17> IEnableLogger: Failed downloading URL: https://github.com/BoostIO/boost-releases/releases/download/v0.8.9/boost-0.8.9-delta.nupkg: System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
`

If I browse to that URL, I get a 404 Not Found error.  If this isn't the correct log, please advise as to where to find the one you want to see.  Thanks!

[SquirrelSetup.zip](https://github.com/BoostIO/Boostnote/files/975186/SquirrelSetup.zip)

**Comment by Pinjasaur** [comment]
I'm having the same issue. How can I send logs?

**Comment by kazup01** [comment]
If this bug is still occurred, please re-install current version from [here](https://boostnote.io/#download). I'm terribly sorry.
