### ISSUE TITLE
[BUG] Two scrollbars appears on markdown note (Windows 10)

### ISSUE THREAD

**Issue by LetItRock** [BoostIO/Boostnote#535]
Hello,
I've found this bug when I was creating new markdown note:

![przechwytywanie](https://cloud.githubusercontent.com/assets/2607232/25565705/b12bdcea-2dcc-11e7-996b-af3e07ada173.png)

As you can see from image above - two scrollbars appeared, one was from "Edit mode" and another from "Preview mode". When I switched to "Edit mode" the latter one has disappeared.

P.S. Really appreciate your work and love this app :)

**Comment by sota1235** [comment]
Thank for your feedback!
Can you paste the text of its note?

**Comment by NonlinearFruit** [comment]
This happens on Linux (Ubuntu 16.04) as well.

**Comment by kazup01** [comment]
Fixed at current version. Thanks for reporting!
