### ISSUE TITLE
[Linux] Error to install Boostnote 0.8.9-1 version (PKGBUILD)

### ISSUE THREAD

**Issue by alan-garcia** [BoostIO/Boostnote#538]
Hi guys,
I'm trying to install the last version of Boostnote (right now it's 0.8.9-1, May 1 2017) but I can't go on due to PKGBUILD error, I don't know if someone it's happens the same.

From terminal it's says below (sorry, my terminal output is in Spanish, I hope that's understand):

```
boostnote.js ha sido encontrado 
  -> boostnote.desktop ha sido encontrado 
  -> warning-fix.patch ha sido encontrado 
==> Validando los archivos source con sha512sums…
    0.8.9.tar.gz ... Aprobado
    boostnote.js ... Aprobado
    boostnote.desktop ... Aprobado
    warning-fix.patch ... Aprobado
==> Extrayendo las fuentes…
  -> Extrayendo 0.8.9.tar.gz con bsdtar
==> Iniciando prepare()…
/tmp/yaourt-tmp-alan/aur-boostnote/./PKGBUILD: línea 34: patch: no se encontró la orden
==> ERROR: Se produjo un fallo en prepare().
    Cancelando…
==> ERROR: Makepkg no ha podido compilar boostnote.
==> ¿Reiniciar la compilación de boostnote? [s/N]
```

And the line 34 from PKGBUILD file is this:

```
prepare() {
  cd "${_pkgname}-${pkgver}"

  patch -Np1 -i "${srcdir}/warning-fix.patch" // <--- Line 34
}
```

Thanks!

**Comment by kazup01** [comment]
Hi @alan-garcia san, sorry for inconvenience. Thank you for your information!
Could you tell me your dev environment?

refs: #534

**Comment by alan-garcia** [comment]
Hi @kazup01 , I'm using Manjaro Linux distro, version 17.0.1 (Gellivara), and the Linux Kernel version is 4.29.24-1.

Regards

**Comment by clone1612** [comment]
Co-creator of the PKGBUILD here, the cause for this issue is that you are missing the 'patch' package. The build was made for and tested with Arch where this package is always installed but this does not seem to be the case for Manjaro. Try to first install patch with ```pacman -S patch``` and then install Boostnote again, it should work.

**Comment by alan-garcia** [comment]
Hi @clone1612, you're right, I needed to install the **patch** package, and now it's works!!

Thank you very much, and great app!

**Comment by kazup01** [comment]
Thanks @alan-garcia for your reporting, and thanks @clone1612 for your supporting! Enjoy Boostnote :)
