### ISSUE TITLE
Connecting BoostNote to Secure Scuttle Butt

### ISSUE THREAD

**Issue by agentlewis** [BoostIO/Boostnote#539]
I think these could potentially be very complimentary. 

In short BoostNote by running locally does not care about how data is backed up or distributed.

[SSB](http://scuttlebot.io/) does not care about where content comes from, only about storing it as message locally and distributing it via your social graph.

Together these could be very powerful - a variant on boost note would become a [client](https://github.com/ssbc/ssb-client) and would start saving the data into an ssb network. 

Practically this would mean that you would be backing up your data onto you ssb network, be able to easily distribute the content across the network and refer to the data from other clients: eg [patchwork](https://github.com/ssbc/patchwork) a social network or [git-ssb](https://github.com/clehner/git-ssb) git on the distributed ssb database.

So an example situation would be being on a plane, writing some things, mentioning some peeps and when you land having the great experience of everything just sinking up when you come into contact with the internet again.

So what do we need in order to make a BoostNote client for SSB basically reworking how the data is stored, turning it into a message that works with an append-only log (how ssb works)

I would be interested to know if anyone in the BoostNote community is interested in this? I am planning to swarm on this on a weekend in the next few weeks with a friend. I am more than happy to write back hear how we progress but would be even happier to be working with other peeps towards this.

**Comment by GaryFurash** [comment]
Does this stop me from writing to the file system. I'm kind of fine with the way it is.

**Comment by agentlewis** [comment]
Maybe - it would be implementation dependent.

Ideally, it would do both - but I have a suspicion its an either or. Which would probably make it a non-core feature.
