### ISSUE TITLE
Not putting special characters right

### ISSUE THREAD

**Issue by facundomedica** [BoostIO/Boostnote#54]
My native language is spanish, and when I want to insert a special character in my Mac with english keyboard, I press and hold the letter and then enter a number (that is shown in a little window above the cursor). For example: for 'á' I press and hold 'a' and then enter number 2.

In Boostnote it enters 'aá' instead of 'á' only.

**Comment by Rokt33r** [comment]
Thanks for your reporting. It is a bug of ace editor. I created a new issue about it.
https://github.com/ajaxorg/ace/issues/3022

And, I'll make a custom editor for Boostnote on this month.

**Comment by facundomedica** [comment]
Awesome app, by the way! Starting to use it quite often! Thanks

**Comment by Rokt33r** [comment]
@facundomedica Definitely, Ace editor must be replace with Codemirror some when. I comfirmed those special char works well on codemirror.

**Comment by Rokt33r** [comment]
This will be fixed the next update. We replace Ace editor with Codemirror. It seems to work well!
