### ISSUE TITLE
Import/Export a whole Notebook like other notebook apps

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#544]
It would be nice to be able to export a whole Notebook and all its child notes into an file with a custom boostnote extension name and then allow the app to import a Notebook file.  People could backup and restore notebooks as well as share notebooks with others if they want.

I have been using this ZIP library for JS and NodeJS http://stuk.github.io/jszip/ and it works really well and easy to use.

For example to create a file in the new zip archive you can simply set a filename for the file and set the content of the file from a JS variable.

**Comment by asmsuechan** [comment]
You mentioned almost same thing in https://github.com/BoostIO/Boostnote/issues/466, don't you?
