### ISSUE TITLE
Toggle/Hide part of UI 

### ISSUE THREAD

**Issue by LewisVo** [BoostIO/Boostnote#547]
Sometimes I just need the editor part so that I can split my desktop into 2 parts : Boostnote on the left and maybe something else on the right (pdf reading, web browsing...).   :desktop_computer: 
So I request a feature to hide other UI parts except for the editor. Quite often, it feels like I can't read something then take notes at the same time because the UI is so redundant I have to spare a lot of display space for the app.   :smiley:

**Comment by kazup01** [comment]
Hi @VoLuong, it’s been a while.! 
This feature sounds good! I using like this sometimes.😨
![screen shot 0029-05-05 at 2 46 52 pm](https://cloud.githubusercontent.com/assets/8602615/25734966/b2a660f2-31a2-11e7-87c3-5ef1e2654493.png)

Can you try to add this feature?

**Comment by VoLuong** [comment]
>  it’s been a while!   

I was taking a break from github to travel :laughing:   

>  I using like this sometimes.:fearful:    

Your solution is what i am using too. But don't you see, it's just ugly somehow :cry:

**Comment by UltimateRandom** [comment]
I suggest use the menu button, filters, my storage, and search on Top (Horizontal)
Then the notes on the Left (Vertical)
Is going to look similar to OneNote but with the notes on the left 

<img width="320" alt="untitled55" src="https://cloud.githubusercontent.com/assets/20800791/25769622/127670c4-31f5-11e7-822b-4d3d10c071ca.png">

The folders could also have some dropdown menu to subfolders if needed, also both sections could have a breadcrumb button that expand/contracts them so we can use more screen space.

**Comment by kazup01** [comment]
Enjoy full-screen mode!
![screen shot 0029-07-06 at 1 53 49 pm](https://user-images.githubusercontent.com/8602615/27896101-9858281c-6252-11e7-9d7e-249c1bb5685f.png)
