### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by facundomedica** [BoostIO/Boostnote#55]
I was at the readme file of the 0.6.0 version and this caught my attention:

> Target OS : OSX, Windows, Linux(also **mobile** somewhen!)

So I wanted to know if there is anybody involved in the making of a mobile app.

I would like to get involved, I ran the 0.6.0 version but I didn't understand well how the user experience should be. So I suppose that I will have to wait until the release, but in the meanwhile I would like to know if anybody has ideas or thoughts on this.

Edit: I think I'll get started with an app that is like the pre 0.6.0 version

**Comment by Rokt33r** [comment]
I'm glad to hear that.
There is a closed slack team of Boostnote already. Send me a mail, fluke8259@gmail.com, then I'll invite you to the team.

**Comment by Rokt33r** [comment]
This issue will be discussed from #128
