### ISSUE TITLE
Anchor Tag not working in markdown

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#550]
Hi, I am using Boostnote latest version on Ubuntu 16.04.2. 

Anchor tag seems not to be working in Markdown. Anchor tag is like a cross-reference inside a markdown file and it is often used for many purposes, including making a table of content. So hereby I open this issues, hoping that anchor tag will work sometimes in the future :pray:

**Comment by asmsuechan** [comment]
Hi, @VoLuong. I added [markdown-it-toc-and-anchor](https://github.com/medfreeman/markdown-it-toc-and-anchor) in order to be able to use Anchor Tag once. But there was a bug (I fixed). So I'm waiting for a release of it.
