### ISSUE TITLE
Scrollbar very hard to see in dark theme

### ISSUE THREAD

**Issue by VoLuong** [BoostIO/Boostnote#551]
Here is a quick comparison of scrollbar in note between light theme and dark theme. The dark theme's scrollbar is hard to see, especially if it is small (because the note is long).
Light theme ![](http://i.imgur.com/WfuCnRS.png)  
Dark theme ![](http://i.imgur.com/Yb7H45m.png)

**Comment by huettenhain** [comment]
I said this quite a while ago, see #225 - but thanks for the images, it illustrates the problem very clearly.

**Comment by VoLuong** [comment]
Hi @huettenhain . Sorry for duplicating. Although I really did some research to avoid duplicating issue, I didn't see your issue. I will close this and ref #225 
![image](https://cloud.githubusercontent.com/assets/15828926/25738006/f28ccc90-31a4-11e7-8189-cf1a4aa5dc6b.png)
