### ISSUE TITLE
Enable ability to zoom in/ out

### ISSUE THREAD

**Issue by xJeremie** [BoostIO/Boostnote#558]
At present, Boostnote can't be zoomed/scaled to fit the system DPI level (at least on Linux systems). It would be ideal if it can, like almost of electron app.

Thanks for this great app.

**Comment by asmsuechan** [comment]
Hi, @xJeremie. How about this?
<img width="1280" alt="screen shot 2017-05-06 at 11 40 11" src="https://cloud.githubusercontent.com/assets/11307908/25775049/d539e5fe-3250-11e7-904b-68acb0b9e375.png">

**Comment by kazup01** [comment]
Hi @xJeremie san, how about this?
