### ISSUE TITLE
Linux - when close app = still run

### ISSUE THREAD

**Issue by VaclavPavek** [BoostIO/Boostnote#559]
When I close Boostnote it still runs in the background. When restarting, the application does not start.

When running through the terminal, you must quit the application by pressing Ctrl + C.

I use Linux Mint Debian Editon with Cinnamon desktop environment

**Comment by asmsuechan** [comment]
Hi, @VaclavPavek. Did you try `Ctrl - q`? And `Ctrl -C` is not appropriate in this situation. It's usually used in CLI tools.

**Comment by VaclavPavek** [comment]
Hi, @asmsuechan 

Ctrl+Q closes the application correctly

Close / Cross button does not work - if run from CLI and click to Close => app run in background / uncorect close => Ctrl+C to kill process

**Comment by asmsuechan** [comment]
@VaclavPavek It's one of the specifications. Boostnote doesn't stop when you click the close button.

**Comment by VaclavPavek** [comment]
@asmsuechan yes
