### ISSUE TITLE
Keep Boostnote opened in background

### ISSUE THREAD

**Issue by yannickglt** [BoostIO/Boostnote#56]
Great app! I love it but there's a missing feature for me that would make it perfect in my opinion.
It would offer the way to quickly display notes without having Boostnote launched in the dock. Closing Boostnote with the cross or with Cmd+W would only close the main window but the app would continue working in background.
An additional feature would be to allow starting the app in background. In this way, I would everytime launch boostnote on startup.

**Comment by Rokt33r** [comment]
I'm going to fix it on the update of this Sunday. 
And, launching an app on startup is not difficult.

Apple >> System Preferences >> Users & Groups >> Login Items >> Plus Button

<img width="780" alt="screen shot 2016-07-07 at 4 29 31" src="https://cloud.githubusercontent.com/assets/5865853/16645594/2161a302-4460-11e6-85f3-cbb3dcb3626e.png">

**Comment by Rokt33r** [comment]
From v0.6, closing main window doesn't cause quitting app
