### ISSUE TITLE
Ctrl + w should delete previous word, not exit editing

### ISSUE THREAD

**Issue by justin-calleja** [BoostIO/Boostnote#561]
Instead of exiting the editor:

![ctrl w](https://cloud.githubusercontent.com/assets/3186719/25894098/e11878f4-357a-11e7-8baf-be68052acd8d.gif)

`ctrl + w` should delete previous word (should work that way in your terminal).

**Comment by Oylex** [comment]
I'm not saying that's what it should do, but in PhpStorm `ctrl+w` selects the word the cursor is in, and multiple presses just expands the selection.

However, in other applications it closes the window.

**Comment by justin-calleja** [comment]
@Oylex , the only reason I'm saying `ctrl + w` should delete the previous word is because that's one of the basic Emacs commands which is available by default (AFAIK) on all shells and ppl could be used to that.

For e.g. in Boostnote, other Emacs combinations work as expected: `ctrl+n`, `ctrl+p`, `ctrl+f`, `ctrl+b`, `ctrl+a`, `ctrl+e`, `alt+f`, `alt+b` etc... I don't use them all (not an Emacs user myself - but I use these all the time in the terminal).

In any case, there's an open issue on being able to map these things so that should sort this out.

**Comment by Flexo013** [comment]
<kbd>Crtl</kbd>+<kbd>W</kbd> being the close shortcut makes sense when coming from other application as @Oylex mentioned. Some of our default hotkeys are indeed based on Emacs, but not all of them.

I think allow the user to remap these hotkeys would probably be best, so every user can change them to their liking. This issue will be continued in #2645.
