### ISSUE TITLE
Weird Colon bug

### ISSUE THREAD

**Issue by NicoHood** [BoostIO/Boostnote#562]
Version 0.8.9 on Archlinux:

If you have a markdown file and write a colon `:` and then press CTRL it produces asterisks for ever CTRL Press. This means all shortcuts are messed up from them. And even more annoying CTRL+Z is not functional. 

Looks like this then:
```
********:********
```

**Comment by justin-calleja** [comment]
@NicoHood have you tried pulling from master? This issue should have been solved with: https://github.com/BoostIO/Boostnote/commit/efd80d5c0c1b0668b0747a549d12bbb6d6d937ad

Duplicate of: https://github.com/BoostIO/Boostnote/issues/540

**Comment by NicoHood** [comment]
@justin-calleja No I did not test, will test the next release then.

**Comment by kazup01** [comment]
Released on v0.8.10. Enjoy!

**Comment by NicoHood** [comment]
@kazup01 thanks, but now we still have https://github.com/BoostIO/Boostnote/issues/637 and #387  left.
