### ISSUE TITLE
Can't close Boostnote

### ISSUE THREAD

**Issue by Oylex** [BoostIO/Boostnote#565]
When i press the X at the top right, it minimizes the window instead of closing it. I know some apps do that, but usually they have an option to fix it, I can't find any.

I am using Windows 10 with the Creators Update installed if that matters.

**Comment by UltimateRandom** [comment]
Boostnote > exit
or Boostnote icon tray > Right Click > Quit

**Comment by Oylex** [comment]
so there's no way to make the close button close the program?

**Comment by asmsuechan** [comment]
Hi, @Oylex. It's one of the specifications. You can use `Ctrl - Q` to close Boostnote.

related: https://github.com/BoostIO/Boostnote/issues/559

**Comment by Oylex** [comment]
Alright, thanks

**Comment by leothelocust** [comment]
This really needs to be a configurable setting not a "specification".  I for one, do not like apps running in the background after I "close" the app.

Also, `Ctrl+q` does not work for me (Windows 10)
