### ISSUE TITLE
Notes scrollbar appears on top of menu modal

### ISSUE THREAD

**Issue by gabber12** [BoostIO/Boostnote#567]
If the notes listing scrollbar appears on top of menu modal if notes listing has enough notes to list.
Does it make sense to fix this? I would be happy to submit a PR for this.

![screenshot from 2017-05-12 23-26-15](https://cloud.githubusercontent.com/assets/1253456/26011641/8b942788-376f-11e7-98fa-ee94f6fd45b8.png)

**Comment by gabber12** [comment]
Fixed on master [commit](https://github.com/BoostIO/Boostnote/commit/549c289f81964f7b6938cdd0a108e2253c86d263), But the problem remains with Note(both with markdown and code) notes

**Comment by kazup01** [comment]
Thanks for your support! We will release it at next update!

**Comment by kazup01** [comment]
#569

**Comment by kazup01** [comment]
memo #569

**Comment by kazup01** [comment]
Fixed at current version. Thanks for reporting!
