### ISSUE TITLE
[Ubuntu Linux] Boostnote segfaults when closed

### ISSUE THREAD

**Issue by lakshayg** [BoostIO/Boostnote#57]
System: Ubuntu 16.04

Boostnote stops responding when the close button is clicked.

![screenshot from 2016-07-08 23-04-26](https://cloud.githubusercontent.com/assets/7976315/16695988/5d936922-4560-11e6-93a8-9033956bc5f5.png)

**Comment by Rokt33r** [comment]
It seems to be a error from electron. I'm currently inspecting.

**Comment by Rokt33r** [comment]
Do you still have this problem? 
I couldn't find any problem of this...More information is needed to deal with this problem.

If you do, please reopen this issue and please give me more information related this problem.
> Like process list, which can be printed by `ps -e|grep boost`

**Comment by lakshayg** [comment]
Yes, the problem is still the same. Here is the screenshot

![screenshot from 2016-08-03 12-24-26](https://cloud.githubusercontent.com/assets/7976315/17356477/53385cc0-5975-11e6-8fee-7732e404aa35.png)

Let me know if you need any information.

**Comment by Rokt33r** [comment]
1. Is the app still working after error occurs?
2. Could you tell me your desktop environment version?

**Comment by lakshayg** [comment]
1. No the app seems to freeze for a while and then exits when it is closed. When restarted, it seems to work fine till I click on the close button again.
2. I am using unity 7 on Ubuntu 16.04

**Comment by Rokt33r** [comment]
I'll install Ubuntu on this weekend to deal with this problem. Hang on a little more. 😢

**Comment by Rokt33r** [comment]
I fixed this problem on ubuntu. If this error pop again after updating v0.6.3, comment here. Then, I'll re-open this issue.

Anyway, v0.6.3 will be published Today. FIY, check #72.

**Comment by lakshayg** [comment]
v0.6.3 segfaults on closing. The problem is not yet solved.

**Comment by Rokt33r** [comment]
@lakshayg Thank you for reporting. I'll check it again.

**Comment by Rokt33r** [comment]
It seems to be due to the version of Electron. After I updated to v1.2.8, the error won't occur anymore.(Currently Boostnote using v1.1.3)
But, we have to keep watching. I'll inform you when I updating.

**Comment by Rokt33r** [comment]
@lakshayg v0.6.4 released. I confirmed it works well on Ubuntu now!

**Comment by lakshayg** [comment]
I have updated to v0.6.4 and it still has the same problem. Gives a segfault when closed.

**Comment by Rokt33r** [comment]
Hmm... It's too hard to deal with it... Okay, I'll check it again.

**Comment by jordanch** [comment]
@Rokt33r I was experiencing the same issue. Since upgrading to 0.6.4 it has only happened once.

`Linux #####-###### 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Rokt33r** [comment]
I think intercepting `close` event of Main window causes this problem. I'll fix it the next update(v0.6.7 or v0.7.0).

**Comment by Rokt33r** [comment]
I confirmed it has been fixed. Please check v0.6.7. If it still doesn't work, comment here.

**Comment by lakshayg** [comment]
It works .. Finally!
