### ISSUE TITLE
Feature request for soft wrapping the code

### ISSUE THREAD

**Issue by luong-komorebi** [BoostIO/Boostnote#570]
> A soft return or soft wrap is the break resulting from line wrap or word wrap (whether automatic or manual), whereas a hard return or hard wrap is an intentional break, creating a new paragraph. With a hard return, paragraph-break formatting can (and should) be applied (either indenting or vertical whitespace).  

Sometimes the code is long and I think this feature will make it easier for us to look into the code without scrolling too much. 
![image](https://cloud.githubusercontent.com/assets/15828926/26027539/dcd3ae14-3839-11e7-8e8d-00f88c07acbc.png)  

Also, if this was light theme for the code editor, you would be blocked by the scrollbar 
![image](https://cloud.githubusercontent.com/assets/15828926/26027552/1adc8438-383a-11e7-89cd-eb9620e2baef.png)

**Comment by neouyghur** [comment]
is it done yet? Thanks.

**Comment by VitalyKrenel** [comment]
Haven't found any issue on that, sorry me for asking here: Are there any existen option to wrap the text at the ruler? I use 80 chars ruler and it feels a little weird to be forced to wrap text manually when the lines are too long.

**Comment by flinz** [comment]
I would very much welcome this feature.

**Comment by amedora** [comment]
resolved by #3063.
