### ISSUE TITLE
[BUG] Link with multi line description is mis-rendered

### ISSUE THREAD

**Issue by Corea** [BoostIO/Boostnote#573]
# Environments
- MacBook Pro (Retina, 15-inch, Mid 2015)
- Mac OS Sierra 10.12.4(16E195)
- Boostnote 0.8.9
 
# Description
<img width="909" alt="2017-05-15 4 44 02" src="https://cloud.githubusercontent.com/assets/1433166/26047371/e5005e20-398d-11e7-867f-5743ab6171cb.png">

![image](https://cloud.githubusercontent.com/assets/1433166/26047368/dcfa6edc-398d-11e7-99f2-1a2597ccc0e1.png)

**Comment by kazup01** [comment]
Thanks for reporting!

**Comment by yamash723** [comment]
This bug has already been fixed.

PR #1429
