### ISSUE TITLE
[Feature Requests] Full text search in finder window

### ISSUE THREAD

**Issue by onlyice** [BoostIO/Boostnote#579]
Full text search is enabled in search bar of the main window but not in the finder window. It would be much more convenient if it's also enabled in finder window.

**Comment by kazup01** [comment]
Yes we should improve search feature. Please also check it #555 !

**Comment by evmin** [comment]
+1

**Comment by jamiecha** [comment]
Thanks for the great program ! 
I use it everyday. But as I put more notes, search function became more important.
Text search (highlighting) in the notes will be helpful much

**Comment by asmsuechan** [comment]
Hi, @jamiecha. Which context did you mention, Finder or Editor? If Editor, I added it already in https://github.com/BoostIO/Boostnote/pull/696 and will be released in a few weeks.

**Comment by jamiecha** [comment]
Hello, @asmsuechan. Thanks for the quick response. Sorry to make you misunderstood. What I meant was search in "Editor". I checked #696 and it's wonderful. Thanks for your effort.

**Comment by kazup01** [comment]
Hey guys, since we discard the Finder feature at v0.9.0 because this feature used very rarely, so I close this issue.
[v0.9.0 Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)

If you need, please feel free to talk to us. 
Thank you!
