### ISSUE TITLE
Search / Create notes from menubar menu

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#58]
Hello.

I recently found this application (https://www.renfei.org/snippets-lab/) and I really like their "SnippetsLab Assistant" which allows you to search and create new notes directly from the menu bar / tray menu.

[Example](https://www.renfei.org/snippets-lab/images/Landing/osx-1.4/assistant-preview.png)

Boostnote have finder which have similar features  but its not working in all OS and also some people might prefer to use the menu. 

I think it would be nice to have something similar in Boostnote.
There are many menubar examples built with Electron, so I think it wouldn't be too hard to implement.

Also maybe you can take some ideas from "Snippets Lab" about Gist integration.

**Comment by Rokt33r** [comment]
Thanks for suggesting. Let's make it for free to everyone!

**Comment by Rokt33r** [comment]
#85 It will be discussed from here!
