### ISSUE TITLE
Multiple asterisks appears when using ctrl+v in editor

### ISSUE THREAD

**Issue by Oylex** [BoostIO/Boostnote#580]
My version: Boostnote 0.8.9

Sometimes when I paste something in the markdown editor using the shortcut `ctrl+v` some stars (asterisks) appear. It doesn't do it all the time. Also I think they appear when I press just `ctrl`, but I only noticed it when pasting.

Let's say I want to paste: "http://www.google.com/", it will look something like:

*** ** *http://www.google.com/

**Comment by kazup01** [comment]
I can not reproduce it. Could you teach me your development environment?

**Comment by Oylex** [comment]
I found out how to reproduce it 100% of the time:

In any markdown note, type a word followed by a column `:` then press ctrl (or try to paste with the keyboard shortcut), it adds stars.

**Comment by kazup01** [comment]
This is default shortcut key! `ctrl :` = `**bold**`
Please check this list #533

**Comment by Oylex** [comment]
I understand, but I am not using the shortcut `ctrl + :`, I am writing the punctuation mark in the text and when I press ctrl after that is where it bugs.

**Comment by Oylex** [comment]
It feels like when you write a `:` it treats the next `ctrl` as `ctrl+:`

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix. Thanks!
