### ISSUE TITLE
[Mobile App] What is the progress so far of iOS/Android apps developing?

### ISSUE THREAD

**Issue by yanzhang0219** [BoostIO/Boostnote#581]
Hey dear developers,

I am so looking forward to this mobile end app especially for iOS. Everyday I spend very long time on commuting and it will be more convenient if I can go over the notes via my phone. So I'm just wondering whether there is an expected date for releasing the mobile app. Thank you so much and I really love Boostnote!!

**Comment by kazup01** [comment]
Thank you for your message!
Please wait a while. We are busy because also develop the Boostnote Team(https://boostnote.io/team/), but developing the mobile app at free time.
We are developing iOS/Android app using react native and we will make it open source.

**Comment by yanzhang0219** [comment]
Wow, I got it. Thank you.

**Comment by yanzhang0219** [comment]
Oh by the way, what is that slack group whose link is not available currently? Is that related to the discussion of Boostnote developing? Can I join it?

**Comment by kazup01** [comment]
Oops sorry, I will fix it soon!

**Comment by kazup01** [comment]
Fixed! You can join group [here](https://boostnote-group.slack.com/shared_invite/MTg0MzM5MTE3MzQ0LTE0OTUwOTQxMTItNDVkM2MzNmUxOQ)! @yanzhang0219

**Comment by yanzhang0219** [comment]
@kazup01 Many thanks. :)

**Comment by GaryFurash** [comment]
That will be great.

**Comment by kazup01** [comment]
Thanks for you guys waiting! We released Boostnote for iOS and Android and made to Open source!
https://github.com/BoostIO/Boostnote-mobile

Since we have implemented only MVP, we need you guys help.

**Comment by kazup01** [comment]
Thanks for you guys waiting! We released Boostnote for iOS and Android and made to Open source!

🎉🎉 https://github.com/BoostIO/Boostnote-mobile

Since we have implemented only MVP, we need you guys help.
- [Full text search](https://github.com/BoostIO/boostnote-mobile/issues/11)
- [Star the notes](https://github.com/BoostIO/boostnote-mobile/issues/10)
- [Image attachment](https://github.com/BoostIO/boostnote-mobile/issues/9)

**Comment by kazup01** [comment]
Thanks @yanzhang0219 !
