### ISSUE TITLE
[Feature Requests] Add "copy to clipboard" for code blocks

### ISSUE THREAD

**Issue by onlyice** [BoostIO/Boostnote#582]
DevDocs would display an "copy to clipboard" icon on the top right of a code block:

![image](https://cloud.githubusercontent.com/assets/1173899/26184129/91f6d6b2-3bb5-11e7-80c9-b2c46d316c9d.png)

I think this functionality is useful for Boostnote as well.

Also, AFAIK, the snippet notes is not so useful compare to Markdown note. When I write code snippets I always want to write some context (when to use, how to use, etc.). For example:

![image](https://cloud.githubusercontent.com/assets/1173899/26184226/2d7e27ca-3bb6-11e7-8368-209ee4b6dcdf.png)

**Comment by kazup01** [comment]
Ahhh this(copy-button on code block) is great idea! I'm so excited! 
I want to add this feature, but we can not develop it soon because we have other tasks.
If possible, could you develop it and send us a PR?

**Comment by onlyice** [comment]
I'll try, but I'm not familiar with Electron so it may takes a long time.

**Comment by kazup01** [comment]
No worries, thank you for your help!

**Comment by asmsuechan** [comment]
:+1: Good idea.

**Comment by kazup01** [comment]
Thank you for your suggestion @onlyice , and thank you for your cooperation @nadr0 !
Released on v0.8.10! This feature is so great. Enjoy👍
