### ISSUE TITLE
`$>` and `$<` codes doesn't work well in CodeBlock

### ISSUE THREAD

**Issue by ryochack** [BoostIO/Boostnote#585]
Hello, Boostnote team.

The following codes don't work well in CodeBlock.
- `$>`
- `$<`
- `<$>`

My environment is following.
- Mac OS El Capitan (10.11.6)
- Boostnote 0.8.9

### Code
	```
	$>
	```

### Expects
```
$>
```
### Boostnote preview
![case_$>_preview](https://cloud.githubusercontent.com/assets/356703/26192430/919594ec-3bec-11e7-9a67-30069f11b0e2.png)

### Code
	```
	$<
	```

### Expects
```
$<
```

### Boostnote preview
![case_$<_preview](https://cloud.githubusercontent.com/assets/356703/26192461/b4e8e2e6-3bec-11e7-9a14-38523d3a9ef3.png)

### Code
	```
	<$>
	```

### Expects
```
<$>
```

### Boostnote preview
![case_<$>_preview](https://cloud.githubusercontent.com/assets/356703/26192552/2486e04e-3bed-11e7-9f93-657be388f595.png)

# Screenshot of Boostnote
![Screenshot of Boostnote](https://cloud.githubusercontent.com/assets/356703/26193208/85386082-3bef-11e7-829e-9e95c577cbad.png)

**Comment by yashha** [comment]
Is it fixed? I can't reproduce it.

**Comment by ryochack** [comment]
Me too.
This problem is not reproduced on Boostnote 0.8.11.

**Comment by asmsuechan** [comment]
Presumably, I fixed it in https://github.com/BoostIO/Boostnote/pull/341.

**Comment by kazup01** [comment]
Thanks @ryochack for your reporting! Enjoy Boostnote!
