### ISSUE TITLE
Update README.md with Roadmap of planned features

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#588]
Would it be possible to maybe update the `README.md`  file with a Roadmap of planned future features.

I see the same feature request being posted over and over again as people don't realize a feature has already been requested. 

Many projects on GitHub that are under active development will do similar to show what features are planned for a future release so it is easy for everyone to see.  The README.md file is the most read part of the repo for new visitors who want to know what the app is.

Also its nice to see what is coming soon to the app!   I know there are 4-5 features in the Pull requests that I need ASAP in my Boostnote.  Hopefully these can be merged into the project soon?

---

## Example

This image shows a Roadmap from another project as an example.  Each item is linked to the issue that discusses the feature

![image](https://cloud.githubusercontent.com/assets/186818/26273554/47ad5828-3d00-11e7-9b4c-8dbdaa0f9fd8.png)

---

Just an idea

**Comment by kazup01** [comment]
This idea is good but I want to keep Readme simple, so I will consider it if necessary.
Thanks for your suggestion!

We merged some Pull requests yesterday. Check [here](https://github.com/BoostIO/Boostnote/issues?q=label%3A%22Next+Release%22+is%3Aclosed).
