### ISSUE TITLE
How to test Pull requests on Dev build of Boostnote

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#589]
This is more of a Git question.  I just cloned this repo so I can run the dev/build mode version of the app.

Is there a way I can import or test the pull requests from this repo on my local dev version of Boostnote to test new features?

**Comment by kazup01** [comment]
Tried `git pull` or pull from sourcetree? This is not git community. Check [git reference](https://git-scm.com/docs).

<img width="568" alt="screen shot 0029-05-21 at 11 56 18 am" src="https://cloud.githubusercontent.com/assets/8602615/26280798/895962a4-3e1c-11e7-83e6-8f2756d9a715.png">
