### ISSUE TITLE
Select code Syntax - Markdown option only

### ISSUE THREAD

**Issue by kabeza** [BoostIO/Boostnote#59]
I've downloaded latest Windows version and I'm only seeing "Markdown" option in the select code syntax menu. Is something wrong? Should I add other syntax separately?

![imagen_258](https://cloud.githubusercontent.com/assets/274856/16754068/87545a20-47c5-11e6-8dc6-f2a8270235fd.jpg)

**Comment by facundomedica** [comment]
You need to start writing the language in it. What you are seeing are the suggestions for what is written in the textbox.

**Comment by kabeza** [comment]
Sorry @facundomedica don't get it.
As you can see in the screenshot I've attached in my previous post, it is php code, but I don't see the PHP option in the syntax menu... 

Thanks

**Comment by facundomedica** [comment]
It is not a dropdown menu, it's a textbox with suggestions. Select the text "markdown" and start writing PHP.

**Comment by WinaZar** [comment]
Hm. I think you need to read about [markdown](http://daringfireball.net/projects/markdown/). You don't understand what is it. Also you can highlight your code using this:

\`\`\`php
<?
echo 'I am php snippet. Uh!'
?>
\`\`\`

It's look like:
```php
<?
echo 'I am php snippet. Uh!'
?>
```

**Comment by facundomedica** [comment]
@WinaZar I think he wants to use the PHP syntax in the entire note, so he has to follow what I wrote before.
<img width="198" alt="screen shot 2016-07-12 at 1 09 52 pm" src="https://cloud.githubusercontent.com/assets/14063057/16774352/fa1b8a44-4831-11e6-8104-6573e06e59c0.png">
<img width="181" alt="screen shot 2016-07-12 at 1 10 01 pm" src="https://cloud.githubusercontent.com/assets/14063057/16774354/fc058d14-4831-11e6-9957-d626f0d1b76e.png">
<img width="173" alt="screen shot 2016-07-12 at 1 10 09 pm" src="https://cloud.githubusercontent.com/assets/14063057/16774356/fe4a1996-4831-11e6-81ac-3b9e6e2e33c7.png">
<img width="189" alt="screen shot 2016-07-12 at 1 10 17 pm" src="https://cloud.githubusercontent.com/assets/14063057/16774359/ffd74090-4831-11e6-9ee2-d89df86cce9b.png">

**Comment by kabeza** [comment]
@WinaZar I know markdown, but no way I'm gonna convert a php snippet to markdown just to see it nicely in the Boostnote app. I think it is not the purpose of it.

@facundomedica didn't work the step by step. Even by creating a new note. I select markdown, type PHP, etc. then press enter, start typing the note, save, etc. but no luck. When I click another note and return to the newly created, the only option still is markdown.

Thanks anyway

**Comment by Rokt33r** [comment]
@kabeza I've checked it on Windows 10 just now. But, It works fine without any problem.
Could you give me a more information? If an error occurs, You can check it on devtool.
It can be opened by navigating menu, `View->Toggle Developer Tools`, or pressing `Ctrl + Shift + I`.

**Comment by kabeza** [comment]
@Rokt33r I'm posting 2 screenshots with Chromium debug tools enabled (console). Lemme know if I should help with anything else

![imagen_262](https://cloud.githubusercontent.com/assets/274856/16785900/0b773f10-4867-11e6-806f-79c1c1904249.jpg)

![imagen_263](https://cloud.githubusercontent.com/assets/274856/16785901/0b7cf658-4867-11e6-86bc-739d1eb37f50.jpg)

**Comment by Rokt33r** [comment]
@kabeza 
Sorry, It's a bug. I found the matching of syntax type is case-sensitive.
I'll fix it soon. Before It done, you can find it by `php` instead of `PHP`

**Comment by kabeza** [comment]
Yes! you're right @Rokt33r 
Tried with php and worked.

And about the full list of syntax... damn, that's a big list... maybe a comma separated list in readme would be enough I think

Thanks!

**Comment by Rokt33r** [comment]
I think making UI like below screenshot would be great.
I agree with the syntax is too huge... I'll fix it soon.

<img width="929" alt="screen shot 2016-07-26 at 7 42 34 pm" src="https://cloud.githubusercontent.com/assets/5865853/17135133/1f22faf6-5369-11e6-8ce9-a6744ee76d9c.png">
https://www.renfei.org/snippets-lab/

**Comment by kabeza** [comment]
Awesome @Rokt33r 
I also agree, looks much better, and usable

**Comment by Rokt33r** [comment]
Closed. You can track the progress on TodoList #68 
I'll add a comment when it implemented!
