### ISSUE TITLE
Feature Request - Add Embed.js Library to Boostnote Markdown HTML Output

### ISSUE THREAD

**Issue by jasondavis** [BoostIO/Boostnote#590]
I found this amazing Embed.js Library that lets you embed tons of things just by including the JS library and configuring it.  In the config you can define which ones you want and dont want so you dont have to use all of the conversions either!

It would be a great addition to the Markdown files in Boostnote...

---

# embed.js LIbrary

A JavaScript plugin that embeds emojis, media, maps, tweets, gists, code, services and markdown.

## Text converts and embeds these formats:

- **Emoji & Font icons**
- **Twitter**
- **Github Gists**
- **Video Sharing Services**
  - YOUTUBE
  - VIMEO
  - VINE
  - USTREAM
  - DAILYMOTION
  - LIVELEAK
- **Audio and Video Files** 
  - Audi files with extension wav|mp3|ogg
  - video files with extension ogv|webm|mp4 are supported
- **Online Code Editors**
  - CODEPEN
  - JSFIDDLE
  - JSBIN
  - IDEONE 
  - PLUNKER
- **Code Highlighting** - syntax highlighting using the code's markdown syntax
- **Video Details** - The preview of videos with video description 
  - YOUTUBE videos
  - VIMEO videos
- **Music sharing**
  - SPOTIFY
  - SOUNDCLOUD
- **Photo Sharing**
  - FLICKR 
  - INSTAGRAM
- **Google Map**
- **Markdown** - This plugin supports markdown parsing using the power of marked.js
- **URL** - converts urls into HTML anchor tags
- **Images** - Image files with extensions gif|jpg|jpeg|tiff|png|svg|webp are automatically embedded

---

Project Site - http://riteshkr.com/embed.js/
Examples - https://embedjs.readme.io/docs/basic-example
GitHub Repo - https://github.com/ritz078/embed.js

![image](https://cloud.githubusercontent.com/assets/186818/26273764/4173c690-3d05-11e7-8419-8744768cd9ba.png)

**Comment by jasondavis** [comment]
@kazup01 What do you think of this?

**Comment by kazup01** [comment]
I think that it is a good idea, but I implemented html output in the old version, but nobody used it, so I want to hear feedback from others.

**Comment by illia1** [comment]
Looks cool!

**Comment by huettenhain** [comment]
It *does* look cool.

However, I am always worried about bloat. A note taking application should never feel sluggish because of too much bells and whistles. Also, to me this is all very low priority compared to #176. Embedding videos and google maps makes for a nice demo, but if you really use boostnote every day, you want to be able to search and replace text much more.

**Comment by chuoke** [comment]
That's every good! 
 I need the feature, html output, which is a base feature I think, nobody used it just because not many people used Boostnote, but now on the contrary.

**Comment by kazup01** [comment]
Hi guys, @xbotao made [Boost2html](https://github.com/xbotao/Boost2html). 
This is convert tool that Boostnote snippets to web pages and push it to git automatically.
Please check it!

ref: #507
