### ISSUE TITLE
Use Command + Backspace to delete on mac

### ISSUE THREAD

**Issue by zachary822** [BoostIO/Boostnote#592]
Use the Command + Backspace to delete notes on mac to be more consistent with system.

**Comment by asmsuechan** [comment]
Hi, @zachary822. How about `Ctrl-delete`? Are you unhappy to use this shortcut?

**Comment by zachary822** [comment]
The shortcut is fine, just a suggestion. I instinctively use Command + Backspace (Delete) when deleting things. Which is consistent with Finder and other apps.

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix.
