### ISSUE TITLE
Resize an image with markdown

### ISSUE THREAD

**Issue by darkomen** [BoostIO/Boostnote#595]
Hí!
I'm trying to put an image in oe note, but when I have tried to change the size with the follow code it doesn't work.
`![Alternate text](path/to/image =150x50)`
How I could to change the size of an image?

**Comment by kazup01** [comment]
Hi @darkomen san!
It can not do it at current version, but I also want it. If possible, could you develop it and send us a Pull request?

**Comment by darkomen** [comment]
I haven't programmed in JavaScript 😓 But I will try to do the implementation. If I get something I'll make a pull request

**Comment by kazup01** [comment]
Thank you for your suggestion @darkomen , and thank you for your cooperation @dangvanthanh !
Released on v0.8.10! Enjoy 🙌
