### ISSUE TITLE
The App Keeps Running

### ISSUE THREAD

**Issue by AbT10** [BoostIO/Boostnote#596]
When i open it once and then try to close it, it keeps running, i even tried right clicking it and closing, but still it won't close. It only minimises and keeps running in the background.
The only way to close it is to use the exit option from the BootNote option in the nav bar.

**Comment by kazup01** [comment]
Hi, @AbT10, it's one of the specifications. You can use Ctrl - Q to close Boostnote. #559

**Comment by AbT10** [comment]
If that's the case then it's allright, but i think if there's no use of the frame's closing button, maybe the app should run in fullscreen mode with the frame hidden... Just a thought.
