### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#6]
- `Press ESC to watch the preview` message hampers editting the bottom line of editor screen

**Comment by gromain** [comment]
Also, regarding the selection, when the number of lines is higher than the height of the screen, and the editor is completely at the bottom, selecting in the editor leads to the page scrolling up (and selecting all the text in between).

**Comment by gromain** [comment]
Boostnote doesn't close (on Linux). It stays in the background when closed, and cannot be restarted without killing the process.

**Comment by Rokt33r** [comment]
@gromain Thanks, I'll check it.

**Comment by the-c0d3r** [comment]
I have a similar problem like that. When I place the cursor somewhere by clicking, it selects a whole bunch of lines above it automatically. And the message `Press ESC to watch the preview` is covering up the text when I'm writing on the bottom line. The temporary solution I did was to create empty lines under the last line, so the line I'm currently writing is not covered by that message.

**Comment by Rokt33r** [comment]
@the-c0d3r  Thanks for your reporting! I'm currently fixing that problem.

**Comment by Rokt33r** [comment]
@the-c0d3r @gromain
I fixed the bug about selection. I'll release the fixed build on tomorrow!
I really appreciate your help. 

> `Press ESC to watch the preview` is covering up ...
I'm currently thinking how should I solve that problem. Please wait a little.

> Boostnote doesn't close properly on Linux.
I'm currently checking now. It might be fixed it tomorrow.

**Comment by Rokt33r** [comment]
@gromain 
> Boostnote doesn't close properly on Linux. 
I checked it and it was intended feature. It hides by default when click close button on window. This is because, app should remain for search window and quick write popup(coming on v0.6.*).
Actually it can be easily close completely on Windows and OSX by pressing Cmd/Ctrl + Q.
but on Linux, it doesn't seem to work. (I checked it on Xfce Ubuntu and I'll do it again on Unity)

Btw, Could you tell me which desktop environment you are using?
I'll check the behaviour of it and fix it better!

**Comment by Rokt33r** [comment]
@gromain I think we should talk about it on #5 
Btw, I checked it on Unity, and Unity also doesn't work well.

**Comment by Rokt33r** [comment]
@gromain 
I changed my mind. It seems to be impossible to implement Finder window and Tray icon now.
And, I know it is not so important features of Boostnote. These features will be removed on Linux for awhile.
So, I'll make Boostnote quit properly when main window closed. :)
Please wait for a couple of day to publish it!

Btw, could you teach me how I can publish Boostnote as a AUR package?

**Comment by gromain** [comment]
@Rokt33r I'm using Cinnamon (welcome to the linux diversity! ;) ).

For the AUR, the first step is to write a PKGBUILD. It's basically a file that describe the installation in a script (all the steps you would have to type into a command line for the installation). Some more information here: https://wiki.archlinux.org/index.php/PKGBUILD

Also, read the wiki page on the AUR: https://wiki.archlinux.org/index.php/Arch_User_Repository
It describe all the steps needed for getting a package into AUR.

**Comment by Rokt33r** [comment]
@gromain Thanks a lot! I'll check them also! 💃

**Comment by gromain** [comment]
A good example (starting from the .deb file here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitmeter-os

**Comment by gromain** [comment]
Example PKGBUILD for Boostnote:
```
# Maintainer: Rokt33r <email@rokteer.com>
# Contributor: Romain Bazile <gromain.baz@gmail.com>
pkgname=boost
pkgver=0.5.8
pkgrel=1
pkgdesc="Opensource note app for developer"
arch=('x86_64')
url="https://b00st.io/"
license=('GPL')
groups=()
depends=()
makedepends=()
checkdepends=()
optdepends=()
provides=()
conflicts=()
replaces=()
backup=()
options=()
install=
changelog=

source=(
  "https://github.com/BoostIO/boost-releases/releases/download/v0.5.8/boost_0.5.8_amd64.deb"
)

noextract=()

md5sums=('df56bf3167dddb3eb2e1b263c65e61ba')

validpgpkeys=()

package() {
  tar -xa -f ${srcdir}/data.tar.xz
  cp -r "${srcdir}/usr" "${pkgdir}/usr"
}
```
I believe it works (at least for me, makepkg throw me no errors), I'll try installing the package later on, I'm in a business meeting! ;)

**Comment by gromain** [comment]
For the record, boost is standard c library.

**Comment by gromain** [comment]
And a better source line: `source=( "https://github.com/BoostIO/boost-releases/releases/download/v$pkgver/boost_$pkgver_amd64.deb" )`

**Comment by gromain** [comment]
Ok, here is a final clean version. I integrated the specific x86_64 calls, to make it cleaner.
```
# Maintainer: Rokt33r <email@rokteer.com>
# Contributor: Romain Bazile <gromain.baz@gmail.com>
pkgname=boostnote
pkgver=0.5.8
pkgrel=1
pkgdesc="Opensource note app for developer"
arch=('x86_64')
url="https://b00st.io/"
license=('GPL')
groups=()
depends=()
makedepends=()
checkdepends=()
optdepends=()
provides=()
conflicts=()
replaces=()
backup=()
options=()
install=
changelog=

source_x86_64=( "https://github.com/BoostIO/boost-releases/releases/download/v$pkgver/boost_$pkgver_amd64.deb" )

noextract=()

md5sums_x86_64=('df56bf3167dddb3eb2e1b263c65e61ba')

validpgpkeys=()

package() {
  tar -xa -f ${srcdir}/data.tar.xz
  cp -r "${srcdir}/usr" "${pkgdir}/usr"
}
```

**Comment by Rokt33r** [comment]
@gromain As I wrote in #5, I'm going to publish Boostnote on UAR/PPA within this weekend. 

I've fixed the problem 'app doesn't quit properly'. You can check it on `master` branch.

I really appreciate your help. 👍

**Comment by gromain** [comment]
This PKGBUILD works on my machine, and the installation is successful.
I believe the name of the executable will have to be changed/harmonised, as there already is a package named boost (as I said earlier), and it usually is good practice to have the name of the package be the same as the name of the binary (and here we have a package named `boostnote` and a binary named `boost` )

**Comment by Rokt33r** [comment]
Closed. The bug above won't bother anymore from v0.6.0
