### ISSUE TITLE
v0.6.2 plan(planned to be released on 7/28)

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#60]
It will be released on 7/28(This is early treatment. Due to the problem of editing performance.)

- [x] Improve performance
  - [x] debounce dispatch (It works well!)*
  - [ ] ~~use Map instead of pure array~~(Postponed)
- [x] Footnote
- [x] GFM style checkbox*
- [ ] ~~Finder~~(Postponed: I'll ship it on this weeekend)
- [x] Add tooltips to buttons

## Debounce dispatch

on v0.6.0-0.6.1, Code Editor dispatches every time the content changing. It makes editor critically slow.
So, I make it to dispatch after 1 second from last changes. And, It works well. Editing performance recovered just as v0.5. Sorry for making you inconvinent.

## GFM style checkbox

First, Clicking rendered checkbox from preview will applied to the note content.

Second, The current plugin, `markdown-it-checkbox`, isn't compatible with GFM checkbox. So, I'll rewrite it to compatible with GFM.

### Example

Markdown code
```
- [x] this should be rendered checkbox on GFM

[x] this shouldn't be rendered.
```
---

Rendered(Github)
- [x] this should be rendered checkbox on GFM

[x] this shouldn't be rendered.

----

Rendered(current app, v0.6.1)
<img width="293" alt="screen shot 2016-07-26 at 7 35 57 pm" src="https://cloud.githubusercontent.com/assets/5865853/17134969/35fc7492-5368-11e6-9bc2-cb5b0b3af6c1.png">

**Comment by askg7dawn** [comment]
Hi.
Please add the following functions in future if you agree with me.

1. allow users to change the toggle finder hotkey
2. enable to select the target storage to find (when using finder, i'm happy if only snippets are shown up)


and one more question... though it's not suit to write down here...
in my version (v0.6.1), i can't use `toggle finder hotkey`. when i push `cmd + alt + S`, nothing happens. Do you have any ideas about this issue?

thank you.

**Comment by Rokt33r** [comment]
@askg7dawn 
Sorry, Finder has been disabled temporary. 
I have to redesign it because the note format has been changed.

> when using finder, i'm happy if only snippets are shown up
As your wish, The new Finder will be designed to search snippet note mainly. :)

**Comment by askg7dawn** [comment]
@Rokt33r 
Thank you for your reply.
i'm very excited to hear that improvement.
i'm looking forward to the next update!

**Comment by Rokt33r** [comment]
@askg7dawn 
FIY
Check this issue. https://github.com/BoostIO/Boostnote/issues/58

**Comment by Rokt33r** [comment]
Released.
