### ISSUE TITLE
vim shortcuts

### ISSUE THREAD

**Issue by eleijonmarck** [BoostIO/Boostnote#601]
I would love to have shortcuts for vim

[] / - search notes
[x] ctrl + j - go up (already exists)
[] ctrl + k - go down

TODO:
add more shortcuts for vim like feeling

**Comment by asmsuechan** [comment]
Hi, @eleijonmarck. Did you try this? https://www.youtube.com/watch?v=nfLggQ7-H9E

But `/` function is not implemented yet.

**Comment by IzumiSy** [comment]
Generally in vim, `Ctrl + J` is a command to make a new line. This must be followed as an editor. Only in normal mode, `Ctrl + J` is better to be the shortcut to go to the next note as it is.

**Comment by IzumiSy** [comment]
My new suggestion for keybindings in this topics is:

| Bindings | Default (or normal mode in Vim) | Vim (in insert mode) | 
|:---------:|:----------------:|:----------------:|
| `Ctrl + J` | going down in note list | new line |
| `Ctrl + K` | going up in note list | `N/A` |
| `Ctrl + U` | `N/A` | `N/A` |

 The biggest reason to use `J` and `K` as key bindings to going up and down is, that's a kind of UNIX-like tools keybindngs like git and tig.

**Comment by asmsuechan** [comment]
`Ctrl-J` and `Ctrl-K` are not implemented in CodeMirror (https://github.com/codemirror/CodeMirror/blob/32d9b61633cf758c6e186a4bb5e37660b41d87d4/keymap/vim.js) so it's CodeMirror's issue rather than our issue.

**Comment by IzumiSy** [comment]
> Ctrl-J is not implemented in CodeMirror 

Oh got this point.

**Comment by bimlas** [comment]
It seems implemented, issue may be closed.
