### ISSUE TITLE
[Feature Request] Todo List

### ISSUE THREAD

**Issue by mathewmeconry** [BoostIO/Boostnote#606]
It would be nice to have a new type of notes called list that it would be possible to build a todo list.
It would be also great that it would hide finished entries.
Here is a mockup how it could look like:
![image](https://cloud.githubusercontent.com/assets/4057473/26633731/a3ece3de-4614-11e7-8946-cc6215ba81f6.png)

**Comment by kazup01** [comment]
Hi @mathewmeconry , thank you for your suggestion!
Could you explain in more detail? I could not understand it.
BTW, we will add task progress bar like below image at next update.

![task](https://cloud.githubusercontent.com/assets/8602615/26790434/a6d68fda-4a4e-11e7-9ed7-554618b43766.gif)

**Comment by mathewmeconry** [comment]
Great this is what I meant.
An autohide functionality of finished tasks would be great too :)

**Comment by kazup01** [comment]
Thank you for your suggestion @mathewmeconry ! 
Released on v0.8.10! Enjoy👍

**Comment by the4ndy** [comment]
i tried using the ``` - [] ``` style check lists (as github uses) but am unable to make a todo style list. Have the changes and features in the animated gif above made it into the application? If so, where can i find documentation that will explain to me which convention Boostnote uses for making check lists.

**Comment by dreuter** [comment]
Hi there :)

I was wondering the same thing and it seems to be important to add a space between the brackets.

So if you type `-  [ ]` it will work.

```
- [ ] this works
- [] this does not
```

- [ ] this works
- [] this does not

Since this is the first entry on google when you search for "Todolist boostnote" I figured it would be useful to document this :)
