### ISSUE TITLE
HTML Input got rendered in note

### ISSUE THREAD

**Issue by LewisVo** [BoostIO/Boostnote#613]
I am on Ubuntu 16.04.2, Boostnote latest version 0.8.9.

When I type a html input form in the note, it got rendered like this :   
![image](https://cloud.githubusercontent.com/assets/15828926/26759330/feaada2a-4924-11e7-9515-707ec58b4535.png)  
Clicking on that "choose file" button even takes you to real file choosing:
![image](https://cloud.githubusercontent.com/assets/15828926/26759335/12b2de28-4925-11e7-9b0f-c444b392ed80.png)  

Also, this is not intentional. The source of the note is an answer from [StackOverFlow](https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean) . I copied and accidentally found out the bug when I pasted it into Boostnote.

**Comment by asmsuechan** [comment]
Hi, @tlvt! The behavior is not correct. I assume GitHub's specification is our ideal style.
![2abec29d97a551733d00d7fcf90f8ece](https://cloud.githubusercontent.com/assets/11307908/26759416/098d8286-4938-11e7-8c09-3e23a8c9065e.gif)

For now, you can use a code block (```) to solve this issue.
