### ISSUE TITLE
[Bug] Weird cursor behaviour

### ISSUE THREAD

**Issue by luong-komorebi** [BoostIO/Boostnote#616]
I am on Ubuntu 16.04.2, latest version of Boostnote 0.8.9.  
The backtick ( ` ) didn't show up at the cursor position. The problem is so weird that I don't know how to search it in the issue of the repo. Maybe this GIF will help you understand the thing I encounter :  
  
![](https://media.giphy.com/media/l0Iyh6BWDCwTMNJIc/giphy.gif)

**Comment by nagledb** [comment]
I just tested with 0.11.10 and could not reproduce. Maybe it got fixed somewhere along the way?

**Comment by ZeroX-DG** [comment]
Feel free to re-open the issue if it still exists.
