### ISSUE TITLE
Finder not working

### ISSUE THREAD

**Issue by facundomedica** [BoostIO/Boostnote#62]
The finder stopped working on the new version. (Command + Alt + S) on Mac running OS X El Capitan.

**Comment by Rokt33r** [comment]
@facundomedica It is disabled temporary!
Check the comment in #60.
btw, I'll close this issue when I reimplement it.

**Comment by Rokt33r** [comment]
And, I'm terribly sorry... I've just relized there are many people using it than I thought.

**Comment by facundomedica** [comment]
@Rokt33r sorry, didn't read!

**Comment by Rokt33r** [comment]
Done! #72
