### ISSUE TITLE
About data analytics

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#621]
ref: #119

From v0.9.0, we start gathering usage data of Boostnote by Amazon Mobile Analytics.

## Why?
We can not check the data of Boostnote because Mixpanel has exceeded the free plan.
Therefore, we replace Mixpanel with Amazon Mobile Analytics.
We need some data, because these are important for us to improve Boostnote.

<br>

## Current status and future plan
We **WON'T** collect any PRIVATE data. (e.g. content of notes)
Needless to say, we **WON'T** collect data that other than Boostnote.

<Br>

---

If you have any question about data analytics, please feel free to comment here.

**Comment by minddust** [comment]
how about an opt-out option?
