### ISSUE TITLE
'Export As' works only for .md note?

### ISSUE THREAD

**Issue by psy901** [BoostIO/Boostnote#625]
'Export As' feature only works for .md note, and it does not display anything when the current note is 'code snippet' note.

It makes sense but it can be improved I think.

Thanks!

**Comment by asmsuechan** [comment]
Hi, @psy901. That's a bug. The regular behavior is to show a dialog when you try to export a snippet but nothing happens now. So I fixed to show a dialog.

refs: https://github.com/BoostIO/Boostnote/pull/626

**Comment by kazup01** [comment]
Thank you for your reporting @psy901 ! Released on v0.8.10! Enjoy👍
