### ISSUE TITLE
"_" char missed in names column

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#627]
MD note is
```
on_hint(self, ed_self, x, y) -> None, True
hint_proc()

HINT_GET_SIZE(x,y) -> x,y
HINT_CREATE(x, y) -> id_bitmap, id_canvas
HINT_SHOW(x, y, id_bitmap)
```

Bug: for this note, name of item in left column is w/o _ char-
"onhint(self..."

**Comment by asmsuechan** [comment]
Hi, @Alexey-T! Actually, I've found how to fix it already. Chances are it will be fixed in the next version :dancer:

**Comment by kazup01** [comment]
Released on v0.8.10! Enjoy!

**Comment by Alexey-T** [comment]
It is still the same in 0.8.10: no _ in titles.

**Comment by kazup01** [comment]
Oops this is still under work in progress. Thank you for your info @Alexey-T .

**Comment by Flexo013** [comment]
This feature has been released in Dec 2017.
