### ISSUE TITLE
Cannot import Boostnote folder

### ISSUE THREAD

**Issue by LewisVo** [BoostIO/Boostnote#629]
I recently moved to another computer. I installed Boostnote right after everything else was set, then link the folder containing all my notes that I sync from my previous computer. 
However that didn't work. 
I don't know if I am missing anything here.  Found #229 but the discription was to vague and there was no solution to that as it is closed now. 
![](https://thumbs.gfycat.com/LividFlawlessCatbird-size_restricted.gif) 
video : https://gfycat.com/LividFlawlessCatbird

**Comment by kazup01** [comment]
Hi @LewisVo! Could you teach me your development environment?
Have you refreshed Boostnote after importing folder?

**Comment by LewisVo** [comment]
@kazup01  
Environment : Ubuntu 16.04.2 (Xubuntu to be exact) 
I did try both restart the application and refresh Boostnote with `Ctrl + R`

**Comment by kazup01** [comment]
Thank @LewisVo for your info. Sorry for inconvenient. I will investigate this cause!

**Comment by LewisVo** [comment]
I just reinstalled boostnote. Luckily this thing showed up (I didn't see it at first installation) and problem is solved. Feel free to close this issue, but please look into the add storage functionality. There should be some minor problems there 
![](http://i.imgur.com/PensuxZ.png)

**Comment by kazup01** [comment]
That's great! 
Ok, we will improve this function. Thanks for your cooperation!
