### ISSUE TITLE
Markdown syntax is not previewable in Snippets

### ISSUE THREAD

**Issue by pcampbell-software** [BoostIO/Boostnote#63]
If you create a snippet and tag it as Markdown, there appears to be no way to have it render the preview. You can therefore only ever see the markdown syntax and not the rendered output. 

I'm not sure if this is intentional or not; I guess if it is supposed to be this way, you probably shouldn't be able to pick it as a syntax type.

**Comment by Rokt33r** [comment]
It was intended because I thought the snippet note is just for snippet.
But, I also think rendering markdown doesn't seem to suck.

I'll inform you later after I decided.

**Comment by Rokt33r** [comment]
Decided: Markdown snippet will be rendered!

**Comment by Rokt33r** [comment]
It will be shipped on v0.6.3. #72
