### ISSUE TITLE
HTML tags vanish in CodeBlock

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#630]
When you enter 
````
```html
<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>This is a website.</body>
</html>
```
````
Boostnote will render it as follows:
```html
 
 
<head><title>Test</title></head>
<body>This is a website.</body>
 
```
I.e. some of the tags are not displayed.

**Comment by kazup01** [comment]
Could you teach me your development environment?
In my environment render correctly.
macOS Sierra v10.12.3
Boostnote v0.8.9

![jun-12-0029 12-54-46](https://user-images.githubusercontent.com/8602615/27018822-573268a8-4f6e-11e7-96cb-a38d00a0fb81.gif)

**Comment by huettenhain** [comment]
Oh, how odd. It appears that Boostnote did not update on this machine, it still runs 0.8.8. Upgrading manually fixed it. I am sorry.
