### ISSUE TITLE
Relative path on images

### ISSUE THREAD

**Issue by k4ch0** [BoostIO/Boostnote#638]
Hi team, 

I'm trying to use relative paths on the images, but seems like it is not working:
```
![My image description][1]

[1]: ..\images\image.png
```

It only shows me a broken icon.

Thank you in advance

**Comment by asmsuechan** [comment]
Hi, @k4ch0. It's a bit trouble so you should use an absolute path.
I recommend you to use drag&drop an image.

**Comment by k4ch0** [comment]
Hi @asmsuechan, thanks for the feedback!

Right now I'm using Boostnote on Linux and Windows (Synchronizing with Dropbox), that is why I'm asking for relative paths.

Thanks

**Comment by evmin** [comment]
+1 Relative path is a must for the network synced notes.
Please consider along with pasting images.

**Comment by yashha** [comment]
Maybe when pasting an image folder is being created or an image is being appended to the cson file?

**Comment by kazup01** [comment]
How about this? #730

**Comment by yashha** [comment]
Looks good.
I think this can be closed @asmsuechan

**Comment by kazup01** [comment]
Enjoy :)
