### ISSUE TITLE
Search text

### ISSUE THREAD

**Issue by vilmes21** [BoostIO/Boostnote#641]
If I can use `control + f` or `command + f` to search partial texts just like in most other editors, Boostnote would be a total dream.

**Comment by kazup01** [comment]
Yes, I also think as you said.
@asmsuechan will develop it at sometime soon!

**Comment by huettenhain** [comment]
This is  #176, and I stress again that Boostnote **already had that feature** when it used the Ace editor rather than Codemirror.

**Comment by vilmes21** [comment]
So @huettenhain , you meant it once had it, but no longer does now. Correct? I have Boostnote on Windows and Mac, neither has search text function. The search they do have right now is simply `searching for a note file`, but we really want `searching for words within the content of one given note file`.

**Comment by huettenhain** [comment]
@vilmes21, check out the [live demo of the Ace editor](https://ace.c9.io/). This component was used as the editor in earlier boostnote versions. Press `Ctrl`+`F` or `Ctrl`+`H` in the demo, then you will see that there is a search/replace feature there. Check #76, it was said there that Ace would be replaced with Codemirror. I think we should simply switch back.

**Comment by kazup01** [comment]
@asmsuechan is made it at #686. We will release it at next version!

**Comment by vilmes21** [comment]
I saw this new feature on MacOs, awesome job! However, on my Windows machine, there's no such feature yet. By the way, where should I report some bugs for the newest release? I'm no longer able to save my UI preference settings once I quit the program. In fact, it's even hard to save my UI preferences when I collapse the left-hand sidebar.

**Comment by asmsuechan** [comment]
Hi, @vilmes21. 

Umm, when I checked it on windows, it worked. So I'll investigate it.

> UI preference settings once I quit the program.

Sorry for inconvenient. It's a bug. And we'll release a fix version in a few hours. Until then, please put `~/.boostnoterc`.
https://github.com/BoostIO/Boostnote/issues/788

**Comment by joeypedicini92** [comment]
Is this currently released? It's not working for me (I'm on mac desktop version)
