### ISSUE TITLE
Can't copy text in Vim binding mode

### ISSUE THREAD

**Issue by IzumiSy** [BoostIO/Boostnote#646]
I can't copy any texts in Vim mode, because `Ctrl + C` is used in Vim binding to change edit mode. However, yank also does not share its data with system clipboard, so I cannot copy any texts and paste it outside of Boostnote. Any idea to solve this issue?

**Comment by IzumiSy** [comment]
In my case, always when I want to copy texts on Boostnote, I change keybindings from Vim to default. This is too bothering, but no way out.

**Comment by kazup01** [comment]
This is a good point. I'm not using Vim mode, but I want to improve it.

Just idea:
1, Allow right click and make copy / paste possible.
2, Allow key setting for copy / paste.

---

BTW, how about Finder or Copy at codeblock?

- Finder
![finder](https://user-images.githubusercontent.com/8602615/27253410-1907d492-53af-11e7-8873-ba7914cb0e6e.gif)

- Copy at codeblock
![copy](https://user-images.githubusercontent.com/8602615/27253412-2b2b6be8-53af-11e7-8058-a6f85b4eb8dc.gif)

**Comment by kazup01** [comment]
Hi @IzumiSy ,
This is a good point. I'm not using Vim mode, but I want to improve it.

Just idea:
1, Allow right click and make copy / paste possible.
2, Allow key setting for copy / paste.

---

BTW, how about Finder or Copy at codeblock?

- Finder
![finder](https://user-images.githubusercontent.com/8602615/27253410-1907d492-53af-11e7-8873-ba7914cb0e6e.gif)

- Copy at codeblock
![copy](https://user-images.githubusercontent.com/8602615/27253412-2b2b6be8-53af-11e7-8058-a6f85b4eb8dc.gif)

**Comment by IzumiSy** [comment]
Thanks for replying.

> 1. Allow right click in editor and make copy / paste possible
> 2. Allow key setting for copy / paste.

Cool if one of those two is possible, but how do I achieve that from settings? (Or would it be a future implmentation? nice too!)

> how about Finder

My machine is Ubuntu 16.04 with Unity. I am not sure if my environment affects in some bad ways or not, but I can't open Finder. This pic is my hotkey preference which does not work. Is this a bug?

![selection_027](https://user-images.githubusercontent.com/982850/27253648-70eae376-53b3-11e7-8514-a502b59b899d.png)

For further information, it looks I am getting no error.

![selection_026](https://user-images.githubusercontent.com/982850/27253673-a6e22390-53b3-11e7-9da9-68ba9e3f63c6.png)

> Copy at codeblock

This is working nicely! but what almost always I want to do is to copy a whole text, of course not actually always though.

**Comment by asmsuechan** [comment]
The solutions I hit upon are below:

1. Delete `Ctrl-C` from vim keybindings and alter it to copy
2. Change as to copy into clipboard on yank
3. Implement customizable keybindings

You know, No.3 is the best. But it's also another issue and takes much time.

**Comment by IzumiSy** [comment]
> 1. Delete Ctrl-C from vim keybindings and alter it to copy

This might not be a good choice, because I am the heavy user of `Ctrl + C` in Vim to exit insert mode. I really don't want to take this out.

> 2. Change as to copy into clipboard on yank.

This is exactly what I myself want to have in Boostnote. The best one.

**Comment by asmsuechan** [comment]
How about this?
https://github.com/asmsuechan/Boostnote/pull/6

**Comment by IzumiSy** [comment]
I cloned your fork and tested the branch. It was really a great one. Thank you for a quick catch :pray:

**Comment by kazup01** [comment]
Merged!

**Comment by kazup01** [comment]
Released at v0.8.11!

**Comment by narc0tiq** [comment]
Er... isn't "The Vim Way™" to yank/put from the `*` register? I definitely do `"*d` when I want to delete to system clipboard, and `"*p` when I want to put from the system clipboard. I was very confused when yanking from boostnote in Vim mode didn't allow me to put what I expected into my GVim session.

Looks like https://github.com/codemirror/CodeMirror/issues/3293 is relevant in some way, though the specifics elude me. It probably isn't a simple change, but it would definitely be more correct.
