### ISSUE TITLE
How to add images to notes?

### ISSUE THREAD

**Issue by vvs** [BoostIO/Boostnote#651]
Sorry for the stupid question, but how do I add images to Boostnote so that they could be embedded into notes?

I see that some drag'n'drop of images into the app is suggested (and implemented?), but it doesn't work for me. When I drag a JPG image into BoostNote, nothing happens.

I am using **Boostnote 0.8.10**

**Comment by kazup01** [comment]
No problem, thank you for your message @vvs !
My suggestion is to write markdown like this. 
`![Image](https://www.rover.com/blog/wp-content/uploads/2015/05/dog-candy-junk-food-599x340.jpg)`

Since drag a image into Boostnote seems broken, we will investigate it!

**Comment by vvs** [comment]
Here's what I figured so far. If the note is not locked, as soon as I pick up any image in the Windows Explorer, the Boostnote goes out of focus, and the currently edited note gets into "view mode". Dragging the image into this note does nothing.

If I lock the edit mode, then dragging the image does work in a sense that the image is copied into my storage's images files, and some text is appended to the note. But the image is still not visible.

Here's what is being appended:

```
![Anomalies.png](P:%5CMy%20Docs%5CBoostNotes/images/Anomalies.png)
```

Please note that my storage location is: `P:\My Docs\BoostNotes`

**Comment by kazup01** [comment]
You're right. It is probably a bug that image is not displayed in markdown preview, so we will investigate this.

<img width="439" alt="screen shot 0029-06-20 at 8 11 51 pm" src="https://user-images.githubusercontent.com/8602615/27330662-66c375e0-55f5-11e7-8088-43e165ad6029.png">

**Comment by vvs** [comment]
It looks like the URL inserted is wrong. If I replace '%5C' with slash, then the image is OK. :)

But what I really wanted is a local, relative path, relative to the 'STORAGE/images'. So, in my case, the ideal case would be:

```
![Anomalies.png](Anomalies.png)
```

**Comment by k4ch0** [comment]
Adding more feedback on this, it should be a good feature support relative path as @vvs just comment!
Also, it is part of [issue 638.](https://github.com/BoostIO/Boostnote/issues/638)

Thanks!

**Comment by kazup01** [comment]
Hi guys, @asmsuechan is fixed this bug at #667.
We will release it at next release!

**Comment by kirtan403** [comment]
It should also store images somewhere in the storage also. Syncing with google drive and dropbox will need this.

**Comment by kazup01** [comment]
refs: #710

**Comment by Alaev** [comment]
At the moment boostnote doesn't create an image folder when you drop an image into the app
is that ok?
![](https://www.dropbox.com/s/0yc5t6mtub6uonr/Screenshot%202017-07-17%2015.03.09.png?dl=1)
![](https://www.dropbox.com/s/co15ufmny98j7ry/Screenshot%202017-07-17%2015.03.29.png?dl=1)

**Comment by asmsuechan** [comment]
Hi, @Alaev. I fixed it in https://github.com/BoostIO/Boostnote/pull/710 and will be released in a few weeks.

**Comment by Alaev** [comment]
@asmsuechan Glad to hear. TY.

**Comment by evmin** [comment]
I would like to support the idea of the relative paths for the images. I think having them realitev to the storage location would enable moving and re-linking storages without loosing images. Happy to elaborate if require.

**Comment by asmsuechan** [comment]
@evmin I'm going to try to implement it soon.

**Comment by kazup01** [comment]
Updated in v0.8.12! #735

**Comment by k4ch0** [comment]
Thanks for sending!   
  
  
  
  
  
 Luis Cacho  

  
Sent from my Mobile Device
  
  
  
  

  
  
>
