### ISSUE TITLE
Dragging and dropping images overwrites existing images with no warning

### ISSUE THREAD

**Issue by vvs** [BoostIO/Boostnote#652]
When you drag'n'drop the image into the code editor, the image is being copied and overwrites previously existing image in the STORAGE/images folder.

It would be nice to warn about this, and provide some means for user to resolve the issue. Or, maybe, just append number at the end of the file name to make the new filename unique.

**Comment by asmsuechan** [comment]
Hi, @vvs. I believe it's good to solve this by naming a random name to the file is good.

**Comment by asmsuechan** [comment]
Fixed.

**Comment by yashha** [comment]
How do you drop something?
When I want to drop an image I'm back in Preview mode.
