### ISSUE TITLE
UI issue on scrollbar of note list

### ISSUE THREAD

**Issue by IzumiSy** [BoostIO/Boostnote#654]
A scroll bar of note list stays even after the note list hides.
I am using Boostnote 0.8.10 on Ubuntu 16.04

**Before closing**
![selection_028](https://user-images.githubusercontent.com/982850/27361281-3a4fb9a8-5661-11e7-82de-b5795d17429d.png)
**After**
![selection_029](https://user-images.githubusercontent.com/982850/27361288-44cd7438-5661-11e7-8528-e1d85d9d7636.png)

**Comment by asmsuechan** [comment]
Hi, @IzumiSy. It's fixed by https://github.com/BoostIO/Boostnote/pull/644 :dancer:

**Comment by IzumiSy** [comment]
Oh I missed it, Thanks! Will close this.
