### ISSUE TITLE
Translate in Russia

### ISSUE THREAD

**Issue by AlexanderBelkevich** [BoostIO/Boostnote#655]
Hello! How can I help with the translation into Russian?

**Comment by kazup01** [comment]
Cool! I will send you the part I would like you to translate later.
Thanks for your help!

**Comment by AlexanderBelkevich** [comment]
I will wait :)

**Comment by kazup01** [comment]
Please translate the following files. If you have any questions, please feel free to contact me 😊

- [contributing.md](contributing.md)
- [build.md , debug.md and testing.md](https://github.com/BoostIO/Boostnote/tree/master/docs)
- [readme.md](https://github.com/BoostIO/Boostnote/blob/master/readme.md)

**Comment by AlexanderBelkevich** [comment]
contributing.md not found :(

**Comment by kazup01** [comment]
Oops sorry, I fixed the link.

**Comment by AlexanderBelkevich** [comment]
Thank you! I will translate these files today. A translation of the interface will do? :)

**Comment by kazup01** [comment]
Thanks! What is "interface"?

**Comment by AlexanderBelkevich** [comment]
http://prntscr.com/fmotw8
http://prntscr.com/fmou2h
Interface in programm :)

**Comment by kazup01** [comment]
You're not need to translate the interface. Thanks :)

**Comment by asmsuechan** [comment]
Hi, @AlexanderBelkevich. As a matter of fact, it's hard to translate the program interface for now. I'll want your support after I implement something like `Language` menu which can change the settings of the language (it means `i18nize`).
But, we'd be happy if you translate our documents in `docs` directory :dancer:

**Comment by AlexanderBelkevich** [comment]
Oh sure. I'll translate docs :)

**Comment by asmsuechan** [comment]
Really thank you so much!

**Comment by AlexanderBelkevich** [comment]
Somehow, when I try to send a change, I get an error.
I attach the translation archive.
[ru.zip](https://github.com/BoostIO/Boostnote/files/1093779/ru.zip)

**Comment by kazup01** [comment]
Thanks! I'll check it later!

**Comment by AlexanderBelkevich** [comment]
You can always write to me if you need help with the translation!

**Comment by kazup01** [comment]
I added [docs](https://github.com/BoostIO/Boostnote/tree/master/docs/ru) and [contributing.md](https://github.com/BoostIO/Boostnote/blob/master/contributing.md) 👍 Let me know if there is any mistake!

**Comment by AlexanderBelkevich** [comment]
All perfectly! As it will be possible to translate the interface - write to me. I will help!

**Comment by kazup01** [comment]
Yahhhhh Thanks!! You are very kindfull man! Let me know if you come to Tokyo! Let's eat Sushi together 🍣

**Comment by AlexanderBelkevich** [comment]
And to you many thanks! Happy to help! Maybe someday I'll be in Tokyo. And you come to Russia!)))
