### ISSUE TITLE
Copy code snippet hangs client

### ISSUE THREAD

**Issue by neoel** [BoostIO/Boostnote#657]
![image](https://user-images.githubusercontent.com/1440704/27384911-ffd715e8-5690-11e7-8eef-636bc00b7824.png)

When I click on the copy icon as shown in the screenshot, the entire application crashes

**Comment by kazup01** [comment]
Nobody has reported this bug. Could you teach me about your dev environment?

**Comment by neoel** [comment]
I'm Running Kubuntu
```
❯❯❯ lsb_release -a
LSB Version:    core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch                                                                                             
Distributor ID: Ubuntu                                                                                               
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```
Installed boostnote through the package manager
`boostnote/now 0.8.10-1 amd64 [installed,local]`

**Comment by ZeroX-DG** [comment]
@neoel I think it's fixed in the latest version. I'll close this, for now, if it still exists, feel free to re-open this issue.
