### ISSUE TITLE
add a document for guide

### ISSUE THREAD

**Issue by hanfengcan** [BoostIO/Boostnote#666]
hi, team

boostnote is a nice note I can find. But I not found any document about how to use. Can add a document like guide or tutorial or wiki ?

thinks

**Comment by asmsuechan** [comment]
Hi, @hanfengcan! Check this out https://www.youtube.com/channel/UCtyaQWWWV-CECTabb-GWiLg.

What made you confused?

**Comment by hanfengcan** [comment]
OK
