### ISSUE TITLE
boostnote grabs global "ALT+CMD+l" key combo on Mac with no way of turning it off

### ISSUE THREAD

**Issue by larifari** [BoostIO/Boostnote#668]
Once boostnote is running, pressing "ALT+CMD+l" (that's lower case L) will bring boostnote to the foreground. This can neither be configured in boostnote nor macos settings.
Unfortunately "ALT+CMD+l" is the shortcut for source code indenting of jetbrains IDEs such as intellij and webstorm. Please make this shortcut configurable.

**Comment by asmsuechan** [comment]
Hi, @larifari! You can change it in `Menu -> Hotkeys`.
![screen shot 2017-06-28 at 18 55 22](https://user-images.githubusercontent.com/11307908/27631436-711f25d6-5c33-11e7-8d8d-de896f663606.png)

**Comment by cristi-d** [comment]
Hi,

First of all, I'm using Boostnote on Ubuntu 16.04 and it's a great app. Good job!

I want to report the same issue on my OS: having mapped the Toggle Finder to `Ctrl + F` this hotkey stopped working in Chrome. 
I have checked and indeed it somehow captures this hotkey globally.

Also, after mapping the Toggle Finder hotkey to a vacant key combination I noticed that the Finder popup isn't really displayed.

Thanks and if you need any additional info, let me know

**Comment by kazup01** [comment]
Hi @cristi-d , thanks for your message!
How about change the Hotkey, as @asmsuechan said?
