### ISSUE TITLE
Color Highlighting for Markdown

### ISSUE THREAD

**Issue by EavenSheets** [BoostIO/Boostnote#670]
I tend to find looking at my notes easier when I use the editing mode version of the note rather than the live preview of markdown. I think having an option to use the same color syntax in the preview would make looking at notes much easier and pleasing to the eyes. As option, if others do not like this feature they could just keep it off, but I imagine I am not alone.

**Comment by kazup01** [comment]
Color syntax in editing mode is available for current version. How about this?

<img width="621" alt="screen shot 0029-07-03 at 11 15 31 am" src="https://user-images.githubusercontent.com/8602615/27775872-fe16d500-5fe0-11e7-9c14-5eb29b0e097f.png">

**Comment by EavenSheets** [comment]
I guess that works for now, but I was more of thinking of something along the line of the actual Markdown preview having some more color to it. The one thing that I would love to have changed with Markdown is more color to it. We put all of this effort into coloring our text editors in a way that is appealing to our eyes, but why not apply that to other things as well.

**Comment by AlexWootton** [comment]
This could be achievable now that Boostnote supports custom CSS for the preview. I would be interested in this as well so if anyone has any success please let us know here! 😄
