### ISSUE TITLE
Snippet description - Change font

### ISSUE THREAD

**Issue by kirtan403** [BoostIO/Boostnote#673]
Currently, the fonts in the snippet, looks like this:

![image](https://user-images.githubusercontent.com/7900938/27769842-ab037b74-5f50-11e7-9e6f-d20c369c4b19.png)

How about updating it to make it consistent with the app?

**Comment by kazup01** [comment]
Thanks for your feedback!
I fixed this at #675 just a while ago.

**Comment by kirtan403** [comment]
That's awesome! :+1:
