### ISSUE TITLE
Import Doesn't Do Anything on Windows

### ISSUE THREAD

**Issue by GaryFurash** [BoostIO/Boostnote#676]
OS: Window 7, latest version

File > Import From > Plain Text

(nothing happens).

**Comment by asmsuechan** [comment]
@GaryFurash Please paste some screenshots with opening the developer tool.

**Comment by GaryFurash** [comment]
![image](https://user-images.githubusercontent.com/15006133/27916144-0da790ac-621d-11e7-8ada-c949f64d1470.png)
[Document1.pdf](https://github.com/BoostIO/Boostnote/files/1128170/Document1.pdf)

**Comment by asmsuechan** [comment]
No. I want to see the console on the error happening.

**Comment by GaryFurash** [comment]
How do I get the console to show what's happening. When I click developer tools -> Console (tab) I just see the prompt. I don't see any error message or activity.

**Comment by GaryFurash** [comment]
Oh, I figured it out. If I do something normal I see the results in the console. If I try File > Import From... NOTHING happens in the console. It's as if no event is getting triggered.

**Comment by ChukkChukk** [comment]
Same thing happening here. I had installed from chocolatey.  Don't know if that maybe created an issue with a possible path? It seems as if on Windows 7 and installing with chocolatey, this has happened with a few different programs. Had to reinstall a few things, including Node.js from binary because of it. How did you install it @GaryFurash?

**Comment by ChukkChukk** [comment]
@asmsuechan  I was getting a bunch of errors from the main.js and react.js packages. There were a lot, starting on line 11 of main.js. I'm gonna install it another way and see if that changes anything, but don't know when I'll get to that. It would not open any file, even when I changed windows to open markdown files using Boostnote. Been waiting to use it too!

**Comment by GaryFurash** [comment]
I just downloaded and clicked the executable

**Comment by ChukkChukk** [comment]
This seems to be an new issue. This issue is also on the boost-releases issues with "no storage mount". [https://github.com/BoostIO/boost-releases/issues/18](https://github.com/BoostIO/boost-releases/issues/18)

**Comment by GaryFurash** [comment]
I tried deleting the folders under ~/AppData and reinstalling but no luck ;-(

**Comment by asmsuechan** [comment]
@GaryFurash I fixed it and will be released in a few days. (I didn't notice that you created this issue as same as https://github.com/BoostIO/Boostnote/issues/729, sorry!)

**Comment by asim-vax** [comment]
@asmsuechan  was this released as the issue still occurs?
