### ISSUE TITLE
Scrolling with scrollwheel doesn't work after editing markdown note

### ISSUE THREAD

**Issue by MakisH** [BoostIO/Boostnote#680]
## How to reproduce:
1. Open a loooooong note. --> Scrolling works in the view mode, both with the scrollbar and the scrollwheel.
2. Enter the edit mode.
3. Make an edit that affects the markdown structure. E.g. change the level of a heading or add a bullet in a list.
4. Exit the edit mode. --> Scrolling does not work with the scrollwheel, but works with the scrollbar.
5. Open another note and then return to the previous one. Now scrolling works again.

## Observations
* If I simply enter and exit the edit mode, there is no problem.
* If I do only trivial changes that do not involve any changes in the markdown, there is no problem.

## Versions
**Boostnote**: 0.8.11 (I also noticed this in 0.8.10 and maybe it was introduced in 0.8.10 or in a recent previous version).
**Platform**: Ubuntu 16.04 64bit.

**Comment by kazup01** [comment]
Hi @MakisH , thanks for your reporting!
It did not reproduce in my dev environment.
**Boostnote v0.8.11 / macOS 10.12.3**

Would you please attach a movie or gif?

**Comment by AlexEshoo** [comment]
This seems to be the same issue discussed in #170

**Comment by MakisH** [comment]
Here is a short video:

![ezgif-1-dc296b645f](https://user-images.githubusercontent.com/4943683/27906391-a4f4695a-6243-11e7-85f5-ecb2254e8459.gif)

Now that I see #170 closer, it looks like it's the same or very similar issue. Except that for me scrolling works in editing mode.

**Comment by kazup01** [comment]
Thanks for your cooperation @MakisH ! I will fix it.

**Comment by Mindstormer619** [comment]
Hi, any updates on this? :)

**Comment by MakisH** [comment]
I still have this issue in 0.8.15. I think this is an important issue, because it occurs almost every time a user edits a note (at least for my setup).

I noticed that you try to draw attention to some issues with the "Hacktoberfest" label. I suggest that you draw also some attention on this issue with this tag.

**Comment by Mindstormer619** [comment]
For now I have a quick-n-dirty fix that I use as a fast "refresh" mechanism. You need to have at least two notes in the folder for this to work.

1. Edit your note.
2. Exit the editor using `Ctrl + W`
3. Quickly type `Ctrl + J` then `Ctrl + K`. This will take you to the next and then back to your current note quickly, forcing the refresh. You can leave your finger on the `Ctrl` key and just hit `J` then `K` in quick succession.
4. Note is refreshed. Now you can scroll 😄 

Granted, this does not fix the issue at hand. It *is*, however, a workable alternative for the time being.

**Comment by kazup01** [comment]
I'm sorry to have kept you guys waiting so long in the wrong UX.
I've fixed it just now. #1149 
We will update to v0.8.17 in this week. Thank you for waiting!

**Comment by kazup01** [comment]
v0.8.17 is out!

**Comment by MakisH** [comment]
Almost there...! Scrolling is working, however I get two scrollbar thumbs after exiting the edit mode:

![boostnote_scrollbars](https://user-images.githubusercontent.com/4943683/33239540-7db46eec-d2ac-11e7-91dd-50e3c0f26780.png)

Maybe related to #1174, #1175, #1091.

**Comment by kazup01** [comment]
Thanks @MakisH , I will fix it.

**Comment by kazup01** [comment]
Hi @MakisH , how about this layout?
https://github.com/BoostIO/Boostnote/issues/1173#issuecomment-346989681

**Comment by MakisH** [comment]
@kazup01 I am not sure I understand what I should see. The problem I mentioned above is with the scrollbars, not with the layout. :-) As soon as the scrollbar is ok, everything else is another issue.

**Comment by WazzaSoft** [comment]
@kazup01 I'm not sure what the status is on this, but I just installed 0.8.19 and got the same issue MakisH is talking about. It looks like the scrollbar from the edit mode is still visible in the preview mode (but, we can use the scroll wheel now!!!).

Here's what I mean for visual reference. (Red = edit scrollbar, Green = preview scrollbar)

In edit mode:
![edit](https://user-images.githubusercontent.com/25997967/34699086-62387a9a-f490-11e7-8d3f-61ee6dec2da4.png)

In preview mode (scrolled to top):
![preview-1](https://user-images.githubusercontent.com/25997967/34699087-62562a9a-f490-11e7-91b1-b453f9d12eb7.png)

In preview mode (scrolled to bottom):
![preview-2](https://user-images.githubusercontent.com/25997967/34699088-6271528e-f490-11e7-8b1f-1f5eee018855.png)

I hope this helped clarify what the issue was. Thanks for all of your hard work!

**Comment by MakisH** [comment]
In 0.8.20 on Ubuntu it looks mostly fixed for me! The underlying scrollbar is still shown in the beginning, but disappears instantly after I start scrolling.
