### ISSUE TITLE
Gentoo support?

### ISSUE THREAD

**Issue by jolenzy** [BoostIO/Boostnote#687]
This looks like an app I'd use daily. Why there's no other packages other than .deb?

Any plans on supporting other Linux distros? Or making an Appimage?

**Comment by TeHMoroS** [comment]
Making an ebuild for a .deb package is pretty straight-forward, when installed "1 to 1". Looking at Boostnote however I would do some modifications (like adding a "system-electron" USE flag to let people decide if they want to use their own Electron installation or the bundled one).

That being said, @jolenzy you don't have to have an ebuild to use Boostnote on Gentoo. Just use "ar" (a little archiving utility from the binutils ebuild, that is used to create .deb. packages) to extract the .deb file, then extract data.tar.xz file to a directory of your choice and make yourself a .desktop file (the icon is in the package).
Just be sure to check if you have all the necessary dependencies ("ldd directory_of_your_choice/share/boostnote/Boostnote") and emerge them if needed (although if you have Chromium or Electron emerged already, you're good to go). :)

**Comment by jolenzy** [comment]
Thanks, that worked. :)
