### ISSUE TITLE
Three single quotes in markdown file causes notes not to load

### ISSUE THREAD

**Issue by otherwhich1** [BoostIO/Boostnote#691]
I had a problem occur where I loaded Boostnote (v0.8.9 and v0.8.11) and all the markdown notes, although listed under Storages, were empty. 

I believe I traced it to triple single quotes in the markdown text. It looks like the .cson files begin and end the markdown contents with triple, single quotes ('''):
```
content: '''
 [ markdown notes here...]
'''
```
so it presumably has trouble parsing it when it encounters an errant triple single quotes. This is a screen shot showing Boostnote with the Developer Tools open:
![image](https://user-images.githubusercontent.com/29990888/27980577-f13659e4-6334-11e7-8daf-c50455f2ee9b.png)

Removing the triple single quotes alleviates the problem, and all the notes are loaded properly.

There was a related issue #185 with single triple quotes followed by closed parentheses in v0.8.3, but it got resolved back then.

Thanks!

OW1

**Comment by incredibleweirdo** [comment]
Appears related to #677 and #515. From my non-expert attempts to investigate/debug, it appears the root of the issue lies with Coffeescript. Perhaps there is a way for Boostnote to sanitize or escape three or more single quotes in sequence in either markdown or snippet notes?

**Comment by asmsuechan** [comment]
This issue happens because of CSON's specification sadly. CSON uses coffeescript, so it needs `'''` to discribe a sentence with lines.

http://coffeescript.org/
![image](https://user-images.githubusercontent.com/11307908/28996022-95a48faa-7a32-11e7-9cb2-111429f79375.png)

That's why Boostnote fails to parse a note which contains `'''` in the note content.

Actually, it's very hard problem. So I have no idea to solve it for now soon. But I'll do my best to solve it.

**Comment by fhaag** [comment]
I am just running into the same problem in BoostNote, when I tried to save a snippet containing the sequence `''''`.

But I think there is a solution: BoostNote would save this as `\''''`. The three consecutive apostrophes after the first escaped one would still cause this issue. If I manually modify the `.cson` file to contain `\'\'\'\'`, though, it appears to work again.

Maybe you could check and modify BoostNote's saving behaviour accordingly?

**Comment by webwake** [comment]
Steps to reproduce (version 0.11.6) create a new note, enter 4 single quotes followed by a new line followed by 4 single quotes. Close and reopen. The new note will no longer be loaded or available. Breaks on both markdown notes and code snipit notes
```
#test
''''
''''
```

**Comment by Flexo013** [comment]
This bug is no longer present in the latest version of Boostnote:

![image](https://user-images.githubusercontent.com/4507015/62883146-ae7e3800-bd33-11e9-8b1f-ccb4b7eb75db.png)
