### ISSUE TITLE
When i use the reading mode is there anyway to disable "click to edit"

### ISSUE THREAD

**Issue by dwbFrank** [BoostIO/Boostnote#694]
The problem I have with this feature is that I very often click on parts of the text without any intention of editing it. It could be because I want to select the text, or I have some text selected and now I want to de-select it (so I just click anywhere in the text). Or it can be that I simply click somewhere because I just wanted to (I do that quite often, you might call it a tic), or maybe I click just by accident. I want to have the edit mode activated.

**Comment by asmsuechan** [comment]
Hi, @dwbFrank. You can set the way how to toggle it by right-click in UI menu.
<img width="1112" alt="screen shot 2017-07-08 at 18 37 20" src="https://user-images.githubusercontent.com/11307908/27984268-843edff4-640c-11e7-80bb-7d3a2b2c3b51.png">

**Comment by dwbFrank** [comment]
Thanks for your help. It works for me.

**Comment by asmsuechan** [comment]
Good to hear.
