### ISSUE TITLE
Tags not visible behind progressbar on certain screensize

### ISSUE THREAD

**Issue by yashha** [BoostIO/Boostnote#703]
Tags not visible behind progressbar on certain screensize
on 0.8.10
![screenshot from 2017-07-11 22-19-29](https://user-images.githubusercontent.com/4728786/28089105-1f8efe08-6688-11e7-8ab8-1fff7c7159e6.png)
![screenshot from 2017-07-11 22-32-05](https://user-images.githubusercontent.com/4728786/28089279-cdd828c2-6688-11e7-91af-d197d38eabfd.png)

**Comment by kazup01** [comment]
Fixed at #1121.
Please wait for the next update.

<img width="638" alt="screen shot 0029-11-14 at 9 24 35 pm" src="https://user-images.githubusercontent.com/8602615/32779979-0e9671f4-c983-11e7-909d-1375d2706554.png">
<img width="396" alt="screen shot 0029-11-14 at 9 29 44 pm" src="https://user-images.githubusercontent.com/8602615/32779980-0ec064e6-c983-11e7-92c3-94bac03fe664.png">
<img width="411" alt="screen shot 0029-11-14 at 9 32 00 pm" src="https://user-images.githubusercontent.com/8602615/32780050-47536146-c983-11e7-8abf-c429803aafb8.png">
