### ISSUE TITLE
Link to header in Markdown note

### ISSUE THREAD

**Issue by ghost** [BoostIO/Boostnote#712]
So for example if I have a note that is formatted similar to the snippet below, I would be able to link to a specific header in a note. If this is currently supported I am unable to get it to function. If not, could it be something implemented?

```markdown
# List 1
* [Option 1](#option-1)                   
* [Option 2](#option-2)
<br>
...
<br>
## Option 1                                  
## Option 2
```

**Comment by kazup01** [comment]
Hi ghost, this feature is released at v0.8.15 by asmsuechan's great work! Enjoy! #812
