### ISSUE TITLE
Import Doesn't Work on Windows 7 or 10

### ISSUE THREAD

**Issue by GaryFurash** [BoostIO/Boostnote#729]
On two separate machines (win 7, win 10), Import From doesn't do anything. No pop-ups, no error messages, no dialog, nothing in the console.
![capture20170725074540874](https://user-images.githubusercontent.com/15006133/28578076-77f61b32-710d-11e7-9361-25c2c4f852ca.png)

**Comment by asmsuechan** [comment]
I fixed it and will be released in a few days.
![image](https://user-images.githubusercontent.com/11307908/28601858-ab134894-71f5-11e7-9b2d-2cac2aba0dc9.png)
