### ISSUE TITLE
Drag+Drop Notes

### ISSUE THREAD

**Issue by pcampbell-software** [BoostIO/Boostnote#73]
I wanted to suggest this as a possible enhancement; the capability to drag and drop  notes between folders and/or storage areas.

I currently have my Boostnote setup as a knowledge repository for multiple projects and so the number of folders has grown over time. Thus, if I want to move a note elsewhere; finding it in the list is not as easy anymore as I have many options.

Dragging and dropping would improve the UX and allow for simple and quick organisation of notes.

**Comment by Rokt33r** [comment]
I agree with your idea. It will be shipped some when. I'll inform you again when I'm ready.

**Comment by Rokt33r** [comment]
Closed! You can track the progress on TodoList #68 
I'll add a comment when it implemented!
