### ISSUE TITLE
Is there documentation?

### ISSUE THREAD

**Issue by ibtrey** [BoostIO/Boostnote#733]
Hi,

Been using not too long and I love the UI and the dark-theme feature.

I've been saying that you can do stuff like to-do lists, code snippets etc. etc. - my issue is, I have no idea how to use.

right click does nothing, Menu -> hotkey only has 2 items, and I haven't found anything on the website on how to do?

Just a simple text document will do :)

OS: Windows 7 64bit

**Comment by Alaev** [comment]
Hey,
I think it would be best if you learn some markdown.
All the to-do list/code snippets can be done easily.

- [ ] - this todo
- [x] - this is done

```javascript

function foo(){
  return bar();
}

**Comment by ibtrey** [comment]
Hi @Alaev ,

Yeah - for some people that's not a general knowledge thing, I think just generic documentation on how-to would go a mile for people :)

And I can't edit your message to see the markdown :/

**Comment by Alaev** [comment]
I see, Yes then it a good call to have some docs with examples on how to do different tasks.

Raw message:
![mark](https://www.dropbox.com/s/xs8gcqjzh1mpk8m/Screenshot%202017-07-27%2013.54.58.png?dl=1)

**Comment by ibtrey** [comment]
Hi @Alaev ,

Ah awesome :)

And thank you very much! This will help make better notes :)

**Comment by asmsuechan** [comment]
I'm writing a document https://github.com/BoostIO/Boostnote/wiki/Getting-Started and an article https://medium.com/boostnote/boostnote-changes-programmers-note-taking-experience-703cc6b06835. I hope they help you.
