### ISSUE TITLE
All my storages dissapeared and I can't add more

### ISSUE THREAD

**Issue by guayom** [BoostIO/Boostnote#734]
After a system update, boostnote stopped working. I can't add any new storage.
This is a screenshot of how it looks:
<img width="1031" alt="captura de pantalla 2017-07-27 a la s 14 40 50" src="https://user-images.githubusercontent.com/3279037/28691317-b5edd9ac-72d9-11e7-9485-b78a4ddcd515.png">

When I add new storage, everything seems like normal. I can see the list of all the folders in my storage. But when I close that pop up window, I still have that screen that I attached.

I'm using MAC OS Sierra 10.12.5

**Comment by asmsuechan** [comment]
Hi, @guayom. Could you paste a screenshot with opening developer console? (Cmd+alt+i)

**Comment by kazup01** [comment]
Your data has not disappeared. Please relink the file from preferences.
<img width="700" alt="screen shot 0029-07-31 at 10 51 38 am" src="https://user-images.githubusercontent.com/8602615/28759997-4235604a-75de-11e7-9560-8ff78c8a8939.png">

**Comment by guayom** [comment]
Hi, sorry for the late reply. I already know what happened. It isn't a bug.
My user directory changed. It used to be eduardomena. Now it is emenaa. This was something done by the IT team in my company, and I wasn't aware.

Here's what I see in the developer tools:
![captura de pantalla 2017-08-11 a la s 08 53 25](https://user-images.githubusercontent.com/3279037/29218741-fd305ffc-7e72-11e7-8de2-1b27e0a10d5a.png)

Where can I set that directory name?

**Comment by guayom** [comment]
I've tried reinstalling the app completely but still, the problem is the same.
The solution @kazup01 proposed doesn't work. I select the right path, but still, the storage won't load.

**Comment by kazup01** [comment]
I don't know why the permission error is occurring. Please check #742 or select the correct file.

**Comment by guayom** [comment]
After installing the latest version, the error is gone.
