### ISSUE TITLE
[Feature request] Confirming the deletion of a note

### ISSUE THREAD

**Issue by fmaida** [BoostIO/Boostnote#739]
IMHO the trashcan icon is placed not too far from the "expand" icon, and therefore someone might want to press the expand button and finishing by clicking the trashcan icon by mistake:

![boostnote](https://user-images.githubusercontent.com/605017/28744256-05e07b70-745d-11e7-97b8-69c6aab6f3cb.jpg)

Could I suggest you to add an option in the "preferences" menu to specify if -before deleting a note- Boostnote must ask the user to confirm that operation ?

You could simply put a checkbox, and -if checked- each time a user tries to delete a note Boostnote should ask him to confirm the deletion of the note with a messagebox dialog.

**Comment by asmsuechan** [comment]
@fmaida You can restore the note in `Trash` easily. That's why I removed the dialog box.
