### ISSUE TITLE
Gist integration

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#74]
I'm going to provide 2 options to integrate gist.
## Syncing a gist with a note

Every note will be provided an option to export as a gist and keep syncing it.

~~## Gist folder~~

~~Syncing whole gists of a github account with a folder.~~
~~Tags in Boostnote will be kept by hashtags in description of a gist.~~
### Categorizing Folder / Tag?

We provide a service which can store the Folder/Tag map of gists.
The server can not be accessed by URL.

> I thought adding a map file to secret gist would be fine. But, I noticed all of secret gist is visible if a user has URL. So, we think we have to provide the service.

**Comment by specktator** [comment]
IMHO, note sharing should keep the expire time & secret gists, plus the things you said above. Most of the time we share small snippets between colleagues, they shouldn't be kept hanged in public Gists.

Also along with other types of storage google drive, dropbox .. you should consider [seafile](https://github.com/haiwen/seafile) too! Is an excellent open source cloud solution and can be self hosted as well!

**Comment by Rokt33r** [comment]
@specktator Thank you for commenting. I'll check seafile later.

**Comment by bennypowers** [comment]
Is this feature abandoned?
