### ISSUE TITLE
Rearrange storage

### ISSUE THREAD

**Issue by Alaev** [BoostIO/Boostnote#741]
Please paste some **screenshots** with opening the developer tool if you report a bug.

Is there an option to rearrange the side bar of my storage?
Like drag and drop to other position / rearrange with edit button or sort by name?

![img](https://www.dropbox.com/s/jzpdjubjillb7k4/Screenshot%202017-07-30%2010.05.12.png?dl=1)

**Comment by JSn1nj4** [comment]
I would like this too.

But for now it seems you can do it if you open your Preferences, and click the button to open your storage:

![image](https://user-images.githubusercontent.com/5084820/28758222-61a9daae-7562-11e7-8758-5c971721741b.png)


The folder, at least on Windows, is located at `%homepath%\Boostnote`:

![image](https://user-images.githubusercontent.com/5084820/28758243-a1477306-7562-11e7-9890-70ae89f728e0.png)

The storage is just a simple JSON file that can be rearranged:

![image](https://user-images.githubusercontent.com/5084820/28758262-d495823e-7562-11e7-9061-7e468d5d1850.png)

**Comment by Alaev** [comment]
@JSn1nj4 Yes I know that however editing each json is not at confutable especially if you have a bunch of them. I will try to see if I can patch some on edit this storage file. 👍

**Comment by kazup01** [comment]
v0.8.16 is released. Folder rearrange is available now. #853

**Comment by Alaev** [comment]
Closing for #853
