### ISSUE TITLE
Notes wouldn't show up in the editing panel

### ISSUE THREAD

**Issue by xuewang** [BoostIO/Boostnote#742]
After updating to 0.8.12, none of my notes can be shown or edited. Screenshot is attached below. Any help would be appreciated.

<img width="1438" alt="screen shot 2017-07-30 at 6 19 28 pm" src="https://user-images.githubusercontent.com/1138562/28753332-65a6523c-7566-11e7-9c43-477b999c0222.png">

**Comment by kazup01** [comment]
This bug has not been reported. Could you tell me about your dev environment?

**Comment by xuewang** [comment]
BTW, this is on my MacBook running Sierra 10.12.4 (16E195)

**Comment by asmsuechan** [comment]
Could you give me a storage hash in `Resources->LocalStorage->file:` as you can?
![image](https://user-images.githubusercontent.com/11307908/28753766-5887d7ac-7574-11e7-8e6e-fbb2207e763e.png)

**Comment by xuewang** [comment]
@asmsuechan `[{"key":"a9f21fb67e868856c8d3","name":"My Storage","path":"/Users/alexwang/Documents/Boostnote"}]` The app seems to be working just now. But after restart, the problem appears again.

**Comment by xuewang** [comment]
It seems that the app fails to load some of my notes. Some of the notes are fine, some will cause `main.js` to throw `Uncaught Error: Target storage doesn't exist.`. I just found the line at [findStorage.js](https://github.com/BoostIO/Boostnote/blob/a480ca7b551bf70becf8000047b6608194c5c27c/browser/lib/findStorage.js#L7)

**Comment by asmsuechan** [comment]
The storage seems not bad. Umm.
`findStorage` is not released, so I think it's here: https://github.com/BoostIO/Boostnote/blob/bfd67fb7f1e96e37f8e840ffddc968afffda370f/browser/components/MarkdownEditor.js#L220

**Comment by kazup01** [comment]
Have you tried re-linking the existing files from preferences? @xuewang 
<img width="700" alt="screen shot 0029-07-31 at 10 51 38 am" src="https://user-images.githubusercontent.com/8602615/28760059-b9fb1476-75de-11e7-8dd0-51a56f9aa715.png">

**Comment by xuewang** [comment]
@kazup01 tried several times, but with no luck :(

**Comment by xuewang** [comment]
@asmsuechan I just did some debugging, and found that `storageKey` is undefined in the react component props, as shown in the screenshot below. I'm not quite familiar with react, so I may need your help to find out why `storageKey` is undefined. 
![snapshot](https://user-images.githubusercontent.com/1138562/28765523-be5f2b46-75fd-11e7-84ee-f02aa05099d6.png)

**Comment by asmsuechan** [comment]
Great. Could you paste the note-link in InfoPanel?
![image](https://user-images.githubusercontent.com/11307908/28765743-374b2466-7607-11e7-9699-de5d3c67dd1a.png)

**Comment by xuewang** [comment]
The info panel wouldn't show up after the `Target storage doesn't exist.` error :(

**Comment by milesibastos** [comment]
Same issue... I have no access to my notes anymore after latest release!
![image](https://user-images.githubusercontent.com/55114/28792247-5bb7713a-7605-11e7-97e2-0fe059c3993a.png)

**Comment by asmsuechan** [comment]
I cannot reproduce this error, so I don't know what exactly happens. I'll do my best to fix it. Until then please use previous version 0.8.11 https://github.com/BoostIO/Boostnote/releases/tag/v.0.8.11.

**Comment by asmsuechan** [comment]
@xuewang Could you help me with debug?

**Comment by xuewang** [comment]
@asmsuechan Sure. I'm more than glad to help.

**Comment by asmsuechan** [comment]
@xuewang Thank you very much. I want to talk in slack so could you join our slack team? https://join.slack.com/t/boostnote-group/shared_invite/MjE3NDcwODQ3NTkwLTE1MDA4NjQ3ODktM2IxOTk4ZTNjYQ

**Comment by asmsuechan** [comment]
I still don't reproduce this bug. So could you someone give me your storage folder as you can via email, please?

**Comment by asmsuechan** [comment]
Hi, did you someone create `Markdown` snippet? It might be the cause of this issue.

![image](https://user-images.githubusercontent.com/11307908/29125258-461d11a6-7d56-11e7-926d-990d82aaed73.png)

**Comment by xuewang** [comment]
@asmsuechan sorry, I've been extremely busy these days, my current project is reaching its first milestone. I'll be able to look into the problem next week. Just to confirm, yes, the corrupted notes were markdowns.

**Comment by asmsuechan** [comment]
@xuewang No worry, please help us as far as you can.

> the corrupted notes were markdowns.

Do you mean the notes are **snippet** notes?

**Comment by kazup01** [comment]
This bug is fixed at #780. Thanks @asmsuechan !
