### ISSUE TITLE
Drag and drop image does not generate a link

### ISSUE THREAD

**Issue by evmin** [BoostIO/Boostnote#743]
Good day.

When I drag and drop an image into boostnote, it is added to images folder in storage, yet the link is not inserted.

I am using vim editor keymap and switching preview "When right clicking".

Great tool - love it!

**Comment by asmsuechan** [comment]
Hi, @evmin. Were you in `insert` mode? And what's your version?

**Comment by evmin** [comment]
I have tried all three - 

* Editor : Insert
* Editor : Command
* View 

The version is 8.1.2, Mac OS X 10.12.5
When I define it manually as :storage - it works.

Thanks!

**Comment by asmsuechan** [comment]
Umm, please make sure the caret is active.

**Comment by evmin** [comment]
Not sure I understand, tbh. When I drag something from another window, the caret focus goes away. Do I miss something obvious here?

**Comment by evmin** [comment]
Aha, figured this out. Both windows need to be side by side. Any other option fails. Thank you!
Good enough for now. Going forward could be a good idea to have a menu item (Insert Image) .

Please close the issue. Thank you for the prompt response.

**Comment by asmsuechan** [comment]
Good to hear! Have fun!
