### ISSUE TITLE
Image drag and drop not working when using `When Editor Blurred`

### ISSUE THREAD

**Issue by txchen** [BoostIO/Boostnote#744]
There is no 'lock' icon in this mode. Paste image then is not possible when we choose `when editor blurred`

**Comment by asmsuechan** [comment]
> There is no 'lock' icon in this mode.

Could you explain more explicit? Screenshots will work.

**Comment by txchen** [comment]
@asmsuechan I tried again, there is the `lock` icon, my bad, please ignore.

But I can confirm that drag a local image file into the editor, it will not generate image link `[xxx](yyy}`, no matter it is locked or not. However, I found that the image is actually uploaded to the file store.

**Comment by asmsuechan** [comment]
Please make sure the caret is active.

**Comment by txchen** [comment]
@asmsuechan What does `caret is active` mean exactly, please?

**Comment by asmsuechan** [comment]
The caret is active means the vertical bars blinks.
![b50af56bd48204ddd308d21b4c7f29f4](https://user-images.githubusercontent.com/11307908/28782194-6a49389a-7647-11e7-831f-486899e06e81.gif)

**Comment by txchen** [comment]
@asmsuechan got it, it is indeed the root cause. However I still think this is a bug, because:
* When I use shortcut key to switch to another window (finder, for example), the caret becomes inactive.
* When caret is inactive, it would not generate the link, but the image is still uploaded to the file store.

What do you think?

**Comment by asmsuechan** [comment]
Yes indeed.
