### ISSUE TITLE
Feature request: Image resize

### ISSUE THREAD

**Issue by evmin** [BoostIO/Boostnote#745]
Would be great to be able to resize image that are too big:

![My Too Big Image](:storage/92vo43azmbw0o1or.png)

something like:

![My Too Big Image](:storage/92vo43azmbw0o1or.png=300x100)

**Comment by asmsuechan** [comment]
You can resize your image by `![](/path/to/image.png =100x200)`.
ref: https://github.com/BoostIO/Boostnote/pull/598

**Comment by evmin** [comment]
My problem was that I did not leave a space between the name of the file and the equation mark. 
All good.

Once again - love the tool. Slowly switching to it with all my workflows.

**Comment by asmsuechan** [comment]
> Once again - love the tool. Slowly switching to it with all my workflows.

Thank you so much indeed! Have fun!
