### ISSUE TITLE
Unexpected URL-Encoding of Characters in Code Blocks

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#746]
I am on Windows 10, in case it matters, Boostnote V0.8.12.

**Description:** Entering a sequence of the form `%AB` into a code block, with  `A` and `B` any hexadecimal digits, will not show up as the exact sequence `%AB` in view mode, but as the corresponding URL-encoded character.
**Example:** Create a new note with the content 
`````
# Test
```
%2A
```
`````
**Expected Behaviour:** The code block displays the characters `%`, `2` and `A`
**Observed Behaviour:** The code block displays the character `*`

**Comment by ZeroX-DG** [comment]
This bug doesn't appear on the latest version.
