### ISSUE TITLE
Feature request: note search in specific folder

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#747]
I would like to request a feature for the note search. After selecting a folder or the "starred" section, I think it would be useful if the note search would only search among the notes in that folder (resp. among all starred notes).  As of right now (Boostnote V0.8.12), when searching for a note, it will always search **all** notes.

**Comment by asmsuechan** [comment]
I will improve it.

**Comment by asmsuechan** [comment]
Improved.
