### ISSUE TITLE
always loading

### ISSUE THREAD

**Issue by 329379172** [BoostIO/Boostnote#748]
centos7  Linux version 4.4.76-1.el7.elrepo.x86_64
Uncaught Error: ENOENT, node_modules/codemirror/theme not found in /data/downloads/Boostnote-0.8.12/node_modules/electron-prebuilt/dist/resources/default_app.asar

**Comment by asmsuechan** [comment]
Hi, @329379172. Sorry for late reply.
Actually, I'm not sure what exactly it is, but I assume this command helps you.

```
$ cd /data/downloads/Boostnote-0.8.12/ && yarn
```
