### ISSUE TITLE
Ubuntu - Boostnote crashes on Quit.

### ISSUE THREAD

**Issue by TheManFran** [BoostIO/Boostnote#75]
Hi

Boostnote crashes on close. 

Error is: Boostnote crashed with SIGSEGV in atom::NativeWindow::RequestToClosePage()
ApportVersion: 2.20.1-0ubuntu2.1

Ubuntu 16.04
amd64

Kind regards
Francois

**Comment by syossan27** [comment]
@TheManFran 

The cause of the problem is probably that it is electron side.
Will you please try to report in the electron of the issue?

**Comment by Rokt33r** [comment]
@TheManFran 
This issue is duplicated. #57  I'm going to install Ubuntu to my PC on this weekend to deal with this problem.

@syossan27 It might be caused by my mistake. I'll report it after confirming it is not my fault.
