### ISSUE TITLE
[feature request] show todo progress in list

### ISSUE THREAD

**Issue by XGHeaven** [BoostIO/Boostnote#750]
I hope todo progress can show in list.
![image](https://user-images.githubusercontent.com/9291212/28785162-267d8624-7648-11e7-8e16-0c6588b11564.png)
There are my four todo notes, todo progress should shown in red rectangle or other place I hope.

And I very like this app, I hope you can distribute cloud service quickly.
There is no Chinese version of contributing.md. I can translate to Chinese.
And any other Chinese language needed, I can help you.

**Comment by asmsuechan** [comment]
I am willing to agree to your request.

> I hope you can distribute cloud service quickly

Sorry, we don't have any plans to develop it.

> There is no Chinese version of contributing.md. I can translate to Chinese.

Yes, please! I'm really looking forward to seeing your PR indeed.

**Comment by asmsuechan** [comment]
@XGHeaven Really thank you so much for your help! And this feature was released in v0.8.4! :smile:
