### ISSUE TITLE
Ctrl-f globally not working when Boostnote is open

### ISSUE THREAD

**Issue by MakisH** [BoostIO/Boostnote#751]
Whenever I have Boostnote open, typing Ctrl-f to toggle the find in any program (name it Boostnote, Firefox, Atom, Okular, ...) it simply does not work. Nothing happens. When I close Boostnote, everything works well again.

I think this was introduced in one of the last Boostnote versions (0.8.10-0.8.12).

I am using Ubuntu 16.04 and Boostnote 0.8.12.

**Comment by asmsuechan** [comment]
Sorry, I did not understand much about what you say.

> everything works well again

What does your matter?

FYI, we added `find in note by ctrl-f` in version 0.8.12.

**Comment by MakisH** [comment]
I mean that after I close Boostnote, Ctrl-f works again on Firefox, Atom, Okular etc.

So, I cannot use Ctrl-f to toggle the "Find" in any program if at the same time Boostnote is open. I have to close Boostnote first and this is not normal.

Apart from this, Ctrl-f does not open a "Find" form in Boostnote either. But that is another issue.

**Comment by asmsuechan** [comment]
I don't map to `ctrl-f` except `Editor` mode, so I cannot reproduce it.

> Apart from this, Ctrl-f does not open a "Find" form in Boostnote either. But that is another issue.

You can use it to the latest version.

**Comment by MakisH** [comment]
I am using 0.8.12 and it's not working anywhere for me. Neither in "view mode" nor in "editor mode". Currently this is the latest release that I can find on GitHub.

**Comment by MakisH** [comment]
I have the same issue in 0.8.14. Some additional information:

**Scenario 1**: In the _Preferences > Hotkey > Toggle Finder(popup)_ I have "Ctrl + F"

Result: as described in the first post, it looks like the "Ctrl + F" is dead everywhere whenever Boostnote is open. Even in Boostnote's editor.

**Scenario 2**: In the _Preferences > Hotkey > Toggle Finder(popup)_ I have something else, e.g. "Ctrl + T"

Result:

- "Ctrl + T" does nothing (neither in Boostnote nor anywhere else).
- "Ctrl + F" triggers the Boostnote's finder.
- "Ctrl + F" works normally everywhere.

This persists even after restarting Boostnote.

**Scenario 3**:  In the _Preferences > Hotkey > Toggle Finder(popup)_ I leave the field empty.

Result:

- Still "Ctrl + F" triggers the Boostnote's finder.

**Conclusions**

_Conclusion 1:_ "Ctrl + F" is always the key that triggers Boostnote's finder, regardless of the setting in the preferences.

_Conclusion 2:_ Any key that is specified in the _Preferences > Hotkey > Toggle Finder(popup)_ does not work anywhere else when Boostnote is open.

**Next step - Help wanted**

I tried to remove and reinstall Boostnote (with `apt purge`), in order to check if this would solve the problem, but the configuration remains. Where is the configuration stored?

**Comment by MakisH** [comment]
This looks fixed in 0.8.17.
