### ISSUE TITLE
[Feature request] shortcut key for exiting the edit mode

### ISSUE THREAD

**Issue by txchen** [BoostIO/Boostnote#752]
Now we can press 'ctrl-e' to enter the edit mode, but I cannot find a key to exit it.
It would be nice if we can operate boostnote without keyboard, so I think it will be nice to add a shortcut key for this.

**Comment by asmsuechan** [comment]
I hope `Ctrl-w` works.

**Comment by txchen** [comment]
Thanks! Just tried.
It works when switching preview mode is `when editor blurred`, but not when `when right clicking`.
Any chance to make it work in both modes?

**Comment by asmsuechan** [comment]
Here https://github.com/BoostIO/Boostnote/pull/753.

**Comment by txchen** [comment]
super cool! Thanks a lot for the quick change 👍
