### ISSUE TITLE
[Feature request] Highlight searched keyword

### ISSUE THREAD

**Issue by melibou** [BoostIO/Boostnote#755]
Hi, 

When searching something, to highlight the keyword on the text and show a  < > sings for next and after. Additionally, to show how many times this keyword show up. 

Regards,
Meli

**Comment by BobTB** [comment]
Oh,... this note taking app also does not have this.... I had so high hopes for this. It is very hard to use if search result is not highlighted in the text.

**Comment by yahyavi** [comment]
Yes, this is a deal breaker for a note taking app.

**Comment by MakisH** [comment]
The "Find" (inside one note) highlights the terms, but the global "Search" not. Maybe a good idea would be to merge the "Search" and "Find" features. Why are they both needed?

**Comment by yahyavi** [comment]
Find does highlight but then how do you go to the next item? hitting enter writes over the selected value. Using n as in vim also doesn't work.

**Comment by sjtindell** [comment]
Bump, this would be a great feature.

**Comment by lotuc** [comment]
Currently It supports searching in md editor, but search in rendered view will be very useful, desperately need this.
