### ISSUE TITLE
Trashed items are shown in the badge of the storage

### ISSUE THREAD

**Issue by yashha** [BoostIO/Boostnote#757]
Maybe it's better to exclude the count of the trashed notes in the badge.

![screenshot from 2017-08-02 00-44-33](https://user-images.githubusercontent.com/4728786/28850373-8491d0a6-771c-11e7-83e4-ae4bc1ba26b1.png)

**Comment by asmsuechan** [comment]
I'll improve it.

**Comment by asmsuechan** [comment]
Fixed.

**Comment by kazup01** [comment]
🎉
