### ISSUE TITLE
See the storage origin of a trashed note

### ISSUE THREAD

**Issue by yashha** [BoostIO/Boostnote#758]
Maybe it is good to show the storage origin of a trashed note.
Maybe similar to a none deleted note in the top bar?

![screenshot from 2017-08-02 01-08-29](https://user-images.githubusercontent.com/4728786/28850837-31650b8e-771f-11e7-9b16-66554c862668.png)

**Comment by asmsuechan** [comment]
I dealt this request to put an information panel to `Trash`.
ref: https://github.com/BoostIO/Boostnote/pull/765

**Comment by asmsuechan** [comment]
Merged.
