### ISSUE TITLE
Better UX using select all & dialog for deleting file

### ISSUE THREAD

**Issue by Nino9614** [BoostIO/Boostnote#759]
Hello Boostnote Team, 
this is not exactly a issue but more like a suggestion. 
Do you guys considered to make all or just parts of the application not select able when the user presses ctrl+a ( not sure whats the shortcut on mac i guess cmd+a)?. Its nothing big but i think the application will have a more desktop like feel if you cant select all the text.  Also i think it would be great to have a dialog showing up (like the one in the "trash tab" but in the all notes section) where the user has to confirm that he wants to delete the file. This will also improve the UX and will prevent accidentally file deleting

**Comment by asmsuechan** [comment]
> Do you guys considered to make all or just parts of the application not select able when the user presses ctrl+a

Do you mean you don't like this situation below?
![image](https://user-images.githubusercontent.com/11307908/28957738-3deb94e8-792e-11e7-967a-37b008c21f26.png)

> the user has to confirm that he wants to delete the file

I removed the confirmation dialog box when you trash a note because it's easy. And a dialog box appears when you exactly delete a note in `Trash`.

**Comment by Nino9614** [comment]
> Do you mean you don't like this situation below?
Yes, it doesn't bother me that much and i think the most "normal" users don't care. 
But its adds more of a native like feel to the application. If you open the preferences menu for example and hit ctrl +a you see something like this.

![image](https://user-images.githubusercontent.com/27356972/28959893-b8a7eca4-78fc-11e7-98c3-012aafa5e86d.png)

In a native windows .net framework app you usually cant do that. Its a small change that is done quickly
but it adds a much better feel to the overall application

**Comment by asmsuechan** [comment]
I close this because I don't think it's important. But I don't stop you to open a PR :smile:
