### ISSUE TITLE
Application stays in process list after closing it

### ISSUE THREAD

**Issue by inclooder** [BoostIO/Boostnote#760]
I've installed boostnote recently on my Arch linux machine.
When I start boostnote from the terminal by simply writing
```bash
:~ boostnote
```
the main window pops up and everything works as expected but, when I click X to close the window something strange happens. The window dissapears and I'm not able to write anything in the terminal. Application is still running and I need to press CTRL+C to close it.
```bash
:~ ps -ef | grep [b]oostnote                  
inclood+ 18604 16964  9 21:45 pts/6    00:00:01 /usr/lib/electron/electron /usr/bin/boostnote
```

Some information about my setup
```
:~ electron -v
v1.4.16
:~ pacman -Q boostnote
boostnote 0.8.12-2
```

UPDATE:
I've found that there is special case for cinnamon inside main-window.js script.
```js
if (process.platform !== 'linux' || process.env.DESKTOP_SESSION === 'cinnamon') {
  mainWindow.on('close', function (e) {
    e.preventDefault()
    if (process.platform === 'win32') {
      mainWindow.minimize()
    } else {
      if (mainWindow.isFullScreen()) {
        mainWindow.once('leave-full-screen', function () {
          mainWindow.hide()
        })
        mainWindow.setFullScreen(false)
      } else {
        mainWindow.hide()
      }
    }
  })

  app.on('before-quit', function (e) {
    try {
      config.set('windowsize', mainWindow.getBounds())
    } catch (e) {
      // ignore any errors because an error occurs only on update
      // refs: https://github.com/BoostIO/Boostnote/issues/243
    }
    mainWindow.removeAllListeners()
  })
} else {
  app.on('window-all-closed', function () {
    app.quit()
  })
}
```
I wonder why we want to hide the main window on cinnamon :thinking:
There is a handler for `activate` event but as far as I know it only occurs on OSX (am I right?).
```js
app.on('activate', function () {
  if (mainWindow == null) return null
  mainWindow.show()
})
```
So in my case there is no way to show that window after hiding.
My naive workaround is to simply replace  `mainWindow.hide()` with `mainWindow.close()`.

**Comment by Zeustopher** [comment]
I am also running into this very thing on Linux Mint with Cinnamon. I discovered it by launching Boostnote, closing it via the 'X', then on attempting to launch the application a second time the window starts to load but then freezes without ever finishing its initialization. I wasn't able to find a way to bring back up the existing window either. Perhaps there was an attempt as some point to try and make it close to a tray icon or something but that wasn't ever implemented fully?

In either case, I'd love to see this issue fixed. Having to go and manually kill a process after each close is a little frustrating.

**Comment by ZeroX-DG** [comment]
This is fixed in the latest version.
