### ISSUE TITLE
Finder Window - UI Overlap

### ISSUE THREAD

**Issue by MrBMT** [BoostIO/Boostnote#761]
Hello,

Firstly thanks for making this, I found it a few days ago and it's great!

On macOS Sierra (10.12.6) I've noticed there's a slight layout issue with the Finder Window UI, in that the "My Storage" text is shown over the top of the "Trash". Please see attached screenshot of the issue.

Thanks!

![screen shot 2017-08-03 at 12 53 43](https://user-images.githubusercontent.com/6931281/28920956-f27b42de-784b-11e7-9292-6999ad59c857.png)

**Comment by asmsuechan** [comment]
Hi, @MrBMT. Thank you so much for becoming a user :smile:
Alright, I'll improve it.
