### ISSUE TITLE
My storage fails to update the quantity of notes after deleting. 

### ISSUE THREAD

**Issue by wonderlives** [BoostIO/Boostnote#762]
Please paste some **screenshots** with opening the developer tool if you report a bug.
<img width="497" alt="screen shot 2017-08-03 at 6 10 31 pm" src="https://user-images.githubusercontent.com/25517207/28946044-0bf2798c-7877-11e7-9b0f-4a8740bd018b.png">
After delete the notes, the number on the sidebar fails to update.

**Comment by asmsuechan** [comment]
Hi, @wonderlives. Please paste some **screenshots** with opening the **developer tool** if you report a bug.

**Comment by MrBMT** [comment]
@wonderlives Have you gone in to the Trash folder and fully deleted the notes from there?

At the moment the number of notes shown under My Storage doesn't update until they have been completely removed from the Trash, as mentioned in #757

**Comment by asmsuechan** [comment]
@MrBMT Thank you for your support. I hope this (https://github.com/BoostIO/Boostnote/pull/764) helps.
And I close this because of duplication.
