### ISSUE TITLE
Tags cut off on smaller window size 

### ISSUE THREAD

**Issue by mrseanbaines** [BoostIO/Boostnote#769]
Hi,

I've just discovered this tool after not finding anything else that I was happy to use and I think it's great!

I have, however, come across a minor issue:

When shrinking down the window width, there comes a point where the tags drop onto the next line, but they are cut off by the text area (see image attached).

![screen shot 2017-08-06 at 11 03 42](https://user-images.githubusercontent.com/24367010/29002324-7fa9cc50-7a97-11e7-860d-521d0c1de0d3.png)

**Comment by asmsuechan** [comment]
Hi, @mrseanbaines. Thank you for reporting. But this is duplicated, so I close this.
