### ISSUE TITLE
Context Menu for deleting Snippets/Markdowns

### ISSUE THREAD

**Issue by Nino9614** [BoostIO/Boostnote#770]
How about the idea to add a context menu on the items in the sidebar to be able to right click and delete the item instead of clicking the trash button in the right corner?
Its not urgent but i thinks I think this will make the deleting process much quicker.

**Comment by asmsuechan** [comment]
Hi, @Nino9614. Sorry, it existed. But I deleted it. https://github.com/BoostIO/Boostnote/pull/688
Why do you think is it useful? I think the shortcut `Ctrl-Del` is more useful than the context menu.

**Comment by Nino9614** [comment]
@asmsuechan Okay i didn't know there was such a shortcut i only tried the Del Key.
I dont know why you removed the feature because its useless. I mean if its already implemented than you can keep it for someone it may be useful or maybe the user expects this kind of feature because its works in another application. I dont think its completely useless and i dont seem to be heavy for the application

**Comment by asmsuechan** [comment]
Because I thought it was a very small feature and there were alternatives (its shortcut in this case). And it's important to refresh our code base.

**Comment by Nino9614** [comment]
@asmsuechan it was just a suggestion, because some people find it useful. If you say its a lot more going on in the background (i didn't look into the source code) than just leave it out.

**Comment by asmsuechan** [comment]
I understand what you say. Alright. I'll be more prudent next time when I hit a scene that I have to remove any feature.
