### ISSUE TITLE
[feature request] Plantuml request

### ISSUE THREAD

**Issue by PrimaMateria** [BoostIO/Boostnote#771]
I think Plantuml would fit to the context of the Boostnote. 
Once mastered we could write nice UML diagrams without leaving markdown editor.

http://plantuml.com/

**Comment by asmsuechan** [comment]
Hi, @PrimaMateria. Thank you for a great suggestion. I consider to implement it.

**Comment by asmsuechan** [comment]
FYI, you can put a uml via https://g.gravizo.com. I know it's not what you meant.
```
# UML
<img src='https://g.gravizo.com/svg?@startuml;actor User; participant "First Class" as A; participant "Second Class" as B; participant "Last Class" as C;  User -> A: DoWork; activate A;  A -> B: Create Request; activate B;  B -> C: DoWork; activate C;  C --> B: WorkDone; destroy C;  B --> A: Request Created; deactivate B;  A --> User: Done; deactivate A;  @enduml '>
```

![image](https://user-images.githubusercontent.com/11307908/29163195-abcd80b2-7df6-11e7-9316-2b6d6deb5986.png)

**Comment by asmsuechan** [comment]
And you can use `flowchart` as well (actually I even forgot it).

![image](https://user-images.githubusercontent.com/11307908/29246519-2d7f2032-8038-11e7-97e3-187d8aad18c4.png)

```flowchart
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
```

`Sequence` as well.

![image](https://user-images.githubusercontent.com/11307908/29246524-673697ba-8038-11e7-8d4b-c747a6b9520f.png)

```sequence
Title: Here is a title
A->B: Normal line
B-->C: Dashed line
C->>D: Open arrow
D-->>A: Dashed open arrow
```

**Comment by yosmoc** [comment]
@Rokt33r Is this issue still opened?

**Comment by eleijonmarck** [comment]
Not working in latest boostnote 0.1.4

**Comment by Rokt33r** [comment]
@eleijonmarck I don't see any problems in the latest version(v0.15.1). Could you try again with it? If you still have the same problem, please create a new issue.
https://github.com/BoostIO/boost-releases/releases/tag/v0.15.1

**Comment by Flexo013** [comment]
@eleijonmarck That is an issue for another repo. (This repo is for Boostnote.) The repo you need is for Boost Note.next - the beta app.

https://github.com/BoostIO/BoostNote.next/issues
