### ISSUE TITLE
Feature request: Options to save / autosave notes to an online storage / cloud storage

### ISSUE THREAD

**Issue by pfftdammitchris** [BoostIO/Boostnote#772]
It would be great to be able to have our notes synced within our cloud storage or at some custom online storage defined by the user somehow

**Comment by asmsuechan** [comment]
Hi, @pfftdammitchris. It's possible to sync your `Storage` by putting it in the directory of DropBox,  GoogleDrive or something.

**Comment by pfftdammitchris** [comment]
Nice!

_Sent from my Samsung SM-G900T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
