### ISSUE TITLE
Load user-provided js at startup

### ISSUE THREAD

**Issue by yangle** [BoostIO/Boostnote#773]
Is there an easy way to have the electron app load a user-provided script at startup? Something like `~/.config/Boostnote/custom.js`.
This could serve as a basic plugin/extension system.

Thanks for making this awesome app!

**Comment by asmsuechan** [comment]
Hi, @yangle. We're planning to implement `Plugin` system. What do you want to do by your plugin?

**Comment by yangle** [comment]
Thanks for getting back to me. That's great to hear!

I'm just trying to customize some keybindings of CodeMirror, basically calling `CodeMirror.Vim.mapCommand` and `CodeMirror.Vim.defineMotion` (see https://github.com/yangle/dotfiles/blob/master/_jupyter/custom/custom.js for an example).

Right now I'm just pasting them in the Developer Tools console every time I start the app.

**Comment by asmsuechan** [comment]
I got it. `~/.boostnotetc` will help you https://github.com/BoostIO/Boostnote/issues/302 https://github.com/BoostIO/Boostnote/pull/318 I'll re-engage it.

**Comment by yangle** [comment]
Awesome! Thank you!

**Comment by jwkicklighter** [comment]
@asmsuechan I'm confused by looking at those 2 PRs... What is the status of `~/.boostnoterc`?

Came across this issue because I'd like to be able to use CodeMirror's `map()` command to map a few custom vim keys (I can do it myself on startup through `ex mode`, but that's a pain to repeat).

**Comment by yashha** [comment]
Seems like you can do this:
```
{
  "editor": {
    "keyMap": "vim",
    "theme": "railscasts"
  },
  "execs": [
    "CodeMirror.Vim.map('jj', '<Esc>', 'insert')"
  ]
}
```
See https://github.com/BoostIO/Boostnote/pull/318

But I'm not sure if it works

**Comment by asmsuechan** [comment]
Hi, @jwkicklighter. Here's an actually merged PR for `boostnoterc`. https://github.com/BoostIO/Boostnote/pull/783

So you cannot set "exec" in `boostnoterc`. But I'm working on an implementation of Plugin now, so you'll set them in it.
