### ISSUE TITLE
A note doesn't appear on screen even though there is a corresponding file in the storage folder.

### ISSUE THREAD

**Issue by dbford** [BoostIO/Boostnote#774]
## versoin info
- OS
  - macOS Sierra 10.12.6
- Boostnote
  - Version 0.8.12 (0.8.12)

## What happened
I wrote a note yesterday. Today, though, I could not find the note on my storage.
I checked the storage folder directly and found that there was a corresponding note.
(Fortunately, I could find my important note.)

This is the screen shot.
I added a note to a storage called 'a4q project'. 
While the navigation bar(?) shows me the storage have two notes, I could only find one note.
After this problem happened, I added a note to the storage.
Then, the note correctly appeared the right area and the note count became 3.

<img width="1420" alt="screen shot 2017-08-08 at 22 24 27" src="https://user-images.githubusercontent.com/17138455/29073919-6c6cf3ae-7c88-11e7-9827-691b8efa946b.png">
<img width="1423" alt="screen shot 2017-08-08 at 22 24 47" src="https://user-images.githubusercontent.com/17138455/29073922-6dcfd482-7c88-11e7-9520-036c08e0ba8c.png">

**Comment by asmsuechan** [comment]
Hi, @dbford. Could you show me the `Console` of the developer console (I want to see errors)?

**Comment by dbford** [comment]
Hi, @asmsuechan this is a screenshot of the console.
(Maybe, this is not exactly the same error occured under the condition of previous two screen shots.)

<img width="1130" alt="screen shot 2017-08-09 at 9 29 32" src="https://user-images.githubusercontent.com/17138455/29100419-56bc3188-7ce6-11e7-9d09-44b88b77aac8.png">

**Comment by asmsuechan** [comment]
Umm, It seems it's not what I wanted. They happen sometimes and don't affect its behavior. Could you paste the exact errors, please?

Presumption from the Screenshots, there's parsing errors of CSON.

**Comment by dbford** [comment]
It seems that this issue is not the bug.
I noticed that the number of a counter doesn't decrease even if a note has deleted and moved to trash.
When I delete a note from trash,  the count decreased.

I think this behavior is so confusing for new users. So, maybe, you should change the behavior.
I prefer the number is the exactly same as the number of non-trashed notes.

**Comment by asmsuechan** [comment]
Ah, I got it. Already fixed. https://github.com/BoostIO/Boostnote/pull/764
