### ISSUE TITLE
Counter notes

### ISSUE THREAD

**Issue by juancarielo** [BoostIO/Boostnote#775]
Is counting wrong the total of notes, it also counts the deleted ones (trash), would it be a bug?

![image](https://user-images.githubusercontent.com/4699812/29094302-461446b4-7c63-11e7-962a-0ddeb8f26e1a.png)

Sorry for my English, I'm still practicing rs.

**Comment by asmsuechan** [comment]
Already fixed.
https://github.com/BoostIO/Boostnote/pull/764

**Comment by juancarielo** [comment]
Thankss!!

2017-08-08 19:49 GMT-03:00 SuenagaRyota <notifications@github.com>:
