### ISSUE TITLE
Feature request: Complex table markdown syntax

### ISSUE THREAD

**Issue by RedBug312** [BoostIO/Boostnote#778]
I think it would be better to have extended table syntax like [MultiMarkdown](http://fletcher.github.io/MultiMarkdown-4/tables), or at least just `colspan` feature.
It's commonly used for agenda tables, and I think it troublesome to write them in HTML just for `colspan`.

BTW, there seemed no related plugins in markdown-it yet.

**Comment by asmsuechan** [comment]
Hi, @RedBug312. Thank you for your suggestion. I'll consider it when a related plugin of markdown-it is released.
