### ISSUE TITLE
vertically half highlighted tab on hovering

### ISSUE THREAD

**Issue by PiratedVirus** [BoostIO/Boostnote#78]
![image](https://cloud.githubusercontent.com/assets/17083232/17599463/d511b112-601c-11e6-8071-4a8075cbc05d.png)

**Comment by PiratedVirus** [comment]
on hovering tab in snippets......

**Comment by Rokt33r** [comment]
![screen shot 2016-08-12 at 9 20 30 am](https://cloud.githubusercontent.com/assets/5865853/17609247/0aa86ce8-606e-11e6-95fc-bd180ae23f0b.png)
It will be fixed today's update
