### ISSUE TITLE
[little bug] Embedded .php code block not works.

### ISSUE THREAD

**Issue by sv-dev** [BoostIO/Boostnote#781]
Sorry for my English. 
Thank you for so wonderful snippets manager. The best one for Windows!!!

But now app has some troubles.
I have tested on Windows 10 Pro.

When I paste `php` code in markdown mode, I can't see syntax highlighting.

![php code](http://i.imgur.com/ACBN8yM.png)

After editing it looks like so

![php code](http://i.imgur.com/kqIKsi2.png)

`JavaScript` works well

![php code](http://i.imgur.com/F4mvhvv.png)

But, when I add `<?` in code block, It works.

![php code](http://i.imgur.com/5i2qhD1.png)

Another little problem is about rendering highlighted code. There are some difference between embedded code and in attached files. Brackets, signs  almost invisible, because they dark colored always in embedded code. See difference

![php code](http://i.imgur.com/vDgNzfa.png)

And this is attached .php file. Works just right

![php code](http://i.imgur.com/l6asWFk.png)

That happening even in JavaScript code.

Can you fix that?

**Comment by asmsuechan** [comment]
> I can't see syntax highlighting

I don't know why it happens now, so I'll investigate it.

> There are some difference between embedded code and in attached files

Sorry, I didn't find them. Could you specify them?

**Comment by sv-dev** [comment]
Thank you for quick response )

It all about semicolons, brackets, 

 `::`  `;` `(` `)`

![code highlight](http://i.imgur.com/2qYERut.png)

It's must be white, as I posted at the last screen in previous post.

**Comment by Flexo013** [comment]
This seems to be properly handled in the latest version of Boostnote.

If you still experience this issue, then feel free to reopen this issue or create a new one.
