### ISSUE TITLE
Boostnote switches to light theme when changing the note view

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#785]
Since the update to 0.8.13, Boostnote will switch back to the light theme when changing the note view. In other words, when clicking one of the buttons in the lower right of this interface:

![2017-08-10 16_22_16-boostnote](https://user-images.githubusercontent.com/11869704/29174946-1a8a3464-7de8-11e7-9ce6-813bcb551b5a.png)

this happens:

![2017-08-10 16_22_46-boostnote](https://user-images.githubusercontent.com/11869704/29174968-28e30de2-7de8-11e7-8d1b-8127c1d6f39c.png)

As you can imagine, this is quite uncomfortable when you are using the dark theme by default. This is on Windows 10.

**Comment by asmsuechan** [comment]
@huettenhain I'm so sorry. It's a bug. You should put `~/.boostnoterc` of which content is like below for a few days until next version will come.

```
{
    "ui": {
        "defaultNote": "ALWAYS_ASK",
        "disableDirectWrite": false,
        "theme": "dark"
    }
}
```

**Comment by asmsuechan** [comment]
Fixed
