### ISSUE TITLE
One line code blocks too large

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#786]
Using Boostnote 0.8.13 on Windows 10. However, this applies to earlier versions, I just didn't find the time to report it yet because it's just cosmetics: One line code blocks are too large.

![2017-08-10 16_27_14-boostnote](https://user-images.githubusercontent.com/11869704/29175257-d49d21a4-7de8-11e7-91a5-f6c8698aefed.png)

My guess is that it happens because the clipboard copy button requires space. It mildly disturbs my sense of aesthetics, but it's not really a bug =).

**Comment by pseigo** [comment]
I've been thinking the same thing. It's definitely the clipboard button; if you open the developer tools and delete its element, the code block is properly spaced. I guess possibilities are resizing it with 1 or 2 lines, or disabling it completely at those sizes.

**Comment by kazup01** [comment]
Hi thanks for you guys feedback. I'll fix it by the next update.

**Comment by kazup01** [comment]
I fixed it at #844. Thanks for @huettenhain your reporting!
If you guys have other layout problem, please talk to me. I will fix it.

**Comment by kazup01** [comment]
Merged. Thanks @huettenhain
