### ISSUE TITLE
[little bug] Rendering &nbsp; in code block.

### ISSUE THREAD

**Issue by kuronat** [BoostIO/Boostnote#790]
Using Boostnote 0.8.13 on macOS Sierra.

This code 

```
├── app.yaml
└── website
    ├── css
    │   ├── downloads.css
    │   ├── faq.css
    │   ├── feedback.css
    │   └── global.css
    ├── downloads
    ├── downloads.html
    ├── faq.html
    ├── favicon.ico
    ├── feedback.html
    ├── images
    │   ├── facebook.png
    │   ├── google+.png
    │   ├── logo.png
    │   └── twitter.png
    ├── index.html
    └── tutorial.html

4 directories, 15 files
```

looks like this.

![image](https://user-images.githubusercontent.com/30833423/29209752-192b374c-7ecb-11e7-964a-8a8576a7c3e4.png)

My expectation is below.

https://gist.github.com/kuronat/ca294885eb08c30e0f5132a07571ebe5

![image](https://user-images.githubusercontent.com/30833423/29209574-41347ace-7eca-11e7-8274-6648416754f5.png)

**Comment by asmsuechan** [comment]
HI, @kuronat. Thank you for reporting. I'll fix it.

**Comment by asmsuechan** [comment]
![image](https://user-images.githubusercontent.com/11307908/29482000-bc507f7e-84c3-11e7-8b3c-4fb059848569.png)

Fixed.
ref: https://github.com/BoostIO/Boostnote/pull/816

**Comment by asmsuechan** [comment]
Oops, sorry. It's not fixed in that PR.

**Comment by asmsuechan** [comment]
I reopened this issue but it's a specification of codeblock. So I close this again. Sorry!
HTML entities are not encoded as letters in a codeblock, so you should not use codeblock. So, you have to replace `&nbsp;` to space if you want to put them in the codeblock.
