### ISSUE TITLE
Building Boostnote from source on macOS results in mobileAnalyticsClient is not defined error.

### ISSUE THREAD

**Issue by MrBMT** [BoostIO/Boostnote#791]
Building Boostnote from source results in the following error:
*Uncaught ReferenceError: mobileAnalyticsClient is not defined.*

Due to this, as shown, after compilation Boostnote.app fails to load:

![screen shot 2017-08-10 at 16 46 55](https://user-images.githubusercontent.com/6931281/29179245-cde9af00-7deb-11e7-8de3-36cabe25ff14.png)

Setting "amaEnabled": false in ~/.boostnoterc allows boostnote to load e.g.

```
{
    "amaEnabled": false
}
```

![screen shot 2017-08-11 at 15 32 03](https://user-images.githubusercontent.com/6931281/29217639-4f173e1c-7eaa-11e7-866c-08de316a8806.png)

However it would be nice if we could work out what causes this so that you don't need to create a .boostnoterc file to get Boostnote to start.

Compiled as follows on macOS Sierra v10.12.6:

```
Bens-iMac:~ ben$ nvm use default
Now using node v7.10.1 (npm v4.2.0)
Bens-iMac:~ ben$ cd ~/Desktop/Boostnote-dev
Bens-iMac:Boostnote-dev ben$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 58.14s.
Bens-iMac:Boostnote-dev ben$ grunt pre-build
secret/auth_code.json is not found. CodeSigning is not available.
Running "pre-build" task

Running "compile" task
node_modules/.bin/webpack --config webpack-production.config.js
Hash: 8e6b5fa12ddfa1e151f0
Version: webpack 1.15.0
Time: 67278ms
    Asset     Size  Chunks             Chunk Names
  main.js  2.11 MB       0  [emitted]  main
finder.js  1.68 MB       1  [emitted]  finder
    + 908 hidden modules


Running "pack:osx" (pack) task
/Users/ben/Desktop/Boostnote-dev/dist
Packaging app for platform darwin x64 using electron v1.2.8

Done, without errors.
```

**Comment by asmsuechan** [comment]
HI, @MrBMT.

> Building Boostnote from source results in the following error:
Uncaught ReferenceError: mobileAnalyticsClient is not defined.

Please use `yarn run dev-start` instead of compiling it.

**Comment by MrBMT** [comment]
Running it via ```yarn run dev-start``` works fine provided you have node, npm, yarn, etc. installed on the Mac you're trying to use it on, but I'm trying to run it on some Macs that don't have a development environment set up too, so unfortunately that's not always an option.
