### ISSUE TITLE
is there a readonly mode, for the editing panel  **feature request **

### ISSUE THREAD

**Issue by ghost** [BoostIO/Boostnote#797]
for taking more advantage of the markdown, 
is there a way to review and **browse the rightmost panel in a read-only   mode**
that way we can read it without lost the markdown format???

**Comment by Iw1s** [comment]
A read-only mode would be very useful, because including something like
`<details> 
  <summary>Q1: What is the best Language in the World? </summary>
   A1: JavaScript 
</details>`
is completely useless right now. If you try to expand the details by clicking onto it, the edit mode is triggered.

**Comment by Flexo013** [comment]
Yes it exists in Boostnote currently. You have the side-by-side view and the one-panel view. The one-panel view can be locked into edit mode only. Locking the preview mode is being discussed/implemented in this issue: #2955. 

For now you can make the preview mode "more" read-only by customizing the settings.
![image](https://user-images.githubusercontent.com/4507015/61787291-c850ed00-ae0f-11e9-820b-3f047d162806.png)
