### ISSUE TITLE
In Storages Menu, long path names break folder listing display

### ISSUE THREAD

**Issue by christopher-wilson** [BoostIO/Boostnote#798]
![image](https://user-images.githubusercontent.com/4195720/29248463-894d4d62-7fde-11e7-9400-f50bc9c37242.png)

If you have path that it too long, it wraps underneath the horizontal bar, and breaks the listing of the folders.

Using Kubuntu 16.10

**Comment by asmsuechan** [comment]
Hi, @christopher-wilson. Thank you for reporting. We'll improve it.

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/BoostIO/Boostnote/pull/2412
