### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by anemochore** [BoostIO/Boostnote#8]
when i drag & dropped some .java files and .clj files, boost turns into a single-window text viewer.
ie, no edit possible and no menu cannot be selected except for help menu.
i wanted to reset the configuraion, but restarting won't do anything changed, so i had to uninstall. :(
my os is win 8.1 home 64bit. anyone having same issue?

**Comment by Rokt33r** [comment]
Oh... I'll check about it from now on. Sorry for late answering..

**Comment by Rokt33r** [comment]
It occurs every platform haha. I'll fix it and ship it on the update of tomorrow.
Thanks for your reporting! :)
