### ISSUE TITLE
Record hotkeys feature

### ISSUE THREAD

**Issue by yashha** [BoostIO/Boostnote#807]
Like https://github.com/Eugeny/terminus
![peek 2017-08-15 19-48](https://user-images.githubusercontent.com/4728786/29328455-e6eeb6f2-81f2-11e7-8332-53d444ef1c9b.gif)
Don't have to be that fancy :)

**Comment by kazup01** [comment]
Cool!

**Comment by Flexo013** [comment]
Let's continue this issue over here: #2645
