### ISSUE TITLE
Feature Request:  Font color for Markdown rendering

### ISSUE THREAD

**Issue by jolespin** [BoostIO/Boostnote#808]
Is there anyway to change font color for the markdown rendering? I've tried different UI Themes but all of them render the markdown code colors as pink with Light mode and orange in Dark mode? If not, can this feature be added in future versions?  

![image](https://user-images.githubusercontent.com/9061708/29335505-c6157ba6-81bf-11e7-8ad5-a24371c1412e.png)

**Comment by asmsuechan** [comment]
Hi, @jolespin. Did you specify `shell` or something in the codeblock?

![image](https://user-images.githubusercontent.com/11307908/29340593-c662dc66-825a-11e7-935d-7a4fffbe3ad2.png)


![image](https://user-images.githubusercontent.com/11307908/29340588-c1720d12-825a-11e7-819a-b7159b192997.png)

**Comment by jolespin** [comment]
No, I don't think so.  Check it out: 

![image](https://user-images.githubusercontent.com/9061708/29342086-896523a0-81dd-11e7-862b-816fd01e2ef9.png)

**Comment by asmsuechan** [comment]
What do you mean 'I don't think so'? I guess you want to colorize your codeblocks, so I said you can set syntax highlight in my previous comment. Or do you want to just change the font color in codeblocks?

**Comment by jolespin** [comment]
Sorry, I was confused on what you were asking.  I thought you were asking if I added that or something similar which changed my coloring scheme.  I've added ```shell and it looks better.

**Comment by asmsuechan** [comment]
Hmm, sorry. I'm still not sure what you are getting at. But I want to help you, so do you mind if I ask you to explain it from the beginning?

**Comment by MrBMT** [comment]
@asmsuechan my understanding of what they were saying, is that they want the option to change the default font color in code blocks for the text.

e.g. When using the 'Light' UI theme, they want to be able to change the code block text from the pink to a colour of their choice.

So basically adding a setting to change this color code for the Markdown Preview:

```
code {
    color: #CC305F;
}
```

**Comment by kazup01** [comment]
Hi @jolespin , check #899. I change font color to like gfm.
