### ISSUE TITLE
%{hex code} seems to print awkward characters

### ISSUE THREAD

**Issue by shuntaroy** [BoostIO/Boostnote#809]
When I input "%FC", I face this issue.
That is, some of hex codes following `%` print unexpected characters.
See figures below.

![screen shot 2017-08-16 at 13 44 51](https://user-images.githubusercontent.com/6918169/29347659-1fe8f7b0-8289-11e7-97b9-68b8d3fa4fa9.png)
![screen shot 2017-08-16 at 13 44 44](https://user-images.githubusercontent.com/6918169/29347660-1fe932ac-8289-11e7-93eb-964f74d9b104.png)

Due to this issue, I could not write `%FC` strings in my notes which are about the possible argument format of a CLI command.

**Comment by huettenhain** [comment]
Duplicate: #746, but this bug report is much more descriptive than mine, so we might want to close #746.

**Comment by shuntaroy** [comment]
@huettenhain Oops, so sorry for the duplication.
I should have checked known issues more carefully...
Thanks for responding and I hope it'll be fixed.

**Comment by asmsuechan** [comment]
@shuntaroy  Thank you for reporting. Fixed.
