### ISSUE TITLE
Import menu not present in Ubuntu

### ISSUE THREAD

**Issue by francesmothrock** [BoostIO/Boostnote#810]
I can't access any equivalent of the File menu to import or export files. I have access to the preferences pane, but that doesn't have the same options. I see the options I'm looking for in the Mac version, but Linux doesn't have the same menu layout in the UI. Is it hiding from me or is it just not fully adapted to Linux? (Otherwise it works fine.)

I'm on Ubuntu Mate 17.04. 

![screenshot at 2017-08-16 07-46-26](https://user-images.githubusercontent.com/15382674/29369282-084bbcc8-8257-11e7-99a7-867661d0f6e2.png)

**Comment by yashha** [comment]
I think there is no import menu in the UI atm.
You can access the import in the application menu, it reveals when you hit alt. 
At least on my Ubuntu Gnome 16.04.

**Comment by francesmothrock** [comment]
Well, what do you know. I guess I didn't know that was a thing. I might go looking for a way to show the menu by default, but that's nothing to do with Boostnote. 
Thank you!
