### ISSUE TITLE
Highliting lines of code

### ISSUE THREAD

**Issue by danielepolencic** [BoostIO/Boostnote#814]
Is it possible to highlight lines of code like in Deckset: https://docs.decksetapp.com/English.lproj/Formatting/06-code-blocks.html ?

```
```javascript, [.highlight: 2]
$.ajax({
  url: "/api/getWeather",
  data: {
    zipcode: 97201
  },
  success: function( data ) {
    $( "#weather-temp" ).html( "" + data + " degrees" );
  }
});
```

![image](https://user-images.githubusercontent.com/1130499/29479957-f4657894-846c-11e7-9de4-7e2c0d23430b.png)

**Comment by asmsuechan** [comment]
HI, @danielepolencic. For now, you can add your own theme by yourself in this way 
https://github.com/BoostIO/Boostnote/issues/200#issuecomment-271854423

I'm going to implement custom theme feature in a few months along with plugin feature.
