### ISSUE TITLE
Sub-note Request

### ISSUE THREAD

**Issue by jhanna01** [BoostIO/Boostnote#819]
Would it be possible to add some sort of improved file structure?
Currently the structure only goes one level deep:
```
-)Storage
    |-> Note
```
For organization purposes, I find it necessary to have the ability to make sub-levels, e.g.
```
-)Storage
    |-) Sub-storage1
      |-> Note
    |-> Note
```
It could also work with:
```
-)Storage
    |-> Note
    |-> Note2
        |-> Sub-note
```

**Comment by asmsuechan** [comment]
Hi, @jhanna01. thanks for good suggestion! We're contemplating the data structure issue. However, there are some difficult problems, thus we'll take a while to modify the data structure.

**Comment by asmsuechan** [comment]
FYI, you can create markdown tabs on a snippet note.
![4f2fdacfa45942b9602a575b023dbfed](https://user-images.githubusercontent.com/11307908/29515025-a12e6b14-86a5-11e7-809d-b6aab9ed2cd0.gif)

It's a kind of nested in some way.

**Comment by Flexo013** [comment]
This issue will be continued in #2263. As that seems to be the more popular solution of the two that you offered.
