### ISSUE TITLE
Fixing search term does not display proper results

### ISSUE THREAD

**Issue by pradeepvrd** [BoostIO/Boostnote#822]
When I search for a note and if I enter the search incorrectly the first time, the results are not updated until I completely clear the search box and re-enter the search term.

For instance, Searching for **git** gives me the following results
<img src="https://user-images.githubusercontent.com/23413404/29532291-3f34ea26-8661-11e7-868e-25d7edfa8eef.png" width="50%">

But if i mistype it to **gita** does not give any results.
<img src="https://user-images.githubusercontent.com/23413404/29532325-6bc1dafe-8661-11e7-8ea3-1b9767295138.png" width="50%">

Now if I correct my search term to **git** no results show up. The only way I can search again is by completely clearing the search box and typing the term again.
<img src="https://user-images.githubusercontent.com/23413404/29532348-8a66e17a-8661-11e7-8556-7bad7e50a885.png" width="50%">

**Comment by asmsuechan** [comment]
duplicated: https://github.com/BoostIO/Boostnote/issues/799
