### ISSUE TITLE
Link to note in another folder

### ISSUE THREAD

**Issue by wtty** [BoostIO/Boostnote#823]
I see you can link to another note in the same folder which is nice. But is it also possible to link to another note in a different folder? What about linking to a note in different folder that's in a different storage? If so, how?

**Comment by asmsuechan** [comment]
Hi, @wtty. It's not possible now. And it takes quite a time if I implement it.

**Comment by bets** [comment]
@wtty  I'v noticed that while I am in "All Notes" clicking a link will bring me to notes in other folders too.

**Comment by kazup01** [comment]
This bug was fixed yet. Thanks for your report.
