### ISSUE TITLE
Feature Request: Changed h1-h6 font size

### ISSUE THREAD

**Issue by Alaev** [BoostIO/Boostnote#824]
Feature Request:

Able to change the font size of h1-h6. 
At the moment h1 is too large, would be great if there was an option to change the CSS of h1-h6 to make them smaller and etc..

Also would be great to have an option to highlight a word with ``` ::Word:: ``` the way bear app allows you.

**Comment by asmsuechan** [comment]
Hi, @Alaev. Thanks for your suggestion. I'll manage to implement customizing theme somehow in near future. Look forward to it!

duplicated:
https://github.com/BoostIO/Boostnote/issues/184
https://github.com/BoostIO/Boostnote/issues/591

**Comment by Alaev** [comment]
@asmsuechan Thanks for the quick reply. Didn't see issue created for the font sizes (did a search only for the font size) Looking forwards for this one; TY.
