### ISSUE TITLE
Incorrect behavior of nested markdown blockquotes

### ISSUE THREAD

**Issue by BAKFR** [BoostIO/Boostnote#825]
When using nested blockquotes, all lines after a second-level quote are considered second-level even if they are not.

An example:

```markdown
> Level 1
>> Level 2
> Level 1

> Level 1
> > Level 2
> Level 1
```

The third lines should be displayed has part of the first level of the quote. However, it's not the case:

![screenshot 2017-08-23 12-46-31](https://user-images.githubusercontent.com/1631475/29612515-f8f6f692-8801-11e7-959b-c1ea31cd81da.png)

**Comment by asmsuechan** [comment]
Hi, @BAKFR. I assume it's not Boostnote's issue. markdown-it's issue.
https://github.com/markdown-it/markdown-it

https://markdown-it.github.io/

![image](https://user-images.githubusercontent.com/11307908/29614859-cdc896ca-8846-11e7-929c-f6a26e79c218.png)

**Comment by Alaev** [comment]
@BAKFR 
> Level 1
>> Level 2
> Level 1

Git hub works the same as boostnote; however, you can do the following:
> Level 1
>> Level 2

> Level 1

Add break line after level 2 not perfect but works.
```
> Level 1
>> Level 2

> Level 1
```
