### ISSUE TITLE
When in vim mode, typing :w<Enter> means nothing.

### ISSUE THREAD

**Issue by KuangLei** [BoostIO/Boostnote#832]
I hope that in vim mode, `:w<Enter>`, `:q<Enter>`, `:wq<Enter>` should have the same function as pressing `Ctrl-s`.  

Thanks.

**Comment by asmsuechan** [comment]
Hi, @KuangLei. Boostnote doesn't have `save` function. It saves a note automatically when you edit it. So I don't feel like I implement the features.

**Comment by KuangLei** [comment]
Now `:w<Enter>` returns nothing, and `:q<Enter>` or `:wq<Enter>` returns "Not an editor command".  

So, I hope `:w<Enter>`, `:q<Enter>`, `:wq<Enter>` could have the function of exiting edit mode and going back to view mode, just like pressing `Ctrl-s`.  

Thanks.

**Comment by KuangLei** [comment]
#883

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/pull/885
