### ISSUE TITLE
[Feature Request] Provide option to change Selection color for dark schemes

### ISSUE THREAD

**Issue by prat0318** [BoostIO/Boostnote#833]
In all the dark themes (except one - night) it is hard to tell what text has been selected by mouse. The feature request is to either make the selection color a bit lighter or an option for an user. Certainly, option 1 of making selection color lighter will be the easiest fix.

**Comment by kazup01** [comment]
Hi @prat0318, thanks for your request!
I think that your suggestion is absolutely right. Could you fix this?

**Comment by DennyScott** [comment]
@kazup01 How would you like to see this done? Currently the css is loaded from the code mirror node module, so I can't alter the css itself. I could manually change the selection color in if that theme is selected, or create a "boostnote" night css, but both of those feel a bit odd. 

The other option is having an option for the user when selecting themes, but being the only adjustable value is a bit odd too. Which way would you like to see this goin?

**Comment by Flexo013** [comment]
I will close this issue for now as you can add your own custom css from the preferences.

@prat0318 If you feel like something more has to happen with this issue, then feel free to reopen/recreate an issue.
