### ISSUE TITLE
Note key generation question

### ISSUE THREAD

**Issue by ScottDillman** [BoostIO/Boostnote#843]
I have been enjoying boostnote and recently decided to use a git repo to store my notes for backup and versioning, and also to work on separate systems. This seems to work except that the links between notes do not work. Looking at the "Note Link" property using the "i" button shows the document keys are different on different systems. I was wondering how that key is generated? Is it a hash of the path to the document? It would be great if links between notes in a folder could be preserved across systems.

**Comment by asmsuechan** [comment]
> how that key is generated?

The key is a combination of `Storage key` and `Note key`.
If you want more information, please grep `keygen`.
https://github.com/BoostIO/Boostnote/blob/master/browser/lib/keygen.js

>  Is it a hash of the path to the document?

Yes.

> It would be great if links between notes in a folder could be preserved across systems.

It's a bug. The storage key is not same among different machines. I'll fix it.

**Comment by CTrauma** [comment]
excellent.. thanks for the quick response..
