### ISSUE TITLE
Finder UX

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#85]
<img width="993" alt="screen shot 2016-08-15 at 9 34 47 pm" src="https://cloud.githubusercontent.com/assets/5865853/17687147/94c11cbc-63ad-11e6-9c01-400b417a9686.png">
Boostnote app provide finder window which make you can find your note much faster.

Currently, the searcing fucntion only match title. After refactoring redux reducer, we'll provide quick categorizing(by tag) option and other.

Check the detail below. If you have better idea, please comment this issue to improve Boostnote app.
## Name

I don't think the name is good beause the name of  file system manager of OSX is also 'Finder'.

Please recommend new name of Finder window.

Candidates
- [EVA](https://en.wikipedia.org/wiki/Extravehicular_activity)
## Command

Like the flags of Unix system, I'm going to provide these flags, `-f`(by folder) `-s` (by storage) `#` (by tag).

| flag | description |
| --- | --- |
| -s {STORAGE_NAME} | specific storage |
| -f {FOLDER_NAME} | specific folder |
| -c | content search |
| #{TAG} | specific tag |
| -r | RegExp match |
- Default search behaviour is searching title only with fuzzy search.
- When searching by multiple flags of `-s` and `-f`, the result will be an unified set of the results of each flag.
- When searching by multiple tags, the result will be filtered by both tags.
- By `-c`, the result search by content with default match method(Keyword will be RegEx-escaped).
- By `-rc` or `-cr`, the result search by content with default match method(Keyword will be parsed by RegExp).

> The result of `-s abc -f def #qwer #wer` will be notes in `abc` storage or `def` folder(of unspecific storage) with `qwer` and `wer` tags

~~This feature will be shipped to v0.6.4.~~

Or the style of slack are also a valid option

<img width="388" alt="screen shot 2016-08-19 at 9 37 30 am" src="https://cloud.githubusercontent.com/assets/5865853/17795241/bbeb86e2-65f1-11e6-8ae3-bcb1ab9b95fa.png">

| flag | description |
| --- | --- |
| storage:{STORAGE_NAME} | specific storage |
| folder:{FOLDER_NAME} | specific folder |
| in:{STORAGE_NAME}/{FOLDER_NAME} | specific folder(another option) |
| #{TAG} | specific tag |

> This command set is not completed yet

And, we might be able to provide both styles of Shell flag and Slack modifier.
## More behaviour

Copy the snippet to clipboard is not so bad. But, we need more option.
## Disable option

On OSX, Boostnote app spawn another electron process to provide better UX.

> User can open Finder window while editing on other apps, by this approach, Boostnote can focus back the previous app.

But, it has a side effect that we have to keep 4 processes(Main process, Main window renderer, Finder process, Finder window process)

> On Windows and Linux(with Cinnamon), the app Main process, Main window renderer, Finder window process)
## Tray menu

`quick note` will be available soon.
https://blogassets.evernote.com/wp-content/uploads/2013/03/feat_quick.png

@brpaz, @facundomedica Please comment this issue. I'm going to reflect your own needs. I actually barely use this feature. I think that you might have much better idea than mine.

**Comment by Rokt33r** [comment]
I added a candidate of new name, EVA. 
https://en.wikipedia.org/wiki/Extravehicular_activity

I think this concept is quite interesting and suits the name of app.

**Comment by Rokt33r** [comment]
Command section has been updated.

**Comment by brpaz** [comment]
When i thought about the menubar, the idea was to copy the implementation of Snippets Lab.
I was more interested on the search part, but finder have improved a lot, since then so I am not sure if its that important.

Still some people might prefer to use the menubar instead of finder as a simpler and quicker way to search.

* https://www.renfei.org/snippets-lab/images/Landing/osx-1.4/assistant-new.png
* https://www.renfei.org/snippets-lab/images/Landing/osx-1.4/assistant-search.png

**Comment by Rokt33r** [comment]
@brpaz 
Okay.
I'll imitate the menubar app, which can do both writing and searching a note, and replace the current Finder with it.

It would be confusing if there are more than 2 popup windows.

**Comment by kazup01** [comment]
I close this because this issue has been left untouched.
