### ISSUE TITLE
ctrl+f for search and ctrl + shift + f for global search

### ISSUE THREAD

**Issue by aizigao** [BoostIO/Boostnote#850]
any plan add search by content text ?

**Comment by kazup01** [comment]
You can use context search after v0.8.12.

<img width="713" alt="screen shot 0029-09-08 at 1 37 48 am" src="https://user-images.githubusercontent.com/8602615/30174521-5a919f20-9436-11e7-896a-4568ed8e6845.png">

**Comment by aizigao** [comment]
oh my god，dark theme making me had ignored this
