### ISSUE TITLE
Storage on Mac disk image becomes out of sync if unmounted

### ISSUE THREAD

**Issue by b0urb0n** [BoostIO/Boostnote#851]
This issue occurs when the device that the Storage is linked to becomes unavailable in the middle of a note-taking session.  I work out of an encrypted disk image that I keep mounted throughout the day

* If I eject the volume and leave Boostnote open and make some changes it doesn't complain
* Re-mounting the disk image causes nothing to complain
* Closing and re-opening Boostnote after all the above causes Storages to disappear as in #327 and the Storages are unable to be recovered.  (I've had copy-paste out of the old files into a new Storage, folder, notes once running `localStorages.clear()` and re-loading Boostnote)

**Comment by fredleger** [comment]
same here. macosx high sierra

**Comment by Flexo013** [comment]
@b0urb0n Are you still having this issue?

**Comment by b0urb0n** [comment]
With the latest release, I am no longer experiencing the issue above!
