### ISSUE TITLE
Can anyone tell me where are tags on OSX?

### ISSUE THREAD

**Issue by bencolder** [BoostIO/Boostnote#854]
I can create tags no problem, but where can I access them? On the side pane there's only all notes and folders I created. Where are the tags?

**Comment by asmsuechan** [comment]
Hi, @bencolder.
You can search by the tag.
![image](https://user-images.githubusercontent.com/11307908/30236195-234d49aa-954f-11e7-85ab-b44637c34740.png)

**Comment by bencolder** [comment]
Great thanks! Now time to import notes from Evernote.

**Comment by bencolder** [comment]
Hi, @asmsuechan 
Just a quick follow up. I found out when you do a search for tags, it will filter out **all the notes** with that keyword not just specific to the tags. Would be nice if I could just search '#php' for notes that are tagged '*php*' so I can be sure the notes are what I am looking for.

**Comment by kazup01** [comment]
Hi @bencolder, we should improve tag features. Please check #519

**Comment by escobar5** [comment]
@asmsuechan why do you have those items below Trash? those are tags? I don't see it in my version, all I see are "All notes", "Starred" and "Trash"

**Comment by kazup01** [comment]
Hi @escobar5 , 
These are Folders, not Tags. You can make these. 
<img width="512" alt="screen shot 0029-09-14 at 8 46 36 pm" src="https://user-images.githubusercontent.com/8602615/30428274-e8fb7ffe-998d-11e7-8a0f-271056ea7618.png">

**Comment by fladd** [comment]
Some observations:

1. Searching for tags does **not** work for me. I have a tag called #NF, I search for #NF, and no notes are found. How do you search for tags? Is there a special syntax? Is this documented somewhere?

2. @kazup01 How did you manage to create folders outside of a storage? I only seem to be able to have folders inside storage (like the last two in your screenshot).

**Comment by kazup01** [comment]
Hi @fladd , you can create Folders inside Storage not outside.

**Comment by fladd** [comment]
@kazup01 That was my understanding, too. But in @asmsuechan 's screenshot, there is only one Storage ("Boostnote"), and most of your Folders are **not** inside of this Storage. Hence, I was wondering (and apparently so was @escobar5 ), how he managed to move them to this position.

**Comment by kazup01** [comment]
@fladd I understood. The folders you said also belongs to something Storage, but it is not visible in asmsuechan's image (can visible if scrolling up). 
<img width="790" alt="screen shot 0029-09-24 at 12 44 57 pm" src="https://user-images.githubusercontent.com/8602615/30779252-c0f5b574-a126-11e7-869a-1c68e431e516.png">

**Comment by vansteki** [comment]
1. Searching for tags of snippets are not worked for me.
2. Searching tags are not worked in Toggle Finder(popup).

Boostnote Version 0.8.15

![image](https://user-images.githubusercontent.com/1705361/31006545-a9153ad4-a4c2-11e7-8fa8-5da25ff6455f.png)

![image](https://user-images.githubusercontent.com/1705361/31006561-bfda6802-a4c2-11e7-9fbb-42de0ebef052.png)

Mac OS Version:
![image](https://user-images.githubusercontent.com/1705361/31000794-fc4e068c-a4a3-11e7-874b-3593962b0420.png)

**Comment by kazup01** [comment]
Hi guys, @sosukesuzuki is implementing the [Tag Filtering Feature](https://github.com/BoostIO/Boostnote/pull/922) like below image.
We will update it at Next Saturday.
![tag-area-image](https://user-images.githubusercontent.com/8602615/31044573-e425f4f6-a60c-11e7-9880-80df035b7f3a.png)

**Comment by kazup01** [comment]
This feature will be released in this week! Enjoy Boostnote!
https://github.com/BoostIO/Boostnote/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Next+Release%22
