### ISSUE TITLE
empty search result until clear search field

### ISSUE THREAD

**Issue by Sild** [BoostIO/Boostnote#855]
If I make any mistake in search, I must clear search field to get any result.
And I have no result if I just fix a mistake
![image](https://user-images.githubusercontent.com/1629069/30279811-e0b53368-9716-11e7-801a-df1bb1f7b480.png)
![image](https://user-images.githubusercontent.com/1629069/30279815-e3f868d8-9716-11e7-86ed-63dc0e3b4037.png)
![image](https://user-images.githubusercontent.com/1629069/30279820-e6c2a6f0-9716-11e7-958d-5759a4a392bb.png)

Execuse me if this issue already exists. I try to find something similar without any success.

Also I'm able to help with issue if you direct me to appropriate code)

**Comment by kazup01** [comment]
Hi @Sild , thanks for your reporting! This is a bug as you said. Could you fix it and send to us PR? Thanks.

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/pull/954
