### ISSUE TITLE
Too many different ways to search with different scopes ! Why?

### ISSUE THREAD

**Issue by BobTB** [BoostIO/Boostnote#856]
Am I doing something wrong or is this really so? Boostnote doesn't do a full text search through all the notes, it just outputs the search results from note titles.  How can this be a useful for a note taking app? 

There are two major things a note taking app should do:

1. Save the text entered 
2. Search the text entered 

Everything else is just fluff.

**Comment by Sild** [comment]
I can't confirm it
![image](https://user-images.githubusercontent.com/1629069/30315105-8e7d01c6-97ab-11e7-99e2-eb0c37c793b9.png)
![image](https://user-images.githubusercontent.com/1629069/30315113-93ade070-97ab-11e7-8740-cda99179c5f8.png)

**Comment by BobTB** [comment]
Ok, now I know exactly what is wrong. It does not search code snippets, which is quite a problem, how am I supposed to find something in the notes if it is in the snippet?

**Comment by asmsuechan** [comment]
Hi, @BobTB. Please use `Finder`. Please check the hotkey at `Preferences` -> `Hotkey`.

**Comment by BobTB** [comment]
Ok, I know there is Finder, but how can I find the note which has the string in snippet I am looking for in the first place? I have to click through all and every note and then search for the string in finder? There should be a global scope search box and not two searches with different scopes. This is almost useless for me, and I believe for many other users too. Fix that and Boostnote will have a lot more users :)

**Comment by BobTB** [comment]
Actually there are three ways to search:
-a regular search box
-a 'finder' search 
-and a Search box in Editor mode

All three should be combined in just one search box!

**Comment by Sild** [comment]
For example, I don't want to see "search box in edit mode" in finder. They solve totally different tasks.

**Comment by BobTB** [comment]
Check out simplenote, one search finds everything, simple and great.

**Comment by BobTB** [comment]
I really tried now for three days, but this search functionality as now is not useful at all, it is a hinderance instead of help. I have a specific text in a code snippet. I just can not find the note in which this snippet with the text is. I can not find a way of doing it. Sadly I have to use something else, these three different ways of searching for the *same* thing is really a major setback.

**Comment by huettenhain** [comment]
While I am not quite as annoyed by it as @BobTB is, I do feel that the search capabilities of Boostnote could need some improvement. For example, the (global) search/replace in Visual Studio Code is a good example of what I would find appealing. However, it's important not to forget that this is a free and open source project, so noone's stopping us (other than our own priorities) from implementing this ourselves. So far the devs have been nothing but kind and zealous to fulfill our wishes, I am really grateful for that.

**Comment by yahyavi** [comment]
Yes, this is the most frustrating thing about this app, everything else is actually pretty good, but a note taking app needs proper search! 
@kazup01 this is a good app but please make fixing search and unifying all different searches a priority. I think VS Code or sublime are good examples to follow.

**Comment by BobTB** [comment]
Exactly my thoughts! It very hard to use as it is now.

**Comment by Trewlany01** [comment]
I think your comments are valid regarding the different search functionalities, because while they are implemented, search can be frustrating.

The search below seems to only search based on document titles and not actual note content, so this can be frustrating. Would be nice to see additional functionality for search implemented, even find and replace such as sublime/atom editors have, or move to next instance of found word in current found document
![search functionality](https://user-images.githubusercontent.com/32272737/31770058-76e50f86-b493-11e7-98d2-74f65cdb57cf.png)

However using the search functionality you can search note/code snippet content as seen below:
![basic search](https://user-images.githubusercontent.com/32272737/31770273-47dc7e12-b494-11e7-997f-3dd6e3fc947b.JPG)

You can see my example above that boostnote simply finds documents with your string in them.
I think boostnote can be improved tremendously by adding feature to move to next instance of found word in document or even highlight found word as my picture below suggests:

![basic search](https://user-images.githubusercontent.com/32272737/31770354-bba8bd2e-b494-11e7-941b-d400453058c2.JPG)

**Comment by nfaction** [comment]
The search does work fairly well, however it does not show search results inside the actual note. The finder is very difficult to use in that I have not been able to use it without crashing, etc.

A ctrl+f inside the note would be extremely useful when in preview. I use vim mode, and can use / to search, which does work, but often I don't want to have to switch to edit mode to search...

**Comment by ericchase** [comment]
Any reason this hasn't been fixed yet? Without being able to search all my notes at once, there's absolutely no reason to use BoostNote over something else (ie. OneNote).

**Comment by chansey97** [comment]
Hi @asmsuechan,
How to find Finder? I checked the hotkey at Preferences -> Hotkey.
There is only one option:
Show/Hide Boostnote Super + Alt + E
Nothing else...
![capture](https://user-images.githubusercontent.com/4015056/36974603-21b3aa8e-206f-11e8-9984-d0ffc6df52b2.PNG)

**Comment by Rokt33r** [comment]
@chansey97 We discarded it. #1497 But, we're going to bring it back. #1503

**Comment by yahyavi** [comment]
Is there a way to jump to the next highlighted search keywords in the **markdown editor search**?

It finds and highlights the string but changes focus to the highlighted keyword in the editor so if you press enter or _n_ (as vim) it replaces highlighted work with enter or _n_. 

@Rokt33r we appreciate the work on the app but lack of progress on search has been very frustrating. This is the most important feature of the app!

**Comment by Rokt33r** [comment]
> Is there a way to jump to the next highlighted search keywords in the markdown editor search?

There isn't. We need to implement it. Could you create a new issue about this? Then, we could track 
 the progress and introduce it much faster.

**Comment by yahyavi** [comment]
@Rokt33r Done! [#1813](https://github.com/BoostIO/Boostnote/issues/1813)

**Comment by Flexo013** [comment]
Currently this has been brought down to two ways of searching:

1) The Search at the top of the note list. This one should be sufficient in almost all cases. All issues brought up in this thread no longer seem to be present.

2) <kbd>Ctrl</kbd> + <kbd>F</kbd> when inside a note. This will open a specific search, with the added feature of supporting regex. In the future this particular searcher will also allow you to go to the next or previous occurrence of your search query. See #1813
