### ISSUE TITLE
Finder/Search popup text select

### ISSUE THREAD

**Issue by foorb** [BoostIO/Boostnote#858]
Hi, first of all - thank you for Boostnote. I really enjoy it. 

But I have a problem with the finder search popup. 
When you select text in a note without having searched - everything is fine. 
But when you try to select text in a note you have searched before it jumps back to the first note.

I hope everyone understands what I mean.

![ezgif-4-5c973983b6](https://user-images.githubusercontent.com/14993807/30322201-edadfcec-97b8-11e7-916b-f065c9aed3bb.gif)

**Comment by vovanmix** [comment]
+1, I also have this issue! Any idea how soon it can be fixed?

**Comment by foorb** [comment]
Any further information I can provide to help you fixing this?

**Comment by dreadful44** [comment]
I search in bar. And it found but i want to edit this. I dont know how can do that. I try double click, right click. Non of this work. Maybe right click menu and show main window or edit  on the result list, will be great.

**Comment by kazup01** [comment]
Hey guys, since we discard the Finder feature at v0.9.0 because this feature used very rarely, so I close this issue.
[v0.9.0 Release Note](https://medium.com/boostnote/boostnote-v0-9-0-release-5a376e21b625)

If you need, please feel free to talk to us. 
Thank you!
