### ISSUE TITLE
Please add configuration option to use a button to enter edit mode instead of clicking

### ISSUE THREAD

**Issue by Scott-MacD** [BoostIO/Boostnote#860]
It would be really appreciated if there could be a toggle option to enter edit mode for markdown documents instead of it automatically entering edit mode every time you click. Currently it makes it impossible to use the mouse to copy formatted text from the preview area and paste elsewhere.

**Comment by asmsuechan** [comment]
`Right click mode` helps you.

**Comment by Scott-MacD** [comment]
I wrongfully made an assumption and misunderstood this option, my apologies. I did try this and must have forgot to save my settings, and then assumed it was only affecting going from edit mode to preview mode, and not vice versa.

Thank you.
