### ISSUE TITLE
Is there any plan to develop an ipad app?

### ISSUE THREAD

**Issue by czlhs** [BoostIO/Boostnote#863]
I prefer to read and modify note in ipad rather than in mobile phone...

**Comment by kazup01** [comment]
Yes we will make iPad app at sometime soon!
Boostnote mobile's repository is here. https://github.com/BoostIO/boostnote-mobile

**Comment by kazup01** [comment]
Hi @czlhs , iPad app is waiting for review!
<img width="669" alt="screen shot 0029-09-24 at 12 03 43 pm" src="https://user-images.githubusercontent.com/8602615/30779071-7903a4ac-a120-11e7-8785-8ce20bced708.png">

**Comment by kazup01** [comment]
iPad app is released!
![s__3481602](https://user-images.githubusercontent.com/8602615/30841791-1111dc2a-a2b9-11e7-8566-98e9a3b60bb0.jpg)

**Comment by kazup01** [comment]
Enjoy👍
