### ISSUE TITLE
Adding salt from plantUML

### ISSUE THREAD

**Issue by fraygos** [BoostIO/Boostnote#865]
Is it possible to add salt for GUI design?
http://plantuml.com/salt
![image](https://user-images.githubusercontent.com/12282501/30491550-7f5adb20-99f2-11e7-8517-a5e8fc73959b.png)

**Comment by asmsuechan** [comment]
Check this issue https://github.com/BoostIO/Boostnote/issues/771

**Comment by asmsuechan** [comment]
Are you happy? If so, please close this, if not, please explain what you want.
