### ISSUE TITLE
Close to tray menu

### ISSUE THREAD

**Issue by zaknight** [BoostIO/Boostnote#868]
Please! When I select "Close window" or close. How to hide the Boostnote from the Taskbar and only a small icon to tray menu.

![image](https://user-images.githubusercontent.com/8871846/30521659-4b52adba-9bed-11e7-90d6-0bc0e8b7a08e.png)

**Comment by kazup01** [comment]
Please check it. https://github.com/BoostIO/Boostnote/pull/1043
Thank you for your waiting!
