### ISSUE TITLE
In code edit mode, cursor is disconnected from text

### ISSUE THREAD

**Issue by pcampbell-software** [BoostIO/Boostnote#87]
When in edit mode, the cursor appears to be disconnected from where the text is being placed. See this animation to demonstrate. This gets worse (the space larger) the more text you type.

![cursor disconnected](https://cloud.githubusercontent.com/assets/17199516/17724288/71fbf8e8-6473-11e6-8eb9-5bf2f3d97c12.gif)

**Comment by Rokt33r** [comment]
Ace renders the content by the width of a random char. You should use monospaced font. #39 
It might be better after we switch the editor with Codemirror.
Sorry for making you confused. 😢

**Comment by pcampbell-software** [comment]
Ah thanks; sorry I hadn't realised I'd set a regular font for the code editor. All OK :)
