### ISSUE TITLE
MD keys >> unwanted space (probably autocorrect)

### ISSUE THREAD

**Issue by dgoosens** [BoostIO/Boostnote#871]
HI,

Just tested the new **MD keys** in the mobile app.  
Great improvement

But... when hitting the dash (\#) key, the editor automatically adds a whitespace...  
Hence I have to backspace before hitting the dash a second time...

I'm kind a guessing this is due to autocorrect...  
But you guys are much smarter than I am

This is rather annoying though

dGo

**Comment by asmsuechan** [comment]
Here's not the mobile repo. Please reopen on there.
https://github.com/BoostIO/boostnote-mobile
