### ISSUE TITLE
Scrolling in window doesn't work

### ISSUE THREAD

**Issue by s777s** [BoostIO/Boostnote#873]
Hello! I am a new user, thank you for your tool? it looks interesting!
I try it on the latest Arch (KWin+LXQT). I can succesfully scroll code inside of note during editing by arrows on my keyboard or whell of a mouse. But the only way for me to scroll for example Menu -> UI, is to press mouse button and start to select till down of the page. Mouse wheel/Arrow keys/Scroll bar - noting works. The same story in the main window of a note.
And I think, that when I click on the text of a note first time, I sould be able to scroll compiled page with arrows/mouse, and in case of double click - edit it, but its more like very small feature request...

**Comment by s777s** [comment]
And I've seen on you screenshot the posibility to choose markdown. How could it be achieved? I want tou use the PHP code. When I right click anywhere - nothing happens. And I was unable to find that feature in any menu...

**Comment by asmsuechan** [comment]
> double click
Good idea. I'll implement it.

Is this?
![image](https://user-images.githubusercontent.com/11307908/30570485-894b5ace-9d1c-11e7-8a84-aeff551092f2.png)

**Comment by s777s** [comment]
Sorry for the late answer, I was on journey. Yes, On 1st screenshot you can see, that I don't have such menu. Or is it your notes? Anyway, when I right click on any place in a page, I don't have expected behavoir - even simple copy/past menu. Only small grey rounded square appears in code window for a split second. I've noticed, that when adding php files as snippet, markdown works correctly and great. But I'm unable to add it in may note window and bash too :(
May be I'm doing something wrong (there is not any help files), but when trying _```php_ or _```bash_,
I don't get formatted code.

Especially installed Boostnote on my second computer with clean Arch+Kde plasma installation (second screenshot) and have the same behavior with scrolling. Firstly I can click on scrollbar, but when it lost focus 1st time - never works again in any window until the program restart. I usually use arrows on keyboard and don't use scrollbar, but they doesn't work. I can scroll down only by starting to select text with mouse and dragging the selection down.
![screenshot_20170919_111528](https://user-images.githubusercontent.com/12828134/30771190-edb22f8a-a049-11e7-80dd-326458d41134.png)


![screenshot_20170919_112222](https://user-images.githubusercontent.com/12828134/30771048-7b28afea-a047-11e7-9c0f-d79a5e23a104.png)

**Comment by BleuDiamant** [comment]
Same problem on windows and linux, sometime the scrolling stop working.
To temporarily solve that, i have to stretch my window.
(the problem happen when i add code on my note)

**Comment by Trewlany01** [comment]
I would also like to add that I have seen this same issue. Seems when switching between markdown and regular mode that scrolling will infrequently be disabled in one of the modes

**Comment by Lisoph** [comment]
I can confirm the same problem on Windows and @BleuDiamant's workaround work's here too.

**Comment by AntowaKartowa** [comment]
Mousewheel doesn't work for me after note has been updated. But I can move by pull scrollbar with cursor. Or another way is to switch to some other note and then back to make mouswhell work again.

Windows 10 x64, Boostnote 0.8.16

**Comment by xbabinec** [comment]
Same issue as @BleuDiamant. Scrolling always work in editing mode but after switching to regular mode, it often bugs itself and won't scroll using mouse wheel.

**Comment by klingat** [comment]
@derekantrican I am experiencing exactly what you have explained and am on the latest update.

I see that a fix for it has been merged. Has it been deployed yet?

Thanks!

**Comment by derekantrican** [comment]
@klingat Yes, I believe this is fixed in 0.8.17 - but I would wait to update until the bug for updating to 0.8.18 is fixed #1239
