### ISSUE TITLE
Imported Snippets Don't Have Descriptions or Titles

### ISSUE THREAD

**Issue by GaryFurash** [BoostIO/Boostnote#876]
After importing a snippet, instead of having a description box at the top and a way to label the snipped like this

![image](https://user-images.githubusercontent.com/15006133/30616592-96b341ec-9d47-11e7-9696-2230784b74d0.png)

It just has the text of the note

![image](https://user-images.githubusercontent.com/15006133/30616612-a78db786-9d47-11e7-90c5-2bbb9a0eb51f.png)

Is there any way of setting the title of the snippet on import to the file name AND having a description box available? Thanks!

**Comment by Flexo013** [comment]
@GaryFurash  Sorry for the very late response! Could you try this with the latest version of Boostnote (0.12.0) and see if the issue still exists? Thanks in advance!

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
