### ISSUE TITLE
Finder issue with Multiple Screens

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#88]
Hello.
I found an issue with finder when using 2 monitors.
It is centered in the middle of the screens making it unusable.

It appears like [this](http://i.imgur.com/2uiC4un.jpg)

I found this issue before with some other electron apps.

I think the correct behavior would be to open finder centered on the current active screen. 
We need to look at the methods of [Electron Screen API](https://github.com/electron/electron/blob/master/docs/api/screen.md)

Probably we need to combine some of these methods the best result. I might try to do some experiments with this if I have some free time.

Btw, This happens on Linux Mint 18. Not tested on other OS, but I guess it should have the same problem.

**Comment by kazup01** [comment]
Is this bug still occurring?
