### ISSUE TITLE
Import lots of notes in markdown format 

### ISSUE THREAD

**Issue by l0o0** [BoostIO/Boostnote#881]
Hi, I am trying to use boostnote as my default note taking tool instead of wiznote. Now I have many notes in markdown format exported from wiznote, I want to import these notes to boostnote by writing a python script.
  But I don't know how to generate folder key.
```
  "folders": [
    {
      "key": "8e3c423c5cfbba64f615",  # how to generate folders key
      "color": "#1278BD",
      "name": "Default"
    },
```
And the filename for `cson` is a compilicate string, I want to know how to generate this complicate filename.

**Comment by asmsuechan** [comment]
>  I want to import these notes to boostnote

FYI, you'll be able to import your .md notes in bulk by drag-drop
https://github.com/BoostIO/Boostnote/pull/793

> I want to know how to generate this complicate filename.

`browser/lib/keygen.js` creates a filename. https://github.com/BoostIO/Boostnote/blob/master/browser/lib/keygen.js
