### ISSUE TITLE
Suggestion: Exit editing with :q in Vim mode

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#883]
Currently, I do not know how to exit the editor in Vim mode without using the mouse. Intuitively, I tried it by typing `:q`, but that did not work. Maybe it would be a good idea to bind `:q` to exiting the editor in the vim keymap?

**Comment by KuangLei** [comment]
In the present, we can press `Ctrl+S` to exit edit mode.  
Also you can exit with a right click by changing Preferences > UI > Switch to Preview.

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/pull/885

**Comment by asmsuechan** [comment]
FYI, `Ctrl+W` is available to exit from the editor (if you use Vim mode, it's available only in normal mode).
