### ISSUE TITLE
Notification bar should be able to hide

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#886]
# context
The bar on the bottom cannot hide.

![image](https://user-images.githubusercontent.com/11307908/30752912-baeccaca-9ff8-11e7-8a5f-3fba4ec64413.png)

In my personal opinion, I don't like this feature. However, I cannot delete it due to only my opinion because of democracy rule of OSS. So If many users also don't like it, I believe I (probably) can remove it.

Give us your opinion regarding this feature (notification bar).

**Comment by vvs** [comment]
Yes please! Any kind of advertisements would be really nice to be able to close/hide. There is no point of showing that annoying button with the link on the bottom of the page *forever*, it looks ugly and it distracts my attention.

**Comment by asmsuechan** [comment]
Hi, @vvs. Thank you for your opinion! I totally agree.

**Comment by urda** [comment]
This should be dismiss-able, it's a waste of space after the end user has acknowledged it.  Is there no way to dismiss it currently?

**Comment by asmsuechan** [comment]
Hi, @urda. Thank you for your opinion! I totally agree.

> Is there no way to dismiss it currently?

Sadly, no.

**Comment by JoshLloyd30** [comment]
I also agree that there should be a way to remove the bar, either via the app settings or a configuration option in ~/.boostnoterc

I've actually just gone back to the previous version of the app (and disabled update checking via my firewall) because I don't like it.

**Comment by MrBMT** [comment]
I agree, there should be a way to remove the bar, either via the app settings or perhaps a configuration option in ~/.boostnoterc

I've actually just gone back to the previous version of the app (and disabled update checking via my firewall) because I don't like it - I've already got the Mobile App, I don't need the bar at the bottom taking up my screen space.

**Comment by TrevorScrews** [comment]
@asmsuechan @urda I agree, it would be nice if it were dismissable.

**Comment by alarrosa14** [comment]
I totally agree. Beyond being visually intrusive, it covers the "minimize sidebar" button, which is a bug.

**Comment by kenthannigan** [comment]
I didn't want to wait around for a fix, considering this actually removes functionality as the poster above mentioned. If anybody is interested in a hack to remove this bar, you can do the following:

in `AppData\Local\boost\app-0.8.15\resources\app\compiled\main.js`

replace
`.NoteList__root___browser-main-NoteList-{position:absolute;left:0;bottom:0;bottom:30px;`
with
`.NoteList__root___browser-main-NoteList-{position:absolute;left:0;bottom:0;bottom:0px;`

replace
`.RealtimeNotification__notification-area___browser-components-{z-index:1000;`
with
`.RealtimeNotification__notification-area___browser-components-{z-index:1000;display:none;`

replace
`.StatusBar__root___browser-main-StatusBar-{position:absolute;bottom:0;left:0;right:0;height:36px;bottom:16px;`
with
`.StatusBar__root___browser-main-StatusBar-{position:absolute;bottom:0;left:0;right:0;height:36px;bottom:0px;`

Result:
![boostnotenotificationbarhidden](https://user-images.githubusercontent.com/16963630/31035355-9c734f32-a535-11e7-9e1f-66345981fb0d.png)

**Comment by asmsuechan** [comment]
@kenthannigan Cool!

**Comment by MrBMT** [comment]
Based on what @kenthannigan provided, here's a more complete set of replacements that should put everything (as far as I can tell) back to how it looked previously.

Again, just find/replace in your main.js

If I missed anything, let me know and I'll update this.

Find:
`.MarkdownNoteDetail__body___browser-main-Detail-{position:absolute;left:0;right:0;left:25px;right:25px;top:87px;bottom:36px}`

Replace With:
`.MarkdownNoteDetail__body___browser-main-Detail-{position:absolute;left:0;right:0;left:25px;right:25px;top:87px;bottom:24px}`

Find:
`.StatusBar__root___browser-main-StatusBar-{position:absolute;bottom:0;left:0;right:0;height:36px;bottom:16px;`

Replace With:
`.StatusBar__root___browser-main-StatusBar-{position:absolute;bottom:0;left:0;right:0;height:24px;bottom:0px;`

Find:
`.RealtimeNotification__notification-area___browser-components-{z-index:1000;font-size:12px;position:absolute;bottom:0;background-color:#ebebeb;width:100vw;height:30px;text-align:center}`

Replace With:
`.RealtimeNotification__notification-area___browser-components-{z-index:1000;display:none;font-size:12px;position:absolute;bottom:0;background-color:#ebebeb;width:100vw;height:0;text-align:center}`

Find:
`.NoteList__root___browser-main-NoteList-{position:absolute;left:0;bottom:0;bottom:30px;top:59px;background-color:#f3f3f3}`

Replace With:
`.NoteList__root___browser-main-NoteList-{position:absolute;left:0;bottom:0;top:59px;background-color:#f3f3f3}`

Find:
`.SnippetNoteDetail__body___browser-main-Detail-{position:absolute;left:0;right:0;left:25px;right:25px;top:87px;bottom:36px;background-color:#f4f4f4}`

Replace With:
`.SnippetNoteDetail__body___browser-main-Detail-{position:absolute;left:0;right:0;left:25px;right:25px;top:87px;bottom:24px;background-color:#f4f4f4}`

Find:
`.SnippetNoteDetail__override___browser-main-Detail-{position:absolute;bottom:0;left:0;bottom:30px;left:60px;height:23px;z-index:101}`

Replace With:
`.SnippetNoteDetail__override___browser-main-Detail-{position:absolute;bottom:0;left:0;left:60px;height:23px;z-index:101}`

![screen shot 2017-10-02 at 11 01 53](https://user-images.githubusercontent.com/6931281/31072893-b6f97bbe-a761-11e7-8422-8132b527cf93.png)

![screen shot 2017-10-02 at 11 01 57](https://user-images.githubusercontent.com/6931281/31072911-c5b33d98-a761-11e7-8d29-2ceb6367fe07.png)

**Comment by urda** [comment]
@kazup01 is there a way to have the next release make this notification area dismissible? It would be a lot better than end users having to hack it out by hand.

**Comment by urda** [comment]
@kazup01 can you offer any input on this? While it's nice to have recent news and notifications, I would love to reclaim that last bit of space for my notes by hiding or disabling the area. Can we get some input about developing a better solution to this from you?

**Comment by kazup01** [comment]
Hi @urda , sorry for late replying. We are welcome any pull requests. If someone adds this feature, I will check it.

**Comment by urda** [comment]
I'll try and take a look at it, perhaps @MrBMT can convert it into a feature pull request based on their comment ?

**Comment by MrBMT** [comment]
@urda unfortunately I'm super busy for the next few weeks, I'll have a look into changing the CSS so that it removes the bar from the updated version of Boostnote when I get a few minutes, but anything more than that is unlikely to happen any time soon.

**Comment by urda** [comment]
@MrBMT no worries same here!

**Comment by kazup01** [comment]
I will hide this area from main window at next update.

**Comment by kazup01** [comment]
Wait for the next update. Thank you for you guys feedback!
https://github.com/BoostIO/Boostnote/pull/1067
