### ISSUE TITLE
Tags are not searchable (or recallable in any other way)

### ISSUE THREAD

**Issue by fladd** [BoostIO/Boostnote#894]
While I can create tags for notes, there is currently no way to recall them. While some users have reported that they should be searchable, they are **not** searchable in the OS X app. See also: https://github.com/BoostIO/Boostnote/issues/854#issuecomment-331641908

**Comment by kazup01** [comment]
Sorry for the late supporting. This feature will be released in this week! Enjoy Boostnote!
https://github.com/BoostIO/Boostnote/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Next+Release%22
