### ISSUE TITLE
fault in updating to  0.8.15

### ISSUE THREAD

**Issue by KOROKORO-Manbo** [BoostIO/Boostnote#898]
Today updater in my Mac run and renew the version of this app. After restarting , this app came to display quite no storage falders but just a blunk folder there. Is this because this new version ignores the top level JSON file or overwrote the former JSON file and converted it to a blunk file? Anyway whatever, that's why I had to restore all indivisual folders I used in the former version.I expect this never happen again from next coming updatings :)
![2017-09-24 10 09 30](https://user-images.githubusercontent.com/16297739/30778422-843dada0-a110-11e7-908a-c8e62e48c4bd.png)

**Comment by kazup01** [comment]
Hi @KOROKORO-Manbo san, thanks for your reporting and sorry for your inconvenience. We will improve it.

**Comment by KOROKORO-Manbo** [comment]
thanks a lot with  respect to your great work
