### ISSUE TITLE
Backup feature & Evernote?

### ISSUE THREAD

**Issue by the-c0d3r** [BoostIO/Boostnote#9]
Are you planning to add the Backup feature for this application? It would be nice if I can backup the posts easily and maybe with auto synchronisation to evernote account?

**Comment by Rokt33r** [comment]
The new Boost v0.6.* will provide some features about backup.
Note storage will become just like git repository. It can be placed wherever in file system you can access.(It means to backup/sync your note by placing the note storage to Google drive or Dropbox folder)

But, Syncing with Evernote won't be shipped so soon. the developing and maintaining cost is too high.
If we provide it, we should maintain bilateral importing/exporting job perfectly. And, this work should be done every time Evernote updated. Accordingly, I think importing from/exporting to Evernote would be enough. If you think it is necessary and  it seems to be easy to embed, you can give more hint to me.

**Comment by Rokt33r** [comment]
Closed. If the above answer is not enough, feel free to re-open this issue. 😄
