### ISSUE TITLE
v0.6.5 will be released on 9/14 Wed

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#90]
I have to update Boostnote on the next Wednesday 9/14. Until then, I'm going to developing more features.
During the my field trip, there seem to be an accident at my office. So, my internet connection is too slow to upload the new app and check the update procedure works well.
(currently I'm writing this issue by tethering my phone)
I'm so sorry to make you wait. - 2016/09/11

----

I found a critical bug when updating on windows. I currently am digging in what's the problem. v0.6.5 will be released after I fix the problem. - 2016/09/10

----

# v0.6.5

## Features

- ~~[ ] Share to Gist #74~~
- ~~[ ] Share by public URL~~
  - ~~[ ] Use same the renderer of Boostnote app~~
  - ~~[ ] Auto expiration within 7 days~~
- ~~[ ] Tutorial~~

## UI Improvement

- [x] Infinite scroll
- [x] Confirm on blur when editing color and name of folder.
- [x] Default note option(Snippet/Markdown/Always ask)
- ~~[ ] Context menu for folders and notes (Deleting and other actions...)~~
- [x] Context menu for notes(`Delete Note`)
- [x] Show dialog when deleting snippet #107
- [x] Improvement folder select #106 
- [x] Resizable SideNav 
- [x] Strip markdown syntax from title 

## Under the hood (Check #100 )

- [x] Using Immutable
- [x] Refactor for dataApi
  - [x] Tests

----
## Updates(2016/09/08)

The release date has been updated.

## Updates(2016/09/03)

Sorry for making you guys wait! Refactoring job is almost done. I'll ship it on 2016/09/07. But, the features might not be included.
As you see #100, there are big changes(over 2000 lines added). this exceeds my expectation.
But, it seems to be worthy because the indexing speed became hundred times faster.(over a thousand in some cases)
After this updates, I'll going to focus on enhancing UI/UX tasks of #68 and sharing features.

> Honestly,  I've been participating an 6 weeks program of 500 startups. In this event, I and my collegue(CEO of MAISIN) has been developed another project, which named [10hz](https://10hz.io) (I'll explain this later).  And we have to release closed beta version of this app on the next Monday. So, it is also the reason why the update delayed. But, after it released, I could have a plenty of time to concentrate Boostnote. So please hang on a little more. I'm terribly sorry.

**Comment by huettenhain** [comment]
This might be a silly question, but what is the preferred way to update boostnote? In my case, I am a Windows user who very plainly used the installer, so there is a folder `%appdata%\..\Local\boost` which currently contains folders `app-0.6.4`, `packages` and the Squirrel executable. What do I have to do when .6.5 is out? =)

**Comment by Rokt33r** [comment]
@huettenhain 
The app will automatically detect the new release and prepare updating.
When updating is ready, It will shows a dialog to update. :)

Additionally, you don't have to update by the dialog. It only does restart the app. So, you can apply the new release by restarting app whenever you want.
