### ISSUE TITLE
Mobile App Hint Blocking Collapse Button

### ISSUE THREAD

**Issue by Nino9614** [BoostIO/Boostnote#904]
How do i disable or close this message 
![image](https://user-images.githubusercontent.com/27356972/30804223-e21750ac-a1ec-11e7-8dbe-7237ab204fb0.png)

Does it close itself or do i need to set a option. 
Currently its blocking the collapse button. I need to remove it using the developer tools to collapse my sidebar, because all my preferences was reseted after updating boostnote.

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/issues/886

**Comment by Nino9614** [comment]
@asmsuechan my bad :)

**Comment by sferra** [comment]
@asmsuechan i would argue that dismissing the "advertising" is a different issue than fixing the bug which prevents us to collapse the side bar. the first one is an improvement, the second one is a bug. don't you agree?
