### ISSUE TITLE
Add custom adjustment plan order function

### ISSUE THREAD

**Issue by vikin** [BoostIO/Boostnote#908]
Perhaps you could consider adding custom adjustment plan order by dragging. Thanks!

**Comment by kazup01** [comment]
I totally agree with you. How about #396? But I don't know this PR's state.
Could you check it? @sosukesuzuki

**Comment by kazup01** [comment]
Hi @vikin , I totally agree with you. How about #396? But I don't know this PR's state.
Could you check it? @sosukesuzuki

**Comment by sosukesuzuki** [comment]
Hi! @vikin @kazup01 ! I was working on this work a few months ago. However, I have been busy recently, and I could not do the work. I expect to be able to resume work soon. Please wait till then.

**Comment by vikin** [comment]
Hi! @kazup01 @sosukesuzuki, It was so nice to expect this feature to be updated as soon as possible.

**Comment by kazup01** [comment]
You can use this feature in Preferences after v0.8.16. Enjoy :)
![1-hprygaag5obhofhhnns5ca](https://user-images.githubusercontent.com/8602615/32454946-0f117ce8-c364-11e7-81c1-b4750d83549c.gif)
