### ISSUE TITLE
'Add tag' input is wrapped below divider and clipped on smaller windows

### ISSUE THREAD

**Issue by patrick-iv** [BoostIO/Boostnote#910]
Like the title says, when the window is small, the Add Tag input is wrapped below the divider and clipped, as shown in the screenshot below.

![tile](https://user-images.githubusercontent.com/1384547/30847429-cf081dde-a29b-11e7-9c15-2ec6b53b0c1b.png)

**Comment by AntowaKartowa** [comment]
I have opposite case. When adding a lot of tags in some cases part of last tag is cut off. Also there is no place where I can click to add more tags.

![boostnote-tag-screen](https://user-images.githubusercontent.com/3750437/32245502-9c7bebf2-be84-11e7-9528-35ef90df2693.png)

**Comment by kazup01** [comment]
memo #703

**Comment by kazup01** [comment]
Fixed at #1121.
Please wait for the next update :)

<img width="638" alt="screen shot 0029-11-14 at 9 24 35 pm" src="https://user-images.githubusercontent.com/8602615/32779979-0e9671f4-c983-11e7-909d-1375d2706554.png">
<img width="396" alt="screen shot 0029-11-14 at 9 29 44 pm" src="https://user-images.githubusercontent.com/8602615/32779980-0ec064e6-c983-11e7-92c3-94bac03fe664.png">
