### ISSUE TITLE
Export as PDF disabled in Desktop App

### ISSUE THREAD

**Issue by balogic** [BoostIO/Boostnote#912]
![screenshot from 2017-09-26 14-41-14](https://user-images.githubusercontent.com/6650280/30852574-db3b5cb4-a2c9-11e7-9ee2-68466795f7c6.png)

**Export as PDF** option is disabled for all my notes. Is this an issue or the feature is still in development?
If it is still in development, it should be displayed on mouse hover.

**Comment by kazup01** [comment]
Hi @balogic ,
Yes this feature is under development,so cursor is displayed like below image when hovering.
![s__32923650](https://user-images.githubusercontent.com/8602615/30853908-1340e734-a2eb-11e7-89d1-62364a43fac5.png)

If you want to export as PDF, please use [print feature](https://github.com/BoostIO/Boostnote/pull/754).

**Comment by balogic** [comment]
@kazup01 Thanks
