### ISSUE TITLE
Use cmd+s to save on Mac os X

### ISSUE THREAD

**Issue by chbndrhnns** [BoostIO/Boostnote#913]
Currently, Ctrl+S must be used to save a document. But default for Mac OS X is Cmd+S.
Could you please change this behaviour?

**Comment by KuangLei** [comment]
@chbndrhnns Boostnote will save your changes automatically, not required to press `Ctrl+S`.  

But it would be better if the keyboard shortcut could be modified.

**Comment by asmsuechan** [comment]
Boostnote saves documents automatically, so you don't have to press keys. `Ctrl+s` means just focusing the search field.
