### ISSUE TITLE
[Feature request] Checkboxes with color

### ISSUE THREAD

**Issue by MakisH** [BoostIO/Boostnote#914]
I think it would be very helpful if the checkboxes changed color when checked. In a long todo list, I find it difficult to see the non-checked checkboxes (my open TODOs) and color would really help.

It would even be great if I could set these colors in the settings. Two hex color code fields would be enough.

What do you think?

**Comment by kazup01** [comment]
Hi @MakisH , thanks for your suggestion! I think this is great. 
I also want to hear feedback from other people.

**Comment by MrBMT** [comment]
Nice idea 👍 and if the colours were user configurable, if someone didn't like the change they could just set both checked and unchecked to use the same colour.

**Comment by Nino9614** [comment]
And maybe not just change the color of the checkbox but also the text color or adding a background color to the text element. Then you dont need to try identifying on which line the checkbox is on.

**Comment by piefel** [comment]
Colour is good, even if the colour is only grey for finished items.

It’s probably very difficult to colour the checkboxes in HTML, but coloured text should do the trick.

**Comment by kazup01** [comment]
memo https://github.com/BoostIO/Boostnote/pull/1011

**Comment by kazup01** [comment]
Hey guys, how about the current version? :) Thanks!

<img width="1165" alt="screen shot 0030-01-15 at 7 33 01 am" src="https://user-images.githubusercontent.com/8602615/34942646-6336d672-f9c6-11e7-9e64-30d9bd7fcae7.png">

**Comment by MakisH** [comment]
Very nice! Is it already in v.0.8.20? I don't get colored checkboxes in neither of the White, Dark, and Dark-Solarized color themes.
