### ISSUE TITLE
[Feature Request] Add Preferences to OSX menu

### ISSUE THREAD

**Issue by initializard** [BoostIO/Boostnote#916]
It's fairly standard in OSX to have Preferences listed in the native app menu. (See screenshots of Atom and Macdown as examples). I find myself looking there for preferences, rather than in the app UI. Is it possible to add?

![menu-atom](https://user-images.githubusercontent.com/2012737/30931680-10eba4ec-a38b-11e7-9d10-68e6a9978c73.png)
![menu-macdown](https://user-images.githubusercontent.com/2012737/30931682-11cf1cc2-a38b-11e7-9109-dd074fe22924.png)
![menu-boostnote](https://user-images.githubusercontent.com/2012737/30931685-1317994c-a38b-11e7-8d8a-fcbbbc5a83bf.png)

**Comment by kazup01** [comment]
Hi @initializard , thanks for your suggestion! 
I agree with you. We will add it.
BTW, how do you think about fix UI like below image?
<img width="688" alt="screen shot 0029-09-28 at 10 17 29 am" src="https://user-images.githubusercontent.com/8602615/30944956-59459062-a436-11e7-8b6d-6ca77cd9efa3.png">

**Comment by initializard** [comment]
I like it, but some people might miss the full title bar.

**Comment by kazup01** [comment]
Ok, we should get feedback from other people.

**Comment by MrBMT** [comment]
@kazup01 I like the design change, but the corners should be rounded so that they match other mac apps (and the bottom).

**Comment by Fig-R** [comment]
It's much prettier without the hideous title bar ^^.

**Comment by kazup01** [comment]
I agree with you. Thanks! @MrBMT

**Comment by PascalAOMS** [comment]
The Atom editor offers the option to show/hide the title bar. Don't know how hard it is to offer an option in the preferences.

Personally, I like it without the white bar. Hope Windows adapts this system one day.

**Comment by kazup01** [comment]
Thanks @PascalAOMS !

**Comment by KaceyGambill** [comment]
Is there still interest in making the preferences also appear in the native app menu?

**Comment by kazup01** [comment]
Hi @KaceyGambill  , nobody has made this feature yet. We're welcome to your pull request! #Hacktoberfest

**Comment by AlwaysKamin** [comment]
@KaceyGambill Did you end up getting to this? I'd like to take a swing at it, but if you are already working on it I don't want to intrude.

**Comment by KaceyGambill** [comment]
@AlwaysKamin Go for it, I was working on it but was slightly confused how to like main-menu.js with the openModal to load Preferences, not sure if I was doing it right... But my laptop broke yesterday morning heh so definitely go for it!

**Comment by draganmarjanovic** [comment]
Has anyone made progress on this issue? @KaceyGambill @AlwaysKamin  

Also, I personally feel the discussion of UI is slightly off topic for the issue - but I prefer the dark bar.

**Comment by AlwaysKamin** [comment]
@draganmarjanovic Sorry for the late response. I've been able to get the tab to appear but I'm still unsure how to set it up to respond to the click. But I am working still.

**Comment by KaceyGambill** [comment]
I think we need to use ipcRender? to get it to display, I was able to get the Preference button in the menu bar and get it to load external resources... but I for the life of me can't seem to figure out how to load the Preferences.

**Comment by kazup01** [comment]
v0.8.17 is out! I wrote the release note. https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2
Enjoy :)
