### ISSUE TITLE
snippet vertically aligned option

### ISSUE THREAD

**Issue by shelper** [BoostIO/Boostnote#917]
Please paste some **screenshots** with the **developer tool** open if you report a bug.
currently snippets are putting together horizontally, 
when on small display, we have very narrow editor size and not comfortable for code review.
<img width="777" alt="screen shot 2017-09-28 at 9 48 03 pm" src="https://user-images.githubusercontent.com/546163/30997585-e5a7b264-a496-11e7-8ea7-890eb32f67f4.png">

**Comment by kazup01** [comment]
Hi @shelper , thanks for your suggestion, but I can not imagine the vertically align option for sub-snippet.
Could you attach something example?

**Comment by shelper** [comment]
what i mean is vertically align the files not the code line. 

instead of 
| snippet file 1 | | snippet file 2 | 

i want 
| snippet file 1 | 
some code snippets
| snippet file 2 | 
some code snippets

**Comment by Flexo013** [comment]
The width of the editor with your suggestion and current situation is the same, So I don't quite see this being very useful. The buttons at the top are tabs which change the entire view as opposed to splitting the view to have multiple notes adjacent to each other.

Feel free to reopen this issue if you still feel the need for such a ui change/option.
