### ISSUE TITLE
I can't intuitively specify in font name including space

### ISSUE THREAD

**Issue by elliptic-shiho** [BoostIO/Boostnote#919]
Please paste some **screenshots** with the **developer tool** open if you report a bug.

I want to use `Migu 1M` Font but I could specify it only non-intuitive way.

Environment:
* OS: Windows 10
* Version: Boostnote 0.8.15

First, I set `Editor Font Family` and `Preview Font Family` to `Migu 1M`. Then I checked Developer Tool, I can see like below image.

![Capture 1](https://user-images.githubusercontent.com/8950527/31006771-2209aa9e-a539-11e7-9db0-f848a1a88f17.PNG)

So I set `Editor Font Family` and `Preview Font Family` to `"Migu 1M"`. Then It can specify correctly.

![Capture 2](https://user-images.githubusercontent.com/8950527/31007055-1f2a55b6-a53a-11e7-8bfe-1883fa6be3f0.PNG)

**Comment by asmsuechan** [comment]
Hi, @elliptic-shiho. Long time no see! Alright, I'll fix it soon.

**Comment by asmsuechan** [comment]
I hope https://github.com/BoostIO/Boostnote/pull/955 fixes this issue.

**Comment by elliptic-shiho** [comment]
Great!

**Comment by asmsuechan** [comment]
:smile:
