### ISSUE TITLE
Cannot select syntax highlight by typing language name

### ISSUE THREAD

**Issue by darahak** [BoostIO/Boostnote#92]
Hi there,

I just started to use this app and it has a lot of potential! Really cool.

I have some trouble using the syntax dropdown list.
If I type a language name, it will only register one letter at a time and jump around the list.

Here's a [GIF](http://i.imgur.com/5CFbltv.gif) showing the issue (typing "javascript").

**Comment by Rokt33r** [comment]
@darahak 
I'm going to make a custom mode selector! I added it to #68. 

By the way, you can do it easily by filling file name ended with `*.js`. #84 
Boostnote will set syntax mode automatically.

<img width="641" alt="screen shot 2016-08-23 at 9 39 56 pm" src="https://cloud.githubusercontent.com/assets/5865853/17892046/2930969e-697a-11e6-994f-16ae70815182.png">

If you found some filename pattern, which Boostnote can't detect the syntax type, just tell me and I'll implement it soon.
