### ISSUE TITLE
[Feature Request | 10hz] Add Comment System Below Snippet

### ISSUE THREAD

**Issue by PascalAOMS** [BoostIO/Boostnote#925]
What do you think about having a commenting system below a snippet/note for teams?
Giving the snippet creator tips on improving the code might be helpful.

That way you don't need to wait for the next team meeting to talk about it.

**Comment by kazup01** [comment]
memo: [10hz](https://10hz.io/createteam) - Boostnote for teams 

Hi @PascalAOMS , thanks for your feedback. 
I also think need this feature for 10hz, but not implemented yet.
It is very easy to understand because you write concrete usage scenes. Thanks!
