### ISSUE TITLE
Text in a codeblock is not visible

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#928]
![image](https://user-images.githubusercontent.com/11307908/31053821-a5242cee-a6e0-11e7-969a-3b78cfcf0f1f.png)

The text is

```
asdf
asdf
```

The text does not be shown when I don't specify a language.

I checked it doesn't happen on v0.8.14
# env
ubuntu 16.04 LTS
development (on master branch 95d74d1ca2206ed18add0348682af0063a5ac5b0)

**Comment by MrBMT** [comment]
@asmsuechan It looks like that issue has been caused by this change: https://github.com/BoostIO/Boostnote/commit/ec8fac11993aa4308111a47a481bc7ee35901e72

**Comment by kazup01** [comment]
Sorry for my careless mistake. I returned it back. #931
Thanks for your reporting @asmsuechan and teach me @MrBMT !
