### ISSUE TITLE
[Suggestion] Real time notification area

### ISSUE THREAD

**Issue by Hadesy2k** [BoostIO/Boostnote#929]
Instead of putting real-time notification area at the bottom like the image below, using the system notification calls would be better and could make editor space larger. Because it used to be an empty space when there are no notification at all in most time.

![image screenshot](https://i.imgur.com/4WWy1s9.png)

**Comment by kazup01** [comment]
Hi @Hadesy2k , I will hide this area at next release. Thank you.

**Comment by bimlas** [comment]
It seems implemented, issue may be closed.
