### ISSUE TITLE
How to unescape the encoded special chars in short code block tag ?

### ISSUE THREAD

**Issue by chenxinlong** [BoostIO/Boostnote#942]
```< ? > $``` etc, these chars will be encoded to entity in  \`\`\` \`\`\` short code block tag, like ```<``` will be encoded to ```&lt;```

**Comment by kazup01** [comment]
Could you your Boostnote version?
I could not reproduce it. Boostnote v0.8.15

<img width="237" alt="screen shot 0029-10-10 at 9 22 44 am" src="https://user-images.githubusercontent.com/8602615/31363901-af4b8a9c-ad9c-11e7-86da-5c74287d2cac.png">
<img width="212" alt="screen shot 0029-10-10 at 9 22 47 am" src="https://user-images.githubusercontent.com/8602615/31363902-af4f3b06-ad9c-11e7-9c08-50dd9b54d1d1.png">

**Comment by chenxinlong** [comment]
Thx! I use the wrong tag.
![image](https://user-images.githubusercontent.com/9261954/31389801-c3842c58-ad97-11e7-91c7-4f0baa11fc96.png)

![image](https://user-images.githubusercontent.com/9261954/31389760-a6f0c678-ad97-11e7-8984-a7a2529d5616.png)

**Comment by kazup01** [comment]
👍 Enjoy Boostnote!
