### ISSUE TITLE
[Feature Request] Auto format code 

### ISSUE THREAD

**Issue by 123Jon4** [BoostIO/Boostnote#945]
# Context
When you copy fast typed code and you want it to appear properly formatted in Boostnote you have to use an external formatter tool. So it would be nice if there would be a auto format feature for snippets inside of Boostnote. It could be automatically triggered when pasting some code and manually by clicking a button. The automatic function could be optional so some people can use their own code style.

# Benefits
- Better looking code
- Better readable code
- No need to use an external formatter

**Comment by kazup01** [comment]
Please try the v0.8.20 :) Thanks!
refs: #1392
