### ISSUE TITLE
[Feature Request] Other ways to delete note/snippet

### ISSUE THREAD

**Issue by SchwartzWare** [BoostIO/Boostnote#946]
# Context
When you want to delete a note you have to go the whole way to the right side and click the trash icon. It would be nice if you would have some other possibilities to delete a note/snippte.

- Right click on a note (context menu)
- Keyboard shortcut (e. g. DEL)
- Trash icon on the note entry

# Benefits
- Faster
- No need do move the mouse the whole way to the right

**Comment by kazup01** [comment]
Thanks for your suggestion @123Jon4 .

- Delete note by right click is implemented by @voidsatisfaction a #943.
- Keyboard shortcut -> You can use `Ctrl + Delete`

**Comment by voidsatisfaction** [comment]
I did not know `Ctrl + Delete` shortcut before I see boostnote source code. I think shortcut there should be explanation where user easily know(e.g boostnote official page)

**Comment by kazup01** [comment]
Good morning @voidsatisfaction ! 
I wrote it on the [wiki](https://github.com/BoostIO/Boostnote/wiki/Keyboard-Shortcuts). 
I will write a blog about the shortcut-keys later.

**Comment by voidsatisfaction** [comment]
@kazup01 good morning! thank you for kind reply!

**Comment by kazup01** [comment]
Hi @voidsatisfaction , I wrote a blog about shortcuts. https://medium.com/boostnote/how-to-boost-your-work-efficiency-by-using-shortcut-keys-8c47da92ea1d

**Comment by voidsatisfaction** [comment]
@kazup01 Great. As you said in the article, I can save much times if I am used to using short cuts...

I really appreciate your easy-to-understand and kind explanation for me and users..!

Thank you so much

**Comment by Redsandro** [comment]
In the note list view 'd' also deletes a note.
