### ISSUE TITLE
Note titles should not contain MD syntax

### ISSUE THREAD

**Issue by darahak** [BoostIO/Boostnote#95]
For example, if I start a note with `# Hello **World**`, the first `#` will be hidden.
The note is then named `Hello **World**`.

It should be stripped of all Markdown syntax for better readability.
What do you think?

**Comment by Rokt33r** [comment]
I agree with that. It is a easy task because Boostnote sets title of a note when editing finished.
I'll ship it on this weekend.

**Comment by Rokt33r** [comment]
Sorry for making you wait! I'd been busy...It will be shipped on this weekend.(CONFIRMED)

![screen shot 2016-09-08 at 10 37 21 pm](https://cloud.githubusercontent.com/assets/5865853/18376040/52b3195a-7696-11e6-8fd3-af3be2d8c436.png)
