### ISSUE TITLE
Boostnote exits edit mode / Toggle functionality

### ISSUE THREAD

**Issue by tonyflow** [BoostIO/Boostnote#960]
Boostnote seems to ignore the fact that the editor is still in the process of updating the current note and exits the edit mode when one briefly changes the current window and returns after a small absence of a couple of seconds or less. So to describe the scenario more succinctly:
- Edit Mode On: Updating the current note
- Change window of focus from Boostnote to browser
- Return to Boostnote
- Edit Mode has been turned off

Is this on purpose? It is a bit counterintuitive for the application to infer that the editor is done with all the updates (since an ALT+TAB was recorded - quite annoying to be honest) and should implicitly exit the edit mode. It obliges the developer to re-enter edit mode (CTL+E). It would be really nice if something like this would not occur.

Additionally, I would like to mention that it would be great if this, already life-saving application, could be able to toggle between edit mode though some kind of shortcut. Is this maybe something that you're planning or is it something that is already in the bundle and I haven't noticed?

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/pull/283 or RIGHTCLICK mode.

Ctrl-W on the edit mode is available (also Ctrl-S is effective)

**Comment by nikostrongioglou** [comment]
@asmsuechan Thanks a lot for the reply. I see that this functionality was merged back in March but I cannot see this lock on my latest (0.8.15) version. It's not even in the code of `browser/main/Detail/MarkdownNoteDetail.js` for 0.8.15. Was this moved to some un-released feature branch?
