### ISSUE TITLE
Adjust tooltip

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#963]
# context
The tooltip (`Make a note ⌘+n`) position is fixed now, however, it's not good so it should be adjusted.
![image](https://user-images.githubusercontent.com/11307908/31502190-526c3b98-afa7-11e7-816b-1aa97b6df1e8.png)

**Comment by Visovsiouk** [comment]
Can I take a look at it?

**Comment by asmsuechan** [comment]
@Visovsiouk Sure thing :)

**Comment by kazup01** [comment]
Thanks @Visovsiouk 🙌
