### ISSUE TITLE
Text not being displayed in system dialogs

### ISSUE THREAD

**Issue by fullama** [BoostIO/Boostnote#964]
there is no text being displayed on any system dialogs that pop up when using boostnote on fedora 25 gnome Version 3.22.2, Boostnote 0.8.14

Maybe there is a font missing on my system? But i dont know what i should check to find that out?

![image](https://user-images.githubusercontent.com/8556960/31501820-95cffad2-af6b-11e7-8704-89ad2b042d8e.png)

**Comment by asmsuechan** [comment]
Please paste some screenshots with the developer tool open if you report a bug.

I'd say you're right. I assume there's an error that the font set in Boostnote is not found.

**Comment by fullama** [comment]
![image](https://user-images.githubusercontent.com/8556960/31502566-c245c482-af6d-11e7-85b5-609ca619d132.png)

**Comment by fullama** [comment]
Apologies - proper screenshot added.

**Comment by asmsuechan** [comment]
@fullama Thank you for adding the screenshot. How about the `console` tab? Do you see anything in it?

**Comment by fullama** [comment]
![image](https://user-images.githubusercontent.com/8556960/31533452-9a932490-aff2-11e7-90f4-9c0764690ebc.png)
this is what was there at the time when I posted the last screen shot.. this is what it looks like this morning when I restarted:
![image](https://user-images.githubusercontent.com/8556960/31533611-6d1083c2-aff3-11e7-9e48-48f2daa45f59.png)
Not much there..

**Comment by KuangLei** [comment]
I think this is not due to Boostnote. The problem didn't take place in the Boostnote's interface but in the file selecting window developed by GNOME. I've met the problem once in LXDE after installing a non-system font.  
**Solution:**
Try to install any font manager for example `sudo aptitude install font-manager` and remove or disable all the non-system fonts, only leaving fonts like `Droid ...`, `Libre ...`, `Free ,,,`, etc.. Then restart your computer and it should be solved.  

Thanks.

**Comment by fullama** [comment]
Thanks for your suggestion. I would try that but it is a work computer and I dont have root access. I dont think they will want to let me mess around with fonts either unfortunately. The only reason I thought it might be something on the side of boostnote is that it doesnt happen with anything else on my system.  Even other electron based apps like Atom are ok. But if the problem does exist with my system then I guess there is not much we can do.. 

Thanks anyway!

**Comment by mcg** [comment]
Same issue here after upgrading from 0.8.14 to 0.8.16. Using Ubuntu 17.10 on Xorg. Disabling fonts isn't really a fix, as this is the only app that has this issue for me.

**Comment by mcg** [comment]
https://github.com/electron/electron/issues/9616 seems like it.

**Comment by reidstidolph** [comment]
Pop_OS (Ubuntu 17.10):
![image](https://user-images.githubusercontent.com/2548047/32343240-0de1fc0a-bfc0-11e7-9db8-c4892d4415d1.png)

**Comment by mcg** [comment]
Closing as fixed or ?

**Comment by Hubro** [comment]
So this would be fixed by upgrading to the latest version of electron? If so, why has this issue been closed? I'm using the very latest version of Boostnote and I have this issue.

**Comment by asmsuechan** [comment]
I don't think it's fixed and he probably accidentally closed. So I reopen.

**Comment by kazup01** [comment]
Hi guys, @yosmoc has solved this problem. Would someone try this PR? #1105

**Comment by mcg** [comment]
v0.8.17 seems to have fixed this for me.

**Comment by kazup01** [comment]
Thanks @mcg :)
I close this issue, but if you need to more information, please feel free to reopen it.
