### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#965]
This event listener causes tiny errors.
https://github.com/BoostIO/Boostnote/blob/6a3062709c7445e7c8f6438d544f8f408d3615de/browser/main/index.js#L26:L34

![image](https://user-images.githubusercontent.com/11307908/31503964-0ac0c3cc-afac-11e7-9449-6590dcaa141f.png)

**Comment by adrichey** [comment]
I am willing to take this on. On it!

**Comment by asmsuechan** [comment]
@adrichey Yes, please :ok_woman:

**Comment by adrichey** [comment]
How are you consistently replicating this issue?

**Comment by asmsuechan** [comment]
Here's one of them. Actually, there are some other cases...
[![https://gyazo.com/92b48aad033309fab22decd9304782a2](https://i.gyazo.com/92b48aad033309fab22decd9304782a2.gif)](https://gyazo.com/92b48aad033309fab22decd9304782a2)

**Comment by adrichey** [comment]
I think I have sorted it out. It occurs when the element you are clicking on doesn't have an offsetParent in which to check the class. Please see: https://github.com/BoostIO/Boostnote/pull/968

**Comment by alexrussell** [comment]
Should this be closed as #968 was merged?

**Comment by adrichey** [comment]
I would assume it can be closed. @asmsuechan?

**Comment by asmsuechan** [comment]
Thank you for your cooperation!
