### ISSUE TITLE
A style issue

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#966]
# context
The new note button has a weird style. The protrusion should be removed.
![image](https://user-images.githubusercontent.com/11307908/31504715-11526c0c-afae-11e7-9952-ed4cca0ea1a2.png)

The file is https://github.com/BoostIO/Boostnote/blob/master/browser/main/NewNoteButton/NewNoteButton.styl

# how to reproduce
1. create a new empty folder
2. access it
3. look at the button

**Comment by Samatar26** [comment]
@asmsuechan Looking at it now :)
