### ISSUE TITLE
Uncaught TypeError: _this5.handleCloseButtonClick is not a function

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#967]
# context
The init modal cannot escape by clicking the esc button and pushing the esc key.
![image](https://user-images.githubusercontent.com/11307908/31505853-cf959480-afb0-11e7-9ab4-0cc59acaae3f.png)

# how to reproduce
1. clone Boostnote and run `yarn && yarn run dev-start`
2. initialize Boostnote to delete `localStorage.storages` by hand from `Application` in Electron if you've already had Boostnote development environment
3. reload Boostnote
4. try to escape from the initial modal

**Comment by Samatar26** [comment]
@asmsuechan Looking at it now :)

**Comment by kazup01** [comment]
refs; #969
Thanks for your contribution @Samatar26 !
