### ISSUE TITLE
Add images to boostnote via drag drop - version 0.8.14 (linux) 

### ISSUE THREAD

**Issue by dogfish182** [BoostIO/Boostnote#976]
Hi all, 

I'm using boostnote 0.8.14 on linux mint (sonya). Drag drop of images doesn't seem to work at all. I've tried drag/dropping pictures from any source and the application simply doesn't react. 

I see there is closed issues relating to pictures and it should be solved? I can add images in the following ways 

```
Inline-style: 
![alt text](/home/me/Dropbox/notes/boostnote/images/download.jpg
 "Logo Title Text 1")

Reference-style: 
![alt text][logo]
[logo]: /home/me/Dropbox/notes/boostnote/images/download.jpg
 "Logo Title Text 2"
```
and that works fine, but I get nothing with drag drop. Am I missing something straightforward?

**Comment by asmsuechan** [comment]
Try the latest version (v0.8.15) https://github.com/BoostIO/Boostnote/pull/820

**Comment by dogfish182** [comment]
thanks! 

Note that on linux, drag and drop of a picture still does not work, however a copy/paste of a picture does work and adds the following style text

![4yd2in9h3reh4cxr](/:storage/4yd2in9h3reh4cxr.png)

which works perfectly for me. It seems the note has to be in 'edit' mode for lack of a better word and moving outside the app to pick and drag something puts it back in display mode. drag drop simply doesn't react. 

In any case, this tool now ticks all of my boxes, screenshots were a bit issue so this is pretty fantastic news.

If the intention is that drag/drop of images actually works though, I guess this issue should stay open.

**Comment by dogfish182** [comment]
I think this can be closed. it seems to drag drop you must lock the note first. wasnt aware of that. this seems to do what it should.

**Comment by yashha** [comment]
It is not that UI-friendly, it should automatically go to edit mode when dragging the image in.
