### ISSUE TITLE
SQL syntax highlighting does not work on #-style comments

### ISSUE THREAD

**Issue by initializard** [BoostIO/Boostnote#977]
Only "--" style comments in SQL snippets are highlighted correctly, but "#" comments are not. 

Example: 

![screen shot 2017-10-13 at 1 47 27 pm](https://user-images.githubusercontent.com/2012737/31561475-9b5fab52-b01d-11e7-8c63-44e1800a5034.png)

**Comment by clone1612** [comment]
Isn't this the normal behaviour of SQL comments?

A comment can appear between any keywords, parameters, or punctuation marks in a statement. You can include a comment in a statement in two ways:

- Begin the comment with a slash and an asterisk (/&ast;). Proceed with the text of the comment. This text can span multiple lines. End the comment with an asterisk and a slash (&ast;/). The opening and terminating characters need not be separated from the text by a space or a line break.
- Begin the comment with -- (two hyphens). Proceed with the text of the comment. This text cannot extend to a new line. End the comment with a line break.

[Via the Oracle website](https://docs.oracle.com/cd/B12037_01/server.101/b10759/sql_elements006.htm). These are the two accepted ways to add an SQL comment, which both work in Boostnote:
![screenshot_20171019_135339](https://user-images.githubusercontent.com/4518410/31769708-07eb9a54-b4d5-11e7-8b56-62cd8524d846.png)

**Comment by initializard** [comment]
MySQL/MariaDB supports comments beginning with a #. https://dev.mysql.com/doc/refman/5.7/en/comments.html

CodeMirror, which BoostNote appears to be using for syntax highlighting, supports these dialects (and others) and even uses `var mime = 'text/x-mariadb';` on their SQL demo page. https://codemirror.net/mode/sql/index.html
 
Observations: 
- Using the language override at the bottom of a snippet does let me change the highlighting to MySQL mode which highlights # comments correctly
- I cannot trigger MySQL mode via the snippet's extension (ie. `.sql` triggers SQL syntax, `.md` triggers Markdown syntax, `.mysql` does not trigger MySQL syntax)
- In Markdown notes, codeblocks with ```mysql  *do* trigger MySQL highlighting properly

Suggestions: 
- Default the SQL mime-type to `text/x-mariadb`, in keeping with CodeMirror's demo
- Make default SQL dialect a configurable option
- Make it possible to set SQL dialects via snippet extensions

**Comment by Flexo013** [comment]
This is now working. `#` style comments are properly highlighted if you preface the code block with `mysql` as opposed to `sql`.
