### ISSUE TITLE
SideNav layout issues

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#980]
on 1beae4403a6f7742c72b71c3447cf904c1e05787 (current master)

The icons stay at the wrong position.
![image](https://user-images.githubusercontent.com/11307908/31585468-09120754-b1fd-11e7-9d25-611d151ac554.png)

The `tags` starts from a new line.
![image](https://user-images.githubusercontent.com/11307908/31585429-39f0f3a4-b1fc-11e7-95fb-560b83f2541f.png)

Are they already confirmed?

**Comment by Samatar26** [comment]
@asmsuechan I don't seem to be having that issue?

**Comment by asmsuechan** [comment]
@Samatar26 Do you use current master or v0.8.16 (edge)?

**Comment by Samatar26** [comment]
@asmsuechan Current master

**Comment by asmsuechan** [comment]
@Samatar26 Could you paste screenshots?

**Comment by Samatar26** [comment]
@asmsuechan 
<img width="1680" alt="screen shot 2017-10-24 at 14 56 02" src="https://user-images.githubusercontent.com/22747985/31947169-9951f520-b8cb-11e7-883b-b5b91c292b93.png">
<img width="1680" alt="screen shot 2017-10-24 at 14 56 37" src="https://user-images.githubusercontent.com/22747985/31947180-9e40cffc-b8cb-11e7-97db-b2f40fd9cd9c.png">

**Comment by asmsuechan** [comment]
Thank you for your cooperation, @Samatar26. I understand when this issue occurs. It occurs when the size is changed to less than 100% (80% or 90%)

**Comment by kazup01** [comment]
I fixed. Thank you for your reporting! https://github.com/BoostIO/Boostnote/pull/1067
