### ISSUE TITLE
Ctrl-J does not work on a pinned note

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#983]
on 1beae4403a6f7742c72b71c3447cf904c1e05787 (current master)

Ctrl-J does not work on a pinned note without errors.

[![https://gyazo.com/56234154581f12c4241b053f09d6f570](https://i.gyazo.com/56234154581f12c4241b053f09d6f570.gif)](https://gyazo.com/56234154581f12c4241b053f09d6f570)

**Comment by mslourens** [comment]
Not reproduceble on Windows 10 (current master):
![boostnote issue 983](https://user-images.githubusercontent.com/1907152/32160860-d362b916-bd53-11e7-8055-c81501b26b0d.gif)
