### ISSUE TITLE
Import From in new folder on Ubuntu causes error, fails

### ISSUE THREAD

**Issue by asciimo** [BoostIO/Boostnote#987]
I created a new folder, selected it, and attempted to import an .md file (File -> Import From -> Plain Text, Markdown...). Nothing happened. I saw this in the console:

main.js:formatted:126966Uncaught TypeError: Cannot read property 'storage' of undefinedvalue @ main.js:formatted:126966emitOne @ events.js:96emit @ events.js:188

![boostnote_error](https://user-images.githubusercontent.com/70218/31625583-5fa85d1c-b25b-11e7-9222-75843d87f55d.png)

**However**, If I choose the default folder, importing an .md file works. If I drag it into the new, empty folder, that works. If I *then* attempt to import into the new folder (which now contains one item), it works.

Boostnote 0.8.14 on Ubuntu 16.04.3

**Comment by asmsuechan** [comment]
Hi, @asciimo. Thank you for opening an issue. Alright, I'll investigate what causes it and fix it.

**Comment by yosmoc** [comment]
It seems same issue as #1057.

**Comment by Flexo013** [comment]
Since #1057 was fixed I will assume this was fixed too.

If it wasn't then feel free to reopen the issue.
