### ISSUE TITLE
Add Better Preview in Edit-Mode

### ISSUE THREAD

**Issue by troxler** [BoostIO/Boostnote#991]
Please add better preview support when in edit-mode.

* Headings should appear larger
* Inline code highlighting does not work in lists, e.g. ``* `thisIsNotHighlightedAsCode` ``
* Highlight code in code blocks, e.g. `` ```js\n function() {}\n ``` ``  
* Format bold, italic, underline accordingly
* Make links clickable (e.g. by longpressing)
* Show referenced images

The goal is to not having to switch to preview mode at all (for most things).

**Comment by asmsuechan** [comment]
Do you mean WYSIWYG thing?
https://github.com/BoostIO/Boostnote/issues/236

**Comment by troxler** [comment]
@asmsuechan It goes in that direction, yes. Sorry, I did not find the duplicate.
