### ISSUE TITLE
[Google Plugin] Please make a notepad.

### ISSUE THREAD

**Issue by simojun** [BoostIO/Boostnote#993]
<img width="1440" alt="2017-10-18 21 19 05" src="https://user-images.githubusercontent.com/7036457/31718216-ff7d97f4-b449-11e7-8a9a-c416d4daf0cd.png">
I want the Google Plugin to have features like memos at the top right of the image.  
Since there is only one page of image's memo, I think it is even better if it can be divided into folders.  
Can someone make it?

**Comment by asmsuechan** [comment]
Hi, @simojun. Sadly, it's very hard to implement on Boostnote because Chrome cannot access local directories by default. However, there are chances to do it on 10hz.

**Comment by Flexo013** [comment]
This can only really be implemented if we have an easy way of syncing notes remotely, in such a way that a Google Chrome plugin can submit more notes or potentially edit existing ones.

I'm closing this issue for now as there has been very little activity and that this will have to wait quite some time on other features.

@simojun Feel free to recreate/reopen this issue if you still want this feature.
