### ISSUE TITLE
Tags list view missing

### ISSUE THREAD

**Issue by russoue** [BoostIO/Boostnote#995]
On the [hackernoon post](https://hackernoon.com/boostnote-boost-your-happiness-productivity-and-creativity-315034efeebe) I see that there is a way to see the list of tags which actually makes the tags usable.  But after installing it I don't see the control to switch between the folder and the tags view.  I have attached a screenshot to show it.

![screen shot 2017-10-19 at 1 20 16 pm](https://user-images.githubusercontent.com/7917803/31792317-7695e89c-b4d0-11e7-86b5-fe0585d59d3f.png)

**Comment by kazup01** [comment]
We will release Tag filtering feature in this week. Wait a moment!

**Comment by russoue** [comment]
Thanks.

**Comment by kazup01** [comment]
Thanks for your waiting! Boostnote v0.8.16 is out. Enjoy!
https://github.com/BoostIO/Boostnote/pull/1027
