### ISSUE TITLE
Application stays running after attempting to close (Windows 10)

### ISSUE THREAD

**Issue by JheeBz** [BoostIO/Boostnote#997]
Screenshot of the application with the developer tools open as requested:

![image](https://user-images.githubusercontent.com/820173/31842662-7fa0a392-b632-11e7-9d77-d5ee32f2085b.png)

Screenshot after closing:

![image](https://user-images.githubusercontent.com/820173/31842683-a07cb7f4-b632-11e7-83d6-93fef432114c.png)

I've tried closing the application in the following ways:
* Clicking the top-right X in Windows
* Hovering over the application in the taskbar and clicking the X in the preview
* Right-clicking the application in the taskbar and clicking 'Close window'

What **does** work is closing is by going through the UI menus Boostnote > Exit.

**Comment by asmsuechan** [comment]
Alright, I'll try to improve it.
related: https://github.com/BoostIO/Boostnote/issues/280

**Comment by JheeBz** [comment]
Great! I tried Ctrl-Q after you suggested it, but it doesn't appear to do anything.

**Comment by AntowaKartowa** [comment]
Same for me, but I always turn off by clicking Boostnote -> Exit

**Comment by petKitsune** [comment]
boostnote 0.8.16
Win7 64x

Same
X minimize to taskbar
Boostnote>Exit works
